snuba/cli/bootstrap.py
Default is 60s, and this is pretty bad when you're trying to quickly
bootstrap, and in no legit scenario should you need a timeout that long.
=> bootstrap: Lower socket timeout

snuba/api.py
Previously it assumed that the query had to reference issues, but with
tag deletes (including both nested and promoted tags) it can affect
almost all columns.
=> fix: use FINAL when there are tag deletes

snuba/util.py, tests/test_util.py
Also add a topK convenience function so that we can pass eg. 'top3'
instead of 'topK(3)'
=> ref: Put function expression logic in one place

snuba/split.py
The query to get the latest event for a group uses a complex
ordering key of [-timestamp, -event_id] but as long as -timestamp
is the first sort key, we should still be able to use this
walk-backwards query splitting technique.
=> feat: Use query splitting for latest-event queries

snuba/api.py, snuba/util.py, tests/test_util.py
Previously we would not catch the case where there were duplicate
project_id IN (...) clauses where the project_id lists were in different
order.
=> fix: dedupe IN conditions

snuba/api.py, snuba/settings_base.py, snuba/util.py, tests/test_util.py
Add `rtime` as a convenience column that can be grouped in the same
way as `time`, but uses the received time of the event rather than the
timestamp time. The `granularity` value applies to rtime in the same way
as time.
=> feat: Group by received time.

snuba/util.py
To avoid slamming 100 row * 15 column results into redis cache.
=> fix: Don't use snuba cache for wide queries

snuba/state.py, snuba/static/dashboard.html, snuba/util.py
Also default the global rate limit to None so that we don't count it.
Global concurrent limit remains in effect.
=> perf: Don't count rates we don't need

snuba/split.py
With the current implementation of the splitter, we have to query
for limit+offset results and do the offset trimming ourselves in
memory. When people request high page numbers, we end up with some
very large datasets in memory, so this caps the offset at which we
will use the splitter.
=> fix: Don't use splitter for high offsets.

tests/test_util.py
This appears like it would work as given. 
`a AND b` = `and(a, b)`
`a OR b` = `or(a, b)`
https://clickhouse.yandex/docs/en/query_language/operators/#logical-and-operator
=> WIP feat: Added tests to ensure boolean functions (or, and) work.

snuba/perf.py
This allows the data to be viewed using the `pstats` CLI for additional detail or used as a basis for comparison between different implementations.
=> perf: Output profile data to file instead of stdout

README.md, snuba/api.py, snuba/cli/bootstrap.py, snuba/cli/cleanup.py, snuba/cli/consumer.py, snuba/cli/migrate.py, snuba/cli/optimize.py, snuba/cli/perf.py, snuba/cli/replacer.py, snuba/clickhouse.py, snuba/datasets/__init__.py, snuba/datasets/events.py, snuba/datasets/factory.py, snuba/datasets/schema.py, snuba/migrate.py, snuba/schemas.py, snuba/settings_base.py, snuba/settings_docker.py, snuba/settings_test.py, tests/base.py, tests/test_api.py
This is the second step to merge https://github.com/getsentry/snuba/pull/294
It introduce the dataset class. The only responsibility of this class in this pull request is to carry the table names for each dataset. Which means that table names are not resolved from settings anymore but from the dataset classes. The dataset class itself is defined in settings.
**Proposed rollout plan**
- update the production settings file by adding the new DATASETS field (without removing anything for backward compatibility.
- we do not pass the table name to scripts in production thus no need to change anything there.
- Rollout only a consumer or a replacer first. It would be backward compatible with api and will use the new code so we can see how it works in prod.
- When we are happy rollout the api
- …
=> feat: Add datasets class boilerplate

snuba/api.py, snuba/cli/bootstrap.py, snuba/cli/cleanup.py, snuba/cli/consumer.py, snuba/cli/migrate.py, snuba/cli/optimize.py, snuba/cli/perf.py, snuba/cli/replacer.py, snuba/clickhouse.py, snuba/datasets/__init__.py, snuba/datasets/events.py, snuba/datasets/schema.py, snuba/migrate.py, snuba/perf.py, snuba/processor.py, snuba/replacer.py, snuba/settings_base.py, snuba/util.py, snuba/writer.py, tests/base.py, tests/test_api.py, tests/test_clickhouse.py, tests/test_perf.py, tests/test_writer.py
This is the third step of the original dataset PR: (https://github.com/getsentry/snuba/pull/294)
This one moves the DDL code into the dataset abstraction introduced in datasets/boilerplate.
Specifically:
- it moves all the functions used to generate the table structure into TableSchema
- it introduces a subclass of TableSchema for the specific table engine we use.
- It moves the columns definition for the datasets table into Events dataset
It still need a follow up to remvoe the direct dependencies on the default DDL that are scattered around the code base. See the dependencies on ALL_COLUMNS constant.
=> feat: Move dataset ddl to the Dataset abstraction

snuba/api.py, snuba/cli/consumer.py, snuba/cli/migrate.py, snuba/cli/replacer.py, snuba/clickhouse.py, snuba/consumer.py, snuba/datasets/__init__.py, snuba/migrate.py, snuba/perf.py, snuba/replacer.py, snuba/util.py, snuba/writer.py, tests/base.py, tests/test_clickhouse.py, tests/test_consumer.py, tests/test_replacer.py, tests/test_util.py, tests/test_writer.py
We need to remove the get_all_columns() function from clickhouse.py Because that is dataset aware and makes sense in a world with one single dataset.
In order to achieve this we need to make a lot of classes dataset aware and drop the assumption that there is one dataset only.
=> feat: Datasets. Start passing dataset around instead of table name

.freight.yml
In theory, this should let us deploy to both old and new infrastructure
at the same time. Worst case, something in Freight errors with this
combination and we revert.
=> Prep for kubernetes deployments

snuba/api.py, snuba/cli/consumer.py, snuba/consumer.py, snuba/datasets/cdc/cdcprocessors.py, snuba/datasets/cdc/groupedmessage.py, snuba/datasets/cdc/groupedmessage_processor.py, snuba/datasets/events.py, snuba/datasets/factory.py, snuba/datasets/schema.py, snuba/processor.py, tests/test_consumer.py, tests/test_groupedmessage.py, tests/test_replacer.py
This is the first CDC dataset.
This is supposed to replicate groupedmessage table from postgres sentry DB.
It uses a ReplacingMergeTree table partitioned on the first seen event (so that we can drop old groups).
=> feat(CDC): Add GroupedMessage dataset

snuba/datasets/factory.py
Prevent the healthcheck endpoint from failing since the table is not there in prod.
=> fix: Disable groupedmessage

snuba/api.py, snuba/datasets/events.py, snuba/datasets/events_processor.py, tests/datasets/test_events.py, tests/test_api.py
The current implementation of issueless events requires the group_id in clickhouse to be 0 (the column is not nullable and making it nullable has a high cost).
On the Sentry side issueless events have group == None. The fact the group_id is 0 is an implementation detail that should not be visible to Sentry, thus we can map this value to NULL on the Snuba interface. This happens both during ingestion and when querying.
=> feat(issueless events): Hide group_id = 0 on events dataset

snuba/datasets/factory.py
Do not merge unless:
1) the groupedmessage remote table is created in prod
or
2) the groupedmessage is added to the DISABLED_DATASET setting
Otherwise healthcheck fails
=> fix: reenable Groupedmessage dataset

snuba/cli/consumer.py
This should make consumer stats more readable in a multi dataset world. 
@JTCunning please let me know whether you have concerns related with dogstatsd. In theory, as long as we are not able to manage multiple datasets with one consumer, the consumer group gives us the same information, but it is harder to decipher and it won't work anymore when a consumer will consume for multiple datasets.
=> feat(cdc): Divide consumer metrics by dataset

snuba/datasets/__init__.py
Just making sure we don't accidentally deploy the HTTP writer again until we are able to identify and fix the encoding issue.
This is a partial revert of 378636c294b7046df7ab0dc98a37b1c5c3241437.
=> fix(writer): Temporarily switch back to native driver batch writer

snuba/settings_base.py
Make the `PREWHERE_KEYS` default to what it is set everywhere else.
=> build(prewhere): Change default prewhere settings

Dockerfile
Setting `PYTHONUNBUFFERED` to `1` tells python to dump things to stdout directly, which usually helps with faster logging.
=> build(docker): Set PYTHONUNBUFFERED=1 in docker image

snuba/api.py, tests/test_api.py
This introduces stubbed subscription endpoints, based on the spec we've discussed previously. Mostly for testing the integration from sentry.
=> feat: Implement stub subcription endpoints

snuba/settings.py
Using `__file__` and manual path logic is deprecated as of Python 3 and this patch updates our settings implementation to follow the new best practices.
=> ref(settings): Use proper and modern py3 importlib

snuba/api.py
Would be handy to have these endpoints available in prod so that my code that calls them doesn't fail.
=> Move stub subscription endpoints out of dev

README.md
SnubaTagStorage is now default in Sentry, we don't need to override this anymore.
=> chore: Remove reference to old tagstore backend

scripts/reset-kafka-offsets.py, snuba/consumers/strict_consumer.py, snuba/utils/streams/kafka.py, tests/utils/streams/test_kafka.py
This was deprecated in [v1.0.0 of confluent-kafka](https://github.com/confluentinc/confluent-kafka-python/releases/tag/v1.0.0).
=> ref(kafka): Remove deprecated `default.topic.config` consumer configuration

snuba/datasets/transactions.py, tests/test_transactions_api.py
Always treat the event_id column as a hex string, like the events
dataset.
This ensures that we get correct results when a query contains a
condition on the event_id column, and we return properly formatted event
IDs to the end user.
=> feat(transactions): Align event_id field to events dataset

snuba/utils/streams/abstract.py, snuba/utils/streams/kafka.py, tests/utils/streams/test_batching.py, tests/utils/streams/test_kafka.py
This adds `seek` and `tell` methods for updating consumer read positions.
This differs from the Confluent API in a few ways:
- `tell` will always return an absolute and valid offset (including during subscription callbacks), unlike the `confluent_kafka.TopicPartition` instances provided to the native callbacks and the native `Consumer.positions()` API
- `seek` works consistently during the subscription callbacks (rebalancing states) as well as during normal consumption
This includes some basic integration tests, but could really use some multi-consumer integration tests.
=> feat(streams): Add `seek`/`tell` to Consumer API

snuba/datasets/discover.py, tests/test_discover_api.py
Fixes the release, dist and user columns. These were not previously
working correctly in the events dataset since they are tags.
Renamed from "sentry:release", "sentry:user" and "sentry:dist" to
"release", "user" and "dist", since this seems more straightforward.
=> fix(discover): Fix promoted tag columns

snuba/migrations/snuba_migrations/events/0010_groupedmessages_onpremise_compatibility.py
For ClickHouse versions 19.x we discovered that atttempting to alter on
a column that was already part of the primary key throws an error, even
if the operation is no-op. We should skip this step if the user already
has the column and it's in the primary key.
=> fix(migrations): Make groupedmessage migration work in ClickHouse 19.x

snuba/datasets/discover.py, tests/fixtures.py, tests/test_discover_api.py
These columns are now present in events and transactions (and errors) so move
them to the common columns so they can be properly accessed by Discover.
=> fix(discover) Move http_method and http_referer to common fields

snuba/query/logical.py
That pass is certainly there by mistake.
=> fix(query): Remove `pass` statement.

snuba/cli/consumer.py, snuba/consumers/consumer_builder.py, snuba/utils/streams/profiler.py
This adds a `ProcessingStrategyProfilerWrapper` and corresponding factory class that sets up a profiler when a processing strategy is instantiated by the stream processor (on assignment) and profiles the execution of the running process until the stream processor is joined (on revocation) or terminated (on error), upon which the profile data is dumped so that it can be later analyzed with the `pstats` tool.
The profiler can be enabled on any running consumer in any environment (development or production) using the `--profile-path` argument.
This does not currently add any additional profiling to subprocesses when using `ParallelTransform` (`--processes` via the command line arguments), though I would like to do this later.
=> perf(streams): Enable profiling processing strategy directly via consumer

snuba/utils/streams/processing.py
See SNUBA-21B. This exception is reraised later and will be logged independently, so downgrading this statement level to reduce noise.
=> ref(streams): Make logger a bit less noisy when terminating

Dockerfile
The `COPY . /usr/src/snuba` layer is pretty much invalidated all the time, and the build step that follows fetches ~50 MB (227 MB unpacked) system packages. This will happen on like, every update commit to a PR which is pretty painful.
It's fixed by first installing requirements.txt before. To my knowledge at least uwsgi and the dogstatsd SO requires those packages to build.
The typical build time right now is a consistent 5m 30s, I'm not actually sure how much faster this is yet because `--cache-from getsentry/snuba:latest` and Cloud Build only pushes to the registry if it's a commit on master.  It probably won't be much faster, because the extra pip noop step is going to take a bit of time and Travis network is reasonably fast. But this is indeed way more respectful to Debian …
=> build: separate requirements.txt for better layering

snuba/cli/migrations.py
Only show the warning about faking migrations if --fake was actually
passed.
=> fix(migrations): Fix --fake migration message

snuba/utils/streams/backends/dummy.py, snuba/utils/streams/backends/kafka.py, snuba/utils/streams/batching.py, snuba/utils/streams/streaming.py, snuba/utils/streams/types.py, tests/utils/streams/backends/mixins.py, tests/utils/streams/backends/test_kafka.py, tests/utils/streams/test_synchronized.py
This makes `next_offset` an attribute of `Message` (rather than it always being arithmetically derived from `offset`) enabling stream backends to support non-sequential offsets.
=> ref(streams): Make `next_offset` an attribute of `Message`

snuba/datasets/storages/processors/replaced_groups.py
I'd like to gather some data about the distribution of FINAL between unmerge and cases where the list of group ids is too long.
=> perf(final) Collect metrics of how often FINAL is caused by unmerge

snuba/query/parser/functions.py, tests/query/parser/test_functions.py
When functions are passed in with literal arguments, they are not necessarily
strings. Fix the function parser to handle different literal types, particularly
when unpacking array join conditions.
=> fix(ast) Handle different types of literals in arrayjoin

Makefile, config/hooks/post-merge
Not needed if snuba devserver is being used, but might be a useful warning for anyone not running the devserver command.
Mostly copied from https://github.com/getsentry/sentry/blob/master/config/hooks/post-merge
=> feat(migrations): Add post merge hook to warn about new migrations

snuba/migrations/runner.py, tests/migrations/test_runner.py
Add the ability to get the status and timestamp of a migration.
This is intended to provide a way to potentially run different code
depending on whether a migration was completed yet or when it was
completed. We did something similar with a hardcoed date for the flattened
tags and contexts optimization in transactions - however in future we should
get the date the migration was actually run rather than assume that it's
completed at the same date in all environments.
=> feat(migrations): Add get_status function

snuba/subscriptions/consumer.py, snuba/subscriptions/worker.py, tests/subscriptions/test_consumer.py, tests/subscriptions/test_worker.py
This moves the time shifting logic (see #981) from the `SubscriptionWorker` to the `TickConsumer` so that it can be more easily shared between different processing strategies (e.g. batched vs. streaming.)
=> ref(subscriptions): Move time shift from worker to consumer

snuba/cli/subscriptions.py
Fixes regression introduced in #1323
=> fix(subscriptions): Move `time_shift` constructor parameter from worker to consumer

.github/workflows/release.yml
Mostly a port of getsentry/sentry#20796 along with adding a name for aesthetics and removing the obsolete `sleep 10` step.
=> ci(release): Simplify and align with Sentry release

snuba/perf.py, snuba/subscriptions/codecs.py, snuba/utils/streams/backends/kafka.py, snuba/utils/streams/synchronized.py, snuba/web/views.py, tests/datasets/test_errors_replacer.py, tests/test_consumer.py, tests/test_replacer.py, tests/utils/streams/backends/test_kafka.py, tests/utils/streams/test_synchronized.py
This removes the performance hit caused by exposing `key`, `value`, and `headers` as immutable properties while retaining the immutability of the data structure.
=> perf(streams): Convert `KafkaPayload` to `NamedTuple`

snuba/datasets/cdc/message_filters.py
Consumers that use this filter spend a substantial amount of time waiting on `socket.send` for these individual metrics.
The filtration ratio for these consumers is a useful metric, but we will need to find a different method of reporting these metrics moving forward that aggregates the data in-process rather than sending each metric individually. (My hope is to add this in the future to the streaming package so that this is automatically instrumented on the step.)
In the meantime, this will allow us to get a better sense of the consumer performance without the overhead from recording this high density metric.
=> perf(cdc): Remove dropped message metric from filter

snuba/web/split.py
Three of the four metrics we collected around discrepancies in managing the legacy query on query splitter turned out to be expected. So removing that log and the related dependency.
The fourth seems fine (actually it was a bug in the legacy system) but I need to do one last verification, thus logging the stack trace.
=> feat(ast) Remove dependency on legacy query from splitter

snuba/datasets/cdc/message_filters.py, tests/datasets/test_groupassignee.py, tests/test_groupedmessage.py
Removing messages that are not directed at a specific table when filtering the CDC stream should prevent sending a large amount of messages to the processing pool that are otherwise discarded at that stage. Specifically when dealing the the parallel transformation, this will remove begin and commit events that have had all of their contents filtered out since they do not affect relevant tables. I suspect we send a lot of these transactional events due to our use of autocommit creating implicit single change transactions.
=> perf(cdc): Filter out all non-change messages when filtering by table name

snuba/datasets/storages/errors.py, snuba/migrations/migrate.py, tests/datasets/test_errors_replacer.py
This stops migrating the errors table via the old migration system,
as we will be rebuilding this table soon. Keeping migrations in both
the old and the new system in sync is something I want to avoid doing
in this case. This table is currently unused.
It also removes org_id from the required_column list since this column
will be dropped in the new version of the table.
=> feat(errors): Simplify schema, turn off errors migrations via old system

snuba/datasets/storages/errors.py
Forgot to remove the old errors_migration function earlier, it's not
being used anywhere.
=> ref: Remove unused function

snuba/datasets/spans_processor.py
Apparently we may have cases where the parent span id of a transaction is either present and None or present with an invalid type. 
This accounts for those cases.
=> fix(spans) Fix nullability in parent span id

snuba/datasets/transactions_processor.py, tests/datasets/test_transaction_processor.py
When Relay validates a measurement, Relay will preserve the key, `null` the value, and attach a processing error. 
Thus, Snuba may receive measurement values that are `null`.
=> fix(measurements): Ignore measurement values that may be null

snuba/datasets/errors_replacer.py, snuba/datasets/storages/errors.py, snuba/datasets/storages/events.py, snuba/replacer.py, snuba/replacers/replacer_processor.py, tests/datasets/test_errors_replacer.py, tests/test_replacer.py
Not sure if there's a use case for this that I'm not aware of, but
we never currently perform replacements that read rows from one table
and replace them in another. This removes the ability to pass a
different write and read schema to a replacer processor, which may cause
problems since the replacer assumes the same columns are present in
each.
=> ref: Replacements work on a single table

snuba/datasets/transactions_processor.py, tests/datasets/test_transaction_processor.py
Continuation of https://github.com/getsentry/snuba/pull/1364
----
I recently learned from @untitaker that Relay may not guarantee that the expected shape is non-nullable.
=> fix(measurements): Ignore measurement values that are not consistent

snuba/datasets/storages/transactions.py
Remove the parts of the transactions schema that relates to the old
migration system.
Depends on the fix to nested column type modifiers in https://github.com/getsentry/snuba/pull/1368
Also removes BEGINNING_OF_TIME from the flattened contexts optimizations
since we are well past the retention period from when these started
being filled.
=> ref: Simplify transactions schema

snuba/datasets/entities/discover.py
The `search_message` column is never being populated, we should remove
it from the Discover data model.
=> ref(discover): Remove search_message from Discover data model

snuba/clickhouse/columns.py, snuba/datasets/storages/events_common.py, snuba/datasets/storages/groupassignees.py, snuba/datasets/storages/groupedmessages.py, snuba/datasets/storages/outcomes.py, snuba/datasets/storages/spans.py, tests/query/validation/test_signature.py
Replace NullableOld with Nullable everywhere. NullableOld was only
needed to preserve the behavior of the old migration system where
Nullable was treated as a column type modifier.
=> ref: Remove NullableOld

snuba/datasets/storages/transactions.py
This was not actually doing anything in discover since the timestamp column at that point in the query in the old query representation is "timestamp" and not "finish_ts".
=> feat(ast) Remove Flattened Tags from transactions

tests/base.py, tests/clusters/test_cluster.py, tests/conftest.py, tests/datasets/test_factory.py, tests/migrations/test_runner.py, tests/subscriptions/test_worker.py
Thi ensures that migrations are run before any tests, not just those
that inherit from the BaseTest class. This should enable us to simplify
the way we write tests and deprecate BaseTest in future.
=> test: Ensure migrations are run before all tests

snuba/query/processors/prewhere.py, tests/query/processors/test_prewhere.py
=> feat(ast) Legacy query demolition step 8: Remove legacy query path from prewhere processor

snuba/datasets/storages/events_column_processor.py, tests/query/processors/test_events_column_processor.py, tests/test_api.py
This removes the last place where we read from the search_message column.
A query for `message` in the events dataset now simply translates to `message`
instead of `coalesce(search_message, message)`. Since `search_message` is
always Null, the result doesn't change.
=> feat: Stop reading from search_message

tests/base.py, tests/conftest.py, tests/datasets/test_session_processor.py, tests/datasets/test_transaction_processor.py, tests/state/test_rate_limit.py, tests/subscriptions/test_codecs.py, tests/subscriptions/test_scheduler.py, tests/test_util.py
Most of what BaseTest does has now being moved into either
pytest_configure or BaseDatasetTest, we no longer need this class.
=> test: Kill BaseTest

tests/base.py, tests/fixtures.py
Previously only the event data was returned by get_raw_event. Now we
return the entire raw event. This makes `get_raw_event` more reusable.
It is also consistent with how `get_raw_transaction` behaves.
=> test: get_raw_event provides the entire event not just event data

tests/state/test_state.py, tests/test_cleanup.py, tests/test_clickhouse.py, tests/test_optimize.py, tests/test_writer.py
Updates a number of tests to not inherit from BaseEventsTest.
We should move away from needing to have a base class in order to
test a specific dataset, and eventually remove BaseEventsTest.
=> test: Stop using BaseEventsTest

tests/base.py, tests/test_api.py, tests/test_discover_api.py
Our API tests should not assume that the dataset under test is the
events dataset. Some time ago there was only one dataset that could be
queried, but this is no longer the case.
=> test: BaseApiTest does not extend BaseEventsTest

tests/datasets/test_discover.py
This test no longer uses BaseDatasetTest since it's not required. Also
removes an unused method.
=> test(discover): Simplify Discover test

tests/base.py, tests/datasets/test_errors_replacer.py, tests/datasets/test_events.py, tests/datasets/test_events_processor.py, tests/subscriptions/__init__.py, tests/test_consumer.py, tests/test_perf.py, tests/test_replacer.py
BaseEventsTest will be removed soon, update all remaining tests that used
this class to BaseDatasetTest instead.
=> test: Update all tests to use BaseDatasetTest instead of BaseEventsTest

tests/base.py, tests/datasets/cdc/test_groupassignee.py, tests/datasets/cdc/test_groupedmessage.py, tests/datasets/test_errors_replacer.py, tests/datasets/test_events.py, tests/subscriptions/__init__.py, tests/test_api.py, tests/test_cleanup.py, tests/test_optimize.py, tests/test_replacer.py
Removes the write_rows method from BaseDatasetTest.
This simplifies BaseDatasetTest which now only provides two methods:
`write_unprocessed_events` which processes and writes raw events, and
`write_processed_messages` which writes processed insert or replacement
messages.
=> test: Remove BaseDatasetTest.write_rows()

tests/base.py, tests/test_cleanup.py
We should not hardcode self.database in tests, this information should always
come from the cluster since it is technically possible for different clusters
to be on different databases now.
=> test: Get database from cluster in tests

snuba/datasets/spans_processor.py, tests/datasets/test_spans_processor.py
We keep running into cases where span ids and parent span ids are missing.
The transaction processor still discards those events, so we should do the same for spans.
=> fix(spans) Discard events with malformed span_id like the transaction processor does

snuba/datasets/spans_processor.py, tests/datasets/test_spans_processor.py
The root span tags are already present in the transactions table, there is no need to duplicate them here.
=> feat(spans) Remove transaction tags from spans

tests/base.py, tests/datasets/cdc/test_groupassignee.py, tests/datasets/cdc/test_groupedmessage.py, tests/datasets/test_errors_replacer.py, tests/datasets/test_events.py, tests/datasets/test_events_processor.py, tests/helpers.py, tests/subscriptions/__init__.py, tests/test_cleanup.py, tests/test_discover_api.py, tests/test_optimize.py, tests/test_replacer.py
Extract write_processed_messages and write_unprocessed_events from
BaseDatasetTest to tests.helpers so that we can use these methods
outside of dataset specific tests. Refactor all tests to no longer use
BaseDatasetTest.
=> test: Extract helpers

tests/base.py, tests/test_api.py, tests/test_outcomes_api.py, tests/test_transactions_api.py
Update BaseApiTest to no longer inherit from BaseDatasetTest. We can now
completely remove BaseDatasetTest.
=> test: Remove BaseDatasetTest

snuba/utils/streams/processing/strategies/streaming/transform.py
The default multiprocessing context [differs between *nix and macOS](https://docs.python.org/3.8/library/multiprocessing.html#contexts-and-start-methods): macOS uses `spawn`, which starts a fresh interpreter for each subprocess, while *nix uses `fork`, which inherits resources from the parent process — including signal handlers.
When the stream processor encounters an error, it attempts to shut down immediately (abandoning all in-process work) by [terminating the processing strategy](https://github.com/getsentry/snuba/blob/1e426a650966bd37279a2646502da5fba96bbf42/snuba/utils/streams/processing/processor.py#L107-L121), which in the case of a streaming strategy cascades throughout all of the processing steps. For a parallel transform, this means [terminating the process …
=> fix(streams): Avoid problematic fork usage with parallel transform worker pool

snuba/datasets/entities/transactions.py
Now that Discover is using the transactions entity, we need to support
properly processing any "timestamp" field in the query when we are using
the transactions entity since this field is referred to as "timestamp"
in Discover and not it's internal name "finish_ts".
I ran the Sentry test `SnubaEventStorageTest::test_transaction_get_next_prev_event_id`
locally and it seems to fix the issue.
=> fix(discover): Fix processing timestamp column in transactions entity

snuba/datasets/entities/discover.py, snuba/datasets/entities/events.py, snuba/datasets/storages/events_common.py
This aligns the columns of events and Discover so that the Discover
fields "release", "user" and "dist" are now supported on the Events
entity.
Ideally, these will be used by Sentry instead of `tags[sentry:release]`,
`tags[sentry:user]` and `tags[sentry:dist]` in the API, but both will
remain supported.
Note that this mapping won't be required when we switch to the errors
entity since "release", "user" and "dist" are already the same as the
underlying column names in errors.
The only remaining differences now between the Discover and Events
entity should relate to Null mapping of fields that are only present in
transactions.
=> feat: Align the Events and Discover column mapping

.github/workflows/release.yml
See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> ci(release): Don't use set-env in GHA

snuba/consumers/consumer_builder.py
Seems as though we don't do a whole lot of retrying. Not sure when this changed, but it was prior to or with the 1.5.0 release which we use.
References confluentinc/confluent-kafka-python@18e1e737d2ec6dd4b0dc433df5b4c7874cf7cdac
=> fix(consumer): Update arbitrarily renamed `KafkaError` in commit retry policy

snuba/datasets/discover.py, snuba/datasets/entities/discover.py, tests/datasets/test_discover.py
This PR updates the select_entity function on the Discover dataset
to check for the presence of the isHandled and notHandled custom
functions. If they are present, we should attempt to use the Events
entity instead of the Discover entity.
If the Discover entity is still being picked (for example if other
transactions only columns are also present in the query), these functions
are mapped to Null.
This is equivalent to how we handle apdex and failure_rate in entity
selection and mapping.
This fixes SNUBA-22Q
=> fix(discover): Handle custom events functions in Discover

tests/conftest.py
This fixes a bug introduced in
https://github.com/getsentry/snuba/pull/1382, whereby the snuba_test
database is not created properly before running tests. We need to use
the default database in order to create other databases required for tests.
=> test: Fix creating test database

snuba/datasets/errors_replacer.py, snuba/datasets/storages/errors.py, snuba/datasets/storages/events.py, tests/datasets/test_errors_replacer.py
This removes all special handling of promoted tags in the errors replacer
and instead uses the values from tags.key and tags.value like our
unpromoted tags.
Unlike in the events storage, most of our promoted tags are low cardinality
columns now. This is causing a bug in ClickHouse -
https://github.com/ClickHouse/ClickHouse/issues/16171.
Our workaround for now is to not use any of our promoted columns for
errors replacements; event replacements are unchanged.
This fixes SNUBA-22N in Sentry.
=> feat: Remove special handling of promoted tags in errors replacer

snuba/datasets/entities/discover.py, snuba/datasets/entities/events.py, snuba/datasets/entities/transactions.py
Prevent custom mappers from being passed to EventEntity and
TransactionsEntity on initialization.
=> ref: Prevent arguments being passed to entities

snuba/settings.py, snuba/web/split.py, tests/test_split.py
We are applying the column splitter on queries that reference only one column on top of the minimal query.
This is not gaining us much.
So setting up a minimal number of columns to be referenced in the query to apply the splitter.
=> fix(col splitter): Set a minimal threshold of columns to be referenced in the query to apply column splitter

snuba/datasets/storages/__init__.py, snuba/datasets/storages/errors.py, snuba/datasets/storages/errors_common.py, snuba/datasets/storages/errors_ro.py, snuba/datasets/storages/factory.py
The errors readonly storage is the errors equivalent of the events
readonly storage, and will be used in the same scenarios where events_ro
is now - i.e. when `enable_events_readonly_table` is set and the request
is not required to be "consistent", allowing us to use other replicas than
the first one.
The errors_dist_ro table is already being created through the migration
system.
=> feat: Add errors_ro storage

snuba/migrations/operations.py, tests/migrations/test_operations.py
We should use `DROP INDEX IF EXISTS` instead of bare `DROP INDEX` so
that we can reverse migrations even if an index wasn't successfully
added. This came up recently in the migration 0008_transactions_add_timestamp_index.
If the original AddIndex command failed the migration will be marked "IN
PROGRESS" but not have the index present. The user would be stuck and
unable to run either the forwards or backwards migrations.
=> feat(migrations): DropIndex uses IF EXISTS operator

snuba/query/parser/__init__.py
We can skip checking if exp is a column - if a match on the arrayjoin
function exists, this will never be the case.
=> ref: Simplify _validate_arrayjoin

snuba/datasets/storages/errors_common.py
Like Transactions and Discover, we also need to perform event_id column
processing for errors since these are also stored as UUIDs.
=> feat(errors): Add event ID column processing

snuba/cli/devserver.py
Fixing a few settings so that all the pins align correctly. We also have to explicitly specify `--commit-log-topic` on the transaction consumer because it's not defined on storage.
=> Fix transactions subscriptions in local dev.

snuba/clickhouse/query.py, snuba/query/__init__.py, snuba/query/composite.py, snuba/query/logical.py, tests/query/parser/test_query.py, tests/query/snql/test_query.py
While in general having query equality is useful, the __eq__ function provides
no insight into what part of the queries is not equal. Add a new equals function
that returns a useful error message and have the __eq__ function use that.
=> fix(query) Abstract query equality for tests

.github/workflows/release.yml
This fixes the recurring failure when merging the release branch to master when releasing Snuba. The failure happens because we have branch protection enabled and the default `github.token` is not an admin on the repo to by-pass these checks. This token was already added on Sentry and Relay repositories so this was not an issue there.
=> fix(release): Add missing GITHUB_API_TOKEN variable to craft/publish

snuba/clickhouse/formatter/query.py, snuba/clickhouse/query.py, snuba/query/__init__.py, snuba/query/composite.py, snuba/query/logical.py, snuba/query/parser/__init__.py, tests/clickhouse/test_query_data.py, tests/clickhouse/test_query_format.py
Rather than executing the limitby clause directly as it is provided by
the user on ClickHouse, we now parse limitby as an expression and apply
the same transformations that we do to the rest of the query in
`Query.transform_expressions()`
The immediate motivation for this is so that aliases that are mangled before
being run on ClickHouse then replaced later will be properly transformed
if they are being referenced in the limitby clause.
=> feat: Parse and transform limit by clause

snuba/clickhouse/formatter/query.py, tests/clickhouse/test_query_data.py, tests/clickhouse/test_query_format.py, tests/test_discover_api.py
If a user selects timestamp and last_seen() (max(timestamp)), it causes
an error. This seems to be isolated to prod, but removing these brackets
were suggested as a fix. Going to try this out and see if it works.
=> fix(discover) Attempt to fix max(timestamp) + timestamp issue

snuba/clickhouse/formatter/query.py, snuba/query/data_source/visitor.py
I noticed we are running into quite some cases where we need to process the tree of data sources in a composite query.
One of the cases was formatting.
Initially I could not add a visitor because the data sources were not defined in the same module. That is still true, though we can do something similar by encapsulating the exhaustive `isinstance` checks in a class that gets extended, so this is not spread around the code base and we can still rely on a visitor style abstraction.
=> feat(joins) Support composite queries in db_query step 1: Add a visitor for data sources.

tests/pipeline/test_pipeline_delegator.py, tests/utils/test_threaded_function_delegator.py
These tests get stuck occasionally. Set a timeout when using
threading.Condition.wait() to ensure they do not hang forever.
=> test: Always set timeout when waiting for thread conditions

snuba/datasets/errors_processor.py, snuba/datasets/events_processor.py, snuba/datasets/events_processor_base.py, tests/datasets/test_events_processor.py
The columns `culprit`, `type` and `title` are nullable in the events
dataset but not in errors. Their default in errors should be empty
string and not None.
Also moves extracting the primary hash out of the base events processor
as this step is only relevant for events now.
=> fix(errors): Fix default values of non nullable columns

snuba/datasets/storages/transactions.py, snuba/query/matchers.py, snuba/query/processors/uuid_column_processor.py, snuba/query/snql/parser.py, tests/query/processors/test_uuid_column_processor.py, tests/query/snql/test_query.py, tests/test_transactions_api.py
First pass at trying to optimize queries with UUID columns. Right now the simple
case is to target conditions that contain UUID columns, and do a direct
comparison instead of converting the column to a string.
=> feat(ast) Add a uuid optimizer for conditions with UUID columns

snuba/datasets/plans/query_plan.py, snuba/web/query.py, tests/web/test_count_columns.py
Makes change to the visitor that extracts stats from a composite query to collect also final and sampling rate so that we can pass a ComposteQuery to web/query.py methods.
=> feat(join) Allow CompositeQuery in web/query

snuba/datasets/storages/errors_common.py, snuba/migrations/groups.py, snuba/migrations/snuba_migrations/events/0012_errors_make_level_nullable.py
The `level` column should be a nullable string because it is a promoted
tag. Non nullable promoted tags are problematic because the insertion will
fail if the tag is absent in the payload. If we attempted to use empty string
as a default instead, it would cause inconsistent query results.
Migration statement:
`ALTER TABLE errors_local MODIFY COLUMN level LowCardinality(Nullable(String));`
=> feat(errors): Make `level` nullable

snuba/datasets/storages/transactions.py
Since we are now optimizing conditions on UUIDs (https://github.com/getsentry/snuba/pull/1505),
we can now safely run the column splitter on the transactions storage,
without the potential performance regressions related to manipulating event_ids.
=> perf(transactions): Turn on column splitter

snuba/datasets/storages/transactions.py
This reverts commit c035fe6f2aec554459f8a4d95e138a209e48289d.
This caused problems when there are aggregations (but no group by clause) in the query.
In that case the splitter should be skipped but is not. For some reason, this only commonly
happens in production on the transactions dataset.
Reverting first since fixing these turned out to be more involved than I originally thought.
=> Revert "perf(transactions): Turn on column splitter (#1513)"

snuba/query/processors/uuid_column_processor.py, tests/query/processors/test_uuid_column_processor.py, tests/test_discover_api.py
If the client passes in an invalid event id, then the parser was leaving the
event id unchanged but still stripping the replaceAll(... from the left side.
This would cause errors in Clickhouse. Instead, if the event id is not a valid
UUID, bail out of the processor entirely and leave the expression unchanged.
=> fix(transactions) Fix query error in uuid processor

snuba/datasets/entities/discover.py, snuba/pipeline/pipeline_delegator.py
This uses the pipeline delegator to simultaneously run queries to the
Discover entity on the Discover merge table, in addition to the main
events table. This does not yet change any of the results being returned
to users.
The percentage of queries that will also run on the alternate storage
can be specified via the "discover_query_percentage" configuration. The
default is 0.
If more than one storage has been run, we compare the result data from
both storages and increment a metric recording whether they are the same
or different.
=> feat(discover): Add the ability to run queries on merge table

snuba/datasets/entities/discover.py, snuba/pipeline/pipeline_delegator.py, snuba/utils/threaded_function_delegator.py, tests/pipeline/test_pipeline_delegator.py, tests/utils/test_threaded_function_delegator.py
ThreadedFunctionDelegator records the time taken to execute each
callable and provides the value to the callback function if provided.
The purpose of this change is to make it easier to test the performance
impact of various changes before rolling them out.
=> feat(snuplicator): Record time taken to execute each callable

snuba/query/parser/expressions.py, snuba/query/snql/expression_visitor.py, snuba/query/snql/parser.py, tests/conftest.py, tests/query/snql/test_query.py, tests/test_transactions_api.py
Allow any character in quotes, including escaped quotes (\'). The one character
that still doesn't work is the newline character. That will require discussion
with product since it's not clear if it can be handled by the regex directly.
=> fix(snql) Allow arbitrary characters in quotes

snuba/settings_docker.py
Follow up to getsentry/onpremise#754
=> feat(settings): Respect SENTRY_EVENT_RETENTION_DAYS when using docker

snuba/datasets/storages/sessions.py, snuba/migrations/groups.py, snuba/migrations/snuba_migrations/sessions/0002_sessions_aggregates.py
This adds a new `quantity` column to the raw set, and `X_preaggr` columns to the
materialized view table.
Also adds the `user_agent` and `os` columns to both which will be normalized and
provided at a later point by relay.
=> feat: Add schema support for pre-aggregated sessions (1/4)

snuba/migrations/groups.py, snuba/migrations/snuba_migrations/discover/0003_discover_fix_user_column.py
This fixes an error in the original Discover table definition - the
"user" column should be a regular string (not low cardinality string) -
in order to match the type of the column in the underlying errors and
transactions tables.
=> fix(discover): The 'user' column should not be low cardinality

.github/workflows/release.yml
Switches to using getsentry/action-prepare-release for common steps and removes the dry run option from the prepare stage as it prevents us from testing the publish step. Prepare step should be safe anyways and can be skipped with the `skip-prepare` input.
Related: https://app.asana.com/0/1198192131329257/1198192131329301, https://app.asana.com/0/1198192131329257/1198192573081717
=> ci(release): Use action-prepare-release and rework dry-run

snuba/datasets/entities/sessions.py, tests/datasets/test_sessions_processing.py
The next step after #1455.
This adds query support which combines both the old `count` based and the new `sum` based columns.
This also adds new quantiles and `avg` for durations.
=> feat: Add query support for pre-aggregated sessions (2/4)

snuba/query/snql/parser.py, tests/conftest.py, tests/query/snql/test_query.py, tests/test_discover_api.py
Have the discover tests use SnQL. This exposed a few missing cases, particularly
ARRAY JOIN. Add support for the ARRAY JOIN clause. The current language also
supports an implicit transformation on array columns, converting conditions to
be arrayExists or arrayAll functions if the condition is on an array column.
This is ambigious and hidden behaviour that we are trying to avoid in SnQL.
Instead, add a special function the client can use as syntactic sugar for the
same condition, forcing the client to explicitly declare when they are using a
condition on an array column. There are two discover tests that rely on this
behaviour, so xfail them in snql for now.
=> feat(snql) Discover tests using SnQL

snuba/datasets/entities/discover.py
Add some basic Sentry logging when results received via the Discover
merge table do not exactly match those from the events table.
=> feat: Add Sentry logging when Discover results differ

snuba/datasets/entities/discover.py, tests/conftest.py, tests/datasets/test_transaction_translations.py, tests/test_discover_api.py
The test is a little overcomplicated since I took it from a production query, but the issue here is that if a user sends a query with an actual None in it (in the test case it's a parameter of the `if` function) we will incorrectly translate the entire expression to NULL, even if the columns in the expression match the table selected.
When we translate a column to NULL because it's not available in the chosen table, translate it to the identity function. Then, the function translators can look for the identity function to determine whether they should also be translated to NULL.
=> fix(discover) Use identity function as a marker for NULLed columns

snuba/datasets/entity.py, snuba/query/data_source/join.py, snuba/query/data_source/simple.py, snuba/query/parser/__init__.py, snuba/query/snql/joins.py, snuba/query/snql/parser.py, tests/conftest.py, tests/query/snql/test_invalid_queries.py, tests/query/snql/test_joins.py, tests/query/snql/test_query.py
Add support for join clauses in the MATCH clause, as well as support for sub
queries in the match clause. This required writing a complicated linked list
algorithm for the join clause, to ensure the joins were possible and to order
them correctly for clickhouse. It also required changing the post process query
functions to support composite and logical queries.
I know it seems like a big PR but it's 60% tests. Also I may refuse to make changes 
if I can't preserve the exact addition/deletion counts of this PR.
=> Add join/subquery support to MATCH clause

CODEOWNERS
Based on https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners#example-of-a-codeowners-file, the order matters and **the last line that matches** takes precedense. That makes all definitions above the `*` catch-all definition useless. This PR fixes that.
=> meta: Fix CODEOWNERS

scripts/bump-version.sh, scripts/post-release.sh, setup.py
Today we needed to release a patch release right after a CalVer release. Since there is no hard-coded version in Snuba anywhere, Craft got confused when it ran the pre-release script as it did not change anything (it only updates the license date which limits this to 1 release per day). I think it is good practice to hard-code the version in at least `setup.py` even if it is not referenced by anything yet. This also resolves our problem with releases.
=> build: Add VERSION and related bump scripts

snuba/datasets/entities/discover.py
This is a small tweak to the temporary Discover logging. We now send the
data for the row that is actually different to Sentry instead of just
the first one.
=> feat: Tweak Sentry logging for Discover

snuba/clickhouse/translators/snuba/mapping.py, snuba/query/snql/parser.py, tests/conftest.py, tests/datasets/test_transaction_translations.py, tests/test_discover_api.py
This actually fixes two bugs. The first is that we were incorrectly caching
Literals with equal int and float values as the same thing. This would break
the subsequent Clickhouse query since the typing wouldn't match.
The second is that the SnQL parser was not correctly handling the HAVING clause.
=> fix(discover) Literal caching is not typed

.dockerignore
Snuba `scripts` are sometimes used in production, we want to include
them in our built Docker image.
=> feat: Remove scripts from dockerignore

requirements.txt, snuba/cli/multistorage_consumer.py, snuba/clickhouse/http.py, snuba/consumer.py, tests/test_consumer.py
This implements the minimum feature set necessary to support writing to multiple storages from a single consumer. It has several limitations and drawbacks (see comments in entrypoint for specific examples) and provides virtually no safety net to the end user to prevent them from running the consumer in a fashion that may cause problems in the short term (i.e. running a single storage and multiple storage consumer for the same storage simultaneously using the same consumer group) or long term (running specific sets of storages together that may not be supported in the future.) Caveat emptor.
=> feat(consumer): Add support for writing to multiple storages from single consumer

snuba/datasets/storages/errors.py, snuba/datasets/storages/events.py, snuba/datasets/storages/groupassignees.py, snuba/datasets/storages/groupedmessages.py, snuba/datasets/storages/outcomes.py, snuba/datasets/storages/querylog.py, snuba/datasets/storages/sessions.py, snuba/datasets/storages/spans.py, snuba/datasets/storages/transactions.py, snuba/datasets/table_storage.py, snuba/settings.py
This addresses the immediate issues raised in https://github.com/getsentry/snuba/pull/1551#discussion_r544642804 that prevented the multistorage consumer from being able to be used in our production configuration.
=> ref(consumer): Add the ability to override storage topic names through settings

snuba/datasets/storages/spans.py, snuba/datasets/storages/transactions.py
This matches the production configuration for these storages and ensures they are set (and/or able to be overridden) in all environments.
=> ref(storages): Add commit log to spans and transactions

snuba/datasets/entities/discover.py, snuba/pipeline/pipeline_delegator.py, tests/pipeline/test_pipeline_delegator.py
Add the Sentry referrer to Snuplicator logging to help diagnose the underlying
cause of discrepancies.
=> feat: Add referrer to Snuplicator logging

snuba/query/snql/parser.py, tests/query/snql/test_invalid_queries.py, tests/query/snql/test_query.py
In JOIN queries, ensure the columns are qualified with a valid entity alias,
and separate out that alias.
=> fix(snql) Qualify columns in JOIN queries

snuba/datasets/plans/query_plan.py, snuba/datasets/plans/single_storage.py, snuba/pipeline/composite.py, snuba/pipeline/query_pipeline.py, snuba/pipeline/simple_pipeline.py, tests/pipeline/test_composite_planner.py, tests/query/processors/test_arrayjoin_optimizer.py, tests/query/test_query_ast.py
When we execute join queries, each entity provides a query plan builder, this picks a storage and build a QueryPlan for that subquery. 
If an entity has multiple viable storages for a query on different StorageSet, the join planner needs to know about all of them (ranked from best to worst) to ensure we pick storages on the same storage set for all entities. 
If that does not happen the query would fail because the storages may be on different clusters. 
This changes the interface of the QueryPlanBuilder to build multiple plans and either return the best or return the whole list. Single query pipelines use the best directly, the join planner has access to all viable options.
=> feat(joins) Ensure we always pick storages in the same storageSet step 1: Allow the QueryPlanBuilder to return more than one plan

snuba/query/snql/parser.py, tests/query/snql/test_query.py
There is an issue with mangling aliases in subqueries. An outer query is
expecting its columns to match the select statement from the inner query.
I assumed this meant the outer query should match the SelectedExpression,
but that isn't correct in a subquery since the SelectedExpression is
essentially ignored. Instead, the outer query columns need to match the
aliases of the inner query. Since those aliases get mangled, we have to also
mangle the column names of the outer query to match that mangling.
=> fix(snql) Mangle aliases in subqueries

snuba/cli/optimize.py
This information is now provided by the cluster configuration and cannot
be overridden.
=> fix(optimize): Remove the "database" option from the optimize CLI

snuba/migrations/backfill_errors.py, snuba/migrations/operations.py, tests/fixtures.py, tests/migrations/test_backfill_errors.py
The backfill script now runs an INSERT INTO SELECT statement on
each partition to copy data from the events to errors table.
Once the migration is done OPTIMIZE TABLE will be run on each
part if the ClickHouse installation is single node. For distributed
tables, this should be performed manually on each node.
=> feat(backfill): Update backfill to use insert into select

snuba/pipeline/composite.py, tests/pipeline/test_composite_planner.py
This step was missing, the composite query planner was not triggering the two composite subquery generator.
This PR adds the semantically equivalent conditions and the generation of subqueries in the composite planner.
The test is updated because the query provided to the planner before was incorrect as it already contained subqueries.
=> feat(join) Plug the subquery generator into the query planner

snuba/request/__init__.py, snuba/request/schema.py, snuba/request/validation.py, snuba/web/query.py, snuba/web/views.py, tests/conftest.py, tests/datasets/test_events_processing.py, tests/datasets/test_querylog_processor.py, tests/datasets/test_sessions_processing.py, tests/pipeline/test_pipeline_delegator.py, tests/query/processors/test_arrayjoin_optimizer.py, tests/test_outcomes_api.py, tests/web/test_transform_names.py
When a SnQL query is made, the extension fields should already be part of the
query so we don't need the extensions parsed explicitly. Also remove the
timeseries extension call from the query file, since from_date and to_date
were only being used to populate num_days, which is not used anywhere.
I tested this locally with the querylog consumer and the sentry tests and saw
no errors.
=> fix(snql) Remove extensions from SnQL queries

snuba/datasets/entities/discover.py
The user column should return None instead of an empty string. This aligns the user
field in the Discover entity with events, errors and transactions. The column is
nullable in events, and the same column mapping is already being performed on errors
and transactions entities.
=> fix(discover): Fix user column on Discover entity

snuba/datasets/entities/discover.py, snuba/datasets/entities/errors.py, snuba/datasets/entities/events.py
The events entity now runs some queries simultaneously on the errors storage
using the pipieline delegator. The purpose of this is to start testing and
comparing results to events on the two storages.
The percentage of errors that are run on both storages is determined by the
`errors_query_percentage` config. Default is 0.
=> feat(errors): Connect the events entity to errors storage

snuba/datasets/sessions_processor.py, tests/datasets/test_session_processor.py
PR https://github.com/getsentry/snuba/pull/1455 added the quantity column to the sessions raw table with a DEFAULT = 1.
Turns out that on distributed tables we cannot trust the default value. When querying the distributed table the quantity is still 0.
This makes it impossible to apply the migration in https://github.com/getsentry/snuba/pull/1487 as it relies on the quantity to be 1 for individual sessions. 
In order to fix that we need to manually set the quantity value to `1` instead of leaving it empty.
=> fix(sessions) Explicitly set quantity to 1 in the sessions consumer

snuba/datasets/entities/events.py
It's possible to receive an empty results set back, which can error out. It's
still an open question as to why the empty set is returned in the first place.
=> fix(errors) Fix empty results bug

snuba/replacer.py
The database name should be referenced from the cluster configuration, not hardcoded to "default".
=> fix(optimize): Do not hardcode "default" as the database name

.github/workflows/release.yml
We need this for automated version numbers
=> ci(release): Enable the CalVer flag for release

snuba/clickhouse/processors.py, snuba/pipeline/composite.py, tests/pipeline/test_composite_planner.py
Introduces an abstractions to encapsulates Clickhouse query optimizations done before the execution of the strategy.
This is not strictly needed (as instead it was for simple query processors) as those are defined by storages and entities. 
Composite processors are not provided by datasets. They will instead be the same for all datasets, though I can see this changing the more join optimizations we add. Adding an abstraction for such processing logic will thus ensure these optimization will be designed in a modular way.
=> feat(joins) Introduce Composite Query Processors

snuba/datasets/storages/discover.py, snuba/migrations/groups.py, snuba/migrations/snuba_migrations/discover/0005_discover_fix_transaction_name.py
The transaction_name column was incorrectly defined as nullable in Discover.
This is incorrect since it is not nullable in the underlying errors or transactions
tables. Similarly to title and message earlier, this causes errors when attempting
to use an aggregate function over that field.
=> fix(discover): Fix transaction_name column on Discover merge table

requirements.txt
In a 2 lines PR I think I increased the code coverage to 90%. I guess I am done with technical debt for 2021 :D 
Still trying to figure out what specific change in the changelogs fixed our coverage. Before most covered lines were marked as non code (which I suspect has something to do with mypy annotations)
=> fix(coverage) Upgrade pytest-cov and coverage packages

snuba/datasets/entities/events.py
User columns are being requested via the names in the events table,
which are not named the same thing in errors.
This maps "username" to "user_name" and "email" to "user_email" to
prevent these queries from failing.
=> fix(errors): Add column mapping for user columns

snuba/cleanup.py, snuba/cli/optimize.py, snuba/optimize.py, snuba/util.py, tests/test_cleanup.py, tests/test_optimize.py
Update the optimize script so it can be run on the errors and transactions tables.
Since these tables have differently formatted partitioning keys, this script currently
fails on anything other than events.
=> feat(optimize): Enable optimize for errors and transactions

snuba/clickhouse/processors.py, snuba/pipeline/composite.py, snuba/query/joins/semi_joins.py, tests/pipeline/test_composite_planner.py, tests/query/joins/join_structures.py, tests/query/joins/test_semi_join.py, tests/query/joins/test_subqueries.py
A query like this:
```
SELECT max(t.duration) FROM transactions t INNER JOIN span s
```
Does not need to build the entire hashtable as we do not reference anything on the right side. Thus in this case we can switch it to a SEMI join, which means clickhouse will return only the first row it can find from the right side instead of all of them. Which means fewer chances of out of memory.
This PR switches the join clause to semi join if the query does not need anything from the right side.
TODO: This still misses some cases (skip the optimization if werun aggregations on the left side that would depend on the content of the right side (like an avg(t.duration), which would be semantically wrong but still it should not be executed as a SEMI join if the user provided such query).
=> feat(join) Semi join optimization

snuba/datasets/entities/events.py, snuba/datasets/storages/errors_common.py, snuba/datasets/storages/user_column_processor.py
Make user column translation a query processor. This ensures that the
proper translation is applied to both queries to the "user" column as
well as those that reference the "tags[sentry:user]" promoted tag column.
=> fix(errors): Make user column translation a processor

snuba/datasets/table_storage.py, snuba/settings.py
Use the storage key's value in STORAGE_TOPICS rather than it's name.
This is consistent with the rest of our settings and APIs. Also updates
STORAGE_TOPICS to not use defaultdict so it is easier to override this
value in ops.
=> ref: Simplify STORAGE_TOPICS and use storage key value instead of name

snuba/query/composite.py, snuba/query/snql/parser.py, tests/test_snql_api.py
Composite queries haven't been tested end to end yet, so added some tests and
fixed a couple issues.
The query profiler will still fail on composite queries, but it will only log
a warning so it's not blocking.
=> fix(snql) Fix some issues with SnQL and composite queries

snuba/datasets/entities/events.py, snuba/pipeline/pipeline_delegator.py, tests/pipeline/test_pipeline_delegator.py
Since the events and errors tables have different sampling keys,
the differences in these queries are largely expected.
=> feat(snuplicator): Skip diffing results of sampled queries

snuba/cli/migrations.py, snuba/migrations/migration.py, snuba/migrations/operations.py, snuba/migrations/runner.py, snuba/migrations/snuba_migrations/system/0001_migrations.py
Add the --dry-run option to the migrations run and reverse commands.
This outputs the SQL that will be run on the ClickHouse nodes. Non
SQL operations (like Python scripts) cannot be previewed with --dry-run.
The --dry-run option also works with distributed and replicated tables,
which are not yet otherwise supported via the automated migration tool.
This is determined by the CLUSTERS settings configuration - if a particular
cluster has single_node set to false then the DDL that will be output will
be the distributed and replicated variant.
=> feat(migrations): Add --dry-run option to migrations tool

tests/query/data_source/test_join.py, tests/query/snql/test_joins.py
The errors entity only currently exists for testing purposes, and should be removed soon.
This removes it from some of our test suites.
=> test: Do not use errors entity in tests

snuba/utils/streams/processing/processor.py, snuba/utils/streams/processing/strategies/streaming/transform.py, tests/utils/streams/processing/strategies/test_streaming.py
When running the multi process consumer with the INFO log level, we do not know when and if the consumer gets paused. This made the investigation of an incident harder.
This adds logging in two cases:
- the consumer was paused for more than 10 seconds. Not logging every pause events because under some circumstances that can happen more often than a batch being written.
- the consumer waited for results from the worker processes longer than 20 seconds without making progress.
It also records the size of the input batch to identify spikes in the size of the input batch that could justify a longer pause.
=> test(multiprocess) Add some metrics to identify when the consumer is stuck waiting 

snuba/utils/streams/processing/strategies/streaming/transform.py
active_children would also join completed processes. Which is not necessarily a good thing here. Still need to investigate that.
=> fix(multprocess) Fix logging. Do not depend on active_children

snuba/migrations/migration.py, snuba/migrations/snuba_migrations/system/0001_migrations.py
Fixes a bug that ignored the dry-run flag for the initial migration of the migration
system, causing this migration to be performed even when --dry-run was passed.
Also moves the `forwards_local`, `forwards_dist`, `backwards_local` and
`backwards_dist` abstract methods to the base migrations class. These need to
be defined for every migration in order to support the ability to bring up new local
and/or distributed ClickHouse nodes in the future.
=> fix(migrations): Fix running first migration with --dry-run

snuba/clickhouse/query_inspector.py, snuba/clickhouse/query_profiler.py, snuba/web/query.py, tests/clickhouse/test_query_profiler.py
This prevents the query profiler from failing when it encounters a composite query.
It uses a visitor over the query to collect all table names instead of expecting a table name in the first level WHERE condition.
Following steps will take care of the other fields to fill through the same approach. Though at this point querylog does not throws anymore.
=> fix(joins): Fix querylog for join query step 1: Table names

snuba/migrations/operations.py, tests/migrations/test_operations.py
Add a potentially useful SQL operation. This will be used in the
future events -> errors backfill migration for the backwards method.
=> feat(migrations): Add truncate table operation

snuba/clusters/cluster.py
Ensure cluster_name / distributed_cluster name is set before
attempting to look up host information. Also fixes a type error.
=> fix(clusters): Ensure cluster name is set

snuba/datasets/entities/discover.py, snuba/datasets/entities/events.py, snuba/pipeline/pipeline_delegator.py, tests/pipeline/test_pipeline_delegator.py
We plan to gradually roll out the new events storage referrer by
referrer. This change passes the referrer string to the selector function,
so it can be used to determine the storage chosen.
=> feat(snuplicator): Pass referrer to selector function

snuba/datasets/entities/discover.py
Fixes a bug where an invalid pipeline ID was being referenced
in the Discover entity. Fortunately this didn't have an
impact in production since these settings weren't used yet.
=> fix(discover): Fix bug in Snuplicator storage selection

snuba/datasets/storages/discover.py, snuba/datasets/storages/errors_common.py
This matches the split behavior on errors and discover to what we have on
the original events table. The only notable difference is that the
event ID column processor will kick in on the first query since those
columns are now stored as UUIDs.
=> feat: Turn on column splitter for errors and discover storages

tests/test_api.py
Remove hardcoded references to the events table so that these tests
still pass when ERRORS_ROLLOUT_ALL and ERRORS_ROLLOUT_WRITABLE_STORAGE
are set to True.
=> test: Rewrite API tests so they pass with errors storage

snuba/datasets/errors.py, snuba/datasets/factory.py, tests/datasets/test_errors_replacer.py, tests/test_replacer.py
Refactor the events and errors replacer tests so they will still
pass when ERRORS_ROLLOUT_ALL and ERRORS_ROLLOUT_WRITABLE_STORAGE
are flipped. Also removes the "events_migration" (aka Errors)
dataset, which is never used and only existed for the purposes
of this test.
=> test: Refactor events and errors replacer tests

tests/test_discover_api.py
Discover API tests now pass for both old and new events storage - i.e. when the
settings ERRORS_ROLLOUT_ALL and ERRORS_ROLLOUT_WRITABLE_STORAGE are flipped to True.
=> test: Rewrite Discover API tests to pass with both events and errors storage

tests/datasets/test_events_processing.py, tests/pipeline/test_composite_planner.py, tests/subscriptions/__init__.py, tests/test_snql_api.py, tests/web/test_transform_names.py
Tests still pass when ERRORS_ROLLOUT_ALL and
ERRORS_ROLLOUT_WRITABLE_STORAGE are set to True. We'll flip
these values in settings_test.py as part of the SaaS rollout.
=> test: Refactor tests so they still pass with errors storage

snuba/datasets/storages/errors.py
Update the default replacement and commit log topic names to match those
of the events storage. This allows us to safely swap the events consumer
and replacer for the errors consumer and replacer, for environments
like dev and onpremise where the multistorage consumer isn't being used
as part of the rollout strategy and these defaults are relied on.
=> feat(errors): Default replacement and commit log topic names match events

snuba/cli/devserver.py
Devserver switches to the errors storage instead of events if
settings.ERRORS_ROLLOUT_WRITABLE_STORAGE is set to True.
=> feat(devserver): Devserver can switch between events and errors storage

snuba/query/organization_extension.py, snuba/query/project_extension.py, snuba/query/snql/parser.py, snuba/query/timeseries_extension.py, tests/conftest.py, tests/query/snql/test_invalid_queries.py, tests/query/snql/test_query.py, tests/query/test_organization_extension.py, tests/query/test_project_extension.py, tests/query/test_timeseries_extension.py, tests/test_api.py, tests/test_discover_api.py, tests/test_outcomes_api.py, tests/test_sessions_api.py, tests/test_transactions_api.py
Refactored the current SnQL test fixtures to add a 'compare' param that runs
both the SnQL and legacy query and compares the sql output. Added to most API
tests (test_api.py will be a separate PR because it's huge).
=> fix(tests) Add a compare test to the API tests

snuba/query/snql/parser.py, tests/conftest.py, tests/query/snql/test_query.py
SnQL wasn't handling when IS NULL or IS NOT NULL were sent as the condition op.
=> fix(snql) Add unary conditions to parser

snuba/query/snql/parser.py, tests/query/snql/test_query.py
The limit and offset defaults were being applied to subqueries which could lead
to incorrect results. Instead apply the defaults only to the top level query.
=> fix(snql) Don't apply defaults to inner queries

snuba/datasets/entities/assign_reason.py, snuba/datasets/entities/events.py, tests/datasets/entities/test_assign_reason.py
This is an attempt to categorize the discrepancies observed between the events
and errors storage, and quantify the impact of each category.
This implementation is primarily based on the premise that each "referrer"
sent from Sentry tends to be associated with a specific type or shape of query,
and knowing this context about the kind of query we are dealing with and where
it comes from can give us some better insights into what might have gone wrong.
This initial implementation of the "assign_reason_category()" function looks for
one main class of mismatch - mismatched aggregate values when everything else
remains the same. I picked this first because I suspect it accounts for the
lion's share of the discrepancies that we are currently observing. Later, we
should try to add more expected …
=> feat(errors): Assign discrepancies in Snuplicator results to a category

snuba/datasets/entities/assign_reason.py, snuba/datasets/entities/events.py, tests/datasets/entities/test_assign_reason.py
This changeset includes 3 improvements to reason assignment:
1. "reason" is sent as part of Sentry's "tag" data, rather than "extra",
enabling us to filter on this dimension in Sentry.
2. TSDB queries are checked for misisng/extra rows and out of order results.
3. Add aggregate checks from a number of other expected referrers.
=> feat(snuplicator): Improve reason assignment

tests/datasets/test_errors_replacer.py, tests/datasets/test_events_processor.py, tests/datasets/test_fast_bulk_load.py, tests/datasets/test_session_processor.py, tests/datasets/test_transaction_processor.py, tests/state/test_rate_limit.py, tests/state/test_state.py, tests/subscriptions/test_codecs.py, tests/subscriptions/test_data.py, tests/subscriptions/test_store.py, tests/subscriptions/test_subscription.py, tests/test_api.py, tests/test_cli.py, tests/test_replacer.py
A quick and dirty change to capture one one of the low hanging fruits when type
hinting the tests.
=> fix(typing) Add None return to tests

snuba/migrations/runner.py
A dry run of a blocking migration shouldn't require force, since it doesn't
really do anything except print a preview of the migration.
=> fix(migrations): Allow dry run on blocking migrations without force

snuba/state/cache/abstract.py, snuba/state/cache/redis/backend.py, snuba/web/db_query.py, tests/state/test_cache.py
There are 3 possible scenarios:
- If we get an immediate cache hit, "cache_hit" for that query is set to True
- If we get a duplicate query (a same query that will populate the cache is
ahead in the queue but we have to wait for it), "is_duplicate" is set to True
- If none of the above, neither "cache_hit" nor "is_duplicate" is set
=> feat(cache): Record stats for readthrough cache in querylog

snuba/clickhouse/query_dsl/accessors.py, snuba/datasets/cdc/groupassignee_entity.py, snuba/datasets/cdc/groupedmessage_entity.py, snuba/datasets/entities/discover.py, snuba/datasets/entities/errors.py, snuba/datasets/entities/events.py, snuba/datasets/entities/sessions.py, snuba/datasets/entities/transactions.py, snuba/query/processors/project_rate_limiter.py, tests/query/processors/test_project_rate_limiter.py, tests/test_snql_api.py
This is meant for use with SnQL, which is getting rid of query extensions.
Moving this logic to a query processor separates it from the entity logic and
makes it more portable and easier to understand.
=> Add a project rate limiter as a query processor

snuba/datasets/entities/events.py
Allows us to test a hypothesis about whether "consistent" has any
impact on differences seen when running a same query on both the
events and errors storages.
=> ref: Log "consistent" for Snuplicator queries

snuba/datasets/entities/events.py
Results that hit cache are extremely likely to be mismatched between
events and errors at low rollout rates of the new table. This creates
too much noise in Sentry.
=> feat: Do not log cache hit to Sentry

snuba/consumers/consumer.py
The standard consumer records latency as 
`consumer.insertion.latency_ms` with tags `storage:.....`
The multistorage consumer instead records latency as 
`consumer.latency_ms` without tags.
This makes the multistorage consumer behave like the standard consumer and fixes our metrics and alerts which are based on consumer.insertion.latency_ms.
=> fix(metrics) Fix the latency metrics on multi storage consumer 

snuba/web/views.py, tests/test_api.py
If we get unexpected errors (redis errors for example) we return an HTML 500
response. Add a handler that will return JSON so at least Sentry doesn't also
throw exceptions.
=> fix(errors) Add a 500 error handler

snuba/datasets/storages/events_common.py
The "user", "release" and "dist" columns were incorrectly added to the
events schema in https://github.com/getsentry/snuba/commit/481571a16fbb2e592c30a4460c407455c5d65528.
These columns do not actually exist; rather they are mapped to sentry:user,
sentry:release and sentry:dist respectively.
=> ref: Schemas should not contain columns not present in database

snuba/datasets/storages/groupedmessages.py
I'm not sure why the prewhere processor is not being run on the grouped message
storage. I assume it is an oversight since the corresponding schema has got
defined prewhere candidates.
=> feat(prewhere): Add prewhere processor for the grouped message storage

snuba/datasets/plans/single_storage.py, snuba/datasets/schemas/__init__.py, snuba/datasets/schemas/tables.py, snuba/datasets/storages/discover.py, snuba/datasets/storages/errors.py, snuba/datasets/storages/errors_common.py, snuba/datasets/storages/errors_ro.py, snuba/datasets/storages/events.py, snuba/datasets/storages/events_common.py, snuba/datasets/storages/events_ro.py, snuba/datasets/storages/groupassignees.py, snuba/datasets/storages/groupedmessages.py, snuba/datasets/storages/outcomes.py, snuba/datasets/storages/sessions.py, snuba/datasets/storages/spans.py, snuba/datasets/storages/transactions.py, snuba/query/data_source/simple.py, snuba/query/processors/prewhere.py, tests/pipeline/test_composite_planner.py, tests/query/processors/test_mandatory_condition_applier.py, tests/query/processors/test_prewhere.py
Adds a mechanism to prevent specified columns from being included in the prewhere
clause if a query runs with final.
This helps us avoid a fairly obscure ClickHouse bug that causes an error when
a query contains a prewhere on a low cardinality, nullable column and that
query is run with final.
Since the new errors storage uses this column type more often than the events
table that it replaces, this may start to come up more often. It would also allow
us to safely add the `release` column to the list of prewhere candidates as long
as final is not used.
Fixes SNUBA-26G
=> feat(prewhere): Modified prewhere candidates for final queries

snuba/consumers/consumer.py, snuba/datasets/cdc/cdcprocessors.py, snuba/datasets/events_processor_base.py, snuba/datasets/outcomes_processor.py, snuba/datasets/querylog_processor.py, snuba/datasets/sessions_processor.py, snuba/datasets/spans_processor.py, snuba/datasets/transactions_processor.py, snuba/processor.py, tests/datasets/cdc/test_groupassignee.py, tests/datasets/cdc/test_groupedmessage.py, tests/datasets/test_errors_processor.py, tests/datasets/test_querylog_processor.py, tests/datasets/test_session_processor.py, tests/datasets/test_transaction_processor.py, tests/snapshots/test_snapshot_worker.py, tests/test_api.py, tests/test_cleanup.py, tests/test_consumer.py, tests/test_optimize.py
This is a very approximate end to end metric: postgres commit timestamp - clickhosue write timestamp to understand the order of magnitude of the latency we are going to expect and to understand how stable this latency is over time.
It allows each consumer to provide an origin timestamp (which is produced from the parsed message body, so it cannot be extracted by the consumer infrastructure) in the InsertBatch the processor produces for each Kafka message.
Then this is propagated till the BatchWriter that collects the metrics.
=> feat(cdc) Collect some end to end latency metrics for cdc

snuba/query/parser/__init__.py, snuba/query/snql/parser.py, tests/base.py, tests/conftest.py, tests/test_api.py, tests/test_snql_api.py
Now all API tests are running a legacy version, a SnQL version and a compare
version that asserts the generated SQL is the same between the two versions.
=> feat(snql) Use SnQL in all API tests

snuba/datasets/entities/assign_reason.py, tests/datasets/entities/test_assign_reason.py
If a result differs between events and errors due to a missing or
non unique order by term, assign "NONDETERMINISTIC_QUERY" as the reason.
=> feat(snuplicator): Assign reason for non deterministic queries

snuba/query/conditions.py, snuba/query/processors/arrayjoin_keyvalue_optimizer.py, tests/query/test_conditions.py
We have to match conditions often that could have literal on either side of the expression. This is specifically true with SnQL that does not impose the literal to be on the right hand side.
This adds a helper function to generate a proper pattern to match conditions in a commutative way. It will be useful for promoting the trace_id and span_id contexts.
=> feat(query) Add commutative condition matcher

snuba/datasets/storages/transactions.py, snuba/query/processors/typed_context_promoter.py, tests/query/processors/test_typed_context_promoter.py
Now that we are using the trace_id and span_id columns on discover queries, we can improve the performance of those queries further by adding them to the prewhere clause as they are extremely high selectivity columns.
=> perf(trace_id) Add trace_id and span_id to the prewhere clause

snuba/datasets/storages/errors_common.py
We never have group IDs that are 0 in the errors table, so do not convert
to nullIf(group_id, 0)
=> feat: Drop the group_id processor from errors

snuba/datasets/querylog_processor.py
For some reason the messages are missing timing and status fields, so skip them
for now.
=> fix(querylog) Skip missing fields

snuba/datasets/entities/events.py
Don't log the Snuplicator results of nondeterministic queries to Sentry
as this creates too much noise and there's not a lot we can do to change
this.
=> ref: Send less data to Sentry

snuba/datasets/storages/errors_common.py, snuba/datasets/storages/type_condition_optimizer.py, tests/query/processors/test_type_condition_optimizer.py
The expression `type != transaction` is frequently included in events entity queries
in order to filter rows because the events table includes transaction events.
Since the errors table never includes these events to begin with, this condition
will always be met. This optimizer rewrites `type != transaction` to `1` if it is
present when running the errors storage, so that the ClickHouse query does not need
to unnecessarily access the `type` column.
Once the errors storage is fully rolled out, Sentry queries will no longer include this
condition and this optimizer can be removed.
=> feat(errors): Add type optimization for errors storage

snuba/datasets/outcomes_processor.py
we receive a large number of abuse outcomes that are making our metrics non-useful. this change filters those outcomes from counting towards metrics.
=> fix(outcomes): filter abuse outcomes in metrics

tests/pipeline/test_composite_planner.py
The errors storage doesn't apply the group ID processor so the generated
query after processing is slightly different.
=> test: Fix the composite planner test so it also works on errors storage

snuba/datasets/storages/errors_common.py, snuba/query/processors/uuid_column_processor.py, tests/query/processors/test_uuid_column_processor.py
This processor combines the functionality of what is currently split across the
EventIdColumnProcessor and the UUIDColumnProcessor. It gives us the ability to
easily add support and optimizations for UUID columns without having a specific
processor for each column. It also makes it impossible to accidentally apply one
of the processors but not the other one, or apply them in the wrong order which
will result in broken behavior. Now you can no longer apply a UUID processor
without the optimization for conditions as well.
The new processor is only applied to the errors storage to begin with.
=> feat: Improve UUID processing so it can be extended to other columns

snuba/datasets/entities/assign_reason.py
Helps us identify problems with specific referrers, and gives
us a better picture of the impact of over/under counted aggregates.
=> ref: Assign reason for a few more referrers

snuba/snapshots/__init__.py, snuba/snapshots/postgres_snapshot.py, tests/snapshots/test_postgres_snapshot.py
We recently changed the format of the cdc snapshot meta data including a formatter.
This was not yet reflected in the Snuba code base which was still assuming the list of columns to be alist of strings.
This fixes it by adding the details of the missing details in the schema.
=> fix(cdc_snapshot) Fix the logic that loads the snapshot descriptor

snuba/datasets/entities/sessions.py, snuba/datasets/storages/sessions.py, tests/datasets/test_sessions_processing.py, tests/test_sessions_api.py
This also removes the config switch, always enabling minute-resolution sessions unconditionally.
=> feat: Restrict minute-resolution sessions to a 7h time window

snuba/utils/streams/backends/kafka.py
Reverts the rdkafka debug logging change introduced in #1759 to avoid execcive logging on dev machines
=> fix(rdkafka): Disable rbkafka debug logging

tests/query/test_query_ast.py
Queries on event_id need to be valid UUIDs when using the errors
storage otherwise a validation error will be thrown and this test
will start failing.
=> test: Fix test_query_ast

.pre-commit-config.yaml, mypy.ini
We should not ignore all type errors in tests as these will be completely
silenced in development and we will never be aware of these issues. For now, we
still allow CI to pass if there are type errors in tests, only `snuba` is required
for CI.
=> ref: Don't ignore all type errors in tests

snuba/datasets/errors_replacer.py, tests/datasets/test_errors_replacer.py, tests/test_replacer.py
This seems to make clickhouse scan fewer rows.
Also removes a useless condition from the PREWHERE when there is no old primary hash and removes the cityHash from the errors replacer
=> fix(replacer) Add the toString back and remove the hash from errors

snuba/datasets/storages/events_bool_contexts.py, tests/query/processors/test_bool_context.py
These fields are all nullable UInt8. Since this first condition will
never be met remove it from the ClickHouse query.
=> ref: Remove redundant condition in boolean context processor

snuba/datasets/storages/discover.py, snuba/datasets/storages/errors_common.py, snuba/datasets/storages/events_bool_contexts.py, snuba/datasets/storages/events_common.py, snuba/datasets/storages/transactions.py, tests/query/processors/test_bool_context.py
Add equivalent processing for the 3 boolean contexts - device.online,
device.simulator and device.charging - to the errors, transactions and
discover storages. The results are now equivalent to those from the
events storage.
=> feat: Port boolean context processing to all storages

snuba/datasets/storages/events_common.py, snuba/query/processors/mapping_promoter.py, tests/query/processors/test_bool_context.py, tests/query/processors/test_mapping_promoter.py
The mapping column promoter now only promotes a column and does not
attempt to fix it's type by simply casting to string. We need to keep
the old behavior around temporarily as it's used in the legacy events
table - once that is gone the option to cast the type will no longer
be required here.
The previous behavior caused issues with the UUIDColumnProcessor as the
expected query no longer matched what the processor expected if a column
was a promoted one due to the insertion of the extra toString() function.
=> feat: Mapping column promoter does not cast to string by default

snuba/datasets/storages/transactions.py, snuba/migrations/groups.py, snuba/migrations/snuba_migrations/transactions/0011_transactions_add_span_op_breakdowns.py
Based on https://github.com/getsentry/snuba/pull/1233
Associated change in Relay: https://github.com/getsentry/relay/pull/934
Add span op breakdowns column to the transactions dataset that has identical schema to the `measurements` column.
=> feat(breakdowns): Schema change for span op breakdowns

snuba/datasets/storages/errors_common.py
This change ensures that the primary hash column in the errors storage
is always formatted in the same way as it was on the events storage (non
hyphenated 32 byte string).
=> fix: Fix formatting of primary hash

snuba/datasets/transactions_processor.py, tests/datasets/test_transaction_processor.py
Depends on https://github.com/getsentry/snuba/pull/1761
Associated change in Relay: https://github.com/getsentry/relay/pull/934
Ingested transaction events in Relay (https://github.com/getsentry/relay/pull/934) will emit span op breakdowns into the event as in the following example (values are in milliseconds):
```
{
"breakdowns": {
"span_ops": {
"ops.http": {"value": 2000000.0},
"ops.resource": {"value": 100001.003},
"total.time": {"value": 2200001.003},
}
}
}
```
The keys and values will be read from `breakdowns.span_ops` and populate the `span_op_breakdowns` columns of the transactions table.
=> feat(breakdowns): Populate the span op breakdowns field

cloudbuild.yaml
Turns out our e2e tests were not working properly and informing us about failures due to the faulty `./test.sh || docker-compose logs nginx web relay` logic that we fixed over at Sentry but not here. This PR fixes that and aligns the whole file to mimic what we do over at the Sentry repo.
=> ci(gcb): Fix e2e tests, align them with Sentry

cloudbuild.yaml
In Freight, our deployment app, we use Cloudbuild list API to search for build for particular commit using filter query e.g.
```
{'filter': 'images="us.gcr.io/sentryio/snuba:4234a46aead05c8acf6744420995509de11543d3"'}
```
Without the `images` section Freight is unable to find a matching build a thus will not allow deployment.
=> fix(cloudbuild): Add images section so freight can find the builds

snuba/migrations/snuba_migrations/events/0014_backfill_errors.py
We only need to migrate up to 90 days of data (our retention window).
The previous implementation incorrectly migrated an extra partition that
is not required.
=> fix(errors-migration): Avoid migrating unnecessary extra partition

snuba/datasets/entities/discover.py, tests/test_discover_api.py
This is a quick fix to prevent the entire condition expression
from being mapped to null by the DefaultIfNullFunctionMapper. It
ensures that mapping of and/or/not/xor expressions is skipped
even if a match for the identity(...) expression is found.
We sbould probably follow up with a more optimal solution that does
not replace any expression that contains identity(...) with
identity(NULL).
=> fix: Prevent all conditions from being dropped from a query

snuba/query/processors/type_converters/hexint_column_processor.py
Ensure that we return 400 instead of 500 if a string is not a valid hexint value
=> fix(hexint-processor): Return 400 error if invalid hexint value

snuba/query/processors/arrayjoin_keyvalue_optimizer.py, tests/query/processors/test_arrayjoin_optimizer.py, tests/test_api.py
In order for the SQL comparison between Legacy and SnQL to consistently pass,
the tag keys need to be in a consistent order.
=> fix(snql) Keep tags in consistent order in arrayjoin optimizer

snuba/datasets/entities/events.py
The events storage is now deprecated, the data model for the events
entity should be based on the errors storage.
=> ref: Events entity data model is based on errors schema not events

tests/datasets/test_events_processing.py, tests/datasets/test_querylog_processor.py, tests/pipeline/test_composite_planner.py, tests/pipeline/test_pipeline_delegator.py, tests/test_api.py, tests/test_discover_api.py, tests/web/test_transform_names.py
We no longer require our tests to pass when run on the events storage.
This change removes references to these in tests so the storage can be
easily removed later.
=> test: Remove references to events storage in tests

snuba/settings.py, snuba/utils/streams/backends/kafka.py, tests/utils/streams/backends/test_kafka_config.py
DEFAULT_BROKERS has been deprecated for some time; BROKER_CONFIG should be used
instead. This removes support for the DEFAULT_BROKERS setting.
=> feat: Remove deprecated DEFAULT_BROKERS setting

snuba/web/split.py, tests/test_api.py, tests/test_discover_api.py
It's possible for the minimal query to break if the orderby is a function on a
column instead of a bare column. Clickhouse throws an exception along the lines
of `Not found column f(x) in block` if f(x) is not in the select clause. Since
the minimal query replaces the select clause, this failure happens. Skip the
splitter entirely in this case.
=> fix(splitter) Skip the splitter if the order by is a function

snuba/cli/devserver.py, snuba/datasets/entities/events.py, snuba/settings.py, tests/datasets/test_errors_replacer.py, tests/test_replacer.py
Removes support for the ERRORS_ROLLOUT_WRITABLE_STORAGE flag which
previously allowed switching between the events and errors storage in
dev and test environments. Only errors can be used now.
=> feat: Remove the ability to run the events storage in dev and test

.gitignore, snuba/query/parser/conditions.py, tests/query/parser/test_conditions.py, tests/test_discover_api.py
The legacy code strips duplicate top level conditions. I could add this to the
SnQL parser as well, but most SnQL queries have duplicate project conditions,
which the legacy parser preserves (since the extension conditions are added
after the deduping happens). So either I handle the single case of duplicate
project conditions, which requires rewriting the extension, the snql parser
and the SDK, or I remove this check from the legacy parser.
Since there's no Clickhouse impact to having duplicate conditions, I figured
this was the cleaner solution.
=> fix(snql) Allow duplicate conditions

snuba/datasets/table_storage.py
This fixes a bug in the settings validation when the STORAGE_TOPICS
setting is being used. This check is no longer valid since we are no
longer mutating the storage_topics dict.
=> fix: Fixes a bug when using settings.STORAGE_TOPICS

snuba/datasets/storages/events.py, snuba/utils/streams/topics.py
Replacements for events and errors need to be on separate topics.
This is required to support environments (like Sentry prod) where the
multistorage consumer is used to run both events and errors consumers
at the same time. In that case replacements need to be on different topics.
=> fix: Legacy events replacements should be on a separate topic

snuba/settings/validation.py
This is required in order to be able to override the legacy events topic name.
=> fix(settings): Add legacy topic name to settings validation

snuba/cli/confirm_load.py, snuba/consumers/consumer.py, snuba/consumers/consumer_builder.py, snuba/datasets/cdc/groupassignee.py, snuba/datasets/cdc/groupedmessage.py, snuba/datasets/factory.py, snuba/utils/streams/backends/kafka.py, tests/test_writer.py, tests/utils/streams/backends/test_kafka_config.py
This reverts commit adb07d8bf71c93974466b1e3f8161260379e3a8b.
These datasets are still referenced in Sentry tests, we should remove that first.
=> Revert "feat: Remove unused datasets (#1843)"

snuba/cli/devserver.py, snuba/cli/subscriptions.py, snuba/datasets/storages/errors.py, snuba/datasets/storages/events.py, snuba/datasets/storages/transactions.py, snuba/datasets/table_storage.py, snuba/settings/validation.py, snuba/utils/streams/topics.py
This is an attempt to align the way subscription result topics are configured
with the rest of the Kafka topics.
Previously any storage could be subscribed to (though it may not work properly).
Now a storage defines whether it can be subscribed to or not via
`stream_loader.subscription_result_topic`. It is no longer necessary to pass the
--result-topic into the subscriptions consumer, the topic name will come from
the default or settings configuration like all other Kafka topics.
The result topics will also now get created when `snuba bootstrap` is run.
=> feat: Subscription result Kafka topic can be configured via settings

snuba/cli/bulk_load.py, snuba/datasets/table_storage.py
We never need to set this parameter in dev. Or in any environment other than specific production tests. 
Defaulting to the storage table is the right option most of the times. This way we can avoid exposing the clickhouse table names outside of this script.
=> feat(cdc) Make destination table optional on bulk_load

tests/assertions.py
Do not enforce the return type of callable passed to assert_changes and
assert_does_not_change to return any type. The goal of this change is
to make these functions easier to use.
=> ref(typing): Simplify typing assertion helpers

snuba/querylog/query_metadata.py, tests/datasets/test_errors_processor.py, tests/datasets/test_querylog_processor.py, tests/datasets/test_spans_processor.py, tests/datasets/test_transaction_processor.py, tests/test_processor.py
Tackles the type issues in all of the message processor tests except for
`test_events_processor`, as that should be deleted soon.
=> ref(typing): Fix typing in the processor tests

snuba/query/snql/parser.py, tests/test_discover_api.py
Use the existing dataset logic to pick between the different Discover entities
when a query to the "discover" dataset is sent to SnQL. Hopefully this can be
removed in the future but it's needed for now to support legacy queries.
=> feat(snql) Entity selection for Discover queries

snuba/datasets/errors_replacer.py, snuba/datasets/storage.py, snuba/datasets/table_storage.py, snuba/replacer.py, snuba/replacers/replacer_processor.py
Split out the replacement type refactor from https://github.com/getsentry/snuba/pull/1861 without rewriting any replacements at all. In future PRs we can port the replacements one-by-one (like done in #1861) and then remove LegacyReplacement.
=> ref: Redefine Replacement as ABC [minimal]

snuba/datasets/errors_replacer.py
We received this message 
```
{
event_ids: [
'e66bad96c1614dcaa927bdb2b29efe08'
], 
from_timestamp: '2021-05-20T17:04:38.000000Z', 
old_primary_hash: 'AF733E6D20256FEE784E39332EC17A27E0DF3C5A', 
project_id: 5448233, 
to_timestamp: '2021-05-20T17:04:38.000000Z'
}
```
old_primary_hash is not a valid UUID.
=> fix(replacer) Bad tombstone message causes replacements to stop

snuba/datasets/entities/metrics.py, snuba/datasets/storages/metrics.py, tests/datasets/entities/test_tags_transformer.py, tests/datasets/test_metrics_processing.py
`tags[10]` is today parsed as `SubscriptableReference(None, Column(None, None, "tags"), Literal(None, "10"))` as we assume the key is a string.
This has been true for all datasets except for metrics where the tag key is an integer.
I don't think we should change the parser for making it know about specific types of subscriptables, as the valid subscriptables are defined by the dataset and the parser is generic.
Since this is a specific behavior of one dataset, I added this processing as an entity query processor instead of adding this specific logic to the common subscriptable translator (also this kind of change is easier to do in a processor that has a lot more context than a translator or the translator would have to make changes to its children, which can be dangerous). 
I doubt we …
=> feat(metrics) Support tags with integer keys

snuba/datasets/entities/__init__.py, snuba/datasets/entities/factory.py, snuba/datasets/entities/metrics.py, tests/datasets/test_metrics_processing.py
Adds an entity for the storages added in #1907
It can be queried this way:
```
MATCH (metrics_counters) 
SELECT value BY org_id, project_id, tags[10] 
WHERE 
timestamp >= toDateTime('2021-05-17 19:42:01') AND 
timestamp < toDateTime('2021-05-30 23:42:01') AND 
org_id = 1 AND 
project_id = 1
```
=> feat(metrics) Add Counters entity

.github/workflows/docs-pr.yml
Added a new github action file docs-pr.yml which runs only on pull requests. It runs make snubadocs and ensures no failures are found when running that command.
=> ci(docs): Add github action to verify docs on PR's

streaming_kafka_consumer/backends/kafka/__init__.py, streaming_kafka_consumer/concurrent.py, streaming_kafka_consumer/synchronized.py, tests/state/test_cache.py, tests/utils/metrics/test_gauge.py, tests/utils/test_concurrent.py
The `concurrent` module is primarily used by the streaming_kafka_consumer package.
=> ref: Move concurrent to the streaming_kafka_consumer package

snuba/cli/bootstrap.py, streaming_kafka_consumer/backends/kafka/configuration.py, streaming_kafka_consumer/logging.py
The `pylog_to_syslog` method is now only being used by the streaming kafka consumer package
=> ref: Move logging utility to streaming_kafka_consumer

streaming_kafka_consumer/backends/local/storages/file.py, streaming_kafka_consumer/codecs.py, streaming_kafka_consumer/synchronized.py
This copies the Codec class to the streaming kafka consumer package
so that we do not depend on the snuba implementation there.
=> ref: Streaming kafka consumer does not depend on snuba.utils.codecs

streaming_kafka_consumer/processing/strategies/batching.py
Similarly to the rest of the streaming consumer API, metrics should be an optional
argument to the batch processing strategy factory. If no value is provided,
the dummy metrics backend is used.
=> ref: Add default `metrics` value to batch processing strategy factory

tests/state/test_cache.py, tests/utils/metrics/test_gauge.py
Snuba's cache and gauge have not nothing to do with the streaming
consumer. We should not rely on methods imported from there for these tests.
=> test: Refactor cache and gauge tests

streaming_kafka_consumer/tests/test_metrics.py
This is based on a similar test for Snuba's gauge implementation
=> test: Add test for streaming kafka consumer's gauge implementation

snuba/utils/streams/configuration_builder.py, streaming_kafka_consumer/backends/kafka/configuration.py
Make auto_offset_reset, queued_max_messages_kbytes and queued_min_messages
optional when building Kafka configuration. Default values will be applied.
=> ref: Simplify consumer configuration

snuba/state/cache/redis/backend.py, snuba/web/db_query.py
Add data to the span in the cache to track whether a query was actually executed
or was cached or queued for a cached result.
=> fix(perf) Add span data to track query execution

snuba/migrations/snuba_migrations/outcomes/0003_outcomes_add_category_and_quantity.py
This fixes a bug where the outcomes dist migrations were incorrectly attempting
to create the `category` column in the outcomes_hourly_local table instead of
outcomes_hourly_dist. As a result a column was missing from the dist table.
There is also no order by on a distributed table so we cannot attempt to run a
MODIFY ORDER BY statement or this migration will just fail.
=> fix(outcomes): Fix outcomes dist migration

snuba/subscriptions/data.py
Use the rollout pct for all projects, and the project list as 100%.
=> ref(snql): Use the percentage for all projects

requirements.txt
The current version of sentry-relay dependency does not compile with rust versions 1.49.0 and above. Bumping up the sentry-relay requirement to the latest 0.8.7
Found the following open issue in relay project https://github.com/getsentry/relay/issues/915. I have version 1.52.1 installed and hence its failing for me.
=> fix(requirements) Update sentry-relay requirements

snuba/web/db_query.py
Add the query id which is saved in the clickhouse querylog to the
transaction tags and the span to correlate slow transactions with
the corresponding query
=> ref(debug) Add query_id to transaction and span

requirements.txt, tests/state/test_cache.py
I think this test would fail because the `waiter` might get run before the
`setter` since they were delayed equal amounts of time. I added the small sleep
to help ensure that they run in parallel but the waiter won't finish until after
the `setter`.
=> fix(tests) Attempt fix for flaky cache test

.github/workflows/ci.yml
This reverts commit d36d739ee5cc184e880f063ba8f93b4ae3095cd0.
No longer needed for freight
=> Revert "ci: Add back the old context for freight (#1971)"

snuba/cli/cleanup.py, snuba/cli/consumer.py, snuba/cli/multistorage_consumer.py, snuba/cli/optimize.py, snuba/cli/replacer.py
The consumer, multistorage consumer, replacer, optimize and cleanup
commands previously defaulted to the events storage (which is now
deprecated and should be removed). This change removes the default
completely and requires the user to always provide the storage name.
=> ref: Remove default storage from CLI

snuba/environment.py, snuba/settings/__init__.py, snuba/util.py
We are logging `subscriptions.receive_latency` and `subscriptions.process_message` at every tick of the TickConsumer (which is per message).
This happens in the main consuming thread.
This is a test to measure the impact of these metrics on the consumption time.
In the past we saw there was a visible impact in throughput for a consumer due to these metrics logged for each message. 
Probably the gain won't be similar to the one we had on the cdc consumer as the logic is not fully serial in the consumer. Query processing are in separate threads which can use the core while we send the UDP metric to datadog. This is meant to measure that.
=> perf(subscriptions) Test possible message processing improvement by sampling metrics

.github/workflows/ci.yml, .pre-commit-config.yaml, requirements.txt
Upgrade mypy from 0.800 to 0.812. This now matches the version of
mypy used in Arroyo - this may be required to get mypy in precommit
working properly.
=> ref: Upgrade mypy

snuba/querylog/__init__.py
This would be useful have the breakdown by phase during the query for individual referrers.
=> perf(subscriptions) Log the referrer with the marks in the query timer.

snuba/clickhouse/native.py, snuba/datasets/plans/single_storage.py, snuba/reader.py, snuba/subscriptions/worker.py, snuba/web/db_query.py, snuba/web/query.py
This change runs subscription worker with the robust ClickHouse execution
strategy. This means that (like replacers) connection issues are retried 3
times and too many concurrent queries will be retried forever with a 1
second delay.
The main motivation for this change is to prevent subscription workers
unnecessarily crashing and restarting when ClickHouse is overloaded.
An alternative strategy would be to have the subscription worker define
it's own retry logic rather than use the default execute_robust behavior.
This may be preferable if we want to be able to define and tweak subscription
specific retry behavior. However this would require the original ClickHouse
error code to be stored on the QueryException so that the subscription worker
can detect which type of error occurred. Since …
=> feat: Run subscription worker with execute_robust

snuba/request/request_settings.py, snuba/request/validation.py, tests/test_api.py
This is the quickest safeguard in case we still go beyond the max concurrent queries in clickhouse on the nodes that take consistent queries. 
This allows compromises consistency (for the percentage of queries configured) by sending to any node. 
Hopefully we will not have to use it. But it is better to have it  just in case.
The consistent flag means that the query will go to to the same node we write onto so avoiding the replication lag (and use one thread only). Replication lag tends to by tiny: below 10ms), so in case of incident it is probably better being capable to compromise that than to fail large amount of queries.
=> fix(consistent) Have a killswitch we can use in case the amount of consistent queries is too high for clickhouse

.pre-commit-config.yaml, requirements.txt, snuba/consumers/consumer.py, snuba/consumers/consumer_builder.py
This change initializes the Sentry SDK in the subprocesses
spawned by Snuba consumers. Non-fatal errors and warnings
emitted from these subprocesses should now be sent to our
Sentry instance.
It's possible that Sentry will become a bit more noisy as
a result - we may want to follow up later with tweaks to
optimize what we are actually sending Sentry.
=> feat: Initialize Sentry SDK in spawned subprocesses

snuba/request/validation.py
We have been creating HTTPRequestSettings instances for subscriptions instead of SubscriptionRequestSettings for quite some time. This is a bug. 
IT had no consequence until I added a bypass to reduce the concurrent queries, as the parameters used in the HTTPRequestSettings were the same. I noticed the issue since the bypass generates wrong results removing consistent too often.
This fixes the bug.
=> fix(query settings) Create the right instance of query settings

tests/migrations/test_runner.py
This assertion seems to occasionally fail on Google cloud builder (likely
since more than 1 second has elapsed since the status was retreived from
ClickHouse earlier in the test). I don't think it adds that much value so
let's just remove it.
=> test: Remove flaky assertion

snuba/subscriptions/worker.py, snuba/web/query.py
The existing metric around concurrent queries for metrics includes both query processing and clickhouse execution.
This adds another metric to track the concurrent clickhouse queries.
IT should help us quantify how CPU bound the subscriptions consumer is.
=> perf(subscriptions) Add a gauge to measure the amount of concurrent queries we send to clickhouse

snuba/settings/__init__.py, snuba/subscriptions/scheduler.py, tests/subscriptions/subscriptions_utils.py, tests/subscriptions/test_builder_mode_state.py, tests/subscriptions/test_scheduler.py, tests/subscriptions/test_task_builder.py
In the current subscription scheduler implementations, queries are scheduled as soon as possible. This causes a thundering herd of queries at the beginning of each minute as hundreds of queries can be scheduled together.
This has a negative impact on clikchouse as too many ocncurrent queries are executed and the response time of each query gets longer. This also causes additional delay in consumption and backlog.
This PR addresses this problem by spreading queries along the time range corresponding to the subscription resolution.
Example: if the resolution is 60 seconds (which it is), each subscription gets executed every 60 seconds.
Now, instead of executing all the queries at the beginning, each query gets a jitter assigned that is stable and calculated based on the subscription id. …
=> perf(subscriptions) Add a jitter to the subscriptions scheduler to distribute queries in the evaluation window

snuba/request/request_settings.py, snuba/subscriptions/worker.py, tests/subscriptions/test_worker.py
This change adds a way to run and compare the results of subscription queries
without the "consistent" setting to those that currently run in production
with "consistent" set to true. If results turn out not to be significantly
different, it may be worthwhile to turn off consistent for subscriptions
allowing their queries to be spread over all replicas instead of just the
first one.
This can be set for events and transactions subscriptions via the
"event_subscription_non_consistent_sample_rate", and
"transaction_subscription_non_consistent_sample_rate" configuration keys.
Both of these configurations should be set to a value between 0 and 1 where
0 means don't snuplicate any queries (the default) and 1 means run 100% of
queries with both settings and record metrics.
The actual result …
=> perf: Support comparing subscription queries with and without consistent

snuba/datasets/errors_replacer.py
Add a mechanism to find out what is the type of the replacement
message the replacer is receiving. This would help narrow down the
cause of spikes in clickhouse queries due to replacements.
=> ref(replacer): Log metrics for type of replacement

snuba/subscriptions/worker.py
Log 1 in 100 subscription queries that do not match with consistent
vs non-consistent to Sentry
=> feat: Log a small percentage of non matching queries to Sentry

setup.py
Before
```
$ docker run -d --name=snuba --rm --entrypoint=tail -it getsentry/snuba:21.6.3 -f /dev/null
9cdbe2fc10e288e00b514ccb90b3be79657d655ff5ce56f11e6de15cefaad62d
$ docker exec -it snuba /bin/bash
root@9cdbe2fc10e2:/usr/src/snuba# snuba --version
snuba, version 0.0.0
```
After
```
$ docker exec -it snuba /bin/bash
root@9ed21f508eb3:/usr/src/snuba# snuba --version
snuba, version 21.7.0.dev0
```
=> fix: version option

snuba/subscriptions/data.py, snuba/subscriptions/worker.py, tests/subscriptions/test_data.py, tests/subscriptions/test_subscription.py, tests/subscriptions/test_worker.py
Also add a metric to track if any subscriptions are still using legacy. This
metric should always be zero.
=> ref(snql) Remove project rollout flag and default to 100%

snuba/subscriptions/worker.py
Now that discrepancies between the consistent vs non-consistent subscription
queries are extremely rare, let's log them all to Sentry to figure out what's
going on.
=> feat: Log all consistent discrepancies to Sentry

snuba/web/views.py
I originally had SnQL queries using a separate metrics tag so I could track the
performance separately. Now that all traffic is shifting to SnQL it's better to
put all of it in one place so we don't have to change any of our current SLOs
and alerts etc.
=> fix(snql) Use the same metrics path for SnQL queries

snuba/datasets/transactions_processor.py, snuba/settings/__init__.py, tests/datasets/test_transaction_processor.py
Today we are storing in Snuba all contexts the client is sending.
This includes custom contexts, which cannot be searched nor aggregated anyway.
So far this has not been a problem, but custom contexts started being the vast majority of the contexts stored for some projects.
This bloats the size of the contexts column for no reasonas these do not need to be in Snuba at all.
This is the quickest fix to reduce the impact on the queries that look for standard contexts (like trace and geo), then, after we find a way to ensure Snuba always have an up to date list of standard contexts, we should ensure we only store searchable contexts.
=> perf(transactions) Allows us to configure specific contexts not to be stored

tests/conftest.py
It's not necessary to compare the SnQL and legacy outputs anymore, since that
was originally just to ensure that SnQL was returning the correct results. I am
going to leave the legacy tests since there might be customers using the old
endpoint.
=> fix(tests) No need to run the compare version of SnQL tests

snuba/pipeline/pipeline_delegator.py, snuba/subscriptions/worker.py, snuba/utils/threaded_function_delegator.py, tests/pipeline/test_pipeline_delegator.py, tests/utils/test_threaded_function_delegator.py
Currently the callback function receives a list with all of the query
results. If one of the queries has failed, it is ambiguous whether it is
the primary or some other query that has failed. This change passes
the primary result back separately to the rest of the results. It will
be None if the function has errored.
=> fix(snuplicator): Handle exceptions in the primary query

snuba/datasets/entities/sessions.py, snuba/datasets/storages/__init__.py, snuba/datasets/storages/factory.py, snuba/datasets/storages/sessions.py
We created a sessions entity that could be used to query aggregate numbers
across all organizations, however we didn't create a custom storage as well. The
mandatory condition checks on the old storage were failing, so I created a new
storage that is missing those checks just to be used with that one entity.
=> fix(sessions) Add a sessions storage without mandatory conditions

.dockerignore, .github/workflows/ci.yml, snuba/web/views.py
Docker builds do not seem to be using cache.  Instead, we push (and pull) a CI-only image to GitHub's Container Registry that will be used to make use of docker layer caching.
Changed the test jobs to depend on a new job that builds the snuba CI image. We tag this image with `latest`, `<commit sha>`, and `<branch>`. This should mean that the `Tests and code coverage` jobs and Sentry integration test will have all layers cached when they build the snuba image.
=> build(ci): Push a CI-only snuba image to make use of docker caching

Makefile, docs/source/contributing/environment.rst, scripts/lib.sh, scripts/pyenv_setup.sh
pyenv does not install python3.8.3 properly on big sur, making the dev env hard to set up
* port the [script](https://github.com/getsentry/sentry/blob/master/scripts/pyenv_setup.sh) from getsentry/sentry into this repo (with its dependencies)
* update the docs to remove virtualenvwrapper requirement from the environment setup
=> Add pyenv install script and clean up env setup docs

snuba/subscriptions/scheduler.py, tests/subscriptions/test_scheduler.py
Changed value for general mode to apply the jittered mode by default. Updated tests to reflect changes.
=> Subscriptions scheduler now applies jitter by default

snuba/cli/migrations.py, snuba/migrations/migration.py, snuba/migrations/operations.py, snuba/migrations/runner.py, snuba/migrations/snuba_migrations/events/0010_groupedmessages_onpremise_compatibility.py, snuba/migrations/snuba_migrations/events/0014_backfill_errors.py, snuba/migrations/snuba_migrations/transactions/0002_transactions_onpremise_fix_orderby_and_partitionby.py
The migrate, run and reverse commands in the migrations CLI now support
passing a log level parameter. By default it will be a bit more noisy
than it used to be, making it easier to figure out what happened if something
goes wrong during migration. As we build distributed mode this will become
more important as there are more things that can go wrong. It will also silence
some of the unnecessarily noisy output during test runs.
=> feat(migrations): Support passing log level in the migrations CLI

.github/workflows/ci.yml
We skip the build/push step of the snuba CI image for forks as the users will not be able to push to images to `getsentry` org and if we use the forks org, they may not have Actions enabled, so it could fail as well.
=> build(ci): Skip build/publish image for forks

snuba/cli/cleanup.py, snuba/cli/migrations.py, snuba/cli/optimize.py, snuba/clickhouse/http.py, snuba/clickhouse/native.py, snuba/clusters/cluster.py, snuba/migrations/runner.py, snuba/settings/__init__.py, snuba/settings/settings_distributed.py, tests/clusters/test_cluster.py, tests/migrations/test_table_engines.py, tests/test_split.py
=> Revert "Add params for secure ClickHouse connections."

snuba/query/snql/parser.py, tests/query/snql/test_invalid_queries.py, tests/query/snql/test_query.py, tests/test_snql_api.py
These aliases are only used to change the names used in the result output, they
are not used in the Clickhouse query itself.
=> feat(snql) Support column aliases in the select/groupby clauses

snuba/datasets/entities/discover.py
The extra metrics are throwing off the analysis, so properly exclude them.
=> fix(sampler) Only log callback metrics for allowed projects

snuba/replacer.py, tests/replacer/test_cluster_replacements.py, tests/replacer/test_load_balancer.py
https://github.com/getsentry/snuba/pull/2025 sends replacement INSERT queries to individual storage nodes to keep the data consistent after resharding. Before that INSERT queries were going to the query node and the distributed table.
That always preferred the first node of each replica set. As a consequence we are increasing the INSERT statement per second node too much when we have a spike of small replacements in the queue.
This adds a round robin load balancer to pick a different node for each INSERT to spread queries on the cluster. 
This load balancer could actually be made generic and added to the native clickhouse module.
=> feat(replacement) Load balance INSERT query to storage nodes to avoid overloading the first node of the replica set

snuba/clusters/storage_sets.py, snuba/datasets/storages/groupassignees.py, snuba/datasets/storages/groupedmessages.py, snuba/migrations/snuba_migrations/events/0007_groupedmessages.py, snuba/migrations/snuba_migrations/events/0008_groupassignees.py, snuba/migrations/snuba_migrations/events/0010_groupedmessages_onpremise_compatibility.py, snuba/pipeline/composite.py, snuba/pipeline/plans_selector.py, snuba/settings/__init__.py, snuba/settings/settings_distributed.py, snuba/settings/validation.py, tests/clusters/test_cluster.py, tests/clusters/test_storage_sets.py, tests/pipeline/test_selector.py
This change adds a new CDC storage set, which the groupedmessages
and groupassignee storages belong to.
Previously these storages were on the "events" storage set, same as
the errors table. This was wrong because it is impossible for
groupedmessages and groupassignee to share a ClickHouse cluster
and layout (by definition storages on the same storage set share
ClickHouse clusters). Specifically the issue is that errors
being a large table should be able to have more than 1 shard,
but because of the way CDC works, groupedmessages and groupassignees
will not work with more than 1 shard.
In order to solve this problem, we introduce JOINABLE_STORAGE_SETS,
predefined groups of storage sets that are allowed to be joined on.
Storage sets in a storage set group can have different local nodes but …
=> feat: Move CDC to a separate storage set, cross storage set joins

snuba/settings/__init__.py, snuba/web/query.py, tests/web/test_query_size.py
Updated the `create_query` span to include the size of the query in bytes, along with adding a tag to the transaction which groups the query into something easy to track for discovering trends in query sizes.
`create_query` span before:
`query`:
```
<query>
```
Now:
`query`:
```
<query>
```
`query_size_bytes`:
```
<size>
```
A new tag called `query_size_group` has been added to the transaction which groups the query into a 10% bracket of the maximum query size.
The value for this tag can be any one of the following depending on the query size:
```
>=0%, >=10%, >=20%, >=30%, >=40%, >=50%, >=60%, >=70%, >=80%, >=90%, >=100%
```
Clickhouse by default has a `max_query_size` of 256 KiB, which has been hardcoded as a setting in Snuba settings for this tag. It has no other use yet, but could …
=> Track Query sizes

snuba/clickhouse/query_dsl/accessors.py, snuba/datasets/entities/discover.py, snuba/datasets/storages/processors/replaced_groups.py, snuba/query/processors/project_rate_limiter.py, snuba/request/validation.py, tests/clickhouse/query_dsl/test_project_id.py
If there is a single org ID and/or project ID, tag that on the query so we can
do some analysis on a per project basis. If there are multiple projects this tag
doesn't work, so leave it blank.
=> ref(perf) Add tag for project/org id to transaction

snuba/query/processors/empty_tag_condition_processor.py
We weren't checking if a query had multiple empty tag conditions. If that happened, we would potentially only optimize some of the conditions, and randomly assign an experiment value to the partially optimized query. This ensures that we either optimize the entire query or none of it.
Since we weren't checking this, some queries might be partially optimized and then randomly attributed. That might explain some of the inconsistent results in the analysis.
=> fix: Handle multiple condition case in empty tag condition

snuba/query/joins/classifier.py, tests/query/joins/test_branch_cutter.py, tests/test_snql_api.py
If an expression that needed to be moved to a branch involved two different
columns it would cause an error.
=> fix(join) Fix case when an expression has multiple columns

snuba/clickhouse/formatter/expression.py, snuba/clickhouse/formatter/query.py, snuba/querylog/query_metadata.py, snuba/web/db_query.py, snuba/web/query.py, tests/clickhouse/test_formatter.py, tests/clickhouse/test_query_data.py, tests/clickhouse/test_query_format.py, tests/datasets/test_querylog_processor.py, tests/query/processors/test_arrayjoin_optimizer.py
Hackweek: We'd like to store clickhouse queries in bigquery for analysis, but right now there is a problem of potential PII in the queries. This PR adds a new formatter that strips queries of these literals and adds the new formatted sql to the querylog.
- Adds a new Expression Formatter that removes literal strings and integers
- Adds a new field sql_anonymized to ClickHouseQueryMetadata for sending to querylog
- Moves a bit of code around to facilitate specifying the expression formatter in formatter/query.py
=> feat: add anonymized clickhouse query sql to querylog

snuba/datasets/storages/errors_common.py, snuba/query/processors/table_rate_limit.py, snuba/state/rate_limit.py, tests/query/processors/test_table_rate_limit.py
Quick measure to limit the concurrency of the consistent queries on the errors table without impacting the rest of snuba which is fine.
This adds a rate limit config per table. It should be per cluster but that would require a larger change. The table is close enough.
So we can set a maximum concurrency per table.
It is applied to errors and errors_ro so far. If it works we can apply this to others but there does not seem to have been the need so far.
=> fix(concurrency) Add table rate limiter to partition the quota

snuba/datasets/storages/outcomes.py, snuba/datasets/storages/sessions.py, snuba/datasets/storages/transactions.py
This is still not ideal as it is per table but there are multiple tables per cluster. 
Though better than relying on the global rate limit. 
The next step will be to actually make it parametric so different storages can use the same cluster
=> fix(rate limiter) Add table rate limiter to every relevant table

snuba/datasets/querylog_processor.py, snuba/querylog/query_metadata.py, snuba/web/query.py, tests/datasets/test_querylog_processor.py, tests/web/test_project_finder.py
We lost the project id field with SnQL queries as the projects field in the request object was not there anymore.
This restores it by extracting from the query when the query metadata object is built.
The extraction is done through the `get_object_ids_in_query_ast` within a visitor to deal with nested queries.
=> fix(querylog) Restore the project id

Dockerfile
Debian 11 (bullseye) was released on 8/14. That was picked up by the python-3.8-slim docker image yesterday.
Bullseye does not seem to contain libffi6 anymore. It contains libffi7 instead. 
Upgrading this and trying to run the full CI pipeline to see if it works
=> fix(dockerfile) Switch from libffi6 to libffi7

cloudbuild.yaml
The CI pipeline is broken again on master.
It keeps timing out on the e2e test step.
=> fix(ci) Increase the timeout of master build

snuba/datasets/entities/events.py, snuba/datasets/entities/transactions.py, snuba/query/parser/validation/functions.py, snuba/query/processors/custom_function.py, snuba/query/processors/handled_functions.py, snuba/query/processors/performance_expressions.py, snuba/query/validation/__init__.py, snuba/query/validation/signature.py, tests/query/processors/test_apdex.py, tests/query/processors/test_custom_function.py, tests/query/processors/test_failure_rate.py, tests/query/processors/test_handled_functions.py, tests/query/validation/test_signature.py
Follow up from this comment: https://github.com/getsentry/snuba/pull/2044#discussion_r684524112. But also kind of went in a circle of what I thought this meant to what is actually in the PR at the end of the day. 
This PR refactors the following:
* Change the `FunctionCallValidator` to take a `data_source` instead of the `schema` (since the schema can just be take from the data source)
* Changes custom functions to get the data source columns from the `Query` in `process_query` instead of having it be instantiated with the `ColumnSet` 
* Introduces a `QueryEntityFinder` to get the `QueryEntity` and use it to look up any entity validators that we need
* In the case of the CompositeQuery, we cannot reliably get an entity so we return `None`, see comment …
=> refactor FunctionCallsValidator and FunctionCallValidator

snuba/clickhouse/translators/snuba/mappers.py, snuba/datasets/dataset.py, snuba/datasets/entities/discover.py, snuba/datasets/storages/discover.py, snuba/datasets/storages/errors_common.py, snuba/migrations/groups.py, snuba/migrations/snuba_migrations/discover/0007_discover_add_span_id.py, tests/datasets/test_discover.py, tests/query/processors/test_mapping_promoter.py
Discover queries by span_id where unwrapping the context column meaning we needed to store it.
DDL: 
```
ALTER TABLE discover_local ADD COLUMN IF NOT EXISTS span_id Nullable(UInt64) AFTER contexts;
```
=>  Add span_id to discover and promote it in discover, errors dataset

.github/workflows/ci.yml
We refactored [`setup-sentry`](https://github.com/getsentry/sentry/pull/28281) to be able to compose actions better. This workflow was only copying `setup-sentry` which now includes `setup-python`.
=> build(ci): Fix sentry integration test due to refactored actions

snuba/request/request_settings.py, snuba/web/db_query.py, tests/test_api.py
If the per-project rate limit kicks in often for a specific project, and the project does not apply any exponential backoff when retrying, we see an  unexpected increase in the global concurrent count.
I suspect this is due to this:
https://github.com/getsentry/snuba/blob/master/snuba/state/rate_limit.py#L170-L185
The global rate limiter is evaluated first and passes. At this point we bumped the number of global concurrent queries.
If the project rate limiter fails, when resetting the state of the global one we go through line 185 here https://github.com/getsentry/snuba/blob/master/snuba/state/rate_limit.py#L170-L185, which is the success case. 
That does not erase the query from redis, it pushes it back in time like if the query had been performed successfully.
So the query keeps getting …
=> perf(rate limiter) Move the global rate limit check after the project check

snuba/query/functions.py, snuba/subscriptions/data.py
**ifNull**
After adding in some missed functions in https://github.com/getsentry/snuba/pull/2067 there was still one function that was showing up in the datadog metics as not valid: `ifnull`. Datadog metrics tag values are always lowercased so we can't know what the original was, but it wasn't `ifNull` (otherwise it would have been found in `GLOBAL_VALID_FUNCTIONS` set.
In looking at ClickHouse docs, it looks like keywords are case-insensitive https://clickhouse.tech/docs/en/sql-reference/syntax/#syntax-keywords (but functions are often case sensitive). 
I tested out `ifnull`, `IfNull`, and `IFNULL` locally, and in the code it looks like we can confirm that https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/ifNull.cpp#L92-L95.
**other functions...?**
~It's not realistic to …
=> ref(validation): Change ifnull -> ifNull for consistency

snuba/datasets/outcomes_processor.py
This adds a new outcome type `5` which is reserved for recording events discarded on the client side.
Refs https://github.com/getsentry/relay/pull/1074
=> feat(outcomes): Added support for client reported outcomes

snuba/datasets/transactions_processor.py
As I was trying to determine where to trim the contexts column, I decided to split this function up for the following reasons:
1. It is over 200 LOC, I have a vertical monitor and cannot fit the whole function into it
2. There are ~20 variables in the same function scope, that seems dangerous
3. There is no separation between different domains of message processing, making it hard to know where you should modify what you need.
There is no change in functionality this is only a simple refactor
Note: the github diff will look a little strange. It may be better to read the file in its entirety to get a picture of what's going on
=> ref: Split up transactions processor into helper functions

snuba/datasets/errors_processor.py, tests/datasets/test_errors_processor.py, tests/datasets/test_events_processor.py, tests/fixtures.py, tests/migrations/test_runner_individual.py
We currently store trace_id and span_id in two places on the errors table:
* As columns
* As keys and values on the contexts table
The product expects both of these to be present
Add tests to make sure that if someone removes these it's intentional
=> Test that trace and span id are present where they are expected by the product

snuba/datasets/transactions_processor.py, tests/datasets/test_transaction_processor.py
We currently store trace_id and span_id in two places on the transactions table:
* As columns
* As keys and values on the contexts table
This storage is redundant and also non-compressible since these ids are randomly generated.
Solution
This PR makes it so the message processor that writes to the table drops it from the contexts table. It will not be queried due to the changes in #2074
Added to the test_transaction_processor test that validates trace_id and span_id being promoted to the column but not being stored in the contexts
If we start doing this, we have to make sure that we are no longer querying the contexts[trace.trace_id] column. This was verified in the querylog with the following query returning no rows:
```
SELECT COUNT (*) FROM (
SELECT
request_id,
referrer, …
```
=> Remove trace.[trace_id/span_id] from transaction contexts

snuba/datasets/outcomes_processor.py
There is a bad outcome in kafka right now.
```
{
category: 1, 
key_id: 51405, 
org_id: 1, 
outcome: 5, 
project_id: 11276, 
quantity: 7, 
reason: 'sample_rate', 
remote_addr: '178.43.250.103', 
source: 'relay-internal', 
timestamp: '+53677-08-05T22:29:06.000000Z'
}
```
=> Skip bad outcome

snuba/clusters/cluster.py, snuba/migrations/operations.py, tests/migrations/test_operations.py
Hi!
In this PR I fixed 2 problems for distributed clickhouse:
1) ADD INDEX **IF NOT EXISTS** When migration runs on the second node of clickhouse I get an error that index already exists
2) **SETTINGS replication_alter_partitions_sync = 2** I tried to understand why I can't finish migrations on clickhouse cluster and got an error "Metadata on replica is not up to date with common metadata in Zookeeper. Cannot alter". My colleague from Yandex Clickhouse helped me to understand, that migration runs a lot of alter operations and they don't have time to finish. He [improved a little bit error message](https://github.com/ClickHouse/ClickHouse/pull/29009/files). For clickhouse cluster we need [wait for actions to be executed on replicas](https://clickhouse.tech/docs/en/operations/settings/settin …
=> waiting until alter query to be executed on replicas

.pre-commit-config.yaml, requirements.txt, snuba/consumers/consumer.py, snuba/subscriptions/consumer.py, snuba/utils/streams/kafka_consumer_with_commit_log.py, tests/backends/confluent_kafka.py, tests/test_consumer.py, tests/utils/streams/test_kafka_consumer_with_commit_log.py
This change writes the timestamp of the original Kafka message
in the header of its commit log topic with the key `orig_message_ts`.
This timestamp is used as the basis for subscription scheduling and
having this in the commit log will enable subscriptions to no longer
need to consume the original topic in future, only the commit log.
This depends on https://github.com/getsentry/arroyo/pull/28,
https://github.com/getsentry/arroyo/pull/29 and a
new release of arroyo.
=> feat: Produce original message timestamp to commit log headers

.gitignore, snuba/query/validation/validators.py, tests/datasets/validation/test_subscription_clauses_validator.py, tests/subscriptions/test_data.py, tests/test_api.py
Increases the allowed number of aggregations in the select column for `sessions` subscription queries to two since in crash rate alerts, we'd like to be able to return the total count along side the aggregate
Corresponding change in Sentry https://github.com/getsentry/sentry/pull/28675
=> feat(subscription): relax validation on aggregations

.gitignore, snuba/cli/devserver.py, snuba/datasets/storages/sessions.py, snuba/redis.py, snuba/settings/__init__.py, snuba/utils/streams/topics.py
This PR:
- Adds subscription consumer for sessions dataset that will be used specifically for Crash Rate alerts behind settings  `ENABLE_SESSIONS_SUBSCRIPTIONS`
- Adds `SESSIONS_COMMIT_LOG` and `SESSIONS_RESULTS_SESSIONS` topics 
- Convert the `ingest-sessions` topic to have a `LogAppendTime` timestamp setting for subscription to work
=> feat(consumer): Add a subscription consumer for Sessions dataset

snuba/datasets/metrics.py, snuba/web/converters.py, snuba/web/views.py
The existing API endpoint `/tests/<dataset:dataset>/insert` allows writing data to the default entity of each dataset. In the case of metrics, this means that only `metrics_sets` can be written.
This PR introduces an additional endpoint `/tests/entities/<entity:entity>/insert`, which allows the client to define the target entity explicitly.
This is required to run tests in https://github.com/getsentry/sentry/pull/28598.
=> feat(web): Entity-specific insertion endpoint for tests

.pre-commit-config.yaml, requirements.txt, snuba/consumers/consumer.py, snuba/subscriptions/consumer.py, snuba/utils/streams/kafka_consumer_with_commit_log.py, tests/backends/confluent_kafka.py, tests/test_consumer.py, tests/utils/streams/test_kafka_consumer_with_commit_log.py
This is the same as the original version in https://github.com/getsentry/snuba/pull/2093 except it uses arroyo 0.0.4 which handles the case where the `orig_message_ts` header is missing when decoding messages. Previously, old messages still in the pipeline that were produced with an older version of arroyo would be missing the header which caused the consumer to crash. Once there are no more old messages in our pipeline we can enforce the presence of the header again.
=> feat: Add original message timestamp to commit log headers - take 2

snuba/query/validation/validators.py, snuba/subscriptions/data.py, snuba/subscriptions/entity_subscription.py, tests/datasets/validation/test_subscription_clauses_validator.py, tests/subscriptions/test_data.py, tests/test_api.py, tests/test_sessions_api.py
This PR:
- Adds the ability to set an entity specific number of allowed maximum aggregations for subscriptions in the `EntitySubscription` class
=> feat(subscriptions): Support entity max aggregations

.github/workflows/ci.yml
Snuba's Python version is 3.8, however, Sentry uses 3.6, thus, fixing it.
There's currently some integration tests failing to complete because it is
installing a newer version of psycopg2-binary which makes the tests fail.
See [this commit][1] for details.
[1]: https://github.com/getsentry/sentry/commit/3f71db8928bf6e20eb821026ad6713b4b043f2bf
=> fix(ci): Run Sentry integration tests with Python 3.6

snuba/state/rate_limit.py, snuba/subscriptions/data.py, tests/state/test_rate_limit.py
Before, if one rate limit hit its limit, then RateLimitExceeded would be thrown
and crucially, the __exit__ method would not be called on RateLimitAggregator.
Now the __exit__ method is manually called, and if this happens, all the rate
limiters that passed will have the query ID removed to ensure they aren't
counting queries that actually got limited.
=> fix(ratelimit) Decrement the count in all rate limiters if one limits

snuba/utils/metrics/backends/datadog.py
Its possible that some metrics are not being visible on datadog
because the packet format uses "|". Some parent_api tags have "|"
in them. This change replaces "|" to "_". Hopefully this fixes the
problem.
=> fix(metrics): Replace "|" with "_"

.github/workflows/ci.yml
I added the `USE_REDIS_INDEXER` env var to the snuba-integration tests [in Sentry](https://github.com/getsentry/sentry/blob/master/.github/workflows/snuba-integration-test.yml#L21) but didn't update in snuba to do the same.
=> fix(ci): Add USE_REDIS_INDEXER

snuba/settings/validation.py, snuba/utils/streams/topics.py
https://github.com/getsentry/sentry/pull/28431 Adds a consumer for the `ingest-metrics` topic that then translates the raw metrics data of strings for all the metric names, tag keys and tag values to integers. The translated messages will go in the `snuba-metrics` topic so that ClickHouse can store the metrics data.
=> ref(metrics): Change metrics topic name

snuba/state/cache/redis/backend.py, snuba/state/cache/redis/scripts/get.lua, snuba/utils/codecs.py, snuba/web/db_query.py, tests/state/test_cache.py, tests/web/test_result_cache_codec.py
We have a lot of ExecutionErrors happening for reasons that we don't really know. This PR reports those errors back to clients waiting for results of duplicate queries
If an exception happens serialize the exception using SerializableException and put that in redis. Deserialize it on the other side and re-raise it
* The code has unit tests but I'm wondering if there is a larger integration test I can/should write. Are there larger tests that I can take inspiration from?
=> Communicate read-through cache exceptions to waiting clients

snuba/cli/subscriptions.py, snuba/subscriptions/codecs.py, snuba/subscriptions/store.py, snuba/subscriptions/subscription.py, snuba/web/views.py, tests/subscriptions/__init__.py, tests/subscriptions/test_codecs.py, tests/subscriptions/test_scheduler.py, tests/subscriptions/test_store.py, tests/subscriptions/test_subscription.py, tests/test_api.py
The RedisSubscriptionDataStore now stores subscriptions by entity name instead
of dataset name. This is a step towards making all subscriptions based on
an entity rather than a dataset to align with our API. Since multiple
entities (such as events and transactions) are likely to eventually become
part of the same dataset, we should ensure that subscriptions are stored separately
for each entity even if they later become part of the same dataset.
Since all dataset and entity names for our current subscriptions are the same,
no migration is required.
=> feat(subscriptions): Subscription data store uses entity not dataset name

snuba/clickhouse/native.py
Keep track of the number of active connections per pod we have between api nodes and Clickhouse. 
This is meant to help in the investigation on the amount of health checks that we are sending to the query nodes.
=> feat(clcikhouse) Keep track of the number of connections from snuba to clickhouse

snuba/datasets/entities/discover.py, snuba/datasets/storages/transactions.py, snuba/migrations/groups.py, snuba/migrations/operations.py, snuba/migrations/snuba_migrations/transactions/0012_transactions_add_spans.py
Adds the nested columns for op, group, and exclusive span for suspect spans.
```SQL
Local operations:
ALTER TABLE transactions_local ADD COLUMN IF NOT EXISTS spans Nested(op LowCardinality(String), group UInt64, exclusive_time Float64) AFTER span_op_breakdowns.value;
ALTER TABLE transactions_local MODIFY COLUMN spans.op Array(LowCardinality(String)) TTL finish_ts + INTERVAL 1 MONTH;
ALTER TABLE transactions_local MODIFY COLUMN spans.group Array(UInt64) TTL finish_ts + INTERVAL 1 MONTH;
ALTER TABLE transactions_local MODIFY COLUMN spans.exclusive_time Array(Float64) TTL finish_ts + INTERVAL 1 MONTH;
ALTER TABLE transactions_local ADD INDEX IF NOT EXISTS bf_spans_op spans.op TYPE bloom_filter() GRANULARITY 1;
ALTER TABLE transactions_local ADD INDEX IF NOT EXISTS bf_spans_group spans.group …
```
=> feat(suspect-spans): Schema changes for suspect spans

snuba/subscriptions/codecs.py, tests/subscriptions/test_codecs.py
Currently subscription scheduling and executing are done together
in a single process by the subscription worker. Soon this will be
split into two separate phases with the scheduled subscriptions published
to a new Kafka topic to be subsequently picked up by the executors.
We will need to be able to serialize the scheduled subscriptions into
bytes so they can be produced to Kafka.
This PR introduces a SubscriptionScheduledTaskEncoder codec which can
encode a ScheduledTask[Subscription] into bytes and those bytes back
to a ScheduledTask[Subscription]. The encoder is not being used yet.
Note that the encoder does not support non SnQL subscriptions.
This is to avoid unnecessary complexity as legacy subscriptions
are expected to be deprecated and completely removed from our
codebase soon. …
=> feat(subscriptions): Add codec for scheduled subscription task

snuba/utils/serializable_exception.py, tests/utils/test_serializable_exception.py
Sentry sdk uses `str` to get the `value` field of an exception. SerializableException was not calling the `super` constructor and thus its `str` method was misbehaving. This PR fixes that
=> Fix deserialized exception message being swallowed by sentry

.github/workflows/ci.yml
Follow up needed when https://github.com/getsentry/sentry/pull/28914 is merged (these settings need to be consistent in both sentry and snuba)
Technically the indexer is no longer the redis one, I'm changing this to just be `USE_INDEXER` to indicate using the real one, vs the default which is the original mock indexer
https://github.com/getsentry/sentry/blob/bbb0afe520810d911b3d680b4a6338afd6057c23/src/sentry/conf/server.py#L1375
=> ref(sentry-metrics): USE_INDEXER

snuba/cli/subscriptions_scheduler.py, snuba/subscriptions/scheduler_consumer.py, tests/subscriptions/test_scheduler_consumer.py
Upon turning on the scheduler process in production for testing, we experienced
a lot of issues with invalid intervals. The lower bound of the interval constructed
by the CommitLogTickConsumer was frequently higher than the upper bound, which is invalid.
One potential cause of this could be messages being out of their expected order in
the commit log. Though this is known to be possible due to consumer crashes, rebalancing, etc
the frequency with whicih this appeared to happen seemed unusual.
This PR aims to change the scheduler consumer to simply collect more information about
commit log ordering to understand how common out of order messages might be.
For each message consumed, we simply record whether it is earlier or later than the
last one we received for that partition.
In order to …
=> feat(subscriptions): Use scheduler command to debug commit log issues (temporarily)

snuba/datasets/storages/errors.py, snuba/datasets/storages/events.py, snuba/datasets/storages/sessions.py, snuba/datasets/storages/transactions.py, snuba/datasets/table_storage.py, snuba/subscriptions/utils.py
The Kafka stream loader defines the scheduler watermark mode that applies to
the subscriptions on a specific storage. The scheduler mode is
associated in code with the storage / topic and should not need
to be changed by users when running subscriptions. Generally speaking,
"partition" mode will apply to semantically partitioned topics and
"global" mode applies for non semantically partitioned topics
where we will wait for all partitions to reach a timestamp before
executing the subscriptions associated with that particular timestamp.
The mode must be specified if subscriptions are supported for that storage.
=> feat(subscriptions): Add scheduler mode to stream loader

snuba/request/validation.py, snuba/web/views.py
We get query errors in sentry but can never figure out what the offending snql is unless we captured it in a trace. Since this is fairly important just put it in the breadcrumbs
=> Add the snql query to the breadcrumbs in sentry

.github/workflows/ci.yml
In https://github.com/getsentry/sentry/pull/29446 the `USE_INDEXER` env var has been removed, so we can remove that in snuba as well.
=> ref(ci): Remove USE_INDEXER env var

snuba/admin/slack/client.py, snuba/admin/slack/utils.py, snuba/admin/views.py, snuba/settings/__init__.py, snuba/settings/settings_test.py
Most basic of basic slack app to send notifications about changes to runtime config:
**updated config**: 
> ![Screen Shot 2021-11-02 at 5 00 32 PM](https://user-images.githubusercontent.com/15368179/139969674-01eda8cc-8986-46e3-a755-d853307e66f1.png)
**new config**:
> ![Screen Shot 2021-11-02 at 5 10 32 PM](https://user-images.githubusercontent.com/15368179/139969676-b82e7157-2819-4d9c-9607-f6b09b916236.png)
**removed config**:
>![Screen Shot 2021-11-02 at 5 16 41 PM](https://user-images.githubusercontent.com/15368179/139969690-24f83549-d798-4b29-bd75-d2f8c02263f5.png)
To test locally:
1. Have a test slack workspace you want to build the app on
1. Go to https://api.slack.com/apps and click on **Create New App** (create it on your test workspace)
1. Give your app a bot scope of …
=> Runtime changes slack notifications

snuba/query/snql/parser.py
This is to get more visibility into the breakdowns with the `build_request` span in Sentry, that sometimes seems to take a pretty long time without obvious reasons. 
What these added spans will look like in the Sentry product: 
> ![Screen Shot 2021-11-09 at 10 12 37 AM](https://user-images.githubusercontent.com/15368179/140980941-f76b9224-18de-4d37-89fe-385cc064453a.png)
=> Add more sentry logging to query parser

snuba/clickhouse/columns.py, snuba/utils/schemas.py
This change moves the shared column definitions from
`snuba.clickkhouse.columns` to `snuba.utils.schemas`. We will soon
be using these same column definitions for entities as well, and
we do not want to depend on the ClickHouse module as it is likely
to cause circular dependency issues.
The majority of this code has not changed, it is just copy and paste.
The ClickHouse column set now inherits from a base column set (which
currently does nothing). The same base class will also be used by
the entity column set class in the future.
=> ref: Move shared schema code out of ClickHouse module

snuba/web/query.py
Logging's makeRecord already has a parameter called name. When we use it
in extra info, exception is thrown.
Before
`Traceback (most recent call last):
File "/Users/nikharsaxena/workspace/snuba/.venv/lib/python3.8/site-packages/sentry_sdk/integrations/flask.py", line 90, in sentry_patched_wsgi_app
return SentryWsgiMiddleware(lambda *a, **kw: old_app(self, *a, **kw))(
File "/Users/nikharsaxena/workspace/snuba/.venv/lib/python3.8/site-packages/sentry_sdk/integrations/wsgi.py", line 140, in __call__
reraise(*_capture_exception(hub))
File "/Users/nikharsaxena/workspace/snuba/.venv/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 54, in reraise
raise value
File "/Users/nikharsaxena/workspace/snuba/.venv/lib/python3.8/site-packages/sentry_sdk/integrations/wsgi.py", line 133, in __call__ …
=> fix(logging): Don't use name in extra for log entries

snuba/datasets/errors_replacer.py
- Span tells us redis pipeline execution is the bottleneck
- Need to figure out why that is
- Possibly a correlation between size of results and time taken to execute
- Added a bunch of tags just to log the results
=> log(replaced_groups): Add tags PostReplacementConsistencyEnforcer span

snuba/datasets/entities/outcomes.py
- Enabling Sentry warnings for invalid queries on the outcomes entity caused a flood of warnings ~12k events in 10 minutes
- Disabled warnings on outcomes till we can figure out a way to sample or reduce number of events we log
=> fix(validation): Disable warnings on outcomes entity

snuba/datasets/storages/processors/replaced_groups.py, tests/datasets/test_errors_replacer.py, tests/test_api.py
- Replaced groups optimization surrounding replacement times caused some errors replacer API tests to break due to time zone difference
- Was not caught till tests were run locally on a machine not set to UTC
- Updated the time ranges for queries testing the replacer in the API tests
- Changes tested by setting timestamps to UTC, EST, and PST
=> fix(tests): Errors replacer tests

snuba/datasets/errors_replacer.py, tests/test_replacer.py
- Noticed `ProjectsQueryFlags.group_ids_to_exclude` is a sorted list of exclude group ids
- Only other place it's really used is for defining the list for the `group_id NOT IN` clause
- Can just be a set instead of sorted list, which makes it easier for upcoming changes surrounding group ids
- Changed `ProjectsQueryFlags.group_ids_to_exclude` to a `Set[int]` from a `Sequence[int]`
- Updated tests accordingly
=> ref(errors_replacer): Refactor `ProjectsQueryFlags.group_ids_to_exclude`

requirements.txt
**context:**
We introduced a new clickhouse cluster for metrics in https://github.com/getsentry/ops/pull/4118, however, this cluster runs a new version of clickhouse: 21.8.8 [latest (at the time) stable altinity version](https://docs.altinity.com/altinitystablebuilds/releasenotes/releases/21.8/). The old clickhouse-driver is not compatible with the new clickhouse version so we need to update the driver.
**Test Plan**
=> chore: upgrade clickhouse-driver to 0.2.2

snuba/clickhouse/http.py
On arm64 laptops we run a different docker image for clickhouse:
`altinity/clickhouse-server:21.6.1.6734-testing-arm`.
When running the tests against this image we'd get an error like:
```
______________________________________________________ ERROR at setup of TestApi.test_error_handler _______________________________________________________
Traceback (most recent call last):
File "/Users/dan/code/snuba/tests/test_api.py", line 50, in setup_method
self.generate_fizzbuzz_events()
File "/Users/dan/code/snuba/tests/test_api.py", line 148, in generate_fizzbuzz_events
self.write_events(events)
File "/Users/dan/code/snuba/tests/test_api.py", line 72, in write_events
write_processed_messages(self.storage, processed_messages)
File "/Users/dan/code/snuba/tests/helpers.py", line 21, in …
```
=> fix(tests): Fix tests in arm64

snuba/cli/devserver.py, snuba/clusters/storage_sets.py, snuba/datasets/entities/factory.py, snuba/datasets/factory.py, snuba/datasets/storages/factory.py, snuba/datasets/storages/metrics.py, snuba/settings/__init__.py, snuba/settings/settings_test.py, tests/migrations/test_runner.py
In preparation for sentry metrics to be tested out in production, we need to remove it from the `DISABLED_DATASETS` and other dev only settings. 
**BEFORE MERGING**
* This should be merged after we have the necessary provisions (https://github.com/getsentry/ops/pull/3977 and https://github.com/getsentry/ops/pull/4020)
* In addition, we need to make sure the clickhouse cluster is in the prod config (as well as the single tenant one: https://github.com/getsentry/single-tenant/pull/426) before merging.
=> ref(sentry-metrics): Enable metrics dataset

snuba/query/composite.py, snuba/web/query.py
- `snuba.api.query.count` metric had its `final` tag always set to `false`
- This is probably due to Snuba query `__final` attribute and `get_final()` being hardcoded to `False` and `set_final()` was never used
- After a Query is run through the pipeline, the results come with a `stats` dictionary that contains a `final` flag which tells us whether or not the Query will be final when passed to ClickHouse
- Updated the Query classes to appropriately use `set_final()` and `get_final()`, which should fix the metric issue
=> fix(metric): Restore final flag in Queries metrics

cloudbuild.yaml
https://github.com/getsentry/self-hosted/issues/796
Didn't touch migrations files as those are largely historical at this point.
=> Rename onpremise to self-hosted

snuba/subscriptions/entity_subscription.py, tests/subscriptions/test_entity_subscriptions.py, tests/subscriptions/test_subscription.py, tests/subscriptions/test_worker.py, tests/test_api.py, tests/test_sessions_api.py
Hacks out logic that has to do with legacy subscription and delegate subscription data classes since these have been removed
Follow up on #2169
=> ref(subscriptions): Deleting Legacy and Delegate Subscription logic

snuba/datasets/transactions_processor.py, tests/datasets/test_transaction_processor.py
As part of the migration for spans.exclusive_time from Float64 to Float32, start
emitting the new 32 bit column now. This is needed because
`input_format_skip_unknown_fields` allows Clickhouse to ignore extra unknown
fields but will error if the nested spans column is missing 1 or more columns.
Depends on #2232 so transactions processor does not error with the new column.
=> feat(suspect-spans): Start emitting spans.exclusive_time_32 column

snuba/cli/subscriptions.py, snuba/datasets/entities/factory.py, snuba/datasets/factory.py, snuba/subscriptions/subscription.py, snuba/web/views.py, tests/subscriptions/test_subscription.py, tests/test_api.py, tests/test_sessions_api.py, tests/test_writer.py
Decouples subscription creation and deletion logic from datasets to also consider entities since dataset to entity is not a 1-to-1 relation
=> ref(subscriptions): Decouple subscription logic from datasets [INGEST-627]

snuba/cli/subscriptions.py, snuba/subscriptions/codecs.py, snuba/subscriptions/data.py, snuba/subscriptions/scheduler.py, snuba/subscriptions/scheduler_load_testing.py, snuba/subscriptions/scheduler_processing_strategy.py, tests/subscriptions/test_codecs.py, tests/subscriptions/test_scheduler.py, tests/subscriptions/test_scheduler_processing_strategy.py, tests/subscriptions/test_task_builder.py, tests/subscriptions/test_worker.py
In order for the subscriptions executor to be able to handle more than one
entity on a scheduled topic we need to include the entity information into the
Kafka message. Currently the scheduled subscription task codec depends on
knowing the entity key in order to decode the message - this information will no
longer be available when more than one entity's subscriptions are in the same topic
(and will be passed via the executor CLI command).
Since the executor is not running yet and we are never decoding messages
we can safely make this change.
=> feat(subscriptions): Write entity to scheduled topic

snuba/cli/subscriptions_executor.py, snuba/cli/subscriptions_scheduler.py, snuba/subscriptions/executor_consumer.py, tests/subscriptions/test_executor_consumer.py
Subscription execution forms the second part of the subscriptions pipeline.
The executor's job is to consume the scheduled subscriptions from the scheduled
subscription topic, run the queries on ClickHouse and produce the results to
the results topic for Sentry.
This change simply introduces the executor CLI command. It builds the consumer
and processing strategy, however that strategy doesn't really do anything yet
except commit offsets. The processing strategies that are responsible for actually
running the query on ClickHouse and producing the results will be added separately.
Currently only a single dataset/entity pair is supported by the subscriptions
executor and a separate executor needs to be run for each entity.
=> feat: Add subscriptions executor command

snuba/subscriptions/scheduler_consumer.py, snuba/subscriptions/scheduler_processing_strategy.py, tests/subscriptions/test_scheduler_processing_strategy.py
Records a bunch of metrics in each of the subscription scheduler processing
steps. The goal of this is to get a sense of which processing steps are the
ones where the scheduler is spending the most time (and may be worth trying
to improve).
=> feat: Record timings in the subscription scheduler

snuba/subscriptions/scheduler_consumer.py, tests/subscriptions/test_scheduler_consumer.py
Previously we had hard coded GLOBAL mode in the scheduler for testing.
Now we are no longer always using global mode, instead the mode comes
from the stream loader and is specific to the storage definition.
=> feat(subscriptions): Use correct scheduling mode

snuba/cli/subscriptions_executor.py
Incorrectly copied from scheduler, we need to actually put the executor
metrics under a different namespace.
=> fix(subscriptions): Fix executor metrics namespace

snuba/cli/subscriptions_scheduler.py, snuba/settings/__init__.py
This change uses settings.SUBSCRIPTIONS_SCHEDULER_LOAD_FACTOR
as the default value for the load test. This allows us to
scale the load test up and down via code changes (and without
involvement from ops).
=> feat(subscriptions): Default load factor comes from settings

snuba/cli/subscriptions_executor.py, snuba/datasets/table_storage.py, snuba/subscriptions/executor_consumer.py, tests/subscriptions/test_executor_consumer.py
The executor command can now take multiple entities as long as those entities:
- match the dataset value which is passed
- have the same scheduled topic defined
- have the same result topic defined
In the future we may want to make this more flexible by providing a way to override
the scheduled and result topics - but for now they must all be the same in the code.
The entity name is not being used by the executor process yet. Later we will filter
scheduled subscriptions with entity names that do not match any of the values provided.
=> feat(subscriptions): Executor command takes multiple entities

snuba/subscriptions/codecs.py, snuba/subscriptions/data.py, snuba/subscriptions/executor_consumer.py, snuba/subscriptions/worker.py, tests/subscriptions/test_codecs.py, tests/subscriptions/test_executor_consumer.py, tests/subscriptions/test_worker.py
The next processing step after ExecuteQuery will be responsible for encoding the
SubscriptionTaskResult and producing it to the result topic. Since we are going to
reuse the SubscriptionTaskResultEncoder (from the existing pipeline) we need to use
the same SubscriptionTaskResult class (previously they were two distinct classes
in the old and new pipeline).
Since the future is already completed by the time we pass the task to the next step
we should also just submit the actual SubscriptionTaskResult instead of the
SubscriptionTaskResultFuture.
=> feat(subscriptions): Execute query submits SubscriptionTaskResult to next step

snuba/query/conditions.py, snuba/query/matchers.py, snuba/query/snql/parser.py, snuba/query/validation/validators.py, snuba/subscriptions/entity_subscription.py, tests/datasets/validation/test_subscription_clauses_validator.py, tests/query/test_matcher.py, tests/subscriptions/subscriptions_utils.py, tests/subscriptions/test_codecs.py, tests/subscriptions/test_entity_subscriptions.py, tests/subscriptions/test_subscription.py, tests/subscriptions/test_worker.py
This PR:-
- adds MetricsCountersEntitySubscription class to create crash rate alerts for metrics which accepts a maximum of 3 aggregations and accepts a group by clause 
Group by clause is required here because:
- This is the Snql query that currently gets crash free percentage from metrics
https://github.com/getsentry/sentry/blob/1564d0e3c6a421721d211b3e87fdd786ec7959f3/src/sentry/release_health/metrics.py#L217-L232
And this query returns a json that looks like this 
```
[{‘project_id’: 56, ‘tags[320]’: 321, ‘value’: 2.0}, {‘project_id’: 56, ‘tags[320]’: 328, ‘value’: 1.0}]
```
If we were to remove the group by clause, we would merely get something that looks like this 
```
[{'value': 10.0}]
```
Which doesn't really help us determine the crash free percentage as this is merely the total …
=> feat(metric-alerts): Add MetricsCountersSubscription [INGEST-625]

snuba/subscriptions/executor_consumer.py, tests/subscriptions/test_executor_consumer.py
This change adds the ProduceResult strategy. It's job is to take a
SubscriptionTaskResult, encode the message to a Kafka payload and produce
it to the provided result topic. Once producing is done, offsets are
committed. This strategy is designed to be chained together with the
ExecuteQuery strategy (which provides the SubscriptionTaskResult) in the
subscriptions executor.
The approach taken is very similar the ProducedScheduledSubscriptionMessage
strategy in the subscription scheduler which encodes and produces the
messages for the scheduled topic.
This change only adds the strategy - it is not being used anywhere yet
and will be integrated into the executor as a follow up.
=> feat(subscriptions): Add the strategy to produce a subscription result

snuba/admin/clickhouse/system_queries.py
Rather than enforce using the main query node, validate by the list of nodes in the ClickHouse cluster
=> feat(admin): validate by node list in query admin tool

snuba/admin/clickhouse/system_queries.py
Support queries like 'WHERE some_column LIKE '%something%'
=> feat(admin): Allow % in extra part of system query

snuba/subscriptions/executor_consumer.py
Currently if the executor sample rate is set to 0 we don't send any events
through the processing strategy or commit any offsets. In our dashboards
the lag grows continuously dwarfing all other topics/consumer groups.
This adds a temporary workaround that just always commits offsets for every
message if the sampling rate is 0. We can remove it once we actually start
processing executor messages.
=> feat: Commit offsets on subscription executor if sample rate is set to 0

.freight.yml
Just noticed that https://github.com/getsentry/snuba/commit/ffad626c8e8701fc5bddcdc6d8a84c508c8c90b7
didn't get deployed since we never actually added the executor here.
=> feat(freight): Deploy subscriptions executor with Freight

snuba/query/processors/mapping_optimizer.py, tests/query/processors/test_mapping_optimizer_no_useless_conditions.py
The redundant clause optimizer was capturing when it was applying the optimization but not when it wasn't. This made analyzing its effects difficult
At the moment the optimization is supposed to be applied, add an experiment value for when it is not.
=> Fix redundant clause optimizer not capturing experiment data

tests/fixtures.py, tests/migrations/test_runner_individual.py, tests/test_cli.py, tests/test_snql_api.py, tests/test_transactions_api.py
This is mostly fixing a bug with our current tests, where in the old version of
Clickhouse the events are not being merged before the tests run. In the new
version of Clickhouse the events are merged before the tests, and since the
fixtures all use the same span_id, they are actually only sending one event.
=> fix(arm64) Fix tests so they work on arm64 as well

snuba/settings/validation.py
=> feat(subscriptions): Adds metrics topics to topics validation

.pre-commit-config.yaml
Prefer https:// over git://.
See: https://github.blog/2021-09-01-improving-git-protocol-security-github/#when-are-these-changes-effective
=> use https instead of git

snuba/clusters/cluster.py, snuba/clusters/storage_sets.py, snuba/datasets/entities/transactions.py, snuba/datasets/storages/__init__.py, snuba/datasets/storages/factory.py, snuba/datasets/storages/transactions.py, snuba/datasets/storages/transactions_ro.py, snuba/settings/__init__.py, snuba/settings/settings_distributed.py, tests/clusters/test_cluster.py, tests/datasets/test_transactions.py
Add a read-only mode to transactions via a new `transactions_ro` storage.
It should be settable via a global flag or by a referrer list in `snuba.settings`.
https://getsentry.atlassian.net/browse/SNS-990
=> feat(ops): add transactions_ro storage support

snuba/subscriptions/scheduler_processing_strategy.py
The new subscriptions scheduler is not shutting down the producer when it terminates. 
This would make the scheduler hang waiting when we close it. 
This fixes it.
=> fix(subscriptions) Fix the shutdown process of the scheduler

snuba/datasets/storages/errors_common.py, snuba/datasets/storages/transactions.py, snuba/query/expressions.py, snuba/query/processors/uniq_in_select_and_having.py, tests/datasets/test_context_promotion.py, tests/datasets/test_tags_hashmap.py, tests/query/processors/test_uniq_in_select_and_having.py, tests/query/test_expressions.py
This is a hacky query processor put in for the purpose of
mitigating clickhouse crashes. When a query is sent to clickhouse
which has a `uniq` in the `HAVING` clause but not in the `SELECT`
clause, the query node will crash. This may be fixed with future versions
of clickhouse but we have not upgraded yet. This exists as a check so that we
return an exception to the user but don't crash the clickhouse query node
* add query processor to catch this case, make it throw an exception
* Add query processor to transaction storage 
* General approach, is it acceptable?
* Any other cases I should test for?
* What's a good way to dry run it? My thought is to send the error to sentry when it happens, hide this behind a runtime config
=> Enforce uniq in HAVING and SELECT

snuba/subscriptions/executor_consumer.py, snuba/subscriptions/scheduler_processing_strategy.py, tests/subscriptions/test_executor_consumer.py
https://github.com/getsentry/snuba/pull/2332 was the wrong way to fix the shutdown issue.
The producer was already being closed in the CLI script. 
Closing it in the strategy actually was counter productive because it would not be reopened in case of rebalancing crashing the consumer.
This removes the close statements from the processing strategies and relies on the one at the end of the script. It also add a similar close statement to the test.
=> fix(scheduler) Remove the shutdown of the producer from the strategy

snuba/admin/clickhouse/system_queries.py
snuba-admin currently does not provide mechanisms to run queries which
have math operators in them. The change allows those operators.
Here's the test showing that the match happens
```json
[
[
{
"content": "SELECT toUInt8(toMonday(now()) - toMonday(min(min_time))) / 7 AS weeks_ago, table, count() AS count, sum(bytes_on_disk) AS size FROM system.parts WHERE (min_time > (now() - ((90 * 3600) * 24))) AND (min_time < now()) GROUP BY toMonday(min_time), table ORDER BY table ASC, toMonday(min_time) DESC",
"isParticipating": true,
"groupNum": 0,
"groupName": null,
"startPos": 0,
"endPos": 295
},
{
"content": "SELECT",
"isParticipating": true,
"groupNum": 1,
"groupName": 1,
"startPos": 0,
"endPos": 6
},
{
"content": "toUInt8(toMonday(now()) - toMonday(min(min_time))) / 7 AS weeks_ago, table, …
```
=> fix(admin): Allow math operators

.freight.yml
Since `executor_sample_rate` is currently set to 0, this won't run any ClickHouse queries
or attempt to produce anything, just committing offsets.
According to https://github.com/getsentry/snuba/pull/2323 there was an issue that was
not diagnosed when we attempted to do this last month. Giving it another shot so we
can at least get hold of the stack trace even if this still fails.
=> feat: Deploy subscription executor

snuba/datasets/storages/transactions.py, snuba/query/processors/array_has_optimizer.py, tests/query/processors/test_array_has_optimizer.py
SnQL only allows for conditions of the form `LHS OPERATOR RHS`. This means that
conditions like `has(column, value)` are currently illegal, and has to be
written as `has(column, value) = 1` to satisfy this constraint. This causes
problems with Clickhouse when it's not able to use the bloomfilter index for
these conditions. This change rewrites such conditions to remove the surrounding
`... = 1` so that Clickhouse is able to properly leverage the bloomfilter index.
=> feat(suspect-spans): Add array has processor

snuba/subscriptions/executor_consumer.py
We need to make sure we commit offsets during rollout so our Kafka offset
does not go out of retention. Currently if the sample rate is set to
zero we will never commit.
=> feat(subscriptions): Ensure that we commit if the sample rate is zero

snuba/subscriptions/executor_consumer.py
crc32 can be a bit slow. Since we are constantly running this function
on the same set of subscription IDs, lets cache the results.
=> feat(subscriptions): Cache crc32 subscription ID

snuba/subscriptions/scheduler.py, snuba/subscriptions/scheduler_processing_strategy.py, tests/subscriptions/test_task_builder.py
This function seems to be taking a really long time relative to other parts
of the scheduler. This change adds a bunch of timings to this function to see
if we can isolate the issue further.
Also cleans up a couple metrics we were previously recording but don't need anymore.
=> perf(subscriptions): Add metrics to SubscriptionScheduler.find()

snuba/subscriptions/scheduler.py, tests/subscriptions/test_task_builder.py
The metrics introduced in https://github.com/getsentry/snuba/pull/2362
were a bit too much and themselves actually caused the subscription scheduler
to be unable to keep up. This removes the part that attempts to record a metric
for every single task that is built.
=> fix(subscriptions): Do not record metric for building every task

snuba/clickhouse/http.py, snuba/consumers/consumer.py, snuba/datasets/schemas/tables.py, snuba/datasets/storage.py, snuba/datasets/storages/errors.py, snuba/datasets/table_storage.py, snuba/processor.py, tests/clickhouse/test_http.py, tests/test_consumer.py
This is necessary for an upcoming change which will write aggregate expressions directly in the insert.
Functional changes:
- support for inserting using the VALUES format (https://clickhouse.com/docs/en/interfaces/formats/#data-format-values) at the WritableTableStorage level
- support in the multistorage consumer for serializing to the VALUES format (including a new ValuesRowEncoder)
- added a new type of return from processing called `AggregateInsertBatch` to indicate to callers that the data being returned needs to be interpreted by Clickhouse (e.g. it can contain function call expressions)
This was split out of https://github.com/getsentry/snuba/pull/2346 to be more readable (without the additional metrics changes). There will be an upcoming PR based off this one to support direct …
=> feat(consumer): Add support for VALUES format when writing to ClickHouse

snuba/cli/subscriptions_executor.py, snuba/subscriptions/executor_consumer.py, tests/subscriptions/test_executor_consumer.py
The executor shouldn't be shutdown by the strategy since it is only
created once and passed in. This caused the executor to be incorrectly
shut down in some scenarios, e.g. rebalancing. Now we only shutdown
the executor when the process is interrupted or terminated.
=> fix(subscriptions): Fix executor shutdown

snuba/admin/clickhouse/nodes.py
We have the TRANSACTIONS_V2 storage set now which is not assigned to
a cluster in settings yet. This causes the /clickhouse_nodes API call to fail.
This fixes that by just returning an empty list for that storage.
=> fix(admin): Support unassigned storage sets

snuba/admin/clickhouse/nodes.py
https://github.com/getsentry/snuba/pull/2365 did not fix the entire
problem since the issue also arises when we try to get the local table
name. This is a quick fix that manually excludes transactions_v2 from
the storage list so that the /clickhouse_nodes api call succeeds even
if it is not assigned to a storage set.
=> fix(admin): Fix fetching storage nodes (again)

snuba/admin/clickhouse/common.py, snuba/clusters/cluster.py
The is_valid_node function previously only checked if the node
being queried was a valid local node since we only currently query
local nodes for system qeuries. Now we need to allow the
query node as well since this is what the tracing tool uses.
This fixes a bug introduced in https://github.com/getsentry/snuba/pull/2366
when we switched over to use the readonly user.
=> fix(tracing): Fix querying the query node in the tracing tool

snuba/admin/static/collapse.tsx
This adds a collapse UI component to be used in the admin tool.
This is designed to be used to render query history in the system
queries and tracing tool, and replace the table within a table
layout that we have there now. It is not being used anywhere
yet and will be integrated in the future.
It takes a header as text and the body can be any react component.
Example usage:
```
<Collapse text="Some text header">
<div>Some react component</div>
</Collapse>
```
Preview with a table inside:
=> feat(admin): Add a new collapse component

snuba/datasets/discover.py
This warning isn't providing any actionable value. The metrics will stay in
place, and as the data model in the SDK is rolled out these numbers should
drop down.
=> fix: Remove impossible query warning

bin/mocks/mock-subscriptions
I needed to build this as part of load testing the scheduler
in https://github.com/getsentry/snuba/pull/2387 and although most
of those other changes will be thrown away, I think this part may be
worth keeping. I wanted an easy way for everyone to be able to get
mock subscription data into Snuba for dev and load testing and right
now it's a bit of a hassle.
=> feat(dev): Mock data for subscriptions

snuba/clickhouse/native.py
Increase clickhouse request retry count by 1 to mitigate connectivity issues we've been experiencing in production
=> fix(conn) - increase retry count by 1 in ClickhousePool.execute

snuba/subscriptions/scheduler.py
The delegate task builder is much slower than using the immediate
or jittered one since it has to check which mode to apply for
every subscription within the tick individually. This change uses
the immediate or jittered task builder directly for the whole tick
if we are not in a transition mode. This is checked at the start
of each tick.
=> perf(subscriptions): Avoid slow delegate task builder where possible

snuba/subscriptions/codecs.py
Since legacy subscriptions are deprecated, we no longer need this assertion.
Once this is removed and the executor is deployed with this change, we can
go a step further and remove the "type" from the scheduled subscription payload
completely.
=> ref(subscriptions): Remove unnecessary assertion

snuba/admin/clickhouse/common.py, snuba/admin/clickhouse/system_queries.py, snuba/admin/clickhouse/tracing.py, snuba/clusters/cluster.py
None of the system queries work currently because we are attempting to run them
with readonly=2 but we have only configured readonly=1 for this user.
Since system queries do not actually need the expanded permissions that come with
readonly=2 (ability to change settings queries) just run them with them readonly=1
instead. Tracing still runs with 2.
=> fix(admin): Fix the system query tool

snuba/datasets/entities/discover.py, tests/test_discover_api.py
Removes unused code related to originally rolling out the Discover entity.
Doesn't seem to have been used for quite a long time.
=> ref: Clean up old Discover entity rollout code

tests/test_discover_api.py
We don't use `snuplicator-sampling-rate` config anymore, remove
any reference to it from the test.
=> ref: Remove another old config from test

bin/mocks/mock-subscriptions, snuba/subscriptions/codecs.py, snuba/subscriptions/data.py, snuba/subscriptions/subscription.py, tests/subscriptions/subscriptions_utils.py, tests/subscriptions/test_codecs.py, tests/subscriptions/test_data.py, tests/subscriptions/test_executor_consumer.py, tests/subscriptions/test_partitioner.py, tests/subscriptions/test_scheduler.py, tests/subscriptions/test_scheduler_consumer.py, tests/subscriptions/test_scheduler_load_testing.py, tests/subscriptions/test_scheduler_processing_strategy.py, tests/subscriptions/test_store.py, tests/subscriptions/test_subscription.py, tests/subscriptions/test_worker.py
This PR does 2 things:
1. Consolidates the SubscriptionData class into a single one, instead of a SnQLSubscriptionData
class which inherits from a SubscriptionData class which inherits from another _SubscriptionData class.
Since don't need to support non-SnQL subscription data anymore so we don't need the base class.
2. Moves validation out of `__post__init__` into a separate validate() function. The validate() function
is now only called upon initial creation of the subscription and not every single time it's loaded from
the store or decoded from already scheduled task data.
=> perf(subscriptions): Simplify SubscriptionData, only validate on creation

snuba/datasets/entities/events.py, snuba/query/processors/object_id_rate_limiter.py, snuba/state/rate_limit.py, tests/query/processors/test_referrer_rate_limiter.py
Add the ability to rate limit based on referrer.
`referrer_per_second_limit_{referrer_name}`
`referrer_concurrent_limit_{referrer_name}`
This allows us to shed load when a specific referrer is putting too much strain on the system. It should only be used in emergencies
=> feat(ratelimits): Referrer based load shedder

snuba/query/functions.py
Some of the proposed metrics queries are doing MergeIf functions instead of just
If functions. Add that prefix to list of allowed functions.
=> fix(functions) Add MergeIf as a valid function suffix

cloudbuild.yaml
See https://github.com/getsentry/sentry/pull/31950 for more details.
=> ci: Change machineType for Google Cloud Build to E2_HIGHCPU_8

snuba/cli/replacer.py
In order to run replacements on the errors_v2 storage, we need to allow passing it as a command line option. This PR does exactly that.
=> fix(replacer): Add errors_v2 storage option

snuba/web/db_query.py, tests/datasets/test_querylog_processor.py, tests/test_snql_api.py
The stats of each query in the query list will now have an "error_code" field if
the query failed in Clickhouse.
=> ref(querylog) Add the Clickhouse error code to the querylog stats

snuba/datasets/entities/clickhouse_upgrade.py, snuba/datasets/entities/events.py, snuba/settings/__init__.py, tests/datasets/entities/test_clickhouse_upgrade_rollout.py, tests/datasets/test_upgrade_selector.py
This includes most of what is needed to direct a portion of errors queries to the new storage `errors_v2`.
It uses the PipelineDelegator to run two queries in parallel and compare the results.
It introduces `RolloutSelector` to define the rollout policy. So we can control the amount of queries that go to `errors_vs` by referrer and rely on `errors_v2` for the production results when needed.
Still to do:
- add a callback to compare the results
- register errors_v2_ro
=> feat(errors upgrade) Set up query path for the errors v2 storage

snuba/datasets/entities/clickhouse_upgrade.py, tests/datasets/entities/test_clickhouse_upgrade_callback.py
Fix the logging condition.
I was logging average matches and low matches even in case of perfect matches because the if statement was wrong.
If the match was perfect but the log was not rolled out for that case I would end up logging a low match by mistake.
=> fix(similarity) Fix logging again

snuba/cli/cleanup.py, snuba/cli/optimize.py
In order to run the cron jobs on the new storages we need to allow
passing in the new storage
=> fix(cron): Allow transactions_v2 storage for cron jobs

snuba/optimize.py
We don't have any metrics for `snuba optimize`. This change adds a metric
which records the timing for each part that is optimized.
=> feat: Add a metric to track how long optimize takes

Makefile, mypy.ini
sentry's makefile uses [`backend-typing`](https://github.com/getsentry/sentry/blob/master/Makefile#L133) so I thought it might be nice to just keep the same naming even though we don't have much of a frontend except for admin
=> ref(makefile): Add backend-typing

snuba/admin/clickhouse/nodes.py
We needed to include this hack earlier because of the way transactions_v2 was rolled out
(included in code before added to cluster settings). This is no longer the case and we
want to see transactions_v2 in snuba admin so removing it.
=> fix: Remove transactions v2 hack from Snuba admin

snuba/datasets/errors_replacer.py, snuba/replacer.py, snuba/replacers/replacer_processor.py, tests/replacer/test_cluster_replacements.py
- We're adding a new consumer group for replacements
- We'd like to see replacements metrics split by consumer groups and update some alerts
=> metrics(replacer): Consumer group per replacement processed

snuba/query/processors/prewhere.py, tests/query/processors/test_prewhere.py
We identified some queries that can cause a segfault on the clickhosue server if this pattern is present.
```
SELECT
uniq(something)
PREWHERE something = 'asd'
```
The issue is probably narrower than that but this is the first step to prevent this from happening.
Basically if a column is in a uniq expression anywhere in the query, it will become ineligible for prewhere
=> fix(prewhere) Exclude columns from the prewhere candidates if they are in a uniq expression

snuba/web/__init__.py, snuba/web/query.py, tests/test_snql_api.py, tests/web/test_results.py
There are checks to make sure that different expressions can't have the same
alias, so the only way to hit the warning case when building the response is
an edge case where the same expression has two different aliases. Currently
in that case we would log a warning and only return one of the columns in
the response. Instead, don't log a warning and return both columns with
the same values.
=> fix: Avoid warning on duplicate aliases

snuba/clusters/storage_sets.py, snuba/datasets/entities/events.py, snuba/datasets/storages/__init__.py, snuba/datasets/storages/errors_v2_ro.py, snuba/datasets/storages/factory.py, snuba/settings/__init__.py, snuba/settings/settings_distributed.py
The PR enables errors_v2_ro storage which is a readable storage which
would be selected if consistent queries are not required.
=> feat(errors_v2): Support readonly storage for errors_v2

snuba/datasets/entities/events.py, snuba/pipeline/settings_delegator.py, snuba/query/processors/quota_processor.py, snuba/request/request_settings.py, snuba/state/quota.py, snuba/web/db_query.py, tests/query/processors/test_quota.py
Configuring the rate limiter works to protect the system though it does not help when we have continuous moderate load that is far from being limited by concurrency. By having low concurrency every query uses a large amount of threads.
This is ok for the UI for a short period of time, but it is a problem when it comes from script that hit the api continuously. 
This allows to manually set the max thread config setting by runtime config and reduce quota for specific referrer/projects.
A further improvement would be to support a proper quota system where the max_thread field is calculated based on the past behavior of the project and adapted to enforce a quota over a period of time.
=> perf(quota) Make max thread configurable per referrer and project

cloudbuild.yaml, snuba/query/snql/parser.py, tests/datasets/test_metrics_processing.py, tests/query/parser/test_query.py, tests/query/snql/test_query.py, tests/query/snql/test_query_column_validation.py, tests/query/snql/test_snql_anonymizer.py, tests/test_api.py, tests/test_snql_api.py
If a non-Column expression inside a SelectedExpression does not have an alias
assigned, give it the same expression as the SelectedExpression, which in this
case is the raw string passed into the parser.
This prevents a warning later that an expression is missing an alias when the
results are being processed. Once this is out and working I will remove the
warning here: https://github.com/getsentry/snuba/blob/master/snuba/web/query.py#L256
=> fix(snql) Correctly assign aliases to expressions with none

snuba/cli/consumer.py, snuba/cli/multistorage_consumer.py, snuba/cli/test_consumer.py, snuba/consumers/consumer_builder.py
This is basically the same thing as https://github.com/getsentry/snuba/pull/2245, but applied to the multistorage consumers. (again for reference, the stats definitions for librdkafka can be found [here](https://github.com/edenhill/librdkafka/blob/master/STATISTICS.mdl)). 
* **cli command vs. runtime config**: ~we could limit by consumer group in the runtime config, but there can be multiple consumers in the same consumer group so for now I just want to be able to test reporting these metrics for specific consumers to make sure things look ok~ Changed to use the runtime config, lets try it out with a low risk consumer group and go from there
* **more stats metrics**: testing locally `replyq` seemed to be the correct metric for queue size. As for other stats metrics, I don't think I …
=> ref(consumer-util): add replyq metric to multistorage consumer

snuba/cli/replacer.py, snuba/datasets/errors_replacer.py, snuba/datasets/storages/events.py, snuba/replacers/replacer_processor.py, snuba/settings/validation.py, snuba/utils/streams/topics.py, tests/datasets/storages/processors/test_replaced_groups.py, tests/test_replacer.py
Events storage is deprecated, remove the ability to run a replacer
on it and simplify errors replacer code.
Most of the tests in test_replacer.py were already duplicated in
test_errors_replacer.py so could be deleted.
=> ref: Remove the ability to run a replacer on the events storage

tests/test_api.py
It's not going to pass since we don't return `row_read` and `bytes_read`
in stats.
=> ref: Remove failing test

snuba/subscriptions/scheduler_processing_strategy.py
We are experiencing an issue with the metrics scheduler where offsets
are not being committed regularly. Not sure yet what the root cause of
this is. This metric is intended to help determine whether the issue
is in the ProduceScheduledSubscriptionMessage or if it occurs earlier.
=> feat(subscriptions): Add a metric for debugging

snuba/subscriptions/scheduler_processing_strategy.py
There are some indications that the ProvideCommitStrategy may not
be working exactly as it should. In particular, it is not marking
`should_commit=True` when it should be.
I'm not sure exactly where the error occurs yet, this change adds some
temporary metrics to help debug this.
=> feat: Add metrics to help debug ProvideCommitStrategy

snuba/subscriptions/scheduler_processing_strategy.py
This metric seems to have been recorded incorrectly. It was indented
wrong causing it to be fired on every iteration of the loop instead of once
per tick.
=> fix(subscriptions): Fix recording partition lag

snuba/cli/multistorage_consumer.py, snuba/consumers/consumer_builder.py
We don't necessarily want to set the config individually for each consumer group
for how often stats are collected, as it pollutes our config and it is easier to
use reasonable default values across all consumers. This change adds a default config
`stats_collection_freq_ms`, which is applied if a config is not specified for the
specific consumer group.
=> feat: Add a default value for stats_collection_freq_ms

snuba/datasets/entities/profiles.py, snuba/datasets/profiles_processor.py, snuba/datasets/storages/profiles.py, snuba/migrations/snuba_migrations/profiles/0001_profiles.py, tests/datasets/test_profiles_processor.py
After some round of testings, we realized a few things:
- we don't need to store the symbols separately as the symbolicated version will be store in the profile column.
- we need to have an ID specific to the profile and not just copy the transaction_id
- `received` is a timestamp in Relay and there's no need to transform it as a RFC3339 string along the way to be parsed here as such, might as well just parse it as a timestamp here
=> feat(profiling): Add and remove some fields

snuba/migrations/groups.py, snuba/migrations/snuba_migrations/metrics/0021_polymorphic_bucket_materialized_views.py, snuba/migrations/snuba_migrations/metrics/templates.py
This creates the 3 materialized views necessary for the polymorphic metrics input table.
I tested locally that this creates correct values in the aggregate tables for all 3 types.
If people don't find this to be "interesting" or useful enough on its own, I can do a PR that also includes the application processing logic and therefore uses that polymorphic table end to end
Follow-up of https://github.com/getsentry/snuba/pull/2504
The storage writer that lives on top of this: https://github.com/getsentry/snuba/pull/2510
=> feat(metrics) - create materialized views for polymorphic input tables

snuba/datasets/storages/__init__.py, snuba/datasets/storages/metrics.py
The key and value of the enum in StorageKey need to be identical. This caused an issue when trying to deploy an ops change to run the metrics_raw consumer (https://getsentry.atlassian.net/browse/OPS-1481)
Tested locally that `snuba multistorage-consumer --storage=metrics_counters_buckets --storage=metrics_distributions_buckets --storage=metrics_buckets --storage=metrics_raw --consumer-group=metrics_group` starts successfully
=> fix(metrics) - fix storage key for metrics_raw

snuba/consumers/consumer.py
We are logging a latency metric between clickhouse write an message timestamp at every message. This seems to contribute to up to 1 second latency for every batch, and likely it is the cause of some hard to explain backlog events.
The idea is to only log one latency per batch, as our SLO should be based on the max latency. 
Before replacing the existing metric, this PR starts by recording the max latency and the avg latency per batch to compare how consistent is with the current metric. If it is close enough, we can replace the existing one.
=> perf(consumer) Prepare to remove the latency metric at every message

snuba/web/__init__.py, snuba/web/query.py, snuba/web/views.py, tests/test_api.py, tests/web/test_query_size.py
- Currently when a query is too long for ClickHouse to process, we find out when we attempt to process it and ClickHouse tells us `Max query size exceeded.` We log this as an Error in Sentry
- With these changes Snuba will validate the size of the query and respond with a `400` (and an appropriate message) if the query size exceeds the max.
- Introduced a `QueryTooLongException`
- Snuba API responds with a 400 when query is too long
- Got rid of `>=100%` query size group span tag in favor of `100%` as the maximum possible size group
=> fix(query): Long queries rejected at Snuba level

snuba/cli/consumer.py, snuba/cli/multistorage_consumer.py, snuba/cli/test_consumer.py
Since there are benefits of using the parallel collect, we should turn
it on by default for all the consumers.
=> perf(consumers): Turn on parallel collect by default

snuba/pipeline/settings_delegator.py, tests/pipeline/test_settings_delegator.py
The current RateLimiterDelegate class has an issue: it replicates the state of the class it delegates to in order to keep the list of transformed rate limiter settings. 
This is not a great practice as it assumes the behavior of the delegate class is compliant with `HTTPRequestSettings`, thus breaking its abstraction. 
`SubscriptionRequestSettings` behave differently: it returns nothing as rate limiter config no matter what you add to it. So in practice `RateLimiterDelegate` does not respect its behavior because it overrides this behavior.
This has two negative consequences:
- functionally `RateLimiterDelegate` is not compliant with what `SubscriptionsRequestSettings` thus adding a rate limiter on subscriptions.
- In terms of performance it triggers the rate limiter infrastructure on …
=> perf(pipeline delegator) Reduce impact of rate limiter delegator on SubscriptionRequestSettings

.freight.yml
Not sure if I got this right, but we've got a k8s diff showing up in `master` due to something similar to https://github.com/getsentry/snuba/pull/2458.
Diff:
```diff
ops/k8s on  master via 🐍 v3.10.2 (.ops-venv) on ☁️  michael@sentry.io(us-central1) took 17s
❯ sk diff snuba
--- default/snuba-profiles-consumer-production-Deployment.yaml.live
+++ default/snuba-profiles-consumer-production-Deployment.yaml.merged
@@ -4,7 +4,7 @@
-  generation: 3
+  generation: 4
@@ -343,7 +343,7 @@
- name: UWSGI_DISABLE_WRITE_EXCEPTION
value: 'true'
-        image: us.gcr.io/sentryio/snuba:c70e257a9dfbb754119cd7f1f091668a0a0fcb7c
+        image: us.gcr.io/sentryio/snuba:f4db68dda90c23322938ecb14faf17bc2deec9bc
imagePullPolicy: IfNotPresent
name: profiles-consumer
resources:
```
=> fix(profiles-consumer): Add to freight deployments

snuba/settings/__init__.py
Sample 10% of `subscriptions.executor.latency` metrics since it's
being recorded for every task. This is the same rate as `receive_latency`
and `process_message` which are recorded with the same frequency.
=> perf(subscriptions): Sample metric that is recorded on every task

snuba/migrations/groups.py, snuba/migrations/snuba_migrations/metrics/0022_repartition_polymorphic_table.py, snuba/migrations/snuba_migrations/metrics/0023_polymorphic_repartitioned_bucket_matview.py, snuba/migrations/snuba_migrations/metrics/templates.py
Daily partition is appealing if most data is concentrated in the latest partition. Unfortunately it seems the content of an INSERT is more evenly divided across partitions. This generates one part per partition almost at every batch, which creates 5 parts every time increasing the number of inactive parts instead of reducing 
```
┌─partition───────────┬─active─┬───c─┬─formatReadableSize(sum(bytes_on_disk))─┐
│ 2022-03-12 00:00:00 │      1 │   4 │ 7.48 MiB                               │
│ 2022-03-13 00:00:00 │      0 │ 621 │ 72.55 MiB                              │
│ 2022-03-13 00:00:00 │      1 │  11 │ 65.22 MiB                              │
│ 2022-03-14 00:00:00 │      0 │ 810 │ 471.11 MiB                             │
│ 2022-03-14 00:00:00 │      1 │  10 │ 97.29 MiB …
```
=> feat(metrics) Increase the partition size of the raw metrics table

snuba/cli/subscriptions.py
The StreamProcessor already handles closing the consumer on shutdown,
we don't need to call close() here.
=> ref: Don't re-close consumer

snuba/cli/subscriptions.py
We need to better understand what is happening during the shutdown
sequence of the subscriptions consumer. Increase the log level
to debug.
=> ref: Increase the log level during subscription consumer shutdown

.freight.yml
The profiles consumer is in crashloop.
This may prevent snuba deployment to go through. 
If that is not fixed and no safeguards is put in place, merge this and the deployment should be unblocked.
=> fix(deployment) The profiles consumer is in cashloop. Removing it from freight

snuba/datasets/storages/processors/replaced_groups.py
- When FINAL query optimizations were applied, I introduced a metric to track how many queries were avoided being set to FINAL
- #2138 
- #2226
- It's been ~5 months since these changes and I don't think we need to continue tracking how well that optimization is doing
- Avoided ~14M FINAL queries in the past 5 months (this is a ~<strong>73%</strong> reduction in total FINAL queries over this time frame)
- Datadog [notebook](https://app.datadoghq.com/notebook/1503147/avoiding-final-metrics).
- See `Total Final queries per Day` and `Final vs Avoided Final` charts
- Removed `avoid_final` datadog metric
- Refactored `replaced_groups.py` to get rid of extra code which served to track this optimization
=> refactor(replacements): Remove avoided final metrics

snuba/query/snql/parser.py, tests/test_snql_sdk_api.py
This error comes up frequently and has not been an issue in Snuba for a long
time. Stop logging this error to Sentry and just return a 400.
=> fix(snql) Remove invalid time sentry logging

snuba/cli/optimize.py, snuba/optimize.py, snuba/settings/__init__.py
We saw a few times the optimize job being restarted by Kubernetes after a few hours. 
That job is stateless so it restarts from scratch. If k8s restarts it too late, the job may end so late to overlap with the next day instance. This puts unnecessary load on the DB.
If we are about to start a new instance there is no point in finishing the previous one, so this adds a cutoff time to ensure the job does not go past a certain time of the dat provided in settings.
The proper fix would be to make the job stateful so that it picks up from where it left when restarted, though that is a large refactoring. This is at least a safeguard to prevent the overlap.
=> feat(optimize) Ensure the optimize job does not go past 11 pm

snuba/optimize.py, tests/datasets/test_errors_replacer.py, tests/test_optimize.py
I did not notice we actually had tests running the optimize jobs and that would be impacted by the cutoff time.
So this reintroduce the flag to ignore the cutoff to be used in tests to make the process deterministic no matter when it runs.
=> fix(optimize) Fix tests that I broke when introducing the optimize cutoff time

snuba/subscriptions/executor_consumer.py, tests/subscriptions/test_executor_consumer.py
We want to avoid committing every offset so that the amount of
committing we need to do does not scale with subscriptions volume.
This change throttles committing offsets in the executor to at most
once every second.
=> perf(subscriptions): Throttle committing offsets in executor

.freight.yml
It's causing deploys to hang: https://freight.getsentry.net/deploys/snuba/production/1547
Semi-revert of https://github.com/getsentry/snuba/pull/2547
=> ops(profiles) - remove profiles consumer from freight

snuba/cli/optimize.py, snuba/optimize.py, tests/test_optimize.py
The optimize call is made on the one shard of each replica. Added a
host tag to each call of optimization to differentiate between calls
being made to each shard and differentiate tiger cluster from
errors cluster.
=> fix(metrics): Fix optimize metrics

snuba/query/processors/handled_functions.py, tests/query/processors/test_handled_functions.py
- Based on this conversation: ([slack](https://sentry.slack.com/archives/CA2V2LBDL/p1646674287100079)|[notion](https://www.notion.so/sentry/error-handled-and-unhandled-logic-f720e11193f6470890ec02d8ac587008))
- This changes isHandled to check that all values in the
exception_stacks.mechanism_handled array are either Null or 1
- This is cause currently isHandled() doesn't equal the reverse of
notHandled() which results in `error.handled:1` and
`error.unhandled:1` returning the same rows
- This keeps notHandled the same as before where there's at least a 0 in
the array
=> ref(discover): Change isHandled to check all the values in the array

snuba/datasets/entities/discover.py, snuba/datasets/entities/metrics.py, snuba/datasets/entities/outcomes.py, snuba/datasets/entities/outcomes_raw.py, snuba/datasets/entities/profiles.py, snuba/datasets/entities/sessions.py, snuba/datasets/entities/transactions.py, snuba/datasets/storages/discover.py, snuba/datasets/storages/metrics.py
In the last few months we created a number of rate limiters for Snuba:
- table rate limiter
- referrer rate limiter
- project_referrer rate limiter
- quota control (that reduces the max_thread count)
We did not add them consistently to all datasets, entities and storages. 
This should cover everything.
=> feat(rate limiters) Add recently created rate limiters across the board

requirements.txt
This upgrades confluent-kafka-python from 1.5.0 to 1.6.1 everywhere.
=> feat: Upgrade sentry-arroyo and confluent-kafka-python

tests/test_cli.py
This test wasn't actually passing because invalid arguments were being passed. The sleep was just shorter than it took to actually start the consumer.
=> test: Fix CLI test

snuba/admin/notifications/slack/utils.py, snuba/settings/__init__.py
Removed the button since it felt like it was taking up a lot of room and since we don't have a interactive url set up, every time you click it, it gives a warning (even though it does work)
Put the link in the timestamp instead:
> ![Screen Shot 2022-03-31 at 11 49 20 AM](https://user-images.githubusercontent.com/15368179/161128172-1e63cfab-5526-4452-85ad-0aa709f5c651.png)
=> ref(snuba-admin): Add link to audit log

requirements.txt, snuba/cli/consumer.py, snuba/cli/multistorage_consumer.py, snuba/cli/subscriptions.py, snuba/cli/subscriptions_executor.py, snuba/consumers/consumer_builder.py, snuba/subscriptions/executor_consumer.py
The consumers, multistorage-consumers, subscriptions consumer and
subscriptions-executor now support passing a --cooperative-rebalancing
flag which, if passed, will use the "cooperative-sticky" partition
assignment strategy.
Note that cooperative and non-cooperative strategies cannot be
combined in the same group so this cannot be deployed with a rolling
strategy. When enabling cooperative rebalancing for the first time,
all old consumers in the group should be stopped before restarting.
=> feat(consumers): Support the --cooperative-rebalancing option

snuba/migrations/runner.py, tests/test_consumer.py
Fix of a test failure that hit a TTL condition today at 1:35 PM PT
=> fix(metrics) - update a test with a hard-coded timestamp beyond database TTL

snuba/datasets/entity.py, snuba/query/validation/validators.py, tests/test_snql_api.py
We are not currently validating that columns referenced in queries are actually
available on the Entity. There was an initiative to do those checks, but it
stalled. This make any missing column errors throw a Sentry warning so we can
see how often our validators would catch broken queries. If things are working
as expected, we can turn the validators on by default and remove the xfail
from the test.
=> fix: Change column entity validator to WARN by default

snuba/datasets/storages/factory.py, snuba/datasets/storages/metrics.py, snuba/migrations/groups.py, snuba/migrations/snuba_migrations/metrics/0024_metrics_distributions_add_histogram.py, snuba/migrations/snuba_migrations/metrics/0033_metrics_cleanup_old_views.py, snuba/migrations/snuba_migrations/metrics/0034_metrics_cleanup_old_tables.py
Show tables before:
```
7b701b64404c :) show tables
SHOW TABLES
┌─name──────────────────────────────────────────┐
│ discover_local                                │
│ errors_local                                  │
│ groupassignee_local                           │
│ groupedmessage_local                          │
│ metrics_buckets_local                         │
│ metrics_counters_buckets_local                │
│ metrics_counters_consolidated_mv_local        │
│ metrics_counters_local                        │
│ metrics_counters_mv_10s_local                 │
│ metrics_counters_mv_3600s_local               │
│ metrics_counters_mv_86400s_local              │
│ metrics_counters_mv_local                     │
│ metrics_counters_polymorphic_mv_local         │
│ …
```
=> cleanup(metrics) - remove unused metrics materialized views and tables

snuba/cli/devserver.py
When trying to run sentry tests that depend on the snuba image, I'm getting:
```
23:24:21 metrics-consumer | Usage: snuba multistorage-consumer [OPTIONS]
23:24:21 metrics-consumer | Try 'snuba multistorage-consumer --help' for help.
23:24:21 metrics-consumer |
23:24:21 metrics-consumer | Error: Invalid value for '--storage': invalid choice: metrics_counters_buckets. (choose from groupedmessages, groupassignees, metrics_distributions, metrics_sets, metrics_counters, metrics_raw, errors, outcomes_raw, querylog, sessions_raw, transactions, spans, transactions_v2, errors_v2, profiles)
```
While I can fix this by just using local snuba instead we should probs update this for other people (who have will be using `SENTRY_USE_METRICS_DEV` in sentry)
=> ref(devserver): update metrics-consumer command

snuba/subscriptions/verifier.py
Not all subscriptions have "totals". Previously the verifier would
crash when it encountered a subscription without this key.
=> fix(subscription-verifier): Totals is not always present in result

snuba/subscriptions/executor_consumer.py
This is the same metric we have in our consumers added to the executor
as well, it helps with debugging Kafka issues in consumers.
=> feat: Record librdkafka buffer size from the subscriptions executor

snuba/pipeline/pipeline_delegator.py
There's a data race which happens when the query is run via the
pipeline delegator. The same query object is modified by the entity
processors being run by different threads. To solve this race, we
create a copy of the query object and use it to avoid the race.
=> fix(query): Avoid race in pipeline delegator

snuba/datasets/storages/errors_v2.py, snuba/datasets/storages/transactions_v2.py, tests/test_consumer.py
Now that we have been running inserts on the tiger cluster without
any issues for more than a month, its safe to not ignore the write
errors anymore for the consumers.
=> fix(tiger writes): Disable ignore write errors

snuba/cli/subscriptions_scheduler.py, snuba/subscriptions/scheduler_consumer.py, snuba/subscriptions/scheduler_processing_strategy.py, tests/subscriptions/test_scheduler_consumer.py, tests/subscriptions/test_scheduler_processing_strategy.py
The subscriptions scheduler now supports passing --stale-threshold-seconds.
If a value is passed, subscriptions whose scheduled timestamp is more than
this number of seconds before the current time in the scheduler will be ignored.
This means that if the scheduler sees stale subscriptions they will be skipped
instead of scheduled for execution.
Under normal circumstances we should not really see stale subscriptions, however
there are a few situations where it happens.
- The main consumers were heavily backlogged for some reason
- Consumer or scheduler crashed for some time and we need to catch up
- In dev when devserver is stopped for an extended period of time
Since very delayed alerts are generally of little value to users, having the option
to skip them will be useful in some …
=> feat(subscriptions): Ignore stale subscriptions

snuba/subscriptions/verifier.py, tests/subscriptions/test_verifier.py
A number of results seem to be off by one in the new pipeline + Tiger vs the old
subscriptions pipeline + main ClickHouse cluster. Since there's not a great deal
we can do about these, this change counts those separately and does not log them
to Sentry so we get more visibility on those results that might be more significantly different.
=> feat(subscriptions): Count the off by one results separately in verifier

.pre-commit-config.yaml, requirements.txt, snuba/state/stateful_count.py
Includes changes to support incremental assignments in the stream processor.
This is required in order to switch to using the cooperative-sticky strategy
with Arroyo.
=> feat: Bump arroyo to 0.0.16

scripts/ddl-changes.py
previously ddl-changes.py would match non-migration files and error.
I removed the fragile regex matching and moved the "added/deleted" and
path matching into the `git diff` command itself.
___
testing done: see https://github.com/getsentry/snuba/pull/2612 where I cherry-picked this commit on top to fix CI
=> fix: Match only migration files in scripts/ddl-changes.py

snuba/subscriptions/verifier.py, tests/subscriptions/test_verifier.py
There were a number of bugs in https://github.com/getsentry/snuba/pull/2607.
It was always returning False for `is_off_by_one()`, and then logging the off by
one results to Sentry (always none due to this bug) instead of those that are
different in more significant ways.
=> fix(subscriptions): Fix off by one calculation in verifier

snuba/subscriptions/scheduler_consumer.py
This fixes SNUBA-2R0.
We weren't properly resetting ticks and offsets stored internally in the
CommitLogTickConsumer on partition revocation. This made it possible for the
consumer to receive an earlier tick (after revocation and reassignment) and
attempt to construct an interval with the last one it saw before the revocation
happened, which is invalid. It also means it was possible that scheduling for
a tick was missed on rebalancing / deployment.
=> fix(subscriptions): Fix InvalidRangeError when rebalancing occurs

snuba/datasets/storages/errors.py, snuba/datasets/storages/errors_v2.py
Temporarily run in global mode to verify the results are the same.
We will switch back later after the test.
=> feat(subscriptions): Temporarily run errors in global mode

.envrc
on the latest macos, `python` has been removed and is not
always a symlink to `python3`.
before this patch:
```console
$ direnv allow
direnv: loading ~/workspace/snuba/.envrc
./.envrc:5: python: command not found
./.envrc:6: .venv/bin/activate: No such file or directory
./.envrc:7: pip: command not found
pip install -e .
make: pip: No such file or directory
make: *** [install-python-dependencies] Error 1
```
=> fix: Use `python3` for `.envrc` virtualenv creation

snuba/datasets/entities/events.py, snuba/datasets/entities/transactions.py, snuba/pipeline/pipeline_delegator.py, snuba/utils/threaded_function_delegator.py, tests/pipeline/test_pipeline_delegator.py
In order to avoid impacting our SLO's while still trying to run the
production load we would like to change the exceptions from the tiger
cluster to warn level.
=> chore(tiger): Log exceptions from tiger with warn level

snuba/cli/subscriptions_executor.py
The comma in the entity list does not seem to be properly handled in
Datadog, just tag the dataset instead.
----
By submitting this pull request, I confirm that Sentry can use, modify, copy, and redistribute this contribution, under Sentry's choice of terms.
=> fix: Fix tagging of executor metrics

requirements.txt, snuba/cli/config.py, snuba/cli/subscriptions.py
The main motivation for this upgrade is to match the black version to the
one used in pre-commit. Previously they were different causing editor autoformatting
(e.g. the formatting applied on save in VSCode) to be different to autoformatting
applied in pre-commit.
----
By submitting this pull request, I confirm that Sentry can use, modify, copy, and redistribute this contribution, under Sentry's choice of terms.
=> feat: Upgrade black and click

snuba/datasets/events_format.py, snuba/datasets/events_processor_base.py, snuba/datasets/metrics_aggregate_processor.py, snuba/datasets/metrics_bucket_processor.py, snuba/datasets/sessions_processor.py, snuba/datasets/spans_processor.py, snuba/datasets/transactions_processor.py, tests/datasets/test_metrics_processor.py, tests/datasets/test_session_processor.py
**context**:
Sessions and metrics don't have retention enforced anywhere in snuba and rely on the the payload of the session/metric event. This PR makes sure that sessions and metrics events have a retention of either `30` or `90` days.
**changes**
I've spilt out the override functionality of the existing `enforce_retention` that is used for events/transactions. Overriding retention days is something that can be set on a project level basis for events/transactions.
Sessions/metrics may want to have override functionality later on but currently we don't and we'd want those overrides to be independent from other datasets (events/transactions).
=> ref(metrics/sessions): enforce retention days

snuba/cli/subscriptions_executor.py, snuba/subscriptions/executor_consumer.py
This is an attempt to fix an error we are seeing in the executor logs
about the producer terminating with unflushed messages still in queue.
Now we wait for the producer.close() future to finish when closing the producer.
=> fix(subscriptions): Properly close producer

tests/state/test_stateful_count_policy.py
- Lyn encountered a `DID NOT RAISE` failure on a DLQ policy test
- This test ensures the policy ignores up to `n` invalid messages per second before raising an exception on the `n+1`st invalid message
- The flakeyness could be from the time bucket changing to the next second while the original `n` messages are being submitted, making the expected exception not raise since it's still under the limit
- Reduced `n` from 5 to 1 to reduce the window of possible time bucket change
=> fix(tests): Flakey DLQ policy test

snuba/cli/subscriptions_executor.py
https://github.com/getsentry/snuba/pull/2644 did not really work. The producer
is still not being closed properly. Try closing it first before the executor.
=> fix(subscriptions): Close producer before executor

snuba/datasets/entities/__init__.py, snuba/datasets/entities/factory.py, snuba/datasets/entities/metrics.py, snuba/datasets/metrics.py, snuba/datasets/storages/__init__.py, snuba/datasets/storages/factory.py, snuba/datasets/storages/metrics.py, tests/test_metrics_api.py
To support converting the release monitor in sentry over to metrics we want to be able to make
queries without having to specify org and project ids in the query. This pr adds in
`OrgMetricsCountersEntity` and `org_counters_storage` to allow us to do this.
=> feat(metrics): Add entity and storage to allow for cross-org metric counter queries

snuba/subscriptions/executor_consumer.py
Bringing this experiment back since https://github.com/getsentry/snuba/pull/2644
didn't work.
This is an attempt to fix an error we are seeing in the executor logs
about the producer terminating with unflushed messages still in queue.
Now we manually call flush() when the strategy is closed. For now this
is just a test - if it actually works, then we will update Arroyo to properly
expose the flush() method instead of relying on this hack.
=> fix(subscriptions): Flush producer on rebalance

snuba/util.py, snuba/utils/metrics/backends/testing.py, tests/conftest.py, tests/test_snql_api.py, tests/test_snql_sdk_api.py
There are potentially users who don't want to set up Datadog for Snuba, who will
then be hit by a memory leak since the Dummy backend will record all metrics.
Create a separate Testing backend that is used specifically for tests, and
revert the Dummy backend to stop storing anything.
=> fix: Separate testing metrics backend into a different class

snuba/web/db_query.py, tests/web/test_cache_partitions.py
We are noticing an increase in ExecutionTimeoutError on the tiger
cluster. In order to debug what's happening, I would like the ability
to increase the cache wait timeout period for tiger clusters. The max
query execution time for a clickhouse query would be still 30 seconds.
But I would increase the wait timeout to see if the result gets
populated with some additional wait time.
----
By submitting this pull request, I confirm that Sentry can use, modify, copy, and redistribute this contribution, under Sentry's choice of terms.
=> ref(tiger): Allow increasing cache wait time for tiger

snuba/query/functions.py, snuba/query/parser/validation/functions.py
**context:**
A while back I added some global function validating (in https://github.com/getsentry/snuba/pull/2067) that allowed use to check if the function names were valid. This didn't add checks for whether the functions were called with the right arguments though.
**`DateTimeValidator`**
Just wanted to take a stab at adding signature validation for a small chunk of ClickHouse functions. For now, the validation isn't enforce, so it should just log to Sentry if the validation fails. However, I'm not expecting it to since I think we would have been seeing ClickHouse errors if that was the case. 
Also probs makes sense to move the `default_validators` out of this file if we keep adding to it but I think that can be done later.
=> ref(validators): Add DateTime signature validators

.freight.yml
We are seeing an `OffsetOutOfRange` error crashing the metrics subscription executor so removing it from freight for now so that it doesn't block other snuba deployments
=> ref(freight): Remove metrics subscriptions executor from freight

snuba/clickhouse/native.py, tests/clickhouse/test_native.py
Retry simultaneous query errors for non-robust queries. This logic is very
similar to what happens with robust queries, but the errors will only be retried
once.
Context:
We sometimes see issues where a single storage node gets imbalanced incorrectly and receives a lot more traffic than it should. The reason for the imbalance is unclear, but we can retry those queries so they get run on a different node.
=> fix: Retry simultaneous query errors for non-robust queries

.freight.yml
Reverts getsentry/snuba#2662
Offsets were reset to latest in [OPS-1703](https://getsentry.atlassian.net/browse/OPS-1703).
=> Revert "ref(freight): Remove metrics subscriptions executor from freight"

snuba/web/views.py, tests/test_snql_api.py
When queries fail with Clickhouse errors, return a 400 status code when
the Clickhouse error code indicates a type error in the query. This ensures
our SLOs are not impacted when users make mistakes in their queries.
=> fix(snql): Return 400 error code on queries with type errors

snuba/cli/subscriptions_executor.py
The CLI argument --stale-threshold-seconds can be overriden via config.
=> feat(subscriptions): Add config to skip stale subscriptions in executor

.freight.yml
**context**
Attempt II of https://github.com/getsentry/snuba/pull/2664. The first time around we ran into [this issue](https://sentry.io/organizations/sentry/issues/3252488041/?project=37617&query=is%3Aunresolved&statsPeriod=24h) but @joshuarli has since added the `SENTRY_API_TOKEN` to freight's env.
=> ref(dev-tooling): Enable commit tracking attempt II

snuba/subscriptions/worker.py
Log when subscriptions are skipped due to the `subscriptions_max_latency_sec`
override
=> feat(subscriptions): Add logging for skipped subscriptions

snuba/cli/subscriptions_executor.py, snuba/state/__init__.py, snuba/subscriptions/executor_consumer.py
We are *still* seeing an error in the logs that the producer was
being terminated with messages in queue. Add calls to flush() and
a bunch of logging to try and track this down.
=> feat(subscriptions): Debug producer shutdown

.freight.yml
This was temporary, and is about to be removed completely
=> feat(subscriptions): Remove verifier from Freight

snuba/state/cache/abstract.py, snuba/state/cache/redis/backend.py, snuba/web/db_query.py, tests/state/test_cache.py
When queries are run against the tiger cluster and the operation is performed via readthrough caching, we see a lot of ExecutionTimeoutErrors. This happens because uwsgi respawns the processes every 3 minutes. The respawn ensures that the requests sent to the processes have all returned their responses. So we don't see this issue with the primary queries. Unfortunately, there is no way to ask uwsgi to wait for queries being run in threads that need time to run. Those threads get killed mercilessly.
Differentiate the exceptions being raised be queries from tiger cluster from regular production clusters. That way we can tune the alerts to ignore certain tiger exceptions.
----
By submitting this pull request, I confirm that Sentry can use, modify, copy, and redistribute this contribution, …
=> chore(tiger): Raise a different timeout exception from tiger clusters

snuba/datasets/storages/errors_v2.py, snuba/datasets/storages/errors_v2_ro.py, snuba/datasets/storages/transactions_v2.py, snuba/query/processors/tuple_elementer.py, tests/query/processors/test_backwards_compatibility_processors.py, tests/query/processors/test_tuple_elementer.py
The new clickhouse sometimes fails to parse queries that have a `tupleElement` function.  
Example:
```sql
SELECT
(
toStartOfHour(finish_ts, 'Universal') AS _snuba_time
),
countIf(
lessOrEquals(
multiIf(
equals(tupleElement(tuple('duration', 300), 1), 'lcp'),
(
if(
has(measurements.key, 'lcp'),
arrayElement(
measurements.value,
indexOf(measurements.key, 'lcp')
),
NULL
) AS ` _snuba_measurements [ lcp ] `
),
(duration AS _snuba_duration)
),
tupleElement(tuple('duration', 300), 2)
)
)
FROM
transactions_dist PREWHERE equals((transaction_name AS _snuba_transaction), '/')
WHERE
equals(('transaction' AS _snuba_type), 'transaction')
AND greaterOrEquals(
(finish_ts AS _snuba_finish_ts),
toDateTime('2022-04-11T20:52:46', 'Universal')
)
AND less(
_snuba_finish_ts,
toDateTime('2022-04-25T20:52:46', …
```
=> fix(tiger): Implement tupleElement function in snuba

.github/workflows/ci.yml
this drastically speeds up the arm64 image build
- a representative "before": **54 minutes** https://github.com/getsentry/snuba/runs/6378324183?check_suite_focus=true
- this PR: **25 minutes** https://github.com/getsentry/snuba/runs/6389113546?check_suite_focus=true
validation done:
I override the image in my `sentry` checkout, `make run-dependent-services` and then ran `pytest tests/snuba`
```diff
diff --git a/src/sentry/conf/server.py b/src/sentry/conf/server.py
index 63b3f4e2bc..6489ee9203 100644
--- a/src/sentry/conf/server.py
+++ b/src/sentry/conf/server.py
@@ -1931,7 +1931,7 @@ SENTRY_DEVSERVICES = {
{
"image": "getsentry/snuba:nightly" if not APPLE_ARM64
-            else "ghcr.io/getsentry/snuba-arm64-dev:latest",
+            else …
```
=> ref: try building the arm64 image using linux builders

snuba/state/__init__.py
Sometimes the message is too large for the querylog topic. Add compression to the producer and allow larger messages. There is also an ops ticket to allow larger messages on the broker
=> fix(querylog): compress, allow larger messages on the querylog producer

snuba/state/__init__.py
Lyn was right that `max.request.size` is not applicable for librdkafka producers, I read the wrong confluent docs
=> fix(querylog): use correct kafka config option

snuba/settings/__init__.py, snuba/state/__init__.py, tests/state/test_record.py
* Use the correct kafka setting this time I promise
* Add a test to make sure the producer can actually be created. The test was able to reproduce the failure that happened in production.
=> fix(querylog): fix the kafka config, add test for producer

snuba/datasets/metrics_bucket_processor.py
- Metrics DLQ is behind a runtime config right now
- Warns but should error if we encounter an invalid message and the DLQ is disabled
=> fix(dlq): Metrics ignored messages should be Sentry Errors

snuba/clickhouse/formatter/expression.py, tests/clickhouse/test_formatter.py, tests/query/processors/test_arrayjoin_optimizer.py, tests/query/processors/test_hexint_column_processor.py, tests/query/processors/test_uuid_column_processor.py, tests/query/snql/test_snql_anonymizer.py, tests/test_api.py
After drilling down enough, it seems like this is actually the cause of the bugs. I thought I tried it a week ago when @evanh told me to but I guess I didn't try it correctly. Either way this should actually fix the problems. It looks like we already had to implement a similar fix for arrays so this should be no different.
=> fix(tiger): don't call the explicit tuple function in clickhouse

snuba/datasets/metrics_bucket_processor.py
- Metrics DLQ is not yet active
- I added a sentry error in case we encounter a bad message so we can just skip but keep track
- I realize it wouldn't actually skip, it would just log an error and try processing it anyway
- This is _bad_ and is currently in prod - thankfully no bad messages have been encountered yet.
- Modified Metrics code to return a `None` from the message processor in case of bad message and DLQ is disabled
- I believe this effectively skips the message
- The only reason this extra check exists is in case the DLQ does not work
- This additional logic will be removed in favor of just the DLQ logic once we verify it works as intended
=> fix(dlq): Skip bad message if DLQ inactive

snuba/datasets/metrics_bucket_processor.py
- Logging with `message` as a key in the extra fields raises an error as `message` is a keyword already used by the logger
- Tested with DLQ and with this logger to ensure both ways work
=> fix(dlq): Backup logging overwrote message

snuba/datasets/storages/metrics.py
- There is a bug in produce policy - we never close the producer
- Reverting to Ignore policy while we figure out how to approach closing/rebalancing producer when metrics consumer is closed/rebalanced
=> fix(dlq): Revert Produce policy to Ignore on Metrics

Dockerfile, docker-compose.gcb.yml, docker_entrypoint.sh
- the usage of `gosu` traces back to https://github.com/getsentry/docker-sentry/issues/65
- relates to https://github.com/getsentry/self-hosted/issues/365
=> ref: factor out gosu and use USER instead

snuba/datasets/storages/errors_v2_ro.py
Fix a bug in the tiger errors ro storages to use the query processors
defined by the v2 entity.
=> fix(tiger errors): Use v2 query processors

snuba/subscriptions/scheduler_consumer.py, tests/subscriptions/test_scheduler_consumer.py
**context:**
This should really not ever happen, BUT if for some reason we get a bad message from the commit log topic, the scheduler consumer will just crash. If this happens very frequently the consumer crashing might be okay since it would indicate something upstream is very wrong. However if it's only one (or even a couple messages) we may not want to disrupt the entire subscription processing pipeline
Instead, if we have a problem decoding the kafka payload, let's log the error and drop the message. 
**what's the impact?**
The scheduler consumer creates ticks based on intervals between these `Commit` messages that come from the commit log topic. Given the example messages below (assume all the same partition):
```
message 0 @ 12:00 
message 1 @ 12:01 
message 2 @ 12:02
```
Normally …
=> ref(subscriptions): Log commit log msg decode errors

requirements.txt
This isn't a huge deal but I wanted to be able to type the `caplog` used in some tests, but that is only available starting in [pytest version `6.2.0`](https://github.com/pytest-dev/pytest/releases/tag/6.2.0) where they add `_pytest.logging.LogCaptureFixture`. 
Additionally, when trying to upgrade `pytest` I ran into:
```
The conflict is caused by:
snuba 22.6.0.dev0 depends on attrs==18.1.0
jsonschema 3.0.1 depends on attrs>=17.4.0
pytest 6.2.0 depends on attrs>=19.2.0
```
so I'm also upgrading `attrs` to `19.2.0`. From the [release notes](https://github.com/python-attrs/attrs/releases?page=1) it doesn't seem like there is a whole lot of difference between `18.1.0` and `19.2.0`. 
The only breaking change for moving to `pytest==6.2.0` is that they only support python 3.6+ (and we are using …
=> (chore): Update pytest and attrs deps

Dockerfile, docker-compose.gcb.yml, docker_entrypoint.sh
Reverts getsentry/snuba#2696
This breaks the production deployment as some of the scripts rely on gosu to be present in the docker container
=> Revert "ref: factor out gosu and use USER instead"

requirements.txt
Update `sentry-relay` dependency to ver. 0.8.12
=> build: Update sentry-relay to 0.8.12

snuba/pipeline/settings_delegator.py
The current implementation of RateLimiterDelegate uses the same
RequestSettings passed to it in the constructor. That causes a bug
since the original rate_limit_params of HTTPRequestSettings are stored
in a list. The same list gets used by both the threads processing the
query since add_rate_limit_params from both execution pipelines
adds the rate limit to the same list.
The end result of this is that instead of processing 3 sets of rate
limits (project, table, global), secondary queries are actually getting 6
sets of rate limits (all of the above multiplied by 2). This leads
to overcounting since a query run in a single execution pipeline
gets counted in both execution pipelines.
To fix this we use a deep copy of the RequestSettings.
Look, I get it. The entity doing business as "Sentry" …
=> fix(rate-limits): Create copy of request settings

snuba/subscriptions/entity_subscription.py, tests/subscriptions/test_codecs.py, tests/subscriptions/test_data.py, tests/subscriptions/test_subscription.py, tests/subscriptions/test_worker.py, tests/test_sessions_api.py
Sessions subscriptions are being deprecated. This prevents any new
sessions subscriptions from being created in Snuba.
This is important since Sentry's API still allows these to be created
and does not validate the dataset, even though these will no longer
be created via the UI.
=> feat(subscriptions): Prevent sessions subscriptions from being created

snuba/cli/devserver.py, snuba/datasets/storages/sessions.py, snuba/settings/__init__.py, snuba/utils/streams/topics.py
Removes the ENABLE_SESSIONS_SUBSCRIPTIONS flag.
The sessions consumer no longer has the option of writing a commit log.
=> feat(subscriptions): Remove support for sessions subscriptions

snuba/cli/subscriptions_executor.py, snuba/subscriptions/executor_consumer.py
This was being used during testing to ensure the executor wasn't producing
results to the real result topic. Now we are going to use the real topic from the
stream loader.
This is the first step towards removing it completely. Once we are no
longer passing this anywhere, it will be removed completely.
=> feat(subscriptions): Make --override-result-topic optional in executor

requirements.txt
This reverts commit 20598412d0cd0d7870fddf67227602c81c4f1304.
This caused a noticable regression in query performance.
=> Revert "build(deps): bump parsimonious from 0.8.1 to 0.9.0 (#2753)"

snuba/subscriptions/executor_consumer.py, snuba/subscriptions/scheduler_processing_strategy.py
The offset to be committed should always be the *next_offset* - the minimum
offset of the next message to be processed (which is one higher than the
offset of the last successfully processed message). Previously we
were committing the offset of the current message which is one offset behind
what it should be.
=> fix(subscriptions): Commit the right offset in the scheduler and executor

snuba/subscriptions/scheduler_consumer.py
We record this metric for most of our other consumers, we should bring it
over to the scheduler as well as it was a blind spot for us during
the outage when the scheduler got stuck.
=> feat(subscriptions): Record librdkafka buffer size in scheduler

snuba/subscriptions/scheduler_processing_strategy.py, tests/subscriptions/test_scheduler_processing_strategy.py
During a multi-hour outage, the scheduler gets into the unusual state of having
ticks spanning multiple hours, for which a very large number of subscriptions
need to be scheduled (often exceeding the buffer size of 10,000 applied later
in the pipeline). This is likely to be a cause of the scheduler getting stuck.
If --stale-threshold-seconds is passed, we should use the lower bound of the tick
instead of the upper bound for comparison so that extremely large ticks that are
not able to be properly processed get discarded.
=> feat(subscriptions): Improve filtering of stale subscriptions in scheduler

snuba/subscriptions/worker.py
Previously we are always running ClickHouse queries in the legacy
pipeline even if the transition mode was set to "new". Later we
just discarded the results and didn't publish them anywhere.
This change avoids running the extra ClickHouse queries at all
during the transition.
=> fix(subscriptions): Don't run unnecessary queries in legacy pipeline

Dockerfile
this will be used in conjunction with `runAsUser` / `runAsGroup` in the k8s metadata so `gosu` can be factored out (originally attempted in https://github.com/getsentry/snuba/pull/2696 but that had to be rolled back)
=> ref: set an explicit uid/gid for the snuba user

snuba/query/processors/table_rate_limit.py, tests/query/processors/test_table_rate_limit.py
The table rate limiter was designed with the idea of being a concurrent rate limiter in mind primarily. The per second rate limiter is only meaningful for specific projects/features. At a global level it is generally not very useful.
We are now hitting the default per second rate limiter at times on large clusters, which is kind of expected considering it was set only to 1000. 
This increases the default value so that we have more headroom. We could even remove the per second global rate limiter altogether but that requires a rate limiter refactoring
=> fix(rate limiter) Increase the default table per second rate limiter

snuba/clickhouse/native.py, snuba/web/constants.py, snuba/web/views.py
- Return 400 for queries that can never return the amount of data requested by the user, this is not an internal error
- See [SNS-1333](https://getsentry.atlassian.net/browse/SNS-1333)
- Added `MEMORY_LIMIT_EXCEEDED` to "Acceptable" Clickhouse errors
=> fix(api): Clickhouse Memory Limit Exceeded is a 400, not internal error

tests/subscriptions/test_scheduler_processing_strategy.py
This was flaky before since we were previously generating random subscription UUIDs and asserting they were executed within a 50 second window. Since the jitter spread things out over a minute this would fail roughly 10/60 of the time.
=> test: Fix flaky test

.freight.yml
This reverts commit 6cacf5c029b5a1a2b1364e8660dd6f89af4dc42f.
We need to deploy all consumers with Freight. Currently the profiles
consumer has to be periodically updated by ops manually. It's also
very easy to break the profiles consumer when we change
settings in Snuba as they get applied here against (potentially) very
old version of our codebase. This happened 2 weeks ago and ops
had to manually intervene to update the hash.
=> Revert "ops(profiles) - remove profiles consumer from freight (#2549)"

snuba/cli/devserver.py, snuba/settings/__init__.py
Consolidated the subscription scheduler and executor for dev was added in https://github.com/getsentry/snuba/pull/2666. Having this by default is great, but I wanted to make it easier for when developing on the subscriptions architecture that dev could resemble prod as much as possible.
=> ref(subscriptions): add SEPARATE_SCHEDULER_EXECUTOR_SUBSCRIPTIONS_DEV option

snuba/settings/__init__.py
We want to see the impact 90 day queries have on the tiger clusters. In order to do that, lets move the start date by a months time so that 90 day queries are not run on the tiger clusters.
=> chore(tiger): Move tiger errors start date

snuba/clusters/storage_sets.py, snuba/datasets/storages/__init__.py, snuba/datasets/storages/generic_metrics.py, snuba/datasets/storages/metrics.py, snuba/datasets/storages/tags_hash_map.py, snuba/migrations/groups.py, snuba/migrations/snuba_migrations/generic_metrics/0001_sets_aggregate_table.py, snuba/settings/__init__.py, snuba/settings/settings_distributed.py
`generic_metrics_sets` is the first aggregate table I'm creating for the metrics-enhanced performance project (internal doc: https://www.notion.so/sentry/Metrics-Enhanced-Performance-Q2-SNS-Plan-79247be0ab134aae90269de0523c35f5). The goal with this approach is to create end-to-end functionality for sets (starting from the indexer ingestion in sentry, to writing to ClickHouse, and returning results via the query API) before implementing the other metric types (counters, distributions) and their processors.
Changes in this PR:
- new storage set key (for sets type only)
- new storage set (for sets type only)
- new migration group (will be shared with other "generic" metrics clusters)
- a migration to create the table
Next steps:
- create a raw table and materialized view for writing to …
=> feat(metrics): create generic sets aggregate table + indices

snuba/cli/subscriptions_executor.py, snuba/cli/subscriptions_scheduler_executor.py, snuba/subscriptions/combined_scheduler_executor.py, snuba/subscriptions/executor_consumer.py, tests/subscriptions/test_combined_scheduler_executor.py, tests/subscriptions/test_executor_consumer.py
**context**
This is kind of a reverse and then some of: https://github.com/getsentry/snuba/pull/2364 but for different reasons. Some background on this PR:
The task I'm currently working on is auto scaling our snuba consumers, starting with the executors. We have auto scaling on some of snuba services, such as the api[^1], but not everything. Additionally, certain consumers, like the executors[^2] have args passed in that depend on the no. of replicas (which will no longer will be constant if we have auto scaling implemented).
**why replica dependent args not great?**
When an autoscaler kicks in, it adds new pods. The new pods will be aware of new number of replicas, whereas the currently running "old" pods will not. This would lead to different parameters for different pods, and those …
=> ref(subscriptions): Executor created within strategy

snuba/cli/subscriptions_scheduler_executor.py, snuba/subscriptions/combined_scheduler_executor.py
This is a temporary change that allows the scheduling watermark mode
to be overridden in the combined scheduler/executor. This is needed for
single tenant as we often have empty partitions there and empty partitions are
incompatible with "global" mode. Once transactions are no longer semantically
partitioned, this will not be necessary and this can be removed.
=> feat(subscriptions): Allow scheduling watermark mode to be overridden

snuba/admin/package.json, snuba/admin/yarn.lock
This is a duplicate of a couple dependabot PRs. They were failing CI and it's
easier to debug CI problems on an internal PR vs. external.
Dependabot PRs:
https://github.com/getsentry/snuba/pull/2779
https://github.com/getsentry/snuba/pull/2790
https://github.com/getsentry/snuba/pull/2804
=> fix: Update frontend packages

requirements.txt
Copy of https://github.com/getsentry/snuba/pull/2803 to get CI passing.
Also closes https://github.com/getsentry/snuba/pull/2810.
=> Update clickhouse-driver from 0.2.2 to 0.2.4

mypy.ini, requirements.txt, snuba/datasets/errors_replacer.py, snuba/redis.py, snuba/state/rate_limit.py, tests/test_api.py, tests/test_redis.py, tests/test_replacer.py, tests/test_snql_api.py
Our current version of Redis is EOL, so update to the latest. Dependabot only
updated to 4.1.3 but 4.3.3 contains fixes for things that were broken in the
version Dependabot wanted. redis-py-cluster has been added to the redis library
so we don't need to import it separately any more.
=> fix: Update to latest version of Redis (4.3.3)

snuba/datasets/events_format.py
If the `retention_days` provided is not an int we will just use the `DEFAULT_RETENTION_DAYS`. Should fix https://github.com/getsentry/snuba/issues/2780.
=> enforce retention_days is int type

snuba/cli/subscriptions_executor.py, snuba/cli/subscriptions_scheduler_executor.py, snuba/subscriptions/combined_scheduler_executor.py, snuba/subscriptions/executor_consumer.py, tests/subscriptions/test_combined_scheduler_executor.py, tests/subscriptions/test_executor_consumer.py
**context**:
We've been working on a solution to helping our snuba consumers scale automatically. There is some detailed context about that in https://github.com/getsentry/snuba/pull/2762. For the executors specifically we want `max_concurrent_queries` to be calculated dynamically.
We need three numbers to do that:
1. **total concurrent queries**
* This PR adds this arg be passed in through the cli with the default of `64`. `64` is the `total_concurrent_queries` set in the ops repo for all of the executors aside from [the metrics executor](https://github.com/getsentry/ops/blob/master/k8s/services/snuba/_deployment.metrics-subscriptions-executor.yaml#L10) which is `24`.
1. **total no. partitions**
* This can be gathered from `TOPIC_PARTITION_COUNTS` but we want to make sure those are set …
=> ref(subscriptions): Add total_concurrent_queries cli arg

snuba/cli/devserver.py, snuba/datasets/entities/__init__.py, snuba/datasets/entities/factory.py, snuba/datasets/entities/replays.py, snuba/datasets/replays.py, snuba/datasets/replays_processor.py, snuba/datasets/storages/__init__.py, snuba/datasets/storages/factory.py, snuba/datasets/storages/replays.py, snuba/settings/__init__.py, snuba/settings/validation.py, snuba/utils/streams/topics.py, tests/datasets/test_replays_processor.py
(re-open of #2683)
following up on https://github.com/getsentry/snuba/pull/2681, we add a processor to insert replay data rows into clickhouse.
common code has been copy/pasted from relevant consumers for things like tag/environment processing etc.
Will note that we'll be rapidly prototyping on top of this, so opting for quicker / more isolated changes (as opposed to e.g. refactoring to be more DRY for tag processing).
=> feat(replays): replays processor to ingest data into clickhouse

requirements.txt
bump flake8 from 3.7.8 to 4.0.1
bump progressbar2 from 3.53.1 to 4.0.0
bump chardet from 3.0.4 to 4.0.0
bump pyparsing from 2.2.0 to 3.0.9
These are copied from dependabot PRs:
https://github.com/getsentry/snuba/pull/2751
https://github.com/getsentry/snuba/pull/2752
https://github.com/getsentry/snuba/pull/2812
https://github.com/getsentry/snuba/pull/2811
=> fix: Update various dependencies

tests/test_api.py
The new version of Redis doesn't return the dbsize the same way as the old one, which causes this test to flake.
Remove it for now and debug the flake later.
=> fix: Remove redis check for dbsize

snuba/admin/clickhouse/nodes.py
Currently this breaks the admin page when an experimental cluster is not properly configured. Make it so that only the bad cluster config is affected
=> fix(admin): make get local table name resilient to bad clickhouse configs

requirements.txt, snuba/admin/views.py, snuba/web/views.py
Dependabot wanted werkzeug to go to 2.1.2, but doing that required updating
Flask, which required updating Jinja2 etc. so I used a slightly less version
and we can tackle updating Flask etc. separately.
This is aggregating a few dependabot PRs:
https://github.com/getsentry/snuba/pull/2833
https://github.com/getsentry/snuba/pull/2834
https://github.com/getsentry/snuba/pull/2835
https://github.com/getsentry/snuba/pull/2836
=> fix: Package updates

snuba/migrations/groups.py, snuba/migrations/snuba_migrations/generic_metrics/0004_sets_raw_add_granularities.py, snuba/migrations/snuba_migrations/generic_metrics/0005_sets_replace_mv.py
Allow for custom granularities to be entered in the raw table and expanded in the materialized view
=> db(metrics): migrations to update generic sets schema

snuba/settings/validation.py
This is necessary for https://github.com/getsentry/ops/pull/4910/files to deploy.
The first attempt to deploy that errored out with this log:
```
│ Traceback (most recent call last):                                                                                                                                                                                 
│   File "/usr/local/bin/snuba", line 33, in <module>                                                                                                                                                                
│     sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())                                                                                                                                              
│   File …
```
=> feat(metrics): add snuba-generic-metrics to topics for validation

snuba/datasets/generic_metrics_processor.py
On our last attempt to deploy this consumer, we found that some 64-bit ints from sentry were causing overflow. Sentry issue link: https://sentry.io/organizations/sentry/issues/3385584245/events/fe6a45136d3f461a97ce8f02271d2b2e/?project=300688
Verified that this works on the MAX_VALUE in https://github.com/getsentry/sentry/blob/cf018ef83b999b5287d1fde7ea523d56d09a228d/src/sentry/db/models/fields/bounded.py#L66
```
>>> x = 9223372036854775807
>>> x.to_bytes(length=8,byteorder='little')
b'\xff\xff\xff\xff\xff\xff\xff\x7f'
>>> x.to_bytes(length=4,byteorder='little')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
OverflowError: int too big to convert
```
After making this change, I took a message that caused one of the sentry errors and ran it through my local …
=> fix(metrics): handle 64-bit ints

snuba/migrations/snuba_migrations/replays/0001_replays.py
the materialized trace_ids column needs to be an array. there is no data in this table, will simply drop and re-create.
=> fix(replays): correct initial migration

snuba/consumers/utils.py, snuba/subscriptions/executor_consumer.py, tests/consumers/test_utils.py
**context**
Okay so for the last piece of https://github.com/getsentry/snuba/pull/2761, we need to get the total partition count to use in our calculation for the max_concurrent_queries.
As stated in this comment https://github.com/getsentry/snuba/pull/2761#discussion_r905614595, there are a couple ways to go about this:
1. Keep track of the total number of partitions per topic in settings (implemented in https://github.com/getsentry/snuba/pull/2885)
2. Use the kafka admin api to get the number of partitions (as is implemented in this PR)
For this PR I was thinking that I would just log the metrics for `partition_count` to verify this works, but also to see what the impact of making these requests to the kafka admin is. I'm assuming it shouldn't be too much of an impact since this would …
=> ref(consumers): Add get_partition_count

snuba/datasets/entities/factory.py, snuba/datasets/entities/generic_metrics.py, snuba/datasets/factory.py, snuba/datasets/generic_metrics.py, snuba/datasets/generic_metrics_processor.py, snuba/datasets/metrics_messages.py, snuba/datasets/storages/factory.py, snuba/datasets/storages/generic_metrics.py, tests/test_generic_metrics_api.py
I wanted to make sure we didn't have regressions in terms of metrics_sets consumption, which required adding an e2e test, which itself required exposing the metrics_sets dataset. 
The `GENERIC_METRICS_SETS` entity is not ready for prod traffic, but I didn't want to blow up the scope of this PR. If people prefer, I can increase the scope of this PR
Next steps:
1. getting proper granularity processing and validation on queries
1. adding rate limiting for queries
1. proper array join optimizations (specifically because tags now have raw and indexed values)
I think this can be used by clients once next steps are complete
=> feat(metrics): expose generic_metrics dataset, generic_metrics_sets entity, add e2e test

snuba/cli/offline_replacer.py
This script is for disaster recovery scenarios where we need to temporarily skip a number of replacements and we dump them into a file.
The script scans the file and re-executes them one by one using the same logic as the replacement consumer.
It provides a dry run mode, and an offset mode to skip part of the file. 
The format of the file must be equivalent to the one from Kafka.
=> feat(replacements) Script to execute batches of replacements

requirements.txt
It seems @untitaker marked it as unmaintained: https://github.com/untitaker/python-atomicwrites/commit/d18328460520e18b4f197297f962d4444c5889b6
which appears to break the build (https://github.com/getsentry/snuba/runs/7257404301?check_suite_focus=true)
and I don't believe we're actually using it
=> remove atomicwrites from requirements.txt

snuba/datasets/storages/generic_metrics.py
Right now we parse the JSON of the incoming message and compare it against the `metric_type` for the specific consumer, but we can do a direct string compare of the header value and avoid JSON parsing altogether for many incoming messages.
=> feat(mep): do kafka-header filtering to avoid JSON overhead for generic-metrics

snuba/utils/metrics/timer.py, snuba/web/__init__.py
Now we are on Python 3.8 TypedDict is properly supported. We no longer
need to import from mypy_extensions.
=> ref: Fix TypedDict import

snuba/datasets/message_filters.py, snuba/datasets/storages/generic_metrics.py, tests/datasets/test_message_filters.py
I mistakenly thought that the `KafkaHeaderFilter` was passing matches but it was actually dropping them, so we were dropping all MEP messages (which is fine, it's pre-prod).
This fixes the issue
=> feat(mep): fix header filter error

snuba/datasets/entities/generic_metrics.py, snuba/query/processors/granularity_processor.py, tests/query/processors/test_granularity_processor.py, tests/test_generic_metrics_api.py
add support for bucketed time and handling the mapping of `granularity : enum value` in query processing
@wmak @ahmedetefy for visibility
=> feat(mep): support time bucketing in queries

snuba/clickhouse/native.py, snuba/clusters/cluster.py, snuba/optimize.py, snuba/settings/__init__.py, tests/clickhouse/test_native.py, tests/clusters/fake_cluster.py
Firing an optimize query causes a merge operation. This operation runs
in the background. So even if an error is raised(which is socket timeout
exception caused because optimize queries take longer to execute), it
does not indicate a failure in running the query. The cost of re executing
the query is huge. Hence we add an option to specify whether a query should
be retried or not. For optimize queries, we make them non-retryable.
Also increased the timeout value for the optimize queries to 4 hours
since we are seeing the socket timeout exception happen regularly
during beginning of the week.
=> fix(optimize): Make optimize queries non retryable

snuba/web/db_query.py, snuba/web/views.py, tests/fixtures.py, tests/helpers.py, tests/test_replays_api.py
There are some types of data (IP addresses, UUIDs) that are converted to
classes in the result (ipaddress.IPv4Address, uuid.UUID). These classes are not
JSON serializable, so would throw an exception when encoded into the cache or
returned in the JSON response. Instead, automatically encode them as strings.
Context:
In previous datasets (errors, transactions) that had these types of columns
there are mappers and query processors that transform the query so that
Clickhouse returns a string instead of the class. With newer datasets like
replays they do not have these processors. Instead of forcing new datasets to
have these processors, or to wrap all calls with `toString`, we will
automatically JSON encode these results as strings.
=> feat: Add a str default to JSON encoding

snuba/settings/__init__.py
Since we disabled running TTL merges on the tiger clusters, we can now start the parallel phase of optimize merges earlier. This would allow merges to end much earlier and hopefully before the peak traffic time.
=> fix(optimize): Start parallel merges earlier

snuba/querylog/__init__.py, tests/test_snql_api.py
To help better monitor query performance of the Snuba API, we want to add
the app_id tag to timer query metrics in order to add an extra dimension
to filtering.
=> feat: Add app_id to snuba timer query metrics

cloudbuild.yaml
We were seeing cloud build failures pretty regularly -- in an example log, the e2e tests finished but the container was still not shut down at 10 minutes. Since this doesn't happen every time I bet the timeout is just too low for "cleanup"
In the logs of a couple runs:
```
Finished Step #4 - "e2e-test"
ERROR
ERROR: build step 4 "gcr.io/sentryio/docker-compose" failed: context deadline exceeded
```
=> fix(ci): increase cloud build timeout 10m->15m

tests/datasets/test_functions_processor.py
The processor derives the parent fingerprint from the parent function, so each
function does not need to hold the parent fingerprint.
=> tests(profiling): Remove unused code in functions processor tests

snuba/subscriptions/scheduler_processing_strategy.py
Remove the code that prevented the tick buffer from making progress
when the buffers for all partitions are full. This was supposed to
be an optimization to avoid checking the buffers for every tick
unnecessarily but actually prevented the TickBuffer from making progress
in some circumstances.
=> fix(subscriptions): Fix bug where scheduler got stuck in global mode

snuba/datasets/entities/profiles.py
We want to generate some timeseries on the profiles. The timeseries processor
will allow us to use the granularity clause in snql.
=> feat(profiling): Add timeseries processor for profiles entity

snuba/datasets/replays_processor.py, snuba/datasets/storages/replays.py, snuba/migrations/snuba_migrations/replays/0001_replays.py, tests/datasets/test_replays_processor.py, tests/fixtures.py
- sequence_id 
- remove from the sorting key, and replace with timestamp
- make nullable (so that way we can receive out-of-bands updates)
- rename to segment_id (sequence_id is kind of ambiguous)
- add default empty string for the user field
- add the materialized function for user_hash (missed this when copying the schema from txs, etc.)
We have received no production traffic so no problem with simply rerunning the initial migration, and Colton and I are the only developers who have run the migration locally and we can handle re-running.
=> ref(replays): adjust original schema

snuba/optimize.py, snuba/optimize_scheduler.py, tests/test_optimize.py
The `optimize_partitions` api is primarily called from `optimize_partition_runner` from the cron job to control the execution based on different schedules When a timeout is provided to the api, it means that the current schedule can run only till the provided timeout.
Because `optimize_partitions` is run in a threaded context, it is not easy to capture its exception it raises since by the time join is called on the thread, the threads stack trace is already gone.
What is important for us is that the optimize job raise an exception when OPTIMIZE_JOB_CUTOFF_TIME is reached. Which it does in OptimizeScheduler's get_next_schedule. The code is here https://github.com/getsentry/snuba/blob/master/snuba/optimize_scheduler.py#L96-L98. We don't care about transitions between different schedules.
=> fix(optimize): Remove exception from optimize_partitions

snuba/datasets/entities/generic_metrics.py
For safety purposes, rate limit requests by project_id/org_id
=> config(mep): add rate limiter to entities

snuba/settings/validation.py
Snuba validation blocking ops repo changes for `snuba-dead-letter-replays` and `ingest-replay-events`
=> fix(validation): Validate new Replays topics

tests/subscriptions/test_combined_scheduler_executor.py, tests/subscriptions/test_executor_consumer.py
This option no longer exists, it was only used during the subscriptions roll out
=> test: Clean up subscriptions tests

.freight.yml
- There is no way to know whether a consumer is experimental without diffing the two config files.
- Added a comment identifying split between stable and experimental consumers in the config
=> fix(config): Add comment identifying experimental consumers

snuba/settings/validation.py
adds back in the validation for the old topic, until i can have ops remove it from the production configuration.
=> fix(replays): add old topic back in validation

.freight.yml
- the replays consumer should be good to go on freight now. The kafka topic has been added, and we're ready to deploy.
- i've confirmed the name of the consumer in the ops repo, `replays-consumer`, is correct.
=> chore(replays): add replays consumer to .freight.yaml

snuba/migrations/groups.py, snuba/migrations/snuba_migrations/profiles/0003_add_device_architecture.py
This PR adds a new `architecture` column to the `profiles_local` table.
`architecture` is a string describing the architecture of the CPU that is used in the device that collected the specific profile.
=> feat(profiling): add architecture column to profiles_local table

snuba/datasets/storages/replays.py, snuba/migrations/groups.py, snuba/migrations/snuba_migrations/replays/0003_alter_url_allow_null.py
The `url` column should have allowed null in the original migration.
=> feat(replays): Alter url column to allow null

requirements.txt
This is the version that includes the fix for None header values crashing the Python
interpreter which we encountered in Sentry.
=> build: Bump confluent kafka to 1.8.2 everywhere

snuba/datasets/entities/transactions.py, tests/datasets/test_upgrade_selector_transactions.py
The subscription queries use finish_ts in queries instead of timestamp. Added code to selector function to look at both timestamp and finish_ts columns to determine rollout.
Tested locally end to end to verify that transactions use the new cluster when appropriate paramaters are set.
=> fix(upgrade): Check finish_ts for transactions upgrade

snuba/optimize.py, snuba/optimize_scheduler.py, snuba/settings/__init__.py, snuba/settings/settings_test.py, tests/test_optimize_scheduler.py
With parallel optimizations, one observation made is that the load
gets higher during the end of merge. This could potentially be
because theres a lot of IOPS we do during the end of the merge.
With parallel merges, it can get exacerbated because there's a
burst of higher IOPS happening during the end of the merge.
Have added a mechanism where we add a jitter to the starting of
parallel optimize threads to avoid those bursts.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that …
=> feat(optimize): Add jitter to optimize thread start time

snuba/migrations/groups.py, snuba/migrations/snuba_migrations/transactions/0015_transactions_add_source_column.py
Add new column `source` to transactions group.
PR based on [Snuba migrations field guide](https://github.com/getsentry/snuba/blob/master/MIGRATIONS.md).
Processor implementation lives in https://github.com/getsentry/snuba/pull/2985
=> feat(migrations): Add source column to transactions

snuba/clickhouse/native.py, snuba/clusters/cluster.py, snuba/reader.py, snuba/web/db_query.py, tests/clusters/test_cluster.py, tests/web/test_cache_partitions.py, tests/web/test_db_query.py
Added a mechanism to override the query settings that are fetched from runtime config. This is to allow different query settings on the errors cluster.
The current mechanism provides a way of overriding using cache partitions which is necessary because prod and tiger cluster use the same entity.
=> feat(query): Mechanism to override query settings

scripts/ddl-changes.py
When applying a migration I would like to add backward migrations as well in the PR since it is handy to have it just in case its needed
Tested it locally using an existing PR
```
-- start migrations
-- forward migration transactions : 0015_transactions_add_source_column
Local operations:
ALTER TABLE transactions_local ADD COLUMN IF NOT EXISTS transaction_source LowCardinality(String) AFTER title;
Dist operations:
ALTER TABLE transactions_dist ADD COLUMN IF NOT EXISTS transaction_source LowCardinality(String) AFTER title;
-- end forward migration transactions : 0015_transactions_add_source_column
-- backward migration transactions : 0015_transactions_add_source_column
Local operations:
ALTER TABLE transactions_local DROP COLUMN IF EXISTS transaction_source;
Dist operations:
ALTER TABLE …
```
=> ci(migrations): Print backward migration in the PR

snuba/datasets/storages/transactions_common.py, snuba/datasets/transactions_processor.py, snuba/migrations/snuba_migrations/transactions/0015_transactions_add_source_column.py, tests/datasets/test_transaction_processor.py
Start processing new transaction annotation:
```
{ "transaction_info": {"source": "url"} }
```
https://develop.sentry.dev/sdk/event-payloads/transaction/#transaction-annotations
and storing  it using new column `transaction_source` from https://github.com/getsentry/snuba/pull/2982
**PLEASE DON'T MERGE** until https://github.com/getsentry/snuba/pull/2982
resolves [TET-270]
[TET-270]: https://getsentry.atlassian.net/browse/TET-270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(transactions): Start processing `transaction_source` in transactions_processor.py

requirements.txt, snuba/util.py, snuba/utils/metrics/backends/datadog.py
This reverts https://github.com/getsentry/snuba/pull/2887, in an effort to see if this is the cause of [SNUBA-2WK](https://sentry.io/organizations/sentry/issues/3386195934/?project=300688)
=> (deps): revert update to datadog version 0.44.0

snuba/query/processors/tuple_unaliaser.py, tests/query/processors/test_tuple_unaliaser.py
We don't need the knob of controlling whether to use tuple_unaliaser
anymore.
=> ref(rollout): Remove config option of tuple unaliaser

.freight.yml
These are deployed in prod but we want freight to deploy them automatically
=> config(mep): add generic metrics schedulers/executors to freight

.freight.stable.yml
ready for stable since https://github.com/getsentry/snuba/pull/3014 deployed successfully
=> config(mep): add schedulers/executors to snuba-stable freight

snuba/datasets/storages/transactions_common.py, snuba/datasets/storages/transactions_v2.py
In order to map the transactions dataset to the transactions-tiger
cluster and make it seamless, have the same set of query processors
run for both.
Verified locally that applying the query processor on 20.7 cluster
does not have a negative impact
=> feat(rollout): Make transaction query processors same

snuba/settings/__init__.py
So our tests will pass on the sentry monorepo.
=> Remove replays from the skipped migrations group

snuba/datasets/storages/generic_metrics.py
- add the TableRateLimit and TupleUnaliaser on generic_metrics storages
- remove the broken ArrayJoinKeyValueOptimizer (it didn't work because `tags` has two value columns, neither named value)
=> config(mep): add table rate limit and tuple unaliaser to sets/distributions

snuba/datasets/entities/discover.py
After working on https://github.com/getsentry/sentry/pull/37295, 
@wmak suggested to add `transaction_source` to `TRANSACTIONS_COLUMNS` so 
we can query it from discover with this patch:
```diff
--- a/src/sentry/snuba/events.py
+++ b/src/sentry/snuba/events.py
@@ -466,8 +466,7 @@ class Columns(Enum):
group_name=None,
event_name=None,
transaction_name="transaction_source",
-        # Only available in transactions, pretend like its a tag so we dont error and just null instead
-        discover_name="tags[transaction_source]",
+        discover_name="transaction_source",
alias="transaction.source",
)
```
=> fix(discover): add missing transaction_source to TRANSACTIONS_COLUMNS

snuba/environment.py, snuba/settings/__init__.py
According to @untitaker `parent_sampled` is already a special case in the python SDK (see internal slack thread https://sentry.slack.com/archives/C02N6582ZFA/p1659476660850549?thread_ts=1659473664.627579&cid=C02N6582ZFA for more info) and traces with this context set will never be rejected, even with a sample rate of 0.
We'd like to start testing service-side sampling, and this would unblock us from that.
This should be deployed with an eye on our sentry project to make sure that our assumption is correct
=> config(ds): get rid of existing logic to move to dynamic sampling

requirements.txt
Our current version sentry-python doesn't have transaction source
fixes. So we need to bump it to start sending correct transaction source
from snuba.
=> build: Bump sentry-python to 1.9.0

snuba/web/db_query.py
In a world with many clickhouse clusters the global rate limiter is not very useful. 
It is actually causing issues to redis as the global keys are really hot.
=> fix(rate limiter) Allow us to disable the global rate limiter

snuba/datasets/storages/processors/replaced_groups.py
Adding a project to this list will cause Snuba to ~give up on consistency~ give up on fine-grained consistency
in queries that include that project.
=> fix(inc): Introduce denylist that stops attempting consistent queries per project [INC-190]

snuba/datasets/errors_replacer.py, snuba/datasets/storages/processors/replaced_groups.py, tests/test_replacer.py
This is an insufficient fix for correctness, it mainly ensures the redis
set does not grow unbounded.
The redis set should be trimmed to the most recent groups. I have **not** thought through the product implications of doing that (we should automatically fallback to FINAL), but it seems better to me than manually denylisting projects over the weekend.
=> fix(replacements): Limit size of excluded groups set [INC-190]

snuba/datasets/replays_processor.py, snuba/datasets/storages/replays.py, tests/datasets/test_replays_processor.py
Depends on: https://github.com/getsentry/snuba/pull/3021
- Add `urls`, `user_agent`, and `replay_start_timestamp` columns.
- Removes `url` column.
- Removes old url processor.
=> feat(replays): Add urls, user_agent, and replay_start_timestamp fields and processor

snuba/datasets/pluggable_entity.py, tests/datasets/entities/test_pluggable_entity.py
The goal of this new class is to provide a less flexible version of Entity that will not be subclassed but will be instantiated based on contents of YAML config files.
Once this and https://github.com/getsentry/snuba/pull/3046 are merged, we can make some changes to dynamically populate entities from YAML that fit certain characteristics (single storage plan, a limited set of query processors/mappers/etc.)
This should look somewhat similar to https://github.com/getsentry/snuba/pull/3037/files when done though that's obviously not complete
=> config(datasets) - create a PluggableEntity class

snuba/datasets/factory.py, snuba/utils/config_component_factory.py, tests/admin/test_api.py, tests/datasets/test_dataset_factory.py
YAML datasets and python datasets will need to coexist for some time in production. 
The factory functions are the gateway to accessing datasets.
In order to make the transition easier, a few things were refactored in the dataset factory:
1. One container for all global state in the factory (down from four)
2. Only one list of dataset names maintained
3. remove complicated mapping/caching logic
4. Remove unused `DISABLED_DATASETS` feature
This PR also introduces the ConfigComponentFactory class that I would like to use for all other ConfigComponents (Datasets, Entities, Storages, QueryProcessors) to make the loading and merging of ConfigComponents have a uniform, predictable interface.
=> ref(MDC): cleanup dataset factory, formalize factory pattern

snuba/clickhouse/formatter/expression.py, snuba/clickhouse/formatter/query.py, snuba/query/__init__.py, snuba/query/expressions.py, snuba/query/parsing.py, snuba/web/db_query.py, snuba/web/query.py, tests/clickhouse/test_query_format.py
Context:
To help improve the frequency of raw sql cache hits, this PR is
responsible for sorting column fields and expression conditions in raw
SQL queries. Note: this code should not interferer with the current 
operations of Snuba query caching. This is an experiment to investigate 
the consistency of the natural ordering of columns and conditions.
Test Plan:
* Provide functionality for sorting, and select a certain percentage
(defined in runtime config) of raw queries to be part of the
experiment.
* Exclude queries from an explicit set of referrers to avoid
some computational overhead.
* Record metrics of cache hits of sorted and unsorted queries.
* Determine whether or not sorting should be implemented for all queries.
Sorting is *only* to expressions simple Columns in SELECT clause …
=> feat: Sort raw sql fields and conditions [Experiment]

snuba/cli/subscriptions_scheduler.py
Uses the entity enum for the list of options in entity enum name CLI choice option. Addressing this https://getsentry.atlassian.net/browse/SNS-1570
=> SNS-1570-rely-on-the-entity-enum-in-the-subscriptions-scheduler-cli-command

snuba/datasets/factory.py, snuba/utils/config_component_factory.py, tests/admin/test_api.py, tests/datasets/test_dataset_factory.py
See the original reverted PR here: https://github.com/getsentry/snuba/commit/46566686b32be90f1d95ce1eed633e70cdbcf5ab
@volokluev initial hypothesis of multiple threads accessing incomplete states of the dataset factory map was tested and verified. This PR includes an additional change for moving the initialization of the dataset mapping to the constructor of _DatasetFactory. This ensures the dataset factory object either contains the full map or is None. Test was added accordingly
=> ref(MDC): cleanup dataset factory, formalize factory pattern [updated]

snuba/datasets/storages/transactions_common.py, snuba/migrations/groups.py, snuba/migrations/snuba_migrations/transactions/0016_transactions_add_group_ids_column.py
To link transactions to their associated groups, this PR adds a new array column to transactions table. `group_ids` would contain at most 10 group ids.
I will follow up with changes to the transactions processor once the column is in prod.
Fixes WOR-2086
=> feat(transactions): Add group_ids column to transactions

snuba/admin/clickhouse/system_queries.py
This will allow [`SHOW` commands ](https://clickhouse.com/docs/en/sql-reference/statements/show/) in system queries on snuba admin. Show queries do not reveal customer data and are safe, read-only. Addresses JIRA https://getsentry.atlassian.net/browse/SNS-1625. 
Reviewers, please confirm that the Regex is safe. Right now, it is `SHOW [\w\s\]+$` so theoretically an adversary could insert arbitrary subqueries with the `[\w\s\]` matching. We can probably come up with a more complex regex to skip matching any unsafe subqueries but I'm not sure if its worth the work given that the admin threat model is targeted towards accidental mistakes rather than adversarial attacks.
=> feat(admin):  allow show command to system queries SNS-1625

docs/source/architecture/overview.rst
Just removed same word used twice one after another.
=> doc:  fix small typo in the architecture overview

snuba/datasets/replays_processor.py, tests/datasets/test_replays_processor.py
- process the trace_ids / error_ids as uuids. This normalizes uuids without dashes / with dashes.
- also apply list element limits to trace_ids
=> fix(replays): process trace_ids / error_ids as uuids

snuba/web/__init__.py, snuba/web/db_query.py, snuba/web/query.py, tests/web/test_query_exception.py
This happened in the metrics executor logs when the logger tried to print the exception
AttributeError: 'QueryException' object has no attribute 'message'
This is because this exception is not defined properly. This is documented behavior
https://github.com/getsentry/snuba/blob/master/snuba/utils/serializable_exception.py#L90-L94
This will also most likely fix the double raising of exceptions issues in sentry
=> fix QueryException not being instantiated properly

snuba/datasets/configuration/entity_builder.py
mypy was updated on master while my feature branch for https://github.com/getsentry/snuba/pull/3063 was out.
The version of mypy on my feature branch did type checking on variant constructor arguments -- this one apparently doesn't and complains about `type: ignore` (from before):
```
➜  snuba git:(master) ✗ make backend-typing 
mypy snuba tests --strict --config-file mypy.ini --exclude 'tests/datasets|tests/query|tests/state|tests/snapshots|tests/clickhouse|tests/test_split.py|tests/test_consumer.py'
snuba/datasets/configuration/entity_builder.py:82: error: Unused "type: ignore" comment
snuba/datasets/configuration/entity_builder.py:91: error: Unused "type: ignore" comment
snuba/datasets/configuration/entity_builder.py:102: error: Unused "type: ignore" comment …
```
=> fix(typing) - fix entity_builder to account for mypy updates

bin/mocks/mock-subscriptions, snuba/datasets/entities/factory.py, snuba/datasets/factory.py, snuba/subscriptions/executor_consumer.py, snuba/web/converters.py, snuba/web/views.py, tests/datasets/test_dataset_factory.py, tests/datasets/test_entity_factory.py, tests/query/joins/test_equivalence_adder.py, tests/query/joins/test_equivalences.py, tests/query/joins/test_subqueries.py, tests/subscriptions/__init__.py, tests/test_api.py
Similar to dataset factory in https://github.com/getsentry/snuba/pull/3060, both YAML and Python defined entities will need to coexist. This entity factory pattern helps clean up the old method of initializing and accessing entities. 
This PR is responsible for the following:
1. One central container for all entities to live in (both yaml and python defined) 
2. Remove complicated mapping/caching logic
3. Remove unused `dev_entity_factories`
This PR is *not* responsible for the following:
1. Removing the EntityEnum (the entity factory still requires the full list of enums)
2. Dynamic importing of entities (each entity remains hard-coded in factory)
Additionally, the multithreaded tests for accessing the dataset factory was moved to the top of the test file to ensure test is ran with fresh …
=> ref(MDC): Create Entity Factory Pattern

Dockerfile, Makefile, mypy.ini, requirements.txt, snuba/cli/admin.py, snuba/cli/api.py, snuba/utils/uwsgi.py
pyuwsgi provides wheels making it much faster to install whereas uwsgi isn't wheelable
this also cuts about 10 minutes from the uncached arm64 image build (17 minutes -> 7 minutes)
=> ref: switch from mywsgi/uwsgi to pyuwsgi

snuba/web/__init__.py, snuba/web/db_query.py, snuba/web/query.py, tests/web/test_query_exception.py
If the message field is not set on the SerializableException, then there will be no message in sentry. This change makes sure that where we raise a QueryException, we put the message we want in there (since QueryException is a catchall for many exceptions)
=> make the QueryException's message go through to sentry

.github/workflows/image.yml
I'll leave the other image for now -- but I plan to use this to replace both the `arm64-dev` and the dockerhub image in `sentry` ci
=> ref: publish a multiarch application image to ghcr

snuba/cli/subscriptions_executor.py, snuba/cli/subscriptions_scheduler_executor.py, snuba/subscriptions/combined_scheduler_executor.py, snuba/subscriptions/executor_consumer.py, tests/subscriptions/test_combined_scheduler_executor.py, tests/subscriptions/test_executor_consumer.py
**context:**
This is a follow up of the completion of https://github.com/getsentry/snuba/pull/2761. Now that the executors are using the calculated max concurrent queries in production, we can get rid of the cli arg. 
https://github.com/getsentry/ops/pull/5172 must be merged first so that we can safely remove the cli without there being a reference to it in the ops repo.
=> ref(subscriptions): Remove max_concurrent_queries cli arg

snuba/utils/uwsgi.py
I regressed reloadability in #3076 (a reload would cause `uwsgi` to lose the virtualenv)
see also https://github.com/unbit/uwsgi/issues/2478
=> ref: set binary-path for pyuwsgi to be reloadable

snuba/datasets/entities/factory.py
https://getsentry.atlassian.net/browse/SNS-1656
Mix of latest changes broke the subscriptions executor for generic_metrics_sets (see https://sentry.io/organizations/sentry/issues/3552496714/)
Reproduced the issue locally and observed that this fixes it
=> fix(mdc): use entity name for mapping when type is not sufficient

docs/source/configuration/dataset.rst, docs/source/configuration/intro.rst, docs/source/configuration/overview.rst, docs/source/index.rst
Add some quick placeholder files for Dataset configuration. Any new components
should have a new file created (`entity.rst`) and then add that file name to
`overview.rst` so it gets indexed in the ToC.
=> feat: Add initial documentation for Dataset configuration

.envrc, Dockerfile, Makefile, docs/source/contributing/environment.rst, requirements-test.txt, requirements.txt, setup.py
this changes from using public pypi to using our "internal" (but publicly accessible) pypi
the main advantage is on the 4 supported platforms (linux, macos) x (x86_64, arm64) all python dependencies are prebuilt and will not need to be built from source
pypi packages are sourced from https://github.com/getsentry/pypi
=> ref: use internal pypi for prebuilt packages

snuba/datasets/configuration/dataset_builder.py, snuba/datasets/configuration/generic_metrics/dataset.yaml, snuba/datasets/configuration/json_schema.py, snuba/datasets/dataset.py, snuba/datasets/entities/factory.py, snuba/datasets/factory.py, snuba/datasets/pluggable_dataset.py, snuba/settings/__init__.py, tests/datasets/configuration/test_dataset_loader.py
- Generic Metrics Dataset is loaded from a config file
- Added minimal `PluggableDataset` which can be extended as we config more complicated datasets
- Added validation for Dataset config
- New dataset configs will be automatically picked up
- Any dataset config file should be named `dataset.yaml` and placed as follows to be automatically picked up
- `snuba/datasets/configuration/<dataset_name>/dataset.yaml`
=> feat(MDC): Generic Metrics Dataset loaded from Config

snuba/datasets/cdc/groupedmessage.py, snuba/datasets/entities/__init__.py, snuba/datasets/entities/events.py, snuba/datasets/entities/factory.py, tests/datasets/test_cdc_events.py, tests/datasets/test_entity_factory.py, tests/pipeline/test_composite_planner.py, tests/query/data_source/test_join.py, tests/query/formatters/test_query.py, tests/query/joins/equivalence_schema.py, tests/query/joins/join_structures.py, tests/query/joins/test_equivalence_adder.py, tests/query/joins/test_equivalences.py, tests/query/joins/test_subqueries.py, tests/query/snql/test_invalid_queries.py, tests/query/snql/test_query.py, tests/query/snql/test_snql_anonymizer.py, tests/query/test_nested.py
🤮 `EntityKey.GROUPEDMESSAGES` 💩 
😎 `EntityKey.GROUPEDMESSAGE` 🥇 
- This is necessary to clean up `EntityKey` and unblock #3109
=> ref(EntityKey): Rename GROUPEDMESSAGES to GROUPEDMESSAGE

snuba/clusters/storage_sets.py, snuba/settings/validation.py
In order to swap the mapping of dataset to clusters for events and errors_v2, we would need to get rid of the validation since CDC datasets are not defined in the tiger clusters.
=> fix(settings): Remove requirement of CDC and events to be on same cluster

snuba/subscriptions/scheduler_consumer.py, snuba/utils/streams/kafka_consumer_with_commit_log.py
The arroyo.synchronized module is deprecated and will be removed. Import the commit codec from arroyo.commit instead.
=> ref(arroyo): Fix arroyo imports

snuba/datasets/storages/transactions_common.py, snuba/migrations/groups.py, snuba/snuba_migrations/transactions/0017_transactions_add_app_start_type_column.py
Adds the column app_start_type to transactions. For more context,
see https://github.com/getsentry/sentry/issues/36927.
=> feat(transactions): Add app_start_type migration

cloudbuild.yaml
Add a .reporterrors file with "no" in the self-hosted directory when running e2e tests to avoid the user prompt.
=> fix(self-hosted): Skip user prompt for dogfood self-hosted changes

.github/workflows/ci.yml, .pre-commit-config.yaml, snuba/datasets/configuration/json_schema.py
This PR is responsible for the following:
* Added component config validation pre-commit hook. The python file `snuba/validate_configs.py` was used over the `check-jsonchema` CLI because that only supports `.json` files as an input argument. Our schemas are `.py`. Also note, print statements are not forwarded to stdout in pre-commit hook unless the test fails. 
* `additionalProperties` were added to each full schema to ensure that no arbitrary keys are defined in config. Schema will not validate if a user inputs a key that is not present in `properties`.
=> feat(mdc): Add pre-commit check for config validation and additionalProperties to schema

snuba/snuba_migrations/generic_metrics/0004_sets_raw_add_granularities.py
**context:**
Normally we wouldn't update migrations in place, but the fix to the migration won't affect the state. The migration `0004_sets_add_raw_granularities` was already wrong and there is a follow up migration https://github.com/getsentry/snuba/pull/2892 that fixes it for the prod configuration.
In prod right now for generic metrics we have the local and dist tables on the same node. When trying to run these migrations in different kinds of configurations such as the local and dist tables separated, you'll run into the following error:
```
clickhouse_driver.errors.ServerException: Code: 60.
DB::Exception: Table default.generic_metric_sets_raw_local doesn't exist..
```
since we are trying to add a column to a node that doesn't have that table. So to fix this, we move the operation on …
=> fix(migrations): Remove dist operations

tests/datasets/test_entity_factory.py
The addition of the EntityKey class was breaking `tests/datasets/test_entity_factory.py` when individually executed. This is because config entity keys  (currently `GENERIC_METRICS_SETS` and `GENERIC_METRICS_DISTRIBUTIONS`) are registered when the `PluggableEntity` is created. As a result, this isolated test threw an AttributeError when trying to access config entity keys before the factory was created.
=> Fix unit test: Initialize entity factory to register config entity keys

snuba/cli/multistorage_consumer.py
This is not needed since we already check that there is either:
- a topic passed in via CLI, or
- default topic is shared between both storages passed
In the case where a topic override is passed via CLI and that topic is on another cluster, this will incorrectly raise an exception.
This is blocking us from migrating the transactions Kafka cluster.
=> fix(multistorage-consumer): Remove incorrect assertion

snuba/datasets/generic_metrics_processor.py, tests/datasets/test_metrics_processor.py
When the metrics indexer starts writing tag values as strings, the payload of the message would change. We need to start accepting strings for tag values during migration to the new system. Once we migrate, we can change the protocol to only accept strings.
=> feat(gen-metrics): Accept strings as tag values

snuba/web/views.py
This PR is responsible for removing un-used routes in Snuba API. After removing `default_entity`, the `/insert` and `/eventstream` routes were updated to accept `Entity` as opposed to deriving the entity from dataset.
Original changes to endpoints: https://github.com/getsentry/snuba/pull/3142
Changes to Sentry tests to use new endpoints: https://github.com/getsentry/sentry/pull/38877
=> fix(snuba): Deprecate un-used routes after removing default_entity from Dataset

requirements.txt
This reverts commit d744178f89ee4a45c1ab4f9fdaa4902dbf706362.
Snuba admin pod is in a crashloop for some reason after this change. More investigation is needed, let's revert first though.
=> Revert "build(deps): bump urllib3 from 1.26.11 to 1.26.12 (#3084)"

.github/workflows/ci.yml
outside contributors, including dependabot, will not be able to push to ghcr -- so ignore failures when attempting to do so
=> ref: allow failure when pushing to ghcr in PRs

.github/dependabot.yml
Unfortunately bumping this package caused major performance issues in the past. Ignore upgrades so we don't get bugged about this every week.
=> build(dependabot): Ignore parsimonious

snuba/query/processors/physical/replaced_groups.py
This was changed accidentally in #3098 because the string mirrored the import path. I've double checked the PR that no other metric was renamed in this way. Changing it back so we don't have to update all the dashboards
=> fix: undo accidental metric renaming

snuba/datasets/profiles_processor.py, tests/datasets/test_profiles_processor.py
We have a new format for profiles and we need to map fields slightly differently than the usual format we handle. We detect this new format by looking if a field called `version` is set in the message.
=> feat(profiling): Handle sample format

.pre-commit-config.yaml
The `validate-configs-syntax` pre-commit hook should be using the venv created by pre-commit by default when specifying `language: python`. Calling `python3 ./snuba/validate_configs.py` does not import the current directory by default. This can be achieved by running the library module as a script. Thanks @asottile-sentry for the reference.
=> (fix): Use venv created by pre-commit for validate config

snuba/cli/migrations.py, snuba/migrations/runner.py, tests/migrations/test_runner.py
**context:**
Right now if you run ClickHouse migrations from scratch it is going to run all the migrations for all the groups (that are active). This can make sense for local development on snuba datasets, but for some of the development on the migrations tooling, often it's enough to test with just one group.
Additionally, long term goals for migrations are for folks to own their datasets, and if you were to bring up a new cluster, you are not going to need all the groups, just the groups for that cluster. You could _technically_ get away with that by running each migration individually for each group using `snuba migrations run --migration-id=<migration_id>` but that isn't super user friendly.
This PR adds the ability to run migrations per group at a time. It also makes sure to run the …
=> ref(migrations): Allow running migrations per group

snuba/datasets/common/condition_checker.py, snuba/datasets/configuration/entity_builder.py, snuba/datasets/configuration/generic_metrics/entities/distributions.yaml, snuba/datasets/configuration/generic_metrics/entities/sets.yaml, snuba/datasets/storage.py, snuba/query/processors/logical/__init__.py, snuba/query/processors/logical/basic_functions.py, snuba/query/processors/logical/custom_function.py, snuba/query/processors/logical/granularity_processor.py, snuba/query/processors/logical/handled_functions.py, snuba/query/processors/logical/object_id_rate_limiter.py, snuba/query/processors/logical/quota_processor.py, snuba/query/processors/logical/tags_expander.py, snuba/query/processors/logical/tags_type_transformer.py, snuba/query/processors/logical/timeseries_processor.py, snuba/query/processors/physical/__init__.py, snuba/query/processors/physical/conditions_enforcer.py, snuba/query/processors/physical/null_column_caster.py, snuba/utils/registered_class.py, tests/datasets/configuration/broken_entity_bad_query_processor.yaml, tests/datasets/configuration/broken_entity_positional_validator_args.yaml
Currently query processors work in the entity builder because of a hack that manually imports them and adds them to a dictionary. This PR makes the LogicalQueryProcessor a registered class and auto imports the files. In order to make this work, the `config_key` property had to be defined on all the processors which is most of the lines in this PR.
There shouldn't be much to review here
=> feat(MDC): Auto import logical processors

snuba/state/rate_limit.py, snuba/web/db_query.py, tests/test_api.py
The global rate limiter is a very hot Redis key that can't be sharded. As we move 
to a multi cluster environment that is a non-starter. Also, each table has its own
rate limiter so the global one is less useful.
=> feat: Remove global rate limiter

snuba/subscriptions/executor_consumer.py, snuba/subscriptions/scheduler_processing_strategy.py
In an effort to have a bit more visibility into both the subscriptions executor and subscriptions scheduler, I'm logging the offsets when we commit them. 
For the scheduler, I believe that we only commit once all the partitions have caught up to the same tick in (`GLOBAL` mode), and for the executor, I believe that we only commit once per second max (using the `COMMIT_FREQUENCY_SEC`).
=> Add logging for committing offsets for subscriptions executor, scheduler

snuba/attribution/log.py, snuba/datasets/entity_subscriptions/factory.py, snuba/settings/__init__.py, snuba/state/__init__.py, snuba/utils/serializable_exception.py
- There are a few random variables/constants around the codebase in the form `X = None` without any typing info
- Technically our mypy settings are soft enough so it doesn't complain but the mypy extension on vscode still complains about it
=> fix(typing): Annoying untyped variables

snuba/admin/views.py
Now that we log the result of all auth calls (currently a no-op) we're getting spammed about once/second with what I assume must be health check calls (given the low traffic to snuba admin).
Verified locally that this bypasses the method for `/health` but keeps it intact for others.
Additionally, add some logging context to benefit us in the future
=> fix(logging): remove auth for health check

snuba/utils/threaded_function_delegator.py
Warning logs emitted by `logger:snuba.utils.threaded_function_delegator` are already being captured by `logger:snuba.query` and `logger:snuba.api`. These extra logs are causing duplicate sentry issues (specifically errors from readthrough cache and rate limiting).
Examples:
* This RuntimeError logged by [snuba.utils.threaded_function_delegator](https://sentry.io/organizations/sentry/issues/3198654668/?project=300688&query=is%3Aunresolved&statsPeriod=14d) is already captured by [snuba.query](https://sentry.io/organizations/sentry/issues/3198654751/?project=300688&query=is%3Aunresolved&statsPeriod=14d)
* This TimeoutError logged by [snuba.utils.threaded_function_delegator](https://sentry.io/organizations/sentry/issues/3545430296/?project=300688&query=is%3Aunresolved) is already captured by …
=> Remove duplicate warning logs from threaded_function_delagator

requirements.txt
When we upgraded this last, we thought it caused admin to die. Since then we have new information as to why admin was dying and we have fixed it. We should upgrade it now
=> feat(dependabot): upgrade urrllib3 again

snuba/datasets/configuration/generic_metrics/storages/distributions_bucket.yaml, snuba/datasets/configuration/generic_metrics/storages/sets_bucket.yaml, snuba/datasets/configuration/json_schema.py, snuba/datasets/configuration/storage_builder.py, tests/datasets/configuration/test_utils.py
This PR is a prerequisite for auto-importing pre-filters in storage config. The pre-filter jsonschema should follow the same convention as query_processors, mappers, validators, and etc. This change involves making the pre-filter arguments an object as opposed to list for instantiating the python filter classes.
=> fix(MDC) Allow init arguments for storage pre-filters 

docs/source/architecture/partitioning.rst, snuba/clusters/cluster.py, snuba/settings/__init__.py, snuba/settings/validation.py, tests/clusters/test_cluster.py, tests/settings/test_settings.py
After discussion, we reached a consensus to change naming from `physical partition` to `slice` where applicable. This PR has those changes.
=> fix(slices): Rename physical partition to slice

tests/test_optimize.py
Since it is the optimize scheduler's cutoff time which determines whether to raise an exception or not, move the creation of the scheduler inside frozen time to have a consistent behavior during tests.
The setting `settings.OPTIMIZE_JOB_CUTOFF_TIME` also defaults to 1 day by default to avoid tests running into timeout exception. For this test, we should change it to 23 hours.
=> ref(tests): Move scheduler inside freezetime

docs/source/architecture/partitioning.rst, snuba/settings/__init__.py, snuba/settings/validation.py, tests/settings/test_settings.py
This PR:
- Removes `LOCAL_SLICES` from settings
- Modifies the definitions of `LOGICAL_PARTITION_MAPPING` and `SLICED_STORAGE_SETS` accordingly
- Updates validation and tests
- Renames `SLICED_STORAGES` --> `SLICED_STORAGE_SETS` (point to potentially discuss)
- Updates docs
=> feat(slices): Make slice count vary by storage

snuba/clickhouse/translators/snuba/allowed.py, snuba/clickhouse/translators/snuba/defaults.py, snuba/clickhouse/translators/snuba/function_call_mappers.py, snuba/clickhouse/translators/snuba/mappers.py, snuba/datasets/configuration/generic_metrics/entities/distributions.yaml, snuba/datasets/configuration/generic_metrics/entities/sets.yaml, snuba/datasets/configuration/json_schema.py, snuba/datasets/entities/discover.py, snuba/query/processors/logical/__init__.py, snuba/query/processors/logical/basic_functions.py, snuba/query/processors/logical/custom_function.py, snuba/query/processors/logical/granularity_processor.py, snuba/query/processors/logical/handled_functions.py, snuba/query/processors/logical/object_id_rate_limiter.py, snuba/query/processors/logical/quota_processor.py, snuba/query/processors/logical/tags_expander.py, snuba/query/processors/logical/tags_type_transformer.py, snuba/query/processors/logical/timeseries_processor.py, snuba/query/validation/validators.py, snuba/utils/registered_class.py, tests/clickhouse/translators/test_auto_import.py, tests/datasets/configuration/broken_entity_bad_query_processor.yaml, tests/datasets/configuration/broken_entity_positional_validator_args.yaml
This PR is responsible for adding a `config_key()` classmethod to all base classes for translators, mappers, and validators. 
Changes are the following:
* Modified configs to use class names instead of snake-case names
* Added `config_key` methods to all base class which inherit from `RegisteredClass`
=> fix(MDC): Use class names for translators, mappers, and validators config_key

requirements.txt, snuba/subscriptions/combined_scheduler_executor.py, snuba/subscriptions/executor_consumer.py, snuba/subscriptions/scheduler_consumer.py, snuba/utils/streams/kafka_consumer_with_commit_log.py, tests/subscriptions/test_executor_consumer.py, tests/subscriptions/test_scheduler_consumer.py, tests/utils/streams/test_kafka_consumer_with_commit_log.py
Arroyo now supports commit policies. We no longer need to implement commit throttling by ourselves.
=> ref: Use new commit policy from Arroyo

snuba/datasets/configuration/storage_builder.py, snuba/datasets/configuration/utils.py, snuba/datasets/plans/single_storage.py, snuba/datasets/plans/splitters/__init__.py, snuba/datasets/plans/splitters/strategies.py, snuba/datasets/storage.py, snuba/datasets/storages/discover.py, snuba/datasets/storages/errors_common.py, snuba/datasets/storages/transactions_common.py, tests/test_split.py
The transactions storage uses query splitters, so those need to be imported
automatically in the same way as other RegisteredClasses so they can be used
in configuration.
=> fix(TDC) Make QuerySplitStrategy a RegisteredClass

.github/workflows/ci.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> ref(ci): fix set-output / set-state deprecation

.freight.stable.yml, .freight.yml
This consumer is no longer running
=> build: Remove old transaction consumer from Freight

snuba/datasets/configuration/entity_subscription_builder.py, snuba/datasets/entity_subscriptions/entity_subscription.py, tests/subscriptions/entity_subscriptions/test_entity_subscriptions.py
Transactions will be randomly partitioned, this clause does not make sense unless all events are in the same partition.
=> fix: Remove filtering on offset for transactions subscriptions

snuba/admin/clickhouse/migration_groups.py, snuba/admin/views.py, snuba/settings/__init__.py, tests/admin/clickhouse_migrations/test_api.py
**context:**
A bit of context is in https://github.com/getsentry/snuba/pull/3221, but basically we want to add migrations tooling to the snuba admin tool. As seen in the previously mentioned PR, in order to know which migrations to run, a user must first pick a group. This endpoint is to populate that first dropdown of all the possible groups that one could run (or reverse) a migration for. 
**example payload:**
```json
{
"group": "generic_metrics",
"migration_ids": [
"0001_sets_aggregate_table",
"0002_sets_raw_table",
"0003_sets_mv",
"0004_sets_raw_add_granularities",
"0005_sets_replace_mv",
"0006_sets_raw_add_granularities_dist_table",
"0007_distributions_aggregate_table",
"0008_distributions_raw_table",
"0009_distributions_mv"
]
}
```
Users can pick any migration to run (or reverse) …
=> ref(admin): add migration_groups API

.github/workflows/ci.yml
The distributed tests often take around 20 minutes and sometimes over, bump timeout to 25
=> build: Increase timeout minutes in CI

snuba/datasets/configuration/generic_metrics/entities/distributions.yaml
An incorrectly named column in Generic Metrics config is causing some queries to fail.
This PR fixes the issue ([SNS-1760](https://getsentry.atlassian.net/browse/SNS-1760))
=> fix(MDC): Incorrect column name in Gen Metrics

snuba/admin/views.py, tests/admin/clickhouse_migrations/test_api.py
More context in #3227 
Add an endpoint `migrations/{group}/list` to show the migration for a group. Returns error 400 : invalid group  if the `group` is not found
e.g
```
curl http: //localhost:1219/migrations/replays/list 
[{
"blocking": false,
"migration_id": "0001_replays",
"status": "completed"
}, .... {
"blocking": false,
"migration_id": "0006_add_is_archived_column",
"status": "completed"
}]
```
=>  ref(admin): add migration groups list endpoint

snuba/subscriptions/executor_consumer.py
This simplifies getting the right position to commit from Arroyo. Also fixes a bug where the wrong offset was being committed on shutdown (it should be message.next_offset but we were actually committing message.offset)
=> ref: Use message.position_to_commit from arroyo

snuba/settings/__init__.py
Should be (roughly) synchronized with https://github.com/getsentry/sentry/pull/39988 which will send events to the new topic.
This would only affect self hosted and dev users who are using the Kafka backend. All Sentry prod environments have already been migrated via other methods to ensure zero downtime during the transition.
=> feat: Remove default mapping of "transaction" topic to "events"

snuba/datasets/message_filters.py, snuba/datasets/storages/errors.py, snuba/datasets/storages/errors_v2.py, snuba/datasets/storages/transactions.py, snuba/datasets/storages/transactions_v2.py, tests/datasets/test_message_filters.py
Errors and transactions have fully separated pipelines now. We don't need to filter based on `transaction_forwarder` anymore. This header will no longer be sent.
=> ref: Remove filtering of error and transaction messages

snuba/admin/jwt.py, snuba/settings/__init__.py
Based on this Sentry issue: https://sentry.io/organizations/sentry/issues/3669148611/?project=300688&query=is%3Aunresolved we were blocked from enforcing JWT auth in snuba admin
We don't have a way to dynamically retrieve the JWT audience that we know of that matches the format `/projects/{x}/global/backendServices/{y}` (we have x but don't know how to retrieve y). Since this won't change very much, we will just hardcode the expected audience in settings.
=> fix(JWT): stop trying to get JWT audience dynamically, hard-code in config

snuba/settings/__init__.py
We no longer emit these metrics
=> ref: Small settings cleanup

snuba/datasets/configuration/generic_metrics/storages/distributions_bucket.yaml, snuba/datasets/storages/generic_metrics.py
Stuff broke when we tried switching to the [distributed] query node which correctly does not have local tables
https://sentry.io/organizations/sentry/issues/3671781868/?project=300688&query=is%3Aunresolved
https://sentry.io/organizations/sentry/issues/3671799059/?project=300688&query=is%3Aunresolved
🤦
=> fix(gen-metrics): distributed table name wrong in config

snuba/cli/multistorage_consumer.py, snuba/cli/replacer.py, snuba/consumers/consumer_builder.py, snuba/subscriptions/combined_scheduler_executor.py, snuba/subscriptions/scheduler_consumer.py
Soon this will become a mandatory argument
=> feat: Always pass a commit policy to Arroyo stream processor

.github/workflows/ci.yml
https://github.com/getsentry/snuba/pull/3242 was supposed to increase the timeout for the distributed tests not building the snuba image. This actually does that.
=> build: Actually increase the right CI timeout

snuba/attribution/log.py, snuba/datasets/configuration/storage_builder.py, snuba/datasets/configuration/validation/post_loader.py, snuba/datasets/storages/errors.py, snuba/datasets/storages/errors_v2.py, snuba/datasets/storages/factory.py, snuba/datasets/storages/functions.py, snuba/datasets/storages/generic_metrics.py, snuba/datasets/storages/metrics.py, snuba/datasets/storages/profiles.py, snuba/datasets/storages/querylog.py, snuba/datasets/storages/replays.py, snuba/datasets/storages/sessions.py, snuba/datasets/storages/transactions.py, snuba/datasets/storages/transactions_v2.py, snuba/datasets/storages/validation.py, snuba/settings/__init__.py, snuba/settings/validation.py, snuba/state/__init__.py, snuba/utils/streams/topics.py, tests/consumers/test_utils.py, tests/datasets/configuration/test_utils.py, tests/settings/test_settings.py, tests/subscriptions/test_combined_scheduler_executor.py, tests/subscriptions/test_executor_consumer.py, tests/subscriptions/test_scheduler_consumer.py, tests/subscriptions/test_scheduler_processing_strategy.py
Similar to what we've done with `StorageKey` and `EntityKey`, we also want to use to metaclass design pattern to remove the Topic enum. However, the only difference between `Topic` and `StorageKey` and `EntityKey` is that the `Topic` key/value pairs are not uppercased/lowercased mirrors of each other. For example: `"QUERYLOG": "snuba-queries"`. As a result, when topics are registered through definition in config, they are assigned a different key name than the existing ones in code. Since topic keys are **only** used to reference topics in code and do not reflect real infrastructure (done with value pair), this was fixed by refactoring topic keys to mirror their respective value pairs.
This PR is responsible for the following:
* Deleted Topic enum and added Topic class and metaclass
* …
=> ref(MDC): Topics Enum to Class

snuba/datasets/entity_subscriptions/entity_subscription.py, tests/subscriptions/entity_subscriptions/test_entity_subscriptions.py
None of the other datasets apply this condition (they cannot since they are non semantically partitioned).
We sometimes flip large projects into to random partitioning mode to avoid backlogs and incidents. Doing so causes the alert to be completely wrong unless we remove this condition as the offset across different partitions can no longer be compared.
=> feat: Drop filtering by offset on errors dataset

snuba/admin/jwt.py
We wanted `sub`, or subject, not `id` which is a non-populated property: https://sentry.io/organizations/sentry/issues/3677952001/?project=300688&query=is%3Aunresolved
https://cloud.google.com/endpoints/docs/openapi/migrate-to-esp-v2#handle-jwt
=> fix(jwt): extract correct user ID field from JWT

snuba/migrations/policies.py, tests/migrations/test_policies.py
**context**
As we build out snuba admin tooling for clickhouse migrations, we want to make sure we have some way of deciding which migrations are actually "safe" to run in the admin tool, which may be different for various folks and migration groups. 
**MigrationPolicy**
To start out, each migration group can have a policy. The default policy (if we want a default can be the `NoMigrationsPolicy`.
```python
{
"generic_metrics": NonBlockingMigrationsPolicy,
"replays": AllMigrationsPolicy,
}
```
so that when we look up a migration group we know what policy to apply. Down the road we could expand this to have different access groups (google groups for example) which would have their own definitions for the groups
```python
{
"generic_metrics": {
"default": NoMigrationsPolicy,
"team-sns": …
```
=> ref(migrations): Add MigrationPolicy

snuba/admin/views.py, tests/admin/clickhouse_migrations/test_api.py
Adds endpoints to run and reverse migration via snuba admin. 
endpoints:
`/migrations/<group>/<run,reverse>/<migration_id>`
Clients can pass in the force, and fake params via the query url e.g `/migrations/system/run/0001_migrations?force=true`
If a migration is not in `settings.ADMIN_ALLOWED_MIGRATION_GROUPS` returns error 400, otherwise runs and returns `"OK", 200` if successful.
=> feat(admin): run and reverse migrations

snuba/state/cache/redis/backend.py, snuba/utils/metrics/timer.py
We are having issues with occasionally spiking query times in snuba. We have evidence to believe that this is because of the readthrough cache but we don't know why exactly because its inner workings are not visible at runtime. This PR introduces metrics about the cache's operation such that they can be observed when another spike happens
=> feat(observability): Add measurements to readthrough cache

snuba/datasets/entities/profiles.py, snuba/datasets/processors/profiles_processor.py, snuba/datasets/storages/profiles.py, snuba/migrations/groups.py, snuba/snuba_migrations/profiles/0004_drop_profile_column.py, tests/datasets/test_profiles_processor.py
This was used to store profile data and has now been on GCS for a while. We don't need this column anymore.
=> ref(profiling): Drop profile column

snuba/state/rate_limit.py
`stale_queries` is not a number, because the pipeline didn't execute
yet. In datadog the metric does not exist. It would be easy to fix this
metric but I doubt its usefulness. We already have alerts on growing
redis memory usage that tell us when the rate limiter is misbehaving.
=> fix(metrics): Remove broken statsd metric for rate limiter

cloudbuild.yaml
.reporterrors file is deprecated, use `REPORT_SELF_HOSTED_ISSUES` flag instead
=> (fix)e2e: Add report self hosted issues flag as env variable

snuba/cli/devserver.py
Snuba transaction consumer was writing the wrong commit log topic in dev.
Subscriptions and post process would have been broken in dev.
=> fix(devserver): Fix snuba transaction consumer in dev

snuba/cli/__init__.py, snuba/environment.py
- Snuba's sampling rate is 0 and we don't ever start a transaction anywhere
- I introduced a transaction in #3200 which is populating the Datadog metric just fine but Snuba isn't sending the transaction so we basically still have no visibility
- This PR swaps out our hardcoded sampling rate with a function that sets sampling rate to 1 if the transaction op is `snuba_init` and the default 0 otherwise
- This works fine locally - could this break anything in prod? (There are no instances where we start a fresh transaction anywhere in Snuba so this is the first time we're adding one)
- Is it possible that some global transaction (coming from wherever the current Snuba transactions are started) could have the op name "snuba_init" and hence be sampled 100%?
- If so, would having the check be …
=> fix(logs): Snuba init transaction was not sampled

snuba/migrations/groups.py, snuba/migrations/operations.py, snuba/snuba_migrations/sessions/0004_sessions_ttl.py, tests/migrations/test_operations.py
The sessions tables does not have any retention configured. That means the table data would keep on growing forever. That is unnecessary since the product does not allow querying data older than 90 days. With this fix, data in the raw table is retained for 30 days and data in the rollup table is retained for 90 days. This should fix https://github.com/getsentry/snuba/issues/3191
Verified locally that both tables had the TTL configured after applying the migration
`
create table if not exists sessions_raw_local
(
session_id     UUID,
distinct_id    UUID,
quantity       UInt32 default 1,
seq            UInt64,
org_id         UInt64,
project_id     UInt64,
retention_days UInt16,
duration       UInt32,
status         UInt8,
errors         UInt16,
received       DateTime,
started …
=> fix(sessions): Limit data retention on sessions table

tests/admin/clickhouse_migrations/test_api.py
https://github.com/getsentry/snuba/pull/3223 introduced a new migration to the sessions table. But it seems like the migration api tests depend on the migrations on the sessions table to verify their operations. So we need to fix the test.
=> fix(tests): Fix migration tests api

snuba/cleanup.py, snuba/datasets/configuration/storage_builder.py, snuba/datasets/schemas/tables.py, snuba/datasets/storages/errors.py, snuba/datasets/storages/errors_v2.py, snuba/datasets/storages/transactions.py, snuba/datasets/storages/transactions_v2.py, snuba/optimize.py, snuba/util.py
The variable name was always referencing the partition, but the short form was a
little confusing because Clickhouse also has parts. Rename to partition to avoid
this problem in the future.
This came out of a discussion on a different PR: https://github.com/getsentry/snuba/pull/3274#discussion_r1002125829
=> fix: Rename part_storage to partition_storage

requirements.txt, tests/test_outcomes_api.py
Update sentry-relay version to 0.8.15 to get the `TRANSACTION_INDEXED` data category.
Note: 0.8.14 had a bug so it had to be yanked.
Add a smoke test to see if the data category is now available.
=> build: Bump relay to 0.8.15 [INGEST-1674]

snuba/redis.py, snuba/settings/__init__.py, snuba/settings/settings_test.py, snuba/state/cache/redis/backend.py, snuba/state/rate_limit.py, snuba/web/db_query.py, tests/conftest.py, tests/state/test_cache.py, tests/state/test_rate_limit.py
We want to split out those usecases to a new redis cluster, but instead
of doing a hard cutover to a new redis instance we want to do it slowly.
We don't care much about dataloss (particularly for those usecases), our
primary concern is whether the new Redis instance can take the load of
those usecases. We have little insight into what causes the most load on
the current redis cluster, and at the same time hope to get away with a
single memorystore instance per-usecase as memorystore does not support
sharding yet.
In order to facilitate a "slow" cutover we introduce two new rollout
rate settings. Increasing a rollout rate will make the corresponding
usecase gradually start a different redis cluster (represented as a new
"v2 usecase"), and once we hit 1.0 on both of them we can essentially …
=> feat(redis): Add second shard to rate limiter and cache

snuba/datasets/configuration/generic_metrics/storages/distributions_bucket.yaml, snuba/datasets/configuration/generic_metrics/storages/sets_bucket.yaml, snuba/datasets/configuration/json_schema.py, snuba/datasets/configuration/storage_builder.py, snuba/datasets/configuration/transactions/storages/transactions.yaml, tests/datasets/configuration/test_utils.py
Generic metrics and transactions don't have message processors that require any
init args in their classes, but there are other processors that do. This is
enabling that case for future datasets.
=> ref: Allow init args in configuration of DatasetMessageProcessor

Makefile, docker-compose.yml, snuba/settings/settings_test_distributed_migrations.py
* Fix the make file to use the `CLICKHOUSE_IMAGE` variable if it exists, otherwise set it to `yandex/clickhouse-server:20.3.9.70`; making it compatible with the CI dockerfile change #3292
* Fix a bug where migrations cluster was mistakenly set to single node and writing to the query node instead of cluster
=> Fix Makefile
