getsentry/snuba

Makefile, setup.py
This includes Armin's fix: https://github.com/mymarilyn/clickhouse-driver/pull/72
=> Bump clickhouse-driver to 0.0.18

snuba/api.py
Doing this so that we don't have to expect ClickHouse to be up before Snuba starts (for dev and test).
=> Move ensure_table_exists inside of the flask endpoints.

README.md
This is ignoring TSDB changes so far.
=> Add other Snuba related config changes

README.md
Goes along with https://github.com/getsentry/sentry/pull/12256
=> conf: Specify SENTRY_TSDB backend for Snuba

snuba/util.py
The expansion of so many columns can poison the uncompressed cache,
slowing down other small queries that benefit from it.
=> feat: Don't use uncompressed cache for queries with lots of cols

tests/base.py, tests/datasets/test_events.py, tests/test_api.py, tests/test_cleanup.py, tests/test_clickhouse.py, tests/test_consumer.py, tests/test_optimize.py, tests/test_perf.py, tests/test_processor.py, tests/test_replacer.py, tests/test_state.py, tests/test_util.py, tests/test_writer.py
Follow up to https://github.com/getsentry/snuba/pull/339
=> test: Parametrize util tests to run for every dataset

snuba/datasets/__init__.py, snuba/datasets/events.py, snuba/replacer.py
=> ref: Remove events specific methods from DataSet class

snuba/datasets/events_processor.py, snuba/datasets/transactions_processor.py, snuba/processor.py, tests/datasets/test_events_processor.py
Related to https://github.com/getsentry/sentry/pull/14727
=> fix: Only store valid ip addresses in clickhouse

snuba/datasets/discover.py
For a transaction this is an alias for the "transaction_name" field.
=> feat(discover): Add message as a common field in Discover

snuba/static/dashboard.html
- Update React to 16.10
- Wrap ReactTable in error handler
=> fix: The Dashboard

conftest.py, requirements.txt, setup.cfg
- update pytest deps (+xdist)
- bind default settings (test)
- fix pytest-xdist config
=> test: Improve test suite defaults

snuba/utils/streams/streaming.py
https://github.com/getsentry/snuba/pull/1269#discussion_r480386534
https://github.com/getsentry/snuba/pull/1282#discussion_r483293727
Mea culpa @fpacifici.
=> docs(streams): Improve documentation of `MessageBatch`

snuba/clickhouse/query_profiler.py, snuba/querylog/query_metadata.py, tests/clickhouse/test_query_profiler.py, tests/datasets/test_querylog_processor.py
Adding the list of all referenced columns to the query profile since the whole list of columns gives an idea of the amount of data we need to load to serve the query.
=> feat(query profile) Add the set of all referenced columns to the query profile

snuba/cli/replacer.py, snuba/cli/subscriptions.py, snuba/consumer.py, snuba/consumers/consumer_builder.py, snuba/consumers/snapshot_worker.py, snuba/datasets/cdc/message_filters.py, snuba/perf.py, snuba/replacer.py, snuba/subscriptions/consumer.py, snuba/subscriptions/worker.py, snuba/utils/streams/__init__.py, snuba/web/views.py, tests/datasets/test_errors_replacer.py, tests/datasets/test_groupassignee.py, tests/snapshots/test_snapshot_worker.py, tests/subscriptions/test_consumer.py, tests/subscriptions/test_worker.py, tests/test_consumer.py, tests/test_groupedmessage.py, tests/test_replacer.py
See https://github.com/getsentry/snuba/pull/1304#discussion_r485319745.
=> ref(streams): Expose commonly imported types from `snuba.utils.streams` module

snuba/datasets/storages/events_common.py, snuba/datasets/storages/transactions.py, snuba/query/processors/mapping_optimizer.py, tests/query/processors/test_mapping_optimizer.py
This has been running ok on the transactions table for a week.
=> perf(tags hashmap) Apply tags hashmap to the events table

snuba/query/processors/mapping_optimizer.py
This is rolled out in production. Let's invert the switch.
=> feat(tags hashmap) Keep it enabled by default.

snuba/utils/streams/streaming.py
The bulk of the time spent in `__check_for_results` is related to unnecessary synchronization:
```
Function                                                                  called...
ncalls  tottime  cumtime
/usr/src/snuba/snuba/utils/streams/streaming.py:348(__check_for_results)  ->       2    0.000    0.000  /usr/local/lib/python3.8/logging/__init__.py:1412(debug)
35391    0.040    1.918  /usr/local/lib/python3.8/multiprocessing/pool.py:764(get)
73792    0.037    0.840  /usr/src/snuba/snuba/utils/streams/streaming.py:183(__iter__)
73790    0.079    0.222  /usr/src/snuba/snuba/utils/streams/streaming.py:564(poll)
73790    0.036    0.503  /usr/src/snuba/snuba/utils/streams/streaming.py:579(submit)
2    0.000    0.000  {built-in method builtins.len}
4    0.000    0.000  {method 'append' of …
```
=> perf(streams): Improve performance of nonblocking batch result checks

snuba/clickhouse/columns.py, tests/test_clickhouse.py
Also removes unused ColumnSet.for_schema() method
=> ref(typing): Improve typing in snuba.clickhouse.columns

tests/base.py, tests/fixtures.py, tests/migrations/test_runner.py, tests/test_discover_api.py
Make it easier to get a valid raw error or transaction event in tests.
=> test: Add fixtures for getting raw errors and transactions

snuba/datasets/entities/groups.py, snuba/datasets/schemas/__init__.py, snuba/datasets/schemas/join.py, snuba/datasets/schemas/tables.py, snuba/datasets/storages/errors.py, snuba/datasets/storages/events_common.py, snuba/datasets/storages/groupedmessages.py, snuba/query/processors/mandatory_condition_applier.py, tests/query/processors/test_mandatory_condition_applier.py
=> feat(ast) Legacy query demolition step 9: Clean up mandatory conditions processor

snuba/datasets/entities/discover.py
It's useful to see this information in Sentry as well
=> feat: Send extra data to Sentry for impossible queries

tests/base.py
This removes the BaseEventsTest class which is now no longer used.
=> test: Remove BaseEventsTest

snuba/web/split.py
This removes some leftover dependencies on the legacy query from the query splitter.
=> feat(ast): Legacy query demolition part 10: Remove additional dependencies on the legacy query representation.

snuba/datasets/discover.py
Renames table -> entity where relevant.
Requires https://github.com/getsentry/snuba/pull/1407 and https://github.com/getsentry/snuba/pull/1417
=> ref(discover): Simplify entity selection methods

snuba/datasets/transactions_processor.py
This mirrors the behavior of the base event processor which [discards events that are beyond the retention period](https://github.com/getsentry/snuba/blob/ceb4ba1df08e00e69b032c74224bd1e72993e02b/snuba/datasets/events_processor_base.py#L152-L155 ) as indicated by the `EventTooOld` exception raised by [`enforce_retention`](https://github.com/getsentry/snuba/blob/ceb4ba1df08e00e69b032c74224bd1e72993e02b/snuba/datasets/events_format.py#L96-L99).
Fixes SNUBA-232.
=> fix(transactions): Discard events beyond retention period

snuba/datasets/cdc/groupassignee_entity.py, snuba/datasets/cdc/groupedmessage_entity.py, snuba/datasets/entities/discover.py, snuba/datasets/entities/errors.py, snuba/datasets/entities/events.py, snuba/datasets/entities/outcomes.py, snuba/datasets/entities/outcomes_raw.py, snuba/datasets/entities/sessions.py, snuba/datasets/entities/transactions.py, snuba/datasets/entity.py, snuba/query/data_source/join.py
Add the JoinRelationship class to be used to store the possible join
relationships an entity can have.
=> feat(entity join) Add JoinRelationship class to track joins in Entities

snuba/datasets/entities/errors.py, snuba/datasets/storages/errors_common.py
This matches the way we handle tags on the events entity.
=> feat(errors): Enable tag expansion and tags_hash_map optimization

snuba/datasets/storages/errors_common.py, snuba/datasets/storages/events_common.py, snuba/datasets/storages/group_id_column_processor.py, tests/query/processors/test_events_column_processor.py
Process the group_id column in errors the same way we do for events
=> feat(errors): Update group_id column processing to match events

tests/datasets/test_events_processor.py
We shouldn't test the events processor through the events dataset;
events processing is unrelated to the events dataset and it will stop
working once the events dataset is changed to use errors for querying.
=> test: Refactor events processor test to not reference events dataset

tests/utils/test_threaded_function_delegator.py
The callback tends to execute after the main thread has notified the condition the callback is supposed to wait on. Which means the wait times out. Replacing Condition with Event, which is the proper abstraction here and works properly in this case.
=> fix(snuplicator): Fix threaded delegator test

tests/datasets/test_discover.py
Since we are only really concerned with testing entity selection here,
we can just assert that the entity in the query is what we expect and
skip running the rest of the pipeline. The actual table name is subject
to change since we will be gradually migrating from the `sentry_local`
to `errors_local` and `discover_local` tables.
=> test: Simplify discover entity selection tests

snuba/query/processors/uuid_column_processor.py
Add a metric to count how often the query is transformed by the UUID processor.
=> fix(uuid) Add a metric for the UUID column processor

snuba/datasets/entities/discover.py
Map the actual Discover table column names to the column names used
in the public API.
=> feat(discover): Add column translations for the Discover storage

snuba/datasets/entities/discover.py, snuba/datasets/entities/errors.py
Add column mapping for geo_country_code, geo_region and geo_city for the
Errors and Discover entities.
=> feat: Add column mapping for geo fields

tests/pipeline/test_composite_planner.py
This test was completely broken but it was not failing because I misinterpreted how the `equals` method on the Query class works (meh).
This fixes the test issue, at least the code was ok and the issue was only with the test.
=> fix(composite queries) Fix composite query processing test

.craft.yml, .github/workflows/release.yml
A copy of getsentry/sentry#22657 with fixes included
=> ci(release): Move to getsentry/publish for releases

scripts/post-release.sh
Copy of getsentry/sentry#22693
=> ci(release): Fix post-release script

snuba/migrations/backfill_errors.py
Split the query to find the migration starting point into two since
`replaceAll(toString(event_id), '-', '')` when searching over all
events in the table can cause out of memory issues.
=> fix(backfill): Improve query to find the migration starting point

snuba/datasets/entities/discover.py
Convert referrer into tag rather than extra data so that we can filter
and group by this field using the Discover feature. This will make it easier
to analyze errors by referrer.
=> ref(logging): Tweak logging of Snuplicator results

snuba/datasets/entities/discover.py
Fix passing 'extras' via the Sentry sdk
=> fix(logging): Fix logging data to Sentry

snuba/datasets/entities/events.py
Add missing translation mappers for the `ip_address` and `transaction` columns.
These were present as raw columns in the events table, but need to be
adjusted in errors.
=> fix(errors): Fix ip_address and transaction translation

snuba/web/views.py
Add some metrics so we can track SnQL adoption and who is using it for what.
=> fix(snql) Add metrics to track adoption

requirements.txt, snuba/datasets/plans/single_storage.py
This addresses the type errors in single_storage.py. Updating mypy
in order to pull in a fix for generic inheritance in dataclasses.
=> ref(mypy): Update mypy

snuba/replacer.py
Fixes a bug in the post replacement optimize call. Would have
affected users who have REPLACER_IMMEDIATE_OPTIMIZE set to True.
This was discovered through type checking.
=> fix(replacer): Fix a bug in optimize call

snuba/subscriptions/data.py
Fixes implicit reexport type error
=> ref(mypy): Fix import of Language class

snuba/utils/codecs.py
Fixing the type error by deleting the JSON codec
=> ref: Remove JSONCodec

snuba/datasets/transactions_processor.py
A typing bug was causing mypy to ignore most of the transaction processor code,
so fixed that and fixed the subsequent typing issues that were exposed.
=> fix(typing) Fix typing issue in transaction processor

.github/workflows/ci.yml, .pre-commit-config.yaml, snuba/clickhouse/query_dsl/accessors.py, snuba/util.py, snuba/web/split.py
Add the unreachable flag to mypy so that we make sure there aren't code sections
that mypy is skipping.
There are a few errors fixed in https://github.com/getsentry/snuba/pull/1713 that need to be merged first for the CI to pass here.
=> fix(typing) Add unreachable flag to mypy

snuba/migrations/runner.py, snuba/query/parser/__init__.py, snuba/query/parser/validation/__init__.py, snuba/query/parser/validation/functions.py, snuba/query/snql/parser.py, tests/query/parser/validation/test_functions.py
Change the validators to handle composite queries, and then incorporate them
into the SnQL parser as well.
=> feat(validation) Update function validators for composite queries

snuba/datasets/transactions_processor.py
Add a metric for skipped transactions, with the missing field.
=> fix(processor) Add metric for skipped transactions

snuba/datasets/querylog_processor.py, tests/datasets/test_querylog_processor.py
The keys sometimes exist and have None values. Need to handle that case as well.
=> fix(querylog) Don't assume missing keys

snuba/datasets/entities/assign_reason.py
Add reason assignment for a couple more common referrers
=> feat(snuplicator): Improve reason assignment

tests/test_api.py
There were some weird edge cases that were failing when the errors storage was
being used. Update/delete the offending tests.
=> fix(tests) Fix some API tests that fail for errors

snuba/datasets/transactions_processor.py
This metric isn't being hit at all. If it does, we can add this back.
=> fix: remove hacky debugging code

.github/workflows/docs.yml, docs/source/conf.py, scripts/bump-version.sh
Adds a github action to publish the docs as github pages
=> feat(docs) Publish the Snuba docs as github pages

tests/datasets/test_events.py
Test uses errors storage instead of events; also fixes type issues
=> test: Refactor events dataset test

.isort.cfg, .pre-commit-config.yaml, Makefile, requirements.txt, tests/test_snql_api.py
This will require running `make setup-git` in order to get the right version of `pre-commit`.
=> feat(isort) Add isort pre commit hook

Dockerfile
The keyserver concept seems to be on the decline and the existing keyservers are quite slow and unreliable. We used to use a personally-owned keyserver proxy to alleviate for these issues but turns out we can simply rely on GitHub and a static signature with equal (or maybe more) reassurance.
=> ci: Bump gosu and move to static hash verification

snuba/datasets/entities/discover.py, snuba/datasets/entities/events.py, tests/test_replacer.py
Since we no longer need to run queries on both storages
at once, we can simplify storage selection on the events
and discover entities.
This also prevents failed healthchecks on unused storages.
Only the errors storage is checked if ERRORS_ROLLOUT_ALL is
set to true, otherwise only the events storage is checked.
=> ref: Simplify storage selection

requirements.txt
This fixes type issues with pytest decorators
=> test: Update pytest to 6.1.2

docs/source/index.rst
- checked build locally using `make snubadocs`
=> docs(migrations): Fixed TocTree Issue

snuba/datasets/entities/__init__.py, snuba/datasets/entities/factory.py, snuba/datasets/entities/metrics.py, snuba/datasets/metrics_processor.py, snuba/datasets/storages/__init__.py, snuba/datasets/storages/factory.py, snuba/datasets/storages/metrics.py, snuba/migrations/groups.py, snuba/migrations/snuba_migrations/metrics/0005_metrics_distributions_buckets.py, snuba/migrations/snuba_migrations/metrics/0006_metrics_distributions.py, tests/datasets/test_metrics_processing.py, tests/datasets/test_metrics_processor.py
Like #1908, adds distributions metrics tables.
It adds:
- the two migrations,
- the two storages
- the entity.
Valid query:
```
MATCH (metrics_distributions) 
SELECT 
percentiles, 
min, 
max,
avg, 
sum, 
count 
BY org_id, project_id, tags[10] 
WHERE 
timestamp >= toDateTime('2021-05-17 19:42:01') AND 
timestamp < toDateTime('2021-05-30 23:42:01') AND 
org_id = 1 AND 
project_id = 1
```
=> feat(metrics) Adds distributions entity in the development environment.

requirements.txt
=> ref(reqs) Use latest version of Sentry SDK

streaming_kafka_consumer/backends/kafka/configuration.py
https://github.com/getsentry/snuba/pull/1933 was really dumb. The
default configuration was not being properly applied since None was
being passed.
=> fix(consumer): Fix a bug causing default configuration to not be applied

requirements.txt
=> Revert "ref(reqs) Use latest version of Sentry SDK"

requirements.txt, snuba/environment.py
Add a tracing sampler since in the latest version tracing is disabled by default
=> ref(sdk) Update to latest Sentry SDK

snuba/migrations/snuba_migrations/events/0011_rebuild_errors.py, snuba/migrations/snuba_migrations/outcomes/0001_outcomes.py, tests/datasets/test_sessions_processing.py, tests/migrations/test_operations.py, tests/migrations/test_runner_individual.py, tests/query/processors/test_arrayjoin_optimizer.py
This PR contains the fixes and revisions for the remaining failure cases that were occurring in distributed testing mode (i.e. when `SNUBA_SETTINGS=test_distributed`). If these work as expected and are approved, then we can run this mode in CI.
=> feat(migrations): Final failure fixes for Distributed Testing Mode

snuba/datasets/errors_replacer.py, tests/datasets/test_errors_replacer.py, tests/test_replacer.py
=> ref: Refactor unmerge replacement to be class-based

snuba/web/views.py
Also remove some unneeded metrics to save a little bit of money.
=> ref(snql) Log all incoming queries

.github/workflows/ci.yml, snuba/web/views.py
This will run Sentry tests (e.g. `make test-snuba`) for every pull
request.
=> build(ci): Add sentry integration test

tests/conftest.py
This change ensures that the test database is re-created on each
test run on every node of a distributed cluster so that tests can
at least start running successfully (even if they do not all pass
yet).
=> test: Add ability to run tests on multi-node ClickHouse cluster

snuba/state/rate_limit.py
This PR attempts to explain more intuitively how the rate limiting function works with more context and examples. No code changes are here
=> Comment rate limit function

snuba/datasets/errors_replacer.py, snuba/datasets/events_processor_base.py, snuba/replacers/replacer_processor.py, tests/datasets/test_errors_replacer.py, tests/datasets/test_events_processor.py, tests/test_api.py, tests/test_replacer.py
Pulling Replacement type Enum refactor out of #2085 to reduce number of side changes for the PR
=> ReplacementType now in an Enum across Snuba

.freight.yml
Companion to https://github.com/getsentry/ops/pull/3966
Freight needs this to find and update image for the corresponding container.
=> build(freight): Add "events-subscriptions-scheduler" to Freight deployment

snuba/datasets/errors_replacer.py, snuba/datasets/storages/processors/replaced_groups.py
- `PostReplacementConsistencyEnforcer` is taking a long time (up to 400ms) when looking at performance for certain transactions.
- Possibly due to recent changes or maybe it's just Redis taking long?
- Added a bunch of spans to see how long the processor internals are taking to try and pinpoint the bottleneck.
- I've added spans where I think bottlenecks could be present, can add/remove if needed.
- Should these be added temporarily or just kept?
=> log(replaced_groups): Add sentry spans to PostReplacementConsistencyEnforcer

.github/workflows/ci.yml
Fixes the if condition on skipping docker publish step for forks.
=> fix(ci): Skip publish step for forks

Dockerfile
https://www.python.org/downloads/release/python-3812/
=> Bump python 3.8.12

docs/source/architecture/overview.rst
TIL about `make snubadocs` and that you can test it before you push 😮‍💨
=> Fix doc images not rendering

snuba/datasets/entities/transactions.py, snuba/datasets/storages/transactions.py
With the Float32 column in place, we want to redirect all reads from the old
column to the new column.
=> feat(suspect-spans): Read from 32 bit exclusive time column

snuba/subscriptions/scheduler_processing_strategy.py
Track the time spent encoding scheduled task messages for the load test.
This is intended to be temporary and removed once we are done optimizing
this function.
=> perf: Collect metric for time spent encoding scheduled task message

.freight.yml
Similar to https://github.com/getsentry/snuba/pull/2249
=> On Freight deploy, update k8s deployments containing `loadtest-*` containers

snuba/clickhouse/native.py
This message is confusing because there is nothing about this function which makes it have to be a write. In fact subscriptions use this function to read.
=> change confusing warning message

snuba/settings/validation.py
=> Revert "feat(subscriptions): Adds metrics topics to topics validation"

snuba/admin/notifications/slack/client.py, snuba/admin/views.py
A few improvements to admin notifications
- Updating an existing config now sends a notification
- Creating a new config now includes the old value in the nofication message
- Add Sentry logging for Slack client
=> feat(admin): Improve admin notifications

snuba/admin/clickhouse/system_queries.py, snuba/admin/views.py
Since the ClickHouse admin tool allows freeform SQL queries to system tables
we get a lot of noise in Sentry due to invalid columns or table names
being entered. This turns off error logging for those specific errors only.
=> fix(admin): Don't log invalid system table or column errors

snuba/query/processors/mapping_optimizer.py, tests/query/processors/test_mapping_optimizer_no_useless_conditions.py
This optimization has shown to be effective. Full report [here](https://www.notion.so/sentry/Removing-Redundant-Tag-Checks-From-Queries-7267cac97649414d9fee4b102d55c8a7)
This PR removes the experiment code and adds a tag to the transaction when the tags hashmap optimization is applied.
=> Roll out redundant tag optimization to all queries

docs/source/language/snql.rst
Add more description to the granularity clause. The content has been taken from the previous README.md
=> docs(granularity): Add more description

snuba/cli/cleanup.py, snuba/cli/optimize.py
Add the SDK to the jobs so we hopefully get more meaningful error messages.
=> fix(jobs) Add sentry SDK to the cleanup and optimize jobs

snuba/cli/subscriptions.py
The subscriptions consumer initializes the metrics wrapper too late so the synchronized consumer is not collecting its metrics.
Fixes this.
=> fix(metrics)  Initialize metrics in the right place 

snuba/utils/metrics/backends/abstract.py
Tried adding some clarification around some misunderstandings I had in another PR
=> docs(internal): Add some doc comments for MetricsBackend

snuba/admin/clickhouse/predefined_system_queries.py, snuba/admin/clickhouse/system_queries.py, snuba/admin/views.py
Pulls out the backend pieces from https://github.com/getsentry/snuba/pull/2374. 
Updated some of the queries as well to hopefully be more helpful re: @fpacifici's comments like https://github.com/getsentry/snuba/pull/2374#discussion_r799699351
=> ref(snuba-admin): Edit predefined queries

snuba/redis.py
We've seen tests increasingly fail in CI due to Redis not being ready yet.
This change increases the sleep duration exponentially between
each retry attempt starting with 500ms.
=> feat(ci): Wait longer between retries for Redis cluster on initialization

snuba/state/__init__.py
`set_config()` has multiple Redis calls that could be put in a pipeline to reduce network calls from 4 to 1.
=> fix(runtime config): Execute set_config() Redis calls in a pipeline

snuba/datasets/entities/clickhouse_upgrade.py, tests/datasets/entities/test_clickhouse_upgrade_callback.py
If any value was 0 in the comparison, the result would have been 0
=> fix(similarity) Fix comparison

snuba/datasets/entities/clickhouse_upgrade.py
Log some data about the results of the primary/secondary query at different rates depending on the similarity score.
=> feat(clickhouse_upgrade) Log some of the discrepancies

snuba/datasets/entities/clickhouse_upgrade.py
The extra data parameter is not called `extra_data` but `extra`
=> fix(parameter name)

snuba/query/processors/prewhere.py, tests/query/processors/test_prewhere.py
Like 
https://github.com/getsentry/snuba/pull/2453
But countIf has the same problem
=> fix(prewhere) remove from prewhere columns that appear in countIf as well

.freight.yml
Add the new tiger replacer consumer to freight deployments
=> fix(tiger-replacers): Add to freight deployments

tests/subscriptions/test_worker.py
This test often fails when run on GCP. Try waiting for the
future. Note the sleep is still required since the metric
gets incremented in the callback function that runs in a separate thread.
Also adds 3 retries.
=> test: Attempt to fix flaky test

snuba/admin/views.py
The list of configs is getting long and hard to scan. Let's sort them alphabetically.
=> feat(admin): Sort configs alphabetically

snuba/consumers/consumer.py
https://github.com/getsentry/snuba/pull/2514 Shows that the avg latency in a batch is a good enough approximation of what we use today as latency SLO. So removing the metric per message and relying on recording only one metric per batch which should have a positive performance impact
=> perf(consumer) Remove the latency metric per message

snuba/datasets/storages/metrics.py
Use the new storage created in https://github.com/getsentry/snuba/pull/2524
=> feat(metrics) use re-partitioned polymorphic metrics table as main storage

snuba/migrations/groups.py, snuba/migrations/snuba_migrations/metrics/0028_metrics_sets_aggregate_v2.py, snuba/migrations/snuba_migrations/metrics/0029_metrics_distributions_aggregate_v2.py
Create new metrics_sets and metrics_distributions tables with reasonable granularity and use_case_id column
Similar to #2539
=> feat(metrics): create sets_v2 and distributions_v2 aggregate tables

snuba/migrations/groups.py, snuba/migrations/snuba_migrations/metrics/0030_metrics_distributions_v2_writing_mv.py, snuba/migrations/snuba_migrations/metrics/0031_metrics_sets_v2_writing_mv.py
Same as https://github.com/getsentry/snuba/pull/2540 but for sets and distributions
=> feat(metrics) add migrations to write to v2 sets/distributions tables

snuba/datasets/storages/metrics.py, snuba/migrations/snuba_migrations/metrics/0030_metrics_distributions_v2_writing_mv.py, tests/test_metrics_api.py
Reverts getsentry/snuba#2560
This is causing test failures in sentry that show up in CI here but block deploys in getsentry/sentry
=> Revert "feat(metrics) - switch to v2 distributions aggregate table"

snuba/datasets/storages/metrics.py
Use the new sets table with a better-set index granularity
=> feat(metrics) switch to metrics_sets v2 aggregate table

snuba/datasets/entity.py, snuba/query/validation/validators.py, tests/test_snql_api.py
=> Revert "fix: Change column entity validator to WARN by default"

.freight.yml
=> OPS-1608: add events-subscriptions-verifier to freight config

snuba/pipeline/pipeline_delegator.py
=> Revert "fix(query): Avoid race in pipeline delegator"

snuba/subscriptions/verifier.py
Compare the whole subscription request as well as result in the verifier.
Also logs the requests to Sentry in the case of non matching result.
=> feat(subscriptions): Compare subscription request in verifier

snuba/subscriptions/executor_consumer.py
While in development, it was useful to be able to run a subset
of subscription queries for testing. This behavior is now removed
as this is not something we would ever want to do in prod.
=> feat(subscriptions): Turn off the ability to sample queries

tests/test_metrics_api.py
This is a hotfix for a test that is currently failing on master.
=> test: Fix test_dists_percentiles

snuba/datasets/entities/clickhouse_upgrade.py
Added score to the log message and parameter to logs to allow for more
data on the mismatches. Also added a referrer tag so that we can find
out mismatches specific to referrers.
=> chore(mismatch): Add more context to result mismatch

snuba/subscriptions/executor_consumer.py
This didn't make a difference, revert the test
This reverts commit 70b7d9d782991c05a7af0e6caaf69019f0dfa603.
=> Revert "fix(subscriptions): Flush producer on rebalance (#2648)"

snuba/settings/validation.py, snuba/utils/streams/topics.py
Not used yet, adding this as a first step to prevent validation issue
when adding the mapping to prod before https://github.com/getsentry/snuba/pull/2645/
gets merged.
=> feat: Add transactions topics

requirements.txt, snuba/state/stateful_count.py, tests/state/test_stateful_count_policy.py
- Updated Arroyo to 0.0.18
- Updated Snuba's Stateful Count DLQ Policy due to upgrade
- Updated tests for said policy
- Unblocks https://github.com/getsentry/snuba/pull/2573
=> Upgrade to Arroyo 0.0.18

.freight.yml
Reverts getsentry/snuba#2664
This didn't work, I dont know why tho so will look into it
=> Revert "ref(dev-tooling): Enable commit tracking"

.github/PULL_REQUEST_TEMPLATE.md
See https://github.com/getsentry/.github/pull/92.
=> Bring in CLA Lite

.freight.yml
Deploy new transactions scheduler and executor with Freight
=> feat(subscriptions): Deploy transactions scheduler and executor

.freight.yml
Kafka offsets are not present in production
=> chore(subscription): Remove metrics subscription executor

snuba/web/db_query.py
=> feat(debug): Add table rate limit metrics

snuba/cli/subscriptions_executor.py, snuba/cli/subscriptions_scheduler.py, snuba/cli/subscriptions_scheduler_executor.py
Sessions subscriptions are being removed. Prevent running this dataset via the
new scheduler and executor.
=> feat(subscriptions): Don't support running sessions subscriptions on new pipeline

.freight.yml
There are no more sessions subscriptions, this consumer will be removed
=> feat(subscriptions): Remove sessions subscriptions from Freight

snuba/datasets/storages/errors_v2.py
=> Revert "Split errors v2 from errors"

.github/dependabot.yml
Adds configuration for Dependabot to detect and submit PRs for dependencies.
=> ci(dependabot): configure dependabot

snuba/state/rate_limit.py
=> Revert "feat(rate-limit): Add rate limit metrics"

snuba/datasets/metrics_bucket_processor.py
- When I made temporary changes to Metrics processors for DLQ, I made `_process_values()` return an `Optional` mapping instead of just a `Mapping`
- Forgot to undo this when cleaning everything up
=> refactor(metrics): Undo Optional in value processors

snuba/migrations/snuba_migrations/generic_metrics/0002_sets_raw_table.py, snuba/migrations/snuba_migrations/generic_metrics/0003_sets_mv.py
=> Revert "make generic sets granularities configurable from raw table"

requirements.txt, snuba/consumers/consumer.py, snuba/subscriptions/combined_scheduler_executor.py, snuba/subscriptions/executor_consumer.py, snuba/subscriptions/scheduler_consumer.py, tests/subscriptions/test_combined_scheduler_executor.py, tests/test_consumer.py
Update arroyo to `0.2.0` and use `create_with_partitions` anywhere we are making our own strategy factory.
=> update arroyo to 0.2.0

requirements.txt, snuba/web/views.py, tests/consumers/test_mock_consumer.py
- Upgrade Arroyo for DLQ bug fixes
- DLQ would not catch errors on `join()`
- DLQ exception repr was way too long, just displaying a list of messages in their entirety
- Also introduces `create_with_partitions` in processing strategies
- https://github.com/getsentry/arroyo/pull/82
=> feat(dependencies): Update Arroyo to 0.2.2

snuba/datasets/entities/__init__.py, snuba/datasets/entities/factory.py, snuba/datasets/entities/generic_metrics.py, snuba/datasets/generic_metrics.py, tests/test_generic_metrics_api.py
1. creates the distributions entity for generic_metrics
2. some refactoring for shared logic of generic_metrics entities
3. e2e testing for the new entity
next steps:
1. getting rate limiters/granularity guard rails in place (should be mostly copy/paste from release health metrics)
2. fix the subscriptable mapper to work with tags (which has two value columns)
=> feat(mep): expose distributions entity, add e2e test

snuba/datasets/factory.py, snuba/datasets/replays.py
- adding here as I noticed its needed for the SnQL UI page, not sure there are any other ramifications I should know about.
=> feat(replays): add replays dataset to dataset factory

snuba/datasets/errors_replacer.py, tests/datasets/test_errors_replacer.py
Redo of https://github.com/getsentry/snuba/pull/2916.
This allows to bypass multiple projects, add proper logging and bypassess all replacements for a given project so we can preserve in order delivery
=> feat(replacements) Reimplement bypass properly

snuba/datasets/storages/generic_metrics.py
Created topics in https://github.com/getsentry/snuba/pull/2928, now let's use 'em
=> feat(mep): add commit log config to generic metrics storages

snuba/web/query.py
Even with the structured query fields, it can get truncated in spans. Use the same method that we do for SnQL queries to avoid this.
=> fix: Prevent db span from truncating query

snuba/cli/subscriptions_scheduler.py
This is needed to deploy subscriptions/alerting for MEP
=> feat(mep): add generic_metrics_distributions, generic_metrics_sets to subscripton-scheduler

snuba/datasets/storages/replays.py, snuba/migrations/groups.py, snuba/migrations/snuba_migrations/replays/0002_add_url.py, snuba/migrations/snuba_migrations/replays/0002_add_urls.py
-- start migrations
-- migration replays : 0002_add_url
Local operations:
ALTER TABLE replays_local ADD COLUMN IF NOT EXISTS url String AFTER title;
Dist operations:
ALTER TABLE replays_dist ADD COLUMN IF NOT EXISTS url String AFTER title;
-- end migration replays : 0002_add_url
=> Add urls column to replays dataset

snuba/cli/subscriptions_executor.py
=> feat(mep): add support for generic-metrics dataset subscription executors

tests/query/processors/test_arrayjoin_optimizer.py
I need to make a change to ArrayJoinKeyValueOptimizer to support two value columns. To make that cleaner, I figured I would start by reorganizing this test file based on a "HACK" comment left by @evanh
=> ref: re-organize ArrayJoinKeyValueOptimizer tests

snuba/datasets/entities/profiles.py, snuba/datasets/profiles_processor.py, snuba/datasets/storages/profiles.py, tests/datasets/test_profiles_processor.py
This PR depends on the successful deployment of #2983
=> Read and write architecture data from and to profiles_local table

snuba/admin/clickhouse/system_queries.py
Once a migration has been run in production I would like to have an
easy way to find out if the schema has been applied correctly across
all nodes of the cluster. Being able to do so via the admin tool
allows me not to ssh into each individual machine.
The describe table is pretty non-intrusive and just shows the schema
of the table. Hence no custom validation is needed. More information
about the command can be found here https://clickhouse.com/docs/en/sql-reference/statements/describe-table
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my …
=> feat(admin): Allow describe table command

snuba/settings/__init__.py
=> Add kafka ssl authentication params to snuba

snuba/subscriptions/entity_subscription.py
Set up configuration
re: sentry issue https://sentry.io/organizations/sentry/issues/3459769919/?project=300688&query=is%3Aunresolved
=> config(mep): add configs for generic metrics subscriptions

snuba/datasets/replays_processor.py, snuba/datasets/storages/replays.py, snuba/migrations/groups.py, snuba/migrations/snuba_migrations/replays/0004_add_error_ids_column.py, tests/datasets/test_replays_processor.py
- add error ids UUID Array column for storing error ids associated with a replay.
=> feat(replays): add error_ids column

snuba/datasets/replays_processor.py, tests/datasets/test_replays_processor.py
The url column exists therefore we should process urls.
=> feat(replays): Enable URL processing in the consumer

requirements.txt, tests/datasets/configuration/test_generic_metrics.py
- Added basic structure for the directories containing dataset-as-a-config yamls
=> feat(datasets): Add configs directory structure

snuba/datasets/entities/replays.py
https://sentry.io/organizations/sentry/issues/3125718316/?referrer=slack
Thanks Evan!
=> bug(replays): Generate abstract_column_set from replays schema

snuba/cli/admin.py
We only enabled it in debug mode LMAO
=> fix(admin): initialize admin logging in prod

snuba/cli/multistorage_consumer.py
This brings the `multistorage-consumer` options closer to the `consumer` options. These two comamnds should eventually be combined anyway, so this is a step in that direction.
The primary motivation for making this change now though is that we are rolling out errors/transactions split together with the transactions/transactions_v2 double writes. This requires us to pass non default topic and Kafka cluster options to one of the multistorage consumers.
=> feat(multistorage-consumer): Add --raw-events-topic and --bootstrap-server options

tests/conftest.py
Currently, the test teardown doesn't run if there's an error in the runner in setup. This means the cleanup is not run and all subsequent tests don't start from a clean state. Having `finally:` ensures that the test cleanup is always performed.
=> fix(tests): cleanup tests even if setup fails

.freight.yml
This will run in parallel with the old one until all projects are migrated to the new consumer
=> feat: Add new transactions consumer to Freight

.github/codeql/codeql-config.yml, .github/workflows/codeql-analysis.yml
Sets up the default CodeQL configuration.
CodeQL scans will happen weekly at 3:30AM UTC on Fridays. Test directories are ignored.
=> security(scanning): Configure CodeQL

snuba/datasets/configuration/entity_builder.py, snuba/datasets/configuration/entity_subscription_builder.py, snuba/datasets/storages/factory.py
=> feat: Remove logging about config built entities and storages

snuba/datasets/entities/discover.py, snuba/datasets/entities/transactions.py, snuba/datasets/transactions_processor.py, tests/datasets/test_transaction_processor.py, tests/fixtures.py, tests/test_snql_api.py
This reverts commit a5ab0bdbbdd3b2c258f4ebb8691ce45b63090982.
Caused transactions consumer to crashloop
=> Revert "feat(transactions): app_start_type reading/writing (#3127)"

snuba/utils/registered_class.py, tests/utils/test_import_submodules.py, tests/utils/test_package_auto_import/garbage, tests/utils/test_package_no_import/garbage
=> fix(MDC): make auto importing resilient to non-python files in the directory

.freight.stable.yml, .freight.yml
Remove the replacer and cdc consumers which are no longer needed
=> ci(consumers): Remove unused consumers

snuba/datasets/storages/replays.py, snuba/migrations/groups.py, snuba/snuba_migrations/replays/0006_add_is_archived_column.py
- Adds new is_archived column.
=> feat(replays): Add is_archived column and migration

snuba/state/cache/abstract.py, snuba/state/cache/redis/backend.py, snuba/web/db_query.py, tests/state/test_cache.py
Remove the TigerTimeoutException since we are not serving dual read queries anymore
=> ref(api): Revert TigerTimeoutException

requirements.txt
Upgrade arroyo library to get latest fixes
=> Upgrade arroyo to latest

requirements-test.txt, requirements.txt, snuba/admin/auth.py, snuba/admin/jwt.py, snuba/admin/user.py
Use the actual JWT from google to validate user ID and e-mail
Next steps would be to extract roles and potentially permissions from IAM based on the user ID (https://cloud.google.com/resource-manager/reference/rest/v1/projects/getIamPolicy?apix_params=%7B%22resource%22%3A%22search-and-storage%22%2C%22body_resource%22%3A%7B%7D%7D)
=> feat(admin): use JWT to validate user ID and e-mail

snuba/datasets/configuration/entity_builder.py, snuba/datasets/configuration/json_schema.py, snuba/datasets/configuration/transactions/entities/transactions.yaml, snuba/datasets/configuration/utils.py, snuba/datasets/pluggable_entity.py, tests/datasets/configuration/test_entity_loader.py
- Transactions entity config'd
- Extended `test_entity_loader.py` with Transactions entity
- Modified json schema as needed
=> feat(TDC): Transactions Entity Config

snuba/datasets/configuration/dataset_builder.py, snuba/datasets/configuration/generic_metrics/dataset.yaml, snuba/datasets/configuration/json_schema.py, snuba/datasets/configuration/transactions/dataset.yaml, tests/datasets/configuration/test_dataset_loader.py
This PR is the same as https://github.com/getsentry/snuba/pull/3277
=> feat(TDC): Create transactions dataset config file

requirements.txt, snuba/admin/clickhouse/common.py, snuba/admin/clickhouse/querylog.py, snuba/admin/notifications/querylog/audit_log.py, snuba/admin/views.py, tests/admin/clickhouse/test_query_validation.py, tests/admin/test_api.py, tests/admin/test_audit_log.py
This is the first of a few PRs which will enable ClickHouse Querylog table to be queryable from Snuba Admin console. This PR sets up the backend endpoints which will be requested by the front end.
The audit log solution is fairly simple - any query that is attempted to be executed against the querylog table (aside from describing the table) is logged to GCP via a new logger using structlog. Each log contains the `user`, `query`, `status` (failed/succeeded), and start/end timestamps. (See sample log below)
- Snuba Admin API - added 2 new endpoints which are locked behind a runtime config.
- No access to ClickHouse Querylog table except via SSH
- Only accessible to those with SSH access to production ClickHouse
- A new admin API endpoint introduced to view the Schema of the Querylog table
- …
=> feat(querylog): Expose ClickHouse Querylog to Snuba Admin API

snuba/cli/consumer.py, snuba/consumers/consumer_builder.py
This reverts the change mentioned above
=> Revert "fix(consumer): Remove shared producers in consumer (#3305)"

snuba/optimize.py, snuba/optimize_tracker.py, snuba/settings/__init__.py, snuba/util.py, tests/test_optimize.py, tests/test_optimize_tracker.py
Reverts getsentry/snuba#3158
The pr above prevented us from running concurrent merges on October 28
=> Revert "feat(optimize): track merge state"

.github/workflows/ci.yml, .github/workflows/ddl-changes.yml, .github/workflows/docs-pr.yml, .github/workflows/docs.yml
=> ref: upgrade actions/setup-python to avoid set-output deprecation

snuba/clusters/cluster.py
Fix comment length. The intent of this PR is to test fast reverts in snuba repository.
=> ref(docs): Fix comment length

requirements.txt
Needs https://github.com/getsentry/pypi/pull/118
=> feat: Arroyo 1.1.0

snuba/datasets/processors/replays_processor.py
SNUBA-2Z9
Force the release to be a string.
=> fix(profiles) It seems we are writing a non string release. Rejected by Clickhouse 

.github/workflows/ci.yml, Makefile, snuba/cli/__init__.py, snuba/cli/devserver.py, snuba/core/initialize.py, snuba/datasets/factory.py, test_initialization/test_initialize.py
Compiling changes in #3311 and #3326 and moving the initialization up  before subcommand compilation
The deploy of #3326 caused a crashloop on `snuba-generic-metrics-distributions-subscriptions-scheduler-production`and `snuba-generic-metrics-distributions-subscriptions-scheduler-production` (and only those two)
This happened because:
1. generic_metrics entities are defined in config
2. the subscriptions scheduler cli has the entity argument defined like so:
```
@click.option(
"--entity",
"entity_name",
required=True,
type=click.Choice([entity_key.value for entity_key in EntityKey]),
help="The entity to target",
)
```
This makes the cli depend on the entity key being fully populated *at import time*. This also makes it so that the code as is only work *by accident*. 
We move up …
=> Explicitly initialize snuba take 3

snuba/admin/migrations_policies.py
Pulling out the logic of getting the migration group polices so that I can use it later in https://github.com/getsentry/snuba/pull/3358.
=> ref(admin): get_migration_group_policies

snuba/migrations/migration.py
Noticed that in https://github.com/getsentry/snuba/pull/3353 the output for all the migrations in the PR comment is the local before the distributed operations. With the changes made in https://github.com/getsentry/snuba/pull/3324/files we should display the dry run in the same order that it will be run/reversed.
=> ref(migrations): Dry run prints out correct order

.github/workflows/ci.yml
This was failing e.g. https://github.com/getsentry/snuba/actions/runs/3492761457/jobs/5846880760
=> Use docker_repo instead of container_repo

snuba/admin/static/clickhouse_migrations/index.tsx
* Remove unused code on the migration UI. 
* Fix UI bug where sql text wasn't cleared on change.
=> fix(admin): remove unused code and clear sql text on change

.gitattributes
=> ref: mark a file as binary so `git grep` is more useful

snuba/datasets/processors/querylog_processor.py, tests/datasets/test_querylog_processor.py
=> Revert "fix(api-abuse): Add duration_ms to individual queries in querylog"

snuba/datasets/configuration/replays/storages/replays.yaml, snuba/migrations/groups.py, snuba/snuba_migrations/replays/0007_add_replay_type_column.py
closes: https://github.com/getsentry/replay-backend/issues/210
@evanh Are enums unsupported?  Yaml validation throws.
=> feat(replays): Add replay_type column

snuba/datasets/configuration/replays/storages/replays.yaml, snuba/datasets/processors/replays_processor.py, snuba/datasets/storages/replays.py, tests/datasets/test_replays_processor.py
closes: https://github.com/getsentry/replay-backend/issues/210
=> feat(replays): Add replay_type column processing

snuba/query/processors/physical/null_column_caster.py
Accidentally merged before fixing this
=> fix comment in NullColumnCaster docstring

snuba/datasets/configuration/issues/entities/search_issues.yaml, snuba/datasets/processors/search_issues_processor.py, tests/datasets/test_search_issues_processor.py, tests/test_search_issues_api.py
Populate `client_timestamp` column with the value from `event.datetime`. Map timestamp -> client_timestamp.
=> fix(search_issues): parse out client_timestamp and map timestamp -> client_timestamp column

.github/workflows/fast-revert.yml
token is configured in `getsentry-bot` account
=> ref: enable fast-revert in snuba

tests/clickhouse/test_native.py
=> ref: fix a typo

snuba/cli/replacer.py, snuba/replacer.py
These are lies, replacer is not doing any batching anymore
=> feat(replacer): Remove max batch size and max batch time CLI args

requirements.txt
This is required for https://github.com/getsentry/snuba/pull/3553
=> feat: Arroyo 2.3.1

snuba/migrations/groups.py, snuba/snuba_migrations/search_issues/0003_search_issues_modify_occurrence_type_id_size.py
Turns out UInt8 isn't large enough for our purposes. This PR adds a migration to increase the column size to UInt16.
=> feat(issue-platform): increase occurrence_type_id column size from UInt8 to UInt16

codecov.yml
Tested for validity with
```
cat codecov.yml | curl --data-binary @- https://codecov.io/validate
```
=> fixcodecov): add settings for codecov

snuba/cli/subscriptions_scheduler_executor.py, snuba/subscriptions/combined_scheduler_executor.py
Remove the ability to override the scheduling mode on the combined scheduler/executor. This hack previously existed for single tenant's `transactions` topic. Since the topic was semantically partitioned but the mode was global, empty partitions would cause the entire pipeline to stop on a regular basis.
This combination (semantic partitioning with subscriptions in global mode) no longer exists so this is not needed.
=> feat: Remove ability to override scheduling mode

snuba/subscriptions/combined_scheduler_executor.py
This is checked https://github.com/getsentry/snuba/blob/e50b6ab0b02af07bba348e56f611794aa363954f/snuba/subscriptions/combined_scheduler_executor.py#L78-L79 so we know it is the same.
=> ref: Remove invalid TODO

snuba/migrations/groups.py, snuba/snuba_migrations/transactions/0018_transactions_add_profile_id.py
This adds a new profile id column to the transactions table as per https://github.com/getsentry/rfcs/blob/main/text/0047-introduce-profile-context.md
=> feat(profiling): Add profile id to transactions table

Dockerfile
=> ref: remove yarn apt list after installation

snuba/datasets/configuration/events/entities/events.yaml, snuba/datasets/configuration/transactions/entities/transactions.yaml, snuba/datasets/entities/transactions.py, tests/datasets/configuration/test_entity_loader.py
Events entity generated with the [entity conversion script](https://github.com/getsentry/snuba/tree/python_2_yaml_entity_converter)
* Added test functionality to compare translation mappers
* Added test to verify join relationships
* added test to verify subscription validators
* The transactions entity was actually out of sync so I fixed it
=> feat(DC): create events entity, expand testing, fix transactions yaml

snuba/datasets/configuration/profiles/entities/profiles.yaml, tests/datasets/configuration/test_entity_loader.py
This PR is responsible for creating the profiles entity yaml file using the [python_2_yaml conversion script](https://github.com/getsentry/snuba/blob/python_2_yaml_entity_converter/scripts/pyentity_2_yaml.py).
=> ref(config) Create Profiles Entity yaml file

snuba/datasets/configuration/replays/entities/replays.yaml, tests/datasets/configuration/test_entity_loader.py
This PR is responsible for creating the replays entity yaml file using the [python_2_yaml conversion script](https://github.com/getsentry/snuba/blob/python_2_yaml_entity_converter/scripts/pyentity_2_yaml.py).
=> ref(config): Create Replays Entity yaml file 

snuba/admin/auth_roles.py, snuba/admin/clickhouse/migration_checks.py, snuba/admin/migrations_policies.py, snuba/admin/views.py, snuba/migrations/policies.py, tests/admin/clickhouse_migrations/test_api.py, tests/admin/clickhouse_migrations/test_migration_checks.py, tests/admin/test_migration_policies.py
Can be used after https://github.com/getsentry/snuba/pull/3606 is merged (still will have to rebase and update some code/tests)
=> ref(migrations): use roles to get group policies

.github/workflows/ci.yml
cc @asottile-sentry
This pulls in https://github.com/getsentry/action-self-hosted-e2e-tests/commit/627c9b5
=> ci: Update self-hosted e2e action to bring in fix for race condition in tests

snuba/datasets/configuration/transactions/entities/transactions.yaml, snuba/datasets/configuration/transactions/storages/transactions.yaml, snuba/datasets/processors/transactions_processor.py, snuba/datasets/storages/transactions_common.py, tests/datasets/test_transaction_processor.py
Process the profile context on transactions and extract the profile id.
=> feat(profiling): Process profile context on transactions

.pre-commit-config.yaml
https://github.com/python-poetry/poetry-core/pull/542
=> ref: upgrade isort to work around poetry breakage

docs/source/clickhouse/schema_design.rst
@fpacifici added some comments on the original PR, so I geared this more into a discussion of why tag indexes can fail on certain kinds of queries
=> docs(schema): update tag promotion doc to talk about bloom filters

snuba/cli/subscriptions_scheduler_executor.py
=> feat(self-hosted): Allow running sessions subscriptions in self hosted

snuba/cli/consumer.py, snuba/consumers/consumer_builder.py, tests/consumers/test_consumer_builder.py
=> Revert "fix(consumer): Separate out the shared producers in consumer"

snuba/admin/auth_roles.py
This https://github.com/getsentry/snuba/pull/3692 added the non blocking role but it needs the non blocking action
=> fix(migrations): Use ExecuteNonBlockingAction action

snuba/cli/multistorage_consumer.py
We are breaking down https://github.com/getsentry/snuba/pull/3707 into smaller, incremental PRs. This way, we can understand and finalize each incremental change faster and with more confidence. 
This PR pulls out the existing code for building the multistorage streaming strategy factory into its function. Ultimately, this would be called from the consumer_builder.
=> ref(consumer): Build strategy factory function in multistorage consumer

snuba/cli/multistorage_consumer.py
--commit-log-topic is an optional string
=> fix: Fix typing of multistorage consumer

snuba/admin/clickhouse/common.py, snuba/clusters/cluster.py
Fix a bug where we didn't recognize dist nodes as valid.
=> fix(admin): allow querying dist nodes too

docs/source/getstarted.rst, docs/source/query/overview.rst, snuba/admin/README.md, snuba/admin/views.py, snuba/cli/migrations.py, snuba/settings/__init__.py, snuba/settings/settings_distributed.py, snuba/settings/settings_docker.py, snuba/settings/settings_test.py, tests/clickhouse/optimize/test_optimize_tracker.py, tests/clusters/test_cluster.py, tests/datasets/test_replays_processor.py, tests/fixtures.py, tests/migrations/test_runner_add_node.py, tests/test_split.py, tests/web/test_cache_partitions.py
sometimes the name `localhost` force-resolves to ipv6
=> ref: force ipv4 localhost

snuba/clusters/cluster.py
change admin log error to warn to stop triggering alerts.
=> change admin log error to warn

snuba/admin/static/clickhouse_migrations/index.tsx
fix ui bug where we dont properly refresh table after running
=> fix(admin): UI fixes

snuba/snuba_migrations/search_issues/0002_search_issues_add_tags_hash_map.py, snuba/snuba_migrations/search_issues/0003_search_issues_modify_occurrence_type_id_size.py
These migrations should be non-blocking.
=> fix(search_issues): change migrations to non-blocking

snuba/consumers/consumer.py
There is no reason for InsertBatchWriter or ReplacementBatchWriter to subclass ProcessingStrategy from Arroyo - they have nothing to do with processing strategies. Also removes unnecessary calls to poll() method which did nothing but was required by ProcessingStrategy.
=> ref: InsertBatchWriter and ReplacementBatchWriter aren't processing strategies

snuba/datasets/configuration/issues/storages/search_issues.yaml, snuba/settings/validation.py, snuba/utils/streams/topics.py
We're need this to get post_process_forwarder going. The topic in prod is currently being created.
=> feat(issue-platform): add commit log topic when processing search_issue events

Dockerfile, snuba/cli/devserver.py
Will also open a PR for exposing this port by default in sentry
devservices
=> feat: Expose Snuba Admin via devserver

snuba/settings/validation.py
All consumers are crash looping due to validation error
=> Add `snuba-generic-events-commit-log`

snuba/consumers/consumer.py, snuba/consumers/schema_files/event.json, snuba/consumers/schema_files/generic_metrics.json, snuba/consumers/schemas.py, tests/consumers/test_schemas.py
- fix eventstream schema based on single message
- add generic_metrics schema
- add extra context data for the to-be-validated message
=> fix: Update some kafka topic schemas, add more instrumentation

snuba/datasets/configuration/generic_metrics/entities/org_counters.yaml, snuba/datasets/configuration/generic_metrics/storages/org_counters.yaml, tests/test_generic_metrics_api.py
This PR adds mappings for accessing tags in organisation generic counters
=> Add tags mapping to organisation generic counters

snuba/datasets/configuration/sessions/storages/raw.yaml, snuba/utils/streams/topics.py
@lynnagara Hi 
https://github.com/getsentry/snuba/pull/3697  did not fully restore the sessions subscription, try to fix it  #3696
=> fix(subscriptions): Fix sessions subscriptions issue #3696

requirements.txt, snuba/consumers/consumer.py, snuba/consumers/strategy_factory.py, snuba/replacer.py
Apply changes required for https://github.com/getsentry/arroyo/pull/177
=> ref: Update to arroyo 2.7.0

.vscode/settings.json, snuba/migrations/groups.py, snuba/snuba_migrations/events/0020_add_main_thread_column.py
=> Add exception_main_thread to Snuba

tests/migrations/test_runner.py
In order for migrations to run in an automated pipeline, the reverse function must be idempotent. This is because Snuba doesn’t not keep per node state; it is either all or nothing. In the case that a failure occurs, a pipeline may call reverse several times on the same node until it is sure that all nodes have reversed the migration. Running reverse must be idempotent and must not have unintended side effects.
This test runs reverse on migrations multiple times and checks the clickhouse create table query statements to check that DDL are not changed on multiple runs.
=> migrations : add test to check that reverse has no side effects

requirements-test.txt, snuba/admin/auth_roles.py, snuba/admin/views.py
Our version of mypy has no support for generic namedtuples, and I would
like to use them.
=> ref: Update mypy to 1.1.1

snuba/settings/__init__.py
Once https://github.com/getsentry/ops/pull/6266 is merged running migrations through the admin tooling for these migration groups
=> ref(admin) enable events/transactions migration groups

snuba/web/query.py
Found while figuring out this code, it's not used anymore
=> chore(db_query): remove dead code from web/query

snuba/snuba_migrations/events/0014_backfill_errors.py
There's a bug where `0014_backfill_errors.py` doesn't properly work in multi-node setups. This is because it always tries to query the dist tables from the query. However, there are some setups where we don't place the dist tables on the query node. This fixes it to find a dist node to query in the mult-node setup.
=> fix(migrations): use correct connection for multi-node clusters

requirements.txt, snuba/datasets/processors/querylog_processor.py, snuba/querylog/query_metadata.py, snuba/subscriptions/data.py
Retrying #3857 with fixed subscriptions executor Org ID placeholder
=> feat(Querylog): Organization ID from `tenant_ids` again

snuba/cli/rust_consumer.py
So Rust consumer can import the Python module
=> feat(rust-consumer): Add python processor info to consumer config

requirements.txt
Relates to https://github.com/getsentry/sentry-kafka-schemas/pull/45
=> ref: Bump sentry-kafka-schemas 0.0.9

snuba/cli/rust_consumer.py
Better to give each config a unique path
=> feat(rust-consumer): Avoid config files overwriting each other

Dockerfile
Some local development workflows are getting messed up because the
from-scratch build takes too long.
One now can use `docker build --build-arg SHOULD_BUILD_RUST=false .`
=> fix(docker): Add argument to skip rust consumer building in Snuba

snuba/migrations/connect.py
Another follow up to #3887 
Discover doesn't have dist/local nodes so it was breaking the the check and blocked migrations.
=> fix(migrations): skip checking local/dist nodes for discover cause it doesn't have them

snuba/admin/clickhouse/common.py
Missed one reference of `get_local_nodes` in snuba admin. Should have been captured in https://github.com/getsentry/snuba/pull/3887.
=> fix(admin): Avoid get_local and get_dist nodes for discover in admin [part 2]

snuba/web/views.py, tests/test_api.py
We have Snuba admin for this now
=> ref: Remove legacy dashboard

snuba/state/sliding_windows.py, tests/state/test_sliding_windows.py
- Ported sliding windows rate limiter from [Sentry](https://github.com/getsentry/sentry/blob/master/src/sentry/ratelimits/sliding_windows.py)
- This will be a useful tool for rate limiting implementations in Allocation Policies
=> feat(CapMan): Sliding Windows Rate Limiter

requirements.txt
Update `outcomes` schema by bumping `sentry-kafka-schemas` version
=> fix(outcome): Update outcome schema

snuba/migrations/connect.py
Fix a typo where some nodes were not listed across storages
=> show all inactive nodes

requirements.txt
This pull in the transactions schema so we can begin validation on that topic
=> feat: sentry-kafka-schemas 0.0.21

snuba/replacers/errors_replacer.py, tests/datasets/test_errors_replacer.py
Also improve typing around _build_event_set_filter
Previously: https://github.com/getsentry/snuba/pull/1968
why now again? well, because I left the job half-finished and it really bugged me when I tried to add types from sentry-kafka-schemas
=> ref: Refactor replace_group to class-based types

snuba/admin/iam_policy/iam_policy.json
Grant access to the SnQL to SQL tool to the replays devs to test our tool
permissioning.
=> ref(admin) Test SnQL to SQL access with replays devs

snuba/datasets/configuration/json_schema.py, snuba/datasets/configuration/storage_builder.py, snuba/datasets/storage.py, tests/datasets/configuration/test_storage_loader.py
- Allocation policies live on Storages, which are configurable
- Allocation policies should be configurable
- Added ability to define allocation policy + args in a storage config
=> feat(CapMan): Allocation Policy Configurable

snuba/cli/migrations.py, snuba/migrations/groups.py, snuba/migrations/runner.py, tests/migrations/test_runner.py
Adds filtering by readiness state to the migrations cli
=> fix(migrations): add filtering by readiness on run all

gocd/pipelines/snuba-sns-test.yaml, gocd/pipelines/snuba-stable.yaml, gocd/pipelines/snuba.yaml
=> Update to new k8s deploy script

snuba/replacers/errors_replacer.py, tests/datasets/test_errors_replacer.py
Previously: https://github.com/getsentry/snuba/pull/3957
=> ref: Make delete_groups replacement class-based

snuba/datasets/configuration/querylog/storages/querylog.yaml, snuba/settings/validation.py, snuba/utils/streams/topics.py
This should not be merged until the topic exists and is configured in settings in prod
=> feat: DLQ for querylog

gocd/pipelines/snuba.yaml, scripts/fetch_service_refs.py
The GOCD access token was missing in my last attempt #4013 . This should work now.
=> fix(CI): add migrations check to main pipeline (attempt 2)

snuba/settings/validation.py
Remove deprecated snubs-replays-events topic from validation script
=> remove: Deprecate snuba-replay-events

gocd/pipelines/snuba.yaml
Depends on consumer being deployed to prod first
=> build: Deploy rust consumer with gocd

snuba/admin/auth_roles.py, snuba/admin/iam_policy/iam_policy.json, snuba/admin/tool_policies.py
Add a new role that gives access to the Tracing tool in the admin. Replays is
doing a lot of experimentation on that right now and it would help them.
=> ref(admin) Add a Tracing role to let replays access that tool

rust_snuba/rust_arroyo/src/backends/kafka/mod.rs
I think this test was flaky because it used the same topic as the test that preceded it. Seems to do a lot better with a different name.
=> test: Fix flaky Rust consumer tests

gocd/pipelines/snuba-stable.yaml, gocd/pipelines/snuba.yaml
This was a mistake on my part during the canary addition
=> Switch to k8s-deploy script

rust_snuba/Cargo.lock, rust_snuba/Cargo.toml, rust_snuba/src/config.rs, rust_snuba/src/consumer.rs, rust_snuba/src/lib.rs, snuba/cli/rust_consumer.py
=> feat(rust): add sentry dsn

rust_snuba/rust_arroyo/src/processing/strategies/commit_offsets.rs, rust_snuba/rust_arroyo/src/processing/strategies/mod.rs, rust_snuba/rust_arroyo/src/processing/strategies/reduce.rs
Currently the consumer does not do any batching, add a reduce strategy to help with this.
=> feat(rust-arroyo): Reduce strategy

gocd/pipelines/snuba-stable.yaml, gocd/pipelines/snuba.yaml
=> No delay for canary

scripts/check-migrations.py
=> [Do not merge] check-migrations.py

gocd/pipelines/snuba-sns-test.yaml, gocd/pipelines/snuba.yaml
Added the spans consumer to be deployed via goCD
=> ci(spans): Deploy spans consumer via gocd

snuba/admin/dist/index.html, snuba/admin/static/data.tsx, snuba/admin/static/dead_letter_queue/index.tsx
UI mockup of how DLQ interface could look.
Though it's not yet functional and there's no API endpoint, I'd like to merge this as-is rather than build everything in one hit.
=> feat(dlq): DLQ design for Snuba admin

snuba/admin/iam_policy/iam_policy.json
We will ultimately be able to do this using google auth but for now add users
that need more performance info.
=> ref(admin): Give more users access to the admin tool

snuba/query/allocation_policies/bytes_scanned_window_policy.py
trying this again given that https://github.com/getsentry/sentry/pull/48599 is now closed. Will quick revert if I break CI
=> Turn on capacity management by default

snuba/datasets/processors/functions_processor.py, tests/datasets/test_functions_processor.py
The new functions payload containing the new fields will now be a flat list instead of a nested tree structure. This changes the functions processor to be able to handle the new format.
=> feat(functions): Process new functions message

.github/workflows/ci.yml
=> ref: reference SENTRY_INTERNAL_APP_ID from vars

requirements.txt, snuba/redis.py
This code was originally copied from Sentry, and has since been modified
to handle more edgecases. Bring those changes back into Snuba.
=> ref: Use RetryingRedisCluster from sentry-redis-tools

tests/clickhouse/optimize/test_optimize_tracker.py
This still fails quite a bit in the distributed tests, add a few retries
=> fix: Fix flaky optimize test

snuba/consumers/consumer.py
It's basically the same information as consumer_group, however, it is
inconvenient to query snuba_logical_topic due to lack of global filter.
=> ref(process_message): Tag all metrics by consumer_group

snuba/datasets/configuration/replays/storages/replays.yaml
now that https://github.com/getsentry/snuba/pull/4196 is merged we can add these. outcome of https://github.com/getsentry/rfcs/pull/88.
Will help with https://sentry.sentry.io/issues/4189062783/?project=1&query=is%3Aunresolved+assigned_or_suggested%3A%5Bme%5D&referrer=issue-stream&statsPeriod=24h&stream_index=1 
Fixes OOM issues we see here: https://sentry.sentry.io/issues/3989847924/?project=1&query=Memory+issue.category%3Aerror&referrer=issue-stream&statsPeriod=90d&stream_index=1
=> config(replays): add replays query settings

snuba/datasets/processors/spans_processor.py, tests/datasets/test_spans_processor.py
Extract platform from `spans.system`
=> fix(spans): use system instead of platform

snuba/datasets/configuration/issues/storages/search_issues.yaml, tests/test_search_issues_api.py
Blocked by https://github.com/getsentry/sentry/pull/50075
=> feat(CapMan): Search Issues Allocation Policy

snuba/datasets/configuration/outcomes/storages/hourly.yaml, snuba/datasets/configuration/outcomes_raw/storages/raw.yaml, tests/test_outcomes_api.py
[Last time](https://github.com/getsentry/snuba/pull/4262) I [broke](https://github.com/getsentry/snuba/pull/4262#issuecomment-1570791590) Sentry, [should be fine](https://github.com/getsentry/sentry/pull/50096) this time 💯
=> feat(CapMan): Outcomes Allocation Policy Again

snuba/datasets/processors/replays_processor.py
Not needed anymore within individual message processors since we have
switched to the new DLQ implementation which already records the rate of
invalid messages, and logs them to Sentry.
=> ref: Remove unnecessary try/except from replays processor

snuba/cli/multistorage_consumer.py, snuba/datasets/slicing.py
Multistorage consumer now resolves topics and storages in the same way as the other consumers
=> ref: Refactor multistorage consumer to use consumer config

snuba/subscriptions/scheduler_processing_strategy.py
We want to ensure the scheduling latency is recorded even for low volume environments where there are barely any subscriptions registered (e.g. single tenants).
=> feat: Always record scheduling latency

snuba/admin/static/api_client.tsx, snuba/admin/static/capacity_management/allocation_policy.tsx, snuba/admin/static/capacity_management/index.tsx, snuba/admin/static/capacity_management/types.tsx, snuba/admin/static/tests/capacity_management/allocation_policies.spec.tsx, snuba/admin/static/tests/capacity_management/index.spec.tsx, snuba/admin/yarn.lock
- Updated Capacity Management UI to work with multiple policies
- This PR will merge this branch into the relevant backend update branch, I pulled this out into it's own PR so front end changes can be reviewed independently of the backend diff
- This wasn't as big of a refactor as I was expecting so it is actually in full working condition
https://github.com/getsentry/snuba/assets/23463457/a2a8c13d-02d4-4674-a9ce-2f30a548fb4c
=> feat(CapMan): Multiple Allocation Policies on a Storage [frontend]

tests/clickhouse/optimize/test_optimize_tracker.py
Disabling flaky test for now to improve everyone's life
=> fix(tests): Skip flaky optimize tests

snuba/datasets/configuration/metrics/storages/counters.yaml, snuba/datasets/configuration/metrics/storages/distributions.yaml, snuba/datasets/configuration/metrics/storages/sets.yaml
This reverts commit a7be100d290c6304961aa209b8d19bf03e7dd5d4.
For when the topics actually exist in prod
=> Revert "fix: Temporarily revert dlq topic changes"

snuba/datasets/processors/spans_processor.py, tests/datasets/test_spans_processor.py
set parent_span_id to 0 if missing, log and fail gracefully if span_id is missing
=> fix(spans): set parent_span_id to 0 if missing

snuba/consumers/consumer_builder.py
This can cause consumer to not shut down cleanly
=> fix: Properly shut down DLQ producer

requirements.txt, snuba/consumers/consumer_builder.py
Applying the basic retry policy with 3 retries everywhere now
=> feat: Arroyo 2.12.0

requirements.txt, tests/consumers/test_consumer_builder.py, tests/test_consumer.py
Depends on https://github.com/getsentry/pypi/pull/352
=> build: Bump confluent-kafka-python to 2.1.1

docker-compose.gcb.yml
fails pytest on the first error
=> fail tests on first error

snuba/consumers/consumer.py
We use the validation errors in prod (especially the attached message.txt) to iterate on the schema. This is kind of a hack to get hold of example messages before a schema is defined to help speed up the process of creating a schema for topics where we don't have them yet.
=> feat: Occasionally log errors if no schema found

.github/workflows/ci.yml
This sometimes just gets stuck and times out. Let's fail faster.
=> ci: Fail faster

snuba/migrations/operations.py
Log what nodes we are applying migrations on to help with debugging.
=> show nodes migration is applied on

snuba/consumers/consumer_builder.py
=> fix(dlq): Actually consume the right topic

snuba/datasets/processors/querylog_processor.py
This is temporary code that should be reverted. It adds the ability to reject messages from the querylog processor and DLQ them based on a reject rate which can be set via runtime config.
We will try replaying them using the new DLQ replay mechanism.
=> feat(dlq-test): Add temporary code to fail message processing

snuba/web/views.py
=> feat: Schema enforcement in the test API

gocd/pipelines/snuba.yaml
Doesn't appear to be getting deployed. Maybe needs to be here too?
=> build: Deploy dlq consumer

snuba/admin/static/index.tsx, snuba/admin/static/types.tsx, snuba/admin/views.py
Add the logged in user's email to any Sentry errors/tracing etc.
=> ref(admin): Set the user email in Sentry

snuba/web/views.py
=> ref: Clean up print statements

tests/consumers/test_schemas.py
We have schemas for these now, can be unskipped
=> test: Unskip schema validation on some topics

snuba/querylog/__init__.py, snuba/querylog/query_metadata.py, snuba/web/db_query.py, tests/datasets/test_querylog_processor.py, tests/test_snql_api.py, tests/web/test_db_query.py
=> Revert "ref: Remove old query status field"

Makefile, gocd/generated-pipelines/rollback-snuba-next.yaml, gocd/generated-pipelines/snuba-next-monitor.yaml, gocd/generated-pipelines/snuba-next-us.yaml, gocd/templates/jsonnetfile.json, gocd/templates/jsonnetfile.lock.json, gocd/templates/pipelines/snuba.libsonnet, gocd/templates/snuba.jsonnet
=> Update jsonnet lib and add rollback pipeline

snuba/datasets/configuration/replays/entities/replays.yaml, snuba/datasets/configuration/replays/storages/replays.yaml, snuba/datasets/processors/replays_processor.py, tests/datasets/test_replays_processor.py
Previously merged: https://github.com/getsentry/snuba/pull/4470
=> chore(replays): Revert removal of dead and rage click column processors

snuba/datasets/metrics_messages.py, snuba/datasets/processors/generic_metrics_processor.py
Update the processor to insert retention_days as the TTL for the minute granularity.
=> fix(generic-metrics): Update aggregation option column default values

gocd/generated-pipelines/rollback-snuba.yaml, gocd/templates/jsonnetfile.json, gocd/templates/jsonnetfile.lock.json, gocd/templates/snuba.jsonnet
=> Add elastic agent to rollback pipeline

snuba/consumers/consumer.py
No reason to ever change this, let's hardcode rather than make more runtime config items
=> ref: Remove unnecessary config

snuba/cli/multistorage_consumer.py, snuba/subscriptions/executor_consumer.py, snuba/subscriptions/scheduler_consumer.py
Arroyo does this automatically now for all consumers since https://github.com/getsentry/arroyo/pull/252.
We don't need to duplicate this code in Snuba
=> ref: Remove manual collection of librdkafka stats

gocd/generated-pipelines/rollback-snuba.yaml, gocd/generated-pipelines/snuba-customer-1.yaml, gocd/generated-pipelines/snuba-customer-2.yaml, gocd/generated-pipelines/snuba-s4s.yaml, gocd/templates/jsonnetfile.json, gocd/templates/jsonnetfile.lock.json
This also renames monitor to s4s.
=> Add customer 1 and 2 to pipedream

snuba/migrations/clickhouse.py
We are going to put group-attributes on 23.3 and start building support for this version
=> feat(clickhouse): Enable 23.3

snuba/migrations/groups.py
Running this in Sentry for internal testing
Depends on https://github.com/getsentry/snuba/pull/4566
=> feat(group-attributes): Migration readiness state = partial

rust_snuba/Cargo.lock, rust_snuba/Cargo.toml, rust_snuba/src/lib.rs, rust_snuba/src/processors/mod.rs, rust_snuba/src/processors/querylog.rs
Not used yet, will be integrated and tested as a follow up
=> feat(rust-consumer): Port querylog processor to Rust

snuba/datasets/configuration/transactions/storages/transactions.yaml
When this is merged it will not be enforced so we can tune it
=> feat(capman): Add rate limit policy for transactions

gocd/generated-pipelines/rollback-snuba.yaml, gocd/generated-pipelines/snuba-customer-3.yaml, gocd/generated-pipelines/snuba-customer-4.yaml, gocd/generated-pipelines/snuba-customer-5.yaml, gocd/generated-pipelines/snuba-customer-6.yaml, gocd/templates/jsonnetfile.json, gocd/templates/jsonnetfile.lock.json
This change adds customer 3 and 4 to pipedream and test deployments for customers 5 and 6
NOTE: This is the final addition of deployments that I've planned
=> Update gocd-jsonnet to v1.4.1

.github/workflows/validate-pipelines.yml
see https://github.com/getsentry/relay/pull/2376
=> ci: only render gocd pipelines if relevant files are changed

snuba/web/db_query.py
- Fixing a slight oversight merged in by #4616
- Query ID is randomized by cache bypass logic but the Query ID tag is still the non-randomized one in the span of the overall transaction
=> fix(cache): Incorrect Query ID in span if Cache is bypassed

rust_snuba/src/processors/querylog.rs
Needs to be transformed to UUID to insert to ClickHouse
=> fix(rust-consumer): Fix serializing request_id

snuba/datasets/configuration/spans/storages/spans.yaml, snuba/datasets/processors/spans_processor.py, snuba/settings/validation.py, snuba/utils/streams/topics.py, tests/datasets/test_spans_payloads.py, tests/datasets/test_spans_processor.py, tests/test_spans_api.py
This switches to the only spans consumer pipeline. This is to be merged after  sentry consumer and kafka schemas PRs are merged in.
=> feat(spans): switch to only spans consumer

snuba/settings/validation.py, snuba/utils/streams/topics.py
Add the `snuba-spans` topic. This has to be done before #4607
=> feat(spans): add the spans topic

snuba/web/db_query.py, tests/web/test_db_query.py
This PR was reverted out of caution because when it was deployed the load on a clickhouse replica and the query node went up significantly. With some post-hoc analysis, I cannot find a reason why this would cause the concurrent queries to go up. Here are the reasons why I think these are unrelated:
* This PR only changes the reporting of the queries, not the way queries are executed
* There is no active allocation policy concurrent limiting at the moment and this PR does not change the amount of queries going to clickhouse
* During the load/concurrent query spike there was a huge spike (187 -> 1100) in TCP_TIME_WAIT sockets on the query node
https://app.datadoghq.com/s/FH6-Y3/zak-spc-r24
which was very disproportional to the concurrent queries hitting the node
* On replica 1-5 (which had …
=> hack(capman): allocation policy violations don't impact SLO

snuba/datasets/configuration/spans/storages/spans.yaml, snuba/datasets/processors/spans_processor.py, snuba/utils/streams/topics.py, tests/datasets/test_spans_payloads.py, tests/datasets/test_spans_processor.py, tests/test_spans_api.py
retry of #4607 . I split the PR into the following steps:
1. Merge in #4654 to set up the topic
2. Update the production settings to make the brokers visible
3. merge in this PR to switch consumer
=> feat(spans): switch to only spans consumer - attempt 2

tests/consumers/test_schemas.py
=> test: Unskip some schema validation

rust_snuba/Cargo.lock, rust_snuba/Cargo.toml, rust_snuba/rust_arroyo/examples/base_processor.rs, rust_snuba/rust_arroyo/examples/transform_and_produce.rs, rust_snuba/rust_arroyo/src/lib.rs, rust_snuba/rust_arroyo/src/processing/strategies/mod.rs, rust_snuba/rust_arroyo/src/processing/strategies/produce.rs, rust_snuba/rust_arroyo/src/processing/strategies/reduce.rs, rust_snuba/rust_arroyo/src/processing/strategies/transform.rs, rust_snuba/rust_arroyo/src/testutils.rs, rust_snuba/rust_arroyo/src/types/mod.rs, rust_snuba/src/consumer.rs, rust_snuba/src/strategies/python.rs, rust_snuba/src/types.rs, snuba/cli/rust_consumer.py, snuba/consumers/rust_processor.py
reapply https://github.com/getsentry/snuba/pull/4655, the only notable change here is that with processes=1, there is no process being spawned
=> feat(rust): Multiprocessing with Python message processors, second attempt

snuba/admin/static/production_queries/index.tsx
Adding query history and copy buttons.
=> feat(prod-queries): Add some UI improvements

snuba/datasets/configuration/replays/entities/replays.yaml, snuba/datasets/configuration/replays/storages/replays.yaml
following up to https://github.com/getsentry/snuba/pull/4669 and as part of https://github.com/getsentry/team-replay/issues/145 adds entities/storage for our new columns.
=> feat(replays): update entity/storage for new columns

rust_snuba/rust_arroyo/src/types/mod.rs
There was a bug in the Reduce strategy - since it was passing the seen offsets, rather than the committable offsets (which should be the message offset + 1), it was always committing one behind what it should be. Hopefully this change makes it easier for users of AnyMessage and harder to commit the wrong offset now.
=> fix(rust-arroyo): Simplify AnyMessage::committable() to avoid off by one error

rust_snuba/rust_arroyo/src/processing/mod.rs
Causes weird issues such as https://github.com/confluentinc/librdkafka/issues/2593
Hopefully fixes some behavior we saw last week when the consumer made no progress after we tried switching it over from the Python to Rust processing function.
=> fix(rust-consumer): Don't call resume on unpaused consumer

snuba/cli/rust_consumer.py
We are going to be testing a lot of different concurrency values with the Rust consumer. Add a way to quickly do this via runtime config to save roundtrips with ops. Obviously this is not actually runtime and needs a redeploy but at least
it is self serve for the team.
=> hack(rust-consumer): Add temporary way to override concurrency CLI value

requirements-test.txt
This version contains the first version of MetricsQuery objects.
=> ref(sdk): Update to the latest version of the Snuba SDK

gocd/templates/pipelines/snuba.libsonnet
This PR was intended to cleanup the sentry releases for snuba where each region creates two releases, one for canary and one for prod. This change will only create a snuba release for the US region (i.e. matching the behavior before pipedream).
I've also removed the canary deployment step for non-US regions since only the US has canary pods.
=> Remove canary deploys in non-US regions

snuba/datasets/processors/spans_processor.py
https://sentry.sentry.io/issues/4473169176/?project=300688&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=7d&stream_index=3
=> fix(spans): Handle bad group and group_raw values

rust_snuba/rust_arroyo/src/processing/strategies/reduce.rs
Avoid unnecessary clone if Reduce gets MessageRejected from the next step.
Also fixes a bug where the batch might not be properly closed if MessageRejected was received in strategy.join(). Now we retry until the timeout is hit.
=> feat(reduce): Avoid clone and ensure all messages are processed in join

gocd/pipelines/snuba-stable.yaml, gocd/templates/bash/check-github.sh
@lynnagara forgot this as part of https://github.com/getsentry/snuba/pull/4720/
=> fix(ci): no more sentry shards

requirements-test.txt
Bump Snuba SDK version to latest.
=> ref(snuba-sdk): Update snuba-sdk version to latest 2.0.1

rust_snuba/Cargo.lock, rust_snuba/Cargo.toml, rust_snuba/src/consumer.rs, rust_snuba/src/lib.rs, rust_snuba/src/logging.rs
Switch to pretty-env-logger, since that's what we have docs for: https://docs.rs/sentry/0.31.7/sentry/integrations/log/index.html
=> ref(rust): Set up logging integration correctly

gocd/templates/bash/saas-sentry-error-check.sh, gocd/templates/bash/saas-sentry-health-check.sh
https://deploy.getsentry.net/go/tab/build/detail/deploy-snuba-us/77/health_check/1/health_check
Error `SKIP_CANARY_CHECKS: unbound variable`
=> fix(GoCD): Unbound variable `SKIP_CANARY_CHECKS`

snuba/consumers/consumer.py
Let's group the errors in Sentry by topic so it's easier to figure out which topics have invalid data.
=> feat: Better grouping of validation error to sentry

rust_snuba/rust_arroyo/src/processing/metrics_buffer.rs, rust_snuba/rust_arroyo/src/processing/strategies/run_task_in_threads.rs
To help us tune this metric in future
=> feat(rust): Record a metric for the number of threads used

snuba/cli/devserver.py
Also try to reduce boilerplate in devserver.py
=> feat(devserver): Run all consumers in devserver with --enforce-schema

gocd/templates/bash/deploy.sh
These are in prod now, ensure they get deployed via gocd
=> feat: Deploy more Rust consumers with gocd

rust_snuba/rust_arroyo/src/processing/mod.rs
This fixes a bug where we were dropping messages when the StreamProcessor got MessageRejected from the processing strategy. Now we properly pause and resume the consumer, and carry over the message to the next iteration of the run loop.
=> fix(rust): Fix a bug that caused messages to be dropped

rust_snuba/src/processors/spans.rs
Turns out span status is optional: https://develop.sentry.dev/sdk/event-payloads/span/#:~:text=Optional.%20Describes%20the%20status%20of%20the%20Span/Transaction.
=> fix(spans): Allow span status to be optional

rust_snuba/rust_arroyo/src/processing/mod.rs
Pausing and resuming consumer is a really slow operation since the rdkafka buffer is discarded. Let's avoid calling this constantly when we are in a backpressure state by only actually pausing if we've been waiting in backpressure for more than 1 second.
If this works, we should probably port this to Python Arroyo too.
=> perf(rust): Only pause consumer after 1 second of backpressure

snuba/admin/clickhouse/common.py
Fix the check in admin to allow CARDINALITY_ANALYZER clickhouse client settings
=> fix(cardinality): Allow new client settings in admin

snuba/cli/consumer.py, snuba/consumers/consumer_builder.py, snuba/consumers/strategy_factory.py
We want this for benchmarking against rust-consumer
=> feat(consumer): Ability to run without writing

snuba/datasets/processors/spans_processor.py
Fixed at the source as well https://github.com/getsentry/sentry/pull/57426
=> fix(spans): Handle the absence of retention_days gracefully

gocd/templates/bash/deploy-st.sh
Add snuba-admin to ST deployments.
Use LABEL_SELECTOR var for consistency with SaaS deployments.
=> fix(gocd): Add snuba-admin to ST deployments

tests/datasets/processors/test_generic_metrics_processor.py
Add typing and fix an assertion in `test_generic_metrics_processor.py`
=> fix(tests): Lint and fix generic_metrics_processors_tests

snuba/admin/cardinality_analyzer/cardinality_analyzer.py
Add counters and sets to the list of storage keys allowed by the cardinality analyzer
=> fix(cardinality-analyzer): Add more storage keys to cardinality analyzer

rust_snuba/src/consumer.rs, rust_snuba/src/logging.rs
https://getsentry.atlassian.net/browse/SNS-2431
=> fix: Fix rust logging setup and sentry integration

rust_snuba/rust_arroyo/src/processing/strategies/commit_offsets.rs
More reduction of unnecessary logging. Also this is showing up as breadcrumbs in Sentry and is pretty useless.
=> feat: Reduce more logging

snuba/migrations/group_loader.py, snuba/snuba_migrations/generic_metrics/0021_counters_mv2.py
Add mat view V2 for counter metrics. This will allow each granularity to have its own retention days.
=> feat(generic-metrics): Add new mat view for generic counter metrics

snuba/consumers/consumer.py, snuba/processor.py
Bring back https://github.com/getsentry/snuba/pull/4872, this time with a small bug fix (https://github.com/getsentry/snuba/pull/4894/commits/e4985bfc3690d0ac1834828fdb1f692701cec3dc)
=> feat(subscriptions): Record received_p99 - take 2

.github/workflows/ci.yml, gocd/pipelines/snuba-stable.yaml, snuba/web/views.py
=> feat(CI): Shard the sentry tests more

.github/workflows/ci.yml
=> fix(CI): Fix sharding number

requirements.txt
Sentry has also been bumped already
=> Bump sentry-kafka-schemas to 0.1.32

snuba/datasets/processors/spans_processor.py, tests/datasets/test_spans_payloads.py
Adds test for spans profile_id and fix bug where test was dependent on local timezone https://stackoverflow.com/questions/34622302/python-datetime-timestamp-issue
=> spans: add profile_id to tests 

snuba/admin/cardinality_analyzer/cardinality_analyzer.py
Add raw tables
```
"generic_metric_sets_raw_dist",
"generic_metric_counters_raw_dist",
"generic_metric_distributions_raw_dist",
```
to be queryable for cardinality analyzer
=> feat(cardinality-analyzer): Add raw tables as allowed tables for cardinality analyzer

rust_snuba/rust_arroyo/src/backends/kafka/mod.rs, rust_snuba/src/metrics/statsd.rs
=> fix(rust): Remove unnecessary dead code lint

snuba/subscriptions/types.py, tests/subscriptions/test_types.py
=> fix: Fix SNUBA-3XE

snuba/migrations/group_loader.py, snuba/migrations/groups.py, snuba/snuba_migrations/generic_metrics/0022_gauges_aggregate_table.py, snuba/snuba_migrations/generic_metrics/0023_gauges_raw_table.py, snuba/snuba_migrations/generic_metrics/0024_gauges_mv.py
Reverts getsentry/snuba#4930
Will retry this change (https://github.com/getsentry/snuba/pull/4847) once clusters are confirmed to be configured properly.
=> feat(generic-metrics):  Retry Migrations for all gauges tables

rust_snuba/rust_arroyo/examples/base_consumer.rs, rust_snuba/rust_arroyo/examples/base_processor.rs, rust_snuba/rust_arroyo/examples/transform_and_produce.rs, rust_snuba/rust_arroyo/src/backends/kafka/mod.rs, rust_snuba/rust_arroyo/src/backends/local/broker.rs, rust_snuba/rust_arroyo/src/backends/local/mod.rs, rust_snuba/rust_arroyo/src/backends/mod.rs, rust_snuba/rust_arroyo/src/backends/storages/memory.rs, rust_snuba/rust_arroyo/src/backends/storages/mod.rs, rust_snuba/rust_arroyo/src/processing/mod.rs, rust_snuba/rust_arroyo/src/utils/clock.rs, rust_snuba/src/consumer.rs
This reverts commit c7f4213846bd6d5231d14bc1f26d7f9b4247a112.
Consumer has stopped committing entirely, reverting to figure out why
=> Revert "fix: Commit offsets from strategy join (#4936)"

snuba/datasets/configuration/generic_metrics/storages/gauges.yaml, snuba/datasets/configuration/generic_metrics/storages/gauges_bucket.yaml
This will now activate the new storages, health checks and querying for STs
=> feat(generic-metrics): Bump gauges readiness state to complete

snuba/cli/devserver.py
CDC shouldn't even exist anymore
=> dev: Don't run cdc consumer in dev

rust_snuba/rust_arroyo/src/processing/mod.rs
Based on https://github.com/getsentry/snuba/pull/4936
=> feat(rust): Commit offsets during partition recovation

snuba/migrations/snuba_migrations/generic_metrics/0025_counters_add_raw_tags_hash_column.py, tests/test_snql_api.py
This already exists on the local tables, now we need to add it to the distributed ones
=> fix(metrics): add _raw_tags_hash column to distributed table (counters)

rust_snuba/rust_arroyo/examples/base_consumer.rs, rust_snuba/rust_arroyo/src/processing/mod.rs, rust_snuba/rust_arroyo/src/processing/strategies/produce.rs, rust_snuba/src/strategies/clickhouse.rs, rust_snuba/src/strategies/validate_schema.rs
This applies some clippy suggestions. TBH, I expected there to be a lot more.
=> Apply clippy suggestions

rust_snuba/rust_arroyo/src/backends/storages/memory.rs
The `TopicMessages` (formerly `TopicContent`) struct is intended to store a list of messages for each partition of a topic. We do this simply as a `Vec` of `Vec`s. In particular, this struct doesn't need to know the topic's name.
=> ref: Rename and simplify TopicContent struct

rust_snuba/rust_arroyo/src/backends/local/mod.rs
There were a couple of manual subset checks using `HashSet::difference`, as well as some manual `clone` and `extend` impls.
These have been unified using a new `is_subscribed` fn which checks that all the partitions in the iter are indeed subscribed to.
=> Optimize subset checks

rust_snuba/rust_arroyo/src/processing/strategies/run_task_in_threads.rs, rust_snuba/src/factory.rs, rust_snuba/src/strategies/commit_log.rs, rust_snuba/src/strategies/validate_schema.rs
Not yet integrated into the consumer
=> feat(rust): Add strategy that produces the commit log topic

rust_snuba/src/strategies/clickhouse.rs
Avoids a bunch of clones when sending messages.
=> Micro-optimize `ClickhouseWriter`

rust_snuba/rust_arroyo/src/processing/mod.rs
The main `run_once` fn had a couple of places where it was locking the `consumer` twice in a row, which we avoid now.
This also has some micro-optimizations related to `HashMap` -> `HashSet` transforms.
=> Avoid double locking

snuba/migrations/group_loader.py, snuba/snuba_migrations/generic_metrics/0027_sets_add_raw_tags_column.py
This column already exists on the local tables, adding to the sets dist tables.
Requires: https://github.com/getsentry/snuba/pull/5049
=> fix(generic-metrics): Add raw tags hash to sets dist table

rust_snuba/rust_arroyo/src/processing/mod.rs
This is a port of https://github.com/getsentry/arroyo/pull/299
SNS-2517
=> fix(rust): Clear all backpressure state between assignments

rust_snuba/rust_arroyo/src/processing/strategies/reduce.rs, rust_snuba/src/factory.rs, rust_snuba/src/strategies/clickhouse.rs, rust_snuba/src/strategies/python.rs, rust_snuba/src/strategies/validate_schema.rs
- implement batch_time metric
- add insertions.batch_write_ms metric
- implement schema validation and invalid message metrics
=> ref(rust): Add a few metrics missing from snuba dashboard

rust_snuba/Cargo.lock, rust_snuba/benches/processors.rs, rust_snuba/rust_arroyo/Cargo.toml, rust_snuba/rust_arroyo/src/backends/kafka/mod.rs, rust_snuba/rust_arroyo/src/backends/local/broker.rs, rust_snuba/rust_arroyo/src/backends/local/mod.rs, rust_snuba/rust_arroyo/src/processing/dlq.rs, rust_snuba/rust_arroyo/src/processing/mod.rs, rust_snuba/src/consumer.rs
Some smaller cleanups, clearing up some of my own TODOs, and simplifying some match statements.
=> Assorted cleanups

rust_snuba/src/strategies/python.rs
None payload is valid in kafka, make sure we do not panic
=> fix(rust-python): Handle none payload

rust_snuba/src/consumer.rs, rust_snuba/src/processors/functions.rs, rust_snuba/src/processors/mod.rs, rust_snuba/src/processors/profiles.rs, rust_snuba/src/processors/querylog.rs, rust_snuba/src/processors/spans.rs, rust_snuba/src/strategies/commit_log.rs, rust_snuba/src/strategies/processor.rs, rust_snuba/src/strategies/python.rs, rust_snuba/src/types.rs, snuba/consumers/consumer.py, snuba/consumers/rust_processor.py
Implement all the logic necessary for recording SLOs. What is missing is returning the right numbers in the Rust message processor.
SNS-2519
=> feat(rust): Implement base logic for SLO metrics

rust_snuba/Cargo.lock, rust_snuba/rust_arroyo/Cargo.toml, rust_snuba/rust_arroyo/src/processing/strategies/healthcheck.rs
I originally misunderstood this, and was bumping the `mtime` of the file, but it looks like that one needs to *create* the File.
=> Properly create a file in HealthCheck

rust_snuba/rust_arroyo/src/processing/strategies/reduce.rs
Closes SNS-2524.
This is the simplest change makes it so all strategy constructors have the same signature: they are generic in `next_step` and box it if the strategy internally keeps `next_step` as a `Box<dyn Strategy>`.
Personally I'd be in favor of making Strategies themselves generic over the type of the next step and not boxing implicitly; I'm not sure how much of a problem it is in practice, but I could see the current method leading to double-boxing by mistake (some factory or constructor gives you a boxed strategy, you pass it to the constructor of another strategy and it gets boxed again).
=> ref(rust): Align next_step parameters in strategy constructors

rust_snuba/rust_arroyo/src/processing/dlq.rs
=> fix(rust): Flush all messages in DlqPolicyWrapper::flush

snuba/migrations/group_loader.py, snuba/snuba_migrations/spans/0007_spans_add_metrics_summary.py
Splitting https://github.com/getsentry/snuba/pull/5152 into several PRs.
This is meant to show a metrics summary when we're showing span details.
=> feat(spans): Add a metrics summary column to link spans with DDM metrics

requirements.txt, snuba/consumers/consumer.py, snuba/consumers/strategy_factory.py
Retry https://github.com/getsentry/snuba/pull/5170, this time with some fixes to Arroyo
=> perf: Reusable multiprocessing pools v2

rust_snuba/rust_arroyo/src/processing/strategies/run_task_in_threads.rs
=> feat(rust): Port run_task_in_threads test

requirements.txt, rust_snuba/pyproject.toml
This is needed to run Rust Snuba consumer
Needs https://github.com/getsentry/pypi/pull/581
=> build(rust): Update maturin and add to requirements.txt

rust_snuba/rust_arroyo/Cargo.toml, rust_snuba/rust_arroyo/src/backends/kafka/mod.rs, snuba/migrations/groups.py
self.consumer_offsets is the latest offsets seen by the consumer, not the committed offsets.
=> fix(rust): Fix `self.consumer_offsets`

rust_snuba/rust_arroyo/examples/base_processor.rs, rust_snuba/rust_arroyo/src/processing/strategies/commit_offsets.rs, rust_snuba/rust_arroyo/src/types/mod.rs, rust_snuba/src/factory.rs
Closes SNS-2566.
The fact that we're mixing `std` time and `chrono` time in the same file makes this pretty ugly. Suggestions welcome :)
=> feat(rust): Port arroyo.consumer.latency metric

snuba/cli/spans_cardinality_analyzer.py
In our prod systems, there seems to be an issue when cron jobs try to access other systems using envoy. In order to bypass that, we can use the dns name of the cluster to reach the clickhouse host. That is what we do today in the optimize and cleanup jobs as well. So added the requirement to pass in clickhouse host information as a CLI argument.
=> feat(cardinality): Add clickhouse host and port parameters

snuba/utils/profiler.py
Fix SNUBA-42C
followup https://github.com/getsentry/snuba/pull/5235
=> fix(self-profiler): Unset current_transaction correctly

rust_snuba/Cargo.lock
should fix a major perf issue we see on snuba-rust-spans
=> ref(rust): Update statsdproxy

rust_snuba/Cargo.lock, rust_snuba/Cargo.toml, rust_snuba/benches/processors.rs, rust_snuba/benches/utils.rs
Replaces Divan with Criterion. This opens the possibility of integration codspeed.io into our workflow.
=> perf: replace divan with criterion

rust_snuba/rust_arroyo/src/processing/metrics_buffer.rs, rust_snuba/rust_arroyo/src/processing/strategies/run_task_in_threads.rs
statsdproxy should be able to buffer gauges efficiently
=> ref(rust): Remove explicit buffering of gauges

rust_snuba/rust_arroyo/src/processing/strategies/reduce.rs
we had to revert @phacops's #5294 because it panicked in prod. add a testcase in case we want to try that again
=> fix(rust): add testcase for empty batches

rust_snuba/src/processors/functions.rs
Avoids a bunch of clones by borrowing data from the input.
=> Micro-optimize `functions` processor

snuba/migrations/group_loader.py, snuba/snuba_migrations/spans/0008_spans_add_index_on_span_id.py
We're aiming to speed queries by `span_id` using this index.
=> feat(spans): Add index on span_id

rust_snuba/src/consumer.rs, rust_snuba/src/processors/outcomes.rs, rust_snuba/src/processors/profiles.rs, rust_snuba/src/strategies/clickhouse.rs, rust_snuba/src/types.rs
Plus some other micro-optimizations.
=> Avoid copying `BytesInsertBatch`

rust_snuba/Cargo.lock, rust_snuba/Cargo.toml, rust_snuba/benches/processors.rs
This improves most benchmarks by up to 100% on my mac 😲
=> Use jemalloc in Rust benchmarks

requirements-build.txt, requirements.txt
we must only install one maturin version, not two
=> fix: Use maturin 1.4.0, fix requirements

snuba/datasets/configuration/querylog/storages/querylog.yaml, snuba/migrations/groups.py
=> Revert "hack(oncall) Mark querylog as limited to avoid migration checks"

.github/workflows/image.yml
makes the build basically instant when it hits the cache
=> ref: speed up .github/workflows/image.yml

snuba/datasets/storages/tags_hash_map.py, snuba/migrations/group_loader.py, snuba/snuba_migrations/spans/0005_spans_add_sentry_tags.py, snuba/snuba_migrations/spans/0010_spans_add_compression.py
Add ZSTD compression to most spans columns.
=> feat(spans): add migration to add compression to spans

rust_snuba/Cargo.lock, rust_snuba/Cargo.toml, rust_snuba/src/processors/utils.rs
Topic to produce is also passed as an arg now, as this can be overridden from snuba
=> ref(rust): Bump cogs accountant library

rust_snuba/rust_arroyo/src/processing/strategies/run_task_in_threads.rs
Add rust concurrency metric for arroyo
=> rust: add rust concurrency metric

rust_snuba/src/processors/generic_metrics.rs
Use serde's adjacently tagged enum representation to handle different metric types
=> fix(rust): Generic metrics serde implementation

.pre-commit-config.yaml
https://github.com/getsentry/snuba/pull/5390#pullrequestreview-1825019226
=> fix(pre-commit): Apply review feedback

cloudbuild.yaml
Those tests already run in github actions
=> ref(ci): Do not run tests in gcb

rust_snuba/src/processors/metrics_summaries.rs, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-spans-MetricsSummariesMessageProcessor-snuba-spans__1__basic_span.json.snap, snuba/datasets/configuration/spans/entities/metrics_summaries.yaml, snuba/datasets/configuration/spans/storages/metrics_summaries.yaml, tests/datasets/test_spans_processor.py
Once https://github.com/getsentry/snuba/pull/5453 is merged and clusters are migrated, we can start ingesting new fields.
=> feat(metrics-summaries): Ingest new segment-related columns

rust_snuba/src/processors/mod.rs, rust_snuba/src/processors/release_health_metrics.rs, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-metrics-PolymorphicMetricsProcessor-snuba-metrics__1__snuba-metrics1.json.snap, snuba/datasets/processors/metrics_bucket_processor.py, tests/consumers/test_message_processors.py, tests/datasets/test_metrics_processor.py, tests/test_consumer.py
Reverts getsentry/snuba#5491
Last attempt, there was code merged into master shortly before our change landed, making the Port have issues. This is the retry after fixing the discrepancy
=> Take 2: Port PolymorphicMetricsProcessor to Rust

rust_snuba/src/processors/replays.rs
The `tags` field now accepts null values.
=> fix(replays): Tags can be submitted as null

rust_snuba/src/processors/errors.rs
serde(untagged) gives us bad error messages, and as a result we cannot
understand any error we see in prod.
=> fix(rust): Work around poor error messages by serde

snuba/admin/clickhouse/predefined_querylog_queries.py
The querylog queries are broken in SaaS because it now expects the `_dist` table instead of `_local` table
=> fix(querylog): Use _dist table

snuba/cli/query_fetcher.py, snuba/clickhouse/upgrades/comparisons.py, tests/clickhouse/upgrades/test_comparisons.py
This is kind of a redo of some of the steps that I outlined in https://github.com/getsentry/snuba/pull/5374. But things are laid out a bit differently. 
**Fetcher**
This does the work of the following:
* Fetching the queries that we want to re-run from the prod `system.query_log`
* Saving those queries to the GCS bucket
This PR replaces part of the work of the original **Replayer** (the fetching and saving of queries) but that is now going to be updated in https://github.com/getsentry/snuba/pull/5554 to be in charge of replaying queries and saving the results from the re-run queries
=> add query_fetcher cli

snuba/migrations/groups.py
We're using this in Saas now, we should start pushing it out everywhere.
=> feat(group-attributes): Fully release group_attributes

gocd/pipelines/snuba-sns-test.yaml, gocd/templates/bash/deploy-st.sh, gocd/templates/bash/migrate.sh
Followup to #5529 - DE region migrations were still failing, this should fix
=> remove context from deploy scripts for real this time

snuba/datasets/configuration/group_attributes/storages/group_attributes.yaml
We merged the migration here: https://github.com/getsentry/snuba/pull/5567.
=> feat(group-attributes): Mark group attributes storage readiness as complete

gocd/templates/bash/s4s-fetch-queries.sh, gocd/templates/clickhouse-query-fetcher.jsonnet
Similar to https://github.com/getsentry/snuba/pull/5609 but instead adds the query-fetcher, and I also wrote the env vars out individually to see if that works.
The corresponding ops pr: https://github.com/getsentry/ops/pull/9577
=> ref(gocd): add query fetcher for ch upgrades

snuba/querylog/__init__.py
A small mistake in my previous PR that led us to having the wrong app_feature...oops
=> fix(COGS): Clean up conditions for app_feature

.github/workflows/ci.yml, tests/test_snql_api.py
Reference: https://docs.codecov.com/docs/test-result-ingestion-beta
=> ref(codecov) Try out the failed test feature in Codecov

gocd/templates/bash/s4s-clickhouse-queries.sh
I wasn't running this locally with `set -u` so I didn't catch it before and bad @ bash
=> fix(gocd): fix unbound variable

gocd/templates/clickhouse-query-fetcher.jsonnet
=> fix(gocd): add SNUBA_CMD_TYPE

snuba/cli/query_replayer.py
Allow passing in the clickhouse username and password to the replayer.
=> feat(replayer): allow passing in replayer username and password

snuba/admin/cardinality_analyzer/cardinality_analyzer.py, snuba/admin/clickhouse/predefined_cardinality_analyzer_queries.py
Also add a new predefined query to make debugging orgs usage easier.
=> fix(card-an): Allow meta tables to be queried by the cardinality analyzer

snuba/web/query.py, tests/test_api.py, tests/test_snql_api.py, tests/web/test_query_size.py
The new execution pipeline has been running in production without issue. We can now remove the old code
=> cleanup(devexp): remove old execution pipeline code

snuba/admin/cardinality_analyzer/cardinality_analyzer.py
Add these tables so we can start testing them once they roll out.
Depends on https://github.com/getsentry/snuba/pull/5715
=> fix(admin): Add tag value tables to cardinality analyzer

.github/workflows/ci.yml
docker-compose is no longer available on github workers. Update to the new compose included in docker
=> docker-compose -> docker compose

gocd/templates/snuba.jsonnet
This change will cause Snuba to start auto-deploying.
=> ref(gocd): Moving Snuba to continuous deployment

gocd/pipelines/snuba-stable.yaml, gocd/templates/bash/check-migrations.sh, scripts/fetch_service_refs.py
Fixing some checks that relied on the old, non auto-deploying architecture.
=> fix(gocd): Fixing migration checks

rust_snuba/Cargo.lock, rust_snuba/src/consumer.rs, rust_snuba/src/strategies/commit_log.rs
Update the dependencies so get the latest version of rust arroyo
=> chore(rust): Update dependencies

snuba/cli/subscriptions_executor.py, snuba/cli/subscriptions_scheduler.py
same idea as https://github.com/getsentry/snuba/pull/5753 on the subscriptions consumers as well
=> ref: make auto.offset.reset=earliest everywhere

snuba/cli/replacer.py
same as https://github.com/getsentry/snuba/pull/5753 and https://github.com/getsentry/snuba/pull/5765
=> feat: replacer defaults to auto.offset.reset=earliest

.github/workflows/ci.yml, cloudbuild.yaml
This was reverted due to CI breakage. It was not the issue
=> ef: dual-write docker image to artifact registry

.craft.yml, gocd/pipelines/snuba-sns-test.yaml, gocd/pipelines/snuba-stable.yaml, gocd/templates/bash/check-cloud-build.sh, gocd/templates/bash/deploy-st.sh, gocd/templates/bash/deploy.sh, gocd/templates/bash/migrate-reverse.sh, gocd/templates/bash/migrate-st.sh, gocd/templates/bash/migrate.sh, gocd/templates/bash/s4s-clickhouse-queries.sh, gocd/templates/bash/s4s-replay-queries.sh
step 2 is using the new artifactory, step 3 will be removing gcr publish
=> ref: use artifact registry

cloudbuild.yaml
=> ref: remove pushing to legacy gcr

rust_snuba/src/strategies/clickhouse/mod.rs
=> chore(rust): Minor logging improvements

snuba/datasets/configuration/events/entities/events.yaml, tests/datasets/test_group_attributes_join.py
Ticket: https://getsentry.atlassian.net/browse/REQ3S-101
This PR is responsible for adding support to perform an inner join between events and group_attributes.
=> chore(on-call): Support group attributes inner join

gocd/templates/jsonnetfile.json, gocd/templates/jsonnetfile.lock.json
Updated `gocd-jsonnet` version for provisioning.
=> updated gocd-jsonnet version

snuba/query/conditions.py
I have put the recursion bug fix behind a feature flag in order to see if it works in prod or breaks things
=> fix(api): recursion bug fix experiment

rust_snuba/Cargo.lock, rust_snuba/Cargo.toml, rust_snuba/src/strategies/accountant.rs
It seems we get some produce-related errors in prod related to
accounting, let's upgrade the crate first to see if it helps.
=> ref: Upgrade usage-accountant

snuba/replacers/replacements_and_expiry.py
As a followup to https://github.com/getsentry/snuba/pull/5941, there are additional metrics I'd like to add
=> more replacements metrics

snuba/replacers/errors_replacer.py
emits a DD metric for the number of projects skipped
=> number of projects skipped

snuba/admin/static/production_queries/index.tsx, snuba/admin/static/production_queries/types.tsx, snuba/query/allocation_policies/bytes_scanned_window_policy.py
SNS-2645: Adding changes to remove snuba admin URI ("https://snuba-admin.getsentry.net/") from org_less_referrer to apply allocation policies for queries ran through snuba admin tool. Frontend code changes to show the allocation policies applied for the queries executed on the snuba admin tool.
=> SNS 2645 - Surface allocation policy decisions in production queries tool

snuba/web/db_query.py
Include metrics for the number of queries resulting in cache hits, misses, and waits associated with datasets
=> Include metrics for the number of queries resulting in cache hits, misses, and waits associated with datasets.

tests/query/parser/test_formula_mql_query.py
Adds a test for formula queries with scalar values.
I.e.
```
(-1 - avg(`d:transactions/duration@millisecond`){status_code:418})
/ sum(`d:transactions/duration@millisecond`){status_code:418} + 1
```
=> test(mql): Add tests for formula queries with scalar values

snuba/web/db_query.py
=> Revert "sets throttle policy correctly"

tests/query/parser/test_formula_mql_query.py
Add tests for formula queries with curried aggregate.
=> test(mql): Curried aggregate

.vscode/settings.json
Enables auto-import for Snuba. Mirrors https://github.com/getsentry/sentry/pull/74197
=> feat(auto-import): Enable default vscode auto-import for Snuba

snuba/datasets/configuration/events_analytics_platform/entities/eap_spans.yaml
We moved from 200 columns to 20, reflect that here
=> fix(eap): Update number of columns in entity

snuba/web/delete_query.py, snuba/web/views.py
Just adds some sentry tracing for the delete flow
=> ref(snuba-deletes): add with_span

rust_snuba/src/processors/eap_spans.rs
We would like to re-multiply things if they are set from upstream.
=> chore(eap): Set client sample rate if it comes from upstream

rust_snuba/src/processors/eap_spans.rs, rust_snuba/src/processors/snapshots/rust_snuba__processors__eap_spans__tests__serialization.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-spans-EAPSpansMessageProcessor-snuba-spans__1__basic_span.json.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__snuba-spans-.snap, rust_snuba/src/processors/spans.rs
- Read span.data from relay and insert it into the eap_spans buckets
- Use type inference from the sent json to decide whether each value in `span.data` goes into the string buckets or the number buckets
=> feat(eap): Also read the data in span.data into the buckets

snuba/web/delete_query.py, tests/test_search_issues_api.py
fix bug in region specific delete feature flag
=> fix: snuba deletes config default 

snuba/web/views.py, tests/web/rpc/test_timeseries_api.py
Providing an API to hit which will take the expected payload
=> feat(eap): stub API for aggregate bucket request

gocd/templates/jsonnetfile.json, gocd/templates/jsonnetfile.lock.json
=> change: Update gocd jsonlib to 2.13

snuba/web/rpc/timeseries.py, tests/web/rpc/test_timeseries_api.py
Now that the DSL is here this is easy
=> feat(EAP): implement quantiles in RPC API

snuba/query/mql/mql_context.py, snuba/query/mql/parser_supported_join.py, tests/query/parser/test_formula_mql_query.py, tests/query/parser/test_parser.py
Use the newly added flag from MQL context determine whether to query the weighted columns or the non-weighted columns
=> feat(generic-metrics): Adds extrapolation to MQL

snuba/admin/static/cardinality_analyzer/query_display.tsx, snuba/admin/static/clickhouse_queries/query_display.tsx, snuba/admin/static/production_queries/index.tsx, snuba/admin/static/query_history.tsx, snuba/admin/static/querylog/query_display.tsx, snuba/admin/static/snql_to_sql/index.tsx, snuba/admin/static/snuba_explain/index.tsx, snuba/admin/static/tests/query_history.spec.tsx, snuba/admin/static/tracing/query_display.tsx
- Adds history to queries so that even when you refresh your last 5 queries will still be on the page
https://github.com/user-attachments/assets/7c053617-952f-42a4-9f7f-cfae071b0595
=> feat(snuba-admin): Add query history

snuba/admin/static/common/components/sql_editor.tsx
A small leftover request from Hackweek.
=> feat: CodeMirror line wrapping

snuba/web/rpc/common.py, snuba/web/views.py, tests/web/rpc/test_timeseries_api.py
This merges all the existing RPCs to a single /rpc/AggregateBucketRequest endpoint
=> chore(eap): Merge RPC endpoints to a single place

CODEOWNERS
=> chore(eap): Fix typo in CODEOWNERS

snuba/admin/clickhouse/common.py, snuba/admin/views.py, tests/admin/test_api.py
Added snuba admin logs for troubleshooting in production and unblocked @nachivrn by commenting the profile event gathering logic.
=> Debug snuba admin event profile query tracing

snuba/snuba_migrations/events_analytics_platform/0012_span_attribute_table_numeric.py
See https://github.com/getsentry/snuba/pull/6262, this is the numeric equivalent and identical in all other ways.
=> feat(eap): Add a numeric attributes meta table 

snuba/datasets/configuration/events_analytics_platform/dataset.yaml, snuba/datasets/configuration/events_analytics_platform/entities/spans_num_attrs.yaml, snuba/datasets/configuration/events_analytics_platform/entities/spans_str_attrs.yaml, snuba/datasets/configuration/events_analytics_platform/storages/spans_num_attrs.yaml, snuba/datasets/configuration/events_analytics_platform/storages/spans_str_attrs.yaml, snuba/datasets/configuration/json_schema.py, snuba/datasets/configuration/utils.py, snuba/migrations/parse_schema.py, tests/datasets/test_entity_factory.py
See https://github.com/getsentry/snuba/pull/6265 and https://github.com/getsentry/snuba/pull/6262 for context.
=> chore(eap): Add entities and storages for EAP span meta tables

requirements.txt, snuba/web/rpc/tags_list.py, snuba/web/views.py, tests/web/rpc/test_tags_list.py
This is important for things like the search bar, where you want to discover tags you can use
=> feat(eap): Endpoint to get the tags available for a project

snuba/datasets/configuration/events_analytics_platform/storages/eap_spans.yaml, snuba/web/rpc/common.py, tests/web/rpc/test_common.py, tests/web/rpc/test_span_samples.py
Adds some tests for span_samples, and solves some issues with span_id
=> fix(eap): Make span_id be returned as a string correctly

snuba/datasets/configuration/events_analytics_platform/entities/eap_spans.yaml, snuba/datasets/configuration/events_analytics_platform/storages/eap_spans.yaml
Evan added this in https://github.com/getsentry/snuba/pull/6190, make it queryable via the entity with a rename
=> fix(eap): Switch to sampling_weight_2 in entity

tests/web/rpc/test_trace_item_attribute_list.py, tests/web/rpc/test_trace_item_attribute_values.py
Partially reverts https://github.com/getsentry/snuba/pull/6317
=> test(eap): re-enable attribute tests

snuba/web/views.py, tests/test_search_issues_api.py
Should fix errors popping up in https://github.com/getsentry/sentry/pull/78062
=> fix(snuba-deletes): Remove trailing slash

rust_snuba/Cargo.lock
There seem to be a few high-severity bugfixes in master.
=> chore(rust): Bump rust-rdkafka

snuba/admin/static/capacity_management/index.tsx, snuba/admin/static/capacity_management/types.tsx, snuba/admin/static/tests/capacity_management/allocation_policies.spec.tsx, snuba/admin/static/tests/capacity_management/index.spec.tsx, snuba/admin/views.py, tests/admin/test_api.py
The UI was supposed to get added in https://github.com/getsentry/snuba/pull/6248, not sure what happened here. 
Also had to fix the endpoint too - I think I did a bad merge conflict resolution or something
=> fix(allocation-policies): delete policies to admin re-do

tests/web/rpc/v1alpha/test_timeseries_api.py
Just making sure that the merge function for t-digest states works.
=> test(eap): Create unit tests for t-digest state merging

snuba/admin/rpc/rpc_queries.py, snuba/admin/static/api_client.tsx, snuba/admin/static/rpc_endpoints/exampleRequestTemplates.json, snuba/admin/static/rpc_endpoints/index.tsx
Improve error handling by providing more informative API error messages and display in RPC snuba admin tool
- Update snuba/admin/static/api_client.tsx to capture and propagate API error messages
- Modify snuba/admin/static/rpc_endpoints/index.tsx to alert API errors
- Update snuba/admin/rpc/rpc_queries.py for better error handling message
- Update snuba/admin/static/rpc_endpoints/exampleRequestTemplates.json including version information for example payloads.
=> Improve error handling and display in RPC admin interface

snuba/admin/clickhouse/predefined_querylog_queries.py
Adds a predefined query to Snuba Admin's Querylog. This is for the CapMan runbook for when we need to increase a customer's threshold.
=> CapMan predefined queries

snuba/admin/static/rpc_endpoints/index.tsx
- Implement debug mode toggle for supported RPC endpoint versions
- Add query metadata display in an accordion for executed requests
- Enhance response visualization with separate sections for metadata and data
=> fix(admin): Add debug mode and query metadata to RPC Endpoints UI

snuba/datasets/configuration/functions/entities/functions.yaml, snuba/datasets/configuration/functions/storages/functions.yaml, snuba/datasets/configuration/json_schema.py, snuba/migrations/columns.py
Following up PR https://github.com/getsentry/snuba/pull/6420, this updates the entity and storage config files accordingly.
=> ref(functions): updates entity and storage config files

snuba/admin/static/tracing/index.tsx
=> feat(tracing): Add a formatted frontend for profile events in tracing tool

snuba/admin/package.json, snuba/admin/yarn.lock
https://github.com/getsentry/snuba/security/dependabot/61
=> chore(deps-dev): bump webpack from 5.88.0 to 5.95.0 in /snuba/admin

rust_snuba/src/mutations/factory.rs
In prod we have 2 min ingestion lag now, so 1h seems good
=> chore(eap): Reduce delay drastically again

snuba/query/allocation_policies/bytes_scanned_rejecting_policy.py, tests/query/allocation_policies/test_bytes_scanned_rejecting_policy.py, tests/web/test_db_query.py
The throttling mechanism was incorrect. This PR makes it correct
=> [CapMan visibility] fix throttling mechanism

snuba/admin/clickhouse/profile_events.py
the `gather_profile_events` functionality for the snuba tracing tool doesn't seem to work well with abnormal storage sets like discover. the host and port that are found in the trace data doesn't match cluster definitions in the [snuba settings](https://github.com/getsentry/ops/blob/5cf804216638d81cc251657a515f265a0b0c5f5a/k8s/services/snuba/region_overrides/us/default.yaml#L165-L170).
ex. we get the following `InvalidNodeError` error message: `"host snuba-errors-tiger-mz-3-6 and port 9000 are not valid"` when trying to get profile events for the discover storage. the discover storage doesn't have any local or dist nodes, just the query node
=> fix(admin): ignore gather_profile_events for certain storages

snuba/web/rpc/common/common.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table_extrapolation.py
Fixes https://github.com/getsentry/projects/issues/399
=> fix(eap): Fix bug where count wasn't aggregating correctly

requirements.txt, snuba/web/rpc/common/common.py
- This updates the RPC to support p75 as a function too
=> feat(rpc): Add p75 as a function

scripts/send_spans.py
While using the script for generating load, I found that messages were not being produced to the kafka topic. Triaged it to the program exiting prematurely and not waiting for the kafka producer to finish. Wait for all futures before exiting the program.
=> fix(script): Wait for futures when producing to kafka

snuba/web/rpc/common/common.py, tests/web/rpc/test_common.py
Does [this](https://github.com/getsentry/snuba/pull/6581#pullrequestreview-2452984129)
=> fix(eap-api): delimeter for alias

rust_snuba/src/processors/eap_spans.rs, rust_snuba/src/processors/snapshots/rust_snuba__processors__eap_spans__tests__serialization.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-spans-EAPSpansMessageProcessor-snuba-spans__1__basic_span.json.snap
We need to make sure we extract profile id for eap spans as well.
=> feat(eap): Extract profile id for eap spans

snuba/datasets/configuration/events_analytics_platform/entities/eap_spans.yaml, snuba/web/rpc/common/aggregation.py, snuba/web/rpc/v1/endpoint_time_series.py, snuba/web/rpc/v1/endpoint_trace_item_table.py, tests/web/rpc/test_aggregation.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series_extrapolation.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table_extrapolation.py
Closes https://github.com/getsentry/projects/issues/394
=> feat(eap): add confidence calculations for sums and averages

gocd/templates/bash/deploy.sh
EAP scheduler and executor consumers have access to the snuba image
=> chore(subscriptions): Add EAP scheduler & executor to deploy script

devservices/config.yml
Adding a label to the docker compose config to signify that devservices is the orchestrator.
=> feat(label): adding label to container

.github/workflows/bump-version.yml
Apparently Rust support in bump-version was never tested properly.
=> fix: Actual Rust support in bump-version

snuba/admin/static/rpc_endpoints/endpoint_selector.tsx, snuba/admin/static/rpc_endpoints/index.tsx, snuba/admin/static/rpc_endpoints/types.tsx, snuba/admin/yarn.lock
this closes https://github.com/getsentry/eap-planning/issues/103
=> fix: admin rpc endpoint selector bug fix

snuba/web/rpc/common/aggregation.py, tests/web/rpc/test_aggregation.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series_extrapolation.py
Closes https://github.com/getsentry/eap-planning/issues/104
=> feat(eap): Implement confidence intervals for percentiles

snuba/web/rpc/v1/endpoint_time_series.py
closes https://github.com/getsentry/eap-planning/issues/120
=> feat: support 15 minute granularity on eap time series RPC

snuba/admin/static/rpc_endpoints/exampleRequestTemplates.json
this is a follow up from https://github.com/orgs/getsentry/projects/292/views/1?pane=issue&itemId=89746323&issue=getsentry%7Ceap-planning%7C98
I found another endpoint missing an example, so I added one for it.
=> feat: add missing example in admin rpc tool

requirements.txt, snuba/web/rpc/common/common.py
Closes https://github.com/getsentry/projects/issues/488
=> feat(eap): add default value to virtual column

snuba/web/rpc/v1/endpoint_trace_item_table.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table.py
Closes https://github.com/getsentry/eap-planning/issues/111
=> feat(eap): add additional validation for group by 

requirements.txt, rust_snuba/Cargo.lock, rust_snuba/Cargo.toml
needed for https://github.com/getsentry/snuba/pull/6697
=> feat(deps): bump sentry-kafka-schemas

snuba/datasets/configuration/events_analytics_platform/storages/uptime_monitor_checks.yaml
set this to experimental so we can test on s4s
=> chore(uptime): set readiness state to experimental

snuba/snuba_migrations/profile_chunks/0002_add_environment_column.py
This adds the `environment` column to the `profile_chunks` dataset.
=> feat(profiling): add environment column to the profile_chunks table

rust_snuba/src/processors/mod.rs, rust_snuba/src/processors/ourlogs.rs, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-ourlogs-OurlogsMessageProcessor-snuba-ourlogs__1__maximal_log.json.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-ourlogs-OurlogsMessageProcessor-snuba-ourlogs__1__minimal_log.json.snap, snuba/datasets/processors/ourlogs_processor.py
This consumer will be used in CI and dev (among other places) to put logs into clickhouse directly
=> feat(ourlogs): Add a kafka consumer

rust_snuba/src/processors/profile_chunks.rs, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-profile-chunks-ProfileChunksProcessor-snuba-profile-chunks__1__valid.json.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__snuba-profile-chunks-.snap, snuba/datasets/configuration/profiles/storages/chunks.yaml
Following PR https://github.com/getsentry/snuba/pull/6722
=> feat(profiling): process environment value for profile_chunks and add the column to the storage definition

snuba/cli/devserver.py, snuba/datasets/configuration/events_analytics_platform/dataset.yaml, snuba/datasets/configuration/events_analytics_platform/entities/ourlogs.yaml, snuba/datasets/configuration/events_analytics_platform/storages/ourlogs.yaml, snuba/utils/streams/topics.py, tests/datasets/test_entity_factory.py
- Adds a storage for our new logs type
- Adds an entity for our new logs type
- Configures the new kafka topic from sentry-kafka-schemas
=> feat(ourlogs): Add entity/storage configs & dev worker

snuba/datasets/configuration/issues/storages/search_issues.yaml
issues platform load goin crazy. Adding this policy to police bad actors or we'll have to scale up
=> feat(oncall): add bytesscannedrejectingpolicy to search_issues

snuba/admin/clickhouse/predefined_system_queries.py
I needed this today and thought it could be useful for others.
=> feat(snuba-admin): Add pre-defined query to fetch index sizes

snuba/datasets/configuration/issues/storages/search_issues.yaml
=> INC: Turn off DLQ for search issues/generic events

tests/admin/dead_letter_queue/test_dlq.py
=> hotfix(inc-1013): remove dumb test

snuba/web/rpc/v1/endpoint_get_traces.py, tests/web/rpc/v1/test_endpoint_get_traces.py
Closes https://github.com/getsentry/eap-planning/issues/170
=> feat(eap): add more keys to get_traces

snuba/admin/static/query_history.tsx, snuba/admin/static/tests/query_history.spec.tsx, snuba/admin/yarn.lock
While having the history is good, its not that great at the expense of a snappier load time. Reduce the history size to 3 items.
Fixes https://github.com/getsentry/snuba/issues/6747
=> feat(admin): Reduce history size to last 3 items

.github/workflows/ci.yml, snuba/migrations/clickhouse.py
https://altinity.com/blog/altinity-stable-build-for-clickhouse-24-8
https://hub.docker.com/layers/altinity/clickhouse-server/24.8.11.51285.altinitystable/images/sha256-65b4fed146dd9fa4fc7b0eff17adbeb3c1eb3e5d3c37fc2f635913eafc22b7a5
=> chore(ci): Test with ClickHouse 24.8

snuba/clickhouse/columns.py, snuba/datasets/configuration/json_schema.py, snuba/datasets/configuration/utils.py, snuba/migrations/parse_schema.py, snuba/utils/schemas.py, tests/clickhouse/test_columns.py, tests/datasets/configuration/test_storage_loader.py, tests/migrations/test_parse_schema.py
Add support for the Bool type in Clickhouse.
=> feat: Add a Bool column type

requirements.txt, rust_snuba/Cargo.lock, rust_snuba/Cargo.toml, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-uptime-results-UptimeMonitorChecksProcessor-snuba-uptime-results__1__failure.json.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-uptime-results-UptimeMonitorChecksProcessor-snuba-uptime-results__1__success.json.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-uptime-results-UptimeMonitorChecksProcessor-snuba-uptime-results__1__timeout.json.snap, rust_snuba/src/processors/uptime_monitor_checks.rs, snuba/datasets/configuration/events_analytics_platform/entities/uptime_checks.yaml, snuba/datasets/configuration/events_analytics_platform/storages/uptime_monitor_checks.yaml, snuba/web/rpc/v1/resolvers/R_uptime_checks/common/common.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series_uptime_checks.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table_uptime_checks.py
This reverts commit 2c8e104236a0b2ec1278aae65fc0bca031482d48.
=> Reapply "feat(uptime): Ability to ingest and query in_incident"

snuba/clickhouse/http.py
Add maxsize and block options to http[s]connectionpool  to fix issue: #6918
=> fix(consumer): add options to clickhouse http[s]connectionpool (#6918)

snuba/datasets/configuration/events_analytics_platform/storages/eap_items.yaml, snuba/datasets/configuration/events_analytics_platform/storages/eap_spans.yaml, snuba/datasets/configuration/events_analytics_platform/storages/spans_num_attrs.yaml, snuba/datasets/configuration/events_analytics_platform/storages/spans_str_attrs.yaml
This will return an error after 30s of executing the query.
=> fix(eap): Set a max execution time for queries

snuba/web/rpc/proto_visitor.py, snuba/web/rpc/v1/endpoint_trace_item_table.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table.py
fixes https://github.com/getsentry/eap-planning/issues/201
=> bug: cant use group by with formulas

gocd/templates/bash/deploy.sh
=> remove test-eap-mutations-vector from deploy script

gocd/templates/bash/deploy.sh
TIL comments are not supported here
=> Remove unsupported comments deploy.sh

snuba/admin/clickhouse/tracing.py, snuba/admin/views.py
we were passing in settings in maybe the dumbest way possible. Stop doing that
=> fix(admin): fix log profile events nonsense

devservices/config.yml, snuba/environment.py
=> fix: Fix spotlight configuration

snuba/web/rpc/v1/resolvers/R_eap_spans/common/common.py, snuba/web/rpc/v1/resolvers/R_eap_spans/resolver_get_trace.py, tests/web/rpc/v1/test_endpoint_get_trace.py
Closes https://github.com/getsentry/eap-planning/issues/195
=> feat(eap): Use eap_items in the get trace endpoint

snuba/web/rpc/v1/endpoint_trace_item_attribute_names.py
It's more important for the client to get all of the attributes than returning very quickly from the endpoint. I tested this in the tracing tool, the latency is acceptable for project_id=1
=> feat(autocomplete): remove best effort optimization from autocomplete

requirements.txt, snuba/web/rpc/v1/resolvers/R_eap_spans/resolver_time_series.py, snuba/web/rpc/v1/resolvers/R_eap_spans/resolver_trace_item_table.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table.py
closes https://github.com/getsentry/eap-planning/issues/202
=> feat(eap): implement literals

snuba/web/rpc/v1/resolvers/R_eap_spans/common/common.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table.py
Closes https://github.com/getsentry/eap-planning/issues/226
=> fix(eap): fix bug with virtual columns

snuba/web/rpc/common/common.py
THESE LINES OF CODE WERE RANDOMLY DUPLICATED WHO KNOWS WHY, so i deleted it
=> chore: remove random duplicate code

.github/workflows/ci.yml, rust_snuba/.cargo/config.toml
inspired by https://github.com/getsentry/relay/pull/4632
=> ci: workaround for cmake issue

snuba/snuba_migrations/events_analytics_platform/0038_eap_items_add_sampling_factor.py
First step to address the issue described here: https://www.notion.so/sentry/Sampling-Weight-Extrapolation-Errors-1c28b10e4b5d80f8bbc6f7154870e56a?d=1c88b10e4b5d80dc8ee0001cb56303ea#1c38b10e4b5d80879bf1f8e50bba6efb
=> fix(eap): add sampling factor column

snuba/web/rpc/common/common.py, tests/web/rpc/v1/test_R_ourlogs/test_logs_expression_converters.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table.py
I will wait to merge this until monday. this has been enabled in production for a while now so im getting rid of the feature flag.
=> chore: retire feature flag use_new_null_comparison 

snuba/web/rpc/v1/resolvers/R_eap_spans/common/sampling_in_storage_util.py
=> perf(sampling-in-storage): emit span data

snuba/web/rpc/v1/resolvers/R_eap_spans/common/sampling_in_storage_util.py
adds to https://github.com/getsentry/snuba/pull/7037
=> perf(sampling-in-storage): fix span

rust_snuba/src/processors/eap_items.rs, rust_snuba/src/processors/ourlogs.rs, rust_snuba/src/processors/snapshots/rust_snuba__processors__eap_items__tests__serialization.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-ourlogs-OurlogsMessageProcessor-snuba-ourlogs__1__maximal_log.json.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-ourlogs-OurlogsMessageProcessor-snuba-ourlogs__1__minimal_log.json.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-spans-EAPItemsProcessor-snuba-spans__1__basic_span.json.snap, snuba/datasets/configuration/events_analytics_platform/entities/eap_items.yaml, snuba/datasets/configuration/events_analytics_platform/entities/eap_items_log.yaml, snuba/datasets/configuration/events_analytics_platform/storages/eap_items.yaml, snuba/datasets/configuration/events_analytics_platform/storages/eap_items_downsample_512.yaml, snuba/datasets/configuration/events_analytics_platform/storages/eap_items_downsample_64.yaml, snuba/datasets/configuration/events_analytics_platform/storages/eap_items_downsample_8.yaml, snuba/datasets/configuration/events_analytics_platform/storages/eap_items_log.yaml
Write to new column created by https://github.com/getsentry/snuba/pull/7014
Don't merge until that change is merged!
=> fix(eap-items): Write to new sampling_factor column

snuba/web/rpc/v1/resolvers/R_eap_spans/common/sampling_in_storage_util.py
Right now all the span attributes is saying target tier is 1
=> fix(sampling-in-storage): fix increment metric

snuba/admin/clickhouse/tracing.py
Those things are usually not sensitive information.
=> fix(admin): Do not scrub UUIDs, hex strings and datetimes

snuba/web/rpc/v1/resolvers/R_eap_spans/common/sampling_in_storage_util.py
to figure out: are we over or under estimating?
my understandig is that gauge is the authoritative value
=> perf(sampling-in-storage): emit raw estimation error

snuba/web/rpc/v1/resolvers/R_eap_spans/common/sampling_in_storage_util.py
There are 2 possibilities that can cause a 0 div error like [this one](https://sentry.sentry.io/issues/6532558122/?project=300688&query=firstRelease%3A7498331448cc0b2572a944654f36df17308a3a4b%20issue.type%3Aerror%20%21level%3Ainfo%20%21server_name%3A%2Aeap%2A&referrer=issue-stream&stream_index=0)
1. `ClickhouseProfile` never gets filled, which shouldnt happen, so I just error if it does
2. The query actually scanned 0 bytes, in which case I'd want to see what the result from CH looks like
=> fix(sampling-in-storage): query scans 0 bytes

requirements.txt, rust_snuba/Cargo.lock, rust_snuba/Cargo.toml
ref https://github.com/getsentry/arroyo/pull/449
fix #6358 #3551 #6441
=> feat(rust-snuba): Enable SSL in rdkafka

snuba/web/rpc/v1/resolvers/R_eap_items/resolver_time_series.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series.py
follow up to https://github.com/getsentry/snuba/pull/7088
see that PR for a description
=> feat: eap timeseries, enable default value in formulas

snuba/settings/__init__.py, snuba/web/rpc/common/common.py, snuba/web/rpc/v1/resolvers/R_eap_items/resolver_time_series.py, snuba/web/rpc/v1/resolvers/R_eap_items/resolver_trace_item_table.py, snuba/web/rpc/v1/resolvers/R_uptime_checks/resolver_time_series.py, snuba/web/rpc/v1/resolvers/R_uptime_checks/resolver_trace_item_table.py, snuba/web/rpc/v1/resolvers/common/aggregation.py, tests/web/rpc/test_common.py
Closes https://github.com/getsentry/eap-planning/issues/239
=> feat(eap): use sampling factor in aggregations

snuba/web/rpc/v1/resolvers/R_eap_items/routing_strategies/linear_bytes_scanned_storage_routing.py, snuba/web/rpc/v1/resolvers/R_eap_items/routing_strategies/sampling_in_storage_util.py, snuba/web/rpc/v1/resolvers/R_eap_items/routing_strategy_selector.py, snuba/web/rpc/v1/resolvers/R_eap_items/storage_routing.py, tests/web/rpc/v1/routing_strategies/test_linear_bytes_scanned.py, tests/web/rpc/v1/routing_strategies/test_strategy_selector.py, tests/web/rpc/v1/test_storage_routing.py
We plan on having multiple strategies to test out, which requires us to implement a strategy selector. 
The strategy selector will read config from Snuba Admin. This PR sets this up
=> feat(sampling-in-storage): set up json parsing for storage selector

tests/web/rpc/v1/test_storage_routing.py
https://github.com/getsentry/snuba/pull/7121 but increase the bound
=> fix(storage-routing): fix flakey test

snuba/web/rpc/v1/resolvers/R_eap_items/storage_routing/routing_strategies/normal_mode_linear_bytes_scanned.py
Make them the same as the outcome based strategy so we can view them together in DD
=> perf(storage-routing): routing mistakes metric should use the same tag names

snuba/web/rpc/common/debug_info.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table_logs.py
redo of https://github.com/getsentry/snuba/pull/7131/files
=> feat(storage-routing): dont emit tier

snuba/manual_jobs/truncate_eap_spans.py
Still needs ops changes to actually run in prod
=> create manual job for truncating eap_spans_2_local tables

.github/dependabot.yml
=> chore(dependabot): Remove overlapping schedules

snuba/snuba_migrations/events_analytics_platform/0044_remove_hash_map_columns_0_4.py
Remove the first 10 hash map columns that are not used.
=> chore(eap): Remove hash map columns for buckets 0 to 4

devservices/config.yml, devservices/programs.conf, requirements.txt
This bumps devservices to version 1.2.1. This also consolidates programs.conf file into config.yml
=> chore(devservices): Bump devservices to 1.2.1

snuba/web/rpc/v1/endpoint_get_traces.py, tests/web/rpc/v1/test_endpoint_get_traces.py
Trace view is rolling out on EAP so we can start showing standalone spans.
=> chore(traces): Remove standalone spans condition

rust_snuba/Cargo.lock, rust_snuba/Cargo.toml, rust_snuba/benches/processors.rs, rust_snuba/src/config.rs, rust_snuba/src/consumer.rs, rust_snuba/src/metrics/statsd.rs, snuba/consumers/consumer_config.py
https://github.com/getsentry/snuba/pull/7251 + https://github.com/getsentry/snuba/pull/7253
=> chore(consumers): bump statsdproxy

snuba/clickhouse/optimize/optimize.py, snuba/clusters/cluster.py, snuba/migrations/runner.py
https://linear.app/getsentry/issue/PF-26/sql-injection-in-getsentrysnuba
https://linear.app/getsentry/issue/PF-25/sql-injection-in-getsentrysnuba
https://linear.app/getsentry/issue/PF-19/sql-injection-in-getsentrysnuba
=> chore: fix security vulnerabilities

snuba/settings/__init__.py
This setting is no longer in use
=> remove TOPIC_PARTITION_COUNTS setting from __init__

.github/workflows/bump-version.yml
https://linear.app/getsentry/issue/PF-20
=> fix(ci): update bump-version to not interpolate PR_OPTIONS directly

snuba/web/rpc/v1/endpoint_get_traces.py, tests/web/rpc/v1/test_endpoint_get_traces.py, tests/web/rpc/v1/test_utils.py
reverting https://github.com/getsentry/snuba/pull/7275 with a fix
=> fix(eap): Implement cross item query support in get traces with fix

.github/workflows/ci.yml, config/clickhouse/default-password.xml, devservices/clickhouse/default-password.xml, devservices/clickhouse/users.xml, devservices/config.yml, docker-compose.gcb.yml
Same as https://github.com/getsentry/snuba/pull/7332 and overriding the `default-password.xml` for `dev services` as well.
=> chore: Test ClickHouse 25.3

snuba/web/rpc/storage_routing/routing_strategies/outcomes_based.py, tests/web/rpc/v1/routing_strategies/test_outcomes_based.py
Requests for Traces do not have item type specified (which makes sense). In order to use tracing, a customer is most likely going to be ingesting spans. Thus, use spans as the default item when unspecified. 
We can definitely get more sophisticated with this but this will allow us to sample GetTraces calls and solve some timeouts on big customers
=> fix(storage-routing): If item type is unspecified, default to spans

snuba/datasets/configuration/outcomes/entities/outcomes.yaml, snuba/datasets/configuration/outcomes/storages/daily.yaml, snuba/datasets/entities/storage_selectors/outcomes.py, snuba/query/query_settings.py, snuba/web/rpc/storage_routing/routing_strategies/outcomes_based.py, tests/datasets/entities/storage_selectors/test_outcomes.py, tests/web/rpc/v1/routing_strategies/test_outcomes_based.py, tests/web/rpc/v1/test_storage_routing.py
Okay I cherry-picked commits from https://github.com/getsentry/snuba/pull/7388 since that PR got a little borked as well
=> ref(outcomes): storage selecter, settings, daily storage (try 2)

pyproject.toml, uv.lock
Add `granian` as a dependency.
This will allow to switch the http server on some environments as discussed with @phacops
=> dep: add granian
