getsentry/snuba

snuba/settings/settings_test_distributed_migrations.py

**context:**
Adding in `CLICKHOUSE_MIGRATIONS_HOST` so that I can get this to work with https://github.com/getsentry/clickhouse-setup/pull/4. We set `CLICKHOUSE_HOST` here https://github.com/getsentry/snuba/blob/174398093727ebf337fc3a781aa727638eef8cde/docker-compose.gcb.yml#L27 so we can't use that if we want the host to be different, aka `clickhouse-query`.
Also, need the `single_node=False` change in order for the `migrations_local` table to be created on the right node. Having `single_node=True` means that the local tables get created on the query node (with this set up).
The `single_node` fix was done in https://github.com/getsentry/snuba/pull/3304 but got reverted so im just adding it back in here.
This should all one to test out changes to snuba by having the clickhouse-setup …

ref(migrations): use env varibles for CLICKHOUSE_MIGRATIONS_HOST

---

snuba/cleanup.py
snuba/optimize.py
snuba/optimize_tracker.py
snuba/settings/__init__.py
snuba/util.py
tests/test_optimize.py
tests/test_optimize_tracker.py

Addresses [SNS-1483](https://getsentry.atlassian.net/browse/SNS-1483). 
Adds functionality to query `system.merges` at the start of an optimization and delay running `OPTIMIZE` on a partition if there are already ongoing merges on that partition.
It works by calling `optimize.is_busy_merging()` to check if it should execute a merge or sleep then retry later. 
`is_busy_merging` queries `system.merges` table for merges executing and returns true and the estimated sleep time if clickhouse is busy with merges in progress for the table. Clickhouse is considered busy if:
1. there are more than `settings.OPTIMIZE_MERGE_MAX_CONCURRENT_JOBS` merges in progress with an elapsed time > `settings.OPTIMIZE_MERGE_MIN_ELAPSED_CUTTOFF_TIME`. These are merges that we consider long running and should …

feat(optimize): track merge state

---

snuba/cli/consumer.py
snuba/consumers/consumer_builder.py

This PR:
- Removes the shared default producer code in the consumer
- Instead, creates a replacements-specific producer and a commit log-specific producer in the respective locations 
- Having dedicated producers is also more similar to how the Multistorage Consumer creates producers (in `snuba/cli/multistorage_consumer.py`). 
This change is not associated with any particular JIRA ticket, but was something I noticed while working on https://github.com/getsentry/snuba/pull/3301.

fix(consumer): Remove shared producers in consumer

---

snuba/migrations/runner.py
tests/migrations/test_runner.py

**context**
A while back I added an endpoint to get a list of groups and their migration ids https://github.com/getsentry/snuba/pull/3227. What we really want is the status along with the migration ids in addition to information on what migrations can actually be run/reversed.
Right now `show_all()` gets the status for all migration groups, but we want to isolate migration groups based on user permissions. The `migrations/groups/` endpoint should only show you groups you have access to, so I've added the option to get the status for a select amount of groups. 
This will allow us to add to the `migrations/groups` endpoint to do things like:
* check whether the migrations can be run or reversed (e.g. already run migrations can't be run again, migrations cant be reversed if there is a …

ref(migrations): Show all for a specific groups

---

snuba/migrations/connect.py

We run custom built ClickHouse and snuba migration command fails with error:
```
File "/usr/src/snuba/snuba/cli/migrations.py", line 66, in migrate
check_clickhouse_connections()
File "/usr/src/snuba/snuba/migrations/connect.py", line 30, in check_clickhouse_connections
check_clickhouse(clickhouse)
File "/usr/src/snuba/snuba/migrations/connect.py", line 55, in check_clickhouse
raise InvalidClickhouseVersion(
snuba.migrations.errors.InvalidClickhouseVersion: Snuba requires Clickhouse version 20.3.9.70 (<REDACTED> - 21.8.10.19-lts-a382a48cdc5)
```
```
>>> version.parse("21.8.10.19-lts-a382a48cdc5") < version.parse("20.3.9.70")
True
>>> version.parse("21.8.10.19") < version.parse("20.3.9.70")
False
```
Current ClickHouse version check replaces the custom version strings.
This commit makes …

Fix ClickHouse version check

---

snuba/datasets/storage.py

For a sliced storage, this function would return the wrong cluster unless we pass the slice_id along. Defaults to None for backward compatibility - not everything is slice aware yet.

feat: Pass the slice_id to storage.get_cluster()

---

.github/workflows/ci.yml
Makefile
snuba/cli/__init__.py
snuba/core/initialize.py
snuba/datasets/factory.py
test_initialization/test_initialize.py

This is mostly the same as #3311 with the only difference being the name transformation
if you have a click command like this:
```python3
@click.command
def my_command():
pass
```
it will be accessible in the cli as `my-command`. #3311 naively expected it to be `my_command`. 
This PR fixes that and adds a comment explaining why it's important
Today I remembered about the `snuba devserver` command which starts up everything with the correct names. If I had done that initially I wouldn't have had to revert.
With this change, `snuba devserver` starts up properly (before it did not)

Explicitly initialize snuba take 2

---

snuba/admin/migrations_policies.py
snuba/admin/views.py
snuba/migrations/policies.py
snuba/settings/__init__.py
tests/admin/clickhouse_migrations/test_api.py

Makes the migration policy checking middleware in snuba admin. The middleware gets the migration group policy from the settings map then runs `can_run` / `can_reverese` to if the migration key is allowed to run.

Add migration policy middleware SNS-1776

---

snuba/migrations/migration.py
tests/migrations/test_operations.py

Allow migrations to specify if they want to execute the local ops before distributed ops for run and reverse. This is the first PR in a change in migrations to better handle the order of operations to avoid getting into an inconsistent state.
**Context**
There are certain SQL ops that must be applied to the distributed tables before local tables and vice versa. Right now, our migrations always run local first and this leads to errors.  By introducing the local_first flag, creaters of migrations can specify the correct order.  The follow up to this PR will include a best effort checker that will run test to check that the order specified is consistent with the SQL ops in the migration and will not cause errors.
**Blast Radius**
Migrations Base Class
**Before**
All migrations run local ops …

ref (migrations): allow specifying order in migrations  SNS-1816

---

snuba/datasets/processors/querylog_processor.py
tests/datasets/test_querylog_processor.py

A negative project ID got into the querylog processor which was causing
Clickhouse writer failures downstream. Skip and log messages with negative
project IDs for now.
References INC-251

fix: Skip negative project IDs in querylog processor

---

snuba/datasets/processors/replays_processor.py
tests/datasets/test_replays_processor.py

closes: https://github.com/getsentry/replay-backend/issues/192
This will be the first in a series of refactors to the replays processor.  The goal is to address the issues raised by INC-250 and to add preventative safety measures.

feat(replays): Add additional parsing safety to string column types

---

snuba/cli/multistorage_consumer.py
snuba/consumers/consumer.py
tests/test_consumer.py

Currently the multistorage consumer completely ignores the policy defined on the storage itself and just applies it's own policy which produces the message to a topic. This is wrong and also different to how the main consumer works where the policy defined on the storage is the one that is used. It was also applied on a different part of the pipeline (only wraps the collector step). This also means the collector implementation was inconsistent in the two consumer variants.
When this hack was first introduced, it's likely there were practical reasons we needed this at Sentry, but since this particular code path (multistorage consumer with dlq) is never used today, those obviously don't exist anymore.
This is a step on the path to folding the multistorage consumer into the main consumer and …

feat: Make multistorage consumer dlq respect the policy defined

---

snuba/consumers/consumer.py

Previously this used the producer configuration from the default topic. If this happened to not be the same cluster as the replacements topic this wouldn't work. Now, it doesn't matter which cluster the replacement topic is on, the right producer configuration will be built.

fix: Fix the multistorage replacements producer Kafka configuration

---

snuba/clusters/cluster.py
snuba/web/views.py

- Closes [SNS-1740](https://getsentry.atlassian.net/browse/SNS-1740)
- This PR introduces a new `healthcheck_failed` metric for non 200 responses in the Snuba API `/health` route
- The metric also records a couple relevant booleans as tags
As far as Clickhouse goes, I believe we are already logging the errors on health check:
https://github.com/getsentry/snuba/blob/ed5cbef9086204cbd5dc105a4a69091f96080ba6/snuba/web/views.py#L155-L164
We can check Sentry/GCP logs for when we see a failed health check where `clickhouse_ok` is `False`

feat(api): Snuba healthcheck observability

---

snuba/datasets/processors/replays_processor.py
tests/datasets/test_replays_processor.py

closes: https://github.com/getsentry/replay-backend/issues/194
- Add upper limit to the number of tags accepted per request.
- Enforces non-null string keys.
- Enforces nullable string values.
- Preserves duplicate tag keys (supported by the replays product).
- Skips (instead of erring on) malformed tag tuples.

feat(replays): Add additional safety to tags processor

---

snuba/datasets/processors/querylog_processor.py
tests/datasets/test_querylog_processor.py

In order to mitigate an incident with a negative project id in a query, we simply would discard that query from the querylog. 
This PR just takes those negative ids out of the field to be inserted but keeps the rest of the query intact

fix(querylog): filter out negative project ids instead of rejecting the whole query

---

snuba/state/rate_limit.py
tests/state/test_rate_limit.py

step to repro leak:
1) add set items, but do not explicitly remove them. possible by killing
processes while a query is running
2) stop processing requests for a particular bucket. possible by
deleting a project that receives queries. we maintain sets of open
requests per-project, using https://github.com/getsentry/snuba/blob/a9ef6c56594246d0182a2b07728d1446a10e881b/snuba/query/processors/logical/object_id_rate_limiter.py#L19
without 1), we would be deleting set items explicitly on context manager
exit. Empty sets are equivalent to deleted keys in Redis.
without 2), we would have an extremely limited number of possible values
for `bucket`, so the issue is practically nonexistent. but since we
maintain sets per "object id" it's possible for a user to produce new
redis keys without ttl by …

fix(rate_limit): Set explicit TTL for set of open requests [SNS-1864]

---

snuba/datasets/processors/replays_processor.py
tests/datasets/test_replays_processor.py

@evanh This fixes an oversight in my previous pull request.  Tag values can not be null in our schema.
ref: https://github.com/getsentry/snuba/pull/3354

bug(replays): Tag keys and values may not be null

---

snuba/admin/clickhouse/querylog.py

Currently we cannot do a query like this in the admin tool because `clikhouse_queries` is not an allowed table to query
```sql
SELECT
toStartOfTenMinutes(timestamp) AS time,
COUNT(clickhouse_queries.is_duplicate) as dup_count,
SUM(duration_ms) as duration_sum
FROM
querylog_local
ARRAY JOIN
clickhouse_queries <--- rejected by tool
WHERE
(timestamp > (now() - (3600 * 5))) AND
status = 'error' AND
clickhouse_queries.is_duplicate = 1
GROUP BY
time
ORDER BY 
time ASC
LIMIT 1 BY time
```

fix(admin): Allow ARRAY JOIN with clickhouse_queries in admin

---

snuba/datasets/processors/replays_processor.py
tests/datasets/test_replays_processor.py

closes: https://github.com/getsentry/replay-backend/issues/193
- Strictly collapses integers or errs.
- Generates timezone aware datetimes from integer timestamps.
- Defaults to timezone aware utc now.
- Adds missing key safety for default-able fields.

feat(replays): Add additional parsing safety to integer and datetime column types

---

snuba/cli/__init__.py
snuba/core/initialize.py
snuba/web/wsgi.py
test_initialization/test_initialize.py

- When uWSGI starts a new Snuba API process, it simply starts the Flask app
- This is a problem as the first query which hits this new process will force Snuba to load all datasets/entities/storages from config before the query can be executed
- This is causing timeouts as queries which normally take <1s will randomly take >5s to execute
- First query to any Snuba API process loads all datasets
- Datasets are loaded before the Snuba API is declared "ready" by uWSGI
- Snuba API
- Initialization is more explicit once again
- Tested locally to verify the old version forces datasets to load on first query and now it does not 👨‍🔬

fix(init): uWSGI Snuba API processes not initializing Snuba

---

snuba/datasets/processors/querylog_processor.py
snuba/datasets/storages/querylog.py
tests/datasets/test_querylog_processor.py

We need to have bytes_scanned in the querylog consumer to better pinpoint api abuse. This is a prereq to #3360. 
The only other place this data is accessed is in the [attribution recording](https://github.com/getsentry/snuba/blob/master/snuba/querylog/__init__.py#L61). It may be useful to put it in a more visible place. I'm open to doing that but didn't want that to stop the PR

feat(abi-abuse): add bytes scanned to the querylog consumer

---

snuba/cli/consumer.py

Adds a slice_id tag to all metrics for a consumer if slice_id is present in the CLI flags. This doesn't change run-time behavior.
There is no way to distinguish metrics across slices without using host info
Consumers passed slice_id will report that as a tag to metrics, to allow for filtering

config(slicing) - add slice ID to emitted metrics tags

---

snuba/datasets/configuration/generic_metrics/storages/distributions.yaml
snuba/datasets/configuration/generic_metrics/storages/distributions_bucket.yaml
snuba/datasets/configuration/generic_metrics/storages/sets.yaml
snuba/datasets/configuration/generic_metrics/storages/sets_bucket.yaml
snuba/datasets/configuration/json_schema.py
snuba/datasets/configuration/transactions/entities/transactions.yaml
snuba/datasets/configuration/transactions/storages/transactions.yaml
snuba/datasets/configuration/utils.py
snuba/utils/schemas.py
tests/datasets/configuration/test_storage_loader.py

- Currently, the JSON Schema and Parser assume `Array` Column types will only have a `Float` or `UInt` inner type
- This was sufficient for many datasets but as we work on more configs, we need to add support for all types of Arrays
- This PR modifies the Array schema to now accept recursive inner types
- The validation limits this to up to 1 layer of recursion, eg `Array(Array(String()))`
- This is good enough as I haven't seen any instances of `Array(Array(Array(...)))`
- The parser technically has no limit, it supports as much recursion as needed but the validation will block this
- Updated JSON Schema
- Updated parser to support additional recursive inner types for Array
- Updated all existing configs with Array's to use the new format
- Modified `parse_columns()` function to split …

feat(DC): More inner types for Array

---

.github/workflows/ci.yml
.github/workflows/docs-pr.yml
.github/workflows/docs.yml
.github/workflows/release.yml

checkout v2 uses node12, which is going away. There's checkout v3 which shouldn't
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

use new checkout action to fix GHA warnings

---

snuba/migrations/groups.py
snuba/snuba_migrations/querylog/0004_add_bytes_scanned.py

The attribution log contains attribution for internal customers but not for sentry customers (no project_id in attribution log). We want to be able to analyze bytes scanned by sentry customers as well. Hence we need to add this column

MIGRATION: add bytes_scanned to querylog

---

snuba/datasets/storages/querylog.py

#3360 and #3375 have already been merged and the migration has been applied
Now all we need is the storage to reflect the table.

feat(querylog): add bytes_scanned column to querylog storage

---

snuba/migrations/operations.py
snuba/migrations/validator.py
snuba/snuba_migrations/events/0016_drop_legacy_events.py
snuba/snuba_migrations/profiles/0004_drop_profile_column.py
snuba/snuba_migrations/transactions/0014_transactions_remove_flattened_columns.py
tests/migrations/test_operations.py
tests/migrations/test_validator.py

Adds a script to validate the order of migration and introduce a test in CI that checks existing migrations
#3324 added the option to set flags to specify order, this PR introduces a checker to validate the specified order does not introduce errors. The checker uses the following spec:
1. For two `AddColumn` OPs with the same target table and target column, the local OP must be applied first
2. For two `CreateTable` OPs with the same target table name, the local OP must be applied first
3. For two `DropColumn` OPs with the same target table and target column, the dist OP must be applied first
The target table for distributed ops is then extracted either by looking at the engine attribute in the case of `CreateTable`, or by parsing the the local table name from the table engine in …

feat(migrations): add migration order validator SNS-1831

---

snuba/datasets/configuration/querylog/storages/querylog.yaml
tests/datasets/configuration/test_storage_loader.py

- Adding Querylog storage as a config
- Storage config was generated and tested using scripts from #3336 
- Any call to `get_storage(StorageKey.QUERYLOG)` will return the querylog storage built from config instead of the hardcoded version
- How config was generated:
- `python3 scripts/pystorage_2_yaml.py querylog querylog.yaml`
- Removed quotes around `columns` in schema, format yaml file with Prettier
- How config was tested:
- `python3 scripts/check_yaml_against_code.py querylog querylog.yaml`
- Updated `tests/datasets/configuration/test_storage_loader.py`

feat(DC): Querylog Storage as a Config

---

snuba/web/db_query.py
tests/web/test_db_query.py

The querylog is not writing `max_thread` to `stats`. When the query metadata message gets produced to querylog topic, it is missing `max_threads` key in its payload. This is caused by the introduction of applying thread quota to `clickhouse_query_settings`. 
* In `raw_query()` we pass `clickhouse_query_settings` and mutate its contents by reference. However, `_apply_thread_quota_to_clickhouse_query_settings` creates a new dictionary (with new memory address) and writes max_threads. As a result, the original  dictionary in the top level function does not contain `max_threads` key.
* Mutate the original dictionary
* The payload of Querylog messages
* Validated that `max_threads` is correctly passed through pipeline.
* Validate `max_threads` now exists in querylog Kafka message.

fix(api-abuse): Querylog receiving bad clickhouse_query_settings 

---

.freight.stable.yml
.freight.yml

The sessions infrastructure is being torn down and is no longer needed.

ref(deploys): remove sessions consumers

---

snuba/datasets/configuration/generic_metrics/entities/distributions.yaml
snuba/datasets/configuration/generic_metrics/entities/sets.yaml
snuba/datasets/configuration/generic_metrics/storages/distributions.yaml
snuba/datasets/configuration/generic_metrics/storages/sets.yaml
snuba/datasets/configuration/json_schema.py
snuba/datasets/configuration/utils.py
tests/datasets/configuration/broken_entity_bad_query_processor.yaml
tests/datasets/configuration/broken_entity_positional_validator_args.yaml
tests/datasets/configuration/test_storage_loader.py

- Currently, the JSON Schema and Parser treat the `AggregateFunction` column type's inner/arg types differently but they are themselves just `ColumnType`'s as well
- Updated the schema and parser to recursively parse arg types as ColumnType's
- Updated JSON Schema
- Updated parser to support additional arg types for AggregateFunction
- Updated all existing configs with AggFuncs to use the new format
- Dataset Configs
- As far as I know, the documentation surrounding JSON Schema _should_ auto update but I will do it manually if I'm wrong
- A lot of this PR is just my auto formatter 😅

feat(DC): Better AggregateFunction arg types

---

snuba/datasets/configuration/json_schema.py

ReadableStorage JSON schema has a bug. Currently, the `STORAGE_QUERY_PROCESSORS_SCHEMA` is used for query_processors, query_splitters, and mandatory_condition_checkers. This PR fixes and updates those fields to use their correct schemas.

fix(DC): Fix ReadableStorage Schema

---

snuba/datasets/storages/sessions.py
snuba/query/processors/physical/minute_resolution_processor.py

- `MinuteResolutionProcessor` seems to have been missed in #3160 
- Moved it to appropriate folder so it can be picked up by the registered class

fix(DC): Move missed ClickhouseQueryProcessor

---

snuba/cli/replacer.py
snuba/replacer.py

This moves the BatchProcessingStrategyFactory code into the snuba replacer since BatchProcessingStrategyFactory is being removed from Arroyo.

ref: Stop using BatchProcessingStrategyFactory from Arroyo

---

snuba/datasets/configuration/functions/storages/functions.yaml
snuba/datasets/configuration/functions/storages/functions_raw.yaml
tests/datasets/configuration/test_storage_loader.py

- Adding all Functions storages as a config
- Storage configs were generated and tested using scripts from #3336 
- Any call to `get_storage()` with a functions storage key will return the storage built from config instead of the hardcoded version
- How config was generated (eg functions_raw):
- `python3 scripts/pystorage_2_yaml.py functions_raw functions_raw.yaml`
- Removed quotes around `columns` in schema, format yaml file with Prettier
- How config was tested:
- `python3 scripts/check_yaml_against_code.py functions_raw functions_raw.yaml`
- Updated `tests/datasets/configuration/test_storage_loader.py`

feat(DC): Functions Storages as Config

---

.github/workflows/ci.yml

This is work as part of https://github.com/getsentry/self-hosted/issues/1756
Essentially, we want to move from Google Cloudbuild to a centralized Github Action that can be used across Sentry/Snuba/Relay/self-hosted. This adds a job which should use that action.

Add self-hosted Sentry end-to-end tests to CI using new Github action

---

requirements.txt

Updating arroyo. This should be a no-op for Snuba as we are not using any of the strategies that changed in this release.

feat: Arroyo 1.2.0

---

.github/workflows/ci.yml

The newer version does not push docker images for now so that won't fail.

Update end-to-end tests

---

snuba/cli/__init__.py
snuba/core/initialize.py

- Added a call to `setup_logging()` at the end of Snuba CLI init to reset log level back to `settings.LOG_LEVEL` ie INFO
- Removed extra snuba init log

fix(logging): Log level was always DEBUG

---

snuba/clickhouse/optimize/optimize.py

It became confusing tracking down what logs belong to which threads inside the optimize jobs. This adds the process id and thread id to the logs. Threads belonging to the same cron job will log with the same process id.

optimize: add thread and process info to logs

---

snuba/datasets/plans/sliced_storage.py
snuba/settings/__init__.py
tests/datasets/plans/test_sliced_storage.py

With slicing, logical partitions could be one of 2 states
1. All data resides on a single sliced clickhouse cluster.
2. Partial data resides in some other sliced clickhouse cluster. This would happen when the mapping of a logical partition to a slice is modified. When the mapping is changed, **writes** of new data will happen on the new slice on which the logical partition is mapped. But we do not perform data migration of the logical partition from older slice to newer slice. So **reads** need to query across both the old slice and the new slice.
The overall system would look something like this
A new runtime config is introduced to identify which logical partitions of a storage_set have should use the mega cluster. If a  query belongs to a logical partition which is set in the runtime …

feat(slicing): Mega cluster using runtime overrides

---

snuba/clickhouse/http.py

As suggested by reviewers in
https://github.com/getsentry/snuba/pull/3404, collect some metrics first
to see whether it is feasible to keep the batch in memory for better
error reports.

ref(metrics): Emit total HTTP batch byte size for each table [sns-1850]

---

snuba/datasets/processors/querylog_processor.py
tests/datasets/test_querylog_processor.py

The snuba querylog has a `duration_ms` which is the runtime of the entire snuba query. However, the runtime of the individual clickhouse query itself (time elapsed for Clickhouse to run a query on server) is not captured by querylog. This PR is responsible for adding this data to querylog.
Querylog always writes `0` in `clickhouse_queries.duration_ms`
Querylog writes the elapsed time to run the clickhouse query in `clickhouse_queries.duration_ms`
Tested locally to ensure messages produced to querylog topics are correct and contain accurate fields.

fix(api-abuse): Add duration_ms to individual queries in querylog

---

scripts/copy-tables.py

Example use case: replacing chalet with snuba-access-logs
Chalet had a special "clicktail" database, but snuba-access-logs could just use "default"
```
snuba/scripts on  SNS-1753-support-different-databases [?] via 🐍 v3.10.6 (.venv) on ☁️  michael@sentry.io(us-central1)
❯ ./copy-tables.py --source-host 192.168.208.151 --target-host 192.168.208.204 --source-database clicktail --target-database default
Replicated Table Check:
...looking up macros
...found replica: chalet for shard: 0
...verifying zk replica path for table: access_log...
...zookeeper replica paths verified for table: access_log ! :)
Mismatched databases.. Replacing: clicktail.access_log with default.access_log
creating access_log... on replica: snuba-access-logs-1-1, shard: 1, database: default
create table statement: …
```

SNS-1753: support different source/target databases

---

snuba/admin/static/clickhouse_migrations/index.tsx

Run real migrations and refresh the status table in the UI. Previously we were only running dry runs.

admin: run/reverse real migrations

---

snuba/cli/subscriptions_executor.py
snuba/subscriptions/executor_consumer.py
tests/subscriptions/test_executor_consumer.py

This PR contains the changes necessary for slicing, at the level of subscription executors. Namely, we want to:
- Pass in `slice_id` optionally to the executor CLI
- Ensure that, when a `slice_id` is passed, the executor consumes from the "sliced" (physical) scheduled topic. These topics should be defined in slicing settings (`settings.SLICED_KAFKA_TOPIC_MAP`). Note that the result topic is not sliced, i.e. we use the common default across slices. 
- If no `slice_id` is passed, we should observe default behavior and the default scheduled and result topics should be used.
This work will synchronize with the slicing changes added to the subscriptions scheduler, once those are ready

feat(slicing): Introduce slicing into Subscriptions Executor

---

snuba/datasets/configuration/generic_metrics/storages/distributions.yaml
snuba/datasets/configuration/generic_metrics/storages/distributions_bucket.yaml
snuba/datasets/configuration/generic_metrics/storages/sets.yaml
snuba/datasets/configuration/generic_metrics/storages/sets_bucket.yaml

- Generic metrics configs were manually created
- Redid them using the script to make them consistent with other configs
- This changes the "name" field in the gen metrics

ref(DC): Generic Metrics storages from Script

---

snuba/datasets/processors/querylog_processor.py
tests/datasets/test_querylog_processor.py

The original PR with details is specified here: https://github.com/getsentry/snuba/pull/3432. That PR was reverted due to a typing error in `duration_ms`.
This PR includes the bug fix which casts the `duration_ms` to an `int` type. The consumer and batch writer was tested locally and validated.

fix(api-abuse): Add duration_ms to individual queries in querylog [with bug fix]

---

snuba/migrations/groups.py
snuba/settings/__init__.py

It was a bit confusing to me why we had both `OPTIONAL_GROUPS` and `SKIPPED_MIGRATION_GROUPS`. 
There is nothing stopping someone from adding groups to `SKIPPED_MIGRATION_GROUPS` that don't exist in `OPTIONAL_GROUPS`, it just means that it won't actually skip it. And there is no messaging that would let someone know it wasn't skipped (or why).

Add clarification about optional and skipped migration groups

---

snuba/migrations/migration.py
snuba/migrations/operations.py
tests/migrations/test_operations.py

A precursor to #3399 . This adds the target enum to specify which nodes to run an op on.
The runner would pass in the local flag to let an op know which nodes to run on
Ops take in the target enum as a parameter. When executing ops already know what nodes to target. By default, the target enum is set to "unset" and will throw an error if the user does not explicitly set it.

ref(migrations): add migration target enum

---

snuba/migrations/columns.py
tests/migrations/test_operations.py

Currently the only way to specify a TTL for a specific column in a table is to
have a ModifyColumn migration to add the TTL after the table is created. It
should also be possible to specify those TTLs in the create table however.
Before:
There was no TTL modifier for a Column, so a ModifyColumn migration had to run
in order to add a TTL to a specific column.
After:
There is now a TTL modifier that can specify a custom TTL expression on a column

feat(migrations): Allow TTL clause on columns in migrations

---

snuba/redis.py
snuba/settings/__init__.py
snuba/settings/settings_test.py
snuba/state/cache/redis/backend.py
snuba/state/rate_limit.py
snuba/web/db_query.py
tests/state/test_cache.py
tests/state/test_rate_limit.py

This requires https://github.com/getsentry/ops/pull/5682 to be deployed
first.
We have successfully moved all traffic to the new clusters, so we can:
1. point the old, now unused logical cluster to the same physical resource (ops PR)
2. change the code to start using the old logical (v1) cluster again and
remove v2 (this PR)

ref(redis): Clean up code after cluster migration [sns-1899]

---

.gitignore

vscode was creating log files like:
configurationCache.log
dryrun.log
targets.log

chore: ignore .vscode log files

---

snuba/consumers/consumer.py
snuba/consumers/consumer_builder.py
snuba/consumers/strategy_factory.py
snuba/web/views.py

This brings code from Arroyo (https://github.com/getsentry/arroyo/blob/fce2952fba90ff7a757ed3ab5f466e16d5fbf66b/arroyo/processing/strategies/factory.py) into Snuba.
The file is copied as-is, there are no changes.
This strategy factory was highly specific to Snuba's use case and will be removed in a future version of arroyo.

feat: Move the ConsumerStrategyFactory to Snuba

---

snuba/cli/__init__.py

- Should use `timing` instead of `gauge` for a timing metric

fix(init): Snuba init timing metric

---

snuba/migrations/migration.py
snuba/migrations/operations.py
snuba/migrations/runner.py
snuba/migrations/validator.py
tests/migrations/test_operations.py
tests/migrations/test_validator.py

Refactors migrations to use a singe sequence of operations, rather having the user specify operations in `_dist()` and `_local()`.
To avoid ordering errors in migrations we refactor them to be a single sequence. The user no longer has to specify the order flags for the whole migration. Instead, each SQL operation takes a target flag specifying if it should run on local or dist. To make a node migration, the user has to only implement `forwards_ops()` and `backwards_ops()`. This removes the limitation of having the user dump all their ops in either `_dist()` or `_local()` methods and executing one before the other. Now the user has complete control of when their operations can execute.
To avoid errors introduced by giving the user more power, we use a validator that runs unit tests against …

ref(migrations): make migration use single ordered sequence SNS-1830

---

snuba/querylog/query_metadata.py
snuba/web/db_query.py

Add a new query status for timeouts so we can track them separately in DD. This
will require changing existing graphs in DD to handle the new status type.
Nothing will change in the graphs themselves, so the SLO remains the same. Now
the failed queries will be defined as error + timeout.
I looked into the possibility of creating a new metric with the new status and
keeping the old metric with the old status codes. That would have required
having two Timer objects and doing some Python trickery to overwrite the Timer
name. It seemed easier to update the graphs in DD.

ref(SLO) Track timeouts with a different status from errors

---

snuba/utils/metrics/backends/abstract.py
snuba/utils/metrics/backends/datadog.py
snuba/utils/metrics/backends/dummy.py
snuba/utils/metrics/backends/testing.py
snuba/utils/metrics/wrapper.py
tests/backends/metrics.py

Allows the datadog backend to send events. This is useful for setups where we may want to trigger alerts in datadog based on events.

Add datadog events

---

snuba/datasets/storages/discover.py
snuba/query/processors/physical/null_column_caster.py
tests/query/processors/test_null_column_caster.py

Discover is the only merge table storage in snuba, which makes it a special case that haunts us forever. One of the ways it haunts us is with the NullColumnCaster, which needs to understand the mismatched null columns. For more info on the null column caster see #2144. 
When the storages are defined in config, and not as python objects, passing the storages into the init constructor does not work.
```python3
import my_storage_object_1
import my_storage_object_2
NullColumnCaster([my_storage_object_1, my_storage_object_2])
```
```python3
import my_storage_object_1
import my_storage_object_2
caster = NullColumnCaster([my_storage_object_1, my_storage_object_2])
caster.process_query(my_query)
```
* Discover dataset queries
* NullColumnCaster query processor

fix(DAC): allow NullColumnCaster to be referenced from config

---

snuba/admin/views.py
snuba/clickhouse/optimize/optimize.py
snuba/settings/__init__.py
tests/clickhouse/optimize/test_optimize_tracker.py

Adds a monitor thread that sends an alert to datadog if the optimize cron job runner is taking longer than `OPTIMIZE_ALERT_THRESHOLD`. 
Additionally, switches logging to structlog so that log severity is recognized by GCP.

feat(optimize): Add datadog alert event on optimize SNS-1841

---

snuba/admin/views.py
snuba/clickhouse/optimize/optimize.py
snuba/settings/__init__.py
tests/clickhouse/optimize/test_optimize_tracker.py

Reverts getsentry/snuba#3416
This is causing an incident as it replaces the standard python logger with the struct log. 
Structlog does not allow this type of logging:
```
logger.info("Cutoff time: %s", str(cutoff_time))
```
Which is used in several places in the optimize job.

Revert "feat(optimize): Add datadog alert event on optimize SNS-1841"

---

snuba/datasets/errors_replacer.py
snuba/datasets/storages/errors.py
snuba/datasets/storages/errors_common.py
snuba/query/processors/physical/replaced_groups.py

Replacer state is an argument in the errors configuration but we don't want it to be an enum since that's not configurable in yaml. Convert it to an enum inside the init function of the replacer and the PostReplacementConsistencyEnforcer
Only the errors dataset is affected, there are no other replacement states defined in the codebase.

feat(DAC): make replacer state a string in storage definition

---

docs/source/architecture/slicing.rst
snuba/consumers/consumer_builder.py
snuba/datasets/plans/sliced_storage.py
snuba/datasets/pluggable_entity.py
snuba/datasets/slicing.py
snuba/settings/__init__.py
snuba/settings/validation.py
tests/datasets/plans/test_sliced_storage.py
tests/settings/test_settings.py

As per design, slicing occurs at the level of storage set. However, this wasn't reflected entirely in slicing-related code changes, in slicing config, and in further usages. This PR attempts to do small refactors and renamings to make it clear that slicing indeed occurs by storage sets, not storages. Docs are and will continue to update accordingly to reflect this.

ref(slicing): Make Storage Set the level of Slicing

---

snuba/datasets/configuration/outcomes/storages/hourly.yaml
snuba/datasets/configuration/outcomes/storages/raw.yaml
tests/datasets/configuration/test_storage_loader.py

- Adding Outcomes storages as a config
- Storage config were generated and tested using scripts from #3336 
- Any call to `get_storage()` with an outcomes storage key will return the storage built from config instead of the hardcoded version
- How config was generated (eg outcomes_raw):
- `python3 scripts/pystorage_2_yaml.py outcomes_raw raw.yaml`
- Removed quotes around `columns` in schema, format yaml file with Prettier
- How config was tested:
- `python3 scripts/check_yaml_against_code.py outcomes_raw raw.yaml`
- Updated `tests/datasets/configuration/test_storage_loader.py`

feat(DC): Outcomes Storages as a Config

---

snuba/datasets/cdc/cdcprocessors.py
snuba/datasets/configuration/storage_builder.py

- CDC Message Processors do not inherit `DatasetMessageProcessor`
- They do inherit from another type `CdcProcessor`
- This class needs to be registered in order for CDC configs to be parsed correctly and have the message processor picked up

feat(DC): CDC Processors Registered

---

snuba/admin/clickhouse/predefined_querylog_queries.py

Add two new queries to help narrow down with referrers might be causing the
abuse. To use these queries you should already know which cluster is
experiencing the abuse, and at what time the abuse started.
The idea behind the queries is: take half an hour before the abuse started, and
half an hour after. Compare the referrers between those two time periods, and
surface the ones that had the highest percentage change from before to after.
The purpose of these is not to automatically find the smoking gun, but to at
least remove some of the noise and show some actionable signal that can be
followed up on to confirm if one of the referrers actually is the source of
the problem.
I tested these queries on some known cases of abuse, and they did surface the
referrers that turned out to be the …

ref(abuse) Add more predefined querylog queries

---

snuba/clickhouse/translators/snuba/allowed.py
snuba/datasets/entities/discover.py

Discover defines translation mappers in its entity file. this makes it impossible to convert it to config. The mappers have to be with all the other ones so they can be references in config
The discover dataset model definition. No other entities use these classes

ref(DC): move discover mappers with all the other mappers

---

snuba/cli/optimize.py

Increase optimize reddis TTL  by 1 hr passed job cuttoff time to avoid keys expiring same time as cuttoff.

Increase optimize redis TTL 

---

snuba/datasets/configuration/discover/storages/discover.yaml
tests/datasets/configuration/test_storage_loader.py

- Adding Discover storage as a config
- Storage config were generated and tested using scripts from #3336 
- Any call to `get_storage()` with a discover storage key will return the storage built from config instead of the hardcoded version
- How config was generated:
- `python3 scripts/pystorage_2_yaml.py discover discover.yaml`
- Removed quotes around `columns` in schema, format yaml file with Prettier
- How config was tested:
- `python3 scripts/check_yaml_against_code.py discover discover.yaml`
- Updated `tests/datasets/configuration/test_storage_loader.py`

feat(DC): Discover Storage as a Config

---

scripts/copy-tables.py

**context:**
Similar to https://github.com/getsentry/snuba/pull/3174 except that this script is independent of Snuba dependencies. The reason for adding this would be so that this script could be used by ops easily without having to run the snuba cli commands.
```shell
(.venv) ✔ ~/snuba [meredith/SNS-1753|⚑ 121]
17:20 $ python scripts/copy-tables.py --table=generic_metric_sets_aggregation_mv,generic_metric_distributions_aggregation_mv --source-host=localhost --target-host=localhost
Materialized View Check:
...checking table statement: generic_metric_sets_aggregation_mv
...looking for local tables: generic_metric_sets_local, generic_metric_sets_raw_local
...local tables found, mv check complete !
Materialized View Check:
...checking table statement: …
```

ref(migrations): add copy-tables script

---

snuba/admin/audit_log/action.py
snuba/admin/notifications/slack/utils.py
snuba/admin/views.py

Originally was going to just switch where we put the audit log statements (in https://github.com/getsentry/snuba/pull/3492) but instead decided to split out `started` and `completed`. 
This way we have an audit of who ran something, even if it failed, and we only need to get notifications when something was completed. In the future if we wanted to have notifications on failure we could easily update the code to do so.

ref(admin): split started/completed audit migrations

---

snuba/migrations/groups.py
snuba/migrations/migration.py
snuba/settings/__init__.py
snuba/snuba_migrations/test_migration/0001_create_test_table.py
snuba/snuba_migrations/test_migration/0002_add_test_col.py
tests/cli/optimize.py
tests/migrations/test_validator.py

Add a simple test migration. This migration creates an empty table in the querylog storage set and adds a column to it. We can use this to test migrations tool on a real cluster.

Add test migration

---

snuba/admin/notifications/slack/client.py
snuba/admin/notifications/slack/utils.py
snuba/admin/views.py

Found some minor things while I was testing this out for a demo:
* we should be returning early if we get an exception from Slack, otherwise we hit a `KeyError`
* ~we should be run/reversing migrations before we do the audit log, because otherwise we will create an audit log record even if we failed (and the audit log doesn't show that something failed)~ addressing in https://github.com/getsentry/snuba/pull/3493
* personal preference but I just updated the emojis to be 👟 and 🔙 , the :uno-reverse: is a custom slack emoji so just wanted something more generic and I got annoyed that the running person 🏃 looked like they were running backwards and not forwards lol

ref(admin): minor migrations audit log fixes

---

snuba/datasets/errors_replacer.py
snuba/datasets/storage.py
snuba/datasets/storages/errors.py
snuba/replacers/replacer_processor.py

- ReplacerProcessor currently requires a schema as an init param
- This makes the config representation of the errors storage very messy since it will first define the schema as the storage param and then once again for the processor
- Moved schema initialization into a new method which basically does what was done on init before, but runs later (once all storages are built)
- The parent storage key is passed to the processor instead of the schema
- This method would be called on the first process_message() or get_schema() call of the processor to initialize the schema

ref(replacements): Refactor Schema out of ReplacerProcessor init

---

snuba/admin/audit_log/base.py
tests/admin/test_querylog_audit_log.py

The logger in `AuditLog` wasn't configured properly and was lazy so it was ignored in k8s. Adding bind to force it to configure properly and add the processors.

fix(admin): bind log to configure it before using

---

snuba/admin/views.py

Follow up to #3503 
Previously we were redirecting all stdout to a user buffer and returning it as json response. This meant that logging wasn't going to stdout. This fix will `tee` output to both the user buffer and `stdout`.
Ultimately, this redirecting should probably be replaced by returning proper info to the caller once we figure out what the appropriate endpoint response should be.

fix(admin): capture migration output on stdout 

---

snuba/consumers/consumer_builder.py
snuba/consumers/strategy_factory.py
tests/consumers/test_strategy_factory.py

The ``KafkaConsumerWithCommitLog`` was a huge hack that essentially moved what should be part of the processing strategy logic (produce and commit) into the consumer code instead to be executed post strategy.
The main issue with this (in addition to be a bit against the library's design) is that it required a big change to Arroyo's interface to support - instead of committing simply an offset and it's partition, we need to now pass the original message timestamp all the way through the commit interface unnecessarily.... just because of this consumer. This makes every other consumer (where committing never needs the timestamp) more complicated.
This is the first step towards deprecating the commit log consumer, and simplifying committing offsets in Arroyo. It removes the …

ref: Rewrite the KafkaConsumerWithCommitLog as a strategy

---

snuba/datasets/replacements/errors_replacer.py
snuba/datasets/replacements/projects_query_flags.py
snuba/datasets/storages/errors.py
snuba/query/processors/physical/replaced_groups.py
snuba/replacer.py
tests/datasets/storages/processors/test_replaced_groups.py
tests/datasets/test_errors_replacer.py
tests/replacer/test_cluster_replacements.py
tests/test_replacer.py

- `ProjectsQueryFlags` is a huge class and concept, and although tied to the errors_replacer, it should probably reside in its own module and not `errors_replacer.py`
- Also, it seems strange that `errors_replacer.py` resides in the main `snuba/datasets/` directory while the `snuba/datasets/replacements/` directory is empty, and the replacer isn't a dataset
- Moved `errors_replacer.py` into that directory and created a new file for `ProjectsQueryFlags` in the same directory
For context, `ProjectsQueryFlags` is the abstraction we use on top of Redis to handle setting and getting replacement data for projects.

ref(replacements): Move ProjectsQueryFlags out of errors_replacer

---

snuba/cli/replacer.py
snuba/replacer.py

The Batch processing strategy / Abstract batch worker classes are getting deprecated from Arroyo. The Snuba replacer use case does not really even benefit from batch processing since we execute one message at a time. This change swaps in RunTask instead of BatchProcessingStep. I did not make any major changes to the ReplacerWorker code yet, but it could be tackled as a follow up.

ref: Rewrite Snuba replacer to not use batch processing strategy

---

snuba/datasets/configuration/json_schema.py
snuba/datasets/configuration/storage_builder.py
snuba/replacers/replacer_processor.py
tests/datasets/configuration/test_storage_loader.py

Support for `replacer_processor` argument of `WritableTableStorage` requires a couple updates to DC stuff:
- `ReplacerProcessor` needs to be a `RegisteredClass`
- Assigning the metaclass `RegisteredClass` enables a class to be referenced by name
- This is required in order for Errors config to be parsed correctly and have the replacer processor picked up
- JSON Schema for Storage needs to be updated to accept `replacer_processor` param
- `storage_builder` needs to be updated to build a storage with a ReplacerProcessor if defined in a config

feat(DC): ReplacerProcessor Registered + JSON Schema'd + Built

---

docker-compose.gcb.yml

Some of the tests were overwriting each others coverage files. This fix renames the coverage paths to give each tests its own coverage file.

fix coverage paths

---

snuba/admin/clickhouse/nodes.py
snuba/admin/static/clickhouse_queries/query_display.tsx
snuba/admin/static/clickhouse_queries/types.tsx
test_distributed_migrations/conftest.py
test_distributed_migrations/test_get_nodes.py

The dist nodes do not show up as hosts for the system queries tab. This usually isn't an issue locally because the dist hosts are the same a local hosts, but for distributed setups where the two are different, it means we cant run system queries on the dist hosts.
The system queries tab would only show local hosts
The system queries tab shows dist hosts if they are not already included in the local hosts
Frontend JSX and `/clickhouse_nodes` admin endpoint.

feat(admin): Show dist nodes hosts

---

snuba/consumers/consumer.py
snuba/consumers/consumer_builder.py

Another take at killing the KafkaConsumerWithCommitLog. This implementation moves the part that produces offsets to the commit log topic into the collect step.
For context, the previous take on it was https://github.com/getsentry/snuba/pull/3511/ but this other approach doesn't work well. Since Collect/ParallelCollect does not pass any output to the next step, it must be done within this processing step itself.
This change is needed as Arroyo will no longer pass message timestamps through to the commit callback function via `Position`. It is wasteful, affects performance and only existed to support this particular use case (writing part of the strategy logic in the consumer) which is not really a valid one.

feat: Deprecate the KafkaConsumerWithCommitLog

---

snuba/consumers/consumer.py
snuba/consumers/consumer_builder.py

This reverts commit 2f2a10ca7024557fbb4a6aa3e3783fc89bba9d28.
This caused a memory leak in the consumer

Revert "feat: Deprecate the KafkaConsumerWithCommitLog (#3523)"

---

snuba/datasets/processors/search_issues_processor.py
tests/datasets/test_search_issues_processor.py
tests/test_search_issues_api.py

We don't pass `group_ids` for occurrences. Fixing the processor to expect `group_id`, and also to write the `event_id` to the table.

fix(issue-platform): Fix `search_issues_processor` to handle event_id and group_id

---

snuba/settings/__init__.py

This PR is mostly needed as a stop-gap since we don't have the production infra setup yet for the table yet, but we still want to be able to reference the dataset in sentry CI and dev.

feat(migration): conditionally auto-run migration based on env var

---

snuba/subscriptions/scheduler_consumer.py
tests/subscriptions/test_scheduler_consumer.py

We had an incident at Sentry (inc-276) caused by the fact that there was an offset/timestamps in the incorrect order in one of the consumers. We are supposed to be catching and ignoring these in the subscriptions scheduler.
We were already handling invalid time intervals, but we forgot to include handling for invalid offset intervals.

feat: Skip invalid offset ranges

---

snuba/consumers/consumer.py
snuba/consumers/consumer_builder.py

Same as https://github.com/getsentry/snuba/pull/3523 but with the `producer.poll(0.0)` call between each message submitted.
This was being called in the original KafkaConsumerWithCommitLog here (https://github.com/getsentry/snuba/blob/9b91174bd9a2d55761c510e934ceeabb096a528a/snuba/utils/streams/kafka_consumer_with_commit_log.py#L32) but was dropped in the previous version of this PR which converted this logic to the strategy.
Poll is required when using the Confluent producer directly in order to poll the producer for events and fire delivery callbacks.
We should merge https://github.com/getsentry/snuba/pull/3530 before this. On the off chance that another out of order message makes its way to one of the commit log topics, we don't want to cause another incident.

feat: Refactor the Kafka consumer with commit log (again)

---

snuba/attribution/log.py
snuba/query/query_settings.py
snuba/querylog/__init__.py
snuba/request/schema.py
tests/subscriptions/entity_subscriptions/test_entity_subscriptions_data.py
tests/test_snql_api.py

The parent_api metric can be useful to see which feature has spiked in abuse,
since one feature can call many referrers and make it harder to see changes in
traffic usage.
This metric was removed in the past because we found cases of the endpoint not
being correct. Referrers were attached to endpoints that didn't actually call
the referrer. However the Sentry SDK has improved quite a bit since then and
even if the endpoint is not correct, it can still be useful signal of a problem.

ref(abuse) Add the parent_api back to the metrics

---

snuba/datasets/configuration/discover/storages/discover.yaml
snuba/datasets/configuration/json_schema.py
snuba/datasets/configuration/storage_builder.py
tests/datasets/configuration/test_storage_loader.py

- Dataset Config doesn't support the `mandatory_conditions` field in storages
- This is currently only used to modify queries to certain storages so that they don't respond with deleted entries
- This is necessary for Errors (and Discover ❗)

feat(DC): Deleted Column mandatory condition

---

snuba/consumers/consumer.py

We need to ensure the producer is flushed during the consumer shutdown process.This fix flushes the commit log producer on each batch. It does add a blocking operation on each batch. Ideally it would only be performed when the consumer is actually shutting down but the current design of the consumer (and use of the CollectStep) does not allow us to easily hook into that. Given the size of batches is fairly large, i think this flush is non problematic.
This is a fix for SNUBA-30Y firing during deployment.

fix: Ensure commit log producer is flushed

---

snuba/cli/__init__.py

I have a suspicion that the sentry sdk and click are interacting in weird ways. Try this to see if the transaction is labeled properly

fix(init): don't return in the with block

---

snuba/admin/static/clickhouse_migrations/index.tsx

UI fixes to the migrations tool
1. Makes it clearer what the dry run buttons do
2. Only presents the EXECUTE buttons run/reverse immediately after user has just run the dry run. Reduces risk of user mistakenly clicking forwards run when they are looking at a dry run from reverse.
3. Show a success/fail alert.
https://user-images.githubusercontent.com/1960911/207752692-28f0cfc0-49c8-480f-89aa-61f6d5c0dc35.mov

migrations UI fixes

---

.github/workflows/ci.yml

This PR:
a) Pulls the snuba image from Google Cloud Build so that the images that are pushed can be scanned, and b) Enables pushing of the images to DockerHub, so that tests run in GCB can be replaced with the Github Action here

ci: Update self-hosted e2e to pull from GCB and push to DockerHub

---

snuba/consumers/consumer.py
tests/state/test_state.py

Removes the ability to skip Kafka messages via config. This functionality was never used, and shouldn't ever be (invalid messages should be handled via dlqs) not this mechanism.
The motivations to remove this are to:
- remove unnecessary complexity that is never used
- align the consumer and multistorage consumer implementations which will be merged together soon
- make it easier to provide a shared decoder/schema validator implementation for both single storage and multistorage consumer

ref: Remove "kafka_messages_to_skip" config

---

snuba/cli/consumer.py
snuba/cli/multistorage_consumer.py
snuba/cli/subscriptions_executor.py
snuba/consumers/consumer_builder.py
snuba/subscriptions/executor_consumer.py

Co-operative rebalancing never quite worked with the way we write our consumers and is not very compatible with Arroyo. Let's remove the option since we never want to run this.
Eventually we might want to try this again but will probably have to wait for https://cwiki.apache.org/confluence/display/KAFKA/KIP-848%3A+The+Next+Generation+of+the+Consumer+Rebalance+Protocol being implemented in Kafka which will be some time away.

feat(consumer): Remove the --cooperative-rebalancing option

---

.github/workflows/ci.yml
Dockerfile

Building the admin UI within the Arm64 docker image is very slow because GH use emulation. Changes to snuba/admin would invalidate the cache and trigger this slow building. This speeds up the CI by building the bundle.js outside of the docker image and copying the file into the container.

fix(admin): build bundle outside of arm64 image 

---

.github/workflows/ci.yml

Search issues migrations have to be enabled explicitly. This PR does that. Without it, CI breaks when running sentry tests against the snuba

fix(CI): autorun migrations in sentry CI

---

.github/workflows/ci.yml
Dockerfile

This reverts commit 37f40dc95058a09cf892c196af344059c78e05b8.
The optimization for building the bundle outside docker wasn't getting triggered sometimes. leaving it out for now.

Revert "build bundle outside of arm64 image (#3514)"

---

.github/workflows/ci.yml
.github/workflows/image.yml
Dockerfile

Follow up fixes to #3514 . Makes docker build the admin UI along with the image by default by using the `build_admin_ui` layer as the default base.  This fixes issues where the CI would mistakenly skip building the UI. 
Optionally, specifying the arg `BUILD_BASE=base`  will use the base layer without the UI. This is useful for steps like building the arm64 image where building the UI within the docker image can take a long time.

build bundle outside of arm64 image. attempt 2

---

snuba/settings/__init__.py

This is a follow up to https://github.com/getsentry/snuba/pull/3551. Since the default security.protocol is set to plaintext, default sasl.username, sasl.password and sasl.mechanism should all be None.

fix(settings): Fix SASL defaults

---

snuba/consumers/consumer.py
snuba/consumers/strategy_factory.py

The KafkaConusmerStrategyFactory is supposed to get deprecated. This change refactors the multistorage consumer to stop using it there. It also removes the need for the generic `ConsumerStrategyFactory` which previously needed to be generic so it could take a MultistorageKafkaPayload instead of a KafkaPayload in the multistorage scenario.
Soon we will be adding a new processing step for payload decoding and schema validation - this will happen between the DLQ and the rest of the message processing steps.
This refactor will make it easier to introduce the decoder/validator as it needs to happen in different places in the main consumer vs the multistorage consumer.

ref(multistorage-consumer): Stop using ConsumerStrategyFactory

---

snuba/cli/consumer.py
snuba/consumers/consumer.py
snuba/consumers/consumer_builder.py
snuba/consumers/schemas.py
snuba/web/views.py
tests/test_consumer.py

Same as https://github.com/getsentry/snuba/pull/3553 but instead of passing JsonCodec to the `process_message` function we are now passing the topic instead.
The previous implementation caused consumers to crash if multiprocessing was used (INC-279 / SNUBA-316) as JsonCodec cannot be pickled in order to pass to subprocesses. The new implementation loads the JsonCodec once in each subprocess and only passes the topic to the `process_message` function so the correct codec and schema can be loaded.

feat: Consumer schema validation, take 2

---

snuba/datasets/entities/factory.py
snuba/settings/__init__.py

Add a new config that lets us disable entity loading when we want to disable storage sets temporarily.
We want to remove the `cdc` and `sessions` storage sets for ops changes, but that causes the validation on EntityFactory loading to fail
```
File "/Users/oliver/workplace/snuba/snuba/datasets/schemas/tables.py", line 92, in get_table_name
if get_cluster(self.__storage_set_key).is_single_node()
File "/Users/oliver/workplace/snuba/snuba/clusters/cluster.py", line 482, in get_cluster
raise UndefinedClickhouseCluster(
snuba.clusters.cluster.UndefinedClickhouseCluster: StorageSetKey.CDC is not defined in the CLUSTERS setting for this environment
```
even if the dataset is in `DISABLED_DATASETS`. This is because initialize_snuba is loading entities first: …

feat(ops): allow disabled entities for storage sets that are not in use

---

snuba/datasets/configuration/issues/entities/search_issues.yaml
snuba/datasets/configuration/issues/storages/search_issues.yaml
snuba/datasets/processors/search_issues_processor.py
tests/datasets/test_search_issues_processor.py
tests/test_search_issues_api.py

This PR extracts additional field values from the event payload so it can be used for querying.

feat(issue-platform): process extra fields from event

---

.github/workflows/ci.yml

Picks up https://github.com/getsentry/action-self-hosted-e2e-tests/pull/3.

Pick up self-hosted CI bugfix

---

MIGRATIONS.md

update migrations doc to reflect new style

docs(migrations): SNS-1977 update migrations doc to reflect new style

---

snuba/clickhouse/translators/snuba/allowed.py
snuba/datasets/entities/discover.py

Dataset configuration doesn't support complex objects for registered classes
like this. In order for the discover entity to be migration to YAML, there needs
to be a different way to initialize this class that can be encoded in YAML.
This mapper is checking if a column name exists in the ColumnSet. That check
compares against the flattened column name stored in the ColumnSet. This can be
achieved by comparing to a normal set instead of a ColumnSet.
This should only concern anyone who works with the Discover entity. 
Also, nothing should change when this is merged.

fix: Change DefaultNoneColumnMapper to use a normal set

---

snuba/datasets/table_storage.py
snuba/settings/__init__.py

TOPIC_PARTITION_COUNTS configuration was unintuitive because (unlike all the other Kafka settings) it referenced the physical topic name and not the logical topic name.
This brings it in line with the way the other settings like KAFKA_TOPIC_MAP, KAFKA_BROKER_CONFIG, LOGICAL_PARTITION_MAPPING, etc, work.

feat: Change settings.TOPIC_PARTITION_COUNTS to use logical topic name

---

snuba/datasets/configuration/issues/storages/search_issues.yaml

Bumps `search_issues` storage `occurrence_type_id` int size from 6 to 12. Migration for this has already been merged https://github.com/getsentry/snuba/pull/3575

bump search_issues storage occurrence_type_id int size

---

snuba/datasets/configuration/entity_builder.py
snuba/datasets/configuration/json_schema.py
tests/datasets/configuration/entity_join_relationships.yaml
tests/datasets/configuration/test_entity_loader.py
tests/datasets/entities/test_entity_key.py

Add support to the schemas to allow entities to specify join relationships.
Also add a test for the join relationship parser.
Since CDC is a deprecated feature, there was a discussion about whether we should support joins in config, since CDC is the only user of them. But I don't think we want to eliminate support for joins entirely, so I decided to add support for the relationships. Perhaps in the future someone will want joins and we will be ready.

fix(config) Support join relationships in configuration

---

snuba/datasets/configuration/issues/entities/search_issues.yaml

Basically mirrors the DiscoverEntity column mappers from here:
https://github.com/getsentry/snuba/blob/fa65895b0d6d62d5cb7003455ff994864d0339da/snuba/datasets/entities/discover.py#L195

feat(issue-platform): add mappers so discover queries can work with search_issues dataset

---

snuba/web/views.py

When we have an error here (for example, due to a dataset not existing) we end up with an obscure connection error in sentry. Explicitly raising an `InternalServerError` causes a 500 to be returned.

chore(eventstream): Fix eventstream dev api to return 500s when there is an error

---

.github/workflows/ci.yml

This bumps the action ref to https://github.com/getsentry/action-self-hosted-e2e-tests/commit/20b5170d3b59d8b44ee5327d64b31d6b6b5aa34f, which introduces sentry-cli, a new dependency of our integration tests.

ci: Update self-hosted e2e action to add sentry-cli

---

snuba/clickhouse/translators/snuba/mappers.py
snuba/datasets/configuration/issues/entities/search_issues.yaml
snuba/datasets/configuration/transactions/entities/transactions.yaml
snuba/datasets/entities/discover.py
snuba/datasets/entities/events.py
tests/datasets/configuration/entity_with_column_mappers.yaml

We shouldn't need to specify the argument for this purpose built translation mapper. 
(CI should fail at first commit because this should break stuff))

fix(DC) ColumnToIPAddress mapper needing unnecessary parameters

---

snuba/consumers/consumer.py
snuba/consumers/strategy_factory.py

The parallel collect step is too complex, and offers little more than what can be achieved with Reduce chained to RunTaskInThreads.
As a follow up, Collect/ParallelCollect will be completely removed from Arroyo. The collect strategy is too complicated and we have introduced more intuitive ways to do batching now (via the Batch and Reduce steps).

feat: Deprecate ParallelCollect strategy in favour of Reduce/RunTaskInThreads

---

snuba/datasets/configuration/entity_builder.py
snuba/datasets/entities/metrics.py
snuba/datasets/entities/storage_selectors/__init__.py
snuba/datasets/entities/storage_selectors/errors.py
snuba/datasets/entities/storage_selectors/selector.py
snuba/datasets/entities/storage_selectors/sessions.py
snuba/datasets/plans/storage_plan_builder.py
snuba/datasets/pluggable_entity.py
tests/datasets/entities/storage_selectors/test_errors.py
tests/datasets/entities/storage_selectors/test_selector.py
tests/datasets/entities/storage_selectors/test_sessions.py
tests/datasets/plans/test_storage_plan_builder.py

Converting sessions and errors entities is not possible until the storage selectors can be referenced from config. This only works now because only the default ones are used in config

fix(DC): Make sure storage selectors are imported automatically

---

snuba/web/db_query.py

Currently, the `table_concurrent` metric is a gauge in Datadog. As a result, the agent only submits the last reported number of the metric in a given time interval. Since we want a more accurate representation of the maximum concurrent queries that hit our tables, we should change this to a `metric.timing`.
A new `table_concurrent_` metric is added to get a more accurate maximum overt time.

feat(api-abuse): Add timing metrics for table_concurrent

---

snuba/cli/consumer.py
snuba/consumers/consumer.py

This allows us to better route Sentry errors to relevant teams based on tags.
The storage name is also tagged on the Snuba consumer so we can filter by consumers for monitoring.

feat: Tag invalid messages for DLQ with `invalid_message`: `true`

---

Makefile
scripts/copy_tables.py
tests/test_copy_tables.py

The old regex did not account for some of the cases that have come up and cause mismatch errors when running the copy-tables script
I changed the name to `copy_tables` since it didn't like `from scripts import copy-tables` but if someone knows a way around that I can change back

ref(copy-tables): fix regex

---

snuba/migrations/groups.py
snuba/snuba_migrations/outcomes/0005_outcomes_ttl.py

Since there is no TTL on the outcomes dataset, the storage size can grow unbounded. This PR adds a TTL of 30 days for the raw tables and 90 days for the aggregate tables.

fix(outcomes): Add TTL to outcomes dataset

---

snuba/admin/clickhouse/migration_checks.py
snuba/admin/migrations_policies.py
snuba/admin/views.py
tests/admin/clickhouse_migrations/test_api.py
tests/admin/clickhouse_migrations/test_migration_checks.py

**context:**
Policies are no longer going to be defined in settings, but rather by the roles added https://github.com/getsentry/snuba/pull/3522. Actually using the roles to get the policies is done in https://github.com/getsentry/snuba/pull/3618 but I wanted to simplify the code a bit in order to make that change more manageable. 
**changes:**
* removal of the `PolicyChecker` class - it made more sense to get the group policies in the API endpoint since we'll need the user to do so. 
* contain all the checking logic within `run_migration_checks_and_policies` - I think ultimately this makes it simpler to read and understand

ref(migrations): Simplfy policies and status checks

---

snuba/datasets/configuration/groupassignee/entities/groupassignee.yaml
snuba/datasets/configuration/groupedmessage/entities/groupedmessage.yaml
snuba/datasets/configuration/json_schema.py
snuba/datasets/pluggable_entity.py
tests/datasets/configuration/test_entity_loader.py

GroupedMessage and GroupAssignee entities had YAML versions created and added to
their existing datasets. The two entities are now being loaded from config
instead of Python.
`required_time_column` can now be set to `null`. The field is still required in
the schema since that is the main case. These entities are a special case.
There is now a test in the entity loader that is similar to the storages test
that compares entities to their Python version. As we migrate entities we should
update that test. Once our migration is done we can delete that test entirely.

feat(config): Migrate GroupedMessage and GroupAssignee Entities to YAML

---

snuba/datasets/configuration/json_schema.py
snuba/datasets/configuration/utils.py
tests/datasets/configuration/entity_with_fixed_string.yaml
tests/datasets/configuration/test_entity_loader.py

The discover Entity contains `FixedString` fields which do not exist in the configuration grammar right now
* update the grammar
* update the parser
**Blast Radius**
No existing entities should be affected
**Feedback Desired**
Is there a better place to put the test that I don't know about?

ref(DC): Add FixedString field to configuration

---

snuba/settings/validation.py
snuba/utils/streams/topics.py

"snuba-dead-letter-inserts" is not used anywhere, let's not unnecessarily define and create it.

feat: Clean up unused topic

---

snuba/state/rate_limit.py
snuba/web/db_query.py
tests/datasets/test_querylog_processor.py

Currently, the snuba querylog contains `status` which specifies whether a query was rate-limited or not. However, it does not specify which rate limiter was applied. This PR is responsible for adding that into `stats`.
Querylog contains a new key `triggered_rate_limiter` in `stats` when a rate limiter is applied to a query.
Tested locally to ensure messages produced to querylog topics are correct and contain accurate fields.

feat(api-abuse): Add triggered rate limiter name to Querylog stats

---

snuba/migrations/groups.py
snuba/migrations/validator.py
snuba/snuba_migrations/outcomes/0003_outcomes_add_category_and_quantity.py
snuba/snuba_migrations/outcomes/0006_outcomes_add_size_col.py
snuba/snuba_migrations/outcomes/0007_outcomes_add_event_id_ttl_codec.py
snuba/snuba_migrations/outcomes/0007_outcomes_add_indexes_and_codecs.py
snuba/snuba_migrations/outcomes/0008_outcomes_add_indexes.py
tests/migrations/test_validator.py

This migrations attempts to make the outcomes tables match what's in sass. 
1. It fixes some of the past migrations to display columns in a consistent order with SaaS. Functionally, this make no difference but allows the diff tool to more easily highlight changes.
2. Add back size, bytes received cols to match SaaS schema
3. Add indexes and codecs to match SaaS schema
Also fixes a bug where the validator was overly aggressive when checking for order errors.

fix(migrations): make outcomes schema match SaaS SNS-1992

---

snuba/cli/subscriptions_executor.py

--stale-threshold-sec should be passed via the CLI, remove the runtime override for this value

ref: Remove runtime config override for stale-threshold-sec

---

tests/migrations/test_legacy_use.py

We would like people to use the new migrations style. The old migrations class `ClickhouseNodeMigrationLegacy` was left for backwards compatibility with the old migrations. Going forwards we would like a new migrations to use the the new `ClickhouseNodeMigration` class. This adds a test in CI that checks that new migrations use the new class.
For current migration groups, new migrations are defined as migrations past the cutoff indexes.

test(migrations): check legacy use SNS-1998

---

snuba/clusters/cluster.py
snuba/web/views.py
tests/web/test_check_clickhouse.py

When an `UndefinedClickhouseCluster` exception was raised sometimes it was
adding extra data to the error. That would be fine except that extra data is
being passed into metrics tags which expect a certain format. Change the error
to correctly pass extra data so it gets propagated to the metric tags correctly.
Fixes https://sentry.io/organizations/sentry/issues/3899535676

fix(health) Fix extra data in storage set error

---

snuba/datasets/processors/replays_processor.py
tests/datasets/test_replays_processor.py

closes: https://github.com/getsentry/replay-backend/issues/260
The SDK team has determined that the `contexts` object is the more appropriate place for these fields to live. Therefore, we can remove the old access pattern and replace it with one that knows to look inside the `contexts` object for these values.

feat(replays): Extract sample rates from the replay contexts object

---

snuba/cli/consumer.py

This was fixed in https://github.com/getsentry/snuba/pull/3502. We do not need this hardcoded key anymore.
Ran `snuba consumer --storage search_issues --auto-offset-reset earliest` locally.

fix(search-issues): Remove hardcoded key in consumer cli

---

snuba/admin/auth_roles.py

Removes the execute-non-blocking action from the default user. This  will make all migrations in the snuba admin tool readonly except from the TestMigration by default.

fix(admin): remove the execute role for the default user

---

snuba/web/views.py

We have some pods failing the readinessprobe. My hypothesis is that it is happening because the healthcheck is taking too long. This gives us more information on its operation

chore(oncall): add timing to healthcheck

---

snuba/datasets/configuration/discover/entities/discover.yaml
snuba/datasets/entities/discover.py
tests/fixtures.py
tests/test_snql_api.py

When querying the profile_id, make sure it only uses the transactions dataset in this case.
Fixes SNUBA-31S

fix(profiling): Profile id only on transaction dataset

---

snuba/datasets/configuration/discover/entities/discover_events.yaml

This dataset config was added after the previous PR was opened but before it was merged.

fix(profiling): Broken discover events test missing profile_id

---

snuba/migrations/groups.py
snuba/snuba_migrations/search_issues/0004_rebuild_search_issues_with_version.py

We wanna rebuild the search_issues table to include a `deleted` column required for replacements. 
This table is only present in local and dev environments so its ok to drop the table and rebuild.
I tested this locally and didn't encounter any issues.

fix(search-issues): rebuild search_issues dataset with a version column to support replacements in the future

---

snuba/cli/consumer.py
snuba/consumers/consumer_builder.py
tests/consumers/test_consumer_builder.py

https://github.com/getsentry/snuba/pull/3626 (third time's the charm?)
This time, the Producers are configured using the logical/default topic name, which is derived from the topic spec, regardless of whether there is a topic override being passed in.

fix(consumer): Separate out producers in consumer_builder

---

snuba/attribution/log.py

This was initially used to validate the consumer, this is no longer needed.

fix(attribution) Remove random logging

---

snuba/datasets/processors/outcomes_processor.py

https://github.com/getsentry/sentry-javascript/issues/6774
Adds two new discard reasons to support replays javascript sdk use-cases.  More information can be found in the linked issue.
- Are there other areas I need to change?
- Test coverage?

feat(outcomes): Add additional discard reasons

---

snuba/web/views.py
tests/web/test_views.py

We are currently conflating two different healthchecks as one. There's the healthcheck that envoy uses to not send traffic to the pod while it's draining, and the healthcheck that k8s uses to know whether to restart the pod. Currently those are the same thing.
The hypothesis is that if we have them as two separate endpoints, we will stop getting erroneous restarts by k8s of the snuba API

feat(oncall): add envoy specific healthcheck endpoint

---

snuba/datasets/processors/search_issues_processor.py
tests/datasets/test_search_issues_processor.py

Adds support for processing `context` arbitrary data bag from the incoming event for search_issues dataset.

feat(search-issues): process context data when processing payload

---

snuba/migrations/policies.py
snuba/settings/__init__.py
tests/migrations/test_policies.py

**context**
Currently our non blocking migration policy allows users to revert migrations that are pending. However, there may be a case where a migration ran successfully and completed, but there may be a valid reason to revert. 
This PR adds an arbitrary time limit of 20 minutes to revert once completed. I figured 20 minutes would be enough time to assess whether the impact of a migration would necessitate a revert.

ref(migrations): allow reverting completed non-blocking migrations

---

snuba/datasets/processors/search_issues_processor.py
tests/datasets/test_search_issues_processor.py

Extracts `contexts.trace.trace_id` and promotes it to a top-level column.

fix(search-issues): promote trace_id from context

---

snuba/admin/wsgi.py

We removed some of the hardcoded enums so now we have to make sure the storages are there when we start admin

fix(admin): initialize snuba in admin

---

rust_snuba/Cargo.toml
rust_snuba/src/lib.rs
rust_snuba/src/main.rs
rust_snuba/src/storage.rs

Adds a Storage struct which can be loaded via a storage yaml file

feat(rust-consumer): Parse storage yaml into Storage struct

---

snuba/cli/subscriptions_executor.py
snuba/cli/subscriptions_scheduler_executor.py

The subscritpion consumers should dynamically pick up the list of allowed datasets and entities. With the current approach, one would need to manually change the list of CLI options which can cause pod crashloops.
Validated that the CLI help option shows all entities and datasets
`
Options:
--entity [events|groups|metrics_sets|org_metrics_counters|metrics_distributions|metrics_counters|discover_events|groupedmessage|groupassignee|discover|discover_transactions|outcomes|outcomes_raw|transactions|sessions|org_sessions|replays|functions|profiles|search_issues|generic_metrics_distributions|generic_metrics_counters|generic_metrics_sets]
The entity to target  [required]
--consumer-group TEXT           Consumer group used for consuming the commit
log topic.
--followed-consumer-group TEXT  Name …

fix(cli): Allow more options for datasets and entities for subscription consumers

---

snuba/datasets/configuration/replays/dataset.yaml

Removes the experimental flag from replays before the Monday launch.

feat(replays): Remove experimental flag

---

snuba/migrations/groups.py
snuba/snuba_migrations/events/0019_add_replay_id_column.py

As per https://github.com/getsentry/rfcs/blob/main/text/0048-move-replayid-out-of-tags.md, this pull request adds a replay_id column to the errors table. 
I'm not sure how `ERRORS_RO` is used, and if its needed in this migration, but not doing anything with it now.

feat(replays): add replay_id to errors table

---

snuba/migrations/groups.py
snuba/snuba_migrations/transactions/0021_transactions_add_replay_id.py

As per https://github.com/getsentry/rfcs/blob/main/text/0048-move-replayid-out-of-tags.md, this pull request adds a `replay_id` column to the transactions table.

feat(replays): add replay_id to transactions table

---

snuba/admin/clickhouse/querylog.py
tests/admin/clickhouse/test_querylog.py

There are many useful querylog queries which we cannot do because we only have one thread to query the querylog with. Up the max_threads to 4 but make it runtime configurable.
NOTE:
I'm not sure how to test this to know that it works as expected (except for deploying it). It seems like you can pass anything you want into the `settings` dict, and have max_threads be any value and the query will still succeed. Would love some guidance on this if anyone has ideas.

feat(admin): allow querylog to be queried by more threads

---

snuba/admin/auth_roles.py
snuba/settings/__init__.py
tests/admin/clickhouse_migrations/test_api.py

The policies are handle via roles, instead of from `ADMIN_ALLOWED_MIGRATION_GROUPS`

ref(migrations): Make ADMIN_ALLOWED_MIGRATION_GROUPS a set

---

snuba/admin/auth_roles.py
snuba/admin/iam_policy/iam_policy.json

Adds custom role to allow running the search issue migrations by default. This is part of the effort to run search issue with the migrations tool.  Follows up #3720

migrations: add custom search issues role

---

.github/workflows/ci.yml

this was within ~10% of failing and so github sometimes reports it as both a pass and a failure at the same time

ref: bump timeout slightly

---

snuba/cli/consumer.py

`group` was removed at Sentry since it's too high cardinality, rename to `consumer_group`

fix: Rename consumer group tag

---

snuba/datasets/configuration/json_schema.py
snuba/datasets/configuration/utils.py
tests/datasets/configuration/test_storage_loader.py

This PR is responsible for adding support for specifying `Enum` column types in configuration. This schema type was already supported in python components and just needed to be moved over to config.

feat(DC): Add support for Enum column type

---

snuba/admin/clickhouse/system_queries.py
tests/admin/test_system_queries.py

The regex does not currently allow literal strings in select statements. Add it to the regex

fix(admin): allow strings in select statements on system queries

---

snuba/consumers/consumer.py

Continuing on from https://github.com/getsentry/snuba/pull/3743. The `terminate` method is never called so let's remove that too.

ref(batch-writer): Remove unused terminate() method

---

snuba/cli/multistorage_consumer.py

This is the second mini step. There is scattered topic validation throughout the multistorage consumer which checks for and ensures that there is only one topic or one dead letter policy in a multistorage context. 
This PR pulls out those validations into a single function and reduces a bit of repetition. With this PR we can also predict some of the small refactors we will need to get multistorage consumer to look a bit more like ConsumerBuilder. In the next step(s), we can move some pieces of code around to get a `get_consumer` and a `build_streaming_strategy_factory` function like ConsumerBuilder has.

ref(consumer): Separate out a get_logical_topics function in multistorage consumer

---

snuba/admin/static/clickhouse_queries/query_display.tsx

Fix a ui bug where where the host and port were not updated after changing storage and queries could be sent to wrong host.

fix(admin): clear host and port when storage is changed

---

snuba/cli/devserver.py

Related to this PR https://github.com/getsentry/sentry/pull/44846/files#diff-b7d8e2b4479e5aa536d95992ae00a4a667372de290d42fc9caf12efa42ebb707R64

fix(issue-platform): use the same consumer group as sentry devserver

---

snuba/consumers/consumer.py
snuba/consumers/consumer_builder.py
snuba/consumers/schemas.py
snuba/web/views.py
tests/test_consumer.py

* The defined schema was not for the generic-metrics topic, but for the
metrics topic. An important difference is that the tag values are
strings!
* The config was not reloaded dynamically, only on consumer start
* Validation errors crashed the consumers, but in this stage we don't
want that

fix: Fix a few bugs with message schema validation

---

snuba/datasets/configuration/issues/entities/search_issues.yaml

Replaces any function calls for `log(x) = -inf` with a value of 0.
Fixes SNUBA-32N

fix(issue-platform): wrap log(0) function calls with 0 value

---

snuba/datasets/configuration/issues/storages/search_issues.yaml
snuba/settings/validation.py
snuba/utils/streams/topics.py

Brings these changes back https://github.com/getsentry/snuba/pull/3767 which was reverted since we didn't have this https://github.com/getsentry/ops/pull/6162 merged in yet. 
The commit log should be fully ready in prod, but gonna hold off merging this until we get the green light from OPS, just getting this ready.

feat(issue-platform): add commit log topic when processing search_issue events

---

snuba/datasets/processors/metrics_bucket_processor.py
tests/datasets/test_metrics_processor.py

https://getsentry.atlassian.net/browse/SNS-1973
This PR follows the same method that the `GenericMetricsBucketProcessor` uses in order to fill the timeseries_id column with data from the message.

feat(metrics): Populate timeseries_id column in metrics_raw table

---

snuba/datasets/configuration/outcomes/entities/outcomes.yaml
snuba/datasets/configuration/replays/entities/replays.yaml
snuba/datasets/configuration/sessions/entities/sessions.yaml
snuba/datasets/pluggable_entity.py
tests/datasets/validation/test_entity_contains_columns_validator.py
tests/datasets/validation/test_entity_validation.py

Queries get sent to us with non-existent columns in them. No need to let those queries get all the way to clickhouse. Turn on the `EntityContainsColumnsValidator` to `ERROR` for all entities by default.
As part of this I moved the test for this validator to its own file and decoupled it from the outcomes entity (it now uses its a test configuration entity)

fix(oncall): error on non-existent columns

---

gocd/pipelines/snuba-stable.yaml
gocd/pipelines/snuba.yaml

1. release name is `production`, not `release`
2. got 403's while trying to set-commits - i've since update the token with the relevant permissions. The reason this failed was freight, which handles snuba releases, uses a sufficiently permissioned token, and so far with our token we have not needed to set-commits till now

cd: sentry releases fixes take 2

---

snuba/consumers/consumer.py
snuba/consumers/schema_files/event.json
snuba/consumers/schema_files/metrics.json
snuba/consumers/schema_files/querylog.json
snuba/consumers/schemas.py

The kafka schema registry isn't yet releaseable so in order to test out
performance, add a few more schemas here instead.
Also tag schema validation related metrics by topic.

ref: Add more topic schemas to Snuba

---

snuba/state/cache/redis/backend.py
snuba/web/db_query.py
tests/state/test_cache.py
tests/test_api.py

in order to make room for capacity management, we have to understand how db_query.py works. As part of that process, I realized that we had dead code in this file `execute_query_with_caching` has not been used since 2020 and we're not going to use it again.
@untitaker actually tried to remove this in #3372 but tests were failing. 
added a short circuit option to the readthrough cache. This was done for the following reasons:
1. The test that was failing was failing because it was hitting the readthrough cache, which never hit the `execute_query` function, thus never setting the `consistent` flag in the results. 
2. We had a single tenant incident where we wanted to disable the reathrough cache and were not able to so I figured it was fine to add it. This way if we lose redis for a …

ref(CapMan): remove execute_query_strategy variable

---

snuba/consumers/consumer.py
snuba/consumers/schema_files/event.json

We are running into event payload size limitations when trying to
attach the "invalid" payload. Instead, try sentry attachments for this
purpose. Since this might be expensive (though it shouldn't be), it is
also now only set up if the sampling decision is true.
Also remove some constructs from event schema that Snuba does not use.

ref: Simplify event schema, add kafka payload as sentry attachment

---

gocd/pipelines/snuba.yaml

There's a real discussion to be had as to which behavior is better, but
this is currently closer to how Freight behaved.

fix(gocd): Automatically deploy after CI passes

---

snuba/cli/migrations.py
snuba/migrations/runner.py
tests/migrations/test_runner.py

**context**
We want to automate migrations in our deployment process. The command we plan to use is the one that runs any migrations that have not been already run. We are not doing this for blocking migrations, only non-blocking, so we do not want to use the `--force` flag.
```
snuba migrations migrate
```
If for some reason something goes wrong during the attempted migrations, we will need to rollback. Currently reversing is only possible to do one migration at a time and you need both the `migration_id` and the `group`. To make things easier in CI/CD, we'd like a way to reverse any migrations that are "stuck" in-progress.  Hence, the reverse in progress cmd.
```
snuba migrations reverse-in-progress
```
**what about completed migrations that need to be reversed?**
As of right now, that …

ref(migrations): add reverse-in-progress cmd

---

snuba/datasets/processors/functions_processor.py
snuba/datasets/processors/profiles_processor.py
tests/datasets/test_functions_processor.py
tests/datasets/test_profiles_processor.py

In order to measure out ingestion time SLO, we need to pass the origin timestamp to `InsertBatch`.

feat(profiling): Set origin timestamp to measure ingestion duration

---

snuba/web/db_query.py
tests/web/test_tables_collector.py

This experiment was made three years ago. I turned the `uncompressed_cache_max_cols` to 100 to see if it would affect the query performance in any way. There is no significant difference with this optimization being turned on or off:
https://app.datadoghq.com/notebook/4927786/volo-mar-03-2023-10-28
According to [this presentation](https://presentations.clickhouse.com/meetup60/overview-of-caching.pdf) clickhouse will automatically disable the uncompressed cache for large queries anyways.

ref(db_query): remove uncompressed cache 'optimization'

---

.github/workflows/ci.yml

Bumps action commit sha to fail test suite properly from typo fix here:
https://github.com/getsentry/action-self-hosted-e2e-tests/pull/7

(chore): Bump self-hosted-e2e-test action

---

snuba/datasets/processors/functions_processor.py
tests/datasets/test_functions_processor.py

We're currently using the client's timestamp (start of the profile) for the origin timestamp and it's producing wild results (like suggesting we took 11 days to ingest some values).
It'd be better to use the timestamp taken from Kafka when we ingest the message. We started forwarding that value recently in https://github.com/getsentry/vroom/pull/190.

fix(profiling): Use correct field as origin timestamp for functions

---

snuba/cli/consumer.py
snuba/consumers/consumer_builder.py
tests/consumers/test_consumer_builder.py

Currently --bootstrap-servers is applied to the main topic being consumed as well as the commit log and replacements topic produced onto.
We are currently moving some topics between clusters. This limitation is inconvenient as it forces all topics to be moved in one hit instead of allowing topics to ever reside on different brokers.

feat(consumer): Support passing commit log and replacements bootstrap servers

---

snuba/consumers/schemas.py

After the latest changes to this file, we started reporting warnings on
startup when we tried to load schemas for all topics that had none
defined.
Fix SNUBA-33H

fix: Suppress irrelevant exception

---

requirements.txt

This introduces the types necessary for #3812 to land.

ref: Bump sentry-kafka-schemas to 0.0.4

---

snuba/cli/subscriptions_executor.py
snuba/cli/subscriptions_scheduler.py
snuba/subscriptions/executor_consumer.py
snuba/subscriptions/scheduler_consumer.py
tests/subscriptions/test_executor_consumer.py
tests/subscriptions/test_scheduler_consumer.py

Similar to https://github.com/getsentry/snuba/pull/3827
We are moving topics around and need a way to easily override these temporarily as we will have 2 subscriptions pipelines running side by side.

feat(subscriptions): Support passing --bootstrap-server via CLI

---

.github/workflows/ci.yml
Makefile
codecov.yml
snuba/admin/jest.config.js
snuba/admin/package.json
snuba/admin/static/tests/kafka/index.spec.tsx

Add tests for the front end components within snuba through [jest](https://jestjs.io/) and [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/).
- Update `package.json` to include new dev dependencies
- Add new github job [`admin-tests`](https://github.com/getsentry/snuba/actions/runs/4349199836/jobs/7598600464) to github actions
- Add `jest.config.js` for jest configerations
- Add sample test for `KafkaTopicData`

feat(admin): Add front-end tests

---

snuba/web/query.py

- Currently, this metric increments when `tenant_ids` exist but at least one of `referrer` or `organization_id` doesn't exist in the dictionary, but doesn't ensure the values are valid nor does it increment in the case where the `tenant_ids` dict is empty entirely
- This change ensures to increment the metric if:
- `tenant_ids` is entirely empty
- if the keys `referrer` and `organization_id` do exist but at least one of the values are `None`

fix(CapMan): Ensure `tenant_ids` metric is accurate

---

snuba/admin/clickhouse/predefined_querylog_queries.py
snuba/admin/package.json
snuba/admin/static/query_editor.tsx
snuba/admin/static/querylog/index.tsx
snuba/admin/static/querylog/query_display.tsx
snuba/admin/static/tests/query_editor.spec.tsx

Changes to the ClickHouse Querylog page in the Snuba admin console allow users and authors of predefined queries to define labels and its corresponding values in their queries.
- Added new component `QueryEditor`
Closes [SNS-1931](https://getsentry.atlassian.net/browse/SNS-1931)
[SNS-1931]: https://getsentry.atlassian.net/browse/SNS-1931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(querylog): Support for query interpolation in Querylog query editor

---

snuba/datasets/processors/replays_processor.py
tests/datasets/test_replays_processor.py

The primary-key of the replays table includes segment_id as a component.  When segment_id is null we need to provide a default event_hash value to prevent row merges.  Previously `None` was coerced to a UUID which was deterministic.

feat(replays): Default event_hash when segment_id is null

---

snuba/processor.py
tests/conftest.py
tests/consumers/test_schemas.py
tests/test_util.py

sentry-kafka-schemas is supposed to contain more and more examples over
time for all kafka topics. Run those examples against the relevant snuba
consumers.

test: Run all consumers' message processors against examples

---

snuba/admin/clickhouse/common.py
snuba/admin/clickhouse/querylog.py
snuba/admin/clickhouse/system_queries.py
snuba/admin/clickhouse/tracing.py
snuba/clusters/cluster.py

**context**
This PR https://github.com/getsentry/ops/pull/6099 was applied today and I started seeing the same error when I tried to run system queries for the querylog or when I tried to use the querylog - see [SNUBA-342](https://sentry.sentry.io/issues/3988451086/?project=300688&query=is%3Aunresolved+is%3Aunassigned+level%3Aerror+lastSeen%3A-24h&referrer=issue-stream).
What seems to be happening is that we set the user to have `readonly=2`, but when we are making the query we set `readonly=1` and clickhouse does not allow the `readyonly` setting to be changed when you have the `readonly=2` setting https://clickhouse.com/docs/en/operations/settings/constraints-on-settings/
**TRACING -> QUERY_AND_SETTINGS**
Since the tracing setting already has `readonly=2` I decided to just rename that …

fix(querylog): enable readonly 2 for querylog

---

snuba/admin/clickhouse/common.py
snuba/admin/clickhouse/querylog.py
snuba/admin/clickhouse/system_queries.py
snuba/admin/clickhouse/tracing.py
snuba/clusters/cluster.py

So cabin doesn't actually have the `trace_readonly` user which makes https://github.com/getsentry/snuba/pull/3847 wrong. 
~However, I think we should be able to use the same user and just change the settings (to be `readonly=2` for the querylog)~
Actually that might still cause issues due to https://github.com/ClickHouse/ClickHouse/blob/20.7/src/Access/SettingsConstraints.cpp#L243-L249 so I'm actually removing it for the querylog together, the settings will just be empty

ref(admin): dont use tracing user for querylog and remove readonly=2

---

.gitignore
rust_snuba/Cargo.toml
snuba/cli/optimize.py
snuba/cli/rust_consumer.py
snuba/clickhouse/optimize/optimize_scheduler.py
snuba/settings/__init__.py
snuba/settings/settings_test.py
snuba/settings/utils.py
snuba/utils/bucket_timer.py
tests/clickhouse/optimize/test_optimize.py
tests/clickhouse/optimize/test_optimize_scheduler.py
tests/settings/test_settings.py

Alt to https://github.com/getsentry/snuba/pull/3802
I prefer this approach at least in the short term as it keeps the settings in Rust aligned with the Python version. It requires more minimal changes to the Python settings than the other option: only that the timedelta types need to change as these are not easily json serializable. Whether Python settings should ultimately move to yaml is a larger, more consequential topic - let's not try to solve it within the Rust consumer prototype.
The Rust consumer entrypoint loads the Python settings, writes the json file and replaces the current process with the Rust program passing the path to the JSON file through to the Rust consumer.

feat: Share Python settings with Rust and add Rust consumer entrypoint

---

rust_snuba/Cargo.toml
rust_snuba/src/bin/consumer/querylog_consumer.rs
rust_snuba/src/consumer.rs
snuba/cli/rust_consumer.py

Add Rust consumer argument parsing. Add --log-level to the Python CLI and pass it to the Rust process.

feat(rust-consumer): Forward Python Cli args to Rust

---

requirements.txt
snuba/datasets/processors/querylog_processor.py
snuba/querylog/query_metadata.py

- There currently exists an `organization` field in the Querylog schema which seemingly has no data in any Querylog entry
- We now have Org ID in each request for >90% (and growing) of requests coming from Sentry via `tenant_ids`
- Updated the `record_query()` function to now pass in Org ID if it exists in the Snuba Request

feat(Querylog): Organization ID from `tenant_ids`

---

rust_snuba/Cargo.toml
rust_snuba/rust_arroyo/src/backends/kafka/config.rs
rust_snuba/src/consumer.rs
rust_snuba/src/lib.rs
rust_snuba/src/settings.rs
rust_snuba/src/storages.rs
snuba/cli/rust_consumer.py

Currently crashes with:
```
$ RUST_BACKTRACE=1 snuba rust-consumer --storage querylog
2023-03-15 15:55:06,869 Initializing Snuba...
2023-03-15 15:55:09,273 Snuba initialization took 2.404892279s
[2023-03-15T14:55:09Z INFO  consumer] Starting consumer for querylog with settings at /Users/untitaker/projects/snuba/tmp/settings.json
[2023-03-15T14:55:09Z INFO  consumer] Loaded settings: Settings { clusters: [Cluster { host: "127.0.0.1", port: 9000, user: "default", password: "", http_port: 8123, storage_sets: ["cdc", "querylog", "search_issues", "migrations", "functions", "transactions", "events", "generic_metrics_distributions", "discover", "events_ro", "sessions", "outcomes", "profiles", "replays", "generic_metrics_counters", "generic_metrics_sets", "metrics"] }], broker_config: …
```

wip: Scaffolding for generic Rust consumer

---

rust_snuba/Cargo.toml

Requires PYTHON_CONFIGURE_OPTS="--enable-shared" to build

fix(rust-consumer): Remove auto-initialize feature

---

rust_snuba/src/consumer.rs
snuba/cli/rust_consumer.py

In Python we have separate consumer and multistorage consumer implementations. Since there is a lot of divergence between them, bringing them together has been a long and ongoing process. In Rust, we only want to support one implementation.

feat(rust-consumer): Multistorage consumer

---

rust_snuba/src/consumer.rs
snuba/cli/rust_consumer.py
snuba/datasets/table_storage.py

We don't want to reimplement the slice/cluster resolution in Rust, call it in Python when the Rust consumer starts and write it in a file for Rust.
This is currently incomplete, there are some additional fields we need to add here such as the reference to the message processor.

feat: Start building the config for Rust consumer

---

snuba/admin/clickhouse/predefined_system_queries.py

This query is useful for investigations for migrations and just in general when you want to see that current schema for a table in production

ref(admin): add CreateTableQuery predefined queries

---

requirements.txt
snuba/querylog/query_metadata.py
snuba/web/db_query.py

It cannot be fully typed yet as schema is not correct. The SLO fields are marked as part of the `clickhouse_query` in the schema but are at the top level in the producer code.

feat(schemas): Partially type the data in querylog producer

---

snuba/datasets/processors/replays_processor.py
tests/datasets/test_replays_processor.py

on clickhouse 20 it seems that we have to specify an empty string for `title` as it is a non-nullable column. On newer versions of clickhouse this does not cause problems, but we were seeing issues in self-hosted. Sentry employees did not see this as generally everyone is on an M1 and uses clickhouse 21.
In CI we run clickhouse 20, but we also do not have adequate test coverage for actual DB insertion, and this is something i plan to follow up on. additionally, we don't use this column anywhere so i'm thinking we should plan on removing it / deprecating it.
Solves https://github.com/getsentry/self-hosted/issues/2002

fix(replays): set transaction as empty string instead of null

---

rust_snuba/rust_arroyo/examples/base_processor.rs
rust_snuba/rust_arroyo/src/backends/kafka/mod.rs
rust_snuba/rust_arroyo/src/backends/local/mod.rs
rust_snuba/rust_arroyo/src/backends/mod.rs
rust_snuba/rust_arroyo/src/processing/mod.rs
rust_snuba/rust_arroyo/src/processing/strategies/mod.rs
rust_snuba/rust_arroyo/src/processing/strategies/noop.rs
rust_snuba/rust_arroyo/src/types/mod.rs

`Position` struct is no longer needed. It was a hack used for the legacy Snuba consumer, and has been removed in Python Arroyo: https://github.com/getsentry/arroyo/pull/165. We are removing it here to bring the two libraries in line.

feat(rust-arroyo): Get rid of `Position`

---

snuba/datasets/processors/transactions_processor.py
tests/datasets/test_transaction_processor.py

We're deprecating sending replay_id as a tag (https://github.com/getsentry/rfcs/blob/rfc/escalating-issues/text/0048-move-replayid-out-of-tags.md)
This PR modifies the transactions processor to:
we can remove the dual writing once we conditionally query on the new column based on date and only write the column
Task: https://github.com/getsentry/team-replay/issues/32
Epic: https://github.com/getsentry/replay-backend/issues/248
Relies on a change to relay to validate the replay context, which i'll be putting up shortly.

feat(tx_processor): write replay_id as top level column

---

rust_snuba/rust_arroyo/src/backends/kafka/mod.rs
rust_snuba/rust_arroyo/src/backends/local/mod.rs
rust_snuba/rust_arroyo/src/backends/mod.rs
rust_snuba/rust_arroyo/src/processing/mod.rs

Follw up to https://github.com/getsentry/snuba/pull/3883.
commit_positions and stage_positions should be called commit_offsets/ stage_offset like in Python's Arroyo library.

ref: Rename positions to offsets everywhere

---

rust_snuba/rust_arroyo/examples/transform_and_produce.rs
rust_snuba/rust_arroyo/src/processing/strategies/mod.rs
rust_snuba/rust_arroyo/src/processing/strategies/produce.rs

Adds the produce strategy and a simple transform -> produce example. 
The produce strategy is an arroyo strategy that produces messages on a given topic.

rust: add simple transform and produce strategy example

---

snuba/settings/settings_self_hosted.py

In order for a snuba environment to determine which snuba readiness state it supports, we need a settings file for each environment to specify its supported states. Currently, [self-hosted](https://github.com/getsentry/self-hosted/blob/b1fda9a55203e3f28a3d02e1056213449b7cff45/docker-compose.yml#L89) uses `SNUBA_SETTINGS: docker`.  This PR is responsible for creating a new file called `settings_self_hosted.py` to house the new `SUPPORTED_STATES` flag specific to self-hosted as specified in the Dataset Readiness State proposal. The contents of this file is a copy of `settings_docker.py` for now.
No changes will occur until the self-hosted repo is updated to use this new file.

feat(DRS): add file for self hosted settings

---

.dockerignore
.github/workflows/ci.yml
Dockerfile
Makefile
cloudbuild.yaml
requirements-build.txt
requirements.txt
rust_snuba/rust_arroyo/src/processing/strategies/produce.rs

This will allow us to run `snuba rust-consumer` from docker.
The build now happens in roughly four steps:
1. Initialize `build_base` layer, which contains common debian packages we need
to have around for building everything else + requirements-build.txt
2. Then, based on `build_base`, there are _three_ build stages that (at
least on my machine) run in parallel:
* `base` is just `build_base` with requirements.txt + additional runtime
deps installed, and all the build dependencies stripped out.
* `build_admin_ui` is `build_base` with JS dependencies installed, and
the admin UI built
* `build_rust_snuba` is `build_base` with Rust installed, and the
`rust_snuba` package built.
3. Based on `base`, `application` is built. Build artifacts from
`build_admin_ui` and `build_rust_snuba` are …

ref: Include rust_arroyo in Dockerfile

---

snuba/admin/clickhouse/nodes.py

The Discover dataset is now exposed in snuba admin tracing tool. However, in production, the discover dataset does not follow the typical snuba cluster pattern. Internally, the discover cluster identifies itself as a non-single node, but is not part of a cluster. 
As a result, this [check](https://github.com/getsentry/snuba/blob/c7d920648a24d2f66c0248cf91423b33ba110f60/snuba/clusters/cluster.py#L325) will always fail for discover. To make this work in admin, we could either refactor `ClickhouseCluster` to work with discover, or we can just update the admin API to accommodate for this one-off case which is what this PR does.

fix(admin): Avoid get_local and get_dist nodes for discover in admin

---

snuba/admin/clickhouse/predefined_querylog_queries.py

Add 2 new queries to Querylog admin for aggregate usage by org/referrer
1. Specify a time period and N. Get the top N referrers with the highest percentage of all bytes scanned
2. Specify a 2 time periods and an org ID. Get the change in percentage of all bytes scanned that org used between those time periods
Closes [SNS-2168](https://getsentry.atlassian.net/browse/SNS-2168)
[SNS-2168]: https://getsentry.atlassian.net/browse/SNS-2168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ref(querylog) Add new pre-defined queries to Querylog Admin

---

.github/workflows/ci.yml
.github/workflows/image.yml

This build arg was changed recently to be a bit more explicit
also get rid of rust in all github docker (ghcr) images for now, caching somehow doesn't work. we only need it on google cloud build, where caching works fine

fix: Update build arguments to no longer build admin UI for ARM

---

snuba/datasets/configuration/loader.py
tests/conftest.py

if tests are run in isolation which depend on the entity factory, they will not have initialized them and get an AttributeError
Also fix an unclosed file warning

fix(tests): initialize snuba before tests run

---

.github/workflows/ci.yml

I took a look and the timeouts didn't start recently, so not sure what's
going on. We have some other PRs lined up for speed improvements at
least.

ci: Bump test_distributed timeout

---

.github/workflows/ci.yml

I believe this image is dead and should be removed entirely, but for now
let's not build Rust inside of it

fix: Also do not build Rust for the arm64 CI image

---

snuba/migrations/connect.py

Some storages like CDC dont have defined clusters in prod. Skip checking them.

skip checking undefined nodes

---

snuba/cli/migrations.py

allow passing `--yes` to the migrations fake prompt so we can run in headless mode. Needed for k8s jobs

fix(migrations): add passing in yes to migrations cli prompt for headless cli running

---

snuba/admin/clickhouse/predefined_system_queries.py
snuba/admin/views.py

Follow up to #3861 
Add a system query to get the replica counts as we use this often. Also allows the admin tool to show the inactive replica error when detected.

feat(admin): add system query for inactive replicas and show error msgs

---

requirements.txt
snuba/datasets/processors/outcomes_processor.py

Added schema validation for outcome and use `Outcome` python type hint for OutcomesProcessor

ref(outcomes): Use python types from sentry-kafka-schemas for OutcomesProcessor

---

tests/web/test_db_query.py

a race condition caused these to be merged after db tests became opt-in

fix(ci): opt in db_query tests to db

---

snuba/cli/migrations.py
snuba/migrations/runner.py
tests/migrations/test_runner.py

Specifying the group and prefix will migration through that migration (includes the matching migration)
this should also work for `--fake`
```shell
12:35 $ snuba migrations migrate -g generic_metrics 0012
2023-03-24 12:35:29,689 Initializing Snuba...
2023-03-24 12:35:31,869 Snuba initialization took 2.181490815s
2023-03-24 12:35:31,895 Running migration: 0012_counters_mv
2023-03-24 12:35:31,957 Finished: 0012_counters_mv
2023-03-24 12:35:31,965 Ran through: 0012_counters_mv
Finished running migrations
```
If the migration is already run or the arg doesn't match, get an error
```shell
12:34 $ snuba migrations migrate -g generic_metrics 0011
2023-03-24 12:35:23,842 Initializing Snuba...
2023-03-24 12:35:26,178 Snuba initialization took 2.337297151s
Error: No pending migration matching: 0011 …
```

ref(migrations): run multiple migrations through a specifc migration id

---

snuba/settings/__init__.py
snuba/settings/settings_self_hosted.py
snuba/settings/settings_test.py

This PR is responsible for adding `SUPPORTED_STATES` settings in dev and self-hosted settings files. Right now, there are four states: `deprecate`, `limited`, `partial`, and `complete`. These readiness states map to snuba specific environments within Sentry are used to determine which storages and migrations groups are available within an environment.
These settings will not do anything after being merged because Dataset Readiness States have not been implemented yet. Side note, the rollout for readiness states will be control by a runtime config and updated for less critical datasets first.

feat(DRS): Add SUPPORTED_STATES settings in dev and self-hosted

---

snuba/state/sliding_windows.py
tests/state/test_sliding_windows.py

#3901 had to be reverted because something changed in master causing tests to fail
- update: it was the db change for testing, only difference in this PR and previous one is I've added `@pytest.mark.redis_db` to each test case

fix(CapMan): Add Sliding Windows rate limiter again

---

requirements.txt
snuba/consumers/consumer_builder.py
snuba/consumers/strategy_factory.py

We want to check if the DLQ proposal in Arroyo is viable by testing the performance impact on Snuba in production.
There are no functional changes here, however if the runtime config `run_dlq_test_{storage_name}` is set, the consumer for that storage will start buffering messages as would be needed for the DLQ.
Note that this config is only checked once upon start up of the consumer so a deploy is needed for the runtime config value to take effect.

feat: DLQ performance test

---

snuba/replacers/errors_replacer.py

We want to know if this actually is still happening since it was
originally conceived in https://github.com/getsentry/snuba/commit/67618adbf987560274b40fa35a6a8b579130ea3a#diff-efbe37619db8bd83053dfc7e8eecf1ec37700b2d5078eb8ad6a5e462ac93605aR112-R119
If not, we could get rid of transaction_id as a concept in replacements

fix: Add error message when replacement is dropped

---

snuba/web/views.py

- We're seeing a lot of pod restarts for Snuba API but the ddog metric doesn't seem to align, it's possible the metric isn't being emitted
- Adds an error log on any failed `/health` call to try and gain more observability on the issue via logs

feat(API): log failed `/health`

---

snuba/admin/clickhouse/predefined_querylog_queries.py

- Adds the following pre-defined queries to Querylog:
- Most bytes scanned for referrer by organization
- Highest cumulative request duration for referrer by organization

feat(admin): Bytes scanned + Request duration by Org pre-defined queries

---

snuba/subscriptions/codecs.py
tests/subscriptions/test_codecs.py

`trace_output` and `profile` are internal Snuba things. Sentry does nothing with them and they are not required by the schema. Let's not produce this data unnecessarily.

fix: Subscription result data

---

snuba/datasets/configuration/functions/dataset.yaml

Turns off `is_experimental` for `functions` dataset. This will enable ClickHouse health-checks in production.

fix(functions): Remove is_experimental flag for functions dataset

---

snuba/subscriptions/scheduler_processing_strategy.py

librdkafka producer buffer is 100k messages.
We limit ourselves. to 10k by mistake.
This increases that limit.

fix(scheduler) Increase producer buffer size

---

.github/workflows/enforce-license-compliance.yml

Let's pin license compliance scanning to a commit. This is done in `sentry` and `getsentry`. Example: https://github.com/getsentry/sentry/blob/2430ab615a525b69558f523ae80612043465bab8/.github/workflows/enforce-license-compliance.yml
This will turn off the license compliance until it is bumped manually, seems reasonable to do for snuba since merging and deploying fast can be super important here

Pin fossa action to commit

---

.github/workflows/ddl-changes.yml
gocd/pipelines/snuba-sns-test.yaml
scripts/check-migrations.py
scripts/fetch_service_refs.py

There's an ongoing effort to make migrations run in a more automated manner. As such, there's a need to add some guardrails to check that migrations aren't coupled with other code changes. This makes them more easily reversible if something goes wrong during when apply a migration.
This PR checks that when changes are made to migrations (in `snuba_migrations`), no other files outside the `snuba_migrations` are touched. It adds two scripts to run in CI:
* `check_migrations.py` :  a script that diff HEAD with a given sha and throws a `CoupledMigrations` exceptions if the diff has a mixture of migrations and non-migrations changes. 
* `fetch_service_ref.py` :  a script that uses the GoCD REST api to fetch the most recent successfully deployed sha from the GoCD pipeline. 
To first test this, …

feat(CI): add check to detect migrations changes coupled with others

---

scripts/check-migrations.py

Skip checking groups_loader.py for coupled migrations changes since this is a file that is also updated with migrations.

fix(CI): skip checking groups loader for migration changes

---

snuba/datasets/configuration/generic_metrics/entities/org_counters.yaml

This PR synchronize validation for org_countries for granularity,
Based on:
https://github.com/getsentry/snuba/blob/51062e0cf93e5dd54fd596a276a774af71f8b197/snuba/datasets/configuration/generic_metrics/entities/org_counters.yaml#L59-L64
Some more detailed context where we use it:
In Dynamic sampling we use query for last 5 mins to calibrate dynamic sampling rules, so we need granularity=60, otherwise we'll see a validation error: 
```
E   sentry.utils.snuba.SnubaError: validation failed for entity generic_org_metrics_counters: granularity must be multiple of 3600
```

fix: update validation from org_countries for granularity

---

snuba/cli/multistorage_consumer.py
snuba/consumers/consumer.py
snuba/consumers/consumer_builder.py
snuba/consumers/strategy_factory.py
snuba/datasets/configuration/storage_builder.py
snuba/datasets/configuration/utils.py
snuba/datasets/table_storage.py
tests/datasets/configuration/test_utils.py

Depends on https://github.com/getsentry/snuba/pull/4003
These are the Snuba changes needed once https://github.com/getsentry/arroyo/pull/202 lands.
Also fixes a bug where the DLQ topic name is not resolved from the logical to physical names or to the correct slice if the storage is sliced.
I kept the DLQ policy definitions in the storage yaml files unchanged, we may want to revisit at some later stage

feat: Use new DLQ from Arroyo

---

snuba/datasets/configuration/events/storages/errors_ro.yaml
snuba/query/allocation_policies/__init__.py
snuba/query/allocation_policies/errors_allocation_policy.py
snuba/settings/__init__.py
snuba/settings/settings_test.py
snuba/web/db_query.py
tests/query/allocation_policies/test_allocation_policy_base.py
tests/query/allocation_policies/test_errors_allocation_policy.py
tests/web/test_db_query.py

This PR introduces the first iteration of the allocation policy for the errors storage
For every organization, keep track of how many bytes they've scanned in the last 10 minutes, when they reach a limit, throttle them to one thread
In runtime config:
```
SET ErrorsAllocationPolicy.is_active 0
```
```
SET ErrorsAllocationPolicy.is_enforced 0
```
```
SET ErrorsAllocationPolicy.org_scan_limit 42069
```
This is not meant to be the final policy, this is just a quick way to get something working end to end and then iterate on it. Most of this code will be rewritten

feat(CapMan): AllocationPolicy for Errors

---

snuba/migrations/group_loader.py
snuba/snuba_migrations/search_issues/0007_add_transaction_duration.py

We missed this column when reviewing what's required to display Issue events for this dataset. Including it now and defaulting it to 0 value.

feat(search-issues) add optional transaction_duration column

---

snuba/datasets/configuration/events/storages/errors.yaml
snuba/datasets/configuration/events/storages/errors_ro.yaml
snuba/query/allocation_policies/__init__.py
snuba/query/allocation_policies/errors_allocation_policy.py
snuba/settings/__init__.py
snuba/settings/settings_test.py
snuba/web/db_query.py
tests/pipeline/test_composite_planner.py
tests/query/allocation_policies/test_allocation_policy_base.py
tests/query/allocation_policies/test_errors_allocation_policy.py
tests/query/allocation_policies/test_pickleability.py
tests/test_snql_api.py
tests/web/test_db_query.py

Same as #3999 except we make sure the allocation policy is pickleable (and all future allocation policies are pickleable)
For every organization, keep track of how many bytes they've scanned in the last 10 minutes, when they reach a limit, throttle them to one thread
In runtime config:
```
SET ErrorsAllocationPolicy.is_active 0
```
```
SET ErrorsAllocationPolicy.is_enforced 0
```
```
SET ErrorsAllocationPolicy.org_scan_limit 42069
```
This is not meant to be the final policy, this is just a quick way to get something working end to end and then iterate on it. Most of this code will be rewritten

feat(CapMan): Errors Allocation Policy V0 (fixed)

---

gocd/pipelines/snuba.yaml
scripts/fetch_service_refs.py

We've tested the migrations check on the test pipeline. This PR transfers it to the main pipeline.
The check compares against the last deployed commit to check that there are not too many undeployed migrations commits stacked up . We are ignoring migrations status for now.

feat(CI): add migrations check to main pipeline

---

snuba/datasets/configuration/issues/entities/search_issues.yaml
snuba/datasets/configuration/issues/storages/search_issues.yaml
snuba/datasets/processors/search_issues_processor.py
tests/datasets/test_search_issues_processor.py
tests/test_search_issues_api.py

2nd step for adding `transaction_duration` to the dataset. Related to this PR: https://github.com/getsentry/snuba/pull/4007
Essentially a copy-past of what's being done in `transactions_processor` https://github.com/getsentry/snuba/blob/9fba7cfbd50f22e7ad0bb3607e0cb089e29d9fdb/snuba/datasets/processors/transactions_processor.py#L116-L135
Pulls out `start_timestamp` and `timestamp` from the event data dictionary to calculate the difference in milliseconds for a transactions, `transaction_duration`, defaulting to 0.

feat(search-issues): process transaction_duration values

---

gocd/pipelines/snuba.yaml

To be merged after #4013 
This add a manually triggered migrate stage to the main gocd. We have been testing this pipeline in the test cluster. At the moment it needs to be manually triggered and only runs for migrations in the "complete" readiness state.

feat(CI): add a manually triggered migrations stage to main gocd

---

snuba/consumers/consumer.py

That code is a bit brittle, and we should have something to prevent it
from raising.

fix: Add killswitch to disable raising of InvalidMessage

---

tests/datasets/cdc/test_groupassignee.py
tests/datasets/cdc/test_groupedmessage.py

Fix typing errors in CDC test that were breaking on master.

fix(typing) Couple typing errors in cdc tests

---

gocd/pipelines/snuba.yaml

Changes the migrations job to list migrations. This is temporary solution to allow us to test the job. Eventually this will be replaced by running the real thing.

fix(CI): make the migrations job list status

---

snuba/admin/auth_roles.py
snuba/admin/migrations_policies.py
snuba/admin/static/clickhouse_migrations/index.tsx
snuba/settings/__init__.py
tests/admin/clickhouse_migrations/test_api.py

Deprecates the `ADMIN_ALLOWED_MIGRATION_GROUPS` list. This list is not needed since we now control access via policy. This allows to show all groups so that migrations status is visible for all. For groups where the migrations policy blocks access , the group is readonly so the user can view its status and dry run it, but cannot execute it.

fix(admin): show all migrations groups

---

snuba/replacer.py
snuba/replacers/errors_replacer.py
snuba/replacers/replacer_processor.py
tests/datasets/test_errors_replacer.py
tests/replacer/test_cluster_replacements.py

When writing all those classes I found it kind of annoying that metadata
was a required getter on the interface. Turns out we only do that so we
can access it in a single function somewhere later. Instead, wrap the
replacement in a tuple and store the metadata alongside.

ref(replacements): Replacements no longer need to carry metadata

---

snuba/query/allocation_policies/errors_allocation_policy.py
tests/query/allocation_policies/test_errors_allocation_policy.py

It was assumed that subscriptions did not have an organization id attached to them. Turns out it's organization_id=1 for everything.
Make subscriptions queries not have a quota enforced for them (as is done currently with rate limiting)

fix(capman): make subscription referrer passthrough

---

.github/workflows/ddl-changes.yml
scripts/check-migrations.py

Use 3 dots to only diff new changes relative to master when checking migrations conflicts. This avoids having to rebase everytime.

fix(ci): diff only new changes

---

snuba/replacers/errors_replacer.py
snuba/replacers/replacer_processor.py
tests/replacer/test_cluster_replacements.py

Currently we first dispatch to replacement based on type based on a big
if-else statement, then ask the replacement what type it is. Either the
replacement has a say about the ReplacementType or it doesn't, but
we shouldn't use it as a databag for random things we want to
forward to another function.

ref: Dispatch replacements based on get_replacement_type

---

gocd/pipelines/snuba.yaml

We tested the migrations pipeline with the list command and verified that it captures the correct migrations. This now adds the actual run/reverse command to the pipeline.

fix(migrations): add the actual run/reverse command to gocd

---

requirements.txt
snuba/redis.py

There is a class called FailoverRedis in Sentry's sentry.utils that is
supposed to deal with networking errors when GCP memorystore falls over.
Snuba doesn't have an equivalent class, and as a result would be
susceptible to the same failures.
sentry-redis-tools is a new package that contains this code + maybe more
redis-related code in the future. For now, it only contains a copy of
Sentry's FailoverRedis.
Add FailoverRedis and make it the default redis client for everything.
Sentry does NOT use FailoverRedis as the default redis client, but I
believe we should change that as well to prevent incidents like INC-311.

ref: Start using FailoverRedis in Snuba

---

rust_snuba/rust_arroyo/src/processing/strategies/commit_offsets.rs

We were logging "performing a commit" on every message even if the commit never actually happens.

fix(rust-consumer): Stop spamming the log with messages

---

Dockerfile

`import rust_snuba` was accidentally importing the folder in the
repository instead of the installed wheel. On top of that, installing
the wheel never happened because the arguments for `find` were in the
wrong order.
Now that that is fixed, we can no longer assume that rust_snuba is
available in all builds, therefore we remove the `import rust_snuba`
sanity check -- not like it helped us catch anything anyway.

fix: Fix broken rust_snuba import

---

snuba/migrations/group_loader.py
snuba/snuba_migrations/functions/0002_add_new_columns_to_raw_functions.py

This adds some new columns to the raw functions table that we want to explore the cardinality of. These columns were chosen based on the same columns the metrics datasets had chosen plus some profiling specific ones. This will be used to create a new materialization from the findings. And any high cardinality columns will be removed.

feat(profiling): Add new columns to raw functions table

---

snuba/consumers/consumer.py

Update to the config introduced in https://github.com/getsentry/snuba/pull/4046 to preserve the existing behavior (default is to log all invalid messages)

fix: Flip config default for logging bad message sample rate

---

requirements.txt

Bumping the `sentry-relay` version to stay in sync with latest as we released more data categories.

build(deps): bump sentry-relay from 0.8.19 to 0.8.21

---

snuba/datasets/configuration/issues/entities/search_issues.yaml
tests/test_search_issues_api.py

Need for issue search.
Is it better to have this as an actual column in the storage?

fix(search-issue): map transaction and transaction_name column to tags[transaction]

---

gocd/pipelines/snuba.yaml

This limits access of the migrate GoCD stage to the `role-deploy-snuba-migrations-operator` google group. Right now members of this group include team-sns

fix(ci): gocd set permissions for migrate

---

snuba/admin/audit_log/action.py
snuba/admin/notifications/slack/utils.py
snuba/admin/views.py

**context**
currently when running/reversing a migration fails, we just don't send a slack notification (we just log it). This changes that behavior by actually sending a notification when something fails. It will look like the following:

ref(admin): notify slack when migrations err

---

snuba/datasets/processors/replays_processor.py
tests/datasets/test_replays_processor.py

- Reduces memory required to aggregate replay segments.
- Reduces disk usage.
- New access pattern does not consider tags on segments > 0 removing ingestion requirement.

feat(replays): Only store tag keys and values on segment 0

---

snuba/datasets/configuration/functions/storages/functions.yaml
snuba/datasets/configuration/functions/storages/functions_raw.yaml
snuba/datasets/configuration/profiles/storages/profiles.yaml
snuba/migrations/groups.py

The storage and migration group's readiness_state for profiles and functions should be `partial` instead of `complete`. This is because they are not available in self-hosted and ST yet. 
No affect. The readiness states for these datasets are not set as active in rollout yet.

fix(DRS): Update readiness_state of profiles and functions

---

.github/workflows/ci.yml

Picks this change up: https://github.com/getsentry/action-self-hosted-e2e-tests/pull/11

(chore) Bump self-hosted-e2e-action pin to limit docker image poll to 10 min

---

snuba/consumers/consumer.py

Instead of sampling invalid messages, let's throttle them so we don't
miss spurious, small issues, and globally so we don't forget to do it
for a particular dataset.

fix: Rate-limit the number of invalid message payloads

---

gocd/pipelines/snuba-stable.yaml
gocd/pipelines/snuba.yaml

With this change, the snuba pipeline will perform the following steps:
1. Deploy new changes to the canary replica
1. Wait for 5 minutes (determined by the canarychecks script flag)
- NOTE: This delay is intended to give the deployer a chance to check for any early signs of issues and our hope is to add some automated checks to this script in the future (i.e. if any alerts trigger for the canary instances, mark the deploy as a failure)
1. Deploy new changes to all replicas (i.e. canary and primary replicas a.k.a all of prod).
For the snuba stable pipeline is changed to follow the same behavior as above with it's smaller set of container names.

Adding canary deployments to snuba pipelines

---

.github/workflows/enforce-license-compliance.yml

This PR re-enables FOSSA license compliance scans. The action has been running for a few days now in all repos except getsentry, snuba, and sentry without issues. Changes have been made to the action to make sure it is more resilient to FOSSA errors (outages, network issues)
Here's the relevant PR in the license scan action: https://github.com/getsentry/action-enforce-license-compliance/pull/16

(feat): Re-enable fossa

---

snuba/consumers/consumer.py
snuba/consumers/consumer_builder.py
snuba/utils/streams/topics.py

We need to start aligning topic configuration and encoding the correct values so that they match in all environments. 50MB is way too large and does not reflect any actual values set in prod. This is problematic because we don't see these issues in dev that actually exist in prod. Reduce the default to 10MB, with the exception of Replays which is 15MB. We should also fix the rest of the topics later.

feat: Kafka topic configuration

---

snuba/datasets/configuration/discover/entities/discover.yaml
snuba/datasets/configuration/discover/entities/discover_events.yaml
snuba/datasets/configuration/discover/entities/discover_transactions.yaml
snuba/datasets/configuration/events/entities/events.yaml
snuba/datasets/configuration/issues/entities/search_issues.yaml
snuba/datasets/configuration/transactions/entities/transactions.yaml

Now that we store`geo.subdivision` https://github.com/getsentry/relay/pull/2058 we need to expose it for querying
Fixes https://github.com/getsentry/getsentry/issues/10313

feat(geo): make geo.subdivision queryable

---

scripts/check-migrations.py

When a new migration group is added, a key element is registering the storage set key. Storage set keys can be hardcoded or be dynamically configured using the settings file. In order to use the dynamically configured settings file, we should allow modifications to settings file to happen in the same PR as migrations.

fix(migrations): Allow setting file changes to happen in migrations

---

snuba/pipeline/settings_delegator.py
snuba/query/processors/logical/quota_processor.py
snuba/query/query_settings.py
snuba/request/validation.py
tests/query/processors/test_quota.py

Reverts getsentry/snuba#3942
This org based thread limiter is not necessary now that we have allocation policies

Revert "feat(rate-limiting): Add an Organization + Referrer thread rate-limiter"

---

snuba/web/db_query.py

- We're seeing a lot of redundant ClickHouse errors in Sentry
- The only ones we really want to see are internal errors - not rate limits or other user errors

fix(observability): Not all ClickHouse Errors need to be surfaced to Sentry

---

snuba/datasets/configuration/storage_builder.py
snuba/datasets/entities/storage_selectors/__init__.py
snuba/datasets/entities/storage_selectors/errors.py
snuba/datasets/entities/storage_selectors/selector.py
snuba/datasets/entities/storage_selectors/sessions.py
snuba/datasets/plans/storage_plan_builder.py
snuba/datasets/storage.py
snuba/query/exceptions.py
snuba/querylog/__init__.py
snuba/querylog/query_metadata.py
snuba/settings/__init__.py
snuba/settings/settings_self_hosted.py
snuba/web/__init__.py
snuba/web/db_query.py
snuba/web/query.py
snuba/web/views.py
tests/datasets/plans/test_storage_plan_builder.py
tests/web/test_query_exception.py
tests/web/test_results.py

This PR is responsible for failing queries to Snuba storages which are not ready yet. For example, a new experimental storage (`readiness_state=limited`) should not be queryable in Sentry prod environments. This PR adds `StorageNotAvailable` error messaging in the storage plan builder. Additionally, in order for this new error to not count against our SLO, a new error type called `QueryPlanException` was created to capture errors outside the query execution flow. More details on how to review this PR below.
I would recommend reviewing this PR in the following order:
* `snuba/datasets/plans/storage_plan_builder.py`: After the appropriate storage is selected for the incoming query, a readiness_state check was added here and throws an error if it is unavailable.
* `snuba/web/views.py`: The …

feat(DRS): Fail queries when storage is unavailable due to readiness state

---

gocd/pipelines/snuba.yaml
snuba/cli/migrations.py
snuba/migrations/runner.py
tests/cli/test_migrations.py
tests/cli/test_optimize.py
tests/migrations/test_runner.py

This add the partial readiness state into the gocd pipeline. We adjust the cli migrations command to take in multiple `-r` parameters to provide readiness states.  Eventually, when the DRS project is complete, this may be deprecates as it may become unnecessary to pass in the readiness state via parameters; the pipelines should be able to infer what state to target based on their enviroment.
This PR adds in a few extra sanity tests for the CLI given that we have quite a few parameters being passed in now.

fix(CI): add partial states to gocd pipeline

---

snuba/cli/consumer.py
snuba/consumers/consumer_builder.py

It's already passed into the constructor of this class. This change removes the possibility of building an invalid consumer with inconsistent slice_id values.

ref: Don't pass slice_id to build_base_consumer() unnecessarily

---

snuba/migrations/group_loader.py
snuba/migrations/groups.py
snuba/settings/__init__.py
snuba/settings/settings_distributed.py
snuba/settings/settings_test_distributed_migrations.py
snuba/snuba_migrations/spans/0001_spans_v1.py
snuba/snuba_migrations/spans/0002_spans_add_tags_hashmap.py

The PR had to be reverted temporarily because goCD pipeline cannot deploy both code changes and migrations in the same deployment pipeline. But due to a bad code commit, we had to revert the migration PR as well.
Nothing has changed in this code compared to the original PR.
This reverts commit 058e6e54d1eff5fc8385389639fceae475cb7cc2.

Revert "Revert "feat(spans): Initial spans migrations (#4089)""

---

snuba/query/allocation_policies/bytes_scanned_window_policy.py
tests/query/allocation_policies/test_bytes_scanned_window_allocation_policy.py

Sentry has some batch scripts it needs to run sometimes. instead of worrying about which organization they are running for, just let them run on one thread

feat(capman): add support for low priority referrers

---

snuba/query/allocation_policies/bytes_scanned_window_policy.py

getsentry has tests which don't run in our CI. This will be fixed

temp(capman): do not enforce allocation policy by default

---

requirements.txt

This release contains the DLQ rebalancing fixes so we can turn on the DLQ and run the load test again

build: Arroyo 2.10.2

---

snuba/query/allocation_policies/bytes_scanned_window_policy.py

Tests in sentry and getsentry have now been updated. We should be able to turn this on again (and quick revert if it breaks CI).
The hard part of this is that it's not easy to run getsentry tests in CI so we're in this in-between. But it's almost over!

feat(capman): enforce the allocation policy by default (again)

---

rust_snuba/src/strategies/python.rs

We are doing DLQ testing and intentionally putting invalid messages on topics. Just ignore those in Rust consumer.

feat(rust-consumer): Ignore invalid message

---

requirements.txt
snuba/consumers/schemas.py

Use codecs from sentry-kafka-schemas instead of Arroyo.
This change would allow us to transparently handle decoding of msgpack
topics, solely based off of configuration in sentry-kafka-schemas. Snuba
doesn't have to know about the underlying encoding format anymore. We
don't want to do that, but I think it's pretty cool.
Unfortunately, when there's no schema, we get no codec back from
sentry-kafka-schemas. So we have to define our own noop subclass.
Eventually we should be able to get definitions for all topics. We might
already have them, actually.

ref: Bump sentry-kafka-schemas to 0.1.3

---

requirements.txt

sentry-kafka-schemas provides the codecs now

build: Don't need json dependency from Arroyo anymore

---

snuba/consumers/strategy_factory.py

We fixed this bug ages ago in the last-seen updater, and ST might be
running into it in generic-metrics.

fix(consumer): Commit at least once per second even with prefilter

---

snuba/clusters/storage_sets.py

Came across this error trying to run a single-tenant deploy (https://deploy.getsentry.net/go/tab/build/detail/st-s4s-experimental/1/run-migrations/1/snuba-migrations), and we don't want those deploys to be blocked:
```
Traceback (most recent call last):
File "/usr/local/bin/snuba", line 33, in <module>
sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1651, in invoke
cmd_name, cmd, args = self.resolve_command(ctx, args)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1698, …
```

fix(dataset-config): make SPANS hardcoded to fix single-tenant deploy

---

snuba/datasets/configuration/spans/entities/spans.yaml
tests/test_spans_api.py

Changes the time required column from `end_timestamp` to `timestamp`. There is already a column mapper defined which maps timestamp to end_timestamp [here](https://github.com/getsentry/snuba/blob/master/snuba/datasets/configuration/spans/entities/spans.yaml#L72-L77). Also adds the timeseries processor to spans entity

feat(spans): Change required time column to be timestamp

---

snuba/settings/__init__.py

With bigger clusters, we have capacity to run 2 merges in parallel for longer. Change the parallel cutoff time to be the same as regular optimize cutoff time.

fix(optimize): Remove cutoff for parally optimize

---

snuba/datasets/processors/replays_processor.py
tests/datasets/test_replays_processor.py

- on clickhouse 20.3, uuids need to have dashes on them. We didn't have this covered in a test case but we now see it occuring in a few different places with new behavior we're trying to add.

fix(replays): use uuid with dashes for event hash

---

snuba/query/allocation_policies/bytes_scanned_window_policy.py

There is a user report task which calls `eventstore.get_events` and it's not very important (because it has been rejected for a straight week and nobody has said anything) but probably shouldn't leave it broken. We throttle it to one thread and call it a day.

chore(capman): add user reports to single thread referrers

---

.github/dependabot.yml

We have our own mechanisms for ensuring the schemas are reasonably up to
date, and we should actively stress-test them. If they don't work, we
have a problem in other repos that do not use dependabot.

fix(dependabot): Ignore sentry-kafka-schemas

---

snuba/query/allocation_policies/bytes_scanned_window_policy.py

Some test utils call snuba. It's fine for them to call it with just one thread.

chore(capman): add test referrer to single thread referrers

---

.github/workflows/bump-version.yml

This workflow can be triggered manually to bump a python package to a
newer version. We want to ensure this is available in snuba so that
people can bump sentry-kafka-schemas more easily.

fix: Fix permissions of bump-version.yml workflow

---

snuba/clickhouse/http.py
tests/clickhouse/test_http.py

When a join is being called on HTTPWriteBatch we should limit the time spent waiting for the operation to be successful. If we do not limit the time spent the consumer can stay hung for any amount of time. It would stay hung till the kafka broker realizes that the consumer is dead (which today is 5 minutes). Instead of waiting so long, we should fail fast and abort earlier.

fix(consumers): Add timeout for http batch writes

---

snuba/datasets/configuration/issues/entities/search_issues.yaml
snuba/datasets/entity.py
snuba/datasets/pluggable_entity.py
snuba/query/validation/validators.py
snuba/utils/schemas.py
tests/datasets/configuration/column_validation_entity.yaml
tests/datasets/validation/test_entity_contains_columns_validator.py

The EntityContainsColumnValidator wasn't checking the mapped columns when
validating if a column was allowed on the entity. Change this so that any mapped
columns are also marked as valid.
Also enable this on one dataset (search_issues) as a test. If everything works
correctly, the rest of the dataset will also get this validator.
Some of these changes were copied from this old PR: https://github.com/getsentry/snuba/pull/3976/files, but with the added checking of the storage mappers.

ref(tech-debt) Column validator also checks mapped columns

---

snuba/cli/__init__.py

I think this provide better context in the errors product, where
transaction is noted next to each error title and just reads "CLI
initialization" for many of them.
For measuring performance of the snuba CLI, I _think_ it makes sense to
measure it on a per-command basis but I'm not entirely sure. Perhaps
common initialization time should be split out into its own transaction?

feat: Add command name to transaction name

---

docs/source/clickhouse/supported_versions.rst
docs/source/index.rst

Since we know which versions of clickhouse Snuba current works with, lets document it.

docs(clickhouse): Document supported clickhouse versions

---

snuba/datasets/configuration/events/storages/errors.yaml
snuba/datasets/configuration/events/storages/errors_ro.yaml
snuba/datasets/configuration/transactions/storages/transactions.yaml
snuba/query/allocation_policies/__init__.py
snuba/query/allocation_policies/bytes_scanned_window_policy.py
snuba/query/allocation_policies/errors_allocation_policy.py
snuba/query/allocation_policies/transactions_allocation_policy.py

The extensions of the BytesScannedWIndowAllocaitonPolicy were stopgap measures to put an allocation policy on the transaction storage. We can now remove that tech debt and reuse the `BytesScannedWindowAllocationPolicy` since the config prefix is decided by the storage key.
**Breaking Changes**
The `metrics` of the allocation policy used to be named the same as the allocation policy class name. That has been changed to always have `allocation_policy` as the name and the rest of the information to be default tags. As a result. The allocation policy dashboard will have to be fixed after this PR is merged

ref(capman): remove extended allocation policies

---

snuba/settings/__init__.py

This will create the datasets needed to use profiling in self-hosted.

feat(profiling): Create profiling datasets by default in self-hosted

---

snuba/consumers/consumer.py

Validate every message for which we have a schema by default
Schema validation can still be turned off or the rate turned down via config. But the default is now to validate 100% of messages. We have been running this way on many topics for a few months already.

feat(schema-validation): Validate all messages 😱

---

snuba/admin/audit_log/action.py
snuba/admin/views.py
snuba/web/views.py
tests/admin/test_api.py

Changes to the allocation policy were not being published to the auditlog or the slack feed. This should fix that.
Also:
* Removes unnecessary `try/catch (Exception)`s
* Adds an allocation policy API test

fix(capman): create auditlog notifications for allocation policy updates

---

snuba/consumers/dlq.py
tests/consumers/test_dlq.py

DLQ instruction is the way to signal which DLQ messages to consume. It is intended to be written to Redis via Snuba admin - and periodically checked for updates from the DLQ consumer.
This change only introduces the DlqInstruction class - it will be integrated as a follow up.

feat(dlq): Add the DLQ instruction mechanism

---

snuba/consumers/consumer.py
snuba/datasets/processors/generic_metrics_processor.py
snuba/datasets/processors/metrics_aggregate_processor.py
snuba/datasets/processors/metrics_bucket_processor.py
snuba/processor.py
tests/datasets/test_metrics_processor.py
tests/test_consumer.py
tests/test_generic_metrics_api.py
tests/test_metrics_api.py

Same as https://github.com/getsentry/snuba/pull/4052 (which got reverted in https://github.com/getsentry/snuba/commit/0d1b0cfa4540e99ff6689e529961eb6d2fb8a3b4 because sentry didn't for some reason have the previous changes that fixed the tests) Fixed tests were re-added in https://github.com/getsentry/sentry/pull/49348

ref(consumer): pass sentry_received_timestamp again

---

snuba/query/allocation_policies/__init__.py
snuba/query/allocation_policies/bytes_scanned_window_policy.py
snuba/web/db_query.py

- Queries with bad Tenant IDs are showing up as errors in Sentry
- We should start rejecting these queries
- Modified existing validation to check for `None`s

fix(CapMan): Validate Tenant IDs

---

snuba/datasets/configuration/events/storages/errors.yaml
snuba/datasets/configuration/events/storages/errors_ro.yaml
snuba/datasets/configuration/transactions/storages/transactions.yaml
snuba/query/allocation_policies/__init__.py
snuba/query/allocation_policies/bytes_scanned_window_policy.py
tests/query/allocation_policies/test_allocation_policy_base.py
tests/query/allocation_policies/test_bytes_scanned_window_allocation_policy.py
tests/test_snql_api.py
tests/web/test__get_allocation_policy.py
tests/web/test_db_query.py

Currently, a policy has configured defaults and whenever it is reused, those defaults are used as well. That runs into a problem when the policy is used across two storages with different needs (for example, the `org_bytes_scanned_limit` default is different for errors vs transactions.
* Allows for the policy defaults to be overridden at instantiation
* inputs the existing defaults we have in production into configuration
* adds validation to catch mistyped defaults on AllocationPolicyConfig(s)

feat(capman): Allow overriding policy defaults in configuration

---

snuba/admin/clickhouse/tracing.py
snuba/admin/static/tracing/index.tsx
snuba/admin/static/tracing/types.tsx
snuba/admin/views.py
snuba/clickhouse/native.py
tests/test_clickhouse.py

To give more guidance to the product on how much data their queries are returning, it's useful to say how many rows it returns. We can probably add more stuff to this summary as time goes on

feat(admin): add amount of rows in result set to tracing tool

---

snuba/admin/audit_log/base.py
snuba/admin/notifications/slack/utils.py
tests/admin/notifications/test_build_blocks.py
tests/admin/test_api.py

Current message does not tell us what change fix it and also fix the default behavior to be less useless. Add tests for slack message generation

Fix slack notifications for when allocation policy changes

---

snuba/cli/consumer.py
snuba/consumers/consumer_builder.py
tests/consumers/test_consumer_builder.py

Previously the default was to wait forever, however this causes problems with rebalancing. 5 seconds is probably a better default. Any partially processed messages that aren't done in this time will be picked up again when the partition is reassigned.
Note this currently doesn't get applied to the HTTP write step since that has it's own timeout set here: https://github.com/getsentry/snuba/blob/e3565b26f9d34a4142bb081c445732f16b7be67b/snuba/clickhouse/http.py#L344

feat: Default join timeout for all consumers of 5 seconds

---

.github/workflows/ci.yml
snuba/migrations/runner.py
snuba/settings/__init__.py
tests/migrations/test_runner.py

This PR is responsible for enabling readiness_states for all migration groups that are not part of `SKIPPED_MIGRATION_GROUPS` in their respective environments. This [section of this document](https://www.notion.so/sentry/Dataset-Readiness-State-Rollout-Plan-d38deffe77534856a4e4f4a3b0cfb110?pvs=4#479d1451ca8a457e9542fedce8cdf87c) is used to track the roll out.
* Existing migration groups will now use its `readiness_state` flag to determine whether or not the migration group is skipped in particular sentry environments.
The following migration groups will use readiness states for each environment:
* In SaaS: All groups except for `sessions`.
* In S4S: All groups except for `functions`,`profiles`, `querylog`,`search_issues`, `spans`, `test_migration`.
* In self-hosted: All groups except for …

feat(DRS):  Enable migration group readiness states for those not skipped

---

snuba/datasets/processors/spans_processor.py
tests/datasets/test_spans_processor.py

Upstream now sends relevant data in `spans.data` field of the payload. Use the information provided in the payload to populate fields in the clickhouse table. With this, we do not need the logic of performing application logic processing anymore in snuba spans consumer so we can get rid of it.
In order to validate that the spans processor is performing valid transformations the PR also adds a test to perform strict validation of the results.

feat(spans): Extract information from span data

---

snuba/migrations/groups.py

The `test_migration` group needs to be set to partial because snuba admin (in SaaS) contains an [auth-role](https://github.com/getsentry/snuba/blob/f1774371103e4f368357d31f372f654fd7cee9e4/snuba/admin/auth_roles.py#L161) which accesses this migration group

fix(DRS): Set test_migration group to partial

---

snuba/pipeline/settings_delegator.py
snuba/query/processors/physical/clickhouse_settings_override.py
snuba/query/query_settings.py
snuba/web/db_query.py
tests/datasets/configuration/test_storage_loader.py
tests/query/processors/test_clickhouse_settings_override.py
tests/web/test_db_query.py

This allows custom clickhouse query settings to be specified in the dataset config through a physical query processor.

feat(clickhouse-settings): Add ability to override clickhouse query settings via query processor

---

snuba/consumers/consumer.py
snuba/consumers/consumer_builder.py

We don't need to wait for the commit log producer to flush between every batch / message produced. This adds an unnecessary and slow blocking operation to each batch. This change removes the flush between each batch and only calls flush once when the consumer is shutting down.

perf: Make the batch write step faster

---

snuba/consumers/consumer_builder.py
snuba/consumers/dlq.py

This is strategy to be used by the DLQ consumer. It processes messages until either a specified number of messages if reached, or if a max timeout is reached between messages. After that point it raises sigint and the consumer will exit.

feat(dlq): Add `ExitAfterNMessages` strategy

---

snuba/consumers/consumer.py
tests/test_consumer.py

**context**
We want to be able to include the latency from sentry indexer for metrics and generic metrics SLOs. We needed to add the `sentry_received_timestamp` in order to do so since the other timestamps we had were either the broker timestamp (so latency of the snuba consumer itself) or the relay timestamp (which we didn't want to include as part of SNS SLOs)
**pre reqs**

ref(consumers): record sentry_received_timestamp metrics

---

snuba/attribution/log.py
snuba/utils/streams/configuration_builder.py

The attribution producer should use the config specified for that topic, not assume the default configuration applies.

fix: Fix attribution producer

---

docs/source/query/overview.rst
snuba/query/snql/parser.py
tests/query/snql/test_invalid_queries.py
tests/query/test_query_validation.py

Currently, if a query is sent in which a required datetime column is compared to a string literal instead of a datetime literal, the error message that is returned is misleading. This new error message should make it more clear that the datetime column needs to be compared with a datetime literal.

fix(parsing): Update error message for missing datetime column comparison condition

---

snuba/consumers/consumer_builder.py
snuba/consumers/strategy_factory.py

DLQ consumer strategy is similar to the main consumer strategy with 2 notable differences:
- it doesn't commit to the commit log
- it subtitutes ExitAfterNMessages for the CommitOffsets strategy. The consumer exits after the requested number of messages is processed and committed.

feat(dlq): Consumer builder can build a DLQ strategy

---

requirements.txt
snuba/cli/migrations.py
snuba/environment.py
snuba/migrations/connect.py
snuba/migrations/runner.py

We're trying to improve how we do some of the logging and transition towards using structlog since it works better with GCP. This PR transitions the migrations module to use structlog, eventually we will update the other modules too. There's a bug where string interpolation and tracebacks don't work properly in structlog v22.0 so we bumped it up to v22.3.

fix(logs) : use structlog in migrations

---

snuba/settings/__init__.py
snuba/web/views.py
tests/migrations/test_runner.py
tests/web/test_check_clickhouse.py

This PR is responsible for enabling readiness_states for all storages. This [section of this document](https://www.notion.so/sentry/Dataset-Readiness-State-Rollout-Plan-d38deffe77534856a4e4f4a3b0cfb110?pvs=4#479d1451ca8a457e9542fedce8cdf87c) is used to track the roll out.
* Existing storages will use their `readiness_state` flag to determine whether or not to execute clickhouse healthchecks in a particular environment.
* Note the `DISABLED_DATASETS` and `is_experimental` still takes precedence over readiness_states.
The following storages will use readiness states for each environment:
* In SaaS: All storages except for `groupassignees`, `groupedmessages`, `search_issues`, `querylog`, `sessions`, `spans`.
* In S4S: All storages except for `functions`, `groupassignees`, `groupedmessages`, …

feat(DRS): Enable readiness state for storages

---

snuba/admin/clickhouse/predefined_querylog_queries.py

- Adding some queries to bring visibility to how Orgs are affected by allocation policies
- Ideally these queries can be used together to gain some insights, modifications may be required depending on what kind of analysis you're doing but they are a decent base
Sample result for past 30 mins of most throttled orgs query:
Sample result for past 30 mins of quantiles query:

feat(CapMan): Most throttled Orgs visibility

---

snuba/migrations/groups.py

The PR will enable migrations for the profiles and functions datasets in self-hosted. Since we have migrated to readiness_states this [PR](https://github.com/getsentry/snuba/pull/4195) is now stale. This change required for https://github.com/getsentry/self-hosted/pull/2154.
Note: Setting profiles and functions to `readiness_state: complete` will not allow migrations on single-tenant as these groups still [exist in SKIPPED_MIGRATION_GROUPS](https://github.com/getsentry/ops/blob/f28e6508f0457c7c1788e9e1adf9aaffe71b9e45/single-tenant/k8s/snuba/templates/snuba.conf.py.j2#L83).

feat(profiling): Promote profiles and functions to complete

---

tests/clickhouse/optimize/test_optimize_tracker.py

Apparently we already retry all assertions in this test 10 times, except
this one. ~It's not entirely clear to me why, there's no code comment
indicating why.~ seems like it was simply an oversight: #4217 #4143

fix: Fix flaky optimize test

---

snuba/query/processors/physical/replaced_groups.py
tests/datasets/storages/processors/test_replaced_groups.py

We encountered some subscription queries that, when run in final mode, cause the query to fail with OOM from clickhouse.
This can break the whole subscriptions pipeline. 
As a quick fix, this pr adds a bypass option to turn the final flag off on subscriptions on specific projects.
This can be activated when needed.

fix(subscriptions) Final bypass for subscriptions

---

snuba/datasets/configuration/issues/entities/search_issues.yaml

We keep getting alerted for queries with bad columns on search issues. Let's turn on the validator and not make it our problem anymore

feat(oncall): reject search issues queries with bad columns

---

snuba/datasets/configuration/events/storages/errors.yaml
snuba/datasets/configuration/events/storages/errors_ro.yaml
snuba/datasets/configuration/transactions/storages/transactions.yaml

- Thankfully this doesn't do any validation just yet, but this spelling should still be fixed..

fix(CapMan): `organzation_id` -> `organization_id`

---

snuba/datasets/configuration/spans/storages/spans.yaml
tests/test_spans_api.py

- As part of our effort to add an Allocation Policy to every storage, adding a `BytesScannedWindowPolicy` to the `spans` storage
Sentry testing:
https://github.com/getsentry/sentry/pull/50010

feat(CapMan): Spans Allocation Policy

---

snuba/query/allocation_policies/__init__.py
tests/query/allocation_policies/test_allocation_policy_base.py

- `AllocationPolicyConfig.to_config_dict()` applied the value with the following logic:
- `value or self.default`
- In the case that the value is a 0, it returns default when the real check should be whether or not the given value is a `None`

fix(CapMan): `value or default` returned default if value was 0

---

snuba/datasets/configuration/groupedmessage/storages/grouped_messages.yaml
snuba/datasets/configuration/json_schema.py

- As part of our effort to add an Allocation Policy to every storage, adding a `BytesScannedWindowPolicy` to the `grouped_messages` storage

feat(CapMan): GroupedMessages Allocation Policy

---

snuba/datasets/configuration/issues/storages/search_issues.yaml
tests/test_search_issues_api.py

Forgot to include `profile_id` and `replay_id` in the `UUIDColumnProcessor`

fix(search-issues): remove dashes from profile_id and replay_id when querying

---

snuba/admin/tool_policies.py
snuba/admin/views.py
snuba/settings/__init__.py
tests/admin/test_authorization.py

This setting was added to enable running two parallel deployments of the admin
tool. However since our permissions now need to be more fine-grained, the
separate deployment is no longer useful.
This should have no impact, this setting was never actually applied in prod.

ref(admin): Revert dashboard developer setting

---

snuba/cli/consumer.py
snuba/consumers/consumer_builder.py
tests/consumers/test_consumer_builder.py

Since we are using the consumer config object now, we don't need to pass the storage key separately

ref(consumer-builder): Don't pass storage key separately to consumer builder

---

snuba/consumers/consumer.py

This is a fix for https://github.com/getsentry/self-hosted/issues/1982
The offset that should be published to the commit log is the same as the one committed to Kafka (current offset + 1).
This is a fix for a regression introduced in https://github.com/getsentry/snuba/pull/3531.

fix: Off by one error in snuba commit log

---

snuba/datasets/entity.py

This enables the column validation by default on all entities.
The code itself has been tested on multiple datasets, so it should
be safe to turn on across the board. This PR will be validated
against all Sentry tests.

ref(validation): Turn on column validation by default

---

snuba/consumers/consumer.py
snuba/datasets/processors/outcomes_processor.py

The metric is now logged for all processors, no needed for users to do this individually in each message processor

ref: Remove unnecessary try/except in outcomes processor

---

snuba/consumers/consumer.py

This was used as a feature flag during the DLQ rollout to provide a quick way to revert behavior. It's not needed anymore.

ref: Remove config used for rollout

---

rust_snuba/src/config.rs
snuba/consumers/consumer_config.py
tests/consumers/test_consumer_config.py

So it can be easily resolved for all of our consumers without duplicating code in each.

feat: Add logical topic to shared consumer config

---

snuba/datasets/configuration/functions/storages/functions.yaml
snuba/datasets/configuration/functions/storages/functions_raw.yaml
snuba/datasets/configuration/profiles/storages/profiles.yaml

This PR will enable clickhouse health checks for the profiles and functions datasets in self-hosted.
Note: Setting profiles and functions to `readiness_state: complete` will not turn on health checks on single-tenant yet since the DISABLED dataset override still exists [here](https://github.com/getsentry/ops/blob/1edfe7a6cb13a74bafce96b20e9338cb080b49df/single-tenant/k8s/snuba/templates/snuba.conf.py.j2#L96).

feat(profiles): Promote profiles and functions storages to complete

---

snuba/admin/auth_roles.py
snuba/admin/iam_policy/iam_policy.json
tests/admin/test_authorization.py

Create a new role for product developers that gives access to the tracing and
snql-to-sql tool. Make this role a default role, so everyone with access to the
admin tool will have access to both tools.
Small additional changes: add David to list of users with access to all tools,
and have the product tool role reflect the actual google group we will use to
grant access going forward.

ref(admin) Allow access to tracing/snql-to-sql by default

---

snuba/query/allocation_policies/__init__.py
snuba/query/allocation_policies/bytes_scanned_window_policy.py
tests/query/allocation_policies/test_allocation_policy_base.py
tests/query/allocation_policies/test_bytes_scanned_window_allocation_policy.py
tests/web/test_db_query.py

Change the `max_threads` attribute of an AllocationPolicy to use the config of
the policy instead of the state config. This means it can be overridden in the
dataset configuration files as well.
This means that the max threads in the allocation policy will no longer use the
state setting. The state setting still is used in db_query.py however. The
default value for the allocation policy max threads has been set to match what
is in prod currently.

fix(capman): Change max_threads to use allocation policy config

---

snuba/settings/__init__.py

This PR allows spans migrations to run locally in snuba since this already runs in SaaS.

feat(spans): Allow spans migrations to run locally

---

snuba/cli/dlq_consumer.py
snuba/consumers/consumer_builder.py
snuba/consumers/dlq.py
snuba/consumers/strategy_factory.py
tests/consumers/test_dlq.py

Previous approach was not correct. Since the strategy was placed at the end of the pipeline it was counting batches of messages not actual messages on the raw topic. Now it's the first step in the sequence so the message count should be correct.

fix(dlq): ExitAfterNMessages strategy should be first step not last

---

snuba/cli/dlq_consumer.py

The dlq consumer reconfigures metrics for each instruction it receives so force is needed

fix(dlq): Pass force to configure_metrics

---

mypy.ini
requirements.txt
snuba/admin/auth.py
snuba/admin/google.py
tests/admin/data/mock_responses/check_transitive_membership_200.json
tests/admin/data/mock_responses/group_lookup_200.json
tests/admin/data/mock_responses/group_lookup_403.json
tests/admin/test_google.py

This change calls the Groups API to check that a user has membership in a given group. This will allow the iam_policy file to use group-based role assignment.

Use Google Groups API for authorization

---

snuba/admin/dead_letter_queue/__init__.py
snuba/admin/static/api_client.tsx
snuba/admin/static/dead_letter_queue/index.tsx
snuba/admin/static/dead_letter_queue/types.tsx
snuba/admin/views.py
snuba/datasets/storage.py
tests/admin/dead_letter_queue/test_dlq.py

Moves the hardcoded DLQ topics out of the admin UI and generate them from storage config definitions

feat(dlq): DLQ topics API for admin

---

snuba/datasets/configuration/metrics/storages/counters.yaml
snuba/datasets/configuration/metrics/storages/distributions.yaml
snuba/datasets/configuration/metrics/storages/sets.yaml

They should actually exist in prod first

fix: Temporarily revert dlq topic changes

---

snuba/admin/iam_policy/iam_policy.json

After replacing my own email with team-sns and validating that I can see all tools on snuba admin, we can now transition all user emails to groups.

ref(iam-policy): Replace user emails with group emails in iam_policy file

---

snuba/admin/auth.py
snuba/admin/google.py

Since we don't use the google cloud API on local and testing environments, we should not be building the api client at all.

fix(iam-policy): Don't build google cloud API client in debug and test environments

---

.vscode/settings.json
docs/source/configuration/dataset.md
snuba/datasets/configuration/dataset_builder.py
snuba/datasets/configuration/discover/dataset.yaml
snuba/datasets/configuration/events/dataset.yaml
snuba/datasets/configuration/functions/dataset.yaml
snuba/datasets/configuration/generic_metrics/dataset.yaml
snuba/datasets/configuration/groupassignee/dataset.yaml
snuba/datasets/configuration/groupedmessage/dataset.yaml
snuba/datasets/configuration/issues/dataset.yaml
snuba/datasets/configuration/json_schema.py
snuba/datasets/configuration/metrics/dataset.yaml
snuba/datasets/configuration/outcomes/dataset.yaml
snuba/datasets/configuration/outcomes_raw/dataset.yaml
snuba/datasets/configuration/profiles/dataset.yaml
snuba/datasets/configuration/replays/dataset.yaml
snuba/datasets/configuration/sessions/dataset.yaml
snuba/datasets/configuration/spans/dataset.yaml
snuba/datasets/configuration/transactions/dataset.yaml
snuba/datasets/dataset.py
snuba/datasets/pluggable_dataset.py
snuba/web/views.py
tests/web/test_check_clickhouse.py

This PR is responsible for deprecating the `is_experimental` flag in favour of readiness_states. Right now, the `is_experimental` flag is responsible for skipping health-checks of all storages of a particular dataset in all sentry environments. Now that we have readiness_states managing health-checks, we no longer need this flag.
There are two datasets that are still marked `is_experimental: true`: `search_issues` and `spans`. When this flag is removed, both these datasets will use their storage readiness_states to manage health-checks.

ref(DRS): Deprecate dataset experimental flag

---

snuba/admin/static/api_client.tsx
snuba/admin/static/dead_letter_queue/index.tsx
snuba/admin/static/dead_letter_queue/types.tsx
snuba/admin/views.py
snuba/consumers/dlq.py

Tried to make it look a bit cleaner/minimalistic. Added ability to get/post/delete the replay instruction.

feat(dlq): Redesign admin UI, add API endpoints for replaying

---

snuba/migrations/groups.py
snuba/settings/settings_self_hosted.py

The following PR is responsible for promoting the `search_issues` migration group from the `partial` readiness state to `complete` state. This enables makes the migration group visible and executable in more Sentry internal environments (ST). However, this skips the migration group in self-hosted as the dataset is not ready for it yet.

feat(search_issues): Promote search_issues migration group to complete

---

snuba/query/allocation_policies/__init__.py
snuba/query/allocation_policies/bytes_scanned_window_policy.py
tests/query/allocation_policies/test_allocation_policy_base.py
tests/query/allocation_policies/test_bytes_scanned_window_allocation_policy.py

Minor refactor to move `is_active` logic to be contained within the Allocation Policy base class. This makes it such that any new policies being added would not need to reimplement is_active logic.

ref(capman): Move is_active check to base allocation policy

---

snuba/datasets/processors/errors_processor.py
tests/datasets/test_errors_processor.py

Related to this https://github.com/getsentry/snuba/pull/4276
Extracts `trace_sampled` from the error event `data.context.trace` map.
Extracts `num_processing_errors` from the error event `data.errors` list of processing errors.
A follow-up PR will be created to expose these two new columns in the entity and discover.

feat(errors): process trace_sampled and num_processing_errors from event

---

snuba/datasets/configuration/discover/entities/discover.yaml
snuba/datasets/configuration/discover/entities/discover_events.yaml
snuba/datasets/configuration/discover/entities/discover_transactions.yaml
snuba/datasets/configuration/events/entities/events.yaml
snuba/query/snql/discover_entity_selection.py
tests/test_discover_api.py

Makes `trace_sampled` and `num_processing_errors` columns available to be queried from events and discover.

feat(errors): expose trace_sampled and num_processing_errors columns for events and discover 

---

snuba/migrations/groups.py

The sessions storages are already set to `deprecate` and this migration group should follow. Note that session this to `deprecate` means that the migrations will only be executable locally and in self-hosted. These migrations will not be executable in any other sentry environments anymore (include ST).

ref(sessions): Demote sessions migration group to deprecate

---

snuba/datasets/plans/storage_plan_builder.py
tests/datasets/plans/test_storage_plan_builder.py

Minor change: We should be getting the storage's cluster after checking that the storage is available, not before.

ref(snuba): Get cluster after checking storage availability

---

snuba/admin/cardinality_analyzer/cardinality_analyzer.py
tests/admin/cardinality_analyzer/test_metrics_query.py

We're having issues where the metric ids are too large to fit in a double and thus are being rounded and showing incorrect data.
By converting them to strings before sending them back we can avoid this issue

fix(starfish): stringify results before sending them to the client

---

snuba/clickhouse/optimize/optimize.py
snuba/clusters/cluster.py

Were in the process of migrating over the logs to use stuctured logging where possible. This makes them easier to parse in tools like GCP. The plan is to implement this module by module. This PR enables structured logging for the optimize module.

fix(logs): use structlog for optimize module

---

snuba/migrations/group_loader.py
snuba/snuba_migrations/search_issues/0009_add_message.py

This adds the `message` column to search issues, since we missed including it a column initially.
Related to https://github.com/getsentry/sentry/issues/50345

feat(search-issues): Add message column to search issues

---

snuba/datasets/configuration/issues/entities/search_issues.yaml
snuba/datasets/configuration/issues/storages/search_issues.yaml
snuba/datasets/processors/search_issues_processor.py
tests/datasets/test_search_issues_processor.py
tests/test_search_issues_api.py

This starts writing to the new `message` column. `message` is already being sent from sentry, so we just need to start writing it here.
I will let this write for a week or two before switching over to use it. We don't need the full 90 days of data for this to be effective.
Relies on https://github.com/getsentry/snuba/pull/4385
Related to https://github.com/getsentry/sentry/issues/50345

feat(search-issues): Start writing message column in search issues

---

snuba/consumers/dlq.py

Still need to count invalid messages in ExitAfterNMessages

fix(dlq): Fix invalid message counting in DLQ consumer

---

snuba/datasets/processors/outcomes_processor.py

As part of adding some backpressure handling to SDKs, we need a new Client Report reason.
see
* https://github.com/getsentry/sentry-python/pull/2189
* https://github.com/getsentry/sentry-python/issues/2095 
* https://github.com/getsentry/team-webplatform-meta/issues/50

feat(outcomes): Add new backpressure client report reason

---

snuba/datasets/processors/outcomes_processor.py

We'd like to add a new client discard reason called `insufficient_data` for the use case where the SDK did not collect enough data for a valid profile and discards it as a result.

feat(profiling): Add insufficient data as client discard reason

---

snuba/admin/auth.py
snuba/redis.py
snuba/settings/__init__.py
snuba/settings/settings_test.py
tests/admin/clickhouse_migrations/test_api.py
tests/admin/test_api.py
tests/admin/test_authorization.py

Currently, we set up a user's roles every time we make a request which is inefficient as it requires reading from a file and making multiple API requests to google. In order to improve performance, I've added a TTL cache with a 10 min TTL. Since it's unlikely for roles and groups to change, we should consider increasing this TTL in the future.

feat(admin-auth): Add TTL cache for admin roles

---

snuba/admin/auth.py
snuba/redis.py
snuba/settings/__init__.py
snuba/settings/settings_test.py
tests/admin/clickhouse_migrations/test_api.py
tests/admin/test_api.py
tests/admin/test_authorization.py

feat(admin-auth): Add TTL cache for admin roles 

---

snuba/query/allocation_policies/__init__.py
snuba/settings/__init__.py
snuba/settings/settings_test.py

- Currently there is some strong correlation between the latest query errors and timeouts on Disney ST and Allocation Policy throttles on the instance
- Disney ST max threads are 30 by default, the throttling sets the queries to 1 thread - a massive difference
- I don't believe we have a huge load problem on ST so we can probably disable the policy enforcement altogether
- Ideally this is done through Snuba Admin but since that does not yet exist for ST this is a good enough solution

fix(CapMan): Allocation Policies causing potentially timeout errors on ST

---

snuba/consumers/consumer_builder.py

We now pass enforce_schema to the process_message function. Forgot to pass it in one place.
Fix SNUBA-3CN

fix(dlq): Fixes call to process_message

---

.github/workflows/lint-pipelines.yml
.gitignore
Makefile
gocd/README.md
gocd/generated-pipelines/snuba-next-monitor.yaml
gocd/generated-pipelines/snuba-next-us.yaml
gocd/generated-pipelines/snuba-next.yaml
gocd/templates/bash/check-cloud-build.sh
gocd/templates/bash/check-github.sh
gocd/templates/bash/check-migrations.sh
gocd/templates/bash/deploy.sh
gocd/templates/bash/migrate-reverse.sh
gocd/templates/bash/migrate.sh
gocd/templates/bash/sentry-release-canary.sh
gocd/templates/bash/sentry-release-primary.sh
gocd/templates/jsonnetfile.json
gocd/templates/jsonnetfile.lock.json
gocd/templates/pipelines/snuba.libsonnet
gocd/templates/snuba.jsonnet

This introduces a new set of GoCD pipelines generated from jsonnet.
1. deploy snuba (a noop pipeline that starts the pipedream flow)
1. deploy snuba US (What is currently snuba-deploy)
1. deploy snuba monitor (Deploys to a single tenant style region)
**The main differences from the current snuba.yaml pipeline**:
1. The migrate step is now run with approval
1. There were some differences in the canary and prod deploy tasks. Canary had the container `dlq-consumer` and prod didn't. Production has the container `rust-querylog-consumer` and canary didn't. I've merged the two steps into one shell script and the label selector for canary vs prod is now managed by an environment variable.
Please let me know if either of the both should be changed some other way.

Introduce pipedream

---

gocd/generated-pipelines/snuba-next-monitor.yaml
gocd/generated-pipelines/snuba-next-us.yaml
gocd/generated-pipelines/snuba-next.yaml
gocd/templates/jsonnetfile.lock.json

This does *not* change the functionality of the piplines, it puts all the pipelines in one group and it defines an order for the pipelines.

Use a single GoCD group and order pipelines

---

snuba/consumers/consumer_builder.py

We are seeing increased consumer lag, and ONCE_PER_SECOND makes it hard
to control/predict it, which makes alert config harder.
Partially reverts https://github.com/getsentry/snuba/pull/4251

fix: Revert debounced commits

---

snuba/admin/static/index.tsx

- Watching a Snuba Admin replay shouldn't block any text, there's no PII
- It would be nice to see exactly the query strings etc that are being input

feat(admin): Stop blocking text/images on Snuba Admin replays

---

snuba/datasets/configuration/spans/storages/spans.yaml
tests/test_spans_api.py

Add `group_raw` to the HexIntColumnProcessor because
right now we return the raw int and we'd like to return
the hash instead as we do with `group`

fix(spans): Add `group_raw` to HexIntColumnProcessor

---

snuba/admin/auth_roles.py
tests/admin/test_authorization.py

This PR adds the production queries tool to the list of product tools in order to expose it to all sentry engineers.

Add production queries tool to product tools

---

snuba/admin/static/query_editor.tsx
snuba/admin/static/tests/query_editor.spec.tsx

There is a bug in the query editor where the RichTextEditor would strip a query's backticks and style the code block instead. This PR replaces the RichTextEditor with the TextArea component from mantine and fixes this bug.

fix(admin): Use text area instead of rich text editor for QueryEditor

---

snuba/admin/iam_policy/iam_policy.json

Give the entire ingest team permission to use the cardinality analyzer.

perm(cardinality-analyzer): Add ingest team

---

snuba/settings/__init__.py
snuba/settings/settings_test.py
snuba/state/cache/redis/backend.py
tests/state/test_cache.py

Sometimes redis has a fit. That's not good but not catastrophic. If the readthrough cache fails due to a redis issue, just run the function normally, don't slow everything to a halt

feat(oncall): Make readthrough cache fail open on redis errors

---

gocd/generated-pipelines/snuba-next-monitor.yaml
gocd/generated-pipelines/snuba-next-us.yaml
gocd/templates/bash/migrate-reverse.sh
gocd/templates/bash/migrate-st.sh
gocd/templates/bash/migrate.sh
gocd/templates/pipelines/snuba.libsonnet

I noticed that s4s has slightly differently migration steps for s4s and ST deployments.
This PR moves the container name / service name to an environment variable so we can re-use the migrate-reverse script on all regions and then there is a second script for the ST deployments migration.
Hopefully in the future we can merge the migration scripts, but this is the safest approach to avoid breaking things for now.

Add script for customer deployments

---

snuba/web/db_query.py

The concurrent throttler is possibly cramping our performance too much. It's also a hidden part of our allocation policy which needs to become explicit. 
This PR allows turning off that functionality so we can run an experiment to tell us how much it actually impacts things

experiment(capman,starfish): add ability to turn off concurrent throttling

---

gocd/pipelines/snuba.yaml

Adding a role permission to the migration stage. This will limit the migration stage access to only people in the `role-deploy-snuba-operator` google group. Ideally, this group should have been called `role-deploy-snuba-migrations-operator` but it's hard to change names on the dev-infra GoCD side.

Add GoCD role to migrations stage

---

snuba/admin/static/production_queries/index.tsx
snuba/admin/static/production_queries/types.tsx

Made some general UI improvements:
- Execution Duration
- Spinner while executing query
- Better looking textbox, dataset selection, and button using Mantine

feat(prod-queries): Improve UI components and add execution duration

---

snuba/datasets/processors/replays_processor.py
tests/datasets/test_replays_processor.py
tests/test_replays_api.py

The `title` column was recently made nullable.  We should ingest title as null so we can properly aggregate the non-null transaction names (stored on the title field).

feat(replays): Ingest null title as null

---

gocd/generated-pipelines/snuba-next-monitor.yaml
gocd/generated-pipelines/snuba-next-us.yaml
gocd/templates/pipelines/snuba.libsonnet

Noticed a naming mistake in the pipedream deploy-primary name.

Fix typo in snuba pipelines

---

snuba/admin/static/api_client.tsx
snuba/admin/static/data.tsx
snuba/admin/static/snql_to_sql/index.tsx
snuba/admin/static/snql_to_sql/types.tsx
snuba/admin/static/snuba_explain/index.tsx
snuba/admin/static/snuba_explain/step_render.tsx
snuba/admin/static/snuba_explain/styles.tsx
snuba/admin/static/snuba_explain/types.tsx
snuba/admin/static/snuba_explain/utils.tsx
snuba/admin/tool_policies.py
snuba/datasets/plans/storage_plan_builder.py
snuba/pipeline/composite.py
snuba/state/explain_meta.py
tests/admin/test_api.py

Add a basic frontend for the explain data that is being sent by the endpoint.
This adds a new tool called Snubsplain to the admin tool, which when provided a
SnQL query will show the list of query processors that ran.
Frontend Changes:
- Create a new Snuba Explain tool that uses the meta data returned from calling
the debugSnQLQuery endpoint
- Build a basic framework for rendering different steps of the query pipeline
- Show the names of the query processors that ran and in what order
- Show the final Clickhouse SQL that ran
Backend Changes:
- Capture the storage query processor names
- Set up some standard dataclasses for capturing explain meta data

feat(snubsplain): Add basic frontend for snubsplain

---

requirements.txt
snuba/clickhouse/native.py
snuba/web/db_query.py
snuba/web/query.py

The sentry performance product expects that `db` spans actually query the DB. Our code is not like that atm. Put a span close to db execution and make the span description the actual sql query. This will allow us to dogfood new performance features

feat(observability): Use spans more accurately in snuba

---

gocd/generated-pipelines/snuba-next-monitor.yaml
gocd/templates/bash/deploy-st.sh
gocd/templates/pipelines/snuba.libsonnet

After running the snuba pipedream on s4s I noticed a few differences and issues I missed.
1. Canary deployments are only needed for saas deployments (a.k.a 'US' region)
2. ST deployments deploy with `--container-name="snuba"` which isn't in the list of containers for saas, so I've opted to create a deploy script for ST deployments that match what we use at the moment.

Fix deployments for snuba on ST regions

---

snuba/request/validation.py
tests/request/test_build_request.py

In order to port the project based rate limiters to the capman framework, we have to have project ids as tenants, we currently do not. Add logic in the `build_request` function to add `project_id` to `AttributionInfo.tenant_ids`
This logic makes an explicit decision that when there are multiple projects being searched in one request, there is no project tenant, instead the organization_id becomes the tenant.

feat(capman): add project_id as implicit tenant

---

snuba/query/allocation_policies/__init__.py
snuba/query/allocation_policies/bytes_scanned_window_policy.py
snuba/web/db_query.py
tests/admin/test_api.py
tests/query/allocation_policies/test_allocation_policy_base.py
tests/query/allocation_policies/test_bytes_scanned_window_allocation_policy.py
tests/test_snql_api.py
tests/web/test_db_query.py

Rate limiting mechanisms need a query id to keep track of. Allocation policy does not have such a concept so I'm introducing it here.

feat(capman): pass query_id into allocation policy

---

snuba/admin/static/clickhouse_queries/index.tsx
snuba/admin/static/clickhouse_queries/query_display.tsx
snuba/admin/static/tests/tracing/index.spec.tsx
snuba/admin/static/tracing/index.tsx
snuba/admin/static/tracing/query_display.tsx
snuba/admin/static/tracing/types.tsx

The following PR is responsible for migrating the System Queries and Tracing Tool to use the [query_editor](https://github.com/getsentry/snuba/blob/master/snuba/admin/static/query_editor.tsx) component. Doing so provides consistency among all query tools in admin and fixes some text input bugs.
System Queries:
Tracing Tool:

feat(admin): Make System Queries and Tracing Tool use query editor component

---

snuba/cli/consumer.py
snuba/migrations/connect.py
snuba/settings/__init__.py

Sometimes it takes envoy sidecar a while to load. Instead of crashlooping immediately, this lets snuba consumers spin for 60 clickhouse connection attempts at startup to check connectivity before running.

check connections on consumer startup

---

snuba/consumers/consumer.py

I was digging the off-by-one error in snuba commit log issue. I prepared two-line fix for 23.3.1 but soon I found the one-line fix (#4297) was merged in last month. I think the rest should be fixed too.

Fix MultistorageCollector as #4297

---

snuba/migrations/group_loader.py
snuba/snuba_migrations/generic_metrics/0014_distribution_add_options.py
snuba/snuba_migrations/generic_metrics/0015_sets_add_options.py
snuba/snuba_migrations/generic_metrics/0016_counters_add_options.py

| [#1](https://github.com/getsentry/snuba/pull/4467) | ➤ Add aggregation options for generic metrics raw tables | Ready for review          | master                                               |
| [#2](https://github.com/getsentry/snuba/pull/4477) | Add new MatViews for generic metrics | Ready for review | [#1](https://github.com/getsentry/snuba/pull/4467) |
| [#3](https://github.com/getsentry/snuba/pull/4478) | Bump …

feat(generic-metrics): Add aggregation options for generic metrics raw tables

---

rust_snuba/src/strategies/clickhouse.rs

We did this in the other strategies, forgot to do in the clickhouse one

fix: Actually resubmit carried over message in clickhouse strategy

---

snuba/migrations/group_loader.py
snuba/snuba_migrations/generic_metrics/0017_distributions_mv2.py

| [#1](https://github.com/getsentry/snuba/pull/4467) | Add aggregation options for generic metrics raw tables | Merged         | master                                               |
| [#2](https://github.com/getsentry/snuba/pull/4504) | ➤ Add new MatView for generic distribution metrics | Approved | master |
| [#3](https://github.com/getsentry/snuba/pull/4509) | Add facilities to insert aggregation options in processor …

feat(generic-metrics): Add new MatView for generic distribution metrics

---

snuba/clusters/storage_sets.py
snuba/migrations/group_loader.py
snuba/migrations/groups.py
snuba/settings/__init__.py
snuba/settings/settings_distributed.py
snuba/settings/settings_test_distributed_migrations.py
snuba/snuba_migrations/group_attributes/0001_group_attributes.py

This new dataset replicates a subset of crucial values from the Groups, GroupAssignee and GroupOwners postgres tables. 
The plan is to stream the latest 'snapshot' values described in the schema every time any of the postgres column values are updated/created/deleted. 
The latest snapshot will always replace the oldest snapshot and eventually get replaced by clickhouse. 
Note: for the time being, this table should only be available in SaaS and in 'prototype' mode. We want to verify joins between the events/search_issues and this table works as expected and that most straight-forward way was to build the dataset, insert some data, and execute some parallel issue search queries to verify.

migration(group_attributes): create new GroupAttributes table that mirrors a subset of columns from sentry

---

snuba/cli/subscriptions_executor.py
snuba/cli/subscriptions_scheduler.py
snuba/cli/subscriptions_scheduler_executor.py

Our subscriptions containers are starting up before the connections to clickhouse are ready. This add a check to attempt to connect to clickhouse for 60s before starting up the consumers.

feat(subscriptions): add clickhouse connection check

---

snuba/datasets/metrics_messages.py
snuba/datasets/processors/generic_metrics_processor.py

| [#1](https://github.com/getsentry/snuba/pull/4467) | Add aggregation options for generic metrics raw tables | Merged         | master                                               |
| [#2](https://github.com/getsentry/snuba/pull/4504) | Add new MatView for generic distribution metrics | Merged | master |
| [#3](https://github.com/getsentry/snuba/pull/4509) | ➤ Add facilities to insert aggregation options in processor | …

feat(generic-metrics): Add facilities to insert aggregation options in processor

---

snuba/datasets/metrics_messages.py

| [#1](https://github.com/getsentry/snuba/pull/4467) | Add aggregation options for generic metrics raw tables | Merged         | master                                               |
| [#2](https://github.com/getsentry/snuba/pull/4504) | Add new MatView for generic distribution metrics | Merged | master |
| [#3](https://github.com/getsentry/snuba/pull/4509) | Add facilities to insert aggregation options in processor | …

feat(generic-metrics): Bump `materialization_version` to 2 for generic distribution metrics

---

rust_snuba/src/consumer.rs
rust_snuba/src/strategies/clickhouse.rs

Also fixes a bug where rejected messages from the subsequent step could be dropped.
Increases concurrency to 2 in line with https://github.com/getsentry/snuba/pull/4516 in python consumer

feat(rust-consumer): Support parallel insert to ClickHouse

---

gocd/generated-pipelines/rollback-snuba.yaml
gocd/generated-pipelines/snuba-monitor.yaml
gocd/generated-pipelines/snuba-us.yaml
gocd/generated-pipelines/snuba.yaml
gocd/pipelines/snuba.yaml
gocd/templates/snuba.jsonnet

This switches the snuba pipelines over to pipedream which will deploy to monitor (s4s) and then saas.
The only difference this will have for the current pipeline is that pipedream will run migrations as part of the deployment, it will no longer be an optional & manual step at the end of the pipeline. This was discussed with @dbanda 
NOTE: The old pipelines will still be available but will be moved to a new group "snuba-old" in case they are needed during the transition.

Switch to pipedream pipelines

---

gocd/generated-pipelines/snuba-monitor.yaml
gocd/generated-pipelines/snuba-us.yaml
gocd/templates/pipelines/snuba.libsonnet

Snuba s4s doesnt have any canary pods, but the create sentry release script for canary step makes the release which is needed for the prod deployment

Fix canaries and migrations in s4s snuba

---

snuba/state/rate_limit.py
tests/state/test_rate_limit.py

The allocation policy infrastructure assumes theres a start and a finish of a query, the rate limit code is a context manager which assumes everything happens in a specific block.
This PR:
* Splits apart the rate limit function into two reusable components
* Adds a test for the fail open case for the rate limiter (which wasn't tested before)
* maintains the context manager abstraction so everything still works as before

ref(capman): split the rate limit function into a start and finish phase

---

snuba/datasets/processors/querylog_processor.py

We don't need this all this fallback logic, "profile" is not optional: https://github.com/getsentry/snuba/blob/e369d972756d7cfb4415be942f1b38b371844a8f/snuba/querylog/query_metadata.py#L192

ref: Simplify querylog processor more

---

snuba/cli/devserver.py
snuba/datasets/configuration/group_attributes/dataset.yaml
snuba/datasets/configuration/group_attributes/entities/group_attributes.yaml
snuba/datasets/configuration/group_attributes/storages/group_attributes.yaml
snuba/datasets/processors/group_attributes_processor.py
snuba/settings/__init__.py
snuba/settings/validation.py
snuba/utils/streams/topics.py
tests/admin/dead_letter_queue/test_dlq.py
tests/datasets/test_dataset_factory.py
tests/datasets/test_entity_factory.py
tests/datasets/test_group_attributes_processor.py
tests/test_group_attributes_api.py

Part 2 of getting group_attributes dataset stood up. This should only be made available in CI and dev. 
* defines the topic for consuming write messages and the dead letter topic 
* defines the storage for the dataset
* defines the entity
* implements a basic processor to start writing to the table
I'll create a follow-up PR to define the join relationships between the entities along with appropriate tests. Just wanna start processing the messages and begin writing to the table in this PR.
I verified this locally by doing the following:
* Running snuba locally with this consumer enabled: `ENABLE_GROUP_ATTRIBUTES_CONSUMER="1" snuba devserver` 
* Produce a message to the topic using an example json message from [sentry-kafka-schemas](https://github.com/getsentry/sentry-kafka-schemas/blob/mai …

feat(group-attributes): expose storage and entity, process messages

---

snuba/admin/static/cardinality_analyzer/CSV.ts
snuba/admin/static/cardinality_analyzer/query_display.tsx
snuba/admin/static/tests/cardinality_analyzer/CSV.spec.ts

The "Copy to clipboard (CSV)" button is great, but it doesn't escape double quotes in the CSV, so the content is sometimes mangled. This is a fix.
- Prettier
- Remove unused variables
- Add some more typing
- Extract CSV class
- Add spec

fix(cardinality-analyzer): Fix CSV escaping

---

rust_snuba/rust_arroyo/src/processing/strategies/mod.rs
rust_snuba/rust_arroyo/src/processing/strategies/run_task_in_threads.rs
rust_snuba/rust_arroyo/src/processing/strategies/transform.rs
rust_snuba/rust_arroyo/src/types/mod.rs
rust_snuba/src/strategies/clickhouse.rs
rust_snuba/src/strategies/mod.rs
rust_snuba/src/strategies/python.rs

Break the task scheduling code out of the Clickhouse writer strategy so it can be used for parallel execution of any functions, such as custom message processors.
The ClickHouse strategy now uses RunTaskInThreads under the hood.

feat(rust-consumer): Add RunTaskInThreads strategy

---

snuba/consumers/consumer.py
snuba/datasets/processors/spans_processor.py
snuba/replacer.py
snuba/state/__init__.py
tests/state/test_state.py

User should specify the type when fetching config. Now there are 3 new methods: `get_int_config()`, `get_float_config()` and `get_str_config()`. `get_config()` is deprecated as returning Any is a source of bugs and usually requires the user to cast to the correct type in their own code anyway.
We also want to call this method from the Rust consumer so we can access runtime config there, and we should not allow these untyped values there either.

feat: Banish fetching untyped runtime config

---

gocd/generated-pipelines/snuba-s4s.yaml
gocd/templates/pipelines/snuba.libsonnet

Noticed that s4s was missing the ST migration step because of the rename - using the library version fixes this and should avoid future issues.

Switch is ST check to library version

---

gocd/pipelines/snuba.yaml

I didn't acknowledge that using a different group would impact the roles managing view, operate and admin access.
This PR moves the old pipeline back to the snuba group with appropriate access roles.

Revert back to snuba group for role access

---

.github/workflows/validate-pipelines.yml
Makefile
gocd/templates/jsonnetfile.json
gocd/templates/jsonnetfile.lock.json

This change does the following:
- Update the gocd-jsonnet libs such that it supports output multiple files OR a single file. The single file will be used by the GoCD jsonnet plugin (the pipelines will be exactly the same in GoCD)
- Update the validation workflow to use the single file fixing the gocd validation action.
#skip-changelog

Fix GoCD pipedream validation

---

snuba/datasets/processors/transactions_processor.py
tests/datasets/test_transaction_processor.py

The `received` field is (most likely) always present in transaction payloads, but we currently don't do anything with it in the relevant MessageProcessor. This PR allows us to grab the timestamp at which Relay received the transaction and pass it into the SLO calculation, to help us get the ingest transactions SLO. 
I think, if we are confident that we are always containing the `received` field, then we should change the Kafka schema to make `received` a required field. Need to verify this is the case though.

feat(consumer): Add transactions consumer SLO

---

snuba/admin/static/api_client.tsx
snuba/admin/static/production_queries/index.tsx
snuba/admin/views.py

This adds the ability to view all allowed project ids.

feat(prod-queries): Add button to view all allowed projects

---

snuba/web/query.py

This metric is not very useful atm because we don't really care how many queries we're executing in aggregate. We need to know which tables we're hitting and which referrer is doing it. Split up this metric by those dimensions

feat(oncall): break down query execution metrics by table and referrer

---

snuba/query/allocation_policies/__init__.py
snuba/web/__init__.py
snuba/web/db_query.py
tests/test_snql_api.py
tests/web/test_db_query.py
tests/web/test_result_cache_codec.py

- This PR brings the readthrough cache hit check to the beginning of db_query
- Previously, db_query did the following:
- Check Allocation policy quotas
- ...
- Check cache
- ...
- New behavior:
- Check cache
- Check allocation policy quotas
- ...
This will enable bringing rate limits to Allocation policies without rate-limiting queries that would have otherwise been cached
- Entire `QueryResult` is now cached and returned instead of just `Result`
- This means `QueryExtraData` is cached with each query containing:
- `stats`
- `sql`
- `experiments`

feat(db_query): Readthrough Cache entire `db_query()` pipeline

---

snuba/query/allocation_policies/__init__.py
snuba/query/allocation_policies/bytes_scanned_window_policy.py
tests/query/allocation_policies/test_allocation_policy_base.py

It turns out that allocation policies don't have `is_enforced` built in to them like I thought. This is especially bad because the UI makes it look like it is. Fix the bug and also make the metrics which the `BytesScannedWindowAllocationPolicy` outputs be outputted by default

fix(capman): Bake in `is_enforced` behavior into every allocation policy

---

snuba/cli/consumer.py
snuba/cli/subscriptions_executor.py
snuba/cli/subscriptions_scheduler.py
snuba/cli/subscriptions_scheduler_executor.py
snuba/consumers/consumer_builder.py
snuba/consumers/strategy_factory.py
snuba/subscriptions/combined_scheduler_executor.py
snuba/subscriptions/executor_consumer.py
snuba/subscriptions/scheduler_consumer.py
tests/cli/test_consumer.py
tests/cli/test_subscriptions.py
tests/subscriptions/test_combined_scheduler_executor.py
tests/subscriptions/test_scheduler_consumer.py
tests/test_consumer.py

Add a health check step to consumers. The health check touches a file `tmp/health.txt`  at regular intervals. In k8s, we can check for this file to see if our consumer is up and running and healthy. This can be use avoid k8s rolling over to consumer pods that are unhealthy or haven't yet completed their setup.
needs: https://github.com/getsentry/arroyo/pull/274

feat(consumer): add health check step to consumers

---

snuba/clusters/storage_sets.py
snuba/datasets/configuration/events/entities/events.yaml
snuba/datasets/configuration/group_attributes/storages/group_attributes.yaml
tests/datasets/test_group_attributes_join.py

Adds a join relationship between the events and group_attributes entities. Also added the `ConsistencyEnforcerProcessor` to the group_attributes storage to ensure any queries targeting that table will see de-duped rows.

feat(group_attributes): add ability to join events -> group_attributes 

---

snuba/datasets/configuration/group_attributes/storages/group_attributes.yaml

Did some verification in SaaS and as far as I can tell everything seems to be looking good. All the infra appears to be working as expected so we should bump this readiness up appropriately

feat(group_attributes): bump readiness for the storage so it can be queried 

---

snuba/query/allocation_policies/concurrent_rate_limit.py
tests/query/allocation_policies/test_concurrent_rate_limit_policy.py

Our current policy is to not rate limit subscriptions, this puts that policy in code

feat(capman): pass through subscriptions for new concurrent rate limiter

---

gocd/generated-pipelines/rollback-snuba.yaml
gocd/templates/jsonnetfile.json
gocd/templates/jsonnetfile.lock.json

This is needed since pipedream rollbacks expect all pipelines to be on the same SHA, which may not be true for test regions

Remove the test regions from rollbacks

---

snuba/web/db_query.py

- During the Readthrough cache removal process it was noticed that most subscriptions queries will have to hit ClickHouse twice as the queries look the same and generate the same Query ID
- First to be rejected because Query is already running (duplicate query ID)
- Second to actually run the query with a randomized ID
- Added support for randomized Query ID being the initial query ID instead of hash of the Query
- Locked behind runtime config `randomize_query_id`

feat(db_query): Randomized Query IDs

---

snuba/query/allocation_policies/concurrent_rate_limit.py
tests/query/allocation_policies/test_concurrent_rate_limit_policy.py

With the existing override implementation, the rate limit key was never differentiated which would make overrides:
1. Not work for increasing limits
2. Eat away from the default
Example:
Let's say we have a `referrer_project_override` for `project_id=1` and `referrer=statistical_detectors`, any query hitting the `statistical_detectors` referrer would eat away at the concurrent limit from all other referrers and vice versa. While this is not explicitly "bad", it's confusing behavior.
Makes it so any overriden tenants consume from their own bucket, avoiding collisions.
This policy is not enforced anywhere yet so now is a good time to approve this

fix(capman): rate limit overrides should not collide

---

.github/workflows/ci.yml

Use the docker build step to use more aggressive caching. Also fixes a bug where we were not always pulling images into the cache. I found this shaved off a 2-3 minutes in CI since we were not always building the image at each step.

fix(ci): improve caching

---

snuba/pipeline/settings_delegator.py
snuba/query/query_settings.py
snuba/web/db_query.py
tests/web/test_db_query.py

Adding the ability to override query settings using the `async_query_settings/` prefix in runtime config. These async query settings take priority over regular query settings, but cluster specific query settings take priority over async query settings.

feat(async-queries): Add ability to override query settings for async queries

---

snuba/clusters/storage_sets.py
snuba/datasets/configuration/issues/entities/search_issues.yaml
tests/datasets/test_group_attributes_join.py

Essentially a copy of https://github.com/getsentry/snuba/pull/4586 but adding the ability to do left joins between search_issues -> group_attributes.

feat(search_issues): add join relationship between search_issues and group_attributes

---

snuba/web/query.py

This tag isn't [visible](https://app.datadoghq.com/metric/explorer?start=1691596522370&end=1691600122370&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKGniqyBoieABGGAB0GPIQjXDEcJkEcMAAVDzNGk6Z+CIIABQAlCA8ALpUru54mKHhS6orGDGl8bMLIBpyaDmg8hgnCAg5STgwI6saEJmJaKJwTnKK5ThvUK-vJz0JjKERuDxoWb8CD2TBYT4KG5vERKeY8PiHeRvBAAYSkwhgKFqaDQPCAA), try hitting `sum by`, I only see referrer and table. Maybe `data` is a ddog key word, we use `dataset` in other metric tags usually.

fix(oncall): Query execution dataset metric tag

---

snuba/consumers/schemas.py

One of the topics is known to have quite a bit of invalid data and is drowning out the rest. This makes it easier to assign fixing these errors for each topic separately as they are typically unrelated.

feat: Group the validation warnings for each topic separately

---

snuba/state/cache/redis/backend.py

Redis Cache fail open was already done here:
#4449 
Updated it to include `ValueError` which is thrown by the ResultCacheCodec upon decoding a value it cannot read. This was the main [error](https://sentry.sentry.io/issues/4360761362/?end=2023-08-02T06%3A59%3A59&project=300688&query=ValueError&referrer=issue-stream&start=2023-08-01T07%3A00%3A00&stream_index=0) rejecting queries in INC-474.

fix(Cache): Cache fail open on ValueError

---

snuba/migrations/group_loader.py
snuba/snuba_migrations/spans/0005_spans_nodestore_version.py

We are trying a new scheme for storing span contexts in nodestore. As such we do not know whether it would cause problems or not. So we need to have schema version used when storing contexts in nodestore to link things correctly. Added a migration to add nodestore_column in the spans schema. Added a Delta encoding since most times we would only have 1 value in the column.

feat(spans): Add migration to fill nodestore version column

---

snuba/migrations/group_loader.py
snuba/snuba_migrations/spans/0005_spans_add_sentry_tags.py

Adds a migration to add the `sentry_tags` , and `_sentry_tags_hash_map`  hash map,  columns to the spans tables. These columns are identical to `tags` but are used for storing sentry extracted tags. We do this to keep the user tags separate from the sentry tags.

migration(spans): add sentry tags cols

---

tests/conftest.py

Instead of running migrations from start to finish each time before a clickhouse, we can cache the end result of applying all migrations and use that instead. We are not adding new migrations within test so that should be fine. This will speed up CI.

fix(ci): cache migrations in ci

---

snuba/subscriptions/executor_consumer.py
snuba/web/constants.py

This is a follow up from INC-395. We should not constantly retry when we get these errors, as it blocks execution of all other subscriptions queries.

feat: Don't retry subscriptions queries which get timeout or OOM from clickhouse

---

tests/datasets/test_generic_metrics_processor.py

Adds the missing assertion to the `test_aggregation_option_is_converted_to_column `

fix(test): Add missing assertion for metrics processor test

---

docker-compose.gcb.yml
rust_snuba/src/strategies/clickhouse.rs

Previously we were treating successful and failed ClickHouse inserts the same, and we simply commit the offset once we get a result from ClickHouse. It's probably better to retry in at least some scenarios. Now the thread will panic. That is probably also not quite right but it's better than silently failing at least for testing purposes.
There was also a bug in the ClickHouse test uncovered by this change. Now we run Snuba migrations in CI before the Rust tests, as it depends on the querylog table being there.

feat(rust-consumer): Handle failed inserts

---

.github/workflows/ci.yml
docker-compose.gcb.yml
tests/test_cleanup.py
tests/test_discover_api.py
tests/test_snql_api.py

We had an issue today where a migration ran on Clickhouse 20 but failed on Clickhouse 21. This adds a test for Clickhouse 21. This is kept outside the matrix to allow it to be optional. This PR relies on using cached migrations in ci #4622  so that we can finish the tests in a reasonable amount of time.
* For some discover API tests, Clickhouse 21 returns no rows whereas Clickhouse 20 would return a count of 0. To fix this, we try the asserts for both cases. 
* Because migrations seem to run faster on 21, we also make the setup function in the discover api test a fixture that runs after the clickhouse_db fixture to guarantee the ordering and avoid a race.
* In the cleanup test, we use a future Sunday date  as the base to avoid hitting the TTLs. Clickhouse 21 tends to work quicker and …

feat(ci): Test Clickhouse 21

---

snuba/state/cache/redis/backend.py
tests/state/test_cache.py

- Currently, the Redis Cache fails open on a select few Exceptions
- Differentiating between a redis failure vs clickhouse failure isn't really established in the fail-open logic
- This PR adds a way to identify errors raised by the value generation function execution step within the readthrough cache, since those are the only errors should actually fail the query
- Any exception raised during value gen function is wrapped with `ValueGenerationError` which is then later caught and the original exception is raised
- All other errors fail open, ie executes the value generation function which routes the query to ClickHouse instead
- Previously only a metric `snuba.read_through_cache.fail_open` was incremented upon cache fail-opens
- Now a warning is also logged with the exception stack …

feat(cache): More generalized cache fail-open

---

snuba/snuba_migrations/spans/0005_spans_add_sentry_tags.py

There an issue in Clickhouse where the arrayMap function passes in Nothing type values for empty arrays. This causes the regex function to fail on the newly added columns without the toString function, unless a merge for the part is completed first. So our replication task queue was building up with all task that were failing and Clickhouse keeps retrying until it get lucky and a merge happens before.
This is fixed in Clickhouse 22.

fix(spans): fix sentry tags migration

---

rust_snuba/src/processors/querylog.rs

Result profile can be null, for example in https://github.com/getsentry/sentry-kafka-schemas/blob/main/examples/snuba-queries/1/rate-limited-real.json

fix(rust-consumer): Handle nullable result profile

---

rust_snuba/Cargo.lock
rust_snuba/Cargo.toml
rust_snuba/src/consumer.rs
rust_snuba/src/processors/mod.rs
rust_snuba/src/processors/querylog.rs
rust_snuba/src/strategies/python.rs
rust_snuba/src/types.rs

Rust message processors should get passed the Kafka metadata like the Python one. This is needed since a number of processors actually write the partition and offset information to ClickHouse

feat(rust-consumer): Port KafkaMessageMetadata to Rust

---

snuba/cli/api.py
snuba/cli/subscriptions_executor.py
snuba/cli/subscriptions_scheduler_executor.py
snuba/querylog/__init__.py
tests/test_snql_api.py
tests/test_snql_sdk_api.py

This consumer is not being used by anyone, and is mostly obsolete due to
COGS/CapMan. There's no point keeping it running since it's just one more thing
to support.
Plan to remove:
[ ] Stop writing to the log (this PR)
[ ] Remove deployments of consumers (separate PRs)
[ ] Remove attribution code

ref(attribution): Stop writing to attribution consumer

---

snuba/web/db_query.py
tests/web/test_db_query.py

The existing SLO calculation depends on the `query_metadata_list` being updated with the correct request status. Make sure that is done for allocation policy rejections even though no query ever runs. This is not the prettiest way to do it but it unblocks getting rate limiters onto capman and we are redoing how the SLO is calculated anyways

hack(capman): allocation policy violations don't impact SLO

---

rust_snuba/Cargo.lock
rust_snuba/Cargo.toml
rust_snuba/rust_arroyo/Cargo.toml
rust_snuba/rust_arroyo/src/backends/kafka/mod.rs
rust_snuba/src/consumer.rs

Fixes failing CI since Arroyo dependencies are not currently pinned.

build: chrono 0.4.26 and remove use of deprecated function

---

rust_snuba/Cargo.toml

So that rust_snuba and rust_arroyo use the same (pinned) library versions of packages

build: Cargo workspace

---

.github/workflows/ci.yml

Job is flaky, and we've decided instead to run this on a more frequent basis until we can invest more into these tests in self-hosted to reduce CI usage.

chore(self-hosted): Remove self-hosted e2e action

---

snuba/cli/rust_consumer.py

A recent PR changed the default, and until this is fixed we may be
writing additional rows into querylog.

fix(rust_consumer): Fix wrong default for --skip-write

---

snuba/query/allocation_policies/bytes_scanned_window_policy.py

[This commit](https://github.com/getsentry/snuba/pull/4611) broke our dashboards that record bytes_scanned because it was part of the old attribution system.  We still need to observe that metric tho. 
Emit the bytes_scanned metric from the BytesScannedWindowAllocationPolicy on a per-referrer basis

fix(observability): emit bytes_scanned metric

---

snuba/datasets/configuration/discover/storages/discover.yaml
snuba/datasets/configuration/events/storages/errors.yaml
snuba/datasets/configuration/events/storages/errors_ro.yaml
snuba/datasets/configuration/functions/storages/functions.yaml
snuba/datasets/configuration/generic_metrics/storages/counters.yaml
snuba/datasets/configuration/generic_metrics/storages/distributions.yaml
snuba/datasets/configuration/generic_metrics/storages/org_counters.yaml
snuba/datasets/configuration/generic_metrics/storages/sets.yaml
snuba/datasets/configuration/group_attributes/storages/group_attributes.yaml
snuba/datasets/configuration/groupassignee/storages/group_assignees.yaml
snuba/datasets/configuration/groupedmessage/storages/grouped_messages.yaml
snuba/datasets/configuration/issues/storages/search_issues.yaml
snuba/datasets/configuration/outcomes/storages/hourly.yaml
snuba/datasets/configuration/outcomes_raw/storages/raw.yaml
snuba/datasets/configuration/profiles/storages/profiles.yaml
snuba/datasets/configuration/replays/storages/replays.yaml
snuba/datasets/configuration/spans/storages/spans.yaml
snuba/datasets/configuration/transactions/storages/transactions.yaml
tests/admin/test_api.py
tests/web/test_db_query.py

This policy is already running on transactions, this PR:
* Adds a concurrent limit policy to every other storage we care about
* Does not enforce it (we will turn on enforcement on a one-by-one basis)
* Paves the way to remove all the existing rate limit processors we have in production

feat(capman): Add concurrent rate limit policy to all storages

---

snuba/datasets/processors/spans_processor.py
tests/datasets/test_spans_payloads.py
tests/datasets/test_spans_processor.py
tests/test_spans_api.py

Since Relay controls span metrics and standalone span extractions, we don't need this allowlist anymore.

feat(spans): Remove allowlist in favor of Relay's feature flag

---

Dockerfile
rust_snuba/Cargo.lock
rust_snuba/Cargo.toml
rust_snuba/rust_arroyo/Cargo.toml
rust_snuba/rust_arroyo/src/processing/mod.rs
rust_snuba/rust_arroyo/src/utils/metrics.rs
rust_snuba/src/config.rs
rust_snuba/src/consumer.rs
rust_snuba/src/lib.rs
rust_snuba/src/metrics/mod.rs
rust_snuba/src/metrics/statsd.rs
rust_snuba/src/metrics/testing.rs
rust_snuba/src/processors/mod.rs
snuba/consumers/consumer_config.py

Add statsd and testing metric backends to rust_snuba. Remove the metric implementation and dependency on cadence from Arroyo - users of Arroyo should provide the trait implementation.
Pass the dogstatsd host and port from Python to Rust via config.
Also start logging one metric ("arroyo.consumer.join.time") to verify it works.

feat(rust-consumer): Configure metrics for Rust consumer

---

snuba/datasets/processors/functions_processor.py

Since we started accepted timestamps for Android profiles as an optional field, this started to crash. We have a bunch of profiles without timestamps on the topic so this is a workaround to still ingest them.
We're also fixing the pipeline upstream to fall back on the older value if the timestamp is not sent.
https://github.com/getsentry/vroom/pull/307

fix(profiling): Handle null timestamps for functions

---

snuba/datasets/processors/spans_processor.py
tests/datasets/test_spans_payloads.py
tests/datasets/test_spans_processor.py

The old pipeline was populating tags with fields that have since been to moved to the `sentry_tags` field of the payload. 
To make the new only spans pipeline compatible with the old one, populate the tags column with any leftover tags in the `sentry_tags` field. Eventually, these should all be going in the new `sentry_tags` columns in Clickhouse to keep them separate from user tags and avoid overwrites from conflicting tags.

feat(spans): populate the tags column with leftover sentry tags

---

rust_snuba/rust_arroyo/src/processing/mod.rs
rust_snuba/rust_arroyo/src/processing/strategies/mod.rs
rust_snuba/rust_arroyo/src/processing/strategies/produce.rs
rust_snuba/rust_arroyo/src/processing/strategies/reduce.rs
rust_snuba/rust_arroyo/src/processing/strategies/run_task_in_threads.rs

We are skipping committing offsets in a fewplaces since we are not doing anything with the CommitRequest in some strategies. `ProcessingStrategy.poll()` and `ProcessingStrategy.join()` are annotated must_use to avoid this happening in future.
Added a TODO for committing offsets in the revocation callback, we are not doing anything with them currently.

fix(rust): CommitRequest must be used

---

snuba/migrations/group_loader.py
snuba/snuba_migrations/replays/0014_add_id_event_columns.py

As part of https://github.com/getsentry/team-replay/issues/145, we're adding new columns that can represent replay / event links to verfied-to-exist Sentry events. This PR should create 5 new columns.
Will be used in an upcoming processor PR.

feat(replays): migration for event link columns

---

snuba/datasets/processors/replays_processor.py
tests/datasets/test_replays_processor.py

Following up to https://github.com/getsentry/snuba/pull/4669, as part of https://github.com/getsentry/team-replay/issues/145, adds a processor for the replay event link new message type.
This message will come in from this PR https://github.com/getsentry/sentry/pull/54986 (still in draft).

feat(replays): add processor for replay event link type

---

gocd/templates/bash/migrate-st.sh
gocd/templates/bash/migrate.sh
snuba/cli/migrations.py
snuba/migrations/check_dangerous.py
snuba/migrations/connect.py
snuba/migrations/migration.py
snuba/migrations/operations.py
snuba/migrations/runner.py
snuba/utils/types.py
tests/cli/test_migrations.py
tests/conftest.py
tests/migrations/test_check_dangerous.py

Include some heuristics to check if a migration does something dangerous like changing Nullable or Cardinality.
Calling migrate with `--check-dangerous` will check for these before running. Right, now all the heuristics are manually crafted and work by checking the string regex. It's far from exhaustive but catches a few obvious ones:
* changing nullable
* changing string cardinality
* changing from a string to a non-string type
* setting a delta encoding without ZSTD or LZ4
Have a test that creates a dummy table with some rows with the modifiers and run a dummy test migration against it. The checker detects the violations.

feat(migrations): add dangerous checks

---

.github/workflows/ci.yml

Due to [removal of e2e tests](https://github.com/getsentry/snuba/pull/4660), we were no longer pushing to dockerhub. This resumes that process.

chore(self-hosted): Publish snuba image to dockerhub again

---

snuba/admin/static/capacity_management/allocation_policy.tsx

Sort the keys in the UI so that when you are switching between storages, the
keys will be in the same place every time.
Before: Notice that when you change storages the sort order changes, which 
makes it harder to edit multiple storages one after the other.
After: The order stays persistent.

ref(admin) Sort capacity management keys

---

tests/clickhouse/optimize/test_optimize.py

This test is flaky and fails if clickhouse returns partitions in a different order. Sort lists before doing to the compare to be more consistent.

fix(ci): sort lists before compare

---

snuba/replacer.py

We're seeing slow replacements in SaaS. Since we can't scale up we want to identify the suspect project_ids with confidence

improvement(visibility): make the replacer log project_ids for slow replacements

---

snuba/clickhouse/native.py
snuba/querylog/__init__.py
tests/web/test_db_query.py

- It seems `conn.last_query.profile.bytes` may be an incorrect value for bytes scanned for a query
- This change adds 2 metrics reporting `profile.bytes` and `progress.bytes`, it seems [progress](https://clickhouse.com/docs/en/native-protocol/server#progress) may be the correct bytes scanned value

experiment(on-call): Profile bytes scanned potentially incorrect

---

rust_snuba/rust_arroyo/src/processing/mod.rs

Align to https://github.com/getsentry/arroyo/blob/83f5f54e59892ad0b62946ef35d2daec3b561b10/arroyo/processing/processor.py#L356

feat(rust-arroyo): Processor calls consumer.poll() with timeout of 1 sec

---

gocd/templates/pipelines/snuba.libsonnet

Use the snuba-admin spec for deploys since snuba-admin is enable in ST. This avoid randomly selecting a pod spec. By consistently using the admin spec, we can make debugging a lot easier.

Use snuba-admin spec for ST and SaaS

---

.github/workflows/ci.yml

Sentry CI now only runs the subset of tests marked @pytest.mark.snuba_ci since https://github.com/getsentry/sentry/pull/56174
No need to split this across 2 jobs anymore as it should be a lot faster

test: No need to run Sentry CI in a matrix

---

snuba/datasets/processors/querylog_processor.py
snuba/querylog/query_metadata.py

Querylog consumer is crashlooping due to negative org ID's in `tenant_ids`, (Clickhouse insert rejects)

fix(on-call): Negative org ID in Tenant IDs crashes Querylog consumer

---

gocd/templates/bash/check-github.sh

#4720 
- This PR changed Sentry tests to no longer run as matrix, our deploy pipeline still expects matrix checks

fix(CI): Unblock deploys as they hard check for sentry matrix'd tests

---

.github/file-filters.yml
.github/workflows/ci.yml
gocd/pipelines/snuba-stable.yaml
gocd/templates/bash/check-github.sh
snuba/datasets/configuration/replays/entities/replays.yaml

Runs different set of Sentry tests when specific paths are changed. The "full" coverage is designed for API related changes which we might want to test against all of the product features in Sentry.
Right now only changes to the yaml files trigger the full set of Sentry/Snuba tests, these should be reviewed later though.
Depends on https://github.com/getsentry/sentry/pull/56352

test: Run different Sentry tests depending on files changed

---

.github/file-filters.yml
.github/workflows/ci.yml

If we change the flask app, query processors, or the allocation policies, that affects the API. Therefore we should have changes to these files run the sentry test suite

feat(ci): make sure possible API changes are tested against sentry

---

rust_snuba/rust_arroyo/src/utils/metrics.rs
rust_snuba/src/metrics/statsd.rs
rust_snuba/src/metrics/testing.rs

Seems kind of silly (and unintuitive) to allow value to be an option, and quietly apply a default of 1. Let's just make it required.

feat(rust): metrics.increment() no longer supports optional value

---

rust_snuba/rust_arroyo/src/processing/metrics_buffer.rs
rust_snuba/rust_arroyo/src/processing/mod.rs
rust_snuba/rust_arroyo/src/utils/metrics.rs
rust_snuba/src/metrics/statsd.rs
rust_snuba/src/metrics/testing.rs

Adds metrics for `arroyo.consumer.poll.time`, `arroyo.consumer.paused.time` and `arroyo.consumer.processing.time`.

feat(rust): Add processor metrics for Rust consumer

---

gocd/templates/jsonnetfile.json
gocd/templates/jsonnetfile.lock.json

This update makes a subtle change to rollbacks.
The current snuba rollbacks (i.e. before v2.2.2), would re-run the `deploy-primary` stage to perform a rollback. However, because each pipeline had a `pipeline-complete` stage at the end of each region, the pipelines would be paused AND locked. This caused some confusion when folks tried to fix re-enable their deployments.
In v2.2.2, the `pipeline-complete` stage is removed (this was a noop stage just used for chaining) and instead the pipelines are chained using the last stage. Rollbacks will the re-run the `deploy-primary` stage and once its finished all pipelines will be paused, but will not be locked.
Rolling this out needs a little attention because of a quirk with GoCD, which will trigger a deploy of all regions since the change causes …

Update gocd-jsonnet to v2.2.2

---

gocd/templates/bash/saas-ddog-health-check.sh
gocd/templates/bash/saas-sentry-error-check.sh
gocd/templates/bash/saas-sentry-health-check.sh
gocd/templates/pipelines/snuba.libsonnet

- Adds 2 Sentry checks
- One checks latest Release for any new issues
- One checks latest Release for total error events > 500
- Adds a Datadog Monitor check
- Simple check of two existing monitors
- Currently this is set to dry-run, which means it won't block since I don't believe these monitors are appropriate for this check
- We need to add some "current" status checks, all existing monitors check for ~5 minutes of data which could block a deploy fixing said monitor to begin with

feat(deploy-gates): Add SaaS -> ST deploy gates

---

snuba/web/query.py

- As part of analyzing cogs for the Generic Metrics dataset in Snuba, we need to see a split of the shared resource by use case (`use_case_id`)
- Currently, queries do not contain `use_case_id` so I'm starting to add a new Tenant ID for generic metrics queries for this
- This will eventually be a required Tenant ID for generic metrics queries
- Relevant Sentry PR adding some `use_case_id`:
- https://github.com/getsentry/sentry/pull/56694
- Removing the existing monitoring for missing `tenant_ids` in Snuba requests
- This metric was used to power this [notebook](https://app.datadoghq.com/notebook/4890769/tenant-ids-notebook) during the introduction of `tenant_ids` in general but is no longer needed as we have Tenant IDs where needed and we auto reject queries without them

feat(CoGS): Monitor missing `use_case_id`

---

snuba/migrations/group_loader.py
snuba/snuba_migrations/replays/0016_materialize_new_event_counts.py

as part of https://github.com/getsentry/team-replay/issues/145 -- add new materialized columns for event counts. we add three -- info, warning, and error.

feat(replays): add new materialized columns for event linking

---

snuba/query/allocation_policies/bytes_scanned_window_policy.py
tests/query/allocation_policies/test_bytes_scanned_window_allocation_policy.py

It looks like the bytes scanned metric we are using is not actually telling us how many bytes were scanned by the query. This PR:
* Gives a way to switch to using the other bytes_scanned metric for the allocation policy
* emits metrics for both bytes scanned metrics
* the `bytes_scanned` metric changes metric is actually being enforced
* Tests the new behavior
The rollout of this should be storage-by-storage as the numbers are wildly different

feat(oncall): Use profile_bytes in bytes scanned allocation policy

---

snuba/datasets/configuration/generic_metrics/storages/counters.yaml
snuba/datasets/configuration/generic_metrics/storages/distributions.yaml
snuba/query/allocation_policies/concurrent_rate_limit.py
snuba/query/allocation_policies/cross_org.py
tests/query/allocation_policies/test_cross_org_policy.py

Before this PR all allocation policies have used a customer id (either `project_id` or `organization_id`) as the tenants for allocation policies. This has worked because most queries that have come in to snuba have been made on behalf of a specific customer. Recently however, new features are being developed where one query can issue scan data across organizations and are done outside of the customer’s control (e.g. escalating issues), as such, capacity to these queries will need to be managed differently.
This PR will roll out to production **inactive**. This means none of its code will run until it is turned on by a human being. The only storage this PR currently affects is `generic_metrics_counters`
- Cross-org queries should not be able to monopolize the entire capacity of the cluster …

feat(capman): Cross-organization allocation policy

---

rust_snuba/Cargo.lock
rust_snuba/Cargo.toml
rust_snuba/src/runtime_config.rs
rust_snuba/src/strategies/python.rs

This reverts commit 9cf07cdcf3ee69841aa660f97b537cee70e170f6.
(revert #4703)
The commit in question is speculated to cause deadlocks (no clear evidence), and while in theory it is faster, in practice we can't use it right now. next time use QE to validate perf improvements.

Revert "ref(rust): Rewrite check_for_results to use better way of joining process pool (#4703)"

---

snuba/cli/consumer.py
snuba/cli/rust_consumer.py
snuba/consumers/consumer_builder.py
snuba/consumers/consumer_config.py
tests/cli/test_consumer.py

We would like to experiment with running Kafka with static membership. This mode is enabled when consumer passing in the `group.instance.id` parameter.  This PR adds passing in the group instance id as a CLI parameter.

feat(consumer): allow group instance id to enable static membership

---

rust_snuba/rust_arroyo/examples/transform_and_produce.rs
rust_snuba/rust_arroyo/src/backends/kafka/producer.rs
rust_snuba/rust_arroyo/src/backends/mod.rs
rust_snuba/rust_arroyo/src/processing/strategies/produce.rs

Produce is simply a special case of RunTaskInThreads. Let's reuse the underlying strategy to avoid reimplementing the part where we keep track of the handles in multiple places.
Also switch to threaded producer. Producer was not being polled previously.

feat(rust): Rebuild Produce strategy based on RunTaskInThreads

---

snuba/admin/clickhouse/predefined_cardinality_analyzer_queries.py
snuba/admin/static/api_client.tsx
snuba/admin/static/cardinality_analyzer/index.tsx
snuba/admin/views.py

This PR adds support for 2 predefined cardinality queries used with starfish 
1. Find the list of projects which have a high cardinality
2. For the list of projects which have a high cardinality find sample values to determine how grouping can be improved.

feat(cardinality): Add predefined queries

---

rust_snuba/rust_arroyo/src/backends/kafka/producer.rs
rust_snuba/rust_arroyo/src/backends/mod.rs
rust_snuba/rust_arroyo/src/processing/strategies/produce.rs

- Producer.produce() can return an error rather than panicking
- Remove producer.close(). Not needed since Drop takes care of this
- Removes an unnecessary clone()

feat(rust): KafkaProducer improvements

---

rust_snuba/rust_arroyo/src/processing/strategies/produce.rs
rust_snuba/rust_arroyo/src/processing/strategies/run_task_in_threads.rs
rust_snuba/src/consumer.rs
rust_snuba/src/strategies/clickhouse.rs

We use this strategy all over the place (and under the hood of other strategies as well). Support passing a custom metric name to disambiguate.

feat: Support passing custom metric name to RunTaskInThreads

---

snuba/admin/clickhouse/predefined_cardinality_analyzer_queries.py

Since we want to query the data as small as 1 hour, use the granularity of 2 as default

fix(cardinality): Use default granularity of 2

---

gocd/templates/bash/check-github.sh
scripts/fetch_service_refs.py

* Adds the clickhouse 21 test to be checked in gocd
* Fixes a bug were we were checking shas against the old pipeline

CI: add clickhouse 21 checks to gocd 

---

gocd/templates/jsonnetfile.json
gocd/templates/jsonnetfile.lock.json
gocd/templates/snuba.jsonnet

This fixes an issue in rollbacks that can cause multiple deploys of the same commit. Now rollbacks have a final manual stage that unpauses and unlocks the pipelines once an incident is complete.
For the curious: The I removed the pipeline-complete stage in a previous version, this caused pipelines to be unlocked after a rollback is complete (a problem folks were running into), however this meant the final stage in the deploy was the stage the rollback re-ran. Since this final stage was run, it triggered the downstream pipeline to run which was unintentional.
#skip-changelog

Update GoCD Jsonnet library

---

requirements-test.txt
requirements.txt
tests/datasets/cdc/test_groupassignee.py
tests/datasets/cdc/test_groupedmessage.py
tests/datasets/entities/test_pluggable_entity.py
tests/datasets/test_cdc_events.py
tests/datasets/test_errors_processor.py
tests/datasets/test_group_attributes_join.py
tests/test_api.py
tests/test_discover_api.py
tests/test_generic_metrics_api.py
tests/test_metrics_api.py
tests/test_org_sessions_api.py
tests/test_outcomes_api.py
tests/test_replacer.py
tests/test_sessions_api.py
tests/test_spans_api.py
tests/test_transactions_api.py

It was only used in tests, and we don't need a separate library for this

ref: Get rid of pytz

---

snuba/admin/cardinality_analyzer/cardinality_analyzer.py
snuba/clusters/cluster.py

Cardinality queries need more threads since they query more data. A lot of the queries are timing out right now.

fix(cardinality): Allow more threads for queries

---

.github/workflows/ci.yml
docker-compose.gcb.yml
gocd/templates/bash/check-github.sh

Not all of these are passing right now or blocking for merge/deploy. This change aims to provide more visibility into which features do not work on future ClickHouse versions so we can prioritize fixing these. It also prevents us merging future changes that do not work well in certain versions of ClickHouse that we should support.

ci: Run Snuba tests against multiple ClickHouse versions in CI

---

snuba/subscriptions/executor_consumer.py
tests/subscriptions/test_combined_scheduler_executor.py
tests/subscriptions/test_executor_consumer.py

Let's dogfood Arroyo a bit more. `ProduceResult` was originally written before Arroyo shipped with a built in Produce method. We can use Arroyo's one now and not maintain a separate implementation.

ref(subscriptions): Use Arroyo's Produce in the executor

---

snuba/migrations/group_loader.py
snuba/snuba_migrations/generic_metrics/0018_sets_update_opt_default.py

| [#1](https://github.com/getsentry/snuba/pull/4780) | ~~Update default `decasecond_retention_days` and `min_retention_days` columns for distributions~~ | closed          | master  |
| [#2](https://github.com/getsentry/snuba/pull/4782) | ➤ Update default `decasecond_retention_days` and `min_retention_days` columns for sets | In review | master |
| [#3](https://github.com/getsentry/snuba/pull/4781) | Update default …

fix(generic-metrics): fix(generic-metrics): Update default `decasecond_retention_days` and `min_retention_days` columns for sets

---

snuba/admin/static/data.tsx

It has been bothering me for a while now... There appears to be a missing space between the emoji and "Cardinality Analyzer!!!" in the snuba admin UI

fix(UI): Add missing space between emoji and 'Cardinality Analyzer'

---

snuba/datasets/processors/metrics_aggregate_processor.py
snuba/datasets/processors/metrics_bucket_processor.py
tests/datasets/test_metrics_processor.py

This PR is responsible for updating the metrics bucket processor to write use_case_id in ClickHouse. Currently in the metrics dataset (release-health), we are writing empty strings (`""`) as part of the `use_case_id`. As a result, this has caused some [confusion around querying for use_case_id](https://github.com/getsentry/sentry/pull/57005) in release-health. Since `use_case_id` is required in [kafka schema](https://github.com/getsentry/sentry-kafka-schemas/blob/8a28e031579e2d40e49a3086c74fdfbb93ac6fc7/schemas/snuba-metrics.v1.schema.json#L74), this field should be already be sent as part of the kafka message. Note: the metrics dataset only contains the `sessions` use_case_id anyways. A data migration might be necessary to follow this PR to update all the existing rows.

fix(metrics): Update metrics processor to write use_case_id

---

snuba/migrations/group_loader.py
snuba/snuba_migrations/generic_metrics/0019_counters_update_opt_default.py

| [#1](https://github.com/getsentry/snuba/pull/4780) | ~~Update default `decasecond_retention_days` and `min_retention_days` columns for distributions~~ | closed          | master  |
| [#2](https://github.com/getsentry/snuba/pull/4782) | Update default `decasecond_retention_days` and `min_retention_days` columns for sets | merged | master |
| [#3](https://github.com/getsentry/snuba/pull/4781) | ➤ Update default …

fix(generic-metrics): Update default `decasecond_retention_days` and `min_retention_days` columns for counters

---

snuba/query/allocation_policies/concurrent_rate_limit.py
snuba/state/rate_limit.py
tests/admin/test_api.py
tests/query/allocation_policies/test_concurrent_rate_limit_policy.py

Currently, `state.max_query_duration_s` is used by the concurrent rate limiter to know how long a TTL to set in Redis. That value is currently set to `60 seconds` while the max request time we allow is 30 seconds. This means that we are potentially storing double the amount of data in redis as we need.
This PR allows us to change that value at runtime so we can experiment with changing the value and saving redis memory.

feat(capman): Allow concurrent rate limit policies to set max_query_duration_s

---

snuba/datasets/metrics_messages.py
tests/datasets/processors/test_generic_metrics_processor.py

`CUSTOM` use case needs 10 second granularity support. Need to double check if this is the only metric type they need it for.
This would go in after the corresponding Sentry changes: https://github.com/getsentry/sentry/pull/56707
UPDATE: confirmed that `CUSTOM` use case wants it for all metric types

feat(generic-metrics): Add support for 10s granularity

---

rust_snuba/Cargo.lock
rust_snuba/Cargo.toml
rust_snuba/rust_arroyo/src/backends/kafka/producer.rs
rust_snuba/rust_arroyo/src/processing/strategies/commit_log.rs
rust_snuba/src/strategies/commit_log.rs
rust_snuba/src/strategies/mod.rs

Ports https://github.com/getsentry/arroyo/blob/f43a9d69ab0e504869f88fcc39ede98bc0cc6807/arroyo/backends/kafka/commit.py to Rust. The codec is not used yet.

feat: Port the commit log encoder/decoder to Rust

---

snuba/datasets/configuration/generic_metrics/storages/distributions.yaml

Adds statistical detectors job to cross org query policy. Register the statistical detectors query as well

feat(capman): add cross org policy to generic metrics distributions

---

snuba/consumers/strategy_factory.py

The consumer now always performs the Reduce step even if it's skipping writes. This is important since the commit strategy is IMMEDIATE and we would attempting to commit every offset otherwise.

fix: Fix committing in the no-skip-write python consumer

---

snuba/cli/multistorage_consumer.py
snuba/consumers/consumer_builder.py

The current dlq policy allows for 100% of problematic messages to be swallowed by the dlq. That would not be ideal since in effect we could be sending 100% of the messages to the dlq. Instead, we configure a max invalid ratio of 0.01 and max consecutive count of 1000 per partition. We set them both because the counts are not persisted across consumer restarts. So when a consumer crashes when the dlq policy limit is hit, the counters are reset.

fix(dlq): Add sane defaults to the dlq policy

---

rust_snuba/rust_arroyo/src/processing/strategies/run_task_in_threads.rs

Logging is expensive, let's stop writing the most useless logs. we already have a metric for this anyway.

feat: Reduce logging in Rust consumers

---

snuba/datasets/configuration/generic_metrics/entities/counters.yaml
snuba/datasets/configuration/generic_metrics/entities/distributions.yaml
snuba/datasets/configuration/generic_metrics/entities/sets.yaml

Since we are now able to store metrics at the 10s granularity, we also want to make that data queryable. Adding 10s to the allowed granularities for the query processors.

feat(processor): Add 10s to generic metrics granularity processors

---

gocd/templates/bash/migrate-st.sh

No sure why this was there in the first place. Removing to prevent running unsafe migrations in ST

remove `--force` from ST migrations

---

snuba/datasets/metrics_messages.py
tests/datasets/processors/test_generic_metrics_processor.py
tests/datasets/test_metrics_processor.py

After the migration from https://github.com/getsentry/snuba/pull/4782, `min_retention_days` columns for sets and counters (which controls the retention days for minute granularity for metrics) now have default values of 30 days. This pr updates the processors to write `retention_days` to those columns so its behaviour is the same as distribution. This after this pr is merged, we will apply mv2 to these tables which actually reads from `min_retention_days`.

feat(generic-metrics): Write `retention_days` to `min_retention_days` columns for sets and counters

---

snuba/migrations/group_loader.py
snuba/snuba_migrations/generic_metrics/0020_sets_mv2.py

This should be merged after the pr chain at https://github.com/getsentry/snuba/pull/4780 is merged.
Add mat view V2 for set metrics. This will allow each granularity to have its own retention days.

feat(generic-metrics): Add new mat view for generic set metrics

---

snuba/datasets/metrics_messages.py

Bump the materialization version for generic sets metrics to 2 to use the new mat view introduced in https://github.com/getsentry/snuba/pull/4803
Ran `send_metrics.py` and emitted metrics to sentry → snuba
Confirmed `materialization_version` is 2 in raw table
```sql
SELECT
use_case_id,
org_id,
project_id,
metric_id,
timestamp,
materialization_version
FROM generic_metric_sets_raw_local
WHERE arrayExists(v -> match(v, 'metric_e2e_.*AS934XZV'), tags.raw_value)
Query id: 6fc6d8e4-dff2-400a-80d6-9ff192479c25
┌─use_case_id───────┬─org_id─┬─project_id─┬─metric_id─┬───────────timestamp─┬─materialization_version─┐
│ custom            │      1 │          3 │     65556 │ 2023-10-07 04:07:32 │                       2 │
│ escalating_issues │      1 │          3 │     65545 │ 2023-10-07 04:07:32 │ …
```

feat(generic-metrics): Bump `materialization_version` for generic sets metrics to 2

---

gocd/templates/bash/deploy.sh

This will enable deploying images to the experimental consumers with static membership enables. By observing this for a while we can track improvements it makes to rebalancing.

enable deploy to experimental static membership consumers

---

snuba/migrations/system_migrations/0001_migrations.py
tests/admin/clickhouse_migrations/test_api.py
tests/migrations/test_runner.py
tests/migrations/test_runner_individual.py

I don't think there's a valid use case to recreate the table and rerun all migrations without user intervention.
This is intented as a safeguard - the migrations table was inadvertently dropped during a recent incident, and we don't want to run any migrations in that case. This stops any further migration from proceeding.

feat: Mark first migration blocking

---

gocd/templates/bash/deploy.sh

Fixing up #4851 . Statefulsets need their own deploy.

deploy static experimental consumers with statefulsets

---

snuba/consumers/consumer.py
snuba/consumers/strategy_factory.py

It's super unintuitive (and pointless) that this was copying the Arroyo strategy interface. There is no need for the separate close() and join() methods.

ref: Simplify collector / processed message batch writer

---

snuba/admin/notifications/slack/client.py
tests/admin/notifications/slack/test_client.py

In order to report cardinality, we need the ability to send files to slack channels. This PR adds a new api `post_file` which uses the slack API endpoint for sending a file to a channel.
Tested the change by writing a program which uses the `post_file` API and verifying that the message got sent to the correct channel

feat(slack): Allow sending files in slack client

---

snuba/datasets/metrics_messages.py
tests/datasets/processors/test_generic_metrics_processor.py
tests/datasets/test_metrics_processor.py

Remove the flag that controls the materialization version

lint(generic-metrics): Remove feature flag for gen-metrics sets mat view version

---

tests/test_transactions_api.py

23.3 has an issue with having trailing escape charaters in LIKE conditions.
Changing the test allows it to work on 23.3.
In the future it will probably be worth having validation on this specific case
but in the interest of unblocking the upgrade, that work will be tracked
separately.

ref(23.3) Fix test so it runs on 23.3

---

.github/dependabot.yml
Dockerfile

- Bumps the base Docker image from Debian 11 to Debian 12.
- Configures Dependabot to open PRs for Docker image and GitHub Action updates.
Partially addresses #4871

deps: bump to debian 12

---

.github/dependabot.yml
.github/workflows/dependency-review.yml

- Use Dependabot's new grouping feature to update modules together. This will reduce the number of PRs and weird states where versions get mismatched.
- Configure Dependency Review in CI to prevent new dependencies being added that have known high or critical severity vulnerabilities.

configure dependabot and dependency review

---

snuba/datasets/configuration/events/storages/errors.yaml
snuba/datasets/configuration/generic_metrics/storages/counters_bucket.yaml
snuba/datasets/configuration/generic_metrics/storages/distributions_bucket.yaml
snuba/datasets/configuration/generic_metrics/storages/sets_bucket.yaml
snuba/datasets/configuration/json_schema.py
snuba/datasets/configuration/metrics/storages/raw.yaml
snuba/datasets/configuration/sessions/storages/raw.yaml
snuba/datasets/configuration/storage_builder.py
snuba/datasets/configuration/transactions/storages/transactions.yaml
snuba/datasets/table_storage.py
tests/datasets/configuration/test_utils.py

Eventually each storage can define which timestamp will be used for scheduling. This is a non functional change that adds the `subscription_synchronization_timestamp` key to the storage configuration, but does not use it yet.

feat(subscriptions): Add mechanism for storage to define timestamp used for scheduling

---

snuba/datasets/metrics_messages.py
tests/datasets/processors/test_generic_metrics_processor.py

Remove the feature flag that determines the materialization version since it is now confirmed to be working

lint(generic-metrics): Remove feature flag for gen-metrics counters mat view version

---

snuba/settings/__init__.py
snuba/settings/settings_distributed.py
snuba/settings/settings_test_distributed_migrations.py

Because the generic metrics migration group is marked with the `COMPLETE` Readiness State, we need to make sure that storage set keys are defined/pointing to the right clusters in _all_ environments before any migrations (https://github.com/getsentry/snuba/pull/4847) can be run. 
This can be merged prior to any clusters being provisioned since this is for local env.

feat(generic-metrics): Add gauges storage set locally

---

snuba/consumers/consumer.py
snuba/processor.py

This supports the subscriptions to opt into using received_p99 for scheduling instead of the current orig_message_ts
Needs https://github.com/getsentry/arroyo/pull/295

feat: Write received_p99 to commit log

---

snuba/migrations/migration.py
snuba/migrations/migration_utilities.py
snuba/migrations/operations.py
snuba/migrations/runner.py
snuba/migrations/table_engines.py
snuba/snuba_migrations/functions/0001_functions.py
snuba/snuba_migrations/querylog/0001_querylog.py

In order to upgrade to ClickHouse 23, we need to ensure all migrations run.
0001_functions uses a nullable column in the primary key. version 23 judges us for this, and one has to use allow_nullable_key to explicitly opt into permitting this `CREATE TABLE` statement.
To make matters worse, version 20.3 (a version we support) does not support the `allow_nullable_key` setting and will throw an error if it is set. So there is no table schema that works on both versions of ClickHouse.
However, the upside is that upgrading from ClickHouse version 21.6 to 23 appears to permit this schema regardless for old tables, but refuses to create new tables with the same schema. I tested this by recreating the container with the new image like so:
0. Be on …

fix: fix 0001_functions and 0001_querylog for clickhouse 23

---

rust_snuba/rust_arroyo/src/processing/mod.rs

Seems like it might have been flipped around the wrong way so we were never pausing

fix(rust): Fix the consumer pause condition when backpressure happens

---

snuba/cli/spans_cardinality_analyzer.py
snuba/clickhouse/span_cardinality_analyzer.py
snuba/clusters/cluster.py
snuba/settings/__init__.py

As we introduce more modules for metrics extraction from spans there is a bigger need to keep track of how cardinality evolves for different modules. This PR adds the queries which are used to perform cardinality analysis as a snuba cli command. The intention is for the snuba cli command to run as a cron job. The cron job would run the desired queries, dump the results in a CSV file locally and then send the file to a slack channel.
Tested locally with some fake data and verified that the files get sent to slack

feat(cardinality): Cardinalily analysis reporting

---

snuba/migrations/table_engines.py
tests/migrations/test_table_engines.py

Clusters with `-` & numbers in their names fail as Clickhouse thinks it's an arithmetic operation.  Surrounding the cluster name in back ticks should fix this.

fix(migrations): Fix handling distributed clusters with - in their names

---

snuba/web/views.py
tests/web/test_views.py

A single tenant customer has some garbage data in their releases that causes the response to crash
if this happens we go through the payload and hex-encode the non-string byte values

feat(oncall): add error handling for corrupted payloads

---

.github/file-filters.yml
.github/workflows/ci.yml
gocd/pipelines/snuba-stable.yaml

Currently the sentry test suite is taking too long and blocking deployments. This PR unblocks the CI pipeline for the weekend in case of emergency. This should not be a permanent state

CI unblock: revert sharding, don't run full sentry test suite

---

snuba/cli/consumer.py
snuba/consumers/consumer_builder.py

This is the same default we apply to all consumers in Sentry

feat: Max poll interval ms default to 30 seconds

---

snuba/datasets/table_storage.py
snuba/subscriptions/combined_scheduler_executor.py
snuba/subscriptions/scheduler_consumer.py
tests/subscriptions/test_scheduler_consumer.py

Scheduler can switch between using orig_message_ts and received_p99 for scheduling. Note this does not change anything functionally yet, as everything is still configured to orig_message_ts.

feat(scheduler): Scheduler can switch between different timestamps

---

rust_snuba/rust_arroyo/src/processing/strategies/mod.rs
rust_snuba/src/consumer.rs
rust_snuba/src/processors/functions.rs
rust_snuba/src/processors/mod.rs
rust_snuba/src/processors/profiles.rs
rust_snuba/src/processors/querylog.rs
rust_snuba/src/processors/spans.rs
rust_snuba/src/types.rs

This is needed so we can DLQ these messages later - this matches how InvalidMessage works in Python Arroyo

feat(rust): Invalid message has partition and offset properties

---

snuba/cli/subscriptions_scheduler.py
snuba/cli/subscriptions_scheduler_executor.py
snuba/datasets/configuration/events/storages/errors.yaml
snuba/datasets/configuration/generic_metrics/storages/counters_bucket.yaml
snuba/datasets/configuration/generic_metrics/storages/distributions_bucket.yaml
snuba/datasets/configuration/generic_metrics/storages/sets_bucket.yaml
snuba/datasets/configuration/json_schema.py
snuba/datasets/configuration/metrics/storages/raw.yaml
snuba/datasets/configuration/sessions/storages/raw.yaml
snuba/datasets/configuration/storage_builder.py
snuba/datasets/configuration/transactions/storages/transactions.yaml
snuba/datasets/table_storage.py
snuba/subscriptions/combined_scheduler_executor.py
snuba/subscriptions/scheduler_consumer.py
tests/datasets/configuration/test_utils.py
tests/subscriptions/test_scheduler_consumer.py

The main motivations for this are:
1. The amount of delay depends on the synchronization timestamp used, and this is defined at the storage level in code. For example if "orig_message_ts" is used, a longer delay will be applied than if "received_p99" is used, since received will be set earlier in the pipeline.
2. The same CLI args get applied in all Sentry deployments, and this makes it easier to keep them in sync
3. Rolling out different values per storage via CLI will probably break some of our templates and require too much rework.
There are no functional changes here since we have 60 configured everywhere right now.

ref(subscriptions): Move --delay-seconds from CLI arg to yaml definition

---

snuba/cli/devserver.py

Has been deprecated for 2 years, will be fully removed shortly

feat: Remove sessions consumer from devserver

---

snuba/subscriptions/data.py
snuba/web/query.py
tests/test_api.py

- As part of figuring out what % of generic metrics subscriptions queries originate from which use case IDs, we need to add extra data to the create subscription request
- This has a side effect of also enabling us to categorize subscriptions by Organization ID once Sentry starts sending `tenant_ids` as part of the request
- Sentry change [here](https://github.com/getsentry/sentry/pull/57101)
- `POST /<dataset>/<entity>/subscriptions` route (`create_subscription`) now supports `tenant_ids` in the request
- These Tenant IDs are stored in `SubscriptionData` but *not* serialized into Redis when the subscription is saved
- For now, this PR will increment a simple metric checking how many subscription are vs aren't being created with `tenant_ids`

feat(COGS): `create_subscription` requests now support Tenant IDs

---

tests/test_snql_api.py

This test was failing in certain versions of Clickhouse because some versions
automatically cast the `type` condition to match types, meaning the test didn't
fail. Use a different column instead and don't try to match the exact error
message (since that changes between versions too).

fix: Test failed in specific versions of Clickhouse

---

snuba/clickhouse/http.py
tests/conftest.py
tests/test_snql_api.py

Ran test locally against 22.8 and I _think_ these two tests were the only troublesome ones?
* `test_clickhouse_type_mismatch_error`
* `test_error_handling` 
But wanted to put up a PR to verify that's the case
For the `test_error_handling` one, the format of the error has seemingly changed from something like:
```
Code: 60, e.displayText() = DB::Exception: Table default.not_existing doesn't exist. (version 19.11.4.24 (official build))
```
to
```
Code: 41. DB::ParsingException: Cannot parse datetime: (while reading the value of key timestamp): While executing ParallelParsingBlockInputFormat: (at row 2). (CANNOT_PARSE_DATETIME) (version 22.8.15.25.altinitystable (altinity build))
```
As for the `test_clickhouse_type_mismatch_error` one... when I put in the following snql from the test we can …

clickhouse upgrades: 22.8 fixes

---

snuba/datasets/configuration/events/storages/errors.yaml
snuba/datasets/configuration/transactions/storages/transactions.yaml
tests/subscriptions/test_scheduler_consumer.py

Errors and transactions have a "received" field. So let's use the p99 of that as the clock for subscription scheduling. This is a better timestamp to use than the Snuba one, as any backlogs in the ingest consumer will actually be taken into account in alerts. That is - if the ingest consumer is backlogging and messages delayed, subscriptions will not be run ahead of those messages being ingested.

feat(subscriptions): Use received_p99 for scheduling subscriptions

---

snuba/web/db_query.py
tests/web/test_db_query.py

This PR is responsible for adding a way to ignore incoming concurrent queries depending on the dataset's configured sample rate runtime config. In order to better manage the health of our systems, we need a way to load balance queries  among our ClickHouse nodes to avoid problems like table rate limits and requiring to scale our cluster despite still having capacity in the cluster (`nodes =! 1-1`). Search_issues dataset is a example of a dataset with high volumes of `consistent` queries, but very low replication lag. It is possible most of those queries do not actually need to be executed on the same write node. 
This can be configured by configuration keys e.g. `search_issues_ignore_consistent_queries_sample_rate`. This flag should be set to a value between 0 and 1 where 0 means we never …

perf: Support ignoring consistent queries with sample rate

---

snuba/consumers/consumer.py

This is a fix for SNUBA-3XE, which caused subscription scheduler to crashloop in INC-548.

fix: Properly clear state between batches

---

rust_snuba/rust_arroyo/examples/base_consumer.rs
rust_snuba/rust_arroyo/examples/base_processor.rs
rust_snuba/rust_arroyo/examples/transform_and_produce.rs
rust_snuba/rust_arroyo/src/backends/kafka/mod.rs
rust_snuba/rust_arroyo/src/backends/local/broker.rs
rust_snuba/rust_arroyo/src/backends/local/mod.rs
rust_snuba/rust_arroyo/src/backends/mod.rs
rust_snuba/rust_arroyo/src/backends/storages/memory.rs
rust_snuba/rust_arroyo/src/backends/storages/mod.rs
rust_snuba/rust_arroyo/src/processing/mod.rs
rust_snuba/rust_arroyo/src/utils/clock.rs
rust_snuba/src/consumer.rs

The return value of Strategy.join() is currently ignored, because we
have no access to the consumer from within the assignment callbacks.
Shuffle a few things around so that consumer callbacks contain Arc to
the consumer internally.
SNS-2473

fix: Commit offsets from strategy join

---

snuba/query/allocation_policies/concurrent_rate_limit.py

This is not used anywhere we should not import it

chore: remove unused redis client

---

rust_snuba/src/config.rs
rust_snuba/src/consumer.rs
rust_snuba/src/factory.rs
rust_snuba/src/lib.rs

consumer.rs is getting unwieldy, split the factory into a separate file. Also passes the whole StorageConfig object to the factory - we will need more data from this object later to produce to the commit log.
Most of this diff is just copy and paste, without functional changes

ref(rust): Split factory into separate module

---

snuba/cli/rust_consumer.py

--processes has been fully removed in favor of --concurrency

ref: Remove deprecated option from Rust consumer CLI

---

.github/workflows/ci.yml
docker-compose.gcb.yml
docker-compose.yml
gocd/templates/bash/check-github.sh

We are about to drop support for 20.3. Let's run 21.8 as default in CI

ci: Switch default ClickHouse version in CI to 21.8

---

snuba/datasets/configuration/generic_metrics/storages/gauges.yaml
snuba/datasets/configuration/generic_metrics/storages/gauges_bucket.yaml

The current readiness state is limited, which means the storage is only available for querying/health checks only in local env. Bumping it to partial to activate it for s4s and saas.

feat(generic-metrics): Bump gauges storage readiness state to partial

---

snuba/datasets/configuration/generic_metrics/entities/gauges.yaml
tests/test_generic_metrics_api.py

The gauges entity was exposing the rounded_timestamp field as the default time
column. Change that to timestamp to keep consistency with the other entities.

ref(gauges) Expose timestamp on the gauges entity

---

snuba/datasets/configuration/generic_metrics/entities/gauges.yaml
tests/test_generic_metrics_api.py

The other entities have the TimeseriesProcessor available, so maintain that.

ref(gauges): Align interface better with other metrics entities 

---

snuba/state/rate_limit.py
tests/state/test_rate_limit.py

As part of debugging the rate limiter memory leak, it showed up that the rate limiter was creating non-expirable keys 
https://www.notion.so/sentry/Experiment-7-Turn-on-concurrent-rate-limit-policy-monitor-non-expirable-keys-cc0b7a18cd8d4eed943ace6c3f9beedf
With https://getsentry.atlassian.net/browse/OPS-4087 , it was confirmed that the non-expiring keys were from this rate limit function. Both from the allocation policy and the legacy rate limiter (but many more on the allocation policy).
```
snuba-ratelimit:5889476
errors_ro.ConcurrentRateLimitAllocationPolicy.rate_limit4504594023645190
```
There are two tickets on stackoverflow that hint that this may be a race condition (also when using redis for ratelimiting).
https://stackoverflow.com/questions/42350277/redis-keys-getting-stuck-with- …

experiment(ratelimit): add runtime config to rate limit with redis transaction

---

rust_snuba/src/config.rs
rust_snuba/src/consumer.rs

Some config data passed from Python (specifically, logical topic name) does not appear to be as expected in production. Let's log the whole config object when the consumer starts to help with debugging.

feat(rust): Log config when consumer starts up

---

gocd/pipelines/snuba-stable.yaml
gocd/templates/bash/deploy.sh

Seeing error in when the cron job is run that the cardinality file does not exist. Guessing that its because it is using an older container image which does not have the required change. Deploying newer images might help.

ci(cardinality): Deploy the new container image

---

snuba/web/views.py

The single tenant datadog is gaslighting us by saying we are not sending the referrer. This PR is introducing some simple logging to see if the problem is on the snuba side

debug(oncall): log referrer at the view level

---

snuba/web/views.py

It looks like on single tenant we are actually not parsing a referrer out the the request. Double check whether this is actually a snuba issue or not by logging the full request body

observability(oncall): log full request on unknown referrers

---

rust_snuba/src/processors/querylog.rs

No need to implement our own way of serializing uuid

fix(rust): Simplify querylog UUID serialization

---

rust_snuba/Cargo.lock
rust_snuba/rust_arroyo/Cargo.toml
rust_snuba/rust_arroyo/examples/base_consumer.rs
rust_snuba/rust_arroyo/examples/base_processor.rs
rust_snuba/rust_arroyo/examples/transform_and_produce.rs
rust_snuba/rust_arroyo/src/backends/kafka/mod.rs
rust_snuba/rust_arroyo/src/backends/kafka/producer.rs
rust_snuba/rust_arroyo/src/backends/local/broker.rs
rust_snuba/rust_arroyo/src/backends/local/mod.rs
rust_snuba/rust_arroyo/src/backends/storages/memory.rs
rust_snuba/rust_arroyo/src/processing/mod.rs
rust_snuba/rust_arroyo/src/processing/strategies/commit_offsets.rs
rust_snuba/rust_arroyo/src/processing/strategies/mod.rs
rust_snuba/rust_arroyo/src/processing/strategies/produce.rs
rust_snuba/rust_arroyo/src/processing/strategies/reduce.rs
rust_snuba/rust_arroyo/src/processing/strategies/transform.rs
rust_snuba/rust_arroyo/src/types/mod.rs
rust_snuba/src/consumer.rs
rust_snuba/src/strategies/python.rs
rust_snuba/src/strategies/validate_schema.rs

This also turns `Topic` into an `Arc<str>` which is cheaper to clone. Making `Topic` completely opaque like this also makes it possible to maybe intern it and make it eventually `Copy` as well.

Give `Topic` and `Partition` a `new` fn

---

snuba/web/db_query.py
tests/web/test_db_query.py

In certain cases we would like to allow a referrer to override certain clickhouse settings. For example, in single tenant environments where the cluster is completely owned by a tenant we might want to allow them to use all replicas in parallel using setting like max_parallel_replicas. Making it referrer based allows the setting to only kick in for certain high volume bursty referrers rather than applying the settings at all times on the whole dataset.

feat(settings): Allow runtime configurable referrer overrides

---

rust_snuba/rust_arroyo/src/processing/dlq.rs
rust_snuba/rust_arroyo/src/processing/mod.rs

This is the start of the DLQ implementation. It adds the struct that keeps track of seen messages from the broker so they can be produced to the DLQ if needed later.
It is basically a 1:1 port of current Arroyo code here ( https://github.com/getsentry/arroyo/blob/112667abdc2ef5c9137e361c0b2bbf69703bc524/arroyo/dlq.py#L215-L269) that we run in the Python consumer. Actual DLQing of messages will be implemented as a follow up.

feat(rust): Port the buffered messages class to Rust

---

rust_snuba/rust_arroyo/examples/base_consumer.rs
rust_snuba/rust_arroyo/src/backends/kafka/mod.rs
rust_snuba/rust_arroyo/src/backends/local/mod.rs
rust_snuba/rust_arroyo/src/backends/mod.rs
rust_snuba/rust_arroyo/src/processing/mod.rs

The `AssignmentCallbacks` don’t need to take `&mut self`, which can remove one `Mutex`.
The reason for this is that the only non-test usage has internal `Mutex` usage anyway.

Avoid Mutex on `AssignmentCallbacks`

---

rust_snuba/src/processors/mod.rs
rust_snuba/src/processors/spans.rs
rust_snuba/src/processors/utils.rs

The need to setup default retention days and converting hex to string are needed across different processors. Lets move them out so that we can reuse them easily.

chore(rust): Move common functionality out to utils

---

rust_snuba/rust_arroyo/src/processing/mod.rs
rust_snuba/rust_arroyo/src/utils/metrics.rs
rust_snuba/src/metrics/statsd.rs
rust_snuba/src/metrics/testing.rs

No need for gauge() and timing() to take &mut self when increment() only takes &self.

ref(rust): Fix inconsistency in metrics trait

---

rust_snuba/rust_arroyo/src/processing/dlq.rs
rust_snuba/rust_arroyo/src/processing/mod.rs
rust_snuba/rust_arroyo/src/processing/strategies/commit_offsets.rs
rust_snuba/rust_arroyo/src/processing/strategies/mod.rs
rust_snuba/rust_arroyo/src/processing/strategies/produce.rs
rust_snuba/rust_arroyo/src/types/mod.rs
rust_snuba/src/processors/functions.rs
rust_snuba/src/processors/profiles.rs
rust_snuba/src/processors/querylog.rs
rust_snuba/src/processors/spans.rs

This is just a bunch of refactorings introducing `let-else` and other patterns to avoid rightward drift in a ton of places.
Best reviewed with the "ignore whitespace" setting.

Use more early-returns

---

rust_snuba/Cargo.lock
rust_snuba/Cargo.toml
rust_snuba/rust_arroyo/Cargo.toml
rust_snuba/src/consumer.rs
rust_snuba/src/factory.rs
rust_snuba/src/processors/functions.rs
rust_snuba/src/processors/mod.rs
rust_snuba/src/processors/profiles.rs
rust_snuba/src/processors/querylog.rs
rust_snuba/src/processors/spans.rs
rust_snuba/src/types.rs

This removes the `BadMessage` error type and related manual logging and error conversion. It also centralizes logging of those errors, configuring anyhow in such a way that it captures stack traces in those cases, and sends those errors to Sentry, however without the failing payloads for now.
Apart from this, it also streamlines some of the processors, in particular removing manual `Uuid` parsing, and avoiding a bunch of `Clone`s.
fixes SNS-2523
however, SNS-2529 is not quite fixed by this

Remove `BadMessage` in favor of `anyhow::Error`

---

rust_snuba/rust_arroyo/examples/base_processor.rs
rust_snuba/rust_arroyo/src/processing/mod.rs

This adds source information to `RunError::PauseError` and `RunError::PollError`. It also unwraps in the `base_processor` example to make it obvious when an error happens.

ref(rust): Add source information to `RunError`

---

rust_snuba/src/factory.rs
rust_snuba/src/strategies/validate_schema.rs

Thus far, the schema validation was running in the "main" thread (the one calling `get_task`), and not on the thread pool actually executing the resulting Future.
Now, the schema validation itself will happen inside of the spawned Task.

Move `SchemaValidator` into async task 

---

CODEOWNERS

This is likely temporary for the duration of the rust consumer project

meta: Make processing team codeowners

---

snuba/request/validation.py
snuba/web/views.py
tests/request/test_build_request.py

Currently, ST datadog is not displaying metrics with the proper tagged referrers. This is because in ST, the referrer (as part of the HTTP request) is not being sent. However, the referrer within the tenant_id (part of the body) is being sent. We enforce this in our allocation policies. This PR is responsible for only using the referrer being passed in the tenant_id. A runtime config `only_use_tenant_id_referrer` is used in case of unexpected behaviours.

fix(referrer): Only use referrer passed in tenant_ids

---

rust_snuba/rust_arroyo/src/processing/strategies/reduce.rs
rust_snuba/rust_arroyo/src/processing/strategies/run_task_in_threads.rs

Duration can't be negative so it is not safe to subtract elapsed from timeout like the prior approach did

fix(rust): Fix duration underflow

---

.github/workflows/ci.yml
snuba/query/processors/physical/prewhere.py

Coming from https://github.com/getsentry/sentry/pull/60050/files
Sentry does not use this target anymore, we just use it for CI. So we just put it in our CI workflow

Move sentry makefile target into snuba

---

rust_snuba/rust_arroyo/src/processing/mod.rs

I'm a bit paranoid this is somehow not exiting properly due do inability to acquire consumer lock. Let's add some (probably temporary) logging to make sure that's not happening.

ref(rust): Add some temporary logging to the on_revoke method

---

snuba/cli/consumer.py

--processes is not available in Rust consumers because it's a bad name
if you're really using threads.
Make it so that there is overlap between Python and Rust again.

fix: Introduce --concurrency as alias for --processes

---

snuba/consumers/consumer.py
snuba/consumers/strategy_factory.py

Recent arroyo versions have a default for input_block_size even if
multiple processes are used. That default is to dynamically resize
blocks, and has never been used in production. The plan is to gradually
remove input-block-size parameters in production and see what happens.

ref: Allow omission of input-block-size

---

rust_snuba/Cargo.toml
rust_snuba/rust_arroyo/examples/transform_and_produce.rs
rust_snuba/rust_arroyo/src/processing/strategies/produce.rs
rust_snuba/rust_arroyo/src/processing/strategies/run_task_in_threads.rs
rust_snuba/src/consumer.rs
rust_snuba/src/factory.rs
rust_snuba/src/strategies/clickhouse.rs
rust_snuba/src/strategies/commit_log.rs
rust_snuba/src/strategies/validate_schema.rs

Instead of having each `RunTaskInThreads` strategy spawn (and kill) its own runtime every time it is (re-)started, usage of runtimes is now controlled using a `ConcurrencyConfig`.
This way, all the strategies that internally run in a thread pool will share that same thread pool.
That also means that the total number of (worker) threads that are spawned is truely limited to `concurrency`, and not `concurrency * number-of-RunTaskInThreads`.

Spawn only one Tokio Runtime

---

snuba/subscriptions/data.py
tests/query/snql/test_invalid_queries.py
tests/query/snql/test_query.py
tests/query/snql/test_snql_anonymizer.py
tests/subscriptions/__init__.py
tests/subscriptions/test_data.py

Issues team wants to create error metric alerts that filter out archived issues. To do this we need to join to the group attributes table. This pr adds the ability to support joins to the subscription system.

Add support for join queries to the subscription system

---

snuba/migrations/group_loader.py
snuba/snuba_migrations/generic_metrics/0026_gauges_add_raw_tags_hash_column.py

This column already exists on the local tables, adding to the gauges dist tables.
Requires: https://github.com/getsentry/snuba/pull/4998

fix(generic-metrics): Add raw tags hash to gauges dist table

---

tests/clickhouse/optimize/test_optimize_tracker.py

This test is flaky and currently fails unexpectedly in CI which blocks deploys.

fix(optimize): Skip flaky test_optimized_partition_tracker unit test

---

rust_snuba/rust_arroyo/src/processing/mod.rs
rust_snuba/src/consumer.rs

In order to make the Rust consumer emit the same metrics as Python
consumer, we need to use the same namespace. This is probably risky as
it could break alerts that do not apply the correct tag filters. We'll
just find out, I'm oncall anyway.
Also add a metric that already exists in Python, to see if it will show
up correctly.

fix(rust): Rename metrics namespace, and implement one metric from python

---

rust_snuba/rust_arroyo/examples/transform_and_produce.rs
rust_snuba/rust_arroyo/src/backends/kafka/mod.rs
rust_snuba/rust_arroyo/src/backends/kafka/producer.rs
rust_snuba/rust_arroyo/src/backends/kafka/types.rs
rust_snuba/rust_arroyo/src/processing/mod.rs
rust_snuba/rust_arroyo/src/processing/strategies/commit_offsets.rs
rust_snuba/rust_arroyo/src/processing/strategies/produce.rs
rust_snuba/src/consumer.rs
rust_snuba/src/processors/functions.rs
rust_snuba/src/processors/profiles.rs
rust_snuba/src/processors/querylog.rs
rust_snuba/src/processors/spans.rs
rust_snuba/src/strategies/commit_log.rs
rust_snuba/src/strategies/python.rs
rust_snuba/src/strategies/validate_schema.rs

Another take on https://github.com/getsentry/snuba/pull/5044
This one uses a single Arc inside KafkaPayload instead of one for
each of the key, headers and payload. Goal was to make it even
cheaper to clone than v2.

feat(rust): Buffered messages option 3

---

rust_snuba/rust_arroyo/src/processing/mod.rs

This metric is not named the way I remember! I want it to overlap with: https://github.com/getsentry/arroyo/blob/ba85564a91f95b0188d626dd3c03bb855f15726c/arroyo/processing/processor.py#L336

fix(rust): Rename run_once metric

---

.github/workflows/ci.yml
gocd/pipelines/snuba-stable.yaml
gocd/templates/bash/check-github.sh
snuba/datasets/processors/errors_processor.py

This is wasteful since a lot of time is spent just setting up the tests (which has to be done on every shard) and not actually running the test suite.
Sentry org is hitting max concurrency on GitHub so this aims to help in other projects too.

ci: Reduce Sentry test concurrency

---

rust_snuba/rust_arroyo/src/backends/kafka/mod.rs
rust_snuba/rust_arroyo/src/backends/kafka/producer.rs
rust_snuba/rust_arroyo/src/backends/kafka/types.rs

There are 2 fixes in this PR:
1. Fix the producer so it actually produces the correct headers. These were omitted before so it never produced any headers even if they were present on the passed in KafkaPayload
2. Hide the internal rdkakfa BorrowedHeaders/OwnedHeaders types so they are not part of the arroyo API

fix(rust): Kafka headers improvements

---

rust_snuba/src/config.rs
rust_snuba/src/consumer.rs

Ensure broker config is always properly deserialized. Previously this was done in the consumer code, but we should move it to the config, so it will also work in other scenarios where we need broker config - such as the replacements producer and the commit log producer.

ref(rust): Move broker config validation into deserializer

---

rust_snuba/rust_arroyo/src/processing/metrics_buffer.rs
rust_snuba/rust_arroyo/src/utils/metrics.rs
rust_snuba/src/consumer.rs

at some point `metrics.incr` had `&mut self`, and back then it was necessary

fix: Remove unnecessary locking in metrics

---

rust_snuba/rust_arroyo/src/processing/dlq.rs

This adds the DLQ limit, DLQ policy and the DLQ producer trait with a noop and Kafka implementation.
These pieces are not yet being used - they will be integrated with the StreamProcessor/message buffer in a separate step.
The code here largely maps 1:1 with the Python reference implementation https://github.com/getsentry/arroyo/blob/main/arroyo/dlq.py.

feat(rust): Add building blocks for DLQ

---

snuba/replacers/errors_replacer.py
tests/datasets/test_errors_replacer.py

A bad message was sent to ReplaceGroup that used the `+00:00` format instead of
`.000Z` format. In order to continue processing, handle that edge case just for
the ReplaceGroup class. As a follow up the emitter of the bad message will be
fixed.

fix(replacegroup): Catch bad datetime formats in ReplaceGroup

---

rust_snuba/src/factory.rs
rust_snuba/src/processors/functions.rs
rust_snuba/src/processors/mod.rs
rust_snuba/src/processors/profiles.rs
rust_snuba/src/processors/querylog.rs
rust_snuba/src/processors/spans.rs
rust_snuba/src/strategies/commit_log.rs
rust_snuba/src/strategies/python.rs
rust_snuba/src/types.rs

The ProduceCommitLog should get a message with type `BytesInsertBatch` from the prior processing step, and produces one message for each partition contained within that batch. The prior version where it got a `KafkaPayload` and produced a single message was wrong.
In order to achieve this, this splits the `BytesInsertBatch` into two separate structs. Now we have `RowData` which we require the message processors to return, as well as `BytesInsertBatch` which is now internal to Snuba and contains other metadata that we will add for producing to the commit log.

fix(rust): Fix the ProduceCommitLog strategy

---

snuba/migrations/group_loader.py
snuba/snuba_migrations/generic_metrics/0028_distributions_add_indexed_tags_column.py

The distributions table already has the _raw_tags_hash column, but it is
missing the _indexed_tags_hash column to make it consistent with the other
metric types.

fix(metrics) Add _indexed_tags_hash column to distributions

---

Dockerfile

The events in sentry for the snuba project are no longer being tagged with a release, I think that it _might_ have been due to https://github.com/getsentry/snuba/pull/4551/ since changes to the Dockerfile were made.
I'm moving the ENV chunk before running the `api` since I'm assuming that's why the `SNUBA_RELEASE` isn't being picked up.

fix: make sure SNUBA_RELEASE is set

---

snuba/datasets/configuration/spans/entities/spans.yaml
snuba/datasets/configuration/spans/storages/spans.yaml

The `profile_id` column was added to spans: https://github.com/getsentry/snuba/blob/master/snuba/snuba_migrations/spans/0006_spans_add_profile_id.py. However, it wasn't added to the storage and entity yet. As a result, a few users are experiencing snuba errors when querying for this column.

fix(spans): Add profile_id to spans query columns

---

rust_snuba/Cargo.toml
rust_snuba/bin/python_processor_infinite.rs
rust_snuba/rust_arroyo/src/processing/strategies/run_task.rs
rust_snuba/rust_arroyo/src/types/mod.rs
rust_snuba/src/lib.rs
rust_snuba/src/strategies/mod.rs
rust_snuba/src/strategies/noop.rs
rust_snuba/src/strategies/python.rs

max_queue_depth does not work as it is implemented right now, but now
that we expose it as a parameter, we might as well use it to determine
how many handles are supposed to be in-flight.
The original theory was correct though: We are blocking too much in
check_for_results, and that's the culprit for our performance problems.
Now the next performance problem is the serialization overhead for
individual messages between processes, and we might have to implement
batching to fix that. But at the very least the processor can now
saturate 5 cores on my machine.

fix(rust-python): Join handles less frequently, fix backpressure bug

---

gocd/templates/bash/saas-sentry-error-check.sh

The rate limit warnings that go to Sentry was causing this check to trip up and
prevent the deploy pipeline from working. Skip warning error events when
running this check.
Depends on https://github.com/getsentry/devinfra-deployment-service/pull/503

fix: Skip warnings in gocd error checks

---

snuba/datasets/configuration/discover/entities/discover.yaml
snuba/datasets/configuration/discover/entities/discover_events.yaml
snuba/datasets/configuration/discover/entities/discover_transactions.yaml

Change the discover entities to reject queries with invalid columns.
This has been tested in production, by logging warnings instead of errors. All
the instances of invalid columns being logged were from queries with invalid
columns.

fix(discover): Enable column validator on discover entities

---

rust_snuba/benches/processors.rs
rust_snuba/rust_arroyo/examples/base_processor.rs
rust_snuba/rust_arroyo/examples/transform_and_produce.rs
rust_snuba/rust_arroyo/src/processing/dlq.rs
rust_snuba/rust_arroyo/src/processing/mod.rs
rust_snuba/src/consumer.rs

This change starts wiring up the DLQ policy and producer.
- The StreamProcessor now takes an optional dlq_policy parameter, which defines the policy to be applied to invalid messages.
- The dlq_policy is applied for consumers/topics where a value for `dlq_topic` is defined (this comes from storage .yaml files), otherwise it is None and no messages will be DLQ'ed.
- The policy is not being used by the StreamProcessor yet

feat(rust): Pass the DLQ policy to stream processor

---

rust_snuba/rust_arroyo/src/processing/mod.rs

Processing time was understated since we were not counting the time spent in strategy.poll() which is where a lot of consumers do processing work. This is now aligned with the Python Arroyo implementation.

fix(rust): Fix processing time metric

---

rust_snuba/src/strategies/python.rs

in https://github.com/getsentry/snuba/pull/5088 i introduced a bug that would
make the python processor permanently backpressure if there was ever
backpressure from the next_step at any point
we currently experience deadlocks in hybrid consumer, but this bugfix _should_
be unrelated, as the clickhouse writer step _should_ never apply backpressure
and we'd never run into this scenario

fix(rust): Fix deadlock on backpressure

---

snuba/datasets/configuration/generic_metrics/entities/counters.yaml
snuba/datasets/configuration/generic_metrics/entities/distributions.yaml
snuba/datasets/configuration/generic_metrics/entities/gauges.yaml
snuba/datasets/configuration/generic_metrics/entities/sets.yaml
tests/test_metrics_sdk_api.py

This column needs to be queried in order to get proper meta information about
the tags and their values in the tables. Ensure that it can be queried with
SnQL.

fix(generic_metrics): Expose tags.raw_value in the generic_metrics entities

---

rust_snuba/benches/processors.rs

It turns out that `get_metrics` and the associated `Arc::drop` is hot enough in benchmarks that it makes a difference.

Initialize metrics in benchmarks

---

rust_snuba/rust_arroyo/src/backends/kafka/mod.rs
rust_snuba/rust_arroyo/src/backends/local/mod.rs
rust_snuba/rust_arroyo/src/backends/mod.rs
rust_snuba/rust_arroyo/src/processing/mod.rs

Offsets are never actually staged without immediately committing them, so we might as well roll the two functions into one.
The `Consumer::commit_offsets` method gains an `offsets` parameter (that was previously on `stage_offsets`) and now only returns `()` in the `Ok` case.
~In the Kafka backend, the `Mutex` around the base consumer is replaced with an `RwLock`, since all calls to the base consumer only require a shared reference. The only times we need a `write` lock are in `subscribe` and `close`, where the base consumer is created and destroyed, respectively.~

ref(rust): Remove offset staging

---

rust_snuba/rust_arroyo/src/processing/mod.rs

Committing offsets in on_revoke still does not appear to be working, add some logging

fix(rust): Log error if committing offsets fails

---

rust_snuba/rust_arroyo/src/backends/local/broker.rs
rust_snuba/rust_arroyo/src/backends/local/mod.rs

Fixes #5121.
We only call `LocalBroker::unsubscribe` in `close` if we are subscribed to at least one topic—I hope that logic is sound?
Additionally it removes some `unwrap`s in `LocalBroker` in favor of returning an empty vector of partitions.

fix(rust): Don't double-unsubscribe in LocalConsumer

---

rust_snuba/rust_arroyo/src/processing/dlq.rs
rust_snuba/rust_arroyo/src/processing/mod.rs
rust_snuba/src/consumer.rs

This adds the basic DLQ implementation. Invalid messages are automatically produced to the DLQ if a topic is defined for the storage.
The feature is not enabled unless `skip_write` is set to False, as we should not be producing any data to actual topics in prod otherwise.
There are a couple of features that are not yet implemented yet and will need to be done as a followup:
- DLQ limits are currently ignored and still need to be wired up
- The DLQ producer should be flushed prior to committing offsets in the revocation callback

feat(rust): Produce invalid messages to DLQ

---

snuba/query/joins/subquery_generator.py
tests/query/joins/join_structures.py
tests/query/joins/test_subqueries.py
tests/test_snql_api.py

The granularity was not being pushed down to the subqueries created in a
CompositeQuery join. That meant that the TimeSeriesProcessor (an entity level
processor) didn't have access to the granularity and wasn't being executed
correctly.
Push the granularity down to all the subqueries so they can be properly
handled.

fix(joins) Push granularity down to the subqueries

---

rust_snuba/src/strategies/clickhouse.rs

I wanted to verify that those metrics show up, but i can't because we
are not actually writing to clickhouse.

fix(rust): Record SLO metrics even when writes are skipped

---

rust_snuba/benches/processors.rs
rust_snuba/rust_arroyo/examples/base_consumer.rs
rust_snuba/rust_arroyo/examples/base_processor.rs
rust_snuba/rust_arroyo/examples/transform_and_produce.rs
rust_snuba/rust_arroyo/src/backends/kafka/mod.rs
rust_snuba/rust_arroyo/src/backends/local/mod.rs
rust_snuba/rust_arroyo/src/backends/mod.rs
rust_snuba/rust_arroyo/src/processing/mod.rs
rust_snuba/src/consumer.rs

This is the first part of an effort to make sure consumers and processors are never in invalid states. The first part is https://github.com/getsentry/snuba/pull/5123.
It removes the methods `subscribe`, `unsubscribe`, `close`, and `shutdown` from `Consumer` and `StreamProcessor`. What was `subscribe` now happens at construction time, while the other functions are moved to `Drop` implementations where necessary.
In other words, no consumer or processor is ever in an unsubscribed state. This removes a lot of checks for whether a consumer is still being polled after it has been closed, &c.
It also adds a constructor `with_kafka` to `StreamProcessor` that removes a lot of the complication from building a `StreamProcessor` in the Kafka case:
```rust
impl StreamProcessor<KafkaPayload> {
pub fn …
```

ref(rust): Remove invalid states from consumers and processors

---

rust_snuba/benches/processors.rs
rust_snuba/rust_arroyo/examples/base_consumer.rs
rust_snuba/rust_arroyo/examples/base_processor.rs
rust_snuba/rust_arroyo/examples/transform_and_produce.rs
rust_snuba/rust_arroyo/src/backends/kafka/mod.rs
rust_snuba/rust_arroyo/src/backends/local/mod.rs
rust_snuba/rust_arroyo/src/backends/mod.rs
rust_snuba/rust_arroyo/src/processing/mod.rs
rust_snuba/src/consumer.rs

This is the first part of an effort to make sure consumers and processors are never in invalid states.
It changes the order in which the parts of `Consumers`/`StreamProcessors` are created so that all the parts must always be there before the whole object. This makes a bunch of `Option` unwrapping unnecessary.
Concretely, it now works like this:
1. Construct a `ConsumerState` from a `StrategyFactory`
2. Construct a `Consumer` from (an `Arc` copy of) the `ConsumerState`
3. Construct a `StreamProcessor` from the `Consumer` and another `Arc` copy of the `ConsumerState`.
Having to manually create the `ConsumerState` (which is really an implementation detail) makes this really cumbersome. This is addressed in TBA.

ref(rust): Change order of consumer/processor creation

---

snuba/datasets/configuration/events/entities/events.yaml

The only warning from errors that sounded off this week was a valid non-existing column:
https://sentry.sentry.io/issues/?groupStatsPeriod=auto&page=0&project=300688&query=is%3Aunresolved+Query+column&referrer=issue-list&statsPeriod=7d
We can safely turn this on

feat(slo): validate errors data model

---

rust_snuba/Cargo.lock
rust_snuba/rust_arroyo/Cargo.toml
rust_snuba/rust_arroyo/src/backends/kafka/mod.rs

This explicitly uses `Hub::run` to trigger logging within a Sentry Hub. The hunch here would be that these logs are running on a background thread that was initialized before Sentry, and so has not inherited a properly configured Hub.
This would be a fix for SNS-2546 if indeed this is the problem.

Run rdkafka logging with an explicit Sentry Hub

---

rust_snuba/rust_arroyo/src/processing/mod.rs

Port over the parts from https://github.com/getsentry/arroyo/pull/310
that make sense -- some of the metrics I added there are duplicates and
are named poorly, and I don't think we need those to line up 1:1 (also
because callbacks in rust work slightly differently)

ref(rust): Add some rebalancing-related metrics

---

snuba/datasets/configuration/functions/entities/functions.yaml
snuba/datasets/configuration/groupassignee/entities/groupassignee.yaml
snuba/datasets/configuration/groupedmessage/entities/groupedmessage.yaml
snuba/datasets/configuration/outcomes/entities/outcomes.yaml
snuba/datasets/configuration/outcomes_raw/entities/outcomes_raw.yaml
snuba/datasets/configuration/profiles/entities/profiles.yaml
snuba/datasets/configuration/sessions/entities/org.yaml
snuba/datasets/configuration/sessions/entities/sessions.yaml
snuba/datasets/configuration/transactions/entities/transactions.yaml

In the past week, there were no missing query column warnings for these entities in sentry. 
See: https://sentry.sentry.io/issues/?groupStatsPeriod=auto&page=0&project=300688&query=is%3Aunresolved+Query+column&referrer=issue-list&statsPeriod=7d
We can safely turn this on for these entities.

oncall(validation): Turn on query column validator for more entities

---

snuba/admin/production_queries/prod_queries.py
snuba/clickhouse/query_dsl/accessors.py
snuba/query/__init__.py
tests/admin/test_production_queries.py
tests/clickhouse/query_dsl/test_accessors.py

Fixes: https://getsentry.atlassian.net/jira/software/c/projects/SNS/issues/SNS-2537
When project ids are specified in subqueries, the production queries tool breaks because we don't look in subqueries for the project ids. make the function doing this recursive so we do look for it

fix(admin): look for project_ids in subqueries

---

rust_snuba/src/consumer.rs
snuba/cli/rust_consumer.py

This doesn't do anything yet, just adding the flag first and passing it through to the Rust Kafka config. 
Merging this first allows us to start passing this flag in some of our test consumers that are already running before we flip the actual behavior over to strict mode with the rest of the implementation.

feat(rust): Add --no-strict-offset-reset to the Rust CLI

---

rust_snuba/rust_arroyo/src/processing/dlq.rs

Closes SNS-2550.
This implements the `DlqLimitState` struct in a way that's similar, but not identical to the Python version.
Differences:
* internally it keeps a single map collecting the numbers of valid messages, invalid messages, consecutive invalid messages, and the offset of the last invalid message per partition, instead of four separate maps.
* the `update_invalid_value` and `should_accept` methods have been combined into `record_invalid_message`, since they are never called separately in the Python implementation.
This implementations also makes the following property explicit that AFAICT is intended in the Python version: the `DlqLimitState` is instantiated with a list of partitions that is never mutated later and any message outside of these partitions is rejected.

feat(rust): Implement DlqLimitState

---

snuba/datasets/readiness_state.py
snuba/settings/__init__.py

This state is meant for experimental features that should only be used locally
or in S4S.

ref: Add experimental readiness state

---

requirements.txt
snuba/consumers/consumer.py
snuba/consumers/strategy_factory.py
snuba/consumers/utils.py

Contains perf improvements for rebalancing

perf: Arroyo 2.15.0 and reusable multiprocessing pools

---

rust_snuba/rust_arroyo/examples/base_consumer.rs
rust_snuba/rust_arroyo/examples/base_processor.rs
rust_snuba/rust_arroyo/examples/transform_and_produce.rs
rust_snuba/rust_arroyo/src/backends/kafka/config.rs
rust_snuba/rust_arroyo/src/backends/kafka/mod.rs
rust_snuba/rust_arroyo/src/processing/strategies/produce.rs
rust_snuba/src/consumer.rs

This uses the `InitialCommit` enum instead of a `String` everywhere. It's only parsed once (in `consumer_impl`) and serialized once (when serializing to the `rdkafka` configuration).

ref(rust): Use enum pervasively

---

requirements.txt
snuba/cli/consumer.py
snuba/consumers/consumer.py
snuba/consumers/strategy_factory.py

Try https://github.com/getsentry/snuba/pull/5170 again with a high join timeout.
This PR is a short term test that should be reverted. We want to check if there's any correlation between join timeout and the consumer issues we saw with arroyo 2.15.0 earlier.

feat: Multiprocessing experiment

---

rust_snuba/rust_arroyo/src/processing/mod.rs

If InvalidMessage was raised in strategy.poll(), we were not previously submitting the message to the DLQ, but putting it back so it would be constantly resubmitted (i.e. handling it like backpressure, which is wrong).

fix(rust): Actually produce to DLQ

---

gocd/templates/jsonnetfile.json
gocd/templates/jsonnetfile.lock.json

Bumping to v2.7 of gocd-jsonnet which should remove the de region temporarily while we figure out why it is broken and remove customer-5 as we are getting rid of it.

chore(gocd): bump gocd-jsonnet version

---

requirements.txt
snuba/datasets/processors/outcomes_processor.py
tests/test_outcomes_api.py

bumping snuba because we introduce new datacategory in https://github.com/getsentry/relay/pull/2824

chore(dep): Bump sentry-relay from 0.8.27 to 0.8.39

---

rust_snuba/rust_arroyo/src/processing/dlq.rs

We were not producing anything to the DLQ because after calling the
async fn, we scheduled the future onto a runtime that we already dropped
in the constructor of DlqProducer. Holding onto the Handle is not
enough, we need the entire Runtime.
Also adjust tests so the error becomes apparent: now the counter is not
incremented if the future isn't polled at least once.

fix(rust/dlq): Do not drop runtime and accidentally cancel tasks

---

rust_snuba/rust_arroyo/src/backends/kafka/mod.rs

This fixes the same bug as https://github.com/getsentry/snuba/pull/5181,
but with a test and without the potential to suppress all kinds of
poll() errors mid-operation. Still a gross hack though.
Also fix a bug where consumer.tell() would be out of date once
consumer.commit_offsets was used. ~We don't really use tell() in prod so
it didn't come up.~
**We do use consumer.tell() extensively in prod.** I don't know why we didn't notice this bug sooner. Potentially affected areas:
* paused consumer -- unclear why we didn't hit it. do our strategies just never backpressure?
* dlq -- maybe it works now?

fix(rust): Suppress error when manually resetting offsets

---

snuba/datasets/processors/metrics_summaries_processor.py

There's not point of calling more functions if the field we're interested in is not there.

ref(metrics-summaries): Skip all the work if the field needed is not there

---

rust_snuba/src/types.rs
snuba/settings/__init__.py

Previously:
* https://github.com/getsentry/snuba/pull/5165
* https://github.com/getsentry/snuba/pull/5169
The default value of earliest_timestamp was 0, so for max_latency_ms we
always current_time() - 0

fix(rust): Fix SLO metrics again again again [SNS-2565]

---

snuba/cli/consumer.py

A few consumers (spans, generic metrics distributions) regularly exceed the 5 second timeout currently configured, and cannot finish processing pending work in time. When this is the case, the multiprocessing pool cannot be reused since there is state in the pool that cannot be carried over to the next assignment. This aims to avoid that scenario.

perf: Increase consumer join timeout

---

snuba/querylog/query_metadata.py
snuba/state/cache/redis/backend.py
tests/test_api_status.py

When the query takes longer than the cache thread timeout, the executor raises
a concurrent.futures.TimeoutError. This was mislabelled as a cache set error,
which it is not. The cache set happens further down in the execution, and a
warning is logged for that. This is a query simply taking too long to run.
As such, reword the error to be slightly more informative and create a new
status to track the difference between a query taking to long to run and a
query that fails to set the cache.

fix(cache): Slightly clean up cache set errors

---

rust_snuba/benches/processors.rs
rust_snuba/src/consumer.rs
rust_snuba/src/factory.rs

This is a partial reversal of https://github.com/getsentry/snuba/pull/5039
We want to scale processing speed separately from the concurrency of
INSERTs we hit clickhouse with. This does not necessarily mean a
separate threadpool, it's just the easiest way to ensure that.
This is equivalent to what we do in Python (again): https://github.com/getsentry/snuba/blob/59732199ceded1dfd239389b0b10b3a48152da8c/snuba/consumers/strategy_factory.py#L139-L140

fix(rust): Separate clickhouse concurrency from processing

---

snuba/admin/auth_roles.py
snuba/admin/iam_policy/iam_policy.json

This will allow ops to revert migrations that have been run more than 24hrs ago (which is our limit for the `NonBlockingMigrationsExecutor` role. It makes sense to all folks on ops to have these permissions because they already have access to the machines.

ref(admin): Add AllMigrations role

---

snuba/cli/consumer.py
snuba/cli/dlq_consumer.py
snuba/consumers/consumer_builder.py
snuba/consumers/strategy_factory.py
snuba/web/views.py
tests/consumers/test_consumer_builder.py
tests/test_consumer.py

INC-588 INC-581
This should help us identify pod-specific problems, such as one
partition lagging behind another.
Ideally arroyo should do this, but it's easier here because arroyo has
no concept of global tags.

fix(arroyo): Tag all consumer metrics by the smallest partition index

---

snuba/migrations/policies.py
tests/migrations/test_policies.py

In the case of experimental groups (`ReadinessState.EXPERIMENTAL`) we can give folks who have access to run and reverse migrations as needed while they are developing.

ref(migrations): add experimental readiness state to policies

---

rust_snuba/Cargo.lock
rust_snuba/Cargo.toml
rust_snuba/benches/processors.rs
rust_snuba/rust_arroyo/Cargo.toml
rust_snuba/rust_arroyo/src/backends/kafka/mod.rs
rust_snuba/rust_arroyo/src/backends/local/mod.rs
rust_snuba/rust_arroyo/src/processing/mod.rs
rust_snuba/rust_arroyo/src/processing/strategies/produce.rs
rust_snuba/rust_arroyo/src/processing/strategies/run_task_in_threads.rs

If strategy panics in poll, submit, join or close, we terminate the consumer now
We swap out std::sync::Mutex for parking_lot::Mutex everywhere to avoid lock poisioning.
fixes SNS-2539
<details>
<summary>contents of jira ticket</summary>
EIther induce a panic in a strategy, or segfault in a message processor in python like so (put this in def process_message):
import ctypes; ctypes.string_at(0)
then, start the consumer.
you will observe the main thread panicking, but at the same time the program won’t stop and also no longer reacts to Ctrl-C (SIGTERM still works). i profiled this with samply to get a stacktrace at the time of the deadlock, and we are locking up in the Drop impl of rdkafka’s NativeClient.
There are a few tickets in rust-rdkafka that hint at this being a potential problem: …

fix(rust): Fix consumer deadlock on strategy panic

---

rust_snuba/benches/processors.rs
rust_snuba/rust_arroyo/src/processing/metrics_buffer.rs
rust_snuba/rust_arroyo/src/processing/mod.rs
rust_snuba/rust_arroyo/src/processing/strategies/run_task_in_threads.rs
rust_snuba/rust_arroyo/src/utils/metrics.rs
rust_snuba/src/strategies/clickhouse.rs
rust_snuba/src/types.rs

This has a bunch of micro-optimizations:
- Moves the `Arc<Mutex>` into `ConsumerState`.
- Avoids two locking operations per `run_once` by moving the `is_paused` flag to an `AtomicBool`. Though this is pretty much academic since we never have contention on this lock anyway, as it is purely single-threaded.
- Optimizes global metrics a bit by avoiding the `Arc` completely, and instead just use a `&'static dyn Metrics`.

Optimize ConsumerState

---

snuba/admin/iam_policy/iam_policy.json

`team-ingestion-pipeline` was added in #4458 and since then removed (see https://github.com/getsentry/security-as-code/pull/515/) and unified under `team-ingest`

perm(cardinality-analyzer): Replace team-ingestion-pipeline with team-ingest

---

rust_snuba/src/processors/functions.rs
rust_snuba/src/processors/metrics_summaries.rs
rust_snuba/src/processors/profiles.rs
rust_snuba/src/processors/querylog.rs
rust_snuba/src/processors/replays.rs
rust_snuba/src/processors/spans.rs
rust_snuba/src/strategies/commit_log.rs
rust_snuba/src/strategies/processor.rs
rust_snuba/src/strategies/python.rs
rust_snuba/src/types.rs

This directly serializes an `Iterator<impl Serialize>` into the output rows. Doing so, it can avoid a bunch of intermediate allocations, as well as simplify its usage.

Serialize Rows directly

---

snuba/datasets/configuration/querylog/storages/querylog.yaml
snuba/migrations/group_loader.py
snuba/snuba_migrations/querylog/0007_add_offset_column.py

add partition and offset columns to querylog like most other datasets have it. we recently deployed rust consumers to querylog in saas, and this will allow us to check whether we are dropping any messages between kafka and clickhouse

fix(querylog): Add partition and offset columns, migration

---

rust_snuba/src/strategies/clickhouse.rs

The rust implementation of writing to clickhouse is missing certain settings we use in the python version. Added those settings as query parameters to the clickhouse writer implementation. The python settings can be found [here](https://github.com/getsentry/snuba/blob/master/snuba/consumers/consumer.py#L400)

fix(rust): Add settings to cickhouse writer

---

rust_snuba/rust_arroyo/src/backends/kafka/mod.rs
rust_snuba/rust_arroyo/src/testutils.rs

Implement pause/seek/resume/tell properly, and attempt to reproduce a rdkafka bug mentioned in python-arroyo where seek + pause would ignore the seek, + write testcase
SNS-2556

fix(rust): pause/resume bugfixes

---

snuba/cli/rust_consumer.py

The Rust consumer running Python is highly experimental - we should flip the default so pure Rust is default rather than hybrid. This is the first step towards that. We need to ensure the --use-python-processor flag is passed everywhere in prod before actually changing the default in the CLI.

ref(rust): Support --use-python-processor in CLI

---

rust_snuba/src/processors/mod.rs
rust_snuba/src/processors/outcomes.rs
rust_snuba/src/processors/utils.rs
rust_snuba/src/types.rs
snuba/datasets/processors/outcomes_processor.py
tests/consumers/test_message_processors.py

This ports all of the functionality from the Python message processor, including recording metrics (even though they seem like they may be unnecessary?).
It involves a small refactor to the Python message processor to produce unix timestamp instead of Python datetime objects so that the outputs of the 2 message processors are easier to compare in tests.

feat(rust): Port outcomes message processor to Rust

---

gocd/templates/bash/deploy.sh

This was removed because it was crashlooping earlier and preventing Snuba deploys from completing successfully. Let's put it back now we have re-implemented the hybrid consumer and fixed the offset reset issues that were previously causing the consumer to crash.

ref: Add hybrid querylog consumer back to gocd deployment

---

snuba/consumers/rust_processor.py

This fixes crashloop in the hybrid spans consumer

fix(rust): Ensure Python does not return naive datetime to Rust consumer

---

Dockerfile

The LD_PRELOAD path was hardcoded to an x86-specific path, causing random non-fatal errors in the docker build process for the ARM image such as:
```
#22 11.35 ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libjemalloc.so.2' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```
I don't exactly know how to use wildcards or commands inside of docker envvars,
so it seems simpler to symlink the file to a hardcoded location and
refer to that in LD_PRELOAD

fix(rust): Use jemalloc even on ARM image

---

Dockerfile

currently getting this in logs, plus a 60-second sleep() to really make it hurt
```
#17 0.874 
#17 0.874 ================================================================================
#17 0.874 ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
#17 0.874 ================================================================================
#17 0.874 
#17 0.874                            SCRIPT DEPRECATION WARNING                    
#17 0.874 
#17 0.874   
#17 0.874   This script, located at https://deb.nodesource.com/setup_X, used to
#17 0.874   install Node.js is deprecated now and will eventually be made inactive.
#17 0.874 
#17 0.874   Please visit the NodeSource distributions Github and follow the
#17 0.874   instructions to migrate your repo.
#17 0.874 …
```

fix(docker): Migrate away from deprecated nodesource script

---

snuba/consumers/rust_processor.py

If the hybrid consumer got a carried over message due to backpressure, we need to actually attempt to re-submit and clear it on poll. Otherwise it gets stuck in backpressure forever.

fix(rust): Fix bug with hybrid consumer backpressure state

---

snuba/query/indexer/resolver.py
snuba/query/mql/parser.py
tests/query/indexer/test_resolver.py
tests/query/parser/test_mql_query.py

This PR is responsible for correctly resolving tag filters in order to support release-health MQL queries. Firstly, we need to correctly assign `tags` and `tags_raw` columns for metrics and generic-metrics datasets respectively. Secondly, since both tag keys and tag values are indexed in release-health, we need to resolve the tag values of filters.
It is important to note that the call to the indexer happens in sentry. The mappings are passed as a dict to the request object and sent to the snuba API. Then, snuba query pipeline executes a "resolve" step which transforms the tags into the mapped integers. Therefore, this code simply ensures that the resolutions are execute, but it still the job of the metrics layer (sentry) to perform the indexer lookups and pass the correct mappings.

bug(mql): Support resolve release-health tag filters in MQL

---

Dockerfile
scripts/rust-dummy-build.sh

this should make PRs where Rust consumers are touched is touched significantly faster, as only application code is being rebuilt rather than the entire rust deptree.
we considered using `cargo chef`, but it doesn't work because our build tool is `maturin`, not `cargo`.
we also saw that relay instead mounts the `target/` folder into the docker container for caching, but i felt that this was harder to implement though it's probably better

ref(rust-docker): Build deps separately from main app

---

rust_snuba/Cargo.lock
rust_snuba/Cargo.toml
rust_snuba/benches/processors.rs
rust_snuba/src/lib.rs
rust_snuba/src/metrics/statsd.rs

re-attempt introduction of statsdproxy, failed previously at #5064. remove dbg!() statement that slows down the entire rust consumer. also fix up benchmarks to actually include statsd overhead.
main branch with benchmark fixes:
```
Timer precision: 41 ns
processors    fastest       │ slowest       │ median        │ mean          │ samples │ iters
├─ functions                │               │               │               │         │
│  ├─ 1       80.34 ms      │ 177.5 ms      │ 91.45 ms      │ 92.68 ms      │ 100     │ 100
│  │          62.23 Kitem/s │ 28.16 Kitem/s │ 54.67 Kitem/s │ 53.94 Kitem/s │         │
│  ├─ 4       51.08 ms      │ 110.4 ms      │ 57.13 ms      │ 59.04 ms      │ 100     │ 100
│  │          97.87 Kitem/s │ 45.28 Kitem/s │ 87.51 Kitem/s │ 84.68 Kitem/s │         │
│ …
```

ref(rust): Introduce statsdproxy v3

---

Dockerfile

This rebuilds the rust app on any change. that's bad!

fix(ci): Do not copy entire folder for rust build

---

.github/workflows/image.yml

there appears to be two problems with ARM64 builds:
* caches get invalidated for no obvious reasons
* QEMU is just really slow
let's disable for now. also https://github.com/getsentry/snuba/pull/5285 was probably a mistake, but not sure if it matters now with this PR. Rust is prohibitively expensive anyway and can't be built outside of the docker image.
the build is not required, but it's still expensive to run it

fix(rust): Disable ARM64 builds on PRs

---

rust_snuba/src/strategies/python_v2.rs
snuba/environment.py
tests/clickhouse/optimize/test_optimize_tracker.py
tests/test_api.py

We are experiencing CI flakes like this:
```
Traceback (most recent call last):
File "/usr/src/snuba/tests/clickhouse/optimize/test_optimize_tracker.py", line 282, in test_run_optimize_with_ongoing_merges
sleep_mock.assert_called_with(settings.OPTIMIZE_BASE_SLEEP_TIME)
File "/usr/local/lib/python3.10/unittest/mock.py", line 929, in assert_called_with
raise AssertionError(_error_message()) from cause
AssertionError: expected call not found.
Expected: sleep(300)
Actual: sleep(5)
```
This sleep(5) is the ondemand-profiler interfering with the mocked time.sleep call. Disable the profiler in tests and remove a duplicate assertion.
didn't investigate further, but it seems like it wouldn't run on macos to begin with. skipped the test entirely
didn't investigate, i think it's just noise in …

ref(ci): Fix up a bunch of flaky tests

---

codecov.yml

this is incredibly annoying with rust

fix(ci): Do not annotate diff with missing coverage

---

rust_snuba/src/metrics/statsd.rs

We are currently seeing only a handful of metrics being emitted and it
might be due to that.

fix: Re-add QueuingMetricSink to cadence setup

---

rust_snuba/benches/processors.rs
rust_snuba/benches/utils.rs
rust_snuba/src/lib.rs

This cycles through all example payloads from the kafka schemas repo that I copy-pasted.
Plus also adds benchmarks for the newly added processors, though `outcomes` is the only one that works.
Each benchmark now also defines a "processor fn only" benchmark which only processes the payloads without the whole `StreamProcessor`.
---
As a followup, maybe it is a good idea to add all the examples as static data into the kafka schemas rust crate?

Add more Rust benchmarks

---

snuba/cli/migrations.py

In SaaS, querylog is down, and we cannot deploy without it being up.

hack(oncall): Remove all connection checks for migrations

---

rust_snuba/Cargo.lock

we're still trying to figure out why some consumers are missing a decent amount of metrics. now trying to apply https://github.com/getsentry/statsdproxy/pull/41

ref(rust): Update statsdproxy

---

gocd/templates/bash/migrate.sh

Temporarily remove the dangerous migrations check to unblock a deployment issue

temporarily remove migrations dangerous checks

---

rust_snuba/src/types.rs

This was an accidental change done in https://github.com/getsentry/snuba/pull/5289 between review rounds. We were counting our batch sizes in bytes, not messages.

fix(rust): Fix unbatched inserts

---

snuba/cli/rust_consumer.py

Hybrid consumer is experimental, use rust processor as default

ref: Flip rust consumer default

---

snuba/consumers/consumer_config.py
tests/consumers/test_consumer_config.py

This fixes the case where --bootstrap-server, --commit-log-bootstrap-server, or --replacement-bootstrap-server is passed via CLI, for both the rust and python consumers.
These options are generally passed only when we are migrating clusters, etc and we need to run 2 sets of consumers on different clusters side by side.

fix: Properly resolves bootstrap server overrides passed via CLI

---

rust_snuba/rust_arroyo/src/processing/dlq.rs
rust_snuba/rust_arroyo/src/processing/mod.rs
rust_snuba/src/consumer.rs

Especially in benchmarks, creating a fresh runtime for every run leads to thousands of threads being spawned which makes local profiling difficult.

Reuse Tokio Handle in DlqPolicy

---

rust_snuba/rust_arroyo/src/backends/kafka/mod.rs

That function is interning the topic name, and thus aquiring a Mutex. If we keep a list of subscribed topics locally, we avoid that and can also guard against errors.

Avoid calling `Topic::new` for every received Message

---

config/hooks/post-merge

It printed "[!!!{}]" instead of "[!!!]"

fix: Fix wrong colors in post-merge hook

---

rust_snuba/src/processors/replays.rs

Tags are provided as (string, Option<string>).  This change reflects that.

fix(replays): Update rust consumer to accept null tag values

---

snuba/migrations/group_loader.py
snuba/snuba_migrations/spans/0009_spans_add_measure_hashmap.py

Performance plans to begin querying measurements in the `measurements` nested column. This add hashmap column to `measurements`, similar to the one we have for `tags`. Unlike for tags however, this only hashes the keys

Spans: Add hashmap col of spans measurements keys

---

snuba/clusters/cluster.py

This readonly setting does not need to be changed on the client side. Remove this line so we can use system queries with the internal user profile that can change max threads

fix(querylog): don't change the readonly setting with QUERY settings

---

rust_snuba/rust_arroyo/src/processing/strategies/produce.rs
rust_snuba/rust_arroyo/src/processing/strategies/run_task_in_threads.rs
rust_snuba/src/strategies/clickhouse.rs
rust_snuba/src/strategies/commit_log.rs
rust_snuba/src/strategies/processor.rs

This causes a lot of double-erroring, and at least within
RunTaskInThreads we can carry forward errors normally. We still have to
remove panics in the main thread, but this should already cut down a few
duplicate errors we are seeing today.

fix: Remove any panics in threads

---

rust_snuba/benches/processors.rs
rust_snuba/src/config.rs
rust_snuba/src/consumer.rs
rust_snuba/src/factory.rs
rust_snuba/src/lib.rs
rust_snuba/src/processors/functions.rs
rust_snuba/src/processors/metrics_summaries.rs
rust_snuba/src/processors/mod.rs
rust_snuba/src/processors/outcomes.rs
rust_snuba/src/processors/profiles.rs
rust_snuba/src/processors/querylog.rs
rust_snuba/src/processors/replays.rs
rust_snuba/src/processors/spans.rs
rust_snuba/src/processors/utils.rs
rust_snuba/src/strategies/processor.rs
snuba/consumers/consumer_config.py

Validates that the retention days matches one of the valid retention days provided via settings. This is very important otherwise invalid values can create too many clickhouse parts. This function is used in most of our message processors as is also needed for metrics, errors, etc.

fix(rust): Port retention days logic from Python
