snuba/admin/iam_policy/iam_policy.json
Gives perms to SnS to run blocking migrations so that SnS can run blocking migrations from the snuba-admin site.
=> fix(migrations): give team-sns permissions to run migrations

rust_snuba/src/processors/functions.rs, rust_snuba/src/processors/profiles.rs, rust_snuba/src/processors/spans.rs
We're now setting a `received` field for a span message: https://github.com/getsentry/relay/blob/master/relay-server/src/actors/store.rs#L1168
=> feat(spans): Set origin_timestamp for spans

rust_snuba/src/strategies/python.rs, snuba/consumers/rust_processor.py
If the message processing function fails in the hybrid consumer, we raise an invalid message exception and DLQ the bad message if one is configured.
=> feat(hybrid): Support invalid message from python in rust consumer

.github/workflows/image.yml
A while ago we added ARM64 images in #3094  because there was some issue with
running the x86 docker container on macos. We can't reproduce that issue
anymore with either colima or orbstack. colton tested colima, i tested
orbstack.
meanwhile, our ARM64 build is ridiculously slow especially since we added Rust,
and for some reason we don't understand also keeps invalidating caches,
guaranteeing a 80 minute build time on almost every commit.
Because of the slow build time, the multiarch image also takes 80 minutes to build, and so every breakage we push to snuba master only manifests in broken sentry CI after 80 minutes. That's a problem for reverting the breaking commits in Snuba efficiently as well, because the revert also takes 80 minutes.
=> ref(docker): Remove ARM64 images [INC-604]

.github/workflows/ci.yml, .github/workflows/image.yml, Dockerfile
We always build the admin UI and Rust nowadays.
=> ref(docker): Remove obsolete build args

requirements.txt, snuba/query/mql/parser.py, tests/query/parser/test_mql_query.py
In [snuba-sdk 2.0.18](https://github.com/getsentry/snuba-sdk/releases/tag/2.0.18), support for arbitrary functions were added in the MQL grammar. This change needs to be reflected in the MQL to LogicalQuery visitor class as well. This PR is responsible for adding visitors to handle arbitrary functions and creates the appropriate expressions for them in the AST.
=> feat(MQL): Bump snuba-sdk to 2.0.18 and support arbitrary functions in MQL parser

.github/workflows/ci.yml
The current set doesn't cover anything in relation to metrics/spans, and
it resulted in a few bad PR merges related to INC-604
Add this file since it failed in almost all of those PRs and doesn't
take long to run.
=> fix(ci): Add ddm_meta test to "full tests"

Makefile, rust_snuba/Cargo.toml
Hide a line that make was printing, and also fix a warning emitted by
cargo (features are still defined in dependencies apparently)
=> fix(rust): Remove noise from output of make install-rs-dev

rust_snuba/src/processors/replays.rs
**Changes:**
- Extracts the user_id field from user.id rather that user.user_id.
- Validates at least one event link was specified.
- Prunes transaction key from tags.
=> fix(replays): Validate at least one event link was sent in rust processor

Makefile
Seems like `cmake` is a prereq for Rust dev
=> fix(Makefile): Change ordering for Rust dev setup

Makefile, config/hooks/post-merge
I was a bit annoyed that post-merge in snuba printed multiple commands
on separate lines, so I copied what sentry did. Now instead of this:
...
make install-python-dependencies
...
make install-rs-dev
We print this:
make install-py-dev install-rs-dev
This is useful to me personally because it's easier to copypaste one
line of terminal scrollback vs many.
install-py-dev is an alias for install-python-dependencies that is also
named consistently with sentry.
Also added apply-migrations, which again, is the same name we use in
sentry.
A new feature is to automatically run those commands on merge, something
that sentry apparently has. I don't know if anybody uses that, i just
copied it over.
=> fix(devenv): Make post-merge hook exactly like sentry's

rust_snuba/Cargo.lock, rust_snuba/Cargo.toml, rust_snuba/rust_arroyo/Cargo.toml
Use upstream master until they cut a new release containing https://github.com/fede1024/rust-rdkafka/pull/636.
=> deps(rust): Change rdkafka dep to upstream master

rust_snuba/rust_arroyo/examples/transform_and_produce.rs, rust_snuba/rust_arroyo/src/processing/mod.rs, rust_snuba/rust_arroyo/src/processing/strategies/commit_offsets.rs, rust_snuba/rust_arroyo/src/processing/strategies/healthcheck.rs, rust_snuba/rust_arroyo/src/processing/strategies/mod.rs, rust_snuba/rust_arroyo/src/processing/strategies/produce.rs, rust_snuba/rust_arroyo/src/processing/strategies/reduce.rs, rust_snuba/rust_arroyo/src/processing/strategies/run_task.rs, rust_snuba/rust_arroyo/src/processing/strategies/run_task_in_threads.rs, rust_snuba/rust_arroyo/src/testutils.rs, rust_snuba/src/consumer.rs, rust_snuba/src/strategies/clickhouse.rs, rust_snuba/src/strategies/commit_log.rs, rust_snuba/src/strategies/noop.rs, rust_snuba/src/strategies/python.rs
This removes the panics in `RunTaskInThreads` that happened in cases of `JoinErrors` or "other" `RunTaskError`s. To this end, the error type of `poll` (and, by necessity, `join`) is changed from `InvalidMessage` to a new enum `PollError` covering exactly these three cases:
```rust
pub enum PollError {
InvalidMessage(InvalidMessage),
JoinError(JoinError),
Other(Box<dyn std::error::Error>),
}
```
The logging of the latter two error cases is moved from `join` to `StreamProcessor::_run_once`.
Questions:
* ~`PollError` is IMO the natural name for the new error enum, but we already have a type of that name. This doesn't necessarily cause problems, but might be confusing. Should I change the name?~ Renamed to `StrategyError`.
* Are we logging the errors in the right place …
=> ref(rust): Don't panic in RunTaskInThreads::poll

rust_snuba/src/consumer.rs, snuba/cli/rust_consumer.py
process::exit does not permit destructors/Drop to run. specifically, sentry's `_sentry_guard` does not run Drop, and so we fail to flush errors to sentry
=> fix(rust): Actually drop before exiting

snuba/datasets/configuration/spans/entities/spans.yaml, snuba/datasets/pluggable_entity.py
All other entities have this enabled, enable it for spans as well. Make it the default so we don't regress
=> feat(spans): Reject queries with an invalid data model before they reach clickhouse

snuba/query/allocation_policies/__init__.py, tests/query/allocation_policies/test_allocation_policy_base.py
fixes: https://getsentry.atlassian.net/browse/SNS-2589
Basically we have some custom serialization for the complex configurations in the allocation policy. However it breaks when the actual configuration has a `.`, `:`, or `,` in it and it becomes unserializable. 
The better thing to do would be to change serialization to JSON however that would require a migration of the old keys to the new format which is not an urgent matter.
=> fix(capman): escape delimiter characters in allocation policy

snuba/datasets/configuration/replays/entities/replays.yaml
A recent change to schema validation caused this missing field to raise errors on Sentry.  By adding the field to the entity we can remove that error.
=> fix: Add _error_ids_hashed column to the replays entity definition

.github/workflows/image.yml
We are seeing some weirdness on snuba:latest on MacOS where either
pulling or starting fails, presumably because snuba:latest used to be a
multiarch image and no longer is. snuba:amd64-latest works
also add --platform tag on the off chance that fixes anything, since it
appears to be present in Relay's dockerfile
=> fix(docker): Tag snuba:amd64-latest again

snuba/query/processors/logical/object_id_rate_limiter.py, snuba/query/processors/logical/quota_processor.py
Add a switch to disable the legacy ratelimiters. If we flip it on and nothing blows up we can remove all of this code
=> feat(capman): add config to disable legacy ratelimiters

Makefile, rust_snuba/src/lib.rs, rust_snuba/src/runtime_config.rs, rust_snuba/src/strategies/python.rs, rust_snuba/src/testutils.rs, scripts/rust-envvars
bug to repro:
1. clone the snuba repo
2. run `direnv allow` to create virtualenv and pre-commit hooks
3. verify pre-commit works by running `pre-commit run --files  snuba/cogs/accountant.py`
4. `rm -rf .venv` (to deal with a python upgrade, for example)
5. run `direnv allow` again to recreate
6. `pre-commit` is broken, the command from step 3 breaks with errors like `Executable check-case-conflict not found`
~The PYTHONPATH was supposed to fix _something_, but I can't recall now what it is. `cargo test` works fine. If it resurfaces we could re-introduce it as `SNUBA_PYTHONPATH` and set it similarly to how we set `SNUBA_PYTHONEXECUTABLE`, if we don't have any better ideas.~ it happened again on my machine, so I've renamed everything to be prefixed with `SNUBA_TEST_`
=> ref: Upgrade pre-commit, fix PYTHONPATH hacks

.pre-commit-config.yaml, Dockerfile, Makefile, rust_snuba/rust-toolchain.toml
Snuba contributors who just want a working consumer and are less
interested in their Rust "devenv" are confronted with random compile
errors because their toolchain is outdated by a few months.
This commit forces the same rust toolchain version for everybody. If
somebody runs `cargo build`, rustup will automatically download and
install the right rust version if it does not already exist.
We don't actually want to pin the exact version -- defining an
oldest-supported version is what we actually need, we don't care if the
default toolchain is newer. However, there's no way to declare that,
defining MSRV in Cargo.toml doesn't provide the same experience of
automatically downloading the right version.
=> fix: Force a specific rust toolchain

.github/workflows/ci.yml, docker-compose.gcb.yml
We are getting spurious rate limits from dockerhub, so let's use our
image mirrors everywhere
=> fix(ci): Use image mirrors

snuba/cli/spans_cardinality_analyzer.py, snuba/clusters/cluster.py
The cardinality analyzer seems to be failing. There is no Sentry error. Also nothing in the logs. Trying few things to debug the problem
=> fix(cardinality): Allow longer running queries

rust_snuba/src/config.rs, rust_snuba/src/factory.rs, snuba/consumers/consumer_config.py, snuba/datasets/processors/generic_metrics_processor.py, snuba/settings/__init__.py, tests/datasets/test_generic_metrics_processor.py
It should be a boolean (either on or off), and should be part of settings not runtime config (which requires manual configuration via UI on each tenant)
Both the Rust and Python consumers record based on the value from settings.
Depends on https://github.com/getsentry/ops/pull/9061
=> ref: Record cogs is a setting not runtime config

snuba/cli/spans_cardinality_analyzer.py, snuba/clickhouse/span_cardinality_analyzer.py
With the newly added logs we see that the job is not able to get the distinct modules. When I run the query with 2 hour window on snuba-admin the query works. Lets increase the time window to 2 hours.
=> fix(cardinality): Increase time duration for finding all modules

rust_snuba/src/processors/replays.rs
This was lost in the port to Rust
=> ref(replays): Re-add e2e latency metric [SNS-2606]

rust_snuba/Cargo.lock, rust_snuba/src/factory.rs, rust_snuba/src/strategies/clickhouse.rs
- bump arroyo
- enable empty batch flushing
- skip empty clickhouse inserts
=> fix(rust): Deal with empty batches correctly

snuba/query/allocation_policies/cross_org.py, tests/query/allocation_policies/test_cross_org_policy.py
The config validation was a little non-standard and not adequately tested. Add some tests and unbreak the config validation logic to allow changing non-referrer related configs
=> fix(capman): fix config validation for cross org policy

rust_snuba/src/processors/metrics_summaries.rs
Handle having missing fields or null values in metrics summaries.
This reflects what's in the schema better: https://github.com/getsentry/sentry-kafka-schemas/blob/main/schemas/snuba-spans.v1.schema.json#L202-L223.
=> feat(metrics-summaries): Handle incomplete metrics summaries

snuba/datasets/pluggable_entity.py, snuba/query/validation/validators.py, tests/datasets/validation/test_illegal_aggregate_conditions_validation.py, tests/test_spans_api.py
Aggregation functions (e.g. `sum(duration)`) are being found in the WHERE clause of incoming queries to snuba. These should be put in the HAVING clause instead.  Example [sentry issue](https://sentry.sentry.io/issues/4875058423/?project=300688&query=start%3D2024-01-18T11%3A52%3A00%26end%3D2024-01-18T18%3A27%3A17%26groupStatsPeriod%3Dauto&referrer=alerts-related-issues-issue-stream).
This PR is responsible for adding a new built-in entity validator that checks if aggregation functions are being used in the conditions of a query. If an aggregation function expression is found, reject the query.
Use runtime config `enable_illegal_aggregate_in_condition_validator` to enable validator.
=> feat(on-call): Add illegal aggregate function in conditions entity validator

snuba/settings/__init__.py
When we introduced the parallel optimize job cutoff time, we made its value same as the overall optimize job cutoff time. As of April 2023, the optimize job would finish by 3am since the size of individual partitions was no more than 110GB. Today, the size of each partition is close to 180GB. With the bigger partitions, it takes longer for the optimize job to finish. Cap the amount of time the optimize job can run in parallel so that parallel optimizations are not running during peak hours.
Also, removed the jitter because I don't believe they are adding any value. Removing it would allow the parallel phase to run a bit longer during the starting phase of the job.
=> fix(optimize): Reduce parallel optimize job cutoff time

tests/test_metrics_api.py
The tests assume that data insertion runs once, but it actually runs once per test method in the test class. This works around it but we should probably understand how to better use fixtures for a cleaner solution
=> workaround for multiple-insertion issue in metrics API tests

snuba/cli/devserver.py
```
13:04:15 transaction-consumer                          | thread '<unnamed>' panicked at src/strategies/processor.rs:48:17:
13:04:15 transaction-consumer                          | Schema error: Topic not found
13:04:15 transaction-consumer                          | stack backtrace:
13:04:15 errors-consumer                               | 2024-01-23 13:04:15,551 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 0}
13:04:15 errors-consumer                               | 2024-01-23 13:04:15,551 Initialized processing strategy: <arroyo.processing.strategies.guard.StrategyGuard object at 0x10a1ac100>
13:04:15 transaction-consumer                          |    0: rust_begin_unwind
13:04:15 transaction-consumer                          |              at …
```
=> fix(devserver): Do not enforce schema

snuba/datasets/configuration/functions/entities/functions.yaml, snuba/datasets/configuration/generic_metrics/entities/distributions.yaml, snuba/datasets/configuration/generic_metrics/entities/org_distributions.yaml, snuba/datasets/configuration/metrics/entities/metrics_distributions.yaml, snuba/datasets/configuration/metrics/entities/org_distributions.yaml, snuba/query/processors/logical/curried_function_bucket_transformer.py, tests/test_metrics_mql_api.py, tests/test_sessions_api.py
In Clickhouse 22.8 and higher, if the query on a aggregate function -Merge doesn't have the same parameters as what was stored in the -State, the query will fail. Add a query processor that catches instances of this so that Sentry queries don't fail.
Also add an xfailing test for tuple conditions that is fixed in 23.8.
=> fix: Upgrading to Clickhouse 22.8

requirements-test.txt, tests/clickhouse/optimize/test_optimize.py, tests/clickhouse/optimize/test_optimize_scheduler.py
Lets move off freezegun since Sentry also moved away from it. With time machine maybe some of the flakiness might go away. Will keep an eye on the test flakiness. If it reappears we can disable it again.
=> ref(optimize): Use time-machine instead of freezegun

cloudbuild.yaml
We were building the testing image instead of the application image in
GCB, which means that an additional 5 minutes were spent on installing
test dependencies.
=> fix(gcb): Remove build steps from GCB

snuba/query/indexer/resolver.py, tests/query/indexer/test_resolver.py, tests/query/parser/test_mql_query.py, tests/test_metrics_mql_api.py
The resolver was always resolving everything it possibly could for both generic
and regular metrics. However generic metrics don't resolve tag values. This
generally wasn't a problem, unless a string was both a tag key and a tag value
(e.g. transaction).
The other issue is that metric_id resolving was being done as a part of tag
value resolution. Break that out into a separate check, and then only do tag
value resolving for metrics.
Also unskip all the resolver tests, which meant bring them up to date with how
the resolver currently works.
=> fix(mql) Only resolve tag values with the metrics dataset

rust_snuba/Cargo.lock, rust_snuba/Cargo.toml, rust_snuba/benches/processors.rs, rust_snuba/src/config.rs, rust_snuba/src/consumer.rs, rust_snuba/src/metrics/statsd.rs, snuba/consumers/consumer_config.py, snuba/settings/__init__.py
We use statsdproxy to pre-aggregate metrics within the application
(counters, gauges). Therefore we should be able to dogfood DDM with
relatively low instrumentation overhead.
Still, add a sampling rate for now.
https://github.com/getsentry/statsdproxy/pull/47
=> ref: Send metrics to DDM from Rust consumers

snuba/state/rate_limit.py
@untitaker pointed out that it's possible to call zincr or zrem on a set that has expired and create a non-expiring set. Add an expire call to `rate_limit_finish_request` to see if that improves memory usage
=> experiment(capman): try explicitly expiring the query bucket in rate_limit_finish_request

snuba/state/rate_limit.py, tests/query/processors/test_org_rate_limiter.py, tests/state/test_rate_limit.py
There was a plan to move the rate limit config keys to a new namespace, so they
could be semantically separated from other config keys. The start of that work
was to start dual writing config keys to the new namespace. However that
project got abandoned, and now the capacity management tool is handling this
anyways. Remove all the dual reads/writes.
=> fix(rate-limit): Remove dual read/write

.github/workflows/ci.yml, tests/admin/test_api.py, tests/clickhouse/optimize/test_optimize.py, tests/migrations/test_validator.py
Problems so far:
1. `tests/admin/test_api.py::test_query_trace`
Seems like the `formatted_trace_output` maybe have changed for this specific query - so we maybe have to update the tracing tool. Or maybe the test just needs to be updated
`{'5b9af86924cb': {'aggregation_performance': ['Aggregator: Merging partially aggregated single-level data.', 'Aggregator: Converted aggregated data to blocks. 1 rows, 8.00 B in 3.167e-06 sec. (315756.236 rows/sec., 2.41 MiB/sec.)'], 'memory_performance': ['MemoryTracker: Peak memory usage (for query): 225.13 KiB.'], 'node_name': '5b9af86924cb', 'node_type': 'query', 'number_of_storage_nodes_accessed': 0, 'read_performance': [], 'storage_nodes_accessed': [], 'thread_ids': ['399', '390'], 'threads_used': 2}}`
1. `tests/clickhouse/optimize/test_optimize.py` …
=> Try Clickhouse 23.3 and 23.8

.github/dependabot.yml, requirements.txt
Those updates are required for us to get to 3.11. There's speculation that the perf issue has been fixed in a recent version, so let's try and go to latest.
I need this for #5476
=> ref: Upgrade parsimonious

rust_snuba/Cargo.lock
I'm doing this to get https://github.com/getsentry/arroyo/pull/329 into snuba, so that we can fix dashboards
=> ref: Upgrade rust-arroyo to 2.16.0

snuba/migrations/group_loader.py, snuba/snuba_migrations/metrics_summaries/0001_metrics_summaries_create_table.py, snuba/snuba_migrations/metrics_summaries/0003_metrics_summaries_add_segment_id_duration_group_columns.py
As we've learned more about what we wanted out of the product, we need to adapt a bit what we store in `metrics_summaries`.
This PR will add useful IDs to be able to query spans more efficiently.
This was the proposal: https://www.notion.so/sentry/Metrics-Correlations-Data-Model-Proposal-32b0979b48094247bdb5c3e866d5730c .
=> feat(metrics-summaries): Add segment-related columns to ease up querying

snuba/environment.py, snuba/utils/metrics/backends/abstract.py, snuba/utils/metrics/backends/datadog.py, snuba/utils/metrics/backends/dualwrite.py, snuba/utils/metrics/backends/dummy.py, snuba/utils/metrics/backends/sentry.py, snuba/utils/metrics/backends/testing.py, snuba/utils/metrics/util.py, snuba/utils/metrics/wrapper.py, tests/backends/metrics.py
This PR wraps the Datadog and Sentry metrics into a single backend, so we can
start dogfooding Sentry metrics. Currently the Sentry portion is feature
flagged and has a sampling rate.
Sentry also provides a way to specify the unit and record distributions, so add
that to the abstract so we can start using it later.
Recreated from  #5474, with bug fixes.
=> ref(ddm): Dual write to Sentry metrics as well as Datadog

docs/source/language/mql.rst
The link is currently broken and cannot be followed. 
This change just fixes the link to the repository.
=> fix: Add the working link to the repository

snuba/admin/README.md, snuba/admin/static/data.tsx
This PR is fix for the following bug [https://getsentry.atlassian.net/browse/SNS-2621](SNS-2621)
When users have ProductTools role, System Queries was not showing up in the nav bar when it should be. After investigating I found the cause of this bug to be as follows:
* In the backend, tool_policies.py, AdminTools Enum, the tab for system queries is defined as `SYSTEM_QUERIES = "system-queries"` which is supposed to match its id on the front-end
* In the frontend however, data.tsx, NAV_ITEMS, this tab was defined as having ```id: "clickhouse"```
* This was causing the problem when the Nav element was rendering. In order to solve the issue I changed the id on the frontend to match "system-queries"
* I tested it worked properly by limiting myself to only having the ProductTools role, and …
=> fix(admin): fix admin nav ui bug (SNS-2621)

snuba/settings/__init__.py
a few lines down we try to access `importlib.abc`, and it crashes in _some_ environments, probably subject to race conditions.
=> fix(py311): Explicitly import importlib.abc

rust_snuba/src/strategies/processor.rs
We currently attach the payload as a single string.
By adding it as a structured value, datascrubbing and trimming works
better, and we don't just get to see the first N bytes of the payload
(or nothing at all because the string contains PII)
=> ref(rust): Add better error messages

rust_snuba/Cargo.lock, rust_snuba/Cargo.toml, rust_snuba/src/processors/errors.rs, rust_snuba/src/processors/functions.rs, rust_snuba/src/processors/metrics_summaries.rs, rust_snuba/src/processors/mod.rs, rust_snuba/src/processors/profiles.rs, rust_snuba/src/processors/querylog.rs, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__run_schema_type_test.snap, rust_snuba/src/processors/spans.rs
We are seeing a lot of serde errors in our dummy deployment, mostly related to nullability. I can fix them all one by one, but I don't want to write a test for each possible nullable field.
We have an existing jsonschema that, for the fields it actually types at all, is correct about nullability. Unfortunately there are two problems with our schema validation:
1. there are large gaps in the schema, some fields do not exist
2. the schema is sufficiently complex to trigger a ton of different bugs in json-schema-diff
to work around both issues, I:
1. only fix some issues, and check in the rest of the diff as "known accepted drift" via insta
2. only validate an inner definition for InsertEvent, not the entire message payload, to work around a bug resulting from our grotesque use of untagged …
=> ref(errors): Fix some nullability issues in the processor [SNS-2619]

gocd/templates/bash/deploy.sh
Context can be inferred by the `k8s-deploy.py` script via the environment variables retrieved from the `region config`. The main reason for this change now is that it is blocking de deploys.
=> Removing explicit context flag from k8s-deploys

snuba/query/processors/logical/calculated_average_processor.py, tests/query/processors/logical/test_calculated_average_processor.py
The query processor that converts avg -> sum / count for gauges was not
updated to handle the case when the avg was in a formula. In that case, the
function is avgIf instead of avg and has extra condition parameters.
=> fix(metrics): Update gauges to handle avgIf functions

snuba/admin/clickhouse/predefined_querylog_queries.py
Add a predefined query to get the list of projects which are scanning the most bytes for a particular referrer
=> feat(querylog): Add query to get project scanning most bytes

tests/clickhouse/optimize/test_optimize.py
We removed the `xfail` in https://github.com/getsentry/snuba/pull/5447 but it's still flaky sometimes, not sure exactly why but when it fails it blocks CI so...
=> fix: xfail optimize test again :(

gocd/pipelines/snuba-stable.yaml
after https://github.com/getsentry/snuba/pull/5510 the `de` GoCD pipeline was still erroring, this removes a few more explicit `--context` flags from the stable pipeline
=> fix(gocd): remove explicit context flag from snuba-stable

snuba/datasets/configuration/spans/storages/spans.yaml
Without this processor, it'll return the full UUID with dashes.
=> fix(spans): Profile id need UUIDColumnProcessor in indexed spans

snuba/cli/rust_consumer.py
This was temporary for fast iteration on the rust consumer. It should not be used anymore.
=> ref(rust): Remove concurrency override

snuba/datasets/configuration/discover/storages/discover.yaml, snuba/datasets/configuration/functions/storages/functions.yaml, snuba/datasets/configuration/functions/storages/functions_raw.yaml, snuba/datasets/configuration/generic_metrics/storages/counters.yaml, snuba/datasets/configuration/generic_metrics/storages/counters_bucket.yaml, snuba/datasets/configuration/generic_metrics/storages/distributions.yaml, snuba/datasets/configuration/generic_metrics/storages/distributions_bucket.yaml, snuba/datasets/configuration/generic_metrics/storages/gauges.yaml, snuba/datasets/configuration/generic_metrics/storages/gauges_bucket.yaml, snuba/datasets/configuration/generic_metrics/storages/org_counters.yaml, snuba/datasets/configuration/generic_metrics/storages/sets.yaml, snuba/datasets/configuration/generic_metrics/storages/sets_bucket.yaml, snuba/datasets/configuration/group_attributes/storages/group_attributes.yaml, snuba/datasets/configuration/groupedmessage/storages/grouped_messages.yaml, snuba/datasets/configuration/issues/storages/search_issues.yaml, snuba/datasets/configuration/metrics/storages/counters.yaml, snuba/datasets/configuration/metrics/storages/distributions.yaml, snuba/datasets/configuration/metrics/storages/org_counters.yaml, snuba/datasets/configuration/metrics/storages/raw.yaml, snuba/datasets/configuration/metrics/storages/sets.yaml, snuba/datasets/configuration/outcomes/storages/hourly.yaml, snuba/datasets/configuration/outcomes_raw/storages/raw.yaml, snuba/datasets/configuration/profiles/storages/profiles.yaml, snuba/datasets/configuration/replays/storages/replays.yaml, snuba/datasets/configuration/sessions/storages/hourly.yaml, snuba/datasets/configuration/sessions/storages/org.yaml, snuba/datasets/configuration/sessions/storages/raw.yaml, snuba/datasets/configuration/spans/storages/metrics_summaries.yaml, snuba/datasets/configuration/spans/storages/spans.yaml, snuba/datasets/configuration/transactions/storages/transactions.yaml
This has been running in prod with errors for over a week now. Add it to all other storages. Don't make them active by default, turn them on one by one to make sure redis load is not unreasonable
=> feat(capman): add referrer guard rail policy to every storage

snuba/utils/gcs.py
Adding some more functionality to the original PR https://github.com/getsentry/snuba/pull/5410. This includes `list_blobs` and `blob_exists`. 
These methods will be helpful when we are trying to compare blobs that exist in one directory to another, since that is how we will know what work is left to do for the jobs that are running the comparison work for clickhouse upgrades
=> ref(gcs): add list_blobs and blob_exists

rust_snuba/src/processors/metrics_summaries.rs
We're trying to parse for a `u64` even when the field is empty, so it errors.
=> fix(metrics_summaries): Do not parse fields when empty

requirements.txt, snuba/utils/streams/topics.py
Topic configuration for sentry is now centralized in sentry-kafka-schemas in an effort to ensure it is aligned across all projects and deployments.
This remove the duplication from snuba.
=> feat: Use topic configuration from sentry_kafka_schemas

snuba/settings/validation.py
This is harmful since it can cause every pod to crash if some topic configuration is missing, which can worse than an actual missing topic here.
The ops repo now populates all topics automatically from topicctl data anyway, so this no longer needs to be manually updated.
=> feat: Remove unnecessary topic validation

rust_snuba/src/metrics/global_tags.rs, snuba/cli/consumer.py
This ensures consumer_group and storage tags are on all consumers
=> ref: Set all global tags existing in metrics also in Sentry

rust_snuba/src/strategies/processor.rs
I don't think we actually care about the stacktrace, so capturing once
via tracing seems ok
=> ref(rust): Do not double-report

rust_snuba/src/strategies/accountant.rs, rust_snuba/src/strategies/commit_log.rs, rust_snuba/src/strategies/processor.rs, rust_snuba/src/strategies/python.rs, rust_snuba/src/strategies/replacements.rs, rust_snuba/src/types.rs
This was missed entirely in our port of commitlog, and as such causes
errors subscriptions in s4s to get stuck
=> ref(rust): Implement received_p99

snuba/migrations/group_loader.py, snuba/snuba_migrations/spans/0011_spans_add_index_on_trace_id.py
With the trace view screen coming up, we need a fast way to fetch spans for a given `trace_id`. Right now, we're having to do a full table scan. This will speed up the query.
=> feat(spans): Add index on trace_id

rust_snuba/Cargo.lock, rust_snuba/Cargo.toml, rust_snuba/src/processors/errors.rs
The payloads in the errors processor are so large that they're
impossible to debug, so add another crate that keeps track of where a
deserialization error occurs.
We might want to do this for other processors, but the performance
implications of this are unclear, so I'd want to avoid it for payloads
which are already small and easily debuggable.
=> ref(rust): Make errors better for errors processor

snuba/admin/README.md
During Rachel's onboarding to snuba admin she had an issue where snuba admin page wasn't starting properly. The problem was solved by running `make build-admin` before `snuba admin`. I have updated the readme to ensure `make build-admin` gets ran first in the future so others dont run into the same issue.
=> ref: snuba admin readme update

.github/dependabot.yml
Dependabot was configured to open PRs for general library updates. Most of those PRs have gone stale or are not managed. The extra noise desensitizes us to the Dependabot PRs. 
This PR changes the configuration to instruct Dependabot to only open a PR to update a dependency if it solves a known security issue.
=> ci: configure dependabot for security updates only

snuba/querylog/__init__.py
What `cluster_name` is today: `snuba-gen-metrics-xxxx` where xxxx is the metric type
What we want as the resource id: `generic_metrics_clickhouse_xxxx`
=> fix(COGS): Fix cluster name in COGS accounting for Snuba API

rust_snuba/src/processors/generic_metrics.rs
Adds some serde logic to support new schema format for the `values` field.
Before
```json
{
"values": [1, 2, 3]
}
```
Now
```json
{
"values": {
"format": "array",
"data": [1, 2, 3]
}
}
```
Both are supported
=> feat(gen-metrics): Support encoding in gen metrics processor

snuba/datasets/configuration/issues/entities/search_issues.yaml, tests/test_search_issues_api.py
This allows the message column on search issues to be queried, and stops using `issue_title`. We won't merge this until we've dual written data for a week or two.
Relies on https://github.com/getsentry/snuba/pull/4385, https://github.com/getsentry/snuba/pull/4387 Related to https://github.com/getsentry/sentry/issues/50345
=> feat(search-issues): Make `message` column available for querying

snuba/cli/query_replayer.py
If we try to run the query that get the results from the querylog (for the queries we just re-ran) too soon, we won't get the right number of results back, since those queries will still be running.
=> ref(query-replayer): add --wait-seconds

tests/cli/test_health.py, tests/utils/test_check_clickhouse.py, tests/web/test_views.py
refactored `snuba health` tests as a follow up to https://github.com/getsentry/snuba/pull/5579
=> ref: refactored tests for snuba health

snuba/query/mql/parser.py, tests/test_metrics_mql_api.py
There was a bug where a Formula that had a scalar value, and had filters, would
fail because the scalar values weren't being handled correctly.
=> fix(mql): Fix bug with Formulas on scalar values

rust_snuba/src/strategies/clickhouse.rs
Log the bytes size of batches written to Clickhouse. This is useful for debugging.
=> rust: log batch byte size

snuba/querylog/query_metadata.py
This PR is responsible for adding the error code and request status to properly tag requests that hits ClickHouse too many simultaneous queries error. This will give us a better idea of how much these errors are impacting our API and our SLOs.
=> on-call(slo): Properly label too many simultaneous queries error

snuba/admin/auth_roles.py, snuba/admin/iam_policy/iam_policy.json, snuba/admin/tool_policies.py, tests/admin/test_authorization.py
Product owners should be able to view which migrations have been executed in production to get a better sense of what their datasets/tables look like in prod. This can help product developers validate whether or not their tables have been created in a new environment without having to traverse GoCD.
=> on-call(admin): Allow viewing migrations for product tools role

snuba/admin/static/capacity_management/allocation_policy.tsx, snuba/admin/static/capacity_management/index.tsx, snuba/admin/static/capacity_management/row_data.tsx, snuba/admin/static/table.tsx, snuba/admin/static/tests/capacity_management/allocation_policies.spec.tsx, snuba/admin/static/tests/capacity_management/table_color.spec.tsx
https://github.com/getsentry/snuba/assets/3169433/333cce70-cc93-4b9e-9cc0-7767481bfd25
In order to make it more clear the state of the policy (active, enforced, inactive, change the color of the table to make it more obvious to the user what is happening
=> feat(capman): Change allocation policy table color based on active/enforced

snuba/cli/devserver.py, snuba/utils/streams/topics.py
In order to align behavior across different environments, billing related messages will be produced to the billing topic in dev, which matches how it is done in prod today. This runs the billing consumer in devserver so we ingest them properly.
=> feat: Run a separate billing consumer in devserver

.github/workflows/bump-version.yml
I always forget to bump the rust versions of our libraries since it's not covered by this action
=> feat: bump-version action also bumps rust

snuba/admin/static/capacity_management/allocation_policy.tsx, snuba/admin/static/capacity_management/row_data.tsx, snuba/admin/static/capacity_management/types.tsx, snuba/admin/static/tests/capacity_management/allocation_policies.spec.tsx, snuba/admin/static/tests/capacity_management/index.spec.tsx
As as user it's a little hard to identify which option is applied globally and which is applied to a specific tenant.
This change splits the 2 types of configurations into separate tables.
The UI element distinguishes whether or not a configuration is global or not by checking if the `params` field is empty, based on the assumption that a configuration is applied globally iff it does not have params.
Also adds some handy functions in tests to verify table contents.
Before
After
=> feat(capman): Split global and tenant specific configs into two tables

.vscode/launch.json
This PR re-adds launch.json and should enable pytest current file for vscode users
=> feat: update launch json for pytest current file in vscode

snuba/querylog/__init__.py
Uses the entity instead of the dataset for generic metrics -- this is a more reliable source for getting the `app_feature` from a query than dataset since it comes directly from the request body. 
I did notice that the entity in a `SnubaQueryMetadata` object is known only if the query is a `LogicalQuery`. Under which circumstances would it not be a `LogicalQuery`? If I understand correctly, the other kinds of queries would be nested/subqueries, and queries involving joins. I don't know how common these two cases are for generic metrics, but we can also fall back to dataset in these cases.
=> fix(COGS): Fix app_feature for generic metrics Clickhouse compute accounting

gocd/templates/bash/s4s-replay-queries.sh, gocd/templates/clickhouse-query-replayer.jsonnet
follow up to #5597 
This adds a manual step that can be called to run the query replayer tool. Arguments to this step can be passed in via the `REPLAYER_ARGS`  environment variable in GoCD.
=> gocd: add s4s query replayer

snuba/cli/query_comparer.py, snuba/clickhouse/upgrades/comparisons.py, tests/clickhouse/upgrades/test_comparisons.py
Updating the comparer to use the file_manager and grab the files to compare from GCS. Corresponding ops PR https://github.com/getsentry/ops/pull/9471
What the comparer does:
1. Looks at the `results-` directories to see if we have pairs of results that are ready to be compared and puts them together as a `matched_pairs`. e.g.
```python
[('results-21-8/2024_02_15/meredith_test_1.csv', 'results-22-8/2024_02_15/meredith_test_1.csv')]
```
2. Iterates through those pairs to actually compare the results from those files. Before it does so though, it checks that we haven't already done the comparison (we ignore that if `--override` is used). We can check in the `compared-data/` and `compared-perf/` directories
3. We compare the results and generate mismatches for the `data` and `perf` categories …
=> ref(ch-upgrades): update query_comparer

gocd/templates/clickhouse-query-replayer.jsonnet
move env vars to top level of the pipeline so that they can be configurable from gocd.
=> query-replayer: move gocd env vars to top level for changes

snuba/query/mql/parser.py, tests/test_metrics_mql_api.py
It is possible for a component of a Formula to be a Formula, and for that
Formula to be made up entirely of scalars (depending on the bracket grouping).
That case was causing an exception to be thrown in parsing.
=> fix(mql): Fix a bug with scalars in Formulas

snuba/query/mql/parser.py, tests/query/parser/test_formula_mql_query.py
When there's a leading literal in the mql formula, we are unable to extract the MRI from it and error. This should be handled and continue trying the next term in the formula for the MRI.
Fixes SNUBA-4H3
=> fix(mql): Handle leading literal in mql formula

snuba/datasets/configuration/events/storages/errors_ro.yaml, snuba/query/allocation_policies/__init__.py, snuba/query/allocation_policies/concurrent_rate_limit.py, snuba/query/allocation_policies/cross_org.py, snuba/query/allocation_policies/per_referrer.py, snuba/web/__init__.py, snuba/web/db_query.py, snuba/web/views.py, tests/query/allocation_policies/test_allocation_policy_base.py, tests/query/allocation_policies/test_bytes_scanned_window_allocation_policy.py, tests/query/allocation_policies/test_concurrent_rate_limit_policy.py, tests/query/allocation_policies/test_cross_org_policy.py, tests/query/allocation_policies/test_per_referrer.py, tests/test_snql_api.py, tests/web/test_db_query.py
Context for the task is in [this ticket](https://getsentry.atlassian.net/browse/SNS-2646)
Basically the way we have been aggregating the allocation policy violations and surfacing it to the caller has been bothering me so I did a little cleanup. No longer do we have two similarly named exceptions `AllocationPolicyViolation, AllocationPolicyViolations`. We also now report the same data structure for allocation policy decisions for failed and non-failed queries. 
Bonus: we now have the storage_key in every quota allowance explanation. sometimes it's not immediately obvious which storage the query was rejected for
=> ref(capman): Simplify allocation policy error reporting

snuba/query/snql/parser.py, tests/test_snql_api.py
If a query had a tag column with an entity alias, e.g. `events.tags[status]`,
the parser would choke and would throw an exception.
=> fix(snql) Correctly parse tag columns with an entity alias

gocd/templates/bash/s4s-clickhouse-queries.sh, gocd/templates/clickhouse-query-comparer.jsonnet
Tried to make one script that could be used by all three pipelines:
* `fetcher` - https://github.com/getsentry/snuba/pull/5625
* `replayer` - https://github.com/getsentry/snuba/pull/5609
* `comparer`  - This PR includes that pipeline
Also adds `--try-deployments-and-statefulsets` from https://github.com/getsentry/devinfra-deployment-service/pull/534
=> ref(gocd): add comparer pipeline, consolidate script?

snuba/query/processors/physical/type_converters.py, tests/query/processors/test_hexint_column_processor.py, tests/test_snql_api.py
The HexIntColumnProcessor was only working on IN conditions that had a tuple as
the argument. Modify it to also accept arrays.
=> fix: Fix a bug in HexIntColumnProcessor that skipped array conditions

gocd/templates/bash/canary-ddog-health-check.sh, gocd/templates/pipelines/snuba.libsonnet
Now that we deploy snuba API canary in GoCD, we can validate that snuba is able to connect to all the appropriate ClickHouse clusters before deploying to SaaS. As we continue to make snuba more self-serve, this safeguard can help product developers stop bad deploys (incorrect storage names, wrong table names, etc.) from going out to production. Additionally, this check would stop developers from prematurely enabling a storage (via readiness_state), before the necessary migrations are executed and tables are created.
This is currently set to `dry_run=true` and should not stop deploys even if check fails. We should be able to see this new check in GoCD UI.
=> feat(gocd): Add snuba API canary health check

rust_snuba/src/processors/generic_metrics.rs
These metrics will allow us to check which "branch" of the processor we're in, and validate the new encoded format is indeed being deserialized in the processor.
=> feat(generic-metrics): Add metrics around encoding format type in processor

rust_snuba/src/processors/querylog.rs, rust_snuba/src/processors/utils.rs, snuba/settings/__init__.py, snuba/web/db_query.py, snuba/web/query.py
[Setting a default `trace_id` upstream](https://github.com/getsentry/snuba/pull/5628) proves to be insufficient to solve the [UUID parsing error](https://sentry.sentry.io/issues/4927370476/?project=300688&query=start%3D2024-02-07T15%3A27%3A00%26end%3D2024-02-07T22%3A23%3A38%26groupStatsPeriod%3Dauto&referrer=alerts-related-issues-issue-stream). It is also not sustainable to find all the places where `trace_id` is set to empty or null since it does not protect against future cases. This pr addresses this issue by adding deserialization logic that populates the query's `trace_id` with `Uuid::nil()` if the payload's `trace_id` is an empty string or null.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is …
=> Allows empty `trace_id`

gocd/templates/bash/canary-ddog-health-check.sh
This health-check ensures that snuba is able to connect to all clickhouse clusters before continuing down the deployment pipeline. Since it is operating as expected, we can turn this on for real now.
=> feat(canary): Enable canary health check

gocd/templates/bash/s4s-clickhouse-queries.sh
This is to fix the `OSError: [Errno 36] File name too long: '/usr/src/snuba/snuba/cli/query_fetcher... ` error Im seeing in GoCD, this change seemed to work locally for me to call the snuba command correctly, hopefully this works in GoCD too
=> fix(gocd): put snuba cmd into $SNUBA_CMD

.vscode/settings.json
removes unittest from vscode settings, since we only use pytest, this allows vscode testing ui to work
=> fix: vscode testing ui

snuba/cli/subscriptions_executor.py
In order to be able to correlate metrics from both scheduler and executor, lets add a tag of entity on the executor. The scheduler already has this tag.
=> chore(oncall): Add entity key to subscription scheduler

snuba/admin/iam_policy/iam_policy.json
We should remove `team-starfish` from the snuba admin iam policy since it no longer exists: https://github.com/getsentry/security-as-code/pull/645. This is causing [auth errors in admin](https://sentry.sentry.io/issues/4739270573/?project=300688&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=2.).
=> chore(admin): Remove starfish group from iam policy

snuba/migrations/group_loader.py, snuba/snuba_migrations/spans/0012_spans_add_index_on_transaction_name.py
We're making queries on the spans dataset involving a whole lot of spans from a specific transaction name. This should help speed up the query.
https://github.com/getsentry/sentry/blob/master/src/sentry/api/endpoints/organization_spans_aggregation.py#L328-L340
=> feat(spans): Add an index on segment_name

snuba/cli/query_fetcher.py
We need to restart the `start_time` for each table we iterate through otherwise it only works for one table
=> fix: handle multiple tables correctly

snuba/migrations/group_loader.py, snuba/snuba_migrations/generic_metrics/0030_add_record_meta_column.py, snuba/snuba_migrations/generic_metrics/0031_counters_meta_table.py, snuba/snuba_migrations/generic_metrics/0032_counters_meta_table_mv.py
The original PR (https://github.com/getsentry/snuba/pull/5669) was merged with a bug (column wasn't added to the dist table. I reverted that PR before it could be deployed broken, and created this replacement.
This creates everything needed to test  storing meta information about
metrics. The new table is meant to satisfy queries that are trying to find
metric_ids, tag keys and tag values, but are not interested in the values
associated with the metrics.
In theory this will eventually be done for all the metric types, but for now
this is being used just for counters to test how well this solution actually
solves the problems.
This does three things:
- Add a column to the raw table that can be used to control which data
goes to the meta table
- Create a new table for aggregated meta …
=> feat(metrics): Add a meta table to counters

rust_snuba/src/processors/generic_metrics.rs, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-generic-metrics-GenericCountersMetricsProcessor-snuba-generic-metrics__1__snuba-generic-metrics1.json.snap
This field will be used by the materialized view to determine whether the row
should be processed into the meta table.
Depends on https://github.com/getsentry/snuba/pull/5681
=> feat(meta): Add record_meta field to counters consumer

snuba/admin/clickhouse/predefined_cardinality_analyzer_queries.py, snuba/admin/static/table.tsx
For the DDM launch, we want a way to analyze the size of the incoming data. Add
two queries to the predefined queries that can give that information (and
provide a useful starting point for more in depth analysis).
Also change the font of table results to be monospace, so it's easier to
compare numbers directly.
=> ref(ddm): Add debug queries to cardinality analyzer

snuba/cli/query_fetcher.py, snuba/clickhouse/upgrades/comparisons.py
we increased the `query_log_ttl` for S4S querylog in https://github.com/getsentry/ops/pull/9562 so I'm increasing the limit for the fetcher to be one week
I also changed the logging a bit cause it will be kind of too much if you are doing multiple tables each for a week - plus I don't think we needed that much logging anyway (can always add back in later)
=> ref(ch-upgrades): increase window_hours

snuba/query/processors/physical/mapping_optimizer.py, tests/query/processors/test_mapping_optimizer.py
This was a TODO item. But on the spans dataset, one easy to encounter situation is a condition like
```
sentry_tags[key] IN (value1, value2)
```
This results in a sql like
```
in((arrayElement(sentry_tags.value, indexOf(sentry_tags.key, 'key')) AS `_snuba_sentry_tags[key]`), ['value1', 'value1'])
```
which scans the entire `sentry_tags.key` and `sentry_tags.value` columns. The optimization here is to use the tags hash map which gives us a condition like
```
hasAny(_sentry_tags_hash_map, array(cityHash64('key=value1'), cityHash64('key=value1')))
```
=> feat(mapping-optimizer): Support in operator for mapping optimizer

rust_snuba/Cargo.lock, rust_snuba/Cargo.toml, rust_snuba/src/strategies/clickhouse/batch.rs, rust_snuba/src/strategies/clickhouse/mod.rs
We want to eventually stop buffering writes to clickhouse, and instead hold one long-running connection for the lifetime of a batch, streaming rows slowly in. This is already how Python works.
This initial refactor creates a new Batch type that holds onto the clickhouse client internally.
=> ref: Initial refactor to facilitate streaming writes to clickhouse

rust_snuba/src/consumer.rs
fix https://github.com/getsentry/snuba/issues/5664
=> fix: don't log secrets

rust_snuba/Cargo.lock, rust_snuba/Cargo.toml, rust_snuba/src/factory.rs, rust_snuba/src/strategies/accountant.rs, rust_snuba/src/strategies/clickhouse/batch.rs, rust_snuba/src/strategies/clickhouse/mod.rs, rust_snuba/src/strategies/commit_log.rs, rust_snuba/src/strategies/processor.rs, rust_snuba/src/strategies/python.rs, rust_snuba/src/strategies/replacements.rs, rust_snuba/src/testutils.rs, rust_snuba/src/types.rs
Refactor the rust consumer so that from within Reduce, the HTTP request is
opened and rows are directly written into the socket.
This requires splitting up the BytesInsertBatch type as it can be in multiple
"states" depending on the stage of the pipeline. It contains a HttpBatch before
writing to clickhouse, and contains none before committing offsets.
The easiest way that I found is to first make it generic over its internal row
data R, then slowly fixing up all the instances where the generic was missing.
In a future PR I would like to see:
* deleting `InsertBatch` entirely, and replacing all instances with `BytesInsertBatch`
* renaming `BytesInsertBatch` to `InsertBatch`
* splitting up `types.rs` into multiple files
=> ref: Move to streaming writes in Rust consumer

.github/workflows/ci.yml, snuba/query/conditions.py, snuba/query/dsl.py, snuba/query/mql/parser.py, snuba/query/processors/logical/filter_in_select_optimizer.py, tests/query/parser/test_formula_mql_query.py, tests/query/processors/test_filter_in_select_optimizer.py, tests/test_metrics_sdk_api.py
https://getsentry.atlassian.net/browse/SNS-2669
This PR should get all of riccardos broken tests passing. 
What motivated the rewrite?
* I needed to implement new functionality to get riccardos tests passing
* It was gunna be a lot of work to do
* After talking to enoch we thought of an alternative approach, this turned out to a better solution that would be faster to implement
* pretty much full optimizer rewrite
* optimizer feature flag on by default
* fixed breaking integration tests
1. use a visitor to get all the conditional aggregates (ex. sumMergeIf) in the ast
2. `or` all the conditions in these functions, and add this to the where clause.
ex:
```
SELECT sumIf(val, metric_id in [1,2,3] and status=200),
avgIf(val, metric_id=7), 
maxIf(val, metric_id=5 and status=400)
WHERE org_id=1 …
```
=> feat: optimizer rewrite

gocd/templates/jsonnetfile.json, gocd/templates/jsonnetfile.lock.json
This change moves `de` from a test region that is run separate from the rest of our deploys, to a production region that is run, in this case, after `s4s` and before `us`. Now that `de` officially has customers, it is a good time to move it.
=> chore(gocd): Move de region to be between s4s and us

CODEOWNERS
This adds product teams as codeowners to their respective datasets, allowing them to make modifications to their dataset without PR approval from snuba
=> feat: add product teams to codeowners

snuba/admin/clickhouse/predefined_cardinality_analyzer_queries.py
This will be handy during the DDM rollout.
=> Add use case filter to BucketsPerOrgOverTime predefined query

snuba/migrations/group_loader.py, snuba/snuba_migrations/generic_metrics/0033_counters_meta_tag_values_table.py, snuba/snuba_migrations/generic_metrics/0034_counters_meta_tag_values_table_mv.py
In the original meta table, having tag values in a groupUniqArray had very poor
query performance, driven by the slowness in aggregating those data sketches.
Create a new table that can just be used for finding tag values, that stores
the tag values as rows in the table.
This table also deliberately does not have org_id or use_case_id in it. In
theory any query for tag values has a project ID, metric ID and tag key in it.
This means the org ID and use case ID don't provide anything useful.
=> feat(metrics): Create a table for finding meta tag values

gocd/templates/snuba.jsonnet
This is a no-op change that removes a temporary argument used while transitioning to a different approach for rollbacks a few months back.
=> chore(gocd): Removing old config arg

snuba/migrations/group_loader.py, snuba/snuba_migrations/generic_metrics/0035_recreate_counters_meta_tag_value_table_mv.py
The original migration used the wrong name for the new view, which caused it to
not be created. Add a new migration with the correct view name.
Since migrations use `IF NOT EXISTS` the previous migration adding the
view was basically a no-op. Nothing was broken, but the view was silently
not created.
=> fix(metrics): Fix tag value meta materialized view

snuba/web/query.py
When testing the new pipeline, there exist difference between the SQL queries outputted from the old and new pipeline. This the `Request` object is passed into the old pipeline, then is passed into the new pipeline. This is incorrect since the old pipeline mutates this object (specifically the query). This PR is responsible for creating a deep copy of the request object and passing it into the new pipeline so that both inputs to the pipelines are the same.
=> bug(dev-exp): Create copy request object for new pipeline

snuba/query/dsl.py, snuba/query/mql/parser.py, tests/query/parser/test_mql_query.py
The following error was happening during MQL parsing:
https://sentry.sentry.io/issues/5082818756/events/489d5cf1818c4909a985bb0c27ad409c/?project=300688
it was being caused by queries that look like `((avg(d:transactions/millisecond) * 100.0) * 50.0){filter}`
When pushdown_filter is called, it recursively will get called on the `100.0`, which causes `AttributeError: 'float' object has no attribute 'formula'`
In order to fix this, we skip pushdown_filter on anything that isnt an InitialParseResult, this is already done in the code but only for the very top layer of recursion. My fix moves this logic into the recursive case in order to ensure this error wont happen at any layer of recursion.
My fix also adds a test case for the query that previously errored.
related links: …
=> fix: parser, bug in pushdown filter 

snuba/cli/query_fetcher.py
Make it easier to use the query fetcher by making the `--tables` arg optional. If it's not provided then we fetch queries for all the table names on the node. This should be fine for tables we don't use anymore because if there are no queries in the querylog, we don't upload anything to gcs
=> ref(fetcher): --tables optional now

snuba/settings/__init__.py
The actual max query size that can be sent to ClickHouse is `131535 bytes`. This is approximately `128.45KiB`. However, snuba has set `MAX_QUERY_SIZE_BYTES` to `256KiB`, As a result, the large queries are incorrectly passing the snuba check and reaching ClickHouse resulting in `ClickHouseError: max query size exceeded`. This PR is responsible for lowering that limit such that snuba catches these errors and returns the proper expection.
More info here: https://www.notion.so/sentry/ClickHouse-max-query-size-exceeded-error-a5851e643b3f435d9dcb1551dbcbbc09
=> chore: Lower max query size check to 128KiB

snuba/cli/consumer.py, snuba/cli/rust_consumer.py
"error" is a dangerous value as it causes consumer to crash if partitions are scaled. This happened in INC-702. Let's always use "earliest" as the default.
=> fix: Fix default auto-offset-reset value

snuba/migrations/group_loader.py, snuba/snuba_migrations/generic_metrics/0036_counters_meta_tables_final.py
These are the final versions of the meta tables that should be used going
forwards. Since the counters table already has the `record_meta` column added,
these tables can be created directly.
This creates two tables populated by materialized views. The first contains
just tag keys, to be used to look up metric IDs for a project, and tag keys for
a given metric ID.
The second table contains tag values, to be used for looking up tag values for
a given metric ID and tag key. This table drops org_id and use_case_id since
those are superfluous given a project_id + metric_id filter.
These tables were tested and researched as part of this epic: https://github.com/getsentry/snuba/issues/5695
=> feat(meta): Add updated versions of meta tables for counters

snuba/cli/query_fetcher.py, snuba/cli/query_replayer.py, snuba/clickhouse/upgrades/comparisons.py
Each time we run the series of these pipelines (fetcher, replayer, comparer) we first have to bring up nodes from backups and have our test clusters to work with. Doing the backup will restore the local tables, along with the data, but usually the dist tables are not backed up (if we change our backup process maybe we can change this) but as of now SRE folks would have to manually create the dist tables.
This aims to save the schemas of the dist tables during the fetching process, and when replaying for the first time we should be downloading the schema and using it to create the tables.
I tested this locally with my own gcs bucket
=> ref(ch-upgrades): create dist tables functionality

snuba/datasets/configuration/spans/storages/spans.yaml
- The spans table is ordered by span ids but not trace_id which means that when both are included in a where clause we're producing a slower query since trace_id will go in the prewhere instead of span_id
=> fix(spans): Move span id above trace id in the prewhere

snuba/admin/cardinality_analyzer/cardinality_analyzer.py, snuba/admin/clickhouse/common.py, tests/admin/clickhouse/test_query_validation.py
Also fix the validation to deal with ARRAY JOIN a little better. It was hard to
test the meta materialized view queries because the validation would choke on
ARRAY JOIN clauses.
=> ref(card-an): Allow the new meta tables in the cardinality analyzer

snuba/datasets/configuration/events/storages/errors.yaml, snuba/datasets/configuration/events/storages/errors_ro.yaml, tests/admin/test_api.py, tests/web/test_db_query.py
This PR is responsible for adding the CrossOrgQueryAllocationPolicy to errors in order to give us better control over referrers that run across all orgs (e.g.: [backfill seer grouping records script](https://github.com/getsentry/sentry/pull/68466)).
=> chore(on-call): Add CrossOrgQueryAllocationPolicy to errors

snuba/cli/rust_consumer.py
Previous default was for testing, consumer should not skip writes by default. This matches the default value on the python consumer.
=> ref: Rust consumer should not skip writes by default (inc-715)

snuba/migrations/group_loader.py, snuba/snuba_migrations/discover/0008_discover_add_replay_id.py
we want to be able to query this field in discover. it exists on both errors and transactions.
=> feat(replays): add replay_id column to merged discover table

.vscode/settings.json
what is currently in the settings file `"python.linting.mypyArgs": ["--strict"]` is depricated and doesnt actually do anything. I updated this to the proper way.
=> fix: fix mypy --strict vscode 

snuba/migrations/group_loader.py, snuba/snuba_migrations/generic_metrics/0041_adjust_partitioning_meta_tables.py
There was an issue with the existing tables that caused them to have a very
high number of inactive parts. This change makes three adjustments to help with
that.
- Remove `retention_days` from the `PARTITION BY`. This will reduce the number
of partitions that the table has, and thus the number of inactive parts
- Change the materialized view to use `toMonday` instead of `toStartOfWeek` so
that the partition lines up with the data in the table. This should help
prevent writing new data into older partitions (which was happening  because
`toStartOfWeek` and `toMonday` don't line up.
- Since partitions are no longer broken up by retention days,
add the `ttl_only_drop_parts` setting so that we drop rows within the
partitions based on retention.
Since it's not possible to modify the `PARTITION …
=> feat(meta): Adjust partitioning/settings of counters meta tables

rust_snuba/src/processors/spans.rs, tests/datasets/test_spans_payloads.py
`domain` is a nullable column (https://github.com/getsentry/snuba/blob/master/snuba/snuba_migrations/spans/0001_spans_v1.py#L38) and we'd want to search for empty domain via `!has:span.domain`, `span.domain:""`, which all get turned into `isNull(domain) == 1`, which fails to find the proper spans since we set an empty string by default.
This PR aims to let the `null` value be `null` and not default to an empty string.
=> fix(spans): Let null domain be null

snuba/migrations/group_loader.py, snuba/snuba_migrations/discover/0008_discover_fix_add_local_table.py, snuba/snuba_migrations/discover/0008_discover_fix_new_dist_table.py
Our migrations in SaaS don't have the discover local table. This causes a mismatch between discover migrations in SaaS and self-hosted/CI. The mismatch prevents us from running any new discover migrations. 
To fix this , this migration adds a `discover_local` table if it doesn't exist to reconcile SaaS with the self-hosted migrations. In SaaS the local table will not be used because we merge the distributed tables directly, but this will allow us to unblock discover migrations.
=> feat(migrations): add discover local

snuba/clusters/cluster.py
Follow up from #4988 , users noticed that this setting did not actually propagate to the cluster which makes sense because we did not use it
https://github.com/getsentry/snuba/pull/4988/files/29d6765a9bb94fe6cf4ff40575aca2774e710c2c#r1569493727
Update cluster instantiation to make sure we respect the setting
=> fix(self-hosted): respect the max_connections passed through settings

.github/workflows/ci.yml, snuba/datasets/configuration/discover/entities/discover.yaml, snuba/datasets/configuration/discover/entities/discover_transactions.yaml, snuba/datasets/configuration/transactions/entities/transactions.yaml, snuba/query/processors/logical/condition_simplifier_processor.py, tests/query/processors/test_arrayjoin_optimizer.py, tests/test_discover_api.py, tests/test_snql_api.py
There is some bug in Clickhouse 22.8 that can cause errors like "Too large size
(13837309855095848992) passed to allocator. It indicates an error."
The issue was narrowed down to conditions on low cardinality string columns,
and specific types of data in those columns. This processor hacks those
conditions to be in a form that allows the query to run.
=> fix(22.8) Add processor to handle 'allocator' bug in Clickhouse

snuba/query/dsl.py, tests/pipeline/test_entity_processing_stage.py, tests/pipeline/test_execution_stage.py, tests/pipeline/test_storage_processing_stage.py
Added a general case test for `EntityProcessingStage`, `StorageProcessingStage`, and `ExecutionStage`.
I decided not to test `EntityAndStoragePipelineStage` since it will be phased out soon.
=> chore: create tests for each API pipeline stage

snuba/datasets/configuration/discover/entities/discover.yaml, snuba/datasets/configuration/discover/entities/discover_transactions.yaml, snuba/datasets/configuration/transactions/entities/transactions.yaml, snuba/query/processors/logical/low_cardinality_processor.py, tests/datasets/test_nullable_field_casting.py, tests/query/processors/test_arrayjoin_optimizer.py, tests/test_snql_api.py
In 22.8, if a LowCardinality(String) is queried, and it actually is not low
cardinality, it can cause an error in Clickhouse. To be safe, cast all
LowCardinality columns to regular String to avoid causing this issue.
So far this is only impacting Discover + transactions, so limit the change
there. This might decrease query performance for other queries, since
all LowCardinality strings will be treated as String.
=> fix(22.8) Cast LowCardinality string columns to String

snuba/query/processors/logical/low_cardinality_processor.py, tests/test_snql_api.py
`ifNull` function here doesn't do us any good because sentry actually expects `null` back, cast to a `Nullable(string)` instead
=> fix(22.8) don't use ifnull for cardinality casting

.github/workflows/ci.yml, cloudbuild.yaml
as part of OPS-3966 we're migrating off of deprecated gcr
this is step 1: dual write
step 2: cut over deploy pipelines
step 3: remove dual writing
=> ref: dual-write docker image to artifact registry

tests/consumers/test_message_processors.py
These tests are just comparing Rust and Rust processor now. Since we deleted the generic metrics Python processor implementations. So we can remove these tests.
=> chore(generic-metrics): Remove unnecessary message processor test

requirements.txt, rust_snuba/Cargo.lock, rust_snuba/Cargo.toml
Bumping this to have support for new commit log and subscriptions scheduled topics
=> chore: Bump Kafka schema version to 0.1.71

rust_snuba/src/processors/generic_metrics.rs
Adding better observability so we can better monitor the effects of switching over to this encoding.
=> feat(generic-metrics): Add success metric around Base64 message processing

snuba/datasets/configuration/spans/entities/metrics_summaries.yaml, snuba/datasets/plans/storage_processing.py, snuba/pipeline/stages/query_processing.py, snuba/query/dsl.py, tests/pipeline/test_storage_processing_stage.py
In order to make storage queries work with nested columns, we need to build in default processing of queries that have expressions like:
`tags[something] = 'blah'`
this PR implements this feature. It also removes the SubscriptableMapper for metric_summaries to show that it's no longer necessary
Also add some syntactic sugar to the DSL to make the tests look nicer
=> feat(devexp): add a default subscriptable mapper to the storage stage

snuba/datasets/configuration/group_attributes/entities/group_attributes.yaml, snuba/datasets/configuration/group_attributes/storages/group_attributes.yaml, snuba/datasets/processors/group_attributes_processor.py
Non-migration changes to add `group.priority` to the group attributes table.
MIgration PR: #5786
=> feat(group-attributes): Add priority to group attributes table

snuba/clusters/storage_sets.py, tests/datasets/test_group_attributes_join.py
The `search_issues` and `group_attributes` datasets no longer share the same query nodes in prod. As a result, ClickHouse is queries are receiving "table does not exist" ClickHouse errors (https://sentry.sentry.io/issues/5219576548/?project=300688&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=0). This PR removes them from `JOINABLE_STORAGE_SETS` and makes sure we fail the query before ClickHouse
=> chore(on-call): Remove search-issues and group-attributes from joinable sets

gocd/templates/bash/check-github.sh
this bug was meant to be fixed by #5834 but wasnt actually, this PR should actually fix it now.
=> fix(cd): deploy fails from ci timeout

.github/workflows/ci.yml
It's been in CI for a week and looks stable. I've checked on every failure in the past week and it is not due to flakiness, it's from image build failure so it looks like we should be good to go to get this required.
=> chore(self-hosted): Mark e2e test check as required

snuba/datasets/configuration/discover/storages/discover.yaml
This column actually causes an error in some queries when it is added to the
prewhere. `DB::Exception: Storage Merge doesn't support PREWHERE for message.`
Remove it for now and it can be revisited in the future if necessary.
=> fix: Remove `message` from the prewhere processor

snuba/migrations/clickhouse.py
We have upgraded all ST and SaaS clusters to `22.8`, and are in the process of updating to `23.3`. Self-hosted still uses `21.8.x` so using the minimum version found in https://github.com/getsentry/self-hosted/blob/9e36d2f57a431a236f86a4fcd38125faf7721232/install/detect-platform.sh#L20-L26
Will have to update the `CLICKHOUSE_SERVER_MAX_VERSION` to `23.8` when we get closer to that, I think we can do that after we've upgrade S4S and made sure that was successful
=> update CLICKHOUSE_SERVER_MIN_VERSION and CLICKHOUSE_SERVER_MAX_VERSION

rust_snuba/src/strategies/clickhouse/batch.rs
We've been seeing some issues with running `snuba devserver` locally and the problem seems to happen when there aren't actually any messages being processed but we still send requests to clickhouse (with `0` as the body).
This change should prevent a request to clickhouse from ever being made if we don't have any rows to write. If the sender doesn't send any messages then the receiver will be empty - which is what we use to check in order to determine when to open the request.
=> snuba devserver fix?

snuba/migrations/group_loader.py, snuba/snuba_migrations/spans/0013_spans_add_indexes_for_tag_columns.py
Searching through the spans dataset is key for the Trace Explorer. We'd like to add indexes to speed search queries on user tags.
We didn't add an index for `sentry_tags.key` since they are mostly the same for all tags (these are specific tags set by Relay for Sentry use).
=> feat(spans): Add indexes for tag columns

snuba/datasets/configuration/generic_metrics/storages/counters_meta_tag_values.yaml, snuba/datasets/configuration/generic_metrics/storages/distributions_meta_tag_values.yaml, snuba/datasets/configuration/generic_metrics/storages/gauges_meta_tag_values.yaml, snuba/datasets/configuration/generic_metrics/storages/sets_meta_tag_values.yaml, snuba/datasets/configuration/json_schema.py, snuba/datasets/configuration/storage_builder.py, snuba/datasets/storage.py, snuba/query/snql/parser.py, tests/datasets/configuration/test_storage_loader.py, tests/query/snql/test_storage_query.py, tests/query/test_query_validation.py
In order to allow storage queries to be validated based on timestamp, we need to know what their timestamp is. Entities already have this so we add this optional field to storages as well.
=> feat(devexp): Add required_time_column to storage

.github/workflows/ci.yml
Don't think this is needed, it just needs to wait on `build-on-snuba-pr` image to finish job
=> chore(self-hosted): Remove dependency on snuba-image build step during e2e action

snuba/query/data_source/join.py, snuba/web/db_query.py, tests/datasets/test_cdc_events.py, tests/datasets/test_group_attributes_join.py, tests/web/test__get_allocation_policy.py
Queries using joins have up to this point not been subject to allocation policies. making them an abuse vector. Now that we have join queries serving in production, put the protection on them
=> fix(capman): make allocation policies work with joins

snuba/cli/dlq_consumer.py
same as https://github.com/getsentry/snuba/pull/5753 and https://github.com/getsentry/snuba/pull/5772 and every other consumer at sentry now
=> fix: dlq-consumer should default to auto-offset-reset earliest

tests/datasets/processors/test_metrics_summaries_processor.py
This testcase uses timestamps that are TTL-ing now. Failure of this test is blocking CI. Make timestamp relative so it never fails in the future.
=> fix(CI): Make timestamp relative for metrics summaries test 

scripts/check-migrations.py
CI is red right now for a particular commit and there is no way to deploy the specific migration in isolation. We need to remove the check to unblock deploys
=> fix: Temporarily remove check for coupled migrations and code changes

snuba/cli/subscriptions_scheduler_executor.py
same as all the other consumer CLIs which have `earliest` as the default, missed this one earlier
=> one more auto-offset-reset earliest

snuba/query/mql/parser.py, tests/query/parser/unit_tests/test_post_process_and_validate_mql_query.py
this is part 3, you will have to click only the last commit for the diff. depends on #5886
* separate mql parse pipeline after treeify into a separate stage
* add tests for this stage
Originally I planned to have mql and snql share their "after treeify stage" but they were too different, so I will be making them separate. A potential improvement to the codebase could be the abstraction of "composite stages" but that is definitely out of scope.
There is no way to verify that the tests "look right" but I verified:
* the expected number of tests were generated
* the expected number of success/fail tests is expected
* they are all passing
So i am fairly confident its good
* snql after treeify
* treeify unit test
* remove e2e
=> ref(api): parse pipeline tests, mql after treeify

rust_snuba/src/factory.rs, rust_snuba/src/strategies/join_timeout.rs, rust_snuba/src/strategies/mod.rs
Ref https://github.com/getsentry/team-sns/issues/4
=> ref(rust-consumer): join-timeout per-step

rust_snuba/src/strategies/clickhouse/mod.rs
the `finish()` function returns whether the write happened, as such the
logs were messed up.
Fix #5847
=> fix(rust): Fix incorrect logging output

snuba/migrations/groups.py
When a migration group is registered in the ops repo and is in the config, it can block deploys because it has not been registered. When this happens just don't run the migration for it and continue on
=> fix(migrations): return limited readiness state for storage set key

snuba/migrations/parse_schema.py, tests/migrations/test_parse_schema.py
This is a fix to the `DateTime64` type added recently. Schema wasn't being parsed correctly when parsing it from a migration.
=> fix(migrations): Parse precision and timezone from DateTime64

rust_snuba/Cargo.lock, rust_snuba/bin/python_processor_infinite.rs, rust_snuba/src/factory.rs, rust_snuba/src/runtime_config.rs, rust_snuba/src/strategies/accountant.rs, rust_snuba/src/strategies/clickhouse/mod.rs, rust_snuba/src/strategies/commit_log.rs, rust_snuba/src/strategies/join_timeout.rs, rust_snuba/src/strategies/noop.rs, rust_snuba/src/strategies/processor.rs, rust_snuba/src/strategies/python.rs, rust_snuba/src/strategies/replacements.rs, rust_snuba/src/testutils.rs
Changes necessary for https://github.com/getsentry/arroyo/pull/366, and
additional timers for get_str_config, since that one acquires multiple
global locks and might impact concurrency.
=> ref: Upgrade arroyo, use coarsetime

snuba/replacers/errors_replacer.py, snuba/replacers/replacements_and_expiry.py
As part of the roll out plan of automatically skipping offending replacements projects, we want to create a DD dashboard to monitor the following metrics:
- number of projects skipped
- latency of adding skipped projects to redis
- latency of deleting expired projects from redis
- latency of getting skipped projects from redis
=> Metrics for replacements DD

snuba/datasets/configuration/events/storages/errors.yaml, snuba/datasets/configuration/events/storages/errors_ro.yaml, snuba/web/db_query.py, tests/web/test_db_query.py
Currently, all the policies of a storage run on every request. This can put undue load on redis when we already know the query is rejected. 
If one policy rejects from now on, just don't run any others
Also reorder the policies on errors so that the rejecting ones run first
=> feat(capman): Short circuit allocation policy

snuba/admin/clickhouse/predefined_system_queries.py
I notice it was missing and I believe is the intention is to set one table name only.
=> fix(snuba-admin): Add quotes around ColumnSizeOnDisk's table value

rust_snuba/src/processors/generic_metrics.rs
Enable processing of metrics for the metric_stats use case in order to store metadata for the usecase in the new generic_metrics_*_meta tables that enable quicker querying
=> feat(metrics): add metric_stats use case to generic metrics meta tables

snuba/utils/bucket_timer.py
Logging the variables used to determine if a replacement project is offending and thus should be skipped. I will revert this commit once we identify the issue
=> Logging for replacements projects

rust_snuba/src/strategies/clickhouse/mod.rs
The consumer pod logs are flooded with these logs. Lets remove them so that triaging becomes easier and reduce the footprint of our costs of logging.
=> fix(clickhouse): Remove unecessary logging

snuba/utils/bucket_timer.py
As part of the debugging efforts on why [auto replacements project skipping](https://github.com/getsentry/snuba/pull/5883) isn't working as intended, we have a new hypothesis that the bucket timer algo we depend on isn't working as we expected. More specifically, we noticed (from logging) that [projects_exceeding_limit](https://github.com/getsentry/snuba/blob/76fd1fff03be960a5da216223ed809860fa0fd6b/snuba/replacer.py#L596) logs, but [projects_exceeding_time_limit](https://github.com/getsentry/snuba/blob/76fd1fff03be960a5da216223ed809860fa0fd6b/snuba/utils/bucket_timer.py#L95) does not. We add additional logging to confirm the control flow of our code
=> Debugging bucket timer

snuba/utils/bucket_timer.py
In the current replacements set up, if a project takes up more time processing replacements than what the threshold allows, it actually won't be skipped if it's the only project that exists. The intention was that it's fine for the single existing project to use up the entire replacements processing budget. Thus, when we are testing within S4S, even if we are going over the testing threshold (which is 0), we are not adding sentry-for-sentry to the list of projects to skip, since it's the only project that exists.
This PR uses another runtime config, `s4s_replacements_testing`, so that if it's true, we allow the single existing project to be skipped as long as it exceeds the threshold (0).
This is for S4S testing only and will be removed
=> allow one replacement project to be skipped

rust_snuba/benches/processors.rs, rust_snuba/src/config.rs, rust_snuba/src/consumer.rs, rust_snuba/src/factory.rs, rust_snuba/src/strategies/clickhouse/batch.rs, snuba/cli/rust_consumer.py
We are going to try out async inserts for specific S4S clusters to test it out and see the impacts of enabling it. This adds a cli arg that we can use to target consumers for specific clusters (e.g. https://github.com/getsentry/ops/pull/10687). I'm also adding a runtime config flag `async_inserts_allowed` so that we can turn it on and off as we test without having to put up code changes. 
When (and if) we move forward to enabling this on more clusters, we won't be able to use the runtime config in the same way since it would turn things on and off across the board, so this is really for testing purposes at this moment
Pre-req for https://github.com/getsentry/ops/pull/10687
=> ref(async-inserts): allow async inserts as an option

snuba/migrations/group_loader.py, snuba/snuba_migrations/replays/0020_add_dist_migration_for_materialization.py
There was a previous PR (https://github.com/getsentry/snuba/pull/5708/files) which added a materialized view to the storage nodes.  However, a distributed migration was never run for the query nodes.  This PR fixes that.
=> feat(replays): Add migration for distributed materialization

snuba/utils/bucket_timer.py
Previously, I added logging as part of rolling out [auto-skipping offending replacements projects](https://github.com/getsentry/snuba/pull/5883). After verifying that things work as expected within S4S, I'm ready to remove logging
=> Remove replacements logging that was previously used for roll out

rust_snuba/src/processors/errors.rs
Adds an option flag `errors_format_full_invalid_payload` to print the full payload on invalid message
=> hack(logs): add option to print full payload on invalid message

rust_snuba/Cargo.lock, rust_snuba/Cargo.toml, rust_snuba/src/processors/errors.rs
Relay can send `lineno` field as a u64, but in clickhouse, we are only storing them as u32. This pr changes the behaviour of the error consumer when it encounters a `lineno` greater than a u32, instead of failing, it uses the default value (`None`).
=> fix(error): Skip lineno deserialization on failure

rust_snuba/src/processors/errors.rs
This reverts commit eb3f8bf268d9a739ea5e2baedc005b3457bba96c.
Going to merge this once I get the full logs from #5979
=> Revert "add option to print full payload on invalid message (#5979)"

.github/workflows/ci.yml
I've recently updated the self-hosted e2e test action to properly pick up changes on pre-submit after noticing breakage snuck into master from https://github.com/getsentry/relay/pull/3633.
It seems reasonable to pin this to main given that our team has alerting for when this CI check fails on master, and we don't update it frequently. Please let me know if there are any concerns here.
#skip-changelog
=> chore(self-hosted): Automatically pick up e2e test action from main

snuba/admin/clickhouse/predefined_system_queries.py
These are some very basic queries that we can use (and modify) for our purposes when testing out async inserts. I would have liked to use the more robust queries that I found in https://clickhouse.com/blog/monitoring-asynchronous-data-inserts-in-clickhouse but it was taking too long to easily add these with the way the system queries is built right now.
So for now we have 
* `PartCreations`: This can let us see how many rows/the size each of our new parts has, with async inserts this should be much higher in theory than we have now since it should be buffering multiple inserts. 
* `AsyncInsertPendingFlushes`: This can give us a quick pulse on how many inserts are pending flushing in total
* `AsyncInsertFlushes`: This is like the query log, but for the async insert flush, and can be used …
=> ref(async-inserts): Add system queries

snuba/datasets/configuration/discover/entities/discover.yaml
Some [discover queries](https://sentry.sentry.io/issues/5281216825/events/4d8e33db9f30420e954bb6443471bc19/) are failing as a result of the allocator bug. This is caused by how ClickHouse version 22.8 deals with low cardinality string columns. This PR is responsible for adding `tags[environment]` to the set of columns to be processed by the LowCardinalityProcessor in discover which casts the low cardinality string into a regular (high cardinality) one.
=> chore(tech-debt): Add missing column low cardinality processor in Discover

snuba/admin/clickhouse/predefined_system_queries.py, snuba/admin/clickhouse/system_queries.py, tests/admin/test_system_queries.py
Some queries fail because we don't do `sql_query = " ".join(sql_query.split())` before we match on the regex, I believe this is due to the fact that we explicitly have `\s` in the regex, vs a newline
=> fix: snuba admin queries check

snuba/migrations/group_loader.py, snuba/snuba_migrations/group_attributes/0003_add_first_release_id_to_group_attributes.py
Add a new column, `group_first_release_id` to the GroupAttributes table. This column will be backfilled as part of the issue search improvements, with data from `Group.first_release_id`. 
This column will help speed up searches for `firstRelease`. We'll still handle `firstRelease` queries using Postgres if the query includes the environment.
=> feat(issue-search): Add group_first_release_id to the GroupAttributes table

snuba/admin/clickhouse/predefined_system_queries.py
Add a system query for seeing the size of indexes on disk.
=> ref(admin): Add a system query for data skipping indexes

gocd/templates/pipelines/snuba.libsonnet
Noticed a bug in the canary stage of the Snuba deployment pipeline. Since the health check was a job in the same stage as the deployment, it would run in parallel meaning the health check is checking the state before (or as) the deploy goes out rather than after. Combining the deploy and health check jobs into one job with multiple tasks enables them to run sequentially meaning the health check will now run after the deploy goes out.
=> fix(gocd): Updating canary checks to happen after the deploy goes out

gocd/templates/bash/deploy.sh
Adds `profiles-chunks` consumer to the GoCD list to be deployed to.
=> chore(profiles-chunks): Add missing consumer to deployment list

snuba/admin/static/production_queries/index.tsx
In the Snuba Admin Production queries UI allocation policies which are throttled were not shown in an ordered list. 
Fix is added to display correctly.
=> Fix for displaying allocation policies throttled correctly on Snuba Admin production queries UI

.github/workflows/ci.yml
We've upgraded our clusters to 23.3 and we use the `23.3.19.33.altinitystable` version https://github.com/getsentry/ops/blob/5d4ce26dd5a0545640bf8a63ef93be4cf10fc05b/salt/pillar/clickhouse/snuba-generic-metrics-distributions.sls#L2
Also we want to use the newer 23.8 version, so I've updated that as well. I have removed 22.8 because we no longer have that running in production
=> ref(ci): update clickhouse versions

snuba/web/db_query.py, tests/web/test_db_query.py
Fixing the metric increment with simple readthrough cache for cache hit, cache miss and cach_hit_simple.
=> Fixing the metric increment with simple readthrough cache for cache hit, cache miss and cach_hit_simple.

snuba/query/allocation_policies/bytes_scanned_rejecting_policy.py, tests/query/allocation_policies/test_bytes_scanned_rejecting_policy.py, tests/web/test_db_query.py
https://getsentry.atlassian.net/browse/SNS-2794
The BytesScannedRejectingPolicy prevents a (project_id|organization_id, referrer) combination from sending too many queries by rejecting them once such combination reaches a rejection threshold. I add a throttle threshold so the offending combination will get throttled first before getting rejected. BytesScannedRejectingPolicy will half the threads when the number of bytes scanned goes over 50% of the rejection threshold for that combination. 
Roll out plan: 
In this PR, I set the throttle dividers to 1 so that the rejection threshold and the throttle threshold are the same, so effectively this PR will create the options on Snuba Admin without doing any throttling. Then, within S4S, I will adjust the throttle dividers. With this, I expect to …
=> [CapMan] add throttling to BytesScannedRejectingPolicy

.github/workflows/ci.yml, docker-compose.gcb.yml
We never upgraded the default test run and so we were still running 21.8. Fix that
=> fix(CI): update CH version used in CI

snuba/querylog/__init__.py, snuba/web/query.py, snuba/web/views.py, tests/test_snql_api.py
Query validation occurs in the [entity processing stage](https://github.com/getsentry/snuba/blob/209d6d5ce9bd0133ff21e8eb880c851c4aa61bed/snuba/pipeline/stages/query_processing.py#L26) of the query pipeline. When it fails, a `InvalidQueryException` gets raised to the top-level pipeline function. Right now, when this [error](https://sentry.sentry.io/issues/5324410007/events/d109b5a0a0dc44aa94e12bec863cfd93/?project=300688&referrer=slack) gets raised, we are not properly recording these invalid request. This PR is responsible for adding the proper error handling for these invalid requests.
=> chore(on-call): Properly handling query validation errors

snuba/cli/migrations.py, snuba/migrations/autogeneration/__init__.py, snuba/migrations/autogeneration/main.py, tests/migrations/test_autogeneration.py
This PR is the interface users will use to generate migrations
```
snuba migrations generate path/to/storage
```
the code in this PR:
* get the storage file at that path
* gets the version of it at HEAD
I will use this to send to the diff functions that take the old and new storage as input and generate the actual migration
=> feat: autogenerate add migration ui

scripts/send_spans.py
Create a script that generates fake traces for a set of projects.
All the traces for a single organization (1123) that spans 3 projects. Conceptually it is meant to
mimic a frontend, backend and service project.
The script can write to a file, output to stdout or produce to a kafka topic. It's all random, so
there are no guarantees of how many transactions/spans will actually appear in a given trace. There
is an option to run the script until a given number of spans are generated. Note this isn't exact,
the script will run until at least that many spans are generated.
=> ref(spans): Create script for generating fake traces

docs/source/contributing/environment.rst
When setting up my Snuba dev environment locally, I noticed that the make command in the docs no longer exists and has no specific replacement that I am aware of.
=> fix(docs): remove make command that no longer exists

snuba/migrations/group_loader.py, snuba/snuba_migrations/group_attributes/0004_fix_group_first_release_id_type.py
The `group_first_release_id` column was added to GroupAttributes as UUID but release IDs are bigints. The processor and YAML changes must be reverted first in https://github.com/getsentry/snuba/pull/6039 so we can safely update the column type here. The column is not yet in use and has no data.
Will get tests passing once the revert is in.
=> fix(group-attributes): Modify the column type for `group_first_release_id` to bigint

snuba/query/allocation_policies/__init__.py, snuba/query/allocation_policies/bytes_scanned_rejecting_policy.py, snuba/query/allocation_policies/bytes_scanned_window_policy.py, snuba/query/allocation_policies/concurrent_rate_limit.py, snuba/query/allocation_policies/cross_org.py, snuba/query/allocation_policies/per_referrer.py, tests/admin/test_api.py, tests/pipeline/test_execution_stage.py, tests/query/allocation_policies/test_allocation_policy_base.py, tests/test_snql_api.py, tests/web/test_db_query.py
https://getsentry.atlassian.net/browse/SNS-2796
Allocation policies are our mechanism for doing traffic management for Snuba queries. Currently, the result of applying allocation policies in the internal API is simply accept/reject/throttle. In this PR, we are updating existing allocation policies to return additional metadata, most importantly to distinguish between queries that are accepted, rejected, or throttled.
Next steps: surface these new metadata fields in the [external API](https://getsentry.atlassian.net/browse/SNS-2797)
When all changes are finished, we should have a payload for Sentry that looks like:
```
"quota_allowance": {
"summary": {
"threads_used": 2, # the actual amount of max_threads sent to clickhouse
"throttled_by": {
"policy": "BytesScannedRejectingPolicy", …
```
=> Add additional information to policies

snuba/web/db_query.py, tests/web/test_db_query.py
https://getsentry.atlassian.net/browse/SNS-2797
Allocation policies are our mechanism for doing traffic management for Snuba queries. Currently, the result of applying allocation policies in the internal API is simply accept/reject/throttle. In a [previous PR](https://github.com/getsentry/snuba/pull/6041), we added internal API to keep track of additional metadata. In this PR, we relay the additional metadata to Sentry by adding them to the HTTP payload. It is then up to product engineers to use this information however they prefer to.
=> Relay query quota information to Sentry

snuba/migrations/group_loader.py
Users no longer need to make changes to the group loader when creating a new migration. They are now only responsible for naming the migration correctly `xxxx_migration_name.py` and putting it in the correct folder `snuba_migrations/dataset/`. The group loader will find the new migrations in these folders by itself.
Ordering the migrations run in is based on migration numbers.
Migration numbers must begin at 0001 and strictly increase by 1 which is validated. The following would cause errors:
* 0000_migration_name.py
* 0001_migration.py, 0002_migration.py, 0004_migration.py
(see commit ac0f0a5 for this code)
I added assert to every single `get_migrations` to verify the new function generated the same as the hard-coded list. I ran `snuba migrations list` with the asserts in place to …
=> feat: no more user-required-changes to migration group loaders

snuba/datasets/configuration/replays/storages/replays.yaml, snuba/datasets/configuration/spans/storages/spans.yaml
We are facing load issues on spans and replays due to excessive bytes scanned. Add the policy that has been successful on errors in mitigating this load and preventing abusive actors. 
Remove the BytesScannedWindow policy because it has not mitigated these load spikes and the BytesScannedRejectingPolicy also throttles now
=> feat(capman): Replace BytesScannedWindow policy with BytesScannedRejectingPolicy for spans, replays

gocd/templates/bash/migrate-st.sh
snuba is currently creating topics (even those that are not in production yet) in single tenant on each gocd deployment. snuba shouldn't be managing topics as topicctl is used to do this in all production environments.
=> gocd: do not create topics on every snuba deployment

snuba/datasets/configuration/events/storages/errors_ro.yaml
we are simply doing point queries, so should be able to do a bit more concurrently without issues.
=> dev(rate-limits): up concurrent rate limit for similarity backfill

snuba/admin/production_queries/prod_queries.py, snuba/query/data_source/projects_finder.py, tests/admin/test_production_queries.py
Currently production queries are broken for joins and subqueries. This is because we weren't looking for project ids in the condition of the composite query. This should fix that
=> fix(admin): fix projects finder not looking in composite query conditions

snuba/snuba_migrations/group_attributes/0004_add_new_first_release_column_to_group_attributes.py
Add a new column with a different name for the `Group.first_release` field to the GroupAttributes table.
=> feat(group-attributes): Add new column for group first release

snuba/datasets/configuration/spans/storages/spans.yaml
There is no index on `transaction_id` nor is it part of the table's ORDER BY. Because of this, promoting conditions on the `transaction_id` to the PREWHERE clause actually slows down the query quite significantly.
=> perf(spans): Remove transaction_id from PREWHERE for spans

snuba/query/allocation_policies/__init__.py, snuba/web/db_query.py, snuba/web/views.py, tests/test_snql_api.py, tests/web/test_db_query.py
https://getsentry.atlassian.net/browse/SNS-2798
Allocation policies are our mechanism for doing traffic management for Snuba queries. On Sentry issues webpage, the [metadata regarding allocation policies](https://github.com/getsentry/snuba/pull/6041) are not surfaced.
In this PR, we relay the metadata to Sentry issues webpage so that they are displayed in that same section.
=> surface CapMan summary in case of AllocationPolicyViolations

snuba/query/data_source/join.py, snuba/query/logical.py, snuba/query/mql/context_population.py, snuba/query/mql/parser.py, snuba/query/mql/parser_supported_join.py, snuba/query/parser/__init__.py, snuba/query/snql/parser.py, tests/query/data_source/test_join.py, tests/query/parser/test_formula_mql_query.py
Most of this code was adapted from: https://github.com/getsentry/snuba/pull/5717. This PR contains the fundamental changes for supporting parsing simple formulas into the appropriate `CompositeQuery` object that contains a `JoinClause`. Note that this CompositeQuery is not executable yet as we still need to add metric subquery generator support. This PR only focuses on the parsing stage, and eventually, we can iteratively add support down the query pipeline. To accomplish this, a new parser file, `parser_supported_join.py`, was created to isolate between the parsing stages. This allows us to iterate on the new MQL parser without affecting the current formula queries. Later, when the parser supports all formulas to JOINs (filters, brackets, groupbys, arbitrary functions, etc.), we can …
=> feat(mql): Support parsing simple formulas into JOIN queries

snuba/query/mql/parser_supported_join.py, tests/query/parser/test_formula_mql_query.py
- Distribute join keys from top level JoinClause to each individual JoinClause.
- Adds tests for bracketed formula queries.
Right now, the query IR that the parser produce for something like
```
max(`d:transactions/duration@millisecond`)
/ sum(`d:transactions/duration@millisecond`) 
+ avg(`d:transactions/duration@millisecond`)
```
Has a join clause of
```python
join_clause = JoinClause(
left_node=JoinClause(
left_node=IndividualNode(
alias="d2",
),
right_node=IndividualNode(
alias="d1",
),
keys=[],
),
right_node=IndividualNode(
alias="d0",
),
keys=[
JoinCondition(
left=JoinConditionExpression(table_alias="d1", column="time"),
right=JoinConditionExpression(table_alias="d0", column="time"),
),
JoinCondition(
left=JoinConditionExpression(table_alias="d2", column="time"), …
```
=> feat(mql): Support filters and bracket rules in parsing

snuba/clusters/storage_sets.py, snuba/settings/__init__.py, snuba/settings/settings_distributed.py, snuba/settings/settings_test_distributed_migrations.py
the purpose of this pr is to create a new storage set.
with the high level goal of enabling the creation of a distributed table on a query node that can access both search_issues and errors.
see https://getsentry.atlassian.net/browse/INF-138
storage set to cluster mapping https://github.com/getsentry/ops/pull/11246
so i will create a new storage set, create a migration on it to create distributed table, and then delete the new storage set
=> chore: new temporary storage set

snuba/datasets/configuration/replays/storages/aggregated.yaml
Without capping the aggregation complexity we run the risk of running out of memory.  This slows the query down significantly.  By applying these optimizations (which are identical to the non-materialized replays dataset) we can significantly improve performance and significantly reduce resource consumption.
=> fix(replays): Add ClickHouse query aggregation settings to materialized view

snuba/query/allocation_policies/bytes_scanned_window_policy.py, snuba/web/db_query.py
In a [previous PR](https://github.com/getsentry/sentry/pull/73442), we emit a Sentry warning and a GCP log for every query throttled by Snuba's capacity management system. However, we quickly realized [a large volume of queries were throttled](https://sentry.sentry.io/issues/5550501231/?project=1&query=&referrer=issue-stream&statsPeriod=24h&stream_index=5).
A potential solution we came up with is to sample the number of throttled queries we emit warnings and logging for, but before this, we realized that every throttled query I manually inspected from GCP logs is throttled by [BytesScannedWindowAllocationPolicy](https://github.com/getsentry/snuba/blob/f8e1456907f046215a3c284b89c91a28d7709191/snuba/query/allocation_policies/bytes_scanned_window_policy.py), a policy we plan on [deprecating …
=> bytes_scanned_window_policy DD metric

snuba/web/db_query.py
The throttle policy should be the policy with the smallest number of threads. The existing logic simply takes the last throttling policy in the `for-loop`
=> sets throttle policy correctly

snuba/query/allocation_policies/__init__.py, snuba/query/allocation_policies/bytes_scanned_window_policy.py, snuba/web/db_query.py, tests/web/test_db_query.py
closes https://getsentry.atlassian.net/browse/SNS-2812
Right now the bytes_scanned metric that is used in our [customer dashboard](https://app.datadoghq.com/dashboard/tjn-nwy-wwf/snuba-customer-dashboard?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1719517147379&to_ts=1719524347379&live=true) and our [API abuse dashboard](https://app.datadoghq.com/dashboard/u66-3d3-a27/snuba-api-abuse) is emitted from the BytesScannedWindowAllocationPolicy ([code](https://github.com/getsentry/snuba/blob/master/snuba/query/allocation_policies/bytes_scanned_window_policy.py#L290-L294))
There is a [plan](https://www.notion.so/sentry/Increasing-visibility-into-the-Capacity-Management-System-c16b375ed2ee43c19cd2fa163fc93332) to deprecate the BytesScannedWindowPolicy and it already does not exist on …
=> fix(capman): emit the bytes scanned metric from db_query

snuba/migrations/autogeneration/main.py
`sentry devservices up`
```
> Failed to check health: <urlopen error [Errno 61] Connection refused>
> 'redis' is healthy
> 'postgres' is healthy
> 'clickhouse' is healthy
> Health check for 'snuba' failed, retrying in 10s (attempt 2 of 12)...
> 'kafka' is healthy
> Health check for 'snuba' failed, retrying in 10s (attempt 3 of 12)...
> Health check for 'snuba' failed, retrying in 10s (attempt 4 of 12)...
> Health check for 'snuba' failed, retrying in 10s (attempt 5 of 12)...
> Health check for 'snuba' failed, retrying in 10s (attempt 6 of 12)...
> Health check for 'snuba' failed, retrying in 10s (attempt 7 of 12)...
> Health check for 'snuba' failed, retrying in 10s (attempt 8 of 12)...
> Health check for 'snuba' failed, retrying in 10s (attempt 9 of 12)...
> Health check for 'snuba' …
```
=> fix: move an import that may be causing issue with sentry devservice

snuba/datasets/configuration/issues/storages/search_issues.yaml, snuba/datasets/configuration/json_schema.py, snuba/datasets/configuration/storage_builder.py, snuba/datasets/deletion_settings.py, snuba/datasets/storage.py
**context:**
Embarking on adding (lightweight) deletes to Snuba. The first storage we want to add this to is search issues, since right now you cannot delete via the Sentry application. 
The first step is to add some definitions on the storage that we will use in the delete pipeline (which will be a new endpoint we add later). 
**changes:**
This PR adds some deletion settings that are needed. they are:
* `is_enabled`: whether deletes are enabled for the storage. If no deletion settings are provided in the yaml file, we default to an empty deletion settings state (where `is_enabled` is `0`)
* `tables`: list of tables that we delete from. in some cases there will be more than one table to delete from - as is the case for storages that have a materialized view and where both the local and …
=> ref(snuba-deletes): add DeletionSettings

snuba/query/mql/parser_supported_join.py, tests/query/parser/test_formula_mql_query.py
Add support for nested function over columns, i.e. ```f(g(`d:transactions/duration@millisecond`))```
=> feat(mql): Arbitrary nested column aggregates

rust_snuba/src/processors/replays.rs, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@ingest-replay-events-ReplaysProcessor-ingest-replay-events__1__archive.json.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@ingest-replay-events-ReplaysProcessor-ingest-replay-events__1__click-serialized.json.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@ingest-replay-events-ReplaysProcessor-ingest-replay-events__1__click.json.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@ingest-replay-events-ReplaysProcessor-ingest-replay-events__1__event-link.json.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@ingest-replay-events-ReplaysProcessor-ingest-replay-events__1__viewed.json.snap, tests/datasets/test_replays_processor.py
Previously it was set to `javascript` as that was the only platform replay was available on.  With the addition of mobile replays this is no longer true.  The query in `sentry` already uses the `anyIf` operator and filters out empty values.
Related: https://github.com/getsentry/sentry/issues/74074
=> feat(replays): Set platform as empty string if platform is not provided

snuba/snuba_migrations/transactions/0023_add_profiler_id_column.py
For continuous profiling, the profile context will contain a new value `profiler_id`, not to be confused with `profile_id`. A `profiler_id` is set on the transaction's profile context when the continuous profiler is enabled. This is a separate value from the existing `profile_id` because we need to be able to distinguish if the transaction is associated with a transaction based profile or a continuous profile and load the profile from the correct place.
=> feat(profiling): Add profiler id column to transactions

requirements.txt, snuba/query/mql/parser.py, snuba/query/mql/parser_supported_join.py, tests/query/parser/test_parser.py
Contributes to https://github.com/getsentry/sentry/issues/69852
=> feat(metrics): add wildcard support to MQL parser

snuba/snuba_migrations/transactions/0023_add_profiler_id_column.py
Re-applying #6099.
For continuous profiling, the profile context will contain a new value `profiler_id`, not to be confused with `profile_id`. A `profiler_id` is set on the transaction's profile context when the continuous profiler is enabled. This is a separate value from the existing `profile_id` because we need to be able to distinguish if the transaction is associated with a transaction based profile or a continuous profile and load the profile from the correct place.
=> feat(profiling): Add profiler id column to transactions (#6099)

snuba/datasets/configuration/spans/entities/spans.yaml, snuba/datasets/configuration/spans/storages/spans.yaml
Initial context in https://github.com/getsentry/snuba/pull/6107 Okie it might be the `LowCardinality` column not actually being low cardinality.
Casting the column seems to make it work 
>
```
SELECT
countIf(
equals((cast(op, 'String') AS _snuba_op), 'browser')
OR equals(_snuba_op, 'resource.link')
) AS _snuba_matching_count
FROM spans_dist...
```
=> fix: LowCardinality column bug w/ aliases

CODEOWNERS
There was a previous PR that made product teams CODEOWNERS for their snuba datasets. But that PR made it so snuba is no longer codeowners. This PR fixes this to make it so both product teams and snuba own the datasets.
=> chore: make snuba co-owners of datasets again

snuba/request/__init__.py
In order to support lightweight deletes in Snuba, we will accept `DELETE` queries. Since they are much simpler than the other types of queries Snuba supports, we figured it'd be easier to have a separate `DeleteRequest` object to work off of.
=> feat(snuba-deletes): DeleteRequest object

rust_snuba/benches/processors.rs, rust_snuba/src/config.rs, rust_snuba/src/consumer.rs, rust_snuba/src/factory.rs, rust_snuba/src/strategies/clickhouse/batch.rs, snuba/cli/rust_consumer.py
I'm trying to track down the source of some production errors when writing to generic-metrics-distributions, where ClickHouse is unable to allocate enough memory to handle the execution of the materialized views. The errors look something like:
```
Strategy(error writing to clickhouse: Code: 241. DB::Exception: Received from xxx:9000. DB::Exception: Memory limit (for query) exceeded: would use 9.81 GiB (attempt to allocate chunk of 1073741824 bytes), maximum: 9.31 GiB.: while executing 'ARRAY JOIN granularities :: 10 -> arrayJoin(granularities) UInt8 : 9': while pushing to view default.generic_metric_distributions_aggregation_mv_v3 (63e6c929-c73f-473e-83d5-9f58c48e904a). (MEMORY_LIMIT_EXCEEDED) (version 23.8.11.29.altinitystable (altinity build))
Stack backtrace:
0: anyhow::error::<impl …
```
=> support max_bytes_before_external_group_by ClickHouse insert flag

snuba/datasets/configuration/issues/entities/search_issues.yaml
Add an inner join relationship for the `search_issues` dataset with the `group_attributes` to support inner join queries on issue search. 
Similar join relationship defined for the events table [here](https://github.com/getsentry/snuba/blob/22f3d4d199f845f468a1b56c7a55c497551d5e31/snuba/datasets/configuration/events/entities/events.yaml#L489).
=> feat(group-attributes): Add an inner join relationship for search_issues and group_attributes

snuba/admin/iam_policy/iam_policy.json
From time to time, while we are debugging some metric issues, it would help a lot knowing which raw data is in the Clickhouse.
Most recent occasion was this morning where we could fix the problem very fast, because the Ingest team had the access to the Cardinality analyzer, and we could see the raw data, it help us eliminate a lot of possible problem causes and quickly locate the real problem.
=> perm(access) Give telemetry experience team access to cardinality analyzer

snuba/datasets/processors/transactions_processor.py, tests/datasets/test_transaction_processor.py
Follow up to #6103 to begin writing the profiler_id value to the transactions table.
=> feat(profiling): Write profiler_id to transactions table

snuba/admin/production_queries/prod_queries.py, snuba/admin/views.py, snuba/web/query.py, snuba/web/views.py, tests/admin/test_api.py, tests/web/test_parse_and_run_query.py
Lightweight deletes needs to run a query to check how many rows will be affected before actually running the deletes. This requires that the code to run a query is reusable. There is also a disconnect in the codebase between the usefulness of datasets.
The original intent in snuba was that datasets where central to how things were queried. That was never really realized. In SnQL queries, entities or storages are specified directly. There is no functional need for datasets. However, many metrics are tagged with the dataset name and many dashboards use it as filters. This means we can't remove datasets entirely just yet.
Creates a `parse_and_run_query` function which is the new top level function for running queries from the input JSON payload. It does not concern itself with any HTTP error …
=> ref(lwdeletes): create parse_and_run_query function

snuba/query/mql/context_population.py, snuba/query/mql/parser_supported_join.py, tests/query/parser/test_formula_mql_query.py, tests/query/parser/test_parser.py, tests/test_metrics_mql_api.py
This PR is responsible for fixing MQL formula totals queries. There are two main necessary changes to fix these queries:
* Add time expression to join conditions (`keys`) for totals queries. 
* Whether or not `interval` is provided in the MQL context, the resulting snuba AST (and SQL) should always contain a time expression in the select clause. It is ok for timestamp column to be `NULL`. This timestamp column is necessary for the join conditions to work properly.
=> bug(mql): Fix MQL totals queries

snuba/datasets/configuration/discover/entities/discover.yaml, snuba/datasets/configuration/discover/entities/discover_events.yaml, snuba/datasets/configuration/discover/entities/discover_transactions.yaml, snuba/datasets/configuration/transactions/entities/transactions.yaml, snuba/datasets/configuration/transactions/storages/transactions.yaml
This makes the new `profiler_id` column on the transactions table (added in #6103) queryable for the profiling use cases.
=> feat(transactions): Make profiler queryable

snuba/migrations/operations.py
Now when migrations are executed, the migration will not move on from 1 host to the next one until `select count(*) from system.mutations where is_done=0` is 0
Not sure how to do a comprehensive test of this but heres how i tested:
* in the case where no mutation in progress, this works. I successfully ran a normal migration locally.
* in the case of a mutation in progress I wasnt able to directly test, but I tested with is_done=1 to make sure the count(*) results were good (`[(13,)]`) so i think it should work
=> fix: wait on system.mutations between hosts during migration execution

snuba/query/allocation_policies/bytes_scanned_rejecting_policy.py, snuba/query/allocation_policies/bytes_scanned_window_policy.py, snuba/query/allocation_policies/concurrent_rate_limit.py, snuba/query/allocation_policies/per_referrer.py, tests/web/test_db_query.py
The previous explanations and suggestions I wrote are vague, ambiguous, and unhelpful. I updated them to be clearer, understandable, and more detailed.
=> Add better explanations for ReferrerGuardRailPolicy, ConcurrentRateLimitAllocationPolicy, and BytesScannedRejectingPolicy

snuba/query/snql/discover_entity_selection.py, tests/fixtures.py, tests/test_snql_api.py
When using the profiler_id column, the discover entity selection should default to the transactions entity the same way it does for profile_id.
=> fix(transactions): Select transactions entity when using profiler id

snuba/clickhouse/formatter/query.py, snuba/clickhouse/query.py, snuba/clusters/cluster.py, snuba/datasets/configuration/issues/storages/search_issues.yaml, snuba/query/__init__.py, snuba/web/converters.py, snuba/web/delete_query.py, snuba/web/views.py, tests/clickhouse/test_query_format.py, tests/test_search_issues_api.py
**context**
This is a simple delete API that allows for deleting data for specific storages that are flagged in, if the runtime config `storage_deletes_enabled` is enabled.
This is not production ready, but rather a way to test out the delete functionality in production, with multi-node clusters. We will be using this to test on search_issues data in S4S only as we iterate. 
**Payload**
This schema may change in the future, and be added to, but the basic structure is a `columns` mapping, which maps the column name to the values you filtering on to delete. This only constructs in or eq expressions, not gte or lte for now.
```json
{
"columns": {"occurrence_id": ["4c90c9d3-5a51-4bb7-90f1-913a4b1b758d"], "project_id": [3]},
"tenant_ids": {"referrer": "api_referrer", "organization_id": 1},
} …
```
=> ref(snuba-deletes): Basic delete API

snuba/clickhouse/formatter/query.py, snuba/query/data_source/join.py, snuba/query/formatters/tracing.py, snuba/query/joins/metrics_subquery_generator.py, snuba/query/mql/context_population.py, snuba/query/mql/parser_supported_join.py, snuba/web/db_query.py, tests/query/joins/test_metrics_subqueries.py, tests/query/parser/test_formula_mql_query.py, tests/query/parser/test_parser.py, tests/test_metrics_mql_api.py
This PR is responsible for fixing formula totals queries, formulas with an orderby, and one-sided groupby formulas. The main changes/fixes in code include:
* Revert back to adding the time expression to the SELECT clause when an interval is provided.
* Only add time expression in join conditions if interval is provided.
* Support formula queries with no groupby, no interval, and with totals. When no groupby and no interval are provided in a formula query, the subqueries will return a single value. As a result, there are no columns to join by. A `CROSS JOIN` is used to to obtain a results in the outer query to perform its given mathematical operation.
* Support one-sided group bys (time spent percentage use-case)
See added unit tests in `tests/test_metrics_mql_api.py` for supported …
=> bug(mql): Fix MQL formula queries with totals and no groupby

snuba/datasets/processors/transactions_processor.py, tests/datasets/test_transaction_processor.py
In addition to the profiler id, sometimes, we need the thread id to be able to link to the right thread within the profile.
=> feat(profiling): Write thread id to transactions table

snuba/datasets/processors/transactions_processor.py, tests/datasets/test_transaction_processor.py
In addition to the profiler id, sometimes, we need the thread id to be able to
link to the right thread within the profile.
Fixes SNUBA-595
=> feat(profiling): Write thread id to transactions table (#6138)

snuba/query/mql/parser_supported_join.py, snuba/query/snql/parser.py, tests/query/parser/test_formula_mql_query.py, tests/test_metrics_mql_api.py
This PR is responsible for fixing MQL queries with nested formulas (no groupby, with totals). See issue here: https://sentry.sentry.io/issues/5644191888/?project=300688&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=7. When the parser receives a totals formula without a groupby, it automatically converts the join type into a `CROSS JOIN`. This cross join needs to be properly pushed down to all join nodes appropriately.
=> bug(mql): Fix nested totals formulas queries with no group by

snuba/query/exceptions.py, snuba/web/delete_query.py, tests/web/test_max_rows_enforcer.py
https://getsentry.atlassian.net/browse/SNS-2821
The cost of a lightweight delete operation depends on the number of matching rows in the WHERE clause and the current number of data parts. This operation will be most efficient when matching a small number of rows, and on wide parts (where the _row_exists column is stored in it’s own file) 
Because of the above, we want to limit the number of rows one deletes at a time. The MaxRowsEnforcer will query clickhouse to see how many rows we plan on deleting and if it crosses the max_rows_to_delete set for that storage we will reject the query.
=> feat(lwdeletes): Add MaxRowEnforcer

snuba/web/delete_query.py, snuba/web/views.py, tests/test_search_issues_api.py, tests/web/test_max_rows_enforcer.py
1. extract the logic that was inside of `views.py:storage_delete` and put it into a new function `delete_query.py:delete_from_storage`. 
Now whats in views.py is basically just responsible for handling the http request stuff, and the actual logic for deletes happens in `delete_from_storage`. This way my snuba admin UI can call `delete_from_storage` as its interface. The motivation for this change can be best described by a summary of my conversations with Evan and Filippo:
> **Filippo & Evan**: The api-endpoint-view-function (`storage_delete`) should be as lightweight as possible, only responsible for parsing the http request inputs and then passing them along to another function that actually handles the logic.
> **Kyle:** But why does it have to be this way? Can't I just use api …
=> ref: deletes api

snuba/pipeline/composite_entity_processing.py, tests/test_metrics_mql_api.py
This PR is responsible for fixing queries with similar tag key filters but different tag values. To do this, the `add_equivalent_conditions` processor was removed from the MQL entity processing pipeline. 
This processor is responsible for finding conditions in a join query on columns that are semantically equivalent in the another entity in the join and adds the same condition on the equivalent column. For example, in a join between events and groupedmessage, if there is a condition on events.project_id, it would replicate the same condition on groupedmessage.project_id as this is a semantically equivalent column in order to optimize the clickhouse scan. This processor is not necessary for MQL as all relevant conditions are already added during parsing. 
More specifically, this fixes the …
=> bug(mql): Remove Add Equivalent Conditions Processor from MQL Pipeline

snuba/snuba_migrations/events_analytics_platform/0001_spans.py
This works locally at least:
```
8a035ef769f1 :) select cityHash64(reinterpretAsUInt128('550e8400-e29b-41d4-a716-446655440000'::UUID));
SELECT cityHash64(reinterpretAsUInt128(CAST('550e8400-e29b-41d4-a716-446655440000', 'UUID')))
7067610571742207507
```
=> fix(events-analytics-platform): Fix sharding key, clickhouse does not like u128

snuba/clusters/storage_sets.py
This is cleaning up what remains of #6079 . This is cleanup of temporary changes that were done to accomplish https://github.com/getsentry/ops/pull/11385 but can now be deleted. This PR accomplishes step 4 (see below).
1. ~~delete migrations for SEARCH_ISSUES_TMP~~
2. ~~delete cluster mapping for SEARCH_ISSUES_TMP in snuba~~
3. ~~delete cluster mapping for SEARCH_ISSUES_TMP in ops~~
4. delete SEARCH_ISSUES_TMP storage set in snuba
5. decommission issue-platform-query-node in production
steps 1 and 2 done in https://github.com/getsentry/snuba/pull/6110
step 3 was done in https://github.com/getsentry/ops/pull/11443
=> chore: delete SEARCH_ISSUES_TMP storage set

snuba/snuba_migrations/generic_metrics/0052_counters_raw_add_sampling_weight.py, snuba/snuba_migrations/generic_metrics/0053_counters_aggregated_add_sampling_weight.py, snuba/snuba_migrations/generic_metrics/0054_counters_mv3.py
Adds a set of migrations to allow materialization to account for sampled counter values.
Specifically
- Adds a new column that contains `sampling_weight`, i.e. `sampling factor^(-1)`, AKA how many actual row it is worth in the raw table
- Adds a new `value_weighted` column that contains the aggregated sum taking the sampling weight into consideration
- Adds a new materialized view to manifest the columns above.
<details>
<summary>Click to expand</summary>
```bash
make apply-migrations
```
```sql
4d5fc6ba4a26 :) insert into generic_metric_counters_raw_local FORMAT JSONColumns \
:-] {
"use_case_id": ["custom"],
"org_id": [1],
"project_id": [1],
"metric_id": [1],
"timestamp": [1722378310],
"retention_days": [90],
"tags.key": [[1]],
"tags.indexed_value": [[10]],
"tags.raw_value": [["c_v_1"]], …
```
=> feat(generic-metrics): Add migrations to allow sampling for counters

snuba/admin/static/api_client.tsx, snuba/admin/static/data.tsx, snuba/admin/static/delete_tool/index.tsx, snuba/admin/tool_policies.py, snuba/admin/views.py, snuba/web/delete_query.py, snuba/web/views.py
This PR adds a page to snuba admin that we can use to test deletes in prod.
1. create a front-end react interface for deletes
* `static/delete_tool/index.tsx` is the new react UI, it calls `api_client.tsx:runLightweightDelete` 
* `api_client.py:runLightweightDelete` sends the input via http request to `/delete` endpoint. (note: i think it would have been equally valid to just send the http request from index.tsx rather than having this separate function, but I did it like this bc everyone else in the codebase did)
* `data.tsx` adds the new page to the Nav bar
2. create a new `/delete` endpoint in snuba admin `admin/views.py:delete`
As said in bullet 1, the react UI sends the input to `/delete`. This is a new endpoint we created, it mostly just calls `delete_from_storage` (what Meredith …
=> feat: new page in snuba admin to do deletes

snuba/snuba_migrations/generic_metrics/0055_gauges_raw_add_sampling_weight.py, snuba/snuba_migrations/generic_metrics/0056_gauges_aggregated_add_weighted_columns.py, snuba/snuba_migrations/generic_metrics/0057_gauges_mv3.py
This PR is responsible for adding a set of migrations to allow materialization to account for sampled gauges values.
More specifically:
- Add a new `sampling_weight`, i.e. `sampling factor^(-1)` column to the gauges raw table 
- Add new `sum_weighted` and `count_weighted` columns that contains the aggregated function which takes the sampling weight into consideration
- Adds new materialized view to manifest the columns above.
<details>
<summary>Click to expand</summary>
```bash
make apply-migrations
```
```sql
b02f52acbe45 :) insert into generic_metric_gauges_raw_local FORMAT JSONColumns {
"use_case_id": ["custom"],
"org_id": [1],
"project_id": [1],
"metric_id": [1],
"timestamp": [1722378310],
"retention_days": [90],
"tags.key": [[1]],
"tags.indexed_value": [[10]],
"tags.raw_value": …
```
=> feat(generic-metrics): Add migrations to allow sampling for gauges

snuba/web/delete_query.py
We can't just re-use the same `from_clause` from the delete query because the table we query from will be different (select queries target the dist table). 
We saw this error in [SNUBA-5A2](https://sentry.sentry.io/issues/5662439338/?project=300688&query=firstRelease%3A1aab7d69cea520eba3deb565065744813510e5fa+issue.type%3Aerror+%21level%3Ainfo&referrer=issue-stream&statsPeriod=1h&stream_index=0). This should provide the correct table using https://github.com/getsentry/snuba/blob/0ffa35091853f719ab5012e9b6f5da4d7739904a/snuba/datasets/schemas/tables.py#L85-L94
=> fix(snuba-deletes): max row enforcer should query dist table

snuba/admin/clickhouse/predefined_system_queries.py
Small change that has just been bugging me - the `CreateTableQuery` right now shows all the [INFORMATION_SCHEMA](https://clickhouse.com/docs/en/operations/system-tables/information_schema) tables which is annoying, so now this just uses the `default` database.
=> (system-queries): use default db in create_table_query

snuba/admin/static/delete_tool/index.tsx, snuba/admin/views.py, snuba/web/delete_query.py
1. add a new endpoint to snuba admin `/deletes-enabled` that returns true if deletes are enabled for the current region, false otherwise
2. make the delete-tool only render if deletes are enabled for that region
previously every region could use the delete tool, even if they werent enabled for that region it would just give a 500 errors when they try to do it. now if they try it will look like this
=> feat: update admin delete-tool UI when deletes are disabled

snuba/admin/views.py, snuba/web/delete_query.py, snuba/web/views.py
If you try to delete from a region or storage where deletes are disabled, our HTTP endpoints used to give 500 errors. It should be a 400 error though, this PR changes it to 400.
=> ref: make deletes not enabled return 400 error instead of 500

snuba/clickhouse/translators/snuba/mappers.py, snuba/datasets/configuration/events_analytics_platform/entities/eap_spans.yaml, snuba/snuba_migrations/events_analytics_platform/0002_spans_attributes_mv.py, snuba/utils/constants.py
Create a table that stores just the attribute keys and values that have been seen by an org. This
can be used for autocomplete or any other validation feature.
The table doesn't have any indexes on it at the moment. It also provides a count, to do simple
ranking if that's useful in the future.
=> feat(eap): Add attribute key/value lookup table

snuba/snuba_migrations/events_analytics_platform/0002_eap_spans_project_id_index.py
The project_id is heavily used in queries, to narrow down to specific services.
Add a bloom filter index on it to help improve query performance.
=> feat(eap): Add index on project_id

snuba/snuba_migrations/generic_metrics/0058_distributions_raw_add_sampling_weight.py, snuba/snuba_migrations/generic_metrics/0059_distributions_aggregated_add_weighted_columns.py, snuba/snuba_migrations/generic_metrics/0060_distributions_mv4.py
This PR is responsible for adding a set of migrations to allow materialization to account for sampled distribution values.
More specifically:
- Add a new `sampling_weight`, i.e. `sampling factor^(-1)` column to the distribution raw table 
- Add new `percentiles_weighted`, `avg_weighted`, `sum_weighted`, and `count_weighted` columns that contains the aggregated function which takes the sampling weight into consideration.
- Adds new materialized view to manifest the columns above.
Optimization changes:
From [investigating arrayJoin performance](https://www.notion.so/sentry/Avoiding-arrayJoin-4fb650aca98a42ba9a2b4178a6560e96?pvs=4), it was discovered that `arrayJoin` in the materialized view consumes significant amounts of memory. To mitigate this, we should `-StateArray` combinator instead …
=> feat(generic-metrics): Add migrations to allow sampling for distributions

snuba/datasets/configuration/issues/storages/search_issues.yaml, snuba/datasets/configuration/json_schema.py, snuba/datasets/configuration/storage_builder.py, snuba/datasets/storage.py, snuba/query/allocation_policies/concurrent_rate_limit.py, snuba/web/delete_query.py, tests/datasets/configuration/test_storage_loader.py
**context**
Right now we have a simple ratelimiter that limits deletes to `1` concurrent query at a time for the whole endpoint https://github.com/getsentry/snuba/blob/ea2f8e716ea519ae173e7a6833da5d2bf16859f2/snuba/web/views.py#L305
This is good enough for testing out ourselves, but beyond that we wanted to add a more robust ratelimiter that allowed for more granular levers that we have for other endpoints. Product should also be ratelimiting on their end though, this is not supposed to be in lieu of that. 
**delete allocation policies**
We can reuse the allocation policy framework for the delete query pipeline. I've made these policies separate to the other allocation policies definitions because we should be adjusting the limits separately; deletes should not have as high thresholds as …
=> ref(snuba-deletes): introduce delete allocation policies

snuba/clickhouse/translators/snuba/mappers.py, snuba/datasets/plans/storage_processing.py, snuba/query/expressions.py, tests/clickhouse/translators/snuba/test_translation.py
Originally, alias on HashBucketMapper would not work (for some reason)
This adds a test that aliasing works, and sends tags as `arrayElement` which clickhouse converts to anyways (Map in clickhouse is Array(Tuple(k, v)))
=> fix(eap): Use arrayElement directly to fix alias issues with HashBucketMapper

requirements.txt, rust_snuba/Cargo.lock, rust_snuba/Cargo.toml, rust_snuba/src/processors/generic_metrics.rs, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-generic-metrics-GenericDistributionsMetricsProcessor-snuba-generic-metrics__1__snuba-generic-metrics-dist-base64.json.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-generic-metrics-GenericDistributionsMetricsProcessor-snuba-generic-metrics__1__snuba-generic-metrics-dist-encoded-plain-array.json.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-generic-metrics-GenericDistributionsMetricsProcessor-snuba-generic-metrics__1__snuba-generic-metrics-dist-zstd.json.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-metrics-PolymorphicMetricsProcessor-snuba-metrics__1__snuba-metrics-sampled.json.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-metrics-PolymorphicMetricsProcessor-snuba-metrics__1__snuba-metrics-unsampled.json.snap
Previous PR in the stack https://github.com/getsentry/snuba/pull/6172
Forwards sampling information (aka `sampling_weight`) to clickhouse now that it can handle sampled data.
<details>
<summary>Click to expand</summary>
Apply migrations and run snuba devserver
```bash
make apply-migrations
snuba devserver
```
Send some metrics
```sql
Use the following SQL to verify clickhouse, there should be 4 metrics for each use cases, 24 in total.
SELECT
materialization_version,
timestamp,
tags.key,
tags.raw_value
FROM generic_metric_counters_raw_local
WHERE arrayExists(v -> match(v, 'metric_e2e_.*VH12IXDX'), tags.raw_value)
UNION ALL
SELECT
materialization_version,
timestamp,
tags.key,
tags.raw_value
FROM generic_metric_distributions_raw_local
WHERE arrayExists(v -> match(v, 'metric_e2e_.*VH12IXDX'), …
```
=> feat(generic-metrics): Forward sampling information from consumer to clickhouse

rust_snuba/src/processors/generic_metrics.rs, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-generic-metrics-GenericCountersMetricsProcessor-snuba-generic-metrics__1__snuba-generic-metrics1.json.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-generic-metrics-GenericDistributionsMetricsProcessor-snuba-generic-metrics__1__snuba-generic-metrics-dist-base64.json.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-generic-metrics-GenericDistributionsMetricsProcessor-snuba-generic-metrics__1__snuba-generic-metrics-dist-encoded-plain-array.json.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-generic-metrics-GenericDistributionsMetricsProcessor-snuba-generic-metrics__1__snuba-generic-metrics-dist-zstd.json.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-generic-metrics-GenericGaugesMetricsProcessor-snuba-generic-metrics__1__snuba-generic-metrics-gauge.json.snap
Bump the materialization version permanently for gauges/counters/distributions to enable sampling now that it has been verified via feature flag
=> feat(generic-metrics): Bump materialization_version for generic metrics

snuba/datasets/configuration/events_analytics_platform/entities/eap_spans.yaml
@wmak can you check this works in dev? There are no tests for EAP spans yet until your sentry acceptance tests are done, so this is completely blind for now
=> feat(eap): Add the TimeSeriesProcessor to entities/eap_spans

snuba/admin/static/api_client.tsx, snuba/admin/views.py, snuba/web/views.py
these are small changes that needed to be made that came up while connecting the deletes endpoint to sentry codebase.
1. Made the api response results to be inside "data". This is bc the sentry codebase relies on api responses to be in this format.
2. make snuba admin requests nest `columns` inside `query`. this is bc we previously changed the schema definition to be this, so snuba admin wasnt working ever since. now it works
=> fix: deletes api, change success response format, fix admin bug

snuba/snuba_migrations/events_analytics_platform/0005_remove_attribute_mv.py
There is a concern that this materialized view is overloading the eap cluster,
so remove it to test the impact on the cluster.
The cluster appears over saturated in IO wait time, and is falling behind on merges.
When this materialized view was added, the number of rows inserted skyrocketed (500% increase).
Disabling this will help to show what the causes/symptoms of the higher load are.
=> ref(eap): Remove materialized view

snuba/migrations/operations.py, snuba/snuba_migrations/events_analytics_platform/0005_drop_attribute_key_project_id_indexes.py
Inserting data in this cluster is slow and having many indices is one of the reason. These indices we added were not as effective as we thought so it's harmless to remove them and will probably help insertion.
=> fix(eap-spans): Drop ineffective indices to speed up insertion

snuba/query/exceptions.py, snuba/web/delete_query.py
https://getsentry.atlassian.net/browse/SNS-2842
Currently, if there are no rows that match the criteria specified by the delete query, the code will still go through the deletion pipeline (and any post-processing). This is unnecessary. Instead, let’s short-circuit and throw an error if there are no rows to delete.
=> ref(snuba-deletes) don't run delete queries when 0 rows need to be deleted

snuba/utils/schemas.py, snuba/web/delete_query.py, snuba/web/views.py, tests/test_search_issues_api.py, tests/utils/test_columns_validator.py
We have some [schema validation](https://github.com/getsentry/snuba/blob/d4b164c06710e15bed33d868102305adf8fe495c/snuba/query/schema.py#L38) on delete api, but because the columns depend on the storage, we can't do that level of type validation when parsing the payload. The only required column we have is the `project_id` (which is debatable on whether we should have that there but anyway)
If the column `occurrence_id` is an uuid and someone sends:
```json
{ "columns": {"occurrence_id": ["hello"]}
```
we'll get a clickhouse error when trying to run the delete.
**ColumnValidator**
This validator will check to make sure that the type defined in the schema matches the values passed through in the api. I've only implemented a handful of types and I don't expect that we will need many more, at …
=> ref(snuba-deletes): add ColumnValidator

snuba/snuba_migrations/events_analytics_platform/0007_drop_project_id_index.py
This migration will take a really long time in US and it already ran in S4S and DE, so, to prevent it from running in US while unblocking the pipeline, we're making it a no-op.
=> fix(eap-spans): Make project_id index removal migration a no-op

snuba/query/mql/context_population.py, snuba/query/mql/parser_supported_join.py, tests/query/parser/test_formula_mql_query.py, tests/query/parser/test_parser.py, tests/test_metrics_mql_api.py
This PR is responsible for fixing a bug with the `totals` flag in MQL. When the `totals` flag is set to true, snuba will insert a `WITH TOTALS` modifier next to the `GROUP BY` in the query. Read more about WITH TOTALS [here](https://clickhouse.com/docs/en/sql-reference/statements/select/group-by#with-totals-modifier). However, if the query does not contain a `GROUP BY` then the modifier will not be added to the query. As a result, the flag is ignored and CH does not return a totals row. When this happens, the query AST still has `totals` set to true, and during [result transformation](https://github.com/getsentry/snuba/blob/fc11af17f7558e56a4139d061f47bef0369de0b7/snuba/clickhouse/native.py#L472), snuba pops the last element of the data array and assumes it is the totals row (even though …
=> bug(mql): Fix WITH TOTALS for MQL queries

snuba/admin/static/tracing/query_display.tsx
This change updates the warning link on the "ClickHouse Tracing" page to open a new tab when clicked. This makes it easier to navigate back once the linked is clicked and the information is read.
=> fix(snuba-admin): Updating snuba admin link to open a new tab

docs/source/contributing/environment.rst
I ran into issues regarding python 3.8.11 version and rust while setting up the local development environment using https://getsentry.github.io/snuba/contributing/environment.html. This PR fixes the documentation and makes it more consistent with what is being used in the team today.
=> Added a few missing details on Snuba development environment README page

snuba/admin/static/tracing/index.tsx, snuba/admin/static/tracing/query_display.tsx
Have an option to show the raw trace output in the Tracing tool, as well as the ability to copy just
the raw tracing output instead of the full JSON response.
=> ref(admin): Show raw trace output in the Admin tool

snuba/admin/static/cardinality_analyzer/query_display.tsx, snuba/admin/static/clickhouse_queries/query_display.tsx, snuba/admin/static/production_queries/index.tsx, snuba/admin/static/querylog/query_display.tsx, snuba/admin/static/tests/tracing/index.spec.tsx, snuba/admin/static/tests/utils/execute_button.spec.tsx, snuba/admin/static/tracing/query_display.tsx, snuba/admin/static/utils/execute_button.tsx
This removes a lot of duplicate logic around handling errors and ensures that every page has a
proper loading indicator.
=> ref(admin): Standardize Execute Query buttons

snuba/query/dsl.py, tests/query/test_dsl.py
We have a convenient way to express functions in the DSL, expand to curried functions (which are a pain in the ass) and add a test
=> feat(dsl): Add curried functions to dsl

snuba/migrations/operations.py
TIL there is a _block_on_mutations function. idk why it exists but if we're running async we def don't need to block on it
=> feat(migrations): allow drop indices to not block on mutations

rust_snuba/Cargo.toml
Currently rust consumer has a ctrlc handler which only handles `SIGINT`. If a user sends `SIGTERM` instead, then the rust consumer gets terminated abruptly. The handling `SIGTERM` section [here](https://arjo129.github.io/rustros_tf/ctrlc/index.html#handling-sigterm) describes that in order for ctrlc handler to handle `SIGTERM` (in addition to `SIGINT`), `termination` feature needs to be enabled.
Before the fix:
> 1. Run rust-consumer:
> ```
> snuba rust-consumer --storage spans --consumer-group snuba-spans-consumers --auto-offset-reset=latest --max-batch-time-ms 1000 --no-strict-offset-reset
> ```
> 
> 2. Send `SIGTERM` to the rust-consumer process:
> ```
> kill -s SIGTERM <rust-consumer-pid> 
> ```
> 
> 3. Watch it terminate abruptly as you see this message on the terminal where …
=> Handle SIGTERM gracefully in rust-consumer

snuba/datasets/plans/entity_validation.py, snuba/query/validation/validators.py, tests/test_snql_api.py
When a column/columns is/are not resolved, the query returns ambiguous error message like:
`validation failed for entity generic_metrics_distributions: Entity generic_metrics_distributions: Query column 'wrapper_type' does not exist`. 
This needs to be fixed to show a more readable message:
`Validation failed for entity generic_metrics_distributions: Tag keys (wrapper_type) not resolved`
Closes #6084
**Testing done:**
Fixed unit tests
=> Emit better error message when a column is not resolved properly

snuba/admin/package.json, snuba/admin/static/common/components/sql_editor.tsx, snuba/admin/yarn.lock
In a bizarre twist, CodeMirror by default does not allow multiple trailing newlines! Why? No idea! It seems like by default `Enter` inserts a newline and immediately re-formats the content, which strips multiple newlines. Fixed with this custom keymap.
=> feat: CodeMirror multi-newline

snuba/admin/views.py, snuba/web/delete_query.py, snuba/web/views.py, tests/web/test_delete_query.py
**context**
We have the configurations for the delete allocation policies but they aren't actually being used in the delete pipeline yet.
Some more info in the original PR that added the configuration for the delete allocation policies https://github.com/getsentry/snuba/pull/6180. 
This reuses some of the functionality from the regular select query pipeline. The delete concurrent policy we defined will not be enforced yet, so we will still be relying on the simple rate limiter  https://github.com/getsentry/snuba/blob/ea2f8e716ea519ae173e7a6833da5d2bf16859f2/snuba/web/views.py#L305
until we are ready to enforce the allocation policy. We can also add another delete policy once we verify the delete allocation policy pipeline is working as expected.
**next steps**
=> ref(snuba-deletes): use allocation policies

snuba/admin/clickhouse/common.py, snuba/admin/clickhouse/tracing.py, snuba/admin/static/tracing/index.tsx, snuba/admin/static/tracing/query_display.tsx, snuba/admin/static/tracing/types.tsx, snuba/admin/views.py, tests/admin/test_api.py
ClickHouse's profile events have a lot of useful data that can be found [here](https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ProfileEvents.cpp). The query passed to tracing tool is appended with `SETTINGS log_profile_events=1` so that ClickHouse makes an entry in the `system.query_log` table. Then another query is made to scan `system.query_log` to get the profile event data. 
Finally, the Snuba admin frontend is modified to accommodate the extra information returned.
Testing done:
=> Gather ClickHouse's profile event data in Snuba admin tracing tool

CODEOWNERS
This folder is all stuff that is owned by EAP team.
=> chore(eap): Add RPC folders to EAP codeowners

snuba/admin/audit_log/action.py, snuba/admin/views.py, snuba/migrations/runner.py, tests/admin/test_api.py
Yes this is kind of a hack but asking OPS to run these commands every time we mess up a migration is driving me and @phacops insane
=> feat(admin): create an api to overwrite a snuba migration state

snuba/web/db_query.py, tests/test_snql_api.py, tests/web/test_db_query.py
https://getsentry.atlassian.net/browse/SNS-2852
Allocation policies are our mechanism for doing traffic management for Snuba queries. This PR adds more fields to the payload returned by Snuba, so we can filter more efficiently in Sentry traces
=> More comprehensive payload from CapMan

snuba/admin/views.py, snuba/web/views.py
Adds delete allocation policies to show up in snuba admin per storage along side the other allocation policies.
> <img width="946" alt="Screenshot 2024-08-28 at 3 54 24 PM" src="https://github.com/user-attachments/assets/b3b6651b-d671-4d3b-8d6c-2c49a0e29b73">
<br/>
If there are no delete query allocation policies listed it will look like the following:
> <img width="992" alt="Screenshot 2024-08-28 at 3 54 42 PM" src="https://github.com/user-attachments/assets/9b83de50-f0e2-4018-bc43-79fb98c08d4d">
=> ref(admin): include delete policies in capacity mgmt

snuba/cli/optimize.py, snuba/clickhouse/optimize/optimize.py, snuba/clickhouse/optimize/optimize_scheduler.py, snuba/clickhouse/optimize/util.py, snuba/settings/__init__.py, tests/clickhouse/optimize/test_optimize.py, tests/clickhouse/optimize/test_optimize_scheduler.py, tests/clickhouse/optimize/test_optimize_tracker.py
The optimize job has been [failing](https://app.datadoghq.com/monitors/72460548?q=kube_job%3Asnuba-optimize-errors-tiger-mz-2-28703520%2Csentry_region%3Aus&event_id=7684526334976626842&source=monitor_notif&view=spans&from_ts=1722295368000&to_ts=1722296568000&eval_ts=1722296568000) due to not meeting the cutoff time. 
There's two aspects of the job scheduling:
- a period of time where the job runs in parallel, which puts more load on ClickHouse
- a period of time when the job optimizes one partition at a time. This lets it overlap with our peak load time without exhausting ClickHouse's resources
In this PR, we changed the parallelization period to run with a configurable number of threads, and this configuration is checked every time a partition finishes optimizing. This way, we can change …
=> Make the number of threads to run the optimize cron job configurable

snuba/admin/audit_log/action.py, snuba/admin/auth_roles.py, snuba/admin/clickhouse/common.py, snuba/admin/clickhouse/system_queries.py, snuba/admin/iam_policy/iam_policy.json, snuba/admin/static/clickhouse_queries/query_display.tsx, snuba/admin/static/clickhouse_queries/types.tsx, snuba/admin/views.py, tests/admin/test_api.py, tests/admin/test_system_queries.py
There has been a lot of requirests for prodction access and SRE tickets
to execute clickhouse system commands that were not supported in the
snuba admin.
This includes commands like: SYSTEM and ALTER.
These commands do not expose customer data. 
They were not exposed at the beginning because they are as safe as
playing with an armed nuclear warhead.
Now snuba has RBAC and an audit log. The Sns team can consider revisiting
this decision.
This PR implements the sudo mode for the system queries
tool in the snuba admin:
- a new parameter is passed to http://127.0.0.1:1219/run_clickhouse_system_query. Which is called `sudo` 
- if the parameter is true the user is trying to execute a query in sudo mode
- If the user has the required role, the system would accept SYSTEM and ALTER statements
- …
=> Snuba admin sudo mode for system commands

requirements.txt, snuba/web/rpc/common.py, snuba/web/rpc/exceptions.py, snuba/web/rpc/span_samples.py, snuba/web/rpc/timeseries.py, snuba/web/views.py, tests/web/rpc/test_common.py, tests/web/rpc/test_timeseries_api.py
This lays the foundation for a lot of the shared snuba RPC logic, including evaluating column names and filters.
=> feat(eap): Add an RPC for span samples, refactor a lot

snuba/admin/views.py
Snuba admin changes to append ProfileEvents to the trace query output were timing out after 10 seconds and not returning the trace query output. The fix involves updating the Snuba admin trace query execution to wait 60 seconds for retrieving ProfileEvents from both storage and query nodes where the query was executed. If the ProfileEvents aren't available within that time, it will return just the trace query output.
=> Fix snuba admin trace query execution

snuba/admin/clickhouse/system_queries.py
The current audit log entry does not say which hosts the command was run on making it mostly useless
=> fix(admin): add more info to system query audit log

snuba/web/db_query.py
We currently emit these metrics on a per-policy level, which means some queries can be counted multiple times for multiple policies. This PR adds metrics so we only count each query once. This will allow us to get a more accurate sense of the % of queries that are successful/throttled/rejected
=> Emits DD metric for queries statuses

snuba/datasets/configuration/events_analytics_platform/entities/eap_spans.yaml, snuba/query/processors/logical/hash_bucket_functions.py, tests/query/processors/test_hash_bucket_functions_processor.py
In eap_spans, we split up map columns for better performance.
In the entity, 
`attr_str Map(String, String)`
becomes
```
attr_str_0 Map(String, String),
attr_str_1 Map(String, String),
...
```
in the storage.
This transformer converts mapKeys(attr_str) to arrayConcat(mapKeys(attr_str_0), mapKeys(attr_str_1), ...)
and the same for mapValues
=> feat(eap): Add a processor that allows you to do mapKeys on attr_str

snuba/admin/static/tracing/index.tsx
Another instance where a null check was missing before calling the function to retrieve values.
=> Fixing Snuba Admin trace UI error.

snuba/admin/static/cardinality_analyzer/query_display.tsx, snuba/admin/static/production_queries/index.tsx, snuba/admin/static/querylog/query_display.tsx, snuba/admin/static/tracing/query_display.tsx, snuba/admin/static/utils/execute_button.tsx
There was a bug in https://github.com/getsentry/snuba/pull/6222 which incorrectly parsed the `err` string in `snuba/admin/static/utils/execute_button.tsx`. The PR fixes that to ensure that query errors are presented back to the user in admin.
=> bug(admin): Fix invalid query error alerting in snuba admin

snuba/admin/views.py, snuba/manual_jobs/manifest_reader.py, snuba/manual_jobs/run_manifest.json
In this PR, I'm creating a sample job run manifest along with a reader and an API endpoint to return what's in the static file. This will help me test whether the plumbing to put different static files in this location is working.
Next steps: deploy to prod, validate the correct result. Start working on providing a different payload in a different environment based on the ops repo.
=> feat(job-runner): scaffolding for job manifest testing

snuba/snuba_migrations/events_analytics_platform/0013_span_attribute_table_shard_keys.py
We'd like to be able to write queries like this one:
```
SELECT
quantileTDigest(0.75)(duration_ms)
FROM eap_spans_dist
PREWHERE name = '/npv' and is_segment = true
WHERE
organization_id = 22381
AND project_id = 1506863
AND attr_str_0['transaction.op'] = 'navigation'
AND attr_str_14['platform'] != 'roku'
AND attr_str_14['environment'] = 'prod'
AND _sort_timestamp > toDateTime(1725576602)
AND (_sort_timestamp, trace_id) IN (
SELECT any(timestamp) AS ts, trace_id FROM spans_str_attrs_local WHERE (organization_id, attr_key, attr_value) IN ((22381, 'transaction.op', 'navigation'), (22381, 'environment', 'prod'))
AND timestamp > toDateTime(1725576602)
GROUP BY trace_id
HAVING groupBitOr(attr_key = 'transaction.op' AND attr_value = 'navigation')
AND groupBitOr(attr_key = 'environment' AND …
```
=> feat(eap): Shard meta tables by trace ID

snuba/query/processors/logical/hash_bucket_functions.py, snuba/web/rpc/common.py, tests/query/processors/test_hash_bucket_functions_processor.py
This hashes the key before it's sent over to clickhouse.
=> feat(eap): make mapContains work with EAP dataset

snuba/pipeline/stages/query_processing.py, tests/pipeline/test_entity_processing_stage_composite.py
This PR contains a fix for this sentry [issue](https://sentry.sentry.io/issues/5825035976/?project=300688&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=4&utc=true). In the composite query pipeline, snuba is not running entity validators. As a result, join queries with missing columns (e.g. mql formula queries with unresolved tag keys) are reaching ClickHouse and affecting our SLO. Instead, the entity validator should catch these invalid queries and fail accordingly.
=> bug(query): Run entity validators in composite query pipeline

rust_snuba/src/processors/eap_spans.rs, rust_snuba/src/processors/snapshots/rust_snuba__processors__eap_spans__tests__serialization.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-spans-EAPSpansMessageProcessor-snuba-spans__1__basic_span.json.snap, snuba/datasets/configuration/events_analytics_platform/entities/eap_spans.yaml
This migration was added, but the consumer was never set up to insert into it.
=> feat(eap): Start ingesting data into sample_weight_2 column

snuba/datasets/readiness_state.py
Adding some doc for the `ReadinessState` _Enum_ class to explain its use and the meaning of each of its members.
=> ref(doc): add documentation for the ReadinessState enum

requirements.txt, snuba/web/rpc/common.py, snuba/web/rpc/span_samples.py, tests/web/rpc/test_span_samples.py
Add support for virtual columns to allow for sorting by project name or semver release (as opposed to release id).
=> feat(eap): add virtual column support

requirements.txt, snuba/web/rpc/span_samples.py, snuba/web/rpc/tags_list.py, snuba/web/views.py, tests/web/rpc/test_span_samples.py, tests/web/rpc/test_tags_list.py
sentry-protos 0.1.21 changes the definition a bit, updating the endpoint to accept it.
=> feat(rpc): Update tags list rpc

rust_snuba/src/processors/spans.rs
We only have this metric for generic metrics but it would be useful to have for spans to potentially help understand memory profiles of the spans consumer.
=> metric(consumer): Add a metric to track the size of individual spans

snuba/admin/clickhouse/migration_checks.py, snuba/admin/views.py, snuba/cli/migrations.py, snuba/migrations/runner.py, tests/admin/clickhouse_migrations/test_migration_checks.py, tests/migrations/test_runner.py
Fixes #2159
Running `snuba migrations list` will now show migrations that are in clickhouse but no longer in the codebase (e.g. because snuba was downgraded).
Deleted migration in codebase to check that it shows up in the list.
=> Update migrations list command to show migrations that no longer exist in the codebase

snuba/admin/notifications/slack/utils.py
The slack messages already contain the admin URL which identifies the
region, but let's print it explicitly as well. SENTRY_ENVIRONMENT
corresponds to the region.
=> fix(admin): Print SENTRY_ENVIRONMENT to slack

.github/workflows/docs.yml
After a PR is merged, the github actions is failing in `docs.yml` - https://github.com/getsentry/snuba/actions/workflows/docs.yml. The failure is because we are using deprecated upload artifact v2 instead of the latest and greatest [v4](https://github.com/actions/upload-artifact?tab=readme-ov-file#v4---whats-new).
=> Update github @actions/upload-artifact to v4

snuba/settings/settings_test.py
During the investigation of https://github.com/getsentry/snuba/pull/6279, I found that:
- `OPTIMIZE_JOB_CUTOFF_TIME` is overridden to `24` and it was causing test failures.
- `OPTIMIZE_PARALLEL_MAX_JITTER_MINUTES` does not seem to be used anywhere in the code.
With the change, less no. of local tests fail. The failure number is non-zero because https://github.com/getsentry/snuba/pull/6279 was reverted yesterday . I would like to verify if this small change passes through the CI and stays stable in prod.
=> Cleanup some settings from settings_test.py

requirements.txt, rust_snuba/Cargo.lock, rust_snuba/bin/python_processor_infinite.rs, snuba/subscriptions/scheduler_consumer.py
Bumped the Python requirements, not sure if anything needs to be changed on the Rust side because of https://github.com/getsentry/snuba/blob/master/rust_snuba/Cargo.toml#L34
=> Bump Arroyo to 2.17.6

snuba/web/rpc/timeseries.py, tests/web/rpc/test_timeseries_api.py
The old tests used the same number a bunch of times, so there was a bug where the results were not ordered by time.
This makes the tests a lot more robust and implements weight in the aggregate functions
=> fix: EAP timeseries order, add weight to calculations

snuba/datasets/configuration/events_analytics_platform/entities/spans_num_attrs.yaml, snuba/datasets/configuration/events_analytics_platform/entities/spans_str_attrs.yaml, snuba/datasets/configuration/events_analytics_platform/storages/spans_num_attrs.yaml, snuba/datasets/configuration/events_analytics_platform/storages/spans_str_attrs.yaml, snuba/snuba_migrations/events_analytics_platform/0014_span_attribute_table_smaller.py
We tried to improve performance of other queries with a subselect, but got disappointing results.
This change:
- Drops trace_id from both tables
- Removes attr_value from the number tables (we'd never want to autocomplete numbers)
- Adds the normalized columns (name, segment_name, service, duration_ms, exclusive_time_ms) to both meta tables
=> feat(eap): rewrite the meta tables to have lower cardinality

snuba/snuba_migrations/replays/0021_index_tags.py
Adds materialized _tags_hash_map column and indexes it.  Follow the prior art established by the errors table.
Addresses the following problems:
1. The number of bytes scanned searching for a tag.
2. The amount of time it takes to search by tag.
Related: https://github.com/getsentry/sentry/issues/76289
=> feat(replays): Add materialized tags column and index

snuba/datasets/configuration/events_analytics_platform/storages/spans_num_attrs.yaml, snuba/datasets/configuration/events_analytics_platform/storages/spans_str_attrs.yaml
While migrating the tables in these storages, CI entered into a point where the migrations can't run because the health check is failing, and the health check is failing because the migrations can't run.
=> fix: temporarily limit eap_attribute tables

snuba/cli/jobs.py, snuba/manual_jobs/__init__.py, snuba/manual_jobs/job_loader.py, snuba/manual_jobs/manifest_reader.py, snuba/manual_jobs/toy_job.py, tests/cli/test_jobs.py
https://github.com/getsentry/snuba/pull/6288
=> feat(job-runner): enable snuba jobs command to run from JSON manifest

requirements.txt, rust_snuba/Cargo.lock, rust_snuba/Cargo.toml
This will add the new EAP mutations topic and schema
=> chore: Bump Kafka schema to 0.1.110

snuba/datasets/configuration/events_analytics_platform/storages/spans_num_attrs.yaml, snuba/datasets/configuration/events_analytics_platform/storages/spans_str_attrs.yaml, tests/web/rpc/test_trace_item_attribute_list.py, tests/web/rpc/test_trace_item_attribute_values.py
We finally got the migrations through, can re-re-enable the tests.
=> fix(eap): re-enable tests and entities now that migrations ran

snuba/web/rpc/common.py
This table is truncated to `toStartOfDay` and has weird artifacts around timezones, just truncate to a whole 48 hour span.
=> fix(eap): make attr table truncate even more permissive

snuba/web/delete_query.py, tests/test_search_issues_api.py
Makes the default `storage_deletes_enabled=1`. 
Sentry tests should be testing against this feature. In production all regions except S4S have this set to `0`. Additionally, only the `search_issues` dataset has deletes enabled in the storage configuration.
=> (snuba-deletes): storage_deletes_enabled default enabled

snuba/utils/streams/topics.py
Doing this separately so we can roll it out independently of the actual consumer: https://github.com/getsentry/snuba/pull/6216
This will be rolled out after the schema is published https://github.com/getsentry/sentry-kafka-schemas/pull/333
=> feat(eap): Add mutations topic to Snuba

snuba/snuba_migrations/events_analytics_platform/0015_span_attribute_table_namespaced.py
We need to be able to disambiguate things sentry sets (like name) from things user set (like `setAttribute("name")`) - this facilitates that in the materialized view
=> chore(eap): add a migration to namespace sentry tags

rust_snuba/src/processors/eap_spans.rs, rust_snuba/src/processors/snapshots/rust_snuba__processors__eap_spans__tests__serialization.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-spans-EAPSpansMessageProcessor-snuba-spans__1__basic_span.json.snap, snuba/web/rpc/common.py, tests/web/rpc/test_common.py, tests/web/rpc/test_span_samples.py
If you don't namespace things before inserting, it causes problems where `sentry_tags` can overwrite data a user sends.
There should be minimal performance impact, because `sentry.` will be compressed out.
=> feat(eap): prefix sentry_tags with sentry.

rust_snuba/src/processors/eap_spans.rs, rust_snuba/src/processors/snapshots/rust_snuba__processors__eap_spans__tests__serialization.snap
Adds support for the new `server_sample_rate` measurement on spans and includes
it in computing the final sampling factor and weight. This allows us to
extrapolate span metrics correctly in organizations that have dynamic sampling
enabled.
This also rounds the sampling factor to a precision of 10^-9 to avoid floating
point errors in the multiplication. For example, without the test using sample
rates of _10%_ and _20%_ respectively already shows floating point error.
In a follow-up, we might revise the schema and move these sample rates into
`span.data`.
See https://github.com/getsentry/relay/pull/4063
See https://github.com/getsentry/relay/issues/4038
=> feat(eap): Include server-side sample rates in sampling weight

snuba/query/processors/physical/clickhouse_settings_override.py, tests/query/processors/test_clickhouse_settings_override.py
We want to optimize things in EAP by setting clickhouse overrides per-endpoint, this facilitates that
=> feat: do not clobber existing overrides with new overrides

snuba/web/db_query.py, tests/test_snql_api.py, tests/web/test_db_query.py
Upon getting a request to increase the thresholds for a customer, one of the things we need to figure out is which storage. This PR surfaces the `StorageKey` to allow easier querying using SnubaAdmin's QueryLog
=> Surface storage key for capacity management

tests/clickhouse/optimize/test_optimize_tracker.py
Lately, we have been seeing flakiness in optimize tests. For example, [this](https://github.com/getsentry/snuba/actions/runs/11061448936/job/30734331050) run failed which has nothing to do with optimize job. We have plans to take deeper look into optimize job but until that happens, this PR disables the flaky test.
=> Disable flaky optimize test until optimize job is fixed

tests/web/rpc/v1alpha/test_trace_item_attribute_list.py, tests/web/rpc/v1alpha/test_trace_item_attribute_values.py
The test appears to be failing because it is now the end of month and the tests rely on things like (TODAY + 1). Changes base time so that we never exceed the number of days in the month.
=> fix: Broken tests in CI

snuba/web/rpc/common/eap_execute.py, snuba/web/rpc/v1alpha/timeseries/timeseries.py, tests/web/rpc/v1alpha/test_timeseries_api.py
This is a performance optimization that removes most of the overhead of running multiple concurrent clickhouse queries.
Benchmarked against `SNUBA_SETTINGS=test pytest -vv tests/web/rpc/test_timeseries_api.py::TestTimeSeriesApi::test_query_caching`
before:
`took 688ms to run timeseries_query`
after:
`took 102ms to run timeseries_query`
This is a request that doesn't hit query cache at all and does ~25 requests.
=> feat: add a way of running EAP queries async with a thread pool

tests/clickhouse/optimize/test_optimize_scheduler.py, tests/clickhouse/optimize/test_optimize_tracker.py
This is constantly failing around 5pm PST or later and blocks PRs and deploys. We should get a better long term fix, but this is to unblock deploys.
=> ref(ci): test_run_optimize_with_ongoing_merges as xfail

gocd/templates/bash/deploy.sh
Reverts getsentry/snuba#6359
Consumer isn't rolling out properly for some reason in GoCD and blocking pipeline
=> Revert "fix(gocd): Add snuba-eap-mutations consumer to US"

snuba/web/rpc/common/common.py
The touched logic crashes on Oct 1st, as it tries to construct a
datetime such as Oct 0th.
=> fix(eap): Do not crash on the first of the month

gocd/templates/bash/deploy.sh
Reverts getsentry/snuba#6364
In order to roll out #6366 , we need to... deploy the eap consumer
i wish we could just exclude it from our deployment health checks instead, will check that next
=> Revert "Revert "fix(gocd): Add snuba-eap-mutations consumer to US""

snuba/web/rpc/v1alpha/trace_item_attribute_list.py, tests/web/rpc/v1alpha/test_trace_item_attribute_list.py
We'd like to make sure rate limits / etc are run for all EAP endpoints, this migrates the last remaining one.
=> feat(eap): Go through snuba query pipeline for attributes list

requirements.txt
This adds the devservices cli tool to be used once the venv is activated. The devservices [configurations](https://github.com/getsentry/snuba/pull/6323) are already added to the snuba repo so you should be able to use it as soon as you install the new cli tool. 
We are also offering a binary to be used for a system installation of devservices (installation instructions in the README [here](https://github.com/getsentry/devservices)). However, use this at your own risk given that we're changing things pretty constantly and bumping/downgrading versions isn't quite as easy as pinning to a version in the venv.
=> feat(devservices): Add devservices cli tool

snuba/cli/jobs.py, snuba/manual_jobs/__init__.py, snuba/manual_jobs/job_loader.py, snuba/manual_jobs/runner.py, snuba/redis.py, snuba/settings/__init__.py, snuba/settings/settings_test.py, tests/cli/test_jobs.py, tests/manual_jobs/test_job.py
This is #6332 unchanged, but now Redis clusters have been defined in all SaaS environments (https://github.com/getsentry/ops/pull/12293 deployed everywhere)
=> Revert "Revert "feat(job-runner): track job status (#6332)""

gocd/templates/bash/deploy.sh
This will make sure the profiled consumer can grab the Snuba image
=> fix: Add profiled spans consumer to GoCD deployment

mypy.ini, scripts/copy_tables.py, snuba/clickhouse/optimize/optimize_scheduler.py, snuba/datasets/cdc/cdcprocessors.py, snuba/datasets/events_format.py, snuba/migrations/check_dangerous.py, snuba/migrations/connect.py, snuba/migrations/group_loader.py, snuba/query/processors/physical/mapping_optimizer.py, snuba/util.py, tests/query/processors/test_mapping_optimizer.py
When an escape character is used in a string, Python 3.12 will now show a SyntaxWarning.
See here: https://docs.python.org/dev/whatsnew/3.12.html#other-language-changes
This was causing mypy to fail to run. Fix this bug across the codebase.
Also exclude the rust_snuba files (which suffer from this problem) since they are autogenerated.
=> fix: Fix SyntaxWarning in Python 3.12

snuba/cli/jobs.py, snuba/manual_jobs/__init__.py, snuba/manual_jobs/job_loader.py, snuba/manual_jobs/runner.py, snuba/manual_jobs/toy_job.py, tests/cli/test_jobs.py, tests/manual_jobs/test_job.py
Removing the dry_run option as we don't see it providing a ton of value, but it creates a lot of branching that makes the code less readable
=> cleanup(job-runner): remove dry_run

snuba/admin/auth_roles.py, tests/admin/test_authorization.py
Because otherwise an SnS engineer will have to manually run it every time we have a capman issue
=> chore(admin): Allow product tools role to use querylog tool

snuba/admin/clickhouse/system_queries.py
CREATE TABLE queries usually have dots and backticks in them. Allow those characters
in the regex so they can be run in sudo mode.
=> fix(admin): Allow dots and backticks in system queries

snuba/datasets/configuration/replays/entities/replays.yaml, snuba/datasets/configuration/replays/storages/replays.yaml
Needed for https://github.com/getsentry/sentry/issues/78531. Sentry tagstore makes this query:
```
MATCH (replays SAMPLE 1.0) SELECT count() AS `count` BY
tags_key WHERE timestamp >= toDateTime('2024-08-12T00:00:00') AND
timestamp < toDateTime('2024-08-13T23:59:59') AND project_id IN
tuple(1) AND project_id IN tuple(1) ORDER BY count DESC LIMIT 1000
```
And right now we're getting http response `'Validation failed for entity replays: Tag keys (tags_key) not resolved'`.
Uses [entities/search_issues.yaml](https://github.com/getsentry/snuba/blob/2544b8e87d9693bc8ffe9feadf5b6809e1cf71d8/snuba/datasets/configuration/issues/entities/search_issues.yaml#L1-L1) and [storages/search_issues.yaml](https://github.com/getsentry/snuba/blob/2544b8e87d9693bc8ffe9feadf5b6809e1cf71d8/snuba/datasets/configura …
=> feat(replay): add arrayJoin translation_mappers for tags.key and value

snuba/web/db_query.py
This is causing us to not be able to raise the thread limit above 10, remove it since all storages have allocation policies now
=> feat(capman): remove legacy cap on threads

snuba/admin/static/api_client.tsx, snuba/admin/static/manual_jobs/index.tsx, snuba/admin/views.py
This wires job execution into snuba admin. Tested locally
https://github.com/user-attachments/assets/7f56f035-faf0-4311-bbb6-c7e3cb2c4725
Back-end logs:
```
127.0.0.1 - - [03/Oct/2024:15:05:09 -0700] "GET /static/snuba.svg HTTP/1.1" 304 215 "http://localhost:1219/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0"
{"module": "snuba.admin.views", "user": "AdminUser(email='unknown', id='unknown', roles=[Role(name='MigrationsReader', actions={<snuba.admin.auth_roles.ExecuteNoneAction object at 0x104ab4ad0>}), Role(name='TestMigrationsExecutor', actions={<snuba.admin.auth_roles.ExecuteAllAction object at 0x104ab5150>}), Role(name='SearchIssuesExecutor', actions={<snuba.admin.auth_roles.ExecuteNonBlockingAction …
```
=> feat(job-runner): run job from snuba admin

snuba/admin/static/utils/execute_button.tsx
In the system queries tool i was getting this error message 
and you can only see the actual error in console
my change makes it show the error in the alert
=> fix: better error message in admin system query

devservices/config.yml
Fixes a small bug introduced in #6350 where a remote was defined for a non remote dependency.
=> fix(devservices): Fixing devservices config

snuba/datasets/configuration/issues/storages/search_issues.yaml
We can delete by `group_id` now and many have above `1000` events. Might need to raise it even more later, but this is to allow testing deleting larger groups in S4S (the only region deletes are enabled in currently)
=> ref(deletes): increase max rows to 100000

snuba/admin/clickhouse/database_clusters.py, snuba/admin/static/database_clusters/index.tsx, snuba/admin/static/database_clusters/types.tsx
Removing the query node column and replacing the distributed node column with a node type column since the query node column was not actually showing if the node was a query node.
=> fix(database-clusters): Remove Query Node column

snuba/admin/clickhouse/tracing.py, snuba/admin/static/tracing/query_display.tsx, snuba/admin/static/tracing/types.tsx, tests/admin/clickhouse/test_tracing.py
Show query results, but remove everything that is not a number. That's
practically getting rid of all PII. Discussed beforehand with Evan and
Matt.
We need this to evaluate query correctness in the context of EAP
mutability. How do we know if our percentiles are correct?
But also more generally: If you're comparing two queries for
performance, and the output is wrong in one of them, how are you going
to notice that your entire benchmark is garbage?
=> feat(admin): Show data in clickhouse tracing tool

snuba/admin/clickhouse/database_clusters.py
Fixes a bug caused by lack of thread safety causing a 500
=> fix(database-clusters): Use a lock when creating connection

snuba/admin/clickhouse/tracing.py, snuba/admin/static/tracing/query_display.tsx
Python will encode NaN into JSON, even though it's not actually valid JSON.
This will cause the frontend to error out. Handle this case for the admin tool.
=> fix(admin): Handle NaN in admin results

snuba/web/rpc/__init__.py, snuba/web/views.py, tests/web/rpc/test_rpc_handler.py
In #6402 I asked to put as [little of the error handling logic into the flask layer as possible](https://github.com/getsentry/snuba/pull/6402#discussion_r1794202135) but it went too far in the other direction and bled the flask object into the RPC code (which was not the intention).
This PR removes the flask `Response` object out of the RPC code
=> fix(eap): remove flask stuff from rpc

rust_snuba/src/mutations/clickhouse.rs
This adds a metric to track how many rows are being inserted into
the new_data table, which corresponds to how many events are being
mutated.
=> ref(eap): Add a metric for number of rows being mutated

gocd/templates/bash/saas-sentry-health-check.sh
Hopefully this makes it less likely that we have to shut down all of EAP
to unblock deploys.
=> chore(gocd): Exclude all EAP services from snuba healthchecks

rust_snuba/src/mutations/clickhouse.rs, rust_snuba/src/strategies/clickhouse/batch.rs
Mutations consumer is currently encountering 404 from clickhouse, but we
don't know why. Print response body.
In the main consumer: In the past people were confused by the error message and didn't realize that it comes from clickhouse
=> chore(consumer): Improve debugging output on bad response

snuba/utils/health_info.py, tests/cli/test_health.py, tests/utils/test_check_clickhouse.py, tests/web/test_views.py
This is a follow up item for inc-894, where a API pod landed on a bad node with no clickhouse connection. Because it was not configured with a thorough healthcheck, the pod stayed and served 5XX to all requests.
Adds a connection check to see if any clickhouse query node is operable. Fails the healthcheck if all query nodes are inoperable, as it likely indicates connection error with the host, so k8 can rotate the pod. Renames the previous check_clickhouse function to `check_all_tables_present` to distinguish the 2.
=> feat(api): Add a clickhouse connection sanity check to api healthcheck

snuba/web/rpc/v1/endpoint_trace_item_table.py, tests/web/rpc/v1/test_endpoint_trace_item_table.py
Protobuf was setting this value to 0 by default, making it return no values if not specified in the request payload
=> fix(eap): add a default row limit if not specified

snuba/subscriptions/scheduler.py
When we schedule subscription tasks, we convert a Unix timestamp from the commit log to a datetime object, so a scheduled message looks like this
```
{"timestamp":"2024-10-15T11:10:00","entity":"eap_spans","task":{"data":{"project_id":1,"time_window":3600,"resolution":60,"query":"MATCH (eap_spans) SELECT count() AS `count` WHERE project_id IN array(1) AND organization_id = 1"}},"tick_upper_offset":4679}
```
`fromtimestamp` creates naive datetime objects using system timezone,
so EDT for me locally, but we use it as a utc timestamp in our clickhouse query
```
SELECT (count() AS _snuba_count) FROM eap_spans_local WHERE in((project_id AS _snuba_project_id), [1]) AND equals((organization_id AS _snuba_organization_id), 1) AND equals(project_id, 1) AND greaterOrEquals(_sort_timestamp, …
```
=> fix(subscriptions): Make scheduled subscriptions utc timezone

snuba/web/views.py
We have allocation policies set in place now, so we can remove the simple rate-limiter.
=> ref(deletes): remove simple ratelimit

snuba/admin/static/utils/execute_button.tsx
error messages in the snuba admin tool haven't been showing up properly on some of the tools. my previous pr #6390 tried to address this, you can see it for an example of the issue.
unfortunately this change fixed the error messages on "system query" tool but broke them on "production query tool".
I have since found out this is because the error messages come from the execute_button component which is used across many different pages, and receives a variety of different looking error variables as input. Related to #6280.
In this PR I updated the logic again and verified across all pages that use the execute button that the error display looks good.
=> fix: fix broken admin error message displays

snuba/datasets/configuration/json_schema.py, snuba/datasets/configuration/utils.py, tests/datasets/configuration/column_validation_entity.yaml
This is a follow up of PR https://github.com/getsentry/snuba/pull/6416 and adds the support for the `tuple` type to be used in the `yaml` configurations.
=> feat: add support for tuple type to the json schema

snuba/manual_jobs/__init__.py, snuba/manual_jobs/job_status.py, snuba/manual_jobs/redis.py, snuba/manual_jobs/runner.py, tests/manual_jobs/test_job.py, tests/manual_jobs/test_job_statuses.py
https://getsentry.atlassian.net/jira/software/c/projects/SNS/boards/147?selectedIssue=SNS-2871
At times we will want to execute long-running ClickHouse jobs that don’t fit neatly into the migrations system; either they only run in a single environment, or we don’t want to block later migrations on them finishing. This PR supports users to create job types that can run asynchronously.
=> feat(job-runner): async job functionality

snuba/web/rpc/__init__.py, snuba/web/rpc/v1/endpoint_trace_item_table.py, snuba/web/rpc/v1alpha/span_samples.py
The execute method provides built in observability. It should not be overridden
=> fix(eap): make execute method final

rust_snuba/src/mutations/factory.rs
This value was set to 1 day, but we'd like to see some mutations in Clickhouse sooner than that so we can perform some analysis. Lower to 12 hours.
=> ref: Lower mutations synchronizer's sleep

snuba/querylog/__init__.py, snuba/querylog/query_metadata.py, snuba/request/__init__.py, snuba/request/validation.py, snuba/web/rpc/common/eap_execute.py, snuba/web/rpc/v1/endpoint_trace_item_table.py, snuba/web/rpc/v1alpha/span_samples.py, snuba/web/rpc/v1alpha/trace_item_attribute_list.py, snuba/web/rpc/v1alpha/trace_item_attribute_values.py, tests/datasets/test_querylog_processor.py, tests/pipeline/test_entity_processing_stage.py, tests/pipeline/test_entity_processing_stage_composite.py, tests/pipeline/test_execution_stage.py, tests/web/test_transform_names.py
There are two ways to stringify a UUID: `str(uuid)`, and `uuid.hex` -- they produce different output, the first one is hyphenated, the second one isn't.
It seems we use both at the same time, and the consumer can only deal with the latter.
But also, sometimes we do this: `str(uuid.uuid4)`
That always produces something like `'<function uuid4 at 0x100c39620>'`,
which is total garbage but since everything is string-typed, mypy
doesn't complain.
Refactor everything to use UUID types and only convert to string on
serialization.
=> ref(querylog): Produce request ID consistently

rust_snuba/src/mutations/factory.rs
The current EAP consumer lags behind 24 + 12 hours.
=> fix(eap): Bump mutations consumer latency significantly

snuba/snuba_migrations/events_analytics_platform/0016_spans_v2.py
- Change the partition key to include `_sort_timestamp` so we can use `ttl_only_drop_parts` and not go through TTLDelete merges
- This forces us to recreate a new table
- Fix `sample_weight` type
- Change codecs as suggested in our call with Altinity
- Change `duration_ms` and `exclusive_time_ms` to be microseconds stored into a `UInt64` column
=> feat(eap-spans): Add a new schema for spans

snuba/admin/clickhouse/system_queries.py, tests/admin/test_system_queries.py
This allows OPTIMIZE queries to be run in the snuba admin when using sudo
mode. This can be useful to potentially resolve tables/partitions in bad
states.
=> fix(admin): Allow OPTIMIZE queries in sudo mode

snuba/admin/package.json, snuba/admin/yarn.lock
Bumps braces from 3.0.2 to 3.0.3.
https://github.com/getsentry/snuba/security/dependabot/53
=> chore(deps): bump braces from 3.0.2 to 3.0.3 in /snuba/admin

rust_snuba/Cargo.lock
https://github.com/getsentry/snuba/security/dependabot/58
=> chore(deps): bump openssl from 0.10.64 to 0.10.68 in /rust_snuba

snuba/manual_jobs/redis.py, snuba/manual_jobs/runner.py, tests/manual_jobs/test_record_job_start.py
store a record of when a job started executing so that we can support timeouts
=> feat(job-runner): record job's start timestamp to support timeouts

snuba/datasets/configuration/issues/storages/search_issues.yaml, snuba/datasets/configuration/json_schema.py, snuba/datasets/deletion_settings.py, snuba/datasets/storage.py, snuba/utils/streams/topics.py, snuba/web/bulk_delete_query.py, snuba/web/delete_query.py, tests/web/test_bulk_delete_query.py, tests/web/test_max_rows_enforcer.py
**context**
The current pipeline we have for deleting data (via lightweight deletes) is an API endpoint that executes the query directly. `DELETE` requests are technically synchronous at the moment due to the ClickHouse version we are on (the `lightweight_delete_mutations_sync` parameter exist in newer version).
**problem**
We'd like to keep the number of concurrent `DELETE` requests to a minimum since they add an increased load to ClickHouse. Though the number of rows being deleted does have an effect on load, even a delete that deletes a few rows can have a significant enough effect because it's still a mutation (under the hood the `DELETE FROM` becomes an `UPDATE`). 
**batched deletes**
In order to scale we are adding a consumer that will batch up DELETE queries so that we have fewer …
=> ref(bulk-deletes): bulk delete query path and producer

requirements.txt
https://github.com/getsentry/snuba/security/dependabot/52
=> chore(deps) bump werkzeug from 2.2.3 to 3.0.5

snuba/web/rpc/v1/endpoint_trace_item_table.py, tests/web/rpc/v1/test_endpoint_trace_item_table.py
protobuf sets the label as an empty string by default which is truthy in python. hence we were not actually bubbling up labels correctly. this fixes the bug
=> fix(EAP): fix bug with unassigned labels

devservices/config.yml, requirements.txt
This allows devservices to use a shared version of redis/kafka defined here:
https://github.com/getsentry/sentry-shared-kafka
https://github.com/getsentry/sentry-shared-redis
This allows relay/snuba/sentry to use the same redis/kafka configurations
It also adds a containerized mode to the config, which sentry will need in order to run snuba devserver inside a container with the lastest snuba image
=> feat(devservices): Add shared redis/kafka and containerized mode for snuba

snuba/web/rpc/common/common.py, snuba/web/rpc/v1/endpoint_time_series.py, snuba/web/rpc/v1/endpoint_trace_item_table.py, tests/web/rpc/v1/test_endpoint_time_series.py, tests/web/rpc/v1/test_endpoint_trace_item_table.py
This PR implements the basics of the timeseries API.
Supported:
* Aggregations on all attributes
* filters
* groupby
* zerofilling nonexistent data
To come in future PRs:
* Sample count
* extrapolation
=> feat(eap): Timeseries V1 RPC

snuba/admin/yarn.lock
Fixes a [moderate](https://github.com/getsentry/snuba/security/dependabot/59) severity alert on micromatch. Despite making several attempts to resolve CI failures on dependabot's PR https://github.com/getsentry/snuba/pull/6461, it did not complete CI runs. So, trying out this manual PR.
=> chore(deps): bump micromatch from 4.0.4 to 4.0.8 in /snuba/admin

.github/workflows/dependency-review.yml
`actions/dependency-review-action` released a [latest version 4.4.0](https://github.com/actions/dependency-review-action/releases/tag/v4.4.0) and this PR consumes that version. Dependabot created https://github.com/getsentry/snuba/pull/6480 but it does not seem to pass CI. Trying this PR.
=> build(deps): bump actions/dependency-review-action from 3.1.0 to 4.4.0

snuba/admin/clickhouse/system_queries.py, tests/admin/test_system_queries.py
Instead of using regex for validating system queries, we can use AST/Query Tree output from CH EXPLAIN to check for dangerous queries. This approach is more maintainable and in the future when the new CH analyzer is no longer experimental, we can switch fully to using the Query Tree.
=> feat(snuba-admin): Use AST and Query Tree generated by EXPLAIN query for system query validation

snuba/pipeline/stages/query_execution.py, snuba/web/rpc/v1/endpoint_trace_item_table.py, tests/web/rpc/v1/test_endpoint_trace_item_table.py
Using the wrong value for selected expression name, also aggregations sometimes don't have a label, we can just inherit the column name
=> fix(eap): fix table aliasing

.vscode/settings.json, snuba/admin/static/rpc_endpoints/index.tsx, snuba/admin/static/rpc_endpoints/styles.ts, snuba/admin/static/rpc_endpoints/trace_formatter.tsx, snuba/admin/static/rpc_endpoints/types.tsx, snuba/admin/static/rpc_endpoints/utils.ts, snuba/admin/static/tests/rpc_enpoints/trace_formatter.test.tsx, snuba/web/rpc/common/debug_info.py
This change enhances the RPC endpoints admin interface by adding trace log visualization capabilities. Key changes include:
- Add new trace log formatter with syntax highlighting and improved readability
- Introduce a toggle switch to alternate between query metadata and trace logs view
- Add new types for better TypeScript support
- Improve styling of response containers with proper scrolling
- Reset debug mode when switching endpoints
- Add proper monospace font styling for trace logs
The trace log visualization includes:
- Color-coded components (host, thread ID, query ID, log levels)
- Text wrapping for better readability
- Proper HTML escaping for security
This enhancement will help to better understand query execution and debug issues more effectively on EAP endpoints.
=> feat(admin): Add trace log visualization to RPC endpoints

requirements.txt, snuba/web/rpc/v1/endpoint_trace_item_attribute_names.py, tests/web/rpc/v1/test_endpoint_trace_item_attribute_names.py
This PR implements the endpoint for TraceItemAttributeNames. For context, please see [this diagram](https://www.notion.so/sentry/Qu-EAP-Querying-Events-Analytics-Platform-76629acc212b4ac486c63e7979f16076?pvs=4#66feb9128c2b4752a7921e47c0cb20fc) "attribute names" in green at the bottom. Also see [this ticket](https://github.com/getsentry/projects/issues/293).
This API allows you to query for the names of all attributes attached to spans for a given project and dates. The interface definition is here https://github.com/getsentry/sentry-protos/blob/main/proto/sentry_protos/snuba/v1/endpoint_trace_item_attributes.proto#L12-L28
Its implemented in the following way at a high-level
1. receive a request from the user
2. convert that request into a `SnubaRequest`. This is an existing object we use …
=> feat(eap): AttributeNames "autocomplete" v1 API

.vscode/extensions.json, .vscode/settings.json
Changes
1. The following vscode settings
```
"python.linting.mypyEnabled": true,
"python.linting.flake8Enabled": true,
"python.formatting.provider": "black",
```
have been deprecated in favor of using the extensions, [see here](https://github.com/microsoft/vscode-python/wiki/Migration-to-Python-Tools-Extensions#linting-and-formatting-settings-deprecation). I don't think they even do anything anymore. So I removed them and added their corresponding extensions to the workspace extension recommendations.
2. `python.pythonPath` settings has been deprecated and I'm pretty sure it doesnt do anything anymore. `python.defaultInterpreterPath` should be used instead so I replaced it with that. See here https://devblogs.microsoft.com/python/python-in-visual-studio-code-july-2021-release/#selecting-a- …
=> fix(vscode): update deprecated vscode workspace settings

requirements.txt, snuba/utils/streams/topics.py, snuba/web/bulk_delete_query.py, tests/web/test_bulk_delete_query.py
Updating for consistency with naming conventions, will need https://github.com/getsentry/sentry-kafka-schemas/pull/347 before we can merge this PR (and update it with the right version)
=> ref(deletes): search-issues -> generic-events

.github/workflows/labeler.yml
https://github.com/getsentry/snuba/commit/b8a94dbc73147ea8800ab5fcdb2c3c1d110577d8 reverted the `labeler` to `v4`. To update the `labeler` to `v5` (originally intended to be done through https://github.com/getsentry/snuba/pull/6496), just updating the version to `v5` is not sufficient. https://github.com/actions/labeler/issues/628 recommends to add the `checkout` action before updating the labeler to `v5`.
=> Checkout labeler code before updating it to v5

snuba/manual_jobs/redis.py
If there are no jobs, we don't need to fetch statuses from redis. This fixes the bug where `_redis_client.mget` errors because the keys are empty
=> fix(job-runner): handle the case of no job runs

snuba/web/bulk_delete_query.py, snuba/web/delete_query.py
Adds better typing to the delete pipeline as well separates some code out from https://github.com/getsentry/snuba/pull/6510. To avoid circular imports, it's easier to have `bulk_delete_query` file almost import from `delete_query`, and never have `delete_query` import from `bulk_delete_query` (where the ConditionsType was before)
=> ref(deletes): add ConditionsType

snuba/admin/clickhouse/profile_events.py, snuba/admin/views.py, snuba/utils/constants.py, tests/clickhouse/test_profile_events.py
This PR makes the profile events gathering more robust while reducing the maximum wait time from 30 seconds to ~23 seconds in worst-case scenarios.
- Moving profile events logic to a dedicated module (snuba/admin/clickhouse/profile_events.py)
- Implementing exponential backoff for polling profile events with configurable limits
- Replaced fixed 30 attempts with 1-second delays with an exponential backoff strategy
- Added configuration constants PROFILE_EVENTS_MAX_ATTEMPTS (4) and PROFILE_EVENTS_MAX_WAIT_SECONDS (16)
=> refactor(profile events): Improve profile events gathering with exponential backoff

snuba/web/rpc/common/common.py, tests/web/rpc/test_common.py, tests/web/rpc/v1/test_endpoint_trace_item_table.py
This PR fixes [this bug](https://github.com/getsentry/projects/issues/363)
The test in the PR successfully reproduce the bug, and began passing after my change.
The bug was caused because one of the SelectedColumns in the query object looked like this
```
CAST(attr_num['attr_num[foo]'] AS attr_num[foo],'Int64')
```
this caused an issue later on at `converters[column_name]` because there is only a converter for `attr_num[foo]` not for `CAST(attr_num['attr_num[foo]'] AS attr_num[foo], 'Int64')`.
My change moved the alias so the SelectedColumn now looks like
```
CAST(attr_num['attr_num[foo]'], 'Int64') AS attr_num[foo]
```
and bug fixed
=> fix(eap-api): fix TraceItemTable aliasing bug

snuba/admin/clickhouse/common.py
When the Discover storage is queried in the admin tool, it returns an error saying that the
given node is not valid. Add more data to try and understand the underlying cause of this.
=> ref(admin): Add debugging for Discover bug

tests/web/rpc/v1/test_endpoint_trace_item_attribute_names.py
The bug:
I was querying for the attributes and they look something like this
```
a_tag_1
a_tag_2
...
a_tag_30
http.status
sentry.environment
...
```
The `a_tag` attributes I created and know where they're coming from. The others like `http.status` idk where they come from, and it turns out that they will be different on the local machine and in CI. I hard coded them to what they are on my local machine but they were different in CI sometimes which caused the tests to fail.
The way previous tests handled this was only validating the first 10
```
a_tag_1
...
a_tag_10
```
so they never encountered the changing attributes like `http.status`. But I didnt like this too much since its ignoring a lot of the other results (like 11 through 30).
I decided to solve the bug by validating only all the …
=> fix: flakey test for EndpointTraceItemAttributeNames

docs-requirements.txt, requirements.txt, snuba/web/views.py
The updated version of the SDK sets the transaction name with a different API.
Update the code to properly set the tags and transaction name.
=> fix(sdk): Fix transaction name with new Sentry SDK

snuba/admin/clickhouse/common.py
The discover storage has a different configuration from the other storages, since
it's a merge table. Instead of silently skipping nodes, attempt to connect
and log the resulting error (if any).
=> fix(admin): Log more data when dealing with discover storage

rust_snuba/src/processors/eap_spans.rs
Using numeric casting, we always round down which leads to the sampling weight being calculated less accurately. For example, a sample rate of 0.16666666666666666 results in a sampling weight of 5 instead of 6.
=> Fix sampling weight calculation

snuba/query/allocation_policies/bytes_scanned_rejecting_policy.py, snuba/query/allocation_policies/concurrent_rate_limit.py, snuba/query/allocation_policies/cross_org.py, snuba/query/allocation_policies/per_referrer.py, tests/query/allocation_policies/test_allocation_policy_base.py, tests/query/allocation_policies/test_bytes_scanned_rejecting_policy.py, tests/query/allocation_policies/test_bytes_scanned_window_allocation_policy.py, tests/query/allocation_policies/test_concurrent_rate_limit_policy.py, tests/query/allocation_policies/test_cross_org_policy.py, tests/query/allocation_policies/test_per_referrer.py
Snuba payload should correctly reflect that rejected queries are ran with 0 threads
=> [CapMan visibility] rejected queries are ran with 0 threads

devservices/config.yml
We should be exposing ports only to localhost as a security measure.
=> feat(devservices): Only expose ports to localhost

snuba/web/views.py, tests/web/test_bulk_delete_query.py
Adding a temporary runtime config (`use_bulk_deletes`) to allow for delete queries to go through the bulk delete pipeline, until we are ready to fully move over to using it. 
I choose a runtime config because I didn't want sentry to have to be aware of which implementation was used (bulk deletes or not). 
We should only enable this when we have the consumers running in S4S
=> ref(deletes): add use_bulk_deletes runtime config

gocd/templates/bash/deploy.sh
replicas are still set to `0` right now, and will only be enabled in S4S in the near future. 
ops PR to set replicas to `1` for S4S: https://github.com/getsentry/ops/pull/12839
=> ref(deletes): add lw-deletions-search-issues-consumer to deploy.sh

snuba/datasets/configuration/events_analytics_platform/storages/eap_spans.yaml
This will enable ClickHouse to split queries between all the replicas of a shard.
=> chore(eap-spans): Increase the number of replicas to scan in parallel

snuba/cli/lw_deletions_consumer.py
Fixing a dumb mistake - the `group_instance_id` was set to the `consumer_group` and because of that we got the following error
`
KafkaError{code=_FATAL,val=-150,str="Fatal error: Broker: Static consumer fenced by other consumer with same group.instance.id: Fatal consumer error: Broker: Static consumer fenced by other consumer with same group.instance.id"}
`
We actually don't want to set the `group_instance_id` at all but I've added it to the consumer so we can in the future (and for consistency with the other consumer cli)
=> fix: dont set group.instance.id incorrectly

snuba/lw_deletions/strategy.py
`max_batch_time` in the batch step calls for seconds, not milliseconds.
=> fix: convert max_batch_time seconds

requirements.txt, snuba/subscriptions/data.py, snuba/subscriptions/rpc_helpers.py, snuba/subscriptions/subscription.py, snuba/web/rpc/v1/create_subscription.py, tests/web/rpc/v1/test_create_subscription.py
This PR adds the CreateSubscription RPC endpoint. To create an RPC subscription we need to:
1. Create an RPC subscription object from the CreateSubscription protobuf
2. Serialize the request (to put it into redis)
3. Validate it
4. Build it & run it before saving
It builds and runs subscription request outside the RPCSubscriptionData class
for now so that we don't have to update the entire subscription pipeline to use both
SnubaRequest and TimeseriesRequest types.
=> feat(subscriptions): Add a create subscription rpc endpoint

requirements.txt
This change bumps the new devservices library to the latest version so snuba can make use of the newest features and bug fixes devservices has to offer. https://github.com/getsentry/devservices/releases/tag/1.0.3
=> chore(devservices): Bumping the version of devservices to latest

snuba/clickhouse/optimize/optimize.py
For easier observability, and because we want to see if oldest parts take the longest consistently, log out which partitions take how long in optimize
=> log(optimize): after optimize, log how long it took w/partition

snuba/migrations/operations.py, snuba/snuba_migrations/events_analytics_platform/0014_span_attribute_table_smaller.py
**context**
When testing out the newest clickhouse version 24.3, it was found that this clickhouse change https://github.com/ClickHouse/ClickHouse/pull/61399, meant that the `0014_span_attribute_table_smaller` migration failed for version `24.3`. 
The `allow_suspicious_primary_key` setting allows us to ignore this, but we don't want to enable it everywhere because we don't want future tables to be created incorrectly. 
I'm editing a past migration so that the setting is only used this particular migration, which shouldn't matter much since this table gets dropped in [`0018_drop_unused_span_tables`](https://github.com/getsentry/snuba/blob/0293a3988d56cad70659d2d88cbff4808f6c9783/snuba/snuba_migrations/events_analytics_platform/0018_drop_unused_span_tables.py#L23). 
This will unblock …
=> ref(clickhouse-24.3): allow_suspicious_primary_key for eap migration

.github/workflows/ci.yml, snuba/clusters/cluster.py, snuba/migrations/clickhouse.py, tests/admin/test_api.py
**clickhouse versions of note:**
* ~`22.8.15.25`: is still used in some [test clusters](https://github.com/getsentry/ops/blob/01c48827f96427e2a2858adb70ff530705ec2d01/salt/pillar/clickhouse/sentry-test-region/snuba-metrics.sls#L3), can update this to be higher once confirmed those test regions aren't needed~
* ~`23.3.19.33`: is still used in [sentry development](https://github.com/getsentry/sentry/blob/master/src/sentry/conf/server.py#L2324), should probably be updated~
* `23.8.11.29`: latest version used for all production clusters and [self-hosted](https://github.com/getsentry/self-hosted/blob/3cf323843ab9e63515bd2816a426bd5116324834/docker-compose.yml#L178) and [sentry development](https://github.com/getsentry/sentry/blob/65fcca934b0604fe65149f12ec648c030b71b6e0/src/sentry/conf/server.p …
=> ref(clickhouse): update versions and add 24.3

snuba/query/processors/physical/replaced_groups.py, snuba/query/query_settings.py, tests/datasets/storages/processors/test_replaced_groups.py
The errors table is partitioned by a key that never changes (timestamp of the event). Given that, we can pass [this ClickHouse query setting](https://clickhouse.com/docs/en/guides/replacing-merge-tree#exploiting-partitions-with-replacingmergetree) and hopefully see some reduced load/performance improvement on queries for groups/projects/etc. that have had replacements run on them. Based on the docs, the worst case seems like no improvement
=> perf(final): add flag to skip cross-partition merging on FINAL

docker_entrypoint.sh
Since Heaptrack performs continuous profiling of the Rust consumer, we will want to track the profiler's output for various profiling runs that happen. A profiling run happens for every consumer process that is started.  
Adds timestamp and ensures Heaptrack writes to a formatted file for each profiling run. This will also make analysis easier as we will know which file corresponds to which date and time.
=> feat(profiler): Update formatting of Heaptrack output file

snuba/subscriptions/data.py, tests/subscriptions/__init__.py, tests/subscriptions/test_data.py, tests/web/rpc/v1/test_create_subscription.py
With this change https://github.com/getsentry/snuba/pull/6609 it's no longer 
required to round the timestamps to get back a single time bucket.
=> chore(rpc-subscriptions): Remove timestamp rounding

snuba/admin/clickhouse/system_queries.py, tests/admin/test_system_queries.py
This function is very handy for debugging, since it allows aggregating across all nodes in a single
query.
=> ref(admin): Allow clusterAllReplicas in system queries

.github/workflows/ci.yml
Seeing self-hosted CI fail in numerous places, but it is not clear exactly what is causing these failures as the logs are not explanatory. Thinking it may be due to resource constraints from github runners. Either way, don't want to block CI until this can be investigated properly
In terms of the impact of turning this off, self-hosted e2e tests are still run in the self-hosted repo twice per day which should pick up changes from snuba master
=> ref(ci): Disable self-hosted e2e CI due to resource constraints

scripts/send_spans.py, scripts/spans_oom_reproduce.sh
From initial investigations it has been found that rebalances could potentially be the reason for some of our consumers having high memory usage. Added a script which mimics the behavior. I can also see the increase in memory usage locally. This will make it easier to triage the problem by potentially using memory profiler locally.
The script uses a parameter `-g` optionally to generate spans on the topic. If you need data, then run with that option. It always resets offsets to 0 between re-runs. So if you have enough data on kafka, you do not need to pass the `-g` option.
On my machine, I was able to use up more than 2GB of memory easily.
```shell
./spans_oom_reproduce.sh
GROUP                          TOPIC                          PARTITION  NEW-OFFSET     
spans_group …
```
=> feat(memory): Add script to debug consumer OOM issues

devservices/config.yml
This adds healthchecks to clickhouse and snuba for devservices. This is required because we want devservices to properly understand when a container is healthy/unhealthy to help developers out when encountering issues with their local dev environment.
=> feat(devservices): Add healthchecks to clickhouse and snuba

snuba/web/rpc/common/aggregation.py
Closes https://github.com/getsentry/eap-planning/issues/105
=> feat(eap-api): Use signs in count, average, and sum calculations

snuba/admin/static/rpc_endpoints/exampleRequestTemplates.json
this closes https://github.com/getsentry/eap-planning/issues/98
I added an example request to each of the following endpoints that were missing it. 
I got the example request for each endpoint from one of its unit tests, I tried to pick a basic representative one. Here are all the endpoints I added example requests for, and a link to the test that I got the request from:
* [CreateSubscriptionRequest](https://github.com/getsentry/snuba/blob/b03c40e91c7b10af6d9794b576055eb9a6027b22/tests/subscriptions/test_scheduler_consumer.py#L165)
* [EndpointTraceItemAttributeNames](https://github.com/getsentry/snuba/blob/b03c40e91c7b10af6d9794b576055eb9a6027b22/tests/web/rpc/v1/test_endpoint_trace_item_attribute_names.py#L89)
* [EndpointTimeSeries](https://github.com/getsentry/snuba/blob/b03c40e91c7b10af …
=> fix(admin): add example RPC call for the endpoints missing it

rust_snuba/src/consumer.rs, snuba/cli/rust_consumer.py
Arroyo consumers maintain an in-memory buffer of messages that gets filled every time a new message is polled from rdkafka. Offsets get removed from the buffer when messages are committed. 
The buffer is kept around in order to populate the DLQ topic and replay invalid messages later. 
However, this buffer can grow unbounded since we haven't configured any cap on it. We have a hunch that this is also contributing to memory spikes on Arroyo Rust consumers. 
Add a flag to configure a limit. We seem to already [have the functionality ](https://github.com/getsentry/arroyo/blob/main/rust-arroyo/src/processing/dlq.rs#L413-L421)to actually set it in the DLQ buffer.
=> consumer: Add flag to configure DLQ buffer limit

devservices/config.yml
We decided to move forwards with https for these reasons:
1. devservices should not commit changes and should only care about configuration files in read only mode
2. It is not easy to integrate ssh authentication for CI
3. devservices will prompt for ssh key locally if ssh authentication is not set up
=> feat(devservices): Use https for repo links

.github/workflows/ci.yml
Reverts getsentry/snuba#6620
It looks like this issue was entirely on Github since the CI check is now passing everywhere. So, re-enabling this
=> Revert "ref(ci): Disable self-hosted e2e CI due to resource constraints"

snuba/query/dsl.py, snuba/web/rpc/common/common.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series.py
This closes this ticket https://github.com/getsentry/eap-planning/issues/119
A request to the timeseries endpoint was failing due to its in condition. I was able to reproduce this bug locally and determine that its being caused because arrays and in conditions werent implemented yet. I implemented them and the test it now passing.
=> feat(eap-api): support in conditions in TraceItemFilter

rust_snuba/Cargo.lock, rust_snuba/Cargo.toml
Bump Arroyo dependency to latest
=> chore: Bump Arroyo to 2.19.1

snuba/snuba_migrations/querylog/0006_sorting_key_change.py
Taking over https://github.com/getsentry/snuba/pull/6203 (from @wolandspb) and creating this PR.
Verified that the assertion error below happens locally:
```
File "/Users/meredithaheller/code/snuba/snuba/snuba_migrations/querylog/0006_sorting_key_change.py", line 41, in update_querylog_table
assert new_create_table_statement.count(new_timestamp_type) == 0
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```
=> fix 0006_sorting_key_change migration

snuba/admin/clickhouse/system_queries.py, tests/admin/test_system_queries.py
This function creates a temporary merge table, which is very useful for doing things like querying
across all the different settings tables.
=> ref(admin): Allow merge function in FROM clause

snuba/datasets/configuration/events_analytics_platform/storages/eap_spans.yaml
We'd like to enable this feature, despite being experimental, on this cluster since it would allow us to speed up querying significantly.
The plan is to enable this during LA and choose whether or not we'll keep it in EA or GA later on.
=> chore(eap-spans): Take advantage of parallel reads

.github/file-filters.yml, .github/workflows/ci.yml
This forces relevant sentry tests to run when we change RPC files.
=> fix: run sentry tests when RPC changes

snuba/web/rpc/common/aggregation.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series_extrapolation.py
Quick fix for a bug caused by dividing by 0 when computing reliability
=> fix(eap): Fix divide by 0 bug

rust_snuba/src/config.rs
60 days is a valid retention day, it is also configured in our python processors:
https://github.com/getsentry/ops/blob/8aefb917b846ed052497856da4c55464a925c840/k8s/services/snuba/templates/prod_settings.py.j2#L140
=> fix(consumers): Respect 60 day retention days period

snuba/web/rpc/v1/endpoint_trace_item_attribute_names.py, tests/web/rpc/v1/test_endpoint_trace_item_attribute_names.py
https://github.com/getsentry/projects/issues/376
Need to do this for attribute values API next
=> Implement filter offset for attribute keys API

snuba/utils/health_info.py
Kubernetes tells the old snuba pods to mark itself as unhealthy, so that
envoy stops sending traffic to it.
Snuba reports itself as unhealthy to Sentry.
Gocd checks Sentry for new errors.
Gocd stalls the deployment because there are new errors.
=> chore(api): Do not log healthcheck error if downfile exists

snuba/subscriptions/data.py
We weren't setting the correct referrer, copy it onto the
timeseries request.
=> fix(eap-alerts): Fix subscriptions referrer for eap alerts

rust_snuba/Cargo.lock, rust_snuba/Cargo.toml
Bump to latest version, which includes important DLQ management fixes.
=> chore: Bump Arroyo to 2.19.5

snuba/manual_jobs/scrub_ips_from_spans.py, tests/manual_jobs/test_scrub_ips_from_spans.py
We don't need to check this, just rewrite the column
=> feat(inc984): make mutation condition simpler

requirements.txt
ref: https://github.com/getsentry/relay/issues/4175
=> chore(deps): bump relay from 0.9.2 to 0.9.4

snuba/admin/clickhouse/system_queries.py, tests/admin/test_system_queries.py
This is needed in order to stop bad mutations from overloading the cluster.
=> fix(admin): Allow KILL MUTATION commands in sudo mode

snuba/datasets/configuration/issues/storages/search_issues.yaml
Realized that the allocation policy was active but not enforced, so making it enforced here.
=> ref(lw-deletes): enforce ratelimiter

snuba/manual_jobs/scrub_ips_from_spans_dictionary.py, tests/manual_jobs/test_scrub_ips_from_spans_dict.py
Instead of storing the massive list of project ids in the query ast, store it in a dictionary table on the cluster. 
This PR also actually tests the scrubbing logic to make sure it's correct
=> feat(inc-984): store project ids list in dictionary in scrub job

snuba/lw_deletions/strategy.py
Ran into `InvalidTenantsForAllocationPolicy` because I wasn't passing in a `project_id` or an `organization_id`
Used `project_id` since that is what I had specified in the storage definition https://github.com/getsentry/snuba/blob/90a2d471ec64dafe282b406452f5791ed5893123/snuba/datasets/configuration/issues/storages/search_issues.yaml#L97
FIXES [SNUBA-6H4](https://sentry.sentry.io/issues/6147044083/?project=300688)
=> ref(lw-deletes): concurrent allocation policy requires org id

snuba/web/rpc/common/aggregation.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series_extrapolation.py
Also updating the count column to use sign
Closes https://github.com/getsentry/eap-planning/issues/133
=> feat(eap): Use weighted average instead of simple average for calculating average sampling rate

snuba/admin/clickhouse/system_queries.py, tests/admin/test_system_queries.py
These queries sometimes have to reference table names or clusters with quotes or other special
characters.
=> fix(admin): Allow special characters in SYSTEM/OPTIMIZE queries

snuba/manual_jobs/runner.py, snuba/manual_jobs/scrub_ips_from_eap_spans.py, snuba/web/db_query.py, tests/manual_jobs/test_scrub_ips_from_eap_spans.py
doing https://github.com/getsentry/snuba/pull/6673
differences:
- changed the UPDATE query
- changed the `StorageSetKey`
- Added `test_span_is_scrubbed`
=> feat(inc-984): Cleanup EAP spans 

docs/source/clickhouse/supported_versions.rst
It was pointed out in https://github.com/getsentry/snuba/issues/6555 that our docs for supported clickhouse versions was really outdated
=> docs: update CH supported versions

snuba/datasets/configuration/issues/storages/search_issues.yaml, snuba/lw_deletions/strategy.py, snuba/web/bulk_delete_query.py, tests/web/test_bulk_delete_query.py
This PR has a couple improvements and additions to the lw delete pipeline, the main one being the killswitch for the project. 
Most storages should have the `project_id` as one of the allowed columns so the assumption right now is that they do and so the killswitch will work for that case. If we add more storages in the future that don't have that, we can update the killswitch logic. The config will be based on the storage:
`lw_deletes_killswitch_search_issues`
The killswitch is added at the API level because the moment it's produced to the consumer it's batched with other messages, most likely with other `project_id`'s. Another option would be to add another strategy step prior to the batch step that filters based on the killswitch, but I felt like not producing to the topic at all made …
=> ref(lw-deletes): add project_id killswitch and some logging

snuba/web/rpc/common/aggregation.py, snuba/web/rpc/v1/endpoint_time_series.py, snuba/web/rpc/v1/endpoint_trace_item_table.py, tests/web/rpc/test_aggregation.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series_extrapolation.py
Fixes https://github.com/getsentry/eap-planning/issues/132
=> fix(eap): Fix divide by 0 errors caused when the sample count is 0

devservices/config.yml
This adds missing label to be used by purge for clickhouse
=> fix(devservices): Add orchestrator devservices label to clickhouse

rust_snuba/rust-toolchain.toml, rust_snuba/src/consumer.rs, rust_snuba/src/metrics/global_tags.rs, rust_snuba/src/mutations/factory.rs, rust_snuba/src/processors/eap_spans.rs
Our version of Rust is severely out of date. This is not a problem but
now vscode's lsp starts to complain about it.
```
Failed to run proc-macro server from path /Users/jferge/.rustup/toolchains/1.74.1-aarch64-apple-darwin/libexec/rust-analyzer-proc-macro-srv, error: Custom { kind: Other, error: "The version of the proc-macro server (2) in your Rust toolchain is too old and no longer supported by your rust-analyzer which requiresversion 4 or higher.\nThis will prevent proc-macro expansion from working. Please consider updating your toolchain or downgrading your rust-analyzer to ensure compatibility with your current toolchain." }rust-analyzermacro-error
```
This bumps the rust version in prod as well, as the dockerfile uses this file to determine the rust version.
=> chore: Bump rust-toolchain

rust_snuba/src/consumer.rs
Previously when a consumer would crash, we would exit with 0 instead of
1.
Now the consumer either exits with 0 or 1.
=> fix(rust): Honor exit code

snuba/manual_jobs/scrub_ips_from_eap_spans.py, tests/manual_jobs/test_scrub_ips_from_eap_spans.py
the `user.ip` field is sent in the `sentry_tags` dictionary which is prefixed with `sentry` automatically in the message processor. thus, a different attribute column has to be scrubbed
=> fix(inc984): scrub the correct bucket for sentry.user.ip

snuba/manual_jobs/scrub_users_from_eap_spans.py, tests/manual_jobs/test_scrub_users_from_eap_spans.py
the ` user` field is sent in the sentry_tags dictionary which is prefixed with sentry automatically in the message processor. thus, a different attribute column has to be scrubbed
=> fix(inc984): scrub the correct bucket for sentry.user

snuba/manual_jobs/scrub_users_from_eap_spans_str_attrs.py, tests/manual_jobs/test_scrub_users_from_eap_spans_str_attrs.py
this job deletes all attributes from the `spans_str_attrs` storage if 
1. its name is`sentry.user` and its an ip 
2. or if its name is `sentry.user.ip`
https://github.com/getsentry/snuba/blob/master/snuba/datasets/configuration/events_analytics_platform/storages/spans_str_attrs.yaml
=> 984: scrub eap_spans_str_attrs

rust_snuba/src/mutations/clickhouse.rs
This test does something like this:
```
CREATE TABLE temp AS eap_spans_2_local;
INSERT INTO temp (some data)
-- irrelevant
SELECT * FROM temp
```
The problem is that eap_spans_2_local has a TTL of 90 days, so between steps 2 and 3, the data is deleted (the hardcoded timestamp is now more than 90 days old!)
This updates the timestamp used by the test to be recent, so that the data isn't TTL-d out before the test can use it.
=> fix: a test is failing on master due to current-time dependencies

snuba/web/rpc/v1/endpoint_trace_item_attribute_names.py
Solves https://github.com/getsentry/eap-planning/issues/138
=> fix: add a missing alias that was causing a warning

snuba/web/rpc/__init__.py
I believe that when internal errors happen in our RPC endpoints, its not currently logged to sentry. This is bc internal errors are caught, translated into error protobufs, and sent back as a 500 response. Since the exceptions are caught they must be logged explicitly, thats what this PR does.
extra, optional:
https://sentry.sentry.io/performance/trace/a8133bb3ddb340deb9dab4dbbf912fe4/?node=txn-7d11c149497d4bd284d4bfe0d9173608&pageEnd=2024-12-28T07%3A43%3A21.936&pageStart=2024-12-27T07%3A43%3A21.936&timestamp=1735328601.721
you can see in this error trace that sentry gets a 500 internal error from snuba, but there is no associated snuba error logged
=> feat: improve internal error logging for rpc endpoints

requirements.txt
Bumps devservices to 1.0.7
Picks up https://github.com/getsentry/devservices/releases/tag/1.0.7
=> chore(devservices): Bump devservices version to 1.0.7

rust_snuba/benches/processors.rs, rust_snuba/src/consumer.rs, rust_snuba/src/factory.rs, rust_snuba/src/strategies/clickhouse/batch.rs, snuba/cli/rust_consumer.py
depends on successful rollout of https://github.com/getsentry/ops/pull/13279
=> ref(rust): Remove unused CLI option max_bytes_before_external_group_by

requirements.txt
Bumps devservices to 1.0.8
Picks up https://github.com/getsentry/devservices/releases/tag/1.0.8
#skip-changelog
=> chore(devservices): Bump devservices to 1.0.8

snuba/web/rpc/v1/endpoint_trace_item_attribute_names.py, tests/web/rpc/v1/test_endpoint_trace_item_attribute_names.py
There is an index out of range error with filter offset when the attribute results are empty. This PR solves this bug.
The new test `test_empty_results` failed before (due to the bug), and now passes
here is the sentry issue it fixes: https://sentry.sentry.io/issues/6189483746/?project=300688&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&statsPeriod=1h&stream_index=8
and it also closes this ticket https://github.com/getsentry/eap-planning/issues/138
=> fix: bug in AttributeNames RPC endpoint, filter offset

snuba/web/rpc/common/aggregation.py, snuba/web/rpc/v1/endpoint_time_series.py, snuba/web/rpc/v1/endpoint_trace_item_table.py, tests/web/rpc/test_aggregation.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table_extrapolation.py
When extrapolating, if there's no data, we skip returning reliabilities. This is problematic as we want to line up each reliability value with the corresponding result so those arrays must be the same length. This fills it with `RELIABILITY_UNSPECIFIED`.
=> fix(eap): Ensure reliabilities are returned more consistently

snuba/admin/views.py, snuba/manual_jobs/runner.py, tests/manual_jobs/test_job_statuses.py
Currently, errors are surfaced to GCP, and Snuba Admin just displays server error. I want to surface the actual error message to Snuba Admin as well
=> feat(job-runner): surface errors to Snuba admin

rust_snuba/src/processors/errors.rs, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__events-.snap
It seems searching by parent span id in errors was broken for a long
time, but nobody noticed?
=> fix(errors): Extract parent_span_id properly

.github/workflows/ci.yml
we have had two external contributions recently:
* #6575
* #6719 
neither of the contributors can iterate properly on their changes because our CI is actually busted for PRs launched from forks
=> fix(ci): Enable third-party contributions

.github/workflows/ci.yml
followup to #6721 
It seems that by using `outputs:` in the previous step, we don't load
the image into docker but _only_ into the local filesystem. this breaks
docker push on master.
=> fix(ci): Load snuba-ci image again

snuba/web/rpc/common/aggregation.py, snuba/web/rpc/v1/endpoint_time_series.py, tests/web/rpc/test_aggregation.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series.py
Fixes https://github.com/getsentry/eap-planning/issues/144
When we perform aggregations over attributes, the function is converted into function_nameIf (e.g. countIf) which returns a default value if no rows match the condition. This means that there is no way to distinguish between an aggregate result that is 0 because it's for example a sum of values that add up to 0, and a result that is 0 because no values matched the given condition. To deal with this, we compute the number of events being aggregated even when we aren't extrapolating so we can determine if data was present or not.
=> fix(eap): fix bug with data_present

gocd/templates/bash/deploy.sh
Add uptime monitor checks consumer to the deployment script to ensure it gets deployed along with other Snuba consumers.
=> feat(uptime): Add uptime monitor checks consumer to deploy script

snuba/admin/views.py
Catching BaseException without re-raising the exception is not a good idea. this will catch KeyboardInterrupt, which in turn makes it not possible to use Ctrl-C to kill the web server.
Let's change that
=> feat(job-runner): allow `BaseException`s to terminate the program 

snuba/datasets/configuration/events_analytics_platform/storages/uptime_monitor_checks.yaml
should be `uptime_monitor_checks` for the key. aligns with how `eap_spans` works. this fixes s4s deployment error here: https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22mattrobenolt-kube%22%0Aresource.labels.location%3D%22us-west1-c%22%0Aresource.labels.cluster_name%3D%22primary%22%0Aresource.labels.namespace_name%3D%22default%22%0Aresource.labels.pod_name%3D%22snuba-uptime-results-consumer-67d755db8c-wz6c8%22%20severity%3E%3DDEFAULT;storageScope=project;pinnedLogId=2025-01-08T23:34:40.996910078Z%2Fgl78637r4sgdqea5;cursorTimestamp=2025-01-08T23:34:40.996894468Z;aroundTime=2025-01-08T23:34:40.996910078Z;duration=PT1H?hl=en&inv=1&invt=AbmVdg&project=mattrobenolt-kube
=> fix(storage): correctly name storage key

snuba/web/rpc/common/aggregation.py
In order to calculate the correct percentiles, we need to use the weighted TDigest - the current implementation uses the unweighted TDigest to calculate percentiles from all samples, but when the percentile estimate calculation is using the TDigest in the weighted variant, the system will basically mark everything as unreliable except from outliers. 
Contributes to https://github.com/getsentry/projects/issues/530
=> fix(eap): use TDigestWeighted instead of TDigest for perncetile confidence calculation

snuba/web/rpc/common/common.py, snuba/web/rpc/v1/endpoint_trace_item_attribute_names.py, snuba/web/rpc/v1/trace_item_attribute_values.py, tests/web/rpc/v1/test_endpoint_trace_item_attribute_names.py, tests/web/rpc/v1/test_trace_item_attribute_values_v1.py
https://github.com/getsentry/eap-planning/issues/115
Already did it for attribute names API, doing it for attribute values API in this PR. Also sorted attribute values alphabetically in response so filter offset can be implemented
=> Implement filter offset for attribute values API

snuba/snuba_migrations/events_analytics_platform/0021_ourlogs_attrs.py
Mergetree isn't used in production anyways, we don't need the performance optimization of having 20 buckets - this lets us map 1-1 with otel by adding int/double/string/boolean attribute buckets
=> feat(ourlogs): Simplify the buckets for logs

snuba/datasets/configuration/events_analytics_platform/storages/uptime_monitor_checks.yaml
moves uptime storage to partial in snuba -- want to start testing this in our SaaS regions.
=> chore(uptime): move uptime storage to partial

devservices/config.yml
This option should be supported as CI in sentry generally runs snuba devserver without workers. Currently, this is determined in sentry based on the `SENTRY_EVENTSTREAM` setting. This is a workaround for an issue that stems from our jumbled logic around configuration files and settings that we should discuss in the future.
=> feat(devservices): Support no workers option for containerized version of snuba

scripts/copy_tables.py, tests/test_copy_tables.py
Input  looks like this. We need to grab the path inside the string.
```
CREATE TABLE somedb.sometable (column TYPE, ...) 
ENGINE = MergeTree('/clickhouse/tables/clustername/{shard}/default/tablename', '{replica}', sign)
```
Instead of trying to grab specific classes of characters (after all, we can't know if our table names have capitals, numbers or else), we'll simply grab everything between the two single quotes.
=> fix(scripts): Grab everything in the path

snuba/manual_jobs/extract_span_data.py, snuba/utils/hashes.py, tests/manual_jobs/test_extract_span_data.py
Closes https://github.com/getsentry/eap-planning/issues/139
=> chore(eap): write script to send scrubbed data into a gcs bucket

snuba/snuba_migrations/events_analytics_platform/0022_uptime_monitors_init_v2.py
after testing and implementing regions, we want to make a few changes to https://github.com/getsentry/snuba/issues/6696
after this is merged, we can modify our strorage to use the new table, and then delete the old table. no data is being read by the UI at the moment
=> ref(uptime): rebuild uptime storage table

rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-uptime-results-UptimeMonitorChecksProcessor-snuba-uptime-results__1__failure.json.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-uptime-results-UptimeMonitorChecksProcessor-snuba-uptime-results__1__success.json.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-uptime-results-UptimeMonitorChecksProcessor-snuba-uptime-results__1__timeout.json.snap, rust_snuba/src/processors/uptime_monitor_checks.rs
since we named it `region` upstream and in the table, we can just call it so here. https://github.com/getsentry/snuba/pull/6758
=> ref(uptime): use region instead of region_slug

snuba/clickhouse/optimize/optimize.py, snuba/clickhouse/optimize/optimize_scheduler.py, tests/clickhouse/optimize/test_optimize.py
There are different expectations in the tests and application of optimize for whether UTC or local TZ times are being used. Fixing them to UTC fixes unreliable tests (at least those failing in my environment and @xurui-c )
=> fix(optimize): make tests and optimize use UTC timestamps

snuba/admin/static/clickhouse_queries/query_display.tsx, snuba/admin/static/utils/execute_button.tsx
this fixes error messaging in the system queries tool of snuba admin. as a follow up i will see if i can expand this new error messaging to the rest of the tools.
heres how it used to look
and heres how it looks now
=> fix: snuba admin system query error messaging

requirements.txt, snuba/web/rpc/__init__.py, snuba/web/rpc/v1/endpoint_get_traces.py, snuba/web/rpc/v1/endpoint_time_series.py, snuba/web/rpc/v1/endpoint_trace_item_table.py, snuba/web/rpc/v1/resolvers/R_eap_spans/resolver_time_series.py, snuba/web/rpc/v1/resolvers/R_eap_spans/resolver_trace_item_table.py, tests/web/rpc/v1/test_endpoint_get_traces.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table.py
In preparation for adding a log type, might as well do some renaming before it's being consumed anywhere.
=> chore(trace-item-types): Switch all trace_item_name references to trace_item_type

snuba/web/rpc/v1/resolvers/R_eap_spans/common/aggregation.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series_extrapolation.py
After careful consideration, this PR removes the effective sample size and replaces it with the sample size itself. The reason is that for very large sample sizes, low sample rates and highly heterogeneous sample rates, this actually causes issues in the confidence interval calculations ([see Notion for more details](https://www.notion.so/sentry/2024-12-18-Confidence-Evaluation-15e8b10e4b5d80aa89eff6579b704ca2?pvs=4)). 
This change also has a positive effect on the stability of the calculations, as there were some issues with NULL results that are not present with this version of the formula, probably caused by some divide-by-zero issues in the query for some buckets.
=> fix(eap): remove effective sample size from confidence calculation for averages

snuba/admin/static/tracing/query_display.tsx, snuba/admin/static/tracing/types.tsx, snuba/admin/views.py
Sometimes the system.query_log table doesn't exist in the environment. Right now that breaks the entire tool. Gathering profile events can also be quite slow and for long queries it can time out. Allow it to be optional in the UI
=> fix(admin): make profile events optional for trace queries

snuba/web/rpc/v1/endpoint_time_series.py, snuba/web/rpc/v1/endpoint_trace_item_table.py, tests/manual_jobs/test_scrub_ips_from_eap_spans.py, tests/manual_jobs/test_scrub_users_from_eap_spans.py, tests/manual_jobs/test_scrub_users_from_eap_spans_str_attrs.py, tests/subscriptions/test_codecs.py, tests/subscriptions/test_data.py, tests/subscriptions/test_scheduler_consumer.py, tests/subscriptions/test_subscription.py, tests/web/rpc/v1/test_create_subscription.py, tests/web/rpc/v1/test_debug_info.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series_extrapolation.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table_extrapolation.py
https://github.com/getsentry/sentry/pull/83530 made the sentry backend send trace_item_type with every request, so now we can get rid of this unspecified => span assumption
=> chore(trace-item-types): throw an error if no trace item type is specified

snuba/web/rpc/v1/resolvers/R_eap_spans/common/aggregation.py, snuba/web/rpc/v1/resolvers/R_eap_spans/resolver_trace_item_table.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table.py
This PR closes [this ticket](https://github.com/getsentry/eap-planning/issues/143)
It implements support for [this field in TraceItemTableRequest](https://github.com/getsentry/sentry-protos/blob/dc01de301c524ce75cea38750f1d5c3e6538cfcf/proto/sentry_protos/snuba/v1/endpoint_trace_item_table.proto#L40)
Aggregation filters can now be specified like [this one](https://github.com/getsentry/snuba/pull/6776/files#diff-95d7f61d81f5bafda1267a2fb8d7ea3b9368b23e34dc2d24de38fb40532f9a1dR1105-R1117)
```
AggregationFilter(
comparison_filter=AggregationComparisonFilter(
aggregation=AttributeAggregation(
aggregate=Function.FUNCTION_SUM,
key=AttributeKey(
type=AttributeKey.TYPE_FLOAT, name="my.float.field"
),
),
op=AggregationComparisonFilter.OP_GREATER_THAN,
val=350,
)
)
```
which translates to
`HAVING …
=> feat: implement aggregate filters on EndpointTraceItemTable

snuba/pipeline/stages/query_processing.py, snuba/query/query_settings.py
This was introduced to the query pipeline stage before there was a clickhouse map type. Now certain datasets in EAP do not use it. Allow it to be turned off via query pipeline.
I thought about doing this via a storage setting but it felt like more work than necessary
=> feat(eap): allow turning off subscriptable mapping in query settings

snuba/admin/static/clickhouse_queries/query_display.tsx, snuba/admin/static/utils/execute_button.tsx
this PR makes the error handling in snuba admin more robust to hopefully prevent errors messages from getting messed up in the UI as frequently.
it maintains the console error logging as backup.
* adds `_convertAnyToError` function that is responsible for converting any type object to an error object. This is the change that has most impact on the already existing messages. It replaces the logic that was in `defaultError` but is more robust.
* changes the type of `onError` property of execute button to `function(Error)` instead of `function(Any)`. this makes overriding the error handling behavior simpler to users of the button. I was the only user of this so it has no serious impacts.
=> fix: make snuba admin error messages more stable

snuba/clickhouse/http.py
I tried to test new version with ssl clickhouse fix and got an error 
```
connectionpool.py", line 1069, in _new_conn
return self.ConnectionCls(
TypeError: __init__() got an unexpected keyword argument 'verify'
```
after some investigation i found that urllib3 HTTPSConnectionPool does not have verify attr.
to reproduce just open python console and execute
```
>>> from urllib3.connectionpool import HTTPSConnectionPool
>>> pool2=HTTPSConnectionPool('......', 443, verify=False)
>>> print(pool2.request('GET', '/'))
```
to fix this need to replace verify to cert_reqs.
```
>>> pool2=HTTPSConnectionPool('....', 443, ca_certs='custom.pem', cert_reqs='REQUIRED')
>>> print(pool2.request('GET', '/').data)
b'Ok.\n'
```
also there is an replacement for verify == False
```
>>> …
```
=> fix(clickhouse): Fix crash in clickhouse client due to invalid verify parameter

rust_snuba/src/processors/uptime_monitor_checks.rs
Fixes SNUBA-6R7
Wish there was a way for snuba to auto generate a schema based on the [kafka schema type.](https://github.com/getsentry/sentry-kafka-schemas/blob/main/schemas/snuba-uptime-results.v1.schema.json) missed this when typing the message.
=> fix(uptime): duration is nullable

requirements.txt
picks up https://github.com/getsentry/devservices/releases/tag/1.0.10
=> chore(devservices): Bump devservices to 1.0.10

snuba/migrations/group_loader.py, snuba/migrations/groups.py, snuba/settings/__init__.py
CDC no longer exists:
https://github.com/getsentry/ops/pull/10334/files
=> Remove CDC from EVENTS migration group

requirements.txt
ref: https://github.com/getsentry/relay/commit/bcd37995353e916bf10612b35c08fa2f99412195
=> chore(deps): bump relay from 0.9.4 to 0.9.5

snuba/datasets/configuration/events/storages/errors_ro.yaml
Based on the [Datadog metrics](https://app.datadoghq.com/dashboard/tht-dpn-5ui/allocation-policy?fromUser=false&fullscreen_end_ts=1727203031641&fullscreen_paused=false&fullscreen_refresh_mode=sliding&fullscreen_section=overview&fullscreen_start_ts=1726598231641&fullscreen_widget=984243635966760&refresh_mode=sliding&view=spans&from_ts=1727169007884&to_ts=1727183407884&live=true) and the corresponding [Sentry error](https://sentry.sentry.io/issues/5655838252/), the `getsentry.tasks.backfill_grouping_records` referrer is hitting our 30/s rate limit pretty frequently.
We would like to increase to 60/s if okay with team. The queries that we're making are point queries, so they should not scan very much data.
=> dev(rate-limits): Increase backfill query allocation to 60 per s

.github/workflows/image.yml
The output of the build job has not been properly declared. ~Instead of
getting it to work, let's just hardcode the image, it's actually
simpler.~ It turns out that the e2e-test job does not have access to the right github.sha for some reason, probably because it doesn't check out the snuba repo?
=> hotfix(ci): Fix missing image sha output

snuba/admin/views.py, snuba/clusters/cluster.py
Sometimes in snuba admin we fail to load the cluster info because one cluster rejected a connection, as we add more clusters, the probability of this will only increase. Add a retry to the function. WIll add caching of this info later as it's not needed to be fresh fetched all the time
=> fix(admin): Make clickhouse node info more retriable

.github/workflows/image.yml
It seems that image_tag was silently empty, which causes the e2e tests
to pull snuba master for testing.
meanwhile pushing to dockerhub fails on master.
=> hotfix(ci): Set image_tag correctly (again)

snuba/web/rpc/v1/endpoint_time_series.py
Our other alerts support 2h and 4h time intervals, so for UX consistency 
we'd like to allowlist those granularities for EAP alerts
closes https://github.com/orgs/getsentry/projects/284?pane=issue&itemId=94947565
=> chore: Allow 2h and 4h granularities in timeseries RPC

snuba/datasets/processors/search_issues_processor.py, tests/datasets/test_search_issues_processor.py
In the logs of the consumer:
```
if profile.get("profile_id") is not None:
^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```
This means that the profile value was explicitly set to None in the payload. make the context handling account for that case
=> fix(inc-1013): account for explicitly None fields in contexts

snuba/web/rpc/common/common.py
if you have the following filter in your `TraceItemTableRequest`
`exists(sentry.duration_ms)`
it will get translated to `isNotNull(sentry.duration_ms)`
which causes a clickhouse error bc that column doesnt actually exists, everywhere else is is translated to `duration_ms AS sentry.duration_ms`
so this PR fixes that bug by translating these special columns properly by using the `attribute_key_to_expression` function that is used everywhere else.
honestly I dont know many internal details of this function so im slightly worried that there will be edge cases that could break things. but based on the name of the function and how i see it used elsewhere in the codebase, I will assume that if the tests pass with this change then its fine.
this bug is blocking …
=> fix: bug with translation of key in exists filter

tests/clickhouse/optimize/test_optimize_scheduler.py
The initial OptimizeScheduler instance could be created on a day's boundary. Fix the time so that the test always runs with the same parameters everytime.
Resolves https://github.com/getsentry/snuba/issues/6829.
=> chore(tests): Fix the time for optimize test

.github/workflows/ci.yml
This flag is now removed in https://github.com/getsentry/sentry/pull/84184, so removing this in all places that use it
=> chore(ci): Remove use new devservices flag

rust_snuba/src/processors/eap_spans.rs
Plan is to limit to 30 days of data while we double-write and start ingesting for GA in order to control volume of data in the cluster. We'll remove this when we're aiming for 90 days.
=> chore(eap): Cap retention to 30 days before we start ingesting for GA

snuba/web/rpc/__init__.py, tests/web/rpc/test_base.py
We need to trim the time range for the time being since we do receive queries longer than 30 days which we do not want to allow right now.
We trim to the more recent data since our product always queries for the more recent data.
We trim instead of returning an error to not break part of the UI where we can't fix querying for 90 days of data.
This is temporary and will be removed before GA.
=> chore(eap): Trim time range if going over 30 days

snuba/web/rpc/common/common.py, snuba/web/rpc/v1/resolvers/R_ourlogs/common/trace_item_filters_to_expression.py, snuba/web/rpc/v1/resolvers/R_uptime_checks/common/common.py, tests/web/rpc/v1/test_endpoint_get_traces.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series.py
https://github.com/getsentry/eap-planning/issues/127
The ticket asks for ignoring case for the values, not the keys themselves
1. equality on keys: "span.op" = "SPAN.OP" <-- we don't support this
2. equality on values: if span.op is pageload, then "pageload" = "PAGELOAD" <-- we support this
=> fix(eap-api): `equal`, `not equal`, `in`, `not in` ignoring case

snuba/web/rpc/v1/resolvers/R_uptime_checks/resolver_trace_item_table.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table_uptime_checks.py
seems like we weren't using the request offset for uptime checks. this PR fixes.
=> fix(uptime): add offset to trace item resolver for uptime checks

rust_snuba/benches/processors.rs, rust_snuba/src/config.rs, rust_snuba/src/consumer.rs, snuba/cli/rust_consumer.py, snuba/consumers/consumer_config.py
This adds the quantized rebalancing as a cli option, so it can be specified in code instead of just
in the runtime config.
=> fix(consumer): Add quantized rebalancing as cli option

requirements.txt
Some various minor improvements: https://github.com/getsentry/devservices/releases/tag/1.0.14
=> chore(devservices): Bump devservices to 1.0.14

requirements.txt, snuba/web/rpc/v1/resolvers/R_eap_spans/resolver_time_series.py, snuba/web/rpc/v1/resolvers/R_eap_spans/resolver_trace_item_table.py, snuba/web/rpc/v1/resolvers/R_ourlogs/resolver_trace_item_table.py, snuba/web/rpc/v1/resolvers/R_uptime_checks/resolver_trace_item_table.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table_extrapolation.py
This PR implements support for formulas in the TraceItemTable endpoint. It is relevant to this ticket https://github.com/orgs/getsentry/projects/284/views/1?pane=issue&itemId=85243940&issue=getsentry%7Ceap-planning%7C27
It enables queries such as `sum(my_attribute) / count(my_attribute)` which werent possible before
* the column to expression conversion logic used to take place [here](https://github.com/getsentry/snuba/pull/6844/files#diff-e1e06d7f875a7c2870cc11bc4301dd6ab9fba73263c76260452c0b3176f66110L141-L187) I extracted this logic into 2 separate new functions: `_get_reliability_context_columns` and `_column_to_expression`. (i.e. the logic stayed the same but its not inside these functions)
* I then extended `_column_to_expression` to support formulas …
=> feat: formula queries in EndpointTraceItemTable

snuba/admin/clickhouse/predefined_system_queries.py
This is helpful in cases where you want to find queries which did not succeed.
=> feat(exception-queries): Add system query to find out exception queries

snuba/web/rpc/common/common.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table.py
Separating not filters into a separate PR instead of doing it in [this one](https://github.com/getsentry/snuba/pull/6837) to allow product to use it before we merge that one
=> feat(eap): add not filter implementation

snuba/web/db_query.py, snuba/web/rpc/v1/resolvers/R_eap_spans/resolver_get_trace.py, tests/web/rpc/v1/test_endpoint_get_trace.py
Currently, if the user doesn't specify attributes to the GetTraceEndpoint, we won't return normalized fields; however, we should
https://github.com/getsentry/eap-planning/issues/187
=> fix(eap-api): return normalized fields for GetTraceEndpoint

requirements.txt
Picks up a few small tweaks: https://github.com/getsentry/devservices/releases/tag/1.0.16
=> chore(devservices): Bump devservices to 1.0.16

.github/workflows/ci.yml, Dockerfile, cloudbuild.yaml, requirements.txt, rust_snuba/Cargo.lock, rust_snuba/Cargo.toml, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__events-.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-uptime-results-UptimeMonitorChecksProcessor-snuba-uptime-results__1__failure.json.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-uptime-results-UptimeMonitorChecksProcessor-snuba-uptime-results__1__success.json.snap
primarily for new uptime failure types added in https://github.com/getsentry/sentry-kafka-schemas/pull/377
=> chore: bump sentry-kafka-schemas

snuba/snuba_migrations/events_analytics_platform/0024_remove_smart_autocomplete_values_mv.py
* Takes up too much space
* full table scan if the attribute doesn't exist
=> cleanup(smart_autocomplete): remove smart autocomplete mv

snuba/web/rpc/v1/resolvers/common/aggregation.py, snuba/web/rpc/v1/resolvers/common/trace_item_table.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table_extrapolation.py
The reliabilities array has to be the same size as the result array. In the previous method, their lengths could be different if some of the aggregations returned null. Prior to the nullity overhaul, this wasn't a concern because the aggregation couldn't be null.
=> fix(eap): reliabilities should be updated even when value is null

snuba/datasets/configuration/events/storages/errors_ro.yaml, tests/web/test_db_query.py
It has been disabled the last three days and survived peak traffic just fine. For more info see the [policy consolidation](https://www.notion.so/sentry/CapMan-Visibility-Project-c16b375ed2ee43c19cd2fa163fc93332?pvs=4#185824a1f34b4ff6b31fe1c6ea872aca) document
=> feat(capman): Remove BytesScannedWindowAllocationPolicy from errors_ro

requirements.txt, snuba/web/rpc/v1/endpoint_time_series.py, snuba/web/rpc/v1/resolvers/R_eap_spans/resolver_time_series.py, snuba/web/rpc/v1/resolvers/R_uptime_checks/resolver_time_series.py, snuba/web/rpc/v1/resolvers/common/aggregation.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series_extrapolation.py
this PR implements support for formulas in the timeseries endpoint. it closes this ticket https://github.com/getsentry/eap-planning/issues/27
major changes:
* auto-convert `TimeSeriesRequest.aggregations` to `TimeSeriesRequest.expressions`
* implement support for formula
tests:
* I have a test for a non-extrapolated formula as well as an extrapolated one
design decisions
* reliability doesnt work with formulas
* formulas dont work w uptime checks or logs
=> feat: eap support formulas in timeseries endpoint

requirements.txt, snuba/clickhouse/native.py
This will be needed to contact cluster based on ClickHouse 24.8.
https://github.com/getsentry/pypi/pull/1258
=> chore: Upgrade clickhouse-driver to 0.2.9

snuba/web/rpc/v1/resolvers/R_eap_spans/resolver_trace_item_stats.py
```
{"timestamp":"2025-02-11T19:28:14.591943Z","level":"INFO","fields":{"message":"Starting consumer for \"outcomes_raw\"","storage":"outcomes_raw"},"target":"rust_snuba::consumer"}
19:28:14 subscriptions-scheduler-executor-transactions |     from snuba.subscriptions.codecs import SubscriptionScheduledTaskEncoder
19:28:14 subscriptions-scheduler-executor-transactions |   File "/usr/src/snuba/snuba/subscriptions/codecs.py", line 13, in <module>
19:28:14 subscriptions-scheduler-executor-transactions |     from snuba.subscriptions.data import (
19:28:14 subscriptions-scheduler-executor-transactions |   File "/usr/src/snuba/snuba/subscriptions/data.py", line 60, in <module>
19:28:14 subscriptions-scheduler-executor-transactions |     from snuba.web.rpc.v1.endpoint_time_series import …
```
=> fix(eap): Bad circular import in endpoint get traces

rust_snuba/benches/processors.rs, rust_snuba/src/consumer.rs, rust_snuba/src/factory.rs, rust_snuba/src/strategies/clickhouse/batch.rs, snuba/cli/rust_consumer.py, snuba/consumers/consumer_config.py
This lets us pass a custom envoy request timeout value in the HTTP request that we send to ClickHouse for inserts. We have observed in production that Envoy made some INSERTs terminate prematurely, and this caused downstream issues as the consumer would crash and try to resubmit on a loop, screwing up the consistent insert rate
(For employees, INC-1035)
=> feat(consumer): add flag for custom envoy request timeout

snuba/datasets/storages/tags_hash_map.py, snuba/snuba_migrations/events_analytics_platform/0025_smart_autocomplete_index.py
Using a similar trick as the tags hashmap optimization, store a hash of all the keys as an array so we can look up the existence of an attribute much faster (no need for string compares), also add a bloom filter index onto that column as well.
With this trick we can add the following statement to a prewhere to speed up the query:
```
has(_str_attr_keys_hash_map, cityHash64('sentry.op'))
```
=> migrate(smart-autocomplete): Add a hashmap optimization + BF index to smart autocomplete table

docs/source/contributing/environment.rst, docs/source/getstarted.rst, docs/source/migrations/modes.rst, snuba/admin/README.md
- Updates references to `devservices` according to [the repo's](https://github.com/getsentry/devservices) original guidance - "`sentry devservices up` is deprecated. Please use `devservices up` instead."
=> chore(docs): update references to devservices

snuba/snuba_migrations/events_analytics_platform/0027_uptime_checks_add_column_in_incident.py
We'll use this to track if a check was currently in an incident so we
may group on it during our stats queries.
=> feat(uptime): Add incident_status column to uptime_monitor_checks

Brewfile
As of a few versions ago, `protoc` is required by `sentry_protos`. It can be
installed through homebrew.
=> build(rs): Add `protobuf` to brewfile

docs/source/contributing/environment.rst
The new `devservices` command does not have an `--exclude` option.
=> docs: Fix docs for running sentry tests

requirements.txt, rust_snuba/Cargo.lock, rust_snuba/Cargo.toml, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-uptime-results-UptimeMonitorChecksProcessor-snuba-uptime-results__1__failure.json.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-uptime-results-UptimeMonitorChecksProcessor-snuba-uptime-results__1__success.json.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-uptime-results-UptimeMonitorChecksProcessor-snuba-uptime-results__1__timeout.json.snap, rust_snuba/src/processors/uptime_monitor_checks.rs, snuba/datasets/configuration/events_analytics_platform/entities/uptime_checks.yaml, snuba/datasets/configuration/events_analytics_platform/storages/uptime_monitor_checks.yaml, snuba/web/rpc/v1/resolvers/R_uptime_checks/common/common.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series_uptime_checks.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table_uptime_checks.py
=> feat(uptime): Ability to ingest and query in_incident

snuba/snuba_migrations/events_analytics_platform/0028_ourlogs_v3.py
- A logs table which is like the 'spans' table but simpler.
- Each log has a UUIDv7 which is in the sort key
- Each log also has the 'attribute buckets' strategy that we use for spans, to make aggregating faster.
=> feat(ourlogs): Add a v3 table which has a UUID per-log

.github/workflows/ci.yml
This bumps the actions/cache action since the previous version is now deprecated
=> chore(ci): Bump action validate devservices config

snuba/web/rpc/v1/resolvers/common/aggregation.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table_extrapolation.py
The `reliability` flag is supposed to return the mathematical accuracy
based on the sample rate without other additional heuristics applied.
Currently, the calculation also compares the sample count with a static
threshold (count > 100) and returns _low reliability_ if the count is
below.
Going forward, any checks for a static sample count threshold will be
performed outside of the EAP.
Confidence calculation for aggregations other than AVG will be fixed in
follow-up PRs.
Requires https://github.com/getsentry/sentry/pull/85323
Ref https://github.com/getsentry/eap-planning/issues/192
=> fix(eap): Remove static sample count thresholds

tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table.py
This is an example of an implementation of the current `http_response_rate(5)` function we use in Insights.
=> chore(eap): Add an example to calculate the HTTP response rate

gocd/templates/bash/deploy.sh, rust_snuba/Cargo.lock, rust_snuba/Cargo.toml, rust_snuba/src/processors/eap_items.rs, rust_snuba/src/processors/eap_spans.rs, rust_snuba/src/processors/mod.rs, rust_snuba/src/processors/ourlogs.rs, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-ourlogs-OurlogsMessageProcessor-snuba-ourlogs__1__maximal_log.json.snap, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-ourlogs-OurlogsMessageProcessor-snuba-ourlogs__1__minimal_log.json.snap, snuba/cli/devserver.py, snuba/datasets/configuration/events_analytics_platform/storages/eap_items_log.yaml, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table_logs.py
Needs to copy the storage definition for now (gross!) - when we migrate to a single kafka topic it'll be better.
=> feat(ourlogs): Use the new items table as the storage

snuba/clickhouse/translators/snuba/mappers.py, snuba/datasets/configuration/events_analytics_platform/entities/eap_items.yaml, snuba/datasets/configuration/events_analytics_platform/entities/eap_spans.yaml, snuba/query/processors/logical/hash_bucket_functions.py, tests/clickhouse/translators/snuba/test_translation.py, tests/query/processors/test_hash_bucket_functions_processor.py
=> feat(eap-items): Use the subscriptable bucket mapper for EAP items

snuba/request/validation.py, snuba/settings/__init__.py, tests/request/test_build_request.py
We want to be able to shut off snql access to datasets so we don't have to support it anymore once the product is using the new EAP API. add this as a runtime configurable shut off switch
=> feat(eap): add ability to shut off snql access to datasets

snuba/web/rpc/v1/resolvers/R_ourlogs/resolver_trace_item_table.py
Now that trace_item_table is the union of both logs and spans, send item_type in the `WHERE` clause
=> feat(ourlogs): Add item type check to resolver

snuba/snuba_migrations/events_analytics_platform/0029_remove_smart_autocomplete_experimental.py
we can't truncate a table this large so we'll just let TTL take care of it and stop populating it
=> cleanup(smart_autocomplete): only remove dist table and mv

.github/workflows/ci.yml
Docker made their rate limits more aggressive this week, we need to auth to circumvent that issue.
=> fix(ci): Auth protoc to avoid rate limits

Dockerfile
rustup will no longer automatically install the active toolchain if it is not installed. To ensure its installation, run `rustup toolchain install` with no arguments.
https://blog.rust-lang.org/2025/03/02/Rustup-1.28.0.html
In the cloudbuild logs we see this happening which is breaking our builds
```
info: default host triple is x86_64-unknown-linux-gnu
info: skipping toolchain installation
```
=> Run rustup toolchain install explicitly

.github/workflows/image.yml, snuba/query/allocation_policies/__init__.py, snuba/query/allocation_policies/bytes_scanned_rejecting_policy.py, snuba/web/db_query.py, tests/query/allocation_policies/test_bytes_scanned_rejecting_policy.py, tests/test_snql_api.py, tests/web/test_db_query.py
Sometimes large customers complain that they get throttled because someone scans all their data and then they're locked out for 10 minutes. Not a great experience
To ease the pain, still allow their queries to go through but give them a short leash using clickhouses `max_bytes_to_read` setting
By default this will not be turned on until a human is around to monitor it
=> feat(capman): Instead of flatly rejecting heavy projects, limit their bytes scanned on the query level

.github/workflows/image.yml, snuba/snuba_migrations/events_analytics_platform/0032_sampled_storage_views.py
Create 3 materialized views for sampling the storage of eap items.
Each tier is exponentially smaller than the previous.
```
Tier 0: eap_items_1_local (entire table)
Tier 1: 1/8th
Tier 2: 1/64th
Tier 3: 1/512th
```
Table was constructed by combining the two items migration into 1 (the initial table creation and the hash columns). For the materialized views, we don't need to bother with materializing the hash columns, they are already calculated on the source table.
Locally tested by inserting some data and making sure that:
* columns are populated (including hash columns)
* sampling does happen (each tier has less data than the previous)
Resolves https://github.com/getsentry/eap-planning/issues/190
=> feat(eap): Sampled storage materialized views

snuba/datasets/configuration/events_analytics_platform/storages/eap_items.yaml, snuba/datasets/configuration/events_analytics_platform/storages/eap_items_log.yaml, snuba/datasets/configuration/events_analytics_platform/storages/eap_spans.yaml, snuba/web/rpc/v1/endpoint_get_traces.py, snuba/web/rpc/v1/resolvers/R_eap_spans/common/common.py, snuba/web/rpc/v1/resolvers/R_eap_spans/resolver_get_trace.py, tests/web/rpc/test_common.py, tests/web/rpc/v1/test_endpoint_get_traces.py
This column will transform the `trace_id` expression to:
```
(cast(replaceAll(toString(trace_id), '-', ''), 'String') AS trace_id)
```
As a result, when this is in the `PREWHERE`, it will not use the bloom filter created for the `trace_id`. Disabling this query processor will make it use the index.
=> fix(eap): Remove column processor preventing the use of an index

snuba/web/rpc/v1/resolvers/R_ourlogs/resolver_trace_item_table.py
We need to be able to paginate, this adds offset similar to the eap spans trace items table.
Fixes https://github.com/getsentry/sentry/pull/86397
=> fix(ourlogs): Logs trace item table should support offset

.github/workflows/ci.yml
We had another broken CI pipeline due to https://github.com/getsentry/snuba/pull/6932 - this ensures several more sentry tests are run on snuba changes.
=> fix(test): run more relevant sentry CI tests

.github/workflows/ci.yml
There was a lot of duplication - we run all tests in tests/sentry/snuba and tests/snuba, so nothing in there needs to be explicitly added
=> chore(tests): Clean up which sentry tests are run on snuba PRs

snuba/web/rpc/v1/resolvers/R_eap_spans/common/common.py, snuba/web/rpc/v1/resolvers/R_eap_spans/resolver_time_series.py, snuba/web/rpc/v1/resolvers/R_eap_spans/resolver_trace_item_table.py, snuba/web/rpc/v1/resolvers/R_uptime_checks/resolver_time_series.py, snuba/web/rpc/v1/resolvers/R_uptime_checks/resolver_trace_item_table.py, snuba/web/rpc/v1/resolvers/common/aggregation.py, tests/web/rpc/test_aggregation.py, tests/web/rpc/test_common.py, tests/web/rpc/v1/test_endpoint_get_trace.py, tests/web/rpc/v1/test_endpoint_get_traces.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series_extrapolation.py, tests/web/rpc/v1/test_endpoint_trace_item_attribute_names.py, tests/web/rpc/v1/test_endpoint_trace_item_stats.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table_extrapolation.py, tests/web/rpc/v1/test_trace_item_attribute_values_v1.py
This PR updates the timeseries endpoint for the eap_spans resolver to use the new eap_items table when the following conditions are met:
- the `use_eap_items_table` runtime config is set to `1`
- the start time of the query is greater than `use_eap_items_table_start_timestamp_seconds` (measured in UTC seconds)
The tests have also been updated to been run once on the eap_spans table and once on the eap_items table.
=> feat(eap): use eap_items in timeseries endpoint

snuba/clusters/storage_sets.py, snuba/datasets/configuration/groupassignee/storages/group_assignees.yaml, snuba/datasets/configuration/groupedmessage/storages/grouped_messages.yaml, snuba/settings/__init__.py, snuba/settings/settings_distributed.py, snuba/settings/settings_test_distributed_migrations.py, snuba/snuba_migrations/events/0007_groupedmessages.py, snuba/snuba_migrations/events/0008_groupassignees.py, snuba/snuba_migrations/events/0010_groupedmessages_onpremise_compatibility.py, tests/clusters/test_storage_sets.py
Simple fix for `UndefinedClickhouseCluster
StorageSetKey.CDC is not defined in the CLUSTERS setting for this environment` errors like [SNUBA-7FY](https://sentry.sentry.io/issues/6337625497/?project=300688&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D%20CDC&referrer=issue-stream&sort=date&statsPeriod=14d&stream_index=2)
The `StorageSetKey.CDC` storages are already created on the events cluster anyway, so logically it makes sense to have these storage belong to `StorageSetKey.EVENTS`. 
It also means we have a migration that removes the tables, instead of leaving the tables or having to remove them manually
=> fix: replace CDC storage set with EVENTS

gocd/templates/bash/deploy.sh
We want to simplify and move to a common "snuba" container name for all snuba deployments, this should prepare our pipelines ahead of time.
=> SRE-630: add snuba container selector for migration

gocd/templates/bash/deploy.sh
It seems the deploy.sh script syntax has changed under our feet causing #6947 to fail validation
=> Remove vector deployment again

snuba/web/rpc/v1/resolvers/R_eap_spans/common/common.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series.py
Since we don't have the `name` column anymore in `eap_items`, we need to map references to the name attribute to the `sentry.description` attribute.
=> fix(eap-items): map sentry.name to sentry.description in eap_items

.github/workflows/ci.yml
I noticed `test_distributed` in our CI has been failing sometimes due to timeout. This causes the deploy pipeline to fail needing manual intervention. This is a short-term fix that increases the timeout so this doesnt happen. Longer term we might want to see if we can reduce the time CI takes.
This change increases the timeout for `test, test_rust, test_distributed, test_distributed_migrations` from 30 minutes to 40 minutes. The only one that actually needs the increase is `test_distributed` but since theyre all together I had to do it for all of them. They run in parallel.
=> chore: increase timeout for some of the ci tests

snuba/snuba_migrations/events_analytics_platform/0035_drop_item_attrs.py
this drops the item_attrs mv for now bc it was causing inserted rows to go up a lot.
i make backwards ops the whole table again bc i feel like if i make no backwards ops it wont let me bc its not symmetric
=> feat: drop item_attrs mv

snuba/web/rpc/v1/resolvers/common/aggregation.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series_extrapolation.py
We determine reliability relative to the returned value. If the
confidence interval (CI) is 0, we're not sampling and have high
reliability. Otherwise, if the value is 0, the CI is infinitely larger
than the value, so reliability is low.
=> fix(eap): Return high reliability when sampling rate is 100%

snuba/snuba_migrations/events_analytics_platform/0036_items_attribute_table_v1.py
this recreates the materialized view from https://github.com/getsentry/snuba/pull/6943 but that one had to be reverted bc too many rows were being inserted. this should solve the issue by adding a group by.
Resolves https://github.com/getsentry/eap-planning/issues/194
=> feat: new mv for item_attrs

snuba/datasets/configuration/events_analytics_platform/entities/eap_items.yaml
Use the hash bucket mapper to allow us to use the hashmap optimization when we need to explicitly. Since we're controlling all the queries ourselves I didn't see a need to create a generic optimizer
=> fix(eap): allow hashmaps to be used in the entity

snuba/snuba_migrations/events_analytics_platform/0037_remove_items_attribute_mv_v1.py
This materialized view was found to be too expensive to be on the critical path. as such we are removing it and choosing an alternate strategy to do autocomplete queries. Only removing the MV for now, waiting for the table to go out of retention to drop it safely
=> fix(eap): remove items_attribute_mv

tests/conftest.py, tests/migrations/test_runner.py
The `runner.py` tests literally take forever to run, and a lot of this is due to the fact that running all the migrations takes about 8 seconds. I've done several things that have improved the overall time these tests take including:
* Used a simplified decorator `@custom_clickhouse_db` (_saves ~20 seconds_)
* Combined `test_run_all` and `test_reverse_all` tests (_saves ~8 seconds_)
* Removed `test_show_all_nonexistent_migration` since it's the same as `test_show_all`  (_saves ~8 seconds_)
* Simplified `test_reverse_idempotency_all` (_saves ~40 seconds_)
* Simplified `test_settings_skipped_group` (_saves ~5 seconds_)
**before changes**
```
collected 20 items
tests/migrations/test_runner.py .................... …
```
=> ref(migrations): speed up runner.py tests

tests/web/rpc/v1/test_endpoint_trace_item_details.py
The test was failing because it was using local time instead of UTC time
=> fix(eap-items): fix a failing test

snuba/environment.py
This is a follow up to getsentry/sentry#87295. Can be disabled by setting `SENTRY_SPOTLIGHT=0` env variable
=> feat: Enable Spotlight in dev mode by default

snuba/datasets/configuration/events_analytics_platform/storages/eap_items.yaml, snuba/subscriptions/scheduler_consumer.py
We want this in order to run eap_spans subscriptions from the eap_items commit log without having to switch subscription scheduler and executor topics or run a parallel processing pipeline. These are fed from the same topic (snuba-spans) and so the commit offsets/timestamps should be comparable.
This change starts pushing eap_items commits to the spans commit log topic. The scheduler consumer has logic to ignore these messages until an ops configuration change is made. We add a metric here to make sure that path is hit
=> feat(eap-spans): push eap-items commits to the commit log

snuba/subscriptions/data.py, snuba/web/rpc/proto_visitor.py, snuba/web/rpc/v1/create_subscription.py, tests/subscriptions/test_codecs.py, tests/web/rpc/test_get_expression_aggregations_visitor.py, tests/web/rpc/v1/test_create_subscription.py
recently sentry switched to sending expressions in their subscriptions request
https://github.com/getsentry/sentry/pull/87031
this caused subscriptions to break bc the pipeline didnt have support for expressions yet
https://sentry.sentry.io/issues/6431285714/?project=300688&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&stream_index=6
this pr implements support for expressions in the subscriptions pipeline.
* convert all use of aggregation to expression
* implement support for expression
=> feat: implement support for expressions in subscriptions pipeline

snuba/web/rpc/v1/resolvers/R_eap_spans/resolver_get_trace.py
We weren't hitting the bloom filter before because we weren't comparing directly against `trace_id`. This ensures that the uuid processor correctly transforms the condition.
=> fix(eap): make sure trace id bloom filter is hit

.github/workflows/image.yml, .github/workflows/release-ghcr-version-tag.yml
Similar work with these PRs:
- https://github.com/getsentry/relay/pull/4532
- https://github.com/getsentry/symbolicator/pull/1635
While also trying to provide a solution (or at least an alternative) for this issue: https://github.com/getsentry/self-hosted/issues/3593
=> feat(ci): tag GHCR image with release version

gocd/templates/bash/check-cloud-build.sh
Cutting over to the new check_cloudbuild script that doesn't rely on images anymore and instead relies on repo_name, trigger_name, sha, and branch_name.
https://linear.app/getsentry/issue/DI-629/update-snuba-to-use-new-script
=> ref(gocd): Cutting over to check_cloudbuild.py

snuba/cli/migrations.py, snuba/migrations/runner.py, tests/migrations/test_runner.py
Addresses https://github.com/getsentry/snuba/issues/6964
**New Usage**
Revert all migrations
```
snuba migrations revert --force
```
Revert all migrations, including the `MigrationGroup.SYSTEM` (aka `migrations_local/dist` table(s))
```
snuba migrations revert --include-system --force
```
Revert all migrations for a group
```
snuba migrations revert --group profile_chunks --force
```
Fake reverting all migrations for a group
```
snuba migrations revert --group profile_chunks --fake --force
```
**Notes**
* The `--include-system` is only relevant for when one wants to revert all migrations, it doesn't do anything when you revert with a specific group
* These new commands shouldn't be added to snuba admin as they are not something we really want to do in production, but more to add …
=> ref(migrations): add revert command

requirements.txt
This picks up better observability in sentry for CI runs that use devservices and adds additional information on what devservices is doing behind the scenes for `devservices up`
https://github.com/getsentry/devservices/releases/tag/1.0.18
=> chore(devservices): Bump devservices to 1.0.18

snuba/downsampled_storage_tiers.py, snuba/query/query_settings.py, snuba/utils/metrics/timer.py, snuba/web/db_query.py, snuba/web/rpc/common/debug_info.py, snuba/web/rpc/v1/resolvers/R_eap_spans/common/sampling_in_storage_util.py, snuba/web/rpc/v1/resolvers/R_eap_spans/resolver_time_series.py, snuba/web/rpc/v1/resolvers/R_eap_spans/resolver_trace_item_table.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table.py
giving my best effort to the best effort mode
Implements best effort mode according to https://github.com/getsentry/eap-planning/issues/212. Also:
1. added functionality to Timer to get the duration between 2 marks before "finishing"
2. refactored build_snuba_request (because it's the same between the time series and trace item table endpoints) to take in build_request (which is different between the endpoints)
https://github.com/getsentry/eap-planning/issues/218
=> feat(sampling-in-storage): best effort mode

snuba/migrations/operations.py, tests/migrations/test_operations.py
Addresses https://github.com/getsentry/snuba/issues/6962
A migration should only be successful if it actually runs the sql operations on the nodes for the cluster - if there are no nodes, it probably means the cluster or migration itself wasn't set up right
The exception to this is when migrations are run in single node mode (which is the setup locally) - in that case it is expected to not have any nodes for the distributed target operations
=> fix(migrations): handle missing nodes

snuba/web/rpc/v1/resolvers/R_eap_spans/common/sampling_in_storage_util.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table.py
https://github.com/getsentry/eap-planning/issues/230
=> bug(sampling-in-storage): empty config should not do storage routing

snuba/web/rpc/v1/resolvers/R_eap_spans/common/sampling_in_storage_util.py, tests/web/rpc/v1/test_sampling_in_storage_util.py
record the following things for each query:
1. The time that it took to run the query on the most downsampled tier
2. difference between estimated time and actual time it took to run the query
3. what tier the query was run on
exceptions:
preflight mode queries will not (2) or (3)recorded
=> perf(sampling-in-storage): add perf metrics

snuba/web/rpc/v1/endpoint_get_traces.py
The offset was not being passed through to the query.
=> feat(eap): Pass page token offset to get traces query

snuba/datasets/configuration/replays/storages/replays.yaml
The `group_by_overflow_mode=any` setting is causing the cluster to segfault (oopsie!)
As a bandaid, use `break`
=> hotfix(inc-1098): Increase use 'break' overflow mode for replays

snuba/utils/metrics/timer.py, snuba/web/rpc/v1/resolvers/R_eap_spans/common/sampling_in_storage_util.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table.py, tests/web/rpc/v1/test_sampling_in_storage_util.py
https://github.com/getsentry/eap-planning/issues/237
Reason for this bug: if the query gets cached and the cached result is fetched, then the timer never got the "right_before_execute" and "execute" marks.
Fix: just use the elapsed field: https://github.com/mymarilyn/clickhouse-driver/blob/8a4e7c5b99b532df2b015651d893a6f36288a22c/clickhouse_driver/result.py#L143
=> feat(sampling-in-storage): remove dependency on Timer

snuba/web/rpc/v1/resolvers/R_ourlogs/common/attribute_key_to_expression.py
We're deprecating floats in lieu of doubles, but logs is not handling the case for doubles since doubles were deprecated (instead of floats) when this was added a few months ago. 
Currently causing 500's if a user tries to filter on a non-int number on the log table page (see [SNUBA-82G](https://sentry.sentry.io/issues/6467815361/events/df8c28fcbf98437a915c6aabe2a9fe16/)).
=> fix(ourlogs): Fix doubles not being handled for logs

rust_snuba/src/processors/replays.rs
This is causing too much noise on replays consumer.
=> Handle uint overflow for segment id in replays processor

rust_snuba/benches/processors.rs, rust_snuba/src/config.rs, rust_snuba/src/factory.rs, rust_snuba/src/strategies/clickhouse/batch.rs, snuba/clusters/cluster.py, snuba/consumers/consumer_config.py
I encountered the need to use Snuba with a secure connection to ClickHouse, but it turned out that the URL for the query hardcodes the http scheme. So I added a parameter for a secure connection in the connection configuration to the Rust consumer and implemented logic to determine the required scheme (http/https) based on it.
=> Fix: Add correct clickhouse connection http scheme in rust consumer

snuba/web/rpc/v1/endpoint_trace_item_details.py, tests/web/rpc/v1/test_endpoint_trace_item_details.py
Use the now required `trace_id` field in this request so the `trace_id` is correctly promoted to the `PREWHERE` clause.
```
SELECT (toUnixTimestamp(timestamp) AS timestamp), (leftPad(lower(hex(item_id)), 32, '0') AS hex_item_id), (replaceAll(toString(trace_id), '-', '') AS trace_id), organization_id, project_id, item_type, (mapConcat(attributes_string_0, ...) AS attributes_string), (mapConcat(attributes_float_0, ...) AS attributes_float), attributes_int, attributes_bool FROM eap_items_1_local PREWHERE equals(trace_id, 'f16dd70d-80d4-47f5-ae7d-6e2048f9ea4d') WHERE in(project_id, [1]) AND equals(organization_id, 1) AND less(timestamp, toDateTime(1744054948)) AND greaterOrEquals(timestamp, toDateTime(1744041600)) AND equals(item_type, 1) AND equals(item_id, …
```
=> fix(eap): Use trace_id field in TraceItemDetails

snuba/utils/metrics/timer.py, snuba/web/db_query.py, snuba/web/rpc/v1/resolvers/R_eap_spans/common/sampling_in_storage_util.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table.py, tests/web/rpc/v1/test_sampling_in_storage_util.py
using time gave us 10s in estimation error and bc we want cost based model. More details here: https://www.notion.so/sentry/Storage-routing-V2-1ca8b10e4b5d80319620c21d32de4dc5?pvs=4
=> feat(sampling-in-storage): use bytes scanned instead of time

snuba/snuba_migrations/events/0027_add_symbolicated_in_app_column_ro.py
follow up to #7044 , added the `symbolicated_in_app` column to the `errors_ro` table as well
=> fix(sourcemaps) - Added `symbolicated_in_app` column to errors_ro

snuba/web/rpc/v1/resolvers/common/aggregation.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table_extrapolation.py
Adding back the sample count threshold only for percentile reliability.
=> feat(eap): add a sample count threshold for percentile reliability

snuba/datasets/configuration/events_analytics_platform/storages/eap_items.yaml
Time out in reality, don't rely on the clickhouse estimator
fixes:
https://sentry.sentry.io/issues/6512417860/?project=300688&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D%20transaction%3A%5BEndpointTraceItemAttributeNames__v1%2CEndpointTimeSeries__v1%2CEndpointTraceItemTable__v1%2CEndpointGetTrace__v1%5D&referrer=issue-stream&sort=date&stream_index=2
=> Set timeout_before_checking_execution speed to 0

snuba/clickhouse/native.py
Settings are crucial to understanding the actual query that ran
=> obs(snuba): add query settings to db span

snuba/web/rpc/v1/resolvers/R_eap_spans/resolver_get_trace.py, tests/web/rpc/v1/test_endpoint_get_trace.py
We were seeing errors with `dt` sometime being a string or a `datetime`. This will always for it to be a `Float64`.
=> fix(eap): Cast timestamp as a float to and then make it a datetime

snuba/web/rpc/v1/resolvers/R_eap_spans/common/sampling_in_storage_util.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table.py, tests/web/rpc/v1/test_sampling_in_storage_util.py
Based on manual QA, we see tier512 being a small amount of data for small orgs which doesn't provide a good way to extrapolate (hence why we also bump the threshold).
On top of that, we noticed the data we show until we display the result of the higher tier query is meaningfully different.
Based on this, bumping the minimal tier would make us query more data in hopes of better accuracy when estimating what higher tier to hit and also present less of a difference in the shape of the data.
https://github.com/getsentry/snuba/pull/7066#issuecomment-2798106164
=> feat(sampling-in-storage): most downsampled tier is now tier 64

snuba/datasets/configuration/events_analytics_platform/storages/eap_items_downsample_512.yaml, snuba/datasets/configuration/events_analytics_platform/storages/eap_items_downsample_64.yaml, snuba/datasets/configuration/events_analytics_platform/storages/eap_items_downsample_8.yaml
[This](https://sentry.sentry.io/explore/traces/?project=1&statsPeriod=14d) query was timing out.  Based on [trace](https://sentry.sentry.io/explore/traces/trace/8d27b6fbd8bd4f8a9b0404e1a39d82c7/?fov=0%2C39926&node=txn-46f66b11b5d84e17b3545e62bd8acc78&project=1&query=user.email%3Anar.saynorath%40sentry.io&source=traces&statsPeriod=1h&targetId=8b179c5400eb861a&timestamp=1744742365), it looks like `timeout_before_checking_execution_speed` setting didn't get applied correctly.
=> fix(eap): make query settings uniform across downsampled tiers

snuba/state/__init__.py
Randomly found this from early days of snuba. 7 years ago, we didn't have the kafka querylog and it looks like https://github.com/getsentry/snuba/blob/2dec3b082cbc07bc75fd1eff34dc99577b50fe9f/snuba/state.py#L149-L160. When the kafka change went in, the redis operation was never cleaned up.
=> Stop writing querylog to redis for no reason

snuba/settings/__init__.py, snuba/settings/settings_test.py, snuba/web/rpc/v1/resolvers/R_eap_items/routing_strategies/linear_bytes_scanned_storage_routing.py, snuba/web/rpc/v1/resolvers/R_eap_items/routing_strategies/storage_routing.py, tests/web/rpc/v1/test_storage_routing.py
Right now we don't have a good way to drill down and understand our routing decisions. spans do an okay job but are subject to sampling. This PR:
* creates a hacky entry in the querylog for every routing decision we make, it abuses the `clickhouse_queries.stats` field which accepts arbitrary JSON and the `dataset=storage_routing` field to make the requests separate
* All metrics outputted by the routing strategy are added to the payload
* Adds tests for this functionality
=> feat(sampling_in_storage): Log routing decisions to querylog

gocd/templates/bash/saas-sentry-error-check.sh, gocd/templates/pipelines/snuba.libsonnet
Errors from `de` prevent `us` from moving forward
https://github.com/getsentry/getsentry/blob/f1730f5fe687c97e3c9347175eb2aaf142583ff7/gocd/templates/bash/backend/check-sentry-errors.sh#L6
Though it seems `de` doesn't have a health check at all so maybe that's why, but perhaps we should add the health check to `de`
=> ref(gocd): filter sentry errors by US env

snuba/web/rpc/v1/resolvers/R_eap_items/routing_strategies/storage_routing.py, tests/web/rpc/v1/test_storage_routing.py
the json schema expects the hex version of UUIDs, not the `str`, fix and add a test
=> fix(storage-routing): fix querylog id generation for storage routing entries

snuba/web/rpc/v1/resolvers/R_eap_items/storage_routing/routing_strategy_selector.py, tests/web/rpc/v1/routing_strategies/test_strategy_selector.py
Allow overrides at organization level
For example
`{
"8392": {
"version": 1, 
"config": {
"LinearBytesScannedRoutingStrategy": 0.25, 
"ToyRoutingStrategy1": 0.25, 
"ToyRoutingStrategy2": 0.25, 
"ToyRoutingStrategy3": 0.25
}
},
"12": {
"version": 1, 
"config": {
"LinearBytesScannedRoutingStrategy": 0.75, 
"ToyRoutingStrategy3": 0.25
}
}
}`
This adds overrides for orgs 8392 and 12
=>  feat(storage-routing): strategy selector takes overrides

snuba/cli/consumer.py
Add a cli flag for the quantized rebalance delay so that it doesn't have to be set via the config.
=> fix: Add a cli flag for the quantized rebalance delay

snuba/web/rpc/v1/endpoint_get_traces.py
Using `LIMIT BY` was creating performance issues, using `DISTINCT` doesn't.
We need to remove the optimization with the `timestamp` values but since we have a `trace_id` bloom filter index, it shouldn't have too much impact as long as this query uses the index.
=> fix(eap): Improve performance by using a DISTINCT instead of a LIMIT BY

snuba/query/processors/physical/clickhouse_settings_override.py, tests/query/processors/test_clickhouse_settings_override.py
Allow us to ignore clickhouse override settings - going to use this to test out some clickhouse query settings in S4S for EAP cluster. This is a temporary change, but I didn't want to change the yaml config for EAP since that would affect all regions
=> ref(clickhouse-settings): ignore_clickhouse_settings_override runtime config

snuba/web/rpc/v1/endpoint_time_series.py
This is to enable anomaly detection on span alerts. Seer requires 28 days of historical data at the interval requested (smallest allowed interval is 15 minutes). We'll need `28 * 24 * 4 = 2688` buckets.
=> chore(eap): Bump _MAX_BUCKETS_IN_REQUEST to 2688

requirements.txt, snuba/web/rpc/common/debug_info.py, snuba/web/rpc/v1/resolvers/R_eap_items/storage_routing/routing_strategies/linear_bytes_scanned_storage_routing.py, snuba/web/rpc/v1/resolvers/R_eap_items/storage_routing/routing_strategies/normal_mode_linear_bytes_scanned.py, tests/web/rpc/v1/routing_strategies/test_linear_bytes_scanned.py, tests/web/rpc/v1/routing_strategies/test_normal_mode_linear_bytes_scanned.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table.py
The NORMAL query mode is 5 seconds
- EAP will route to whatever tier it needs to in order to facilitate this
- The return payload from EAP will need to inform the client if there exists a higher tier to scan, WITHOUT considering the potential of timeout if the query runs on a higher tier
- Queries on this mode should not time out
We previously had preflight mode and best_effort mode. These are now treated the same as normal mode
More details: https://www.notion.so/sentry/Storage-Routing-Alignment-1d88b10e4b5d8056b921ffd50cb31f59?pvs=4
=> feat(storage-routing): NORMAL mode

tests/web/rpc/v1/test_storage_routing.py
=> fix(storage-routing): fix flakey test

snuba/web/rpc/v1/resolvers/R_eap_items/storage_routing/routing_strategies/storage_routing.py
so that we can filter traces based on their storage routing decision
=> obs(storage_routing): set selected sampling tier on the span

snuba/web/rpc/v1/endpoint_get_traces.py
Thanks to our alias `trace_id` on the transformation of the `trace_id` column, the `PREWHERE` was not hitting the index since `trace_id` was then referring to the expression transforming the `trace_id`.
With renaming the alias to `hex_trace_id`, it now correctly looks at the column `trace_id` instead, hitting the index.
=> fix(eap): Rename an alias to improve query performance

snuba/web/rpc/v1/resolvers/R_eap_items/storage_routing/routing_strategies/linear_bytes_scanned_storage_routing.py, snuba/web/rpc/v1/resolvers/R_eap_items/storage_routing/routing_strategies/normal_mode_linear_bytes_scanned.py, tests/web/rpc/v1/routing_strategies/test_linear_bytes_scanned.py, tests/web/rpc/v1/routing_strategies/test_normal_mode_linear_bytes_scanned.py
If a query to the most downsampled tier already exceeds the bytes scanned limit, then don't re-route it
=> fix(storage-routing): most downsampled query can exceed limit

rust_snuba/src/strategies/clickhouse/batch.rs, rust_snuba/src/strategies/clickhouse/mod.rs
* add more metrics to see if it's possible that we are getting stuck waiting while the channel is empty but open
* attempt to add a timeout to joinhandle for writing to clickhouse using [tokio](https://docs.rs/tokio/1.4.0/tokio/index.html)::[time](https://docs.rs/tokio/1.4.0/tokio/time/index.html)::[timeout](https://docs.rs/tokio/1.4.0/tokio/time/fn.timeout.html)
=> ref(INC-1119): add metrics and tokio timeout

snuba/web/rpc/v1/resolvers/R_eap_items/storage_routing/routing_strategies/linear_bytes_scanned_storage_routing.py, snuba/web/rpc/v1/resolvers/R_eap_items/storage_routing/routing_strategies/normal_mode_linear_bytes_scanned.py
This was just getting overwritten in Querylog because it had the same name
=> fix(storage-routing): fix metric name

snuba/web/rpc/v1/resolvers/R_eap_items/storage_routing/routing_strategies/outcomes_based.py, snuba/web/rpc/v1/resolvers/R_eap_items/storage_routing/routing_strategies/storage_routing.py, tests/web/rpc/v1/routing_strategies/test_outcomes_based.py, tests/web/rpc/v1/test_storage_routing.py
After turning on the outcomes based strategy for all customers, we're seeing an exceeding of the time limit more than we would like 
https://app.datadoghq.com/s/FH6-Y3/889-thi-r3u
spot checking a few, it seems like the ingested items were in the tens of billions for those queries. 
Add the ability to downsample further. This can be tuned by changing the `OutcomesBasedRoutingStrategy.max_items_before_downsampling` configuration in the runtime config
=> feat(storage_routing): Use tiers lower than TIER_8 after 10 billion ingested items

snuba/datasets/configuration/events_analytics_platform/entities/eap_items.yaml
the `/tests/{dataset}/drop` endpoint drops all the storages for an entity. due to the fact that the eap_items entity does not define the downsampled storages or attribute storages as entities, it does not drop those tables, causing the data to stick around between test runs
=> fix(tests):  dataset/drop endpoint for EAP works as expected

requirements.txt, snuba/web/rpc/v1/resolvers/R_eap_items/storage_routing/routing_strategies/outcomes_based.py, snuba/web/rpc/v1/resolvers/R_eap_items/storage_routing/routing_strategies/storage_routing.py, tests/web/rpc/v1/routing_strategies/test_outcomes_based.py
Right now all queries being served by the outcomes based strategy would participate in the routing logic, but if `HIGHEST_ACCURACY` queries should bypass this logic and go straight to tier 1
=> feat(storage-routing): introduce HIGHEST_ACCURACY queries to outcomes based strategy 

snuba/datasets/configuration/discover/entities/discover.yaml, snuba/datasets/configuration/discover/entities/discover_events.yaml, snuba/query/snql/discover_entity_selection.py, tests/test_discover_api.py
after adding new column on errors `timestamp_ms`, this exposes it to be queryable in discover
=> feat(errors) - Add `timestamp_ms` to discover and discover-events entites

snuba/datasets/configuration/events_analytics_platform/storages/eap_items.yaml, snuba/datasets/configuration/events_analytics_platform/storages/eap_items_downsample_512.yaml, snuba/datasets/configuration/events_analytics_platform/storages/eap_items_downsample_64.yaml, snuba/datasets/configuration/events_analytics_platform/storages/eap_items_downsample_8.yaml, snuba/datasets/configuration/events_analytics_platform/storages/eap_items_span.yaml, snuba/web/rpc/v1/endpoint_trace_item_attribute_names.py, snuba/web/rpc/v1/resolvers/R_eap_items/storage_routing/routing_strategies/linear_bytes_scanned_storage_routing.py
**context**
The [`timeout_overflow_mode`](https://clickhouse.com/docs/operations/settings/settings#timeout_overflow_mode) setting in ClickHouse is suppose to dictate the behavior of a query if it exceeds `max_execution_time`
options for `timeout_overflow_mode`:
* `throw` which throws a `TimeoutExceeded` error (the default)
* `break` which is supposed to return partial results
Setting `timeout_overflow_mode` to break doesn't actually provide the partial results that it was assumed to return. Additionally, not only does it _not_ provide partial results, but it also is likely related to the series of `TablesStatusResponse` errors we have been seeing when testing out the newer version of ClickHouse that we want to upgrade to. 
In order to prevent possible issues when doing the rest of the …
=> ref(eap): remove timeout_overflow_mode

rust_snuba/src/processors/ourlogs.rs, rust_snuba/src/processors/snapshots/rust_snuba__processors__tests__schemas@snuba-ourlogs-OurlogsMessageProcessor-snuba-ourlogs__1__maximal_log.json.snap, tests/web/rpc/v1/test_endpoint_trace_item_details.py, tests/web/rpc/v1/test_endpoint_trace_item_stats_logs.py
In the trace items table, this is called 'parent_span_id', and it comes from the SDKs setting an attribute instead of the kafka topic.
=> fix(ourlogs): Do not store span_id

snuba/datasets/configuration/events_analytics_platform/dataset.yaml, snuba/datasets/configuration/events_analytics_platform/entities/eap_items_span.yaml, tests/datasets/test_entity_factory.py
We need to redirect the Sentry tests to write to the `eap-items-span` processor, not the future `eap-items` processor.
https://github.com/getsentry/sentry/pull/90808
https://github.com/getsentry/snuba/pull/7122
=> chore(eap): Add a eap_items_span entity for backwards compatibility

snuba/web/rpc/v1/endpoint_trace_item_attribute_names.py
Since we removed the timeout_overflow_mode=break, this is causing timeouts on large queries
=> fix(eap): Remove max execution time from attribute names endpoint

snuba/web/rpc/v1/endpoint_trace_item_attribute_names.py, tests/web/rpc/v1/test_endpoint_trace_item_attribute_names.py
When suggesting keys, we should still return the keys that are already in the filter. This is because as a user, we'd still expect that key to show up in the autocompletions. One case where this is best observed is if the filter is on a wild card and they want to narrow the search. Removing the key from the suggestions seems premature and can lead to confusion.
=> fix(trace-items): Should return keys in filter

snuba/web/rpc/v1/endpoint_time_series.py, snuba/web/rpc/v1/visitors/visitor_v2.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series.py
The main purpose of this PR was to fix a bug involving duplicate labels provided in a users request. Top level expressions have labels, additionally the nested aggregates and formulas inside the expressions also have labels. EX:
```
expression: {
label: label1
aggregate: {
label: label2
...
}
}
```
When the inner labels are duplicated across expressions it causes incorrect behavior. To see the specific bug that was fixed, see here: https://github.com/getsentry/eap-planning/issues/242
this PR resolves https://github.com/getsentry/eap-planning/issues/244
I solved this by implemented visitors on the protobuf request do the following:
1. ensure all top-level expressions have labels, if not adds a unique one. this is required for later steps.
2. remove all inner-expression labels. that is all …
=> fix: fix duplicate labels in RPC causing incorrect behavior

snuba/web/rpc/v1/resolvers/R_eap_items/resolver_trace_item_table.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_endpoint_trace_item_table.py
redoing https://github.com/getsentry/snuba/pull/7149
only add all the sort key columns to order by if the GROUP BY is empty or else we'd get error DB::Exception: Column blah is not under aggregate function and not in GROUP BY
=> feat(eap): Transform an order by on timestamp to the full sort key order to improve performance 

snuba/manual_jobs/truncate_eap_spans.py
interpolate the value of STATEMENT rather than logging STATEMENT
=> fix(job): log correct query for truncating EAP spans

snuba/web/views.py
For the items pipeline, we use Protobuf. Tests in Sentry have been sending JSON to insert into ClickHouse and whatever was received was just pushed to the processor.
Now, we need to be able to receive bytes and this PR will read data sent over as `multipart/form-data` to then insert into the processor.
=> feat(api): Support multipart/form-data to receive binary data

rust_snuba/ARCHITECTURE.md
Instead of dumping this into notion where it will inevitably disappear,
just put it next to code.
=> ref(rust-snuba): Add architecture doc

.github/dependabot.yml
Open PRs to update sentry-sdk, sentry-arroyo at once, and with at most 1
day delay. It should not actually create PRs every day because it's only
two dependencies that get released rarely.
context: we were behind a few arroyo versions. when we had to bump the arroyo version during incident response for INC-1003, we got held up on breaking changes that had been released a few days ago but not been bumped in snuba.
sentry-kafka-schemas is not there because its release speed is way too
high.
=> chore(ci): Bump sentry-related dependencies more aggressively

snuba/query/processors/physical/hexint_column_processor.py, snuba/web/rpc/v1/endpoint_trace_item_details.py, snuba/web/rpc/v1/resolvers/R_eap_spans/common/common.py, snuba/web/rpc/v1/resolvers/R_eap_spans/resolver_get_trace.py, tests/query/processors/test_hexint_column_processor.py, tests/web/rpc/v1/test_endpoint_get_trace.py
In order for the product to directly use `sentry.item_id` and not the alias `sentry.span_id`, we still need to trim the leading zeroes.
I debated making a more generic "trim item_id of the leading 0s" but i don't think i want to handle that now as it might lead to other test failures, so I just want to copy the current behavior for span IDs.
=> fix(eap): Pad to 16 or 32 depending on the size of item_id

snuba/web/rpc/v1/create_subscription.py, tests/subscriptions/test_scheduler_consumer.py, tests/web/rpc/v1/test_create_subscription.py
As part of the items pipeline rollout, we have to switch subscription schedulers to follow the `snuba-items` topic.
New consumers have been deployed and configured for `snuba-items` and we'll have to move subscriptions over from `eap_items_span` entity to `eap_items` to be able to remove the storage fully.
Once this is merged, we'll be able to regenerate the subscription caches and get rid of `eap_items_span` storage.
=> chore(eap): Double write subscriptions under both eap_items and eap_items_span entities

snuba/utils/profiler.py
This small PR resolves the annoying deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
=> fix: resolve logger warnings

snuba/datasets/configuration/profiles/storages/chunks.yaml, snuba/migrations/groups.py
This feature was released to `self-hosted` without the storage marked as complete.
=> fix(profiles): Set profile chunk storage as complete

snuba/snuba_migrations/events/0029_add_sample_weight_column_to_errors.py
This field will contain the result of 1/sample_rate on error events which are sampled, and will then be summed up to reach the extrapolated count of events.
context: https://www.notion.so/sentry/Tech-Spec-Error-Up-Sampling-1e58b10e4b5d80af855cf3b992f75894?pvs=4
=> feat(error-sampling): Add `sample_weight` column to errors

snuba/web/rpc/v1/endpoint_time_series.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series.py
the feature flag `enable_clear_labels_eap` was added in this PR https://github.com/getsentry/snuba/pull/7139
it has been enabled and running in prod for a few weeks with no issue, so im removing the feature flag.
=> chore: remove feature flag enable_clear_labels_eap

snuba/snuba_migrations/events_analytics_platform/0042_remove_hashed_columns.py
Instead of reverting the migration, we should reduce its impact and not drop all the columns in it.
This will let the migration go through more easily and be marked as complete and we'll have a working system in all regions again even if some columns might already be dropped.
We can then address this in additional migrations.
=> fix(eap): Reduce impact of migration

rust_snuba/src/consumer.rs, rust_snuba/src/factory_v2.rs, rust_snuba/src/lib.rs, snuba/cli/rust_consumer.py
Create a copy of the snuba consumer which is selectable via command line argument. This is what will be used to experiment with new consumer implementations in production. As of now, the V2 and V1 consumers are exactly the same. 
Resolves https://linear.app/getsentry/issue/EAP-124/create-forked-snuba-consumer-implmentation
=> feat(consumers): Create V2 consumer copy

snuba/snuba_migrations/events_analytics_platform/0044_remove_hash_map_columns_0_4.py
Since the migration was taking too long, we'll only drop the first bucket to both speed up the migration and ensure it is marked as complete
=> fix(migration): only drop the first bucket to speed up the migration

requirements.txt
looks like we aren't on the latest version, so update to the latest version
=> chore(redis): update sentry-redis-tools to 0.5.0

snuba/query/allocation_policies/concurrent_rate_limit.py
The new workflow-based alerting implementation referrers should get the same treatment as the referrers in the code they're replacing.
=> feat(capman): Don't rate limit customers for workflow alert referrers

snuba/web/rpc/v1/endpoint_time_series.py
Adding an additional bucket since we have updated the product
to make queries with stable time bucket quantization and that means
we could have partial buckets at the ends of the timeseries. So we
need one extra bucket to support 15 min intervals over 28 days.
=> chore(eap-timeseries): Bump max allowed bucktes by 1 (DAIN-667)

snuba/state/cache/redis/backend.py, tests/state/test_cache.py
Previously if a cache write failed by raising an exception it would cause the entire query to fail. We want the query to succeed even if the cache write fails. This PR does that.
This is for inc-1215
=> feat: open fail for snuba cache write failures

snuba/cli/devserver.py, snuba/web/rpc/v1/create_subscription.py, snuba/web/rpc/v1/endpoint_time_series.py, tests/web/rpc/v1/test_create_subscription.py
We'd like to test log alerts in production (with flag enabled just for sentry). 
This allows us to do do so without being blocked on spans moving to the items pipeline. 
Current behaviour is `CreateSubscription` uses a single entity key agnostic of trace item type,
and currently goes to `eap_items_span`. This updates the behaviour to check if trace item type
is logs, and if so, use `eap_items`.
Subscriptions consumers and topics for eap_items [exist in prod alread](https://github.com/getsentry/ops/blob/master/k8s/services/snuba/region_overrides/us/default.yaml#L331-L334)y, so this change
should let us test log alerts in prod. 
I also tested it locally end-to-end with sentry to make sure both span and log alerts work as expected
and span subscriptions are stored in …
=> feat(logs): Add support for creating logs subscriptions

snuba/web/rpc/storage_routing/routing_strategies/storage_routing.py
We have thousands of these info messages in Sentry ([SNUBA-8YR](https://sentry.sentry.io/issues/6678392556/?project=300688&query=is%3Aunresolved&referrer=issue-stream&stream_index=0)) that don't seem to be useful
=> remove sentry logging

snuba/web/rpc/v1/endpoint_trace_item_details.py, tests/web/rpc/v1/test_endpoint_trace_item_details.py
Addresses [EAP-121](https://linear.app/getsentry/issue/EAP-121/traceitemdetails-endpoint-should-merge-attributes-without-leaving)
For `bool` and `int` attributes, we also store a `float` version in the database to simplify aggregations. When returning data to the user we should only return the original type, and ignore the float duplicate.
Waiting on https://github.com/getsentry/sentry/pull/94553 to be merged before I can merge this PR
=> fix(TraceItemsDetails): dedupe int,bool and float attrs

snuba/cli/rust_consumer.py
Rolling out to all of DE was fine, this will make the batching consumer be used everywhere
=> Use v2 consumer everywhere

.vscode/settings.json, snuba/web/rpc/v1/endpoint_trace_item_stats.py, snuba/web/rpc/v1/trace_item_attribute_values.py, tests/web/rpc/v1/test_endpoint_trace_item_stats.py, tests/web/rpc/v1/test_endpoint_trace_item_stats_logs.py
1. We have a lot of timeouts on the autocomplete endpoint which uses the main tables to suggest attribute values. We can definitely sample these queries
2. The TraceItemStats endpoint often times out (especially for large projects), so put in a special case to downgrade the storage tier for them automatically
=> feat(attributes): add sampling to autocomplete

requirements.txt, rust_snuba/Cargo.lock, rust_snuba/Cargo.toml, snuba/utils/streams/configuration_builder.py
This introduces some configuration changes as well, so
https://github.com/getsentry/arroyo/pull/423 can take effect.
arroyo was bumped to 2.25 before in an unrelated PR, and so we already
saw produce metrics from Rust, but with this PR we'll get them from
python producers as well.
=> ref(deps): Bump arroyo to 2.27.0

rust_snuba/src/processors/replays.rs
Error message now includes the event hash and the project id.  With the intent to help solve https://sentry.sentry.io/issues/5661155781/events/latest/?project=300688&query=is%3Aunresolved&referrer=latest-event&stream_index=3
=> chore(replay): Add context to error message

snuba/pipeline/stages/query_execution.py
This ends up as a Sentry error, we have about 2 millions events per 90 days and we still don't act on it.
=> chore(query): Remove warning for missing aliases

snuba/migrations/operations.py, tests/migrations/test_operations.py
Re-creation of https://github.com/getsentry/snuba/pull/6826
=> retry on zk metadata sync issue (PR 6826)

snuba/web/rpc/__init__.py, snuba/web/rpc/common/exceptions.py
When returning 400 errors to clients for invalid requests, from the RPC endpoints, we used to record all these in sentrys but its clogging the feed w irrelevant errors, so this PR stops capturing them.
=> feat: stop capturing 400 exceptions in RPC endpoints in sentry

snuba/admin/audit_log/base.py, snuba/admin/audit_log/query.py
"July 15, 2025 21:28:52 PM" as a timezone format isn't easily sortable and add an AM/PM for a 24hr clock. Use RFC3339 instead.
=> RFC3339 for audit log timestamps

docs-requirements.txt, requirements.txt
I added some changes in the sentry-python sdk that are now in https://github.com/getsentry/sentry-python/releases/tag/2.33.2 so bumping snuba's sentry-sdk version to get those changes
=> chore: bump sentry-sdk to 2.33.2

snuba/web/rpc/v1/endpoint_get_traces.py, tests/web/rpc/v1/test_endpoint_get_traces.py, tests/web/rpc/v1/test_utils.py
Implement get traces functionality for cross item queries as described here: https://www.notion.so/sentry/Cross-Item-Queries-21b8b10e4b5d804d84e0f75405bc56bc?source=copy_link#21b8b10e4b5d8074b55cf757e2965311
Closes https://linear.app/getsentry/issue/EAP-141/implement-cross-item-queries-in-the-gettraces-endpoint
=> feat(EAP): Implement cross event query support in get traces

snuba/snuba_migrations/events_analytics_platform/0045_improve_trace_id_index.py
With the current settings, the false positive rate of the `trace_id` index is 2.5%. The index size is 8GB for each replica. When we try to load a trace for the trace view, we see that it's trying to scan 4 billions rows (after dropping granules based on the index) for a trace in the Sentry organization.
By tweaking the false positive rate to something very small, we see the amount of granules drop significantly, the number of rows scanned drop a lot and the size of index increases to 20GB only.
This would speed up selecting items for a given trace ID in projects ingesting a lot of data.
=> feat(eap): Improve trace_id index performance

snuba/web/rpc/v1/resolvers/R_eap_items/resolver_time_series.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series.py
Without the existence check on subscriptable references, filters on the coalesced elements will only check the first attribute as it'll default to empty string and never try other attributes.
=> fix(eap): Add existence check for subscriptable references in timeseries

snuba/web/rpc/storage_routing/routing_strategies/storage_routing.py
okie so something changed  (in my sdk upgrade https://github.com/getsentry/snuba/pull/7300) so that the current span trace_id isn't always present and anyway then we hit the error
In our code `no_current_span` was the default 
```python
"trace_id": cur_span.trace_id if cur_span else "no_current_span",
```
but our tests assumes empty string
https://github.com/getsentry/snuba/blob/cf1cc65f67f46ee4b1d3c9c430e06070216e3a63/rust_snuba/src/processors/querylog.rs#L475
if you run the test with `no_current_span` as the trace_id you will see the same error we see in the InvalidMessage
> invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `n` at 1
=> fix(inc-1266): use empty trace_id

snuba/datasets/configuration/events/entities/events.yaml
We want to denormalize the `first_seen` column from the `grouped_messages` table to the `errors` table.
The purpose here is that we want to be able to sort queries on errors by the group's first-seen time.
This PR updates the error entity.
=> feat(errors): Add group_first_seen column to errors entity

snuba/snuba_migrations/events_analytics_platform/0046_add_downsampled_retention_days.py
We're adding this column to be able to ingest a specific retention for downsampled tables. We'll then modify the materialized views to use this retention value for downsampled tables.
=> feat(eap): Add a column to store downsampled retention days

snuba/datasets/table_storage.py, snuba/subscriptions/scheduler_consumer.py, snuba/utils/manage_topics.py, tests/datasets/test_table_storage.py, tests/subscriptions/test_scheduler_consumer.py
Address [EAP-167](https://linear.app/getsentry/issue/EAP-167/inc-1248-crash-subscriptions-scheduler-if-logappendtopic-is-not-found)
For subscriptions you have the following topics:
`default_topic -> commit_log_topic -> scheduled_topic -> results_topic`
The `message.timestamp.type` configuration of the original topic (the `default_topic`) being followed by the commit log topic should be set to `LogAppendTime`
This adds a check for the `LogAppendTime` topic configuration
=> ref(subscriptions): crash schedulers that dont have LogAppendTime on default topic

snuba/snuba_migrations/search_issues/0010_add_group_first_seen.py, tests/admin/test_api.py
We want to denormalize the `first_seen` column from the `grouped_messages` table to the `search_issues` table.
The purpose here is that we want to be able to sort queries on `errors` by the group's first-seen time.
This sounds similar to #7305 because it is... we discovered that the issues search uses data from both tables, so both will need the new column.
=> feat(errors): Add group_first_seen column on issues platform

snuba/datasets/configuration/issues/storages/search_issues.yaml
We want to denormalize the `first_seen` column from the `grouped_messages` table to the `search_issues` table.
The purpose here is that we want to be able to sort queries on `errors` by the group's first-seen time.
This sounds similar to #7305 because it is... we discovered that the issues search uses data from both tables, so both will need the new column.
=> feat(errors): Add group_first_seen column to issues platform storage

snuba/datasets/configuration/issues/entities/search_issues.yaml
We want to denormalize the `first_seen` column from the `grouped_messages` table to the `search_issues` table.
The purpose here is that we want to be able to sort queries on `errors` by the group's first-seen time.
This sounds similar to #7305 because it is... we discovered that the issues search uses data from both tables, so both will need the new column.
=> feat(errors): Add group_first_seen column to issues platform entity

snuba/web/rpc/storage_routing/routing_strategies/storage_routing.py, snuba/web/rpc/v1/endpoint_get_traces.py, tests/web/rpc/v1/test_endpoint_get_traces.py
We have timeouts on GetTraces for big customers. Use the sampling recommendation provided by the RPC layer in the snuba query.
=> feat(eap): enable sampling for GetTraces single item queries

docs-requirements.txt, requirements.txt
A retry of https://github.com/getsentry/snuba/pull/7300
It's still unclear what specific behavior in the sdk that changed to make `get_current_span()` not return a span when it did before in certain case but we [already fixed](https://github.com/getsentry/snuba/pull/7302) what caused the incident last time bumped the sdk
I think it's okay to bump the version again though because the missing `trace_id` that were added to the querylog payload isn't actually a trace we capture in sentry - I think the change in behavior may have to do with the way we do sampling, and how we depend on sentry to pass through the sampling decisions. 
https://github.com/getsentry/snuba/blob/8cb85e84a61027d0d1c4631f451e119fbafc4f26/snuba/environment.py#L91 …
=> chore: bump sentry-sdk to 2.33.2 again

requirements.txt, snuba/replacers/errors_replacer.py, tests/replacer/test_errors_replacer.py
This is part of an effort to fix the issue-search's sort-by-age feature. As part of that feature, we are adding the "first_seen" time of a group to each error. When we merge groups, we want to update the errors to have the new group's "group_first_seen". 
We've decided to do that by explicitly passing the primary group's "first_seen" time along with the Kafka message. This PR starts ingesting that field properly; a followup PR in the `sentry` repo will start providing that field after this has deployed everywhere.
=> fix(issues): Start processing new_group_first_seen in merge case

snuba/migrations/clickhouse.py
We are already running `25.3.6.10034` in `s4s` and some `de` clusters
=> update CLICKHOUSE_SERVER_MAX_VERSION to 25.3.6.10034

snuba/settings/__init__.py, snuba/web/rpc/v1/resolvers/R_eap_items/resolver_time_series.py, snuba/web/rpc/v1/resolvers/common/formula_reliability.py, snuba/web/rpc/v1/visitors/time_series_request_visitor.py, snuba/web/rpc/v1/visitors/trace_item_table_request_visitor.py, tests/web/rpc/v1/test_endpoint_time_series/test_endpoint_time_series_extrapolation.py
This PR enables reliabilities to be returned for formulas. The reliability of a formula is defined to be reliable iff each of its parts is reliable. ex: `(agg1 + agg2) / agg3` is reliable iff `agg1, agg2, agg3` are all reliable.
its implemented in 2 main parts
1. step 1, add the leaf nodes of a formula to the request. when a user requests `(agg1 + agg2) / agg3` we traverse this formula to also add `agg1, agg2, agg3` to the request. this is necessary to know their reliabilities are later on. they will have the labels set to `form_label.left.left, form_label.left.right, form_label.right` respectively.
2. step 2, traverse the results to find the reliabilities of the leaf nodes and use them to compute the reliability of the formula. and then afterwards remove the extra colums `agg1,agg2,agg3` …
=> feat: support reliability for formulas in timeseries endpoint

snuba/datasets/configuration/issues/entities/search_issues.yaml, snuba/datasets/configuration/issues/storages/search_issues.yaml, snuba/datasets/processors/search_issues_processor.py, tests/datasets/test_search_issues_processor.py
Follow up to https://github.com/getsentry/snuba/pull/7358. Populate the new `timestamp_ms` field on `search_issues` with `client_timestamp`, which is the canonical timestamp for `search_issues` https://github.com/getsentry/snuba/blob/32b9536c2d01b8e40fbbe4c8de4684d5b698c05e/snuba/datasets/configuration/issues/entities/search_issues.yaml#L84-L89
`timestamp_ms` copies `client_timestamp` exactly, since the messages themselves have timestamps with millisecond precision, but the column is Datetime64 with more precision and won't be truncated by clickhouse.
=> feat(search_issues): populate `timestamp_ms` on `search_issues`

snuba/snuba_migrations/outcomes/0009_outcomes_daily_table.py
The outcomes table is used as part of our routing strategy to determine when to query downsampled data. Now that we are making the move to increase the retention of our data, we'll want to be able to query more than 90 days worth of outcomes to route data accordingly. 
The outcomes hourly table in US has about 2GB worth of data per partition (it's actually a bit less), and we partition by week. So assuming we increased the TTL on that table to 13 months, thats 56 weeks.
```
56 weeks * 2GB = 112GB
```
And with the daily table that should cut down even more since we'll be rolling up by day, not hour
```
112GB / 24 = ~5GB
```
Even if these numbers are slightly off, this shouldn't add a ton of load to the outcomes cluster. And the outcomes consumers should have more than enough headroom to …
=> ref(outcomes): add daily local and mv tables

snuba/datasets/processors/search_issues_processor.py, tests/datasets/test_search_issues_processor.py, tests/test_search_issues_api.py
In https://github.com/getsentry/snuba/pull/7362, we populate `timestamp_ms` in `search_issues` by just copying the `timestamp` of the event, since the event timestamp had all the precision we needed. I had assumed that Clickhouse was the one that truncated the `timestamp` to seconds, but it turns out there's also JSONRowEncoder, which forcefully takes `datetime` objects and chops off the milliseconds: https://github.com/getsentry/snuba/blob/799e027def8bc187c3eb4353b635baee908060fc/snuba/clickhouse/http.py#L54-L55
https://github.com/getsentry/snuba/blob/7bfa538516882dc58b2bed2f3e93e87360a6719c/snuba/clickhouse/__init__.py#L1
I don't want to change DATETIME_FORMAT, since that would be very impactful to a lot of existing schemas. To work around this, we make `timestamp_ms` an actual …
=> fix(search_issues): stop truncating timestamp_ms in search_issues

.github/workflows/ci.yml
this timeout needs to be bumped to allow for venv recreation after https://github.com/getsentry/snuba/pull/7368 which invalidated venv caches in ci
2 minutes isn't enough for creating a venv from scratch (uncached)
=> fix(ci): bump timeout for venv recreation

.github/workflows/ci.yml, .github/workflows/image.yml
Redo of #7409 with another fix and from a branch of the repo (to hopefully avoid permission issues).
=> ci: bump action-build-and-push-images to latest commit hash

snuba/web/rpc/storage_routing/routing_strategies/outcomes_flex_time.py, snuba/web/rpc/v1/resolvers/R_eap_items/resolver_trace_item_table.py, tests/web/rpc/v1/test_endpoint_trace_item_table/test_trace_item_table_flex_time.py
If the time window we shrunk to doesn't have any results to show, we should not send `PageToken(offset=0)`, we should send the next window
=> fix(TraceItemTable): Account for flexible time windows with no results

snuba/utils/health_info.py
During a recent incident, the liveness check was exceeding 30s regularly, probably due to a single cluster being unreachable. This created a lot of flapping in the API, and so we want to minimize the amount that any individual cluster can affect the `/health` endpoint performance.
In this change, we use a thread pool executor and `as_completed()` to limit concurrent query node health checks to 500ms. This is more than p99 for how long the `/health` endpoint usually takes to respond. Additionally, I've added run-time config to make it 2s temporarily in our busiest environments
=> feat(health-check): add limit to individual health check cluster wait
